### ISSUE TITLE
From commands sheet apply command to previous sheet by pressing ENTER

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1001]
I have previously created a sheet (like the vd commands sheet) which lists a subset set of commands relating to the custom plugin. When in this sheet, if the user wants to apply a command on the previous sheet they are able to just press ENTER which applies this to the sheet below.

I found this to be a nice natural workflow and works nicely when you forget a rarely used command and just want to apply it there and then.

**Comment by ajkerrigan** [comment]
That's a neat idea @geekscrapy :) ! It seems tangentially related to #983, along with some other previous discussions related to making commands more explorable by context.

For the sheet you created, did you subclass the existing command sheet? I hadn't thought to do that, but it seems useful for experimenting. It seems pretty useful to be able to choose how wide to cast your net when opening a command list from a given sheet type.

**Comment by geekscrapy** [comment]
So, I have a sheet of dicts (`ListOfDictSheet`): {'command': 'description'}

When I push this commands sheet to the stack I give a kwarg to the origin sheet as `source_sheet`.

On the command sheet I then use this:

```
    def openRow(self, row):
        cmd = row['command']
        sheet = self.source_sheet
        colidx = sheet.cursorColIndex+1

        sheet.addColumnAtCursor(
            Column(f'{sheet.cursorCol.name}_{cmd}', origCol=sheet.cursorCol,
                getter=lambda c,r: self.make_lambda(c,r,cmd),
                cache="async"
            )
        )

        vd.quit(self)
        vd.push(sheet)
```

This works for my usecase and is nothing that special!

In the case of `HelpSheet` though, I think it could be done quite easily by adding an openRow function with `execCommand(inputLongname(vd.activeStack[1:]))`

**Comment by saulpw** [comment]
Hi @geekscrapy, thanks for the idea and impetus!  This makes sense to me, so I went ahead and added a new command to the HelpSheet (you could also put this in your .visidatarc to try it out):

    HelpSheet.addCommand(ENTER, 'exec-command', 'activeStack[1].execCommand(cursorRow.longname); quit(sheet)', 'execute command on undersheet')

I'm not sure if this covers all your cases, as your `openRow` does some more stuff (and I don't know what make_lambda does); let me know how this works for you.

**Comment by geekscrapy** [comment]
Nice! Yes, this works!

Might I suggest a variation of the below though? This would allow a user to see the underlying sheet if something like `capture-col` is initiated, where user input is required? This being said, visually this wont work at the moment as the helpsheet is not cleared before the command is executed so you still see the helpsheet like in #914 . But if that is sorted, this should work well.

`HelpSheet.addCommand(ENTER, 'exec-command', 'cmd=cursorRow.longname; quit(sheet); activeStack[0].execCommand(cmd)', 'execute command on undersheet')`

**Comment by saulpw** [comment]
Good idea, @geekscrapy, and done!
