### ISSUE TITLE
Command to go right by a whole screen (analogous to go-pagedown)

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#1002]
`go-pagedown` (`^F`) and `go-pageup` (`^B`) are very convenient to scroll up and down quickly.
It would be nice if similar commands could be mapped to scroll left and right quickly.

I'm not sure what the best bindings would be. My first thought was `^H` and `^L`, but these open the help sheet and redraw the screen respectively. `^→` and `^←` might work, but might upset vim users 😉.
Vim uses `zH` and `zL` for something similar.

**Comment by saulpw** [comment]
There are already the unbound `go-right-page` and `go-left-page`.  I think both `Ctrl+Right`/`Ctrl+Left` are reasonable bindings, so I added them just now.

`zH`/`zL` are already bound to `slide-left-n`/`slide-right-n`, but if they are known vim bindings for scrolling then maybe we should take advantage of that (has anyone ever used VisiData's `slide-*-n` commands, even?).

**Comment by geekscrapy** [comment]
Since you asked; nope, never used `slide-left-n`. I think you either need to know you're dataset really well (to know how many n should be) or a really wide monitor 😅

**Comment by ghost** [comment]
Thank you!
I didn't know about `slide-left-n`!
