### ISSUE TITLE
[plugins rownum] addcol-delta column changes when rows reordered

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1004]
**Small description**
`addcol-delta` does not give the correct timedelta between dates.

The below shows a correct timedelta for the first 3 rows, but changes to -1 day xxx.

![image](https://user-images.githubusercontent.com/11225502/121035977-70cb8880-c7bf-11eb-8cb7-95c56f421134.png)

I'm unsure about this, but it seems _rowindex gives a static result rather than a dynamic one based on the actual order of the row (for example if it has been sorted). This maybe another issue though.

**Comment by geekscrapy** [comment]
This is not exactly the issue, but I think it is the same vein. It's the most simple example I can provide at the moment

delta.vd
```sheet	col	row	longname	input	keystrokes	comment
global		disp_date_fmt	set-option	%Y-%m-%d %H:%M:%S		
global		clean_names	set-option	True		
			open-file	-	o	
_			unhide-cols		gv	unhide all columns
_	text		type-int		#	set type of current column to int
_	text		addcol-delta			add column with delta of current column
_	text		sort-asc		[	sort ascending by current column; replace any existing sort criteria
```

Command:
`echo -e '1\n2\n3\n6\n7\n8' |  vd --play=delta.vd`

This makes the final result as:
![image](https://user-images.githubusercontent.com/11225502/122063499-60d82800-ce01-11eb-8574-c02f726d7853.png)

Now sort the text column desc `]`, you get the following:
![image](https://user-images.githubusercontent.com/11225502/122064406-33d84500-ce02-11eb-8e19-de5dafac406f.png)

Which I'm not really sure what is happening and what the delta column is actually showing.

Now to loop back to the date part, type the `text` column to a date, and this is when you see the funky deltas. This is where my issue is I believe!

![image](https://user-images.githubusercontent.com/11225502/122064773-739f2c80-ce02-11eb-9ba4-443fffd4b8ac.png)

Side issue: I did the `unhide-cols` command at the beginning as I found I got the following error if I didn't:
```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 154, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/basesheet.py", line 66, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "addcol-delta", line 1, in <module>
    # import plugins.sparkline
  File "/Users/geekscrapy/.visidata/plugins/rownum.py", line 54, in addcol_delta
    col = sheet.visibleCols[vcolidx]
IndexError: list index out of range
```

I hope that's clearer!

**Comment by anjakefala** [comment]
> 23:09  ajkerrigan🐒 i was curious about that timedelta issue geekscrapy had. came across a piece of info that was new to me, in note 5 of the python docs about timedelta: https://docs.python.org/3/library/datetime.html#timedelta-objects
23:10  ajkerrigan🐒 "String representations of timedelta objects are normalized similarly to their internal representation. This leads to somewhat unusual results for negative timedeltas. For example: <insert sample code snippet that pretty much demos the geekscrapy issue>"

**Comment by saulpw** [comment]
This is expected (if unfortunate) behavior with the addcol-delta command as implemented.   Workaround is to freeze the delta column before altering the row order.

Fixing this would require a rework of the rownum plugin which I'm not up for at the moment.  If someone wants to put some effort into it, I'm sure it would be quite welcome for users of that plugin.

**Comment by geekscrapy** [comment]
Ok, I'll give the workaround a go.
Would it be possible to tag this as a wishlist (or a suitable alternative) though, so it's possible to track which have been closed, but not actioned? It could help with coming back to relook at it for a fix?
