### ISSUE TITLE
`view_pandas()` raises TypeError with NumPy 1.20.* and Pandas 1.0.*

### ISSUE THREAD

**Issue by flexatone** [saulpw/visidata#1005]
**Small description**

Greetings, and thanks for this excellent tool.

I discovered that with Pandas 1.0.3 and NumPy 1.20.* the `view_pandas()` fuction raises a `TypeError`. Downgrading to NumPy 1.19.*, or upgrading to Pandas 1.2.4, solves the issue.

I got this configuration from creating a fresh environment with this project's requirements.txt, where Pandas is pinned at 1.0.3. I suggest perhaps pinning the NumPy version or unpinning the Pandas version.

**Expected result**

The following opens an interactive visidata session:

```python
>>> df = pd.DataFrame([[10, 20], [30, 40]])
>>> vd.view_pandas(df)
```

**Actual result with screenshot**

```python
>>> df = pd.DataFrame([[10, 20], [30, 40]])
>>> vd.view_pandas(df)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/src/visidata/visidata/mainloop.py in run(*sheetlist)
    284         for vs in sheetlist:
--> 285             vd.push(vs)
    286 

~/src/visidata/visidata/sheets.py in push(vd, vs, pane)
   1036 
-> 1037     vs.ensureLoaded()
   1038 

~/src/visidata/visidata/basesheet.py in ensureLoaded(self)
    199             self.rows = []  # prevent auto-reload from running twice
--> 200             return self.reload()   # likely launches new thread
    201 

~/src/visidata/visidata/loaders/_pandas.py in reload(self)
    146         self.rows = DataFrameAdapter(df)
--> 147         self._selectedMask = pd.Series(False, index=df.index)
    148         if df.index.nunique() != df.shape[0]:

~/.env-visidata/lib/python3.8/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    304             else:
--> 305                 data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
    306 

~/.env-visidata/lib/python3.8/site-packages/pandas/core/construction.py in sanitize_array(data, index, dtype, copy, raise_cast_failure)
    464 
--> 465             subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
    466 

~/.env-visidata/lib/python3.8/site-packages/pandas/core/dtypes/cast.py in construct_1d_arraylike_from_scalar(value, length, dtype)
   1451 
-> 1452         subarr = np.empty(length, dtype=dtype)
   1453         subarr.fill(value)

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

During handling of the above exception, another exception occurred:

error                                     Traceback (most recent call last)
<ipython-input-11-78cfb657796e> in <module>
----> 1 vd.view_pandas(df)

~/src/visidata/visidata/loaders/_pandas.py in view_pandas(df)
    326 
    327 def view_pandas(df):
--> 328     run(PandasSheet('', source=df))
    329 
    330 

~/src/visidata/visidata/mainloop.py in run(*sheetlist)
    290         ret = vd.mainloop(scr)
    291     finally:
--> 292         curses.endwin()
    293 
    294     if ret:

error: must call initscr() first
```

**Steps to reproduce with sample data and a .vd**

Not applicable; see above.

**Additional context**

This was run from a fork on the head of the stable branch.

```python
>>> import pandas as pd
>>> import visidata as vd
>>> pd.__version__
'1.0.3'
>>> vd.__version__
'2.4'
```

**Comment by ajkerrigan** [comment]
Thanks for the report @flexatone ! Confirmed, and this appears to be a known issue (numpy/numpy#18355). Upgrading pandas seems reasonable to me - looks like anything at or above 1.0.5 would do the trick, but I'm fine unpinning barring any concerns from @anjakefala or @saulpw .

Reviewing release notes I only found a few potentially breaking changes [in 1.1.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.1.0.html#backwards-incompatible-api-changes). As far as I can tell they would not impact the pandas loader.

**Comment by anjakefala** [comment]
Hi!

Thanks everyone for starting a conversation about this. I did notice, and bumped our recommended pandas version to 1.0.5. This will be mentioned at the top of the release notes in the next VisiData release.

Thanks for looking into 1.1.0, @ajkerrigan <(^__^)>.

**Comment by flexatone** [comment]
Many thanks for addressing this issue!
