### ISSUE TITLE
vds: can't load a .vds file from stdin

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#1007]
**Small description**

`cat test.vds | vd --filetype vds` results in: `AttributeError: 'RepeatFile' object has no attribute 'readline'`.

It should instead just work(tm).

**Additional context**

Problem is present on v2.4 and on the develop branch (commit 3350d9fd8c9e64ebf409deae4b31085d12efeb7f)

**Comment by saulpw** [comment]
Thanks for the report and the PR, @pacien!
