### ISSUE TITLE
vd().input obscuring row counts?

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#101]
## Specs

- VisiData v0.99
- Python 3.6.0
- MacOS
- Terminal.app

## Observed Behavior

When running a command that calls `vd().input(...)` — e.g., `/`, `\`, `Control-s`, etc. — the input line obscures all but the 7 right-most chars of the right side of the status bar. So, e.g., `12345 rows` becomes `45 rows`, and `12345 files` becomes `5 files`.

This seems to happen regardless of the terminal size and going back to at least `v0.31` (the earliest git-tag I see in the repo).

## Example

- From the VisiData git repo, run `vd sample_data/surveys.csv`. You'll get something like this, with the right-status indicating `1134 rows`:

![screen shot 2018-01-06 at 7 56 31 pm](https://user-images.githubusercontent.com/534702/34645454-bb07c476-f31b-11e7-970e-563cc93907e5.png)

- Then, press `/`. The right-status now indicates `34 rows`, which is a bit confusing ("Did I accidentally delete a bunch of rows?":

![screen shot 2018-01-06 at 7 56 34 pm](https://user-images.githubusercontent.com/534702/34645455-bb161b70-f31b-11e7-91de-07e19426975b.png)

- If you abort the command (or execute it), the right-status goes back to indicating `1134 rows`:
 
![screen shot 2018-01-06 at 7 56 39 pm](https://user-images.githubusercontent.com/534702/34645456-bb24ead8-f31b-11e7-835e-388f542fa10c.png)

## Questions

- Do you see the same behavior?
- Is that expected?
- Is it fixable?

**Comment by saulpw** [comment]
The issue is in [VisiData._inputLine](https://github.com/saulpw/visidata/blob/stable/visidata/vdtui.py#L614), which reserves exactly 8 characters to the right of the input line.  The fix in a0e048e reserves the exact number of characters in the right status bar.  This looks neater for sure.  Thanks, @jsvine!

**Comment by jsvine** [comment]
Super, and thanks!
