### ISSUE TITLE
cmdlog: cannot reliably save command log when an encoding is set

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#1016]
**Small description**

Starting visidata with the `--encoding=latin-1` option breaks the command log export in some cases.
In my understanding of the manual page, this command line option should only affect the input codec, not the output.

**Expected result**

It should just work(tm).

**Actual result with screenshot**

```stacktrace
Traceback (most recent call last):
  File "/nix/store/zc65ylph8nmbfr24znp8h469r03v47j7-visidata-2.4/lib/python3.8/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/nix/store/zc65ylph8nmbfr24znp8h469r03v47j7-visidata-2.4/lib/python3.8/site-packages/visidata/loaders/tsv.py", line 71, in save_tsv
    fp.write(unitsep.join(dispvals.values()))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u30ad' in position 8: ordinal not in range(256)
```

**Steps to reproduce with sample data and a .vd**

Since the bug prevents exporting the `.vd` command log, here's a hand-crafted version instead:

1. `visidata --encoding=latin-1` to start the program.
2. `<Shift-S>` to open the sheets sheet.
3. `a` to add an empty line.
4. `^D` to attempt saving the command log.
5. `<enter>` to confirm the name of the command log output file.
6. The error above should appear on the status line.

**Additional context**

Version: issue affects v2.4 and the tip of the develop branch (commit 3350d9fd8c9e64ebf409deae4b31085d12efeb7f)

**Comment by saulpw** [comment]
Thanks for filing this issue, @pacien!  I went through all the usages of `open_text()` and explicitly specified `utf-8` where that is defined by the format (including VisiData internal formats), and using the sheet's option otherwise.  Should be fixed in develop.
