### ISSUE TITLE
add new column from bash expr does not respect pipes

### ISSUE THREAD

**Issue by justin2004** [saulpw/visidata#1023]
**Small description**
in a sheet with a column called AIRPORT I pressed z;
then
sh$ echo $AIRPORT | sed -e 's/INTL/INTERNATIONAL/'
but the new derived cell contains:
```
SAN ANTONIO INTL | sed -e s/INTL/INTERNATIONAL/·
```

**Expected result**
I expected the new derived cell to be:
```
SAN ANTONIO INTERNATIONAL
```

**Additional context**
Please include the version of VisiData.

my version is:
```
commit 6979e01fd0b6a12d3fa02b3ade9486157940ea8c (HEAD -> stable, origin/stable, origin/HEAD)
Author: anjakefala <anja.kefala@gmail.com>
Date:   Thu May 27 23:07:07 2021 -0700
```

**Comment by saulpw** [comment]
Thanks for the report, @justin2004!  It was a pretty straightforward fix.

**Comment by justin2004** [comment]
thanks @saulpw .

what branch can i find the fix on?

**Comment by saulpw** [comment]
Should be on develop branch now.

**Comment by justin2004** [comment]
great. it is working for me!
