### ISSUE TITLE
Command to search next column name (equivalent to `/regex n` for `c regex`)

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#1026]
If you search through rows with `/`, you can jump to the next match with `n`.
However, when searching column names with `c` there doesn't appear to be a way to jump to the next matching column name.

My intuition is that `n` should jump to the next match from the previous regex search, regardless of whether it was a row search or a column search. I'm not sure if that would confuse people though!

**Comment by anjakefala** [comment]
Thanks for the feature request @davidwales! 

Here is the previous conversation for the wishlist item: https://github.com/saulpw/visidata/issues/842 =)

I am going to close this issue for the reasons outlined in that conversation.

**Comment by ghost** [comment]
Thanks! I missed that when I searched for previous issues!
