### ISSUE TITLE
[chooser] replace fancy chooser with modal dialog

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#1027]
The fancy chooser was an attempt to provide a helpful interface for multiple-choice input prompts, specifically jointype and aggregators.  It used splitwin to put the fancy chooser in the 'other' pane, keeping the main data visible while choosing, and since it's just a regular sheet, all VisiData commands are available.  Clever, right?  Except:

- in order to "wait" on the input before proceeding with the command, it creates a nested vd instance, which is non-obvious and has some unfortunate behavior (e.g. try `gq` vs `Ctrl+Q` while in the chooser);
- the fancy chooser is incompatible with replay #914 
- undo and redo don't work on the chooser #866 
- easy shortcuts can't be used as they conflict with other keybindings
- it can obscure the main sheet #941 

and there are enough other issues, that it's not worth it to keep this mechanism for the modest usability improvement it grants.

However it's important to have a selection mechanism beyond the non-fancy-chooser interface, which previously showed all options on the status line, and now just shows the number of options and offers `Ctrl+X` to open the fancy chooser.  This is not very usable.

So, we need a new selection mechanism, which should:

- be obviously modal
- include helpstrings for all choices
- allow shortcuts that are ideally completely compatible with the non-visual interface (i.e. you can type `sum<Enter>` the same in the interface as otherwise)
- allow multiple or single selection
- show a prompt while waiting for selection #889 
- handle multiple consecutive choices #905 

I'm closing the issues listed above, since they won't be addressed individually, but will hopefully be handled with a better chooser that is a simple modal dialog, which doesn't reuse the existing VisiData sheet.

**Comment by saulpw** [comment]
Okay, so I repurposed the command palette for chooseAggregator and chooseJointype.  There are only a couple of remaining uses of `chooseOne` but they are fairly minor (theme chooser, signal chooser for the procmgr, ibis sidebar chooser).  The palette has been improved/changed in a couple of subtle ways, too:

- if there aren't enough matches, the palette is filled out with your "favorite" commands, as measured by how much you've used them this session (could be saved in the future);
- you can select multiple aggregators and they append to the list (and are removed from the palette list)
- input-specific help is shown in the sidebar if disp_help == 1
- the intra-string match highlight color is now `options.color_match` (red in the default theme)

With quick-select on the 0-9 number keys, you currently can't type options with numbers in them, e.g. the `q3` aggregator.  Also the individual percentile aggregators (e.g. `p10`) are removed from the aggregator choices; now you can only choose their whole quartile group (e.g. `q10`).

This and a few cosmetic issues aside, I believe this palette mechanism should be sufficient to replace the fancy chooser, so I'm going to close this issue for now.  Please let me know how you like this new choosing mechanism, and open new issues for anything that needs to be changed.

**Comment by frosencrantz** [comment]
Looks great.  I tried looking for bugs.  I've only found one in debug mode:  `m` is not defined:

 https://github.com/saulpw/visidata/blob/develop/visidata/features/cmdpalette.py#L122-L125

**Comment by saulpw** [comment]
Thanks @frosencrantz, fixed now!
