### ISSUE TITLE
[ErrorSheet] cannot use personal command syscopy-col

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1030]
**Small description**
If you open an ErrorSheet and attempt to do `syscopy-col` you get an error.

**Expected result**
Copy the contents of the error column to the system clipboard.

**Error**
```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/loaders/tsv.py", line 67, in save_tsv
    colhdr = unitsep.join(col.name.translate(trdict) for col in vs.visibleCols) + options.row_delimiter
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/extensible.py", line 88, in call_if_not
    return func(self, *args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 405, in visibleCols
    return self.keyCols + [c for c in self.columns if not c.hidden and not c.keycol]
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/extensible.py", line 88, in call_if_not
    return func(self, *args, **kwargs)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/sheets.py", line 420, in keyCols
    return sorted([c for c in self.columns if c.keycol and not c.hidden], key=lambda c:c.keycol)
TypeError: 'Column' object is not iterable
```

**Additional context**
Current workaround is to use `syscopy-cells`
vd commit: 911f15e52560bab8e751ade98050bbf98b0424e9

**Comment by saulpw** [comment]
I don't see a `syscopy-col` command; is this a command from your .visidatarc or a plugin?

**Comment by geekscrapy** [comment]
🥴  Yes, you are correct.... You can blame @ajkerrigan for sharing these extremely useful command a while ago and I've used them so much ever since that I thought they were baked in... Thanks again @ajkerrigan !!!

`Sheet.addCommand(None, 'syscopy-col', 'syscopyCells(cursorCol, rows)', 'yank (copy) current column values to system clipboard (using options.clipboard_copy_cmd)')`

`Sheet.addCommand(None, 'syscopy-col-unique', 'clipboard().copy("\\n".join(set(c.getDisplayValue(r) for r,c in zip(sheet.rows, len(sheet.rows)*[cursorCol] )))); status(f"copied {cursorCol.name} unique values to system clipboard")', 'yank (copy) current column values to system clipboard (using options.clipboard_copy_cmd)')`

While we are here I'll explain why they are useful to me instead of syscopy-cells...

I will often use `select` to highlight a number of rows which I find interesting. In some cases selecting them means nothing more to track and highlight them visually while I use vd to sort/reorder/manipulate the sheet/rows.
Sometimes I want to just copy the whole column during analysis, amybe to pipe into a new vd session or another tool. Using `syscopy-cells` would mean I have to do a `gs` selecting all the rows losing my selections, what `syscopy-col` does for me is it allows me to get the data without loosing the selections, and `syscopy-col-uniq` is self explanatory.

So, if I may turn this into a feature request and forget that I ever reported it as a bug, would be great 😅

**Comment by geekscrapy** [comment]
Aaaand now it is fixed by adding cursorCol as a list 

Sheet.addCommand(None, 'syscopy-col', 'syscopyCells(**[**cursorCol**]**, rows)', 'yank (copy) current column values to system clipboard (using options.clipboard_copy_cmd)')

However the `-uniq` doesn't seem to work still, but this is a different error: `TypeError: 'module' object is not callable`

**Comment by saulpw** [comment]
> However the -uniq doesn't seem to work still, but this is a different error: TypeError: 'module' object is not callable

Try using `sheet.cursorCol` instead.  There's a known issue with using "local" variables within list comprehensions and generator expressions, so inside those you have to qualify them explicitly.
