### ISSUE TITLE
[command history] put reused command at the top of the command stack

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1033]
If you reuse input from the input history for a command I'd love to see that be placed as the most recent command in the stack (just press up once). At the moment if I use a command that was position 5 (I press `up` 5 times to get to it), then press `ENTER` to use it; if I want to use it again I would have to press up multiple times to find it again. I would prefer the last input used is always at the top of the stack.

**Comment by saulpw** [comment]
Good idea, thanks @geekscrapy!  This has been added and will be in the next release.
