### ISSUE TITLE
Long sheet names prevent 'quit-sheet' input being shown

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1035]
**Small description**
If a sheet is modified, when `quit-sheet` is used the user is asked if they really want to close the sheet. This is normally fine, but if you have a long sheet name the prompt is not visible. Long sheet names often occur with joined/concatted sheets.

**Expected result**
To be able to see the user input to confirm the closure. E.g. y/n input

Appreciate this maybe fixed with a modal input thats coming 👍

**Comment by anjakefala** [comment]
Ack. Yes, agreed, I think this would be fixed most neatly by a modal input. Do you know what the length of sheetname is that starts to cover things up? Maybe we can include that in the docs.

**Comment by geekscrapy** [comment]
Depends on the terminal size 😉

**Comment by geekscrapy** [comment]
You or @saulpw are probably doing this already, but maybe this could be added to the "nice things the new modal does by default" list?

Kind of a test list / usability list for the modal

**Comment by anjakefala** [comment]
This has been resolved by the new confirmation box since v2.9!
