### ISSUE TITLE
Limit use of quit-sheet protection

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1037]
I just updated to #911f15e52560bab8e751ade98050bbf98b0424e9 and noticed the behaviour of quit-sheet affects sheets that have been opened from freqsheet but not modified.

Process:
1. freq-col a column
2. dive into a row
3. quit with `q`

At this point, it asks if you want to really want to 'quit modified sheet'. Since no modifications have actually been made I find this prompt odd and not required.

I think this is a really great feature though!

**Comment by anjakefala** [comment]
![Unfortunately, I was unable to reproduce. =(](https://user-images.githubusercontent.com/7489659/124376637-d430c500-dc5c-11eb-8e17-9ee5df45ab2a.gif)

Can you upload a gif or give me anymore information?

**Comment by anjakefala** [comment]
Feedback from @jsvine on inconsistencies:
- Adding a blank row does count, but adding a blank column (via za/addcol-new) does not.
 - Editing a row cell does count as modification but editing a column name doesn't.
- Adding a column via `i` does count, but adding a column via addcol-expr, split-col, expand-col, etc. does not.

**Comment by geekscrapy** [comment]
> ![Unfortunately, I was unable to reproduce. =(](https://user-images.githubusercontent.com/7489659/124376637-d430c500-dc5c-11eb-8e17-9ee5df45ab2a.gif)
> 
> Can you upload a gif or give me anymore information?

Hmm, I'll take a look today, but I have quit guard on if that helps?

**Comment by geekscrapy** [comment]
Ok! Reproducible (for me 😅 )

1. Open any sheet
2. freq-col
3. dive into a group
4. delete a row (this new sheet is now modified)
5. freq-col on this new sheet
6. dive into one of these groups
7. now (try) quit this sheet

![quit](https://user-images.githubusercontent.com/11225502/124465822-e9b20600-dda6-11eb-91b9-9e4f98da44ee.gif)

**Comment by saulpw** [comment]
Great repro, @geekscrapy.  If you deleted rows from the source sheet, you'd want it to confirm quit, right?  But if you delete rows from a sub-sheet like this, you don't.  And I'm guessing if you deleted them from the freq table you wouldn't either.  So is it that we only want to enforce this quitguard on "source sheets" (sheets with a Path as their source, I'm thinking)?

**Comment by geekscrapy** [comment]
Hmm, I'd expect that modifications made to _any_ sheet to be confirmed. A few examples:
0. I open a CSV: no confirmation req
1. I open a CSV, delete a row: confirmation req
2. Number 0., freq a col: no confirmation req to close freq sheet
3. Number 2. + I delete a row in the freq sheet: confirmation req
4. Number 1., freq a col: no confirmation req to close freq sheet
5. Number 4., delete a row (on freq sheet): confirmation req
6. Number 5., dive a row: no confirmation req

I hope this is ok to follow!

Point 6 is really what we're talking about. I expect any subsheets to be protected as well, doesn't matter the source.

For me, a subsheet could be the work I want to save. I often do a quick freq sheet of a main column in my source sheet, and then work from there, modifing the dived subsheet until I'm happy then (eventually) rolling back to the original freq sheet to choose another row to analyse. I can often be several sheets deep (from the main freq sheet) and if the sheets are not easily reproducible (i.e. dive able from their parent sheet), and are modified, I need them protected

**Comment by saulpw** [comment]
Oh! I see.  The bug here is that copied sheets inherit their parent's `modified` flag.  Yes, we will definitely fix that.

But what about the other use cases mentioned?  Should changing a column type mark it as modified?  What if it gets changed back (without undo)?  Should hiding a column count as a modification?

**Comment by geekscrapy** [comment]
Ha, yea I appreciated that I limited my example to one tiny modification...

If something if changed back with undo, and it is basically the original sheet again, I'd suggest no confirmation is required. As for the other examples I think there needs to be a hard and fast rule that yes, any modification flips the flag (unless undo changes it back). Specifically if the user changes it back manually, no, I'd still consider this changed as it hasn't been reverted with the undo function.

How does something like word/excel/sublime work? It considers anything you do a modification, even if it looks the same as the original.

Just a thought, a mechanism that could aid with this could be an undo list for the current sheet? Like the undo button in word it gives you a list of the undoable options which basically show all the changes to the sheet and you can select the historical point of interest you want to go back to. Thinking about it, I guess this is a combination of the `D` sheet and the undo feature! Could these be more combined on a sheet level now undo is a thing?

**Comment by saulpw** [comment]
> Just a thought, a mechanism that could aid with this could be an undo list for the current sheet? Like the undo button in word it gives you a list of the undoable options which basically show all the changes to the sheet and you can select the historical point of interest you want to go back to. Thinking about it, I guess this is a combination of the D sheet and the undo feature! Could these be more combined on a sheet level now undo is a thing?

So, the undo mechanism is actually tied to the cmdlog.  If you open the cmdlog with `Shift+D` and press `gv` to show all hidden columns, the rightmost column is `undo`, which contains the list of undo functions for that command; and `Shift+U`/undo just applies them.  So we could add like a `z Shift+U` on the cmdlog to undo that command specifically.  But it would be quite dangerous as the undos are pretty broad, for instance resetting the entire list of rows to what came before, instead of just restoring the ones that were removed in that command.

**Comment by geekscrapy** [comment]
RE the last conundrum: I would see the undo from the command log to act more like the word/excel undo. It has a list (below) and if an undo is selected that isn't the last one it will roll back all changes up to that point. Basically the --play feature, but in reverse.

For example, to get back to the text just displaying "Hello \n My name", I would select the "My Name" entry in the undo bar, and it would roll back _all_ those before it. e.g.:

![image](https://user-images.githubusercontent.com/11225502/124565126-c0e74a80-de52-11eb-9020-86bc04de5e95.png)

![image](https://user-images.githubusercontent.com/11225502/124566258-f3de0e00-de53-11eb-9fb2-b0e1c57fbd94.png)

Maybe I misunderstood the last point? I read the last sentence as the user wanted to undo just the currently selected command (so a command in the middle of the cmdlog) - no, to get back to that point, they have to undo all the previous otherwise you risk being in limbo, like you describe.

**Comment by saulpw** [comment]
@geekscrapy Let us know if you still have problems with this.

**Comment by geekscrapy** [comment]
Going back to the initial issue:

Should a fresh new unmodified `FreqTableSheet` require confirmation of quit? I do a lot of quick `FreqTableSheet`'ing and it definitely breaks my flow having to confirm quit on something I've not modified.

**Comment by anjakefala** [comment]
@geekscrapy I noticed this too, @geekscrapy! I agree. It has broken my flow in the past. I am re-opening to take a look.

**Comment by geekscrapy** [comment]
I also just noticed this when diving into a list row. Using the example below:

`echo '{"key": "string", "value": ["A", "B"]}' | vd -f json`

Now `zENTER` dive into the list in the value column. The confirmation comes when exiting the list sheet

**Comment by geekscrapy** [comment]
I just noticed `setModified()` is in `addColumn`. I presume this is the reason `FreqTableSheet` has the modified flag set?

I also just noticed, that any sheet that uses addColumn will automatically flagged as modified. I would expect addColumn to only flag as modified _after_ reload/iterload finishes, which will most likely be due to user activity. This however wouldn't work for sheets that take a long time to load (i.e. many rows) as the user can interact while the reload is happening...

Maybe another argument for addColumn to signify it is being loaded as part of the sheet load?

**Comment by saulpw** [comment]
Loaders use `addColumn()` without its index kwarg, where all user command (I believe) include an index kwarg.  So let's try basing it off that for now.

**Comment by geekscrapy** [comment]
> Loaders use `addColumn()` without its index kwarg, where all user command (I believe) include an index kwarg. So let's try basing it off that for now.

This seems reasonable, if not unexpected to a dev using `addColumn`, but fine if it is documented 👍

**Comment by geekscrapy** [comment]
> This seems reasonable, if not unexpected to a dev using `addColumn`, but fine if it is documented 👍

(I was going to add the doco, but I can't seem to find the repo...!)

**Comment by anjakefala** [comment]
It goes in the `addColumn` helpstring! Then that gets picked up by the api doc builder next release. =)

**Comment by geekscrapy** [comment]
> It goes in the `addColumn` helpstring! Then that gets picked up by the api doc builder next release. =)

Oh, nice! Should've realised this... 🤦‍♂️ Thanks both
