### ISSUE TITLE
NameError: name 'vdtui' is not defined

### ISSUE THREAD

**Issue by datamaskin** [saulpw/visidata#1041]
**Traceback (most recent call last):
  File "/usr/bin/vd", line 151, in <module>
    vdtui.status(__version_info__)
NameError: name 'vdtui' is not defined**

**vd open and display input JSON file**

**Windows WSL (Ubuntu) terminal**
No Ctrl-E

**/usr/bin/vd <somefile.json> **
vd does not start

**Additional context**
Installed today on Windows WSL Ubuntu

**Comment by anjakefala** [comment]
Hi @datamaskin!

Unfortunately, this is an environment issue on your end. =( You had an older version of VisiData installed on your system which references a module that does not exist anymore.

I would try to ensure old versions of VisiData are completely removed. That `/usr/bin/vd` contains old code.

**Comment by ldesousa** [comment]
On Ubuntu 20.04 removing the old visidata package does not solve this issue. It is necessary instead to use a different executable, e.g.:
```$ visidata my_data.csv```

**Comment by anjakefala** [comment]
Hi @ldesousa!

I would run `which vd`, and *really* make sure the full package, including the executable, was removed before installing the new version. I bet an old `vd` was still kicking around, that is how this can persist. `visidata` executable is relatively recent, and that is probably why its invocation does not look for `vdtui`.

Did you use two different package managers to install `visidata` at different points? I can imagine something like this happening in that case. =(

**Comment by anjakefala** [comment]
After chatting with a friend of mine, that ran into this issue, it seems that there is a Linux distro that comes pre-installed with a very old version of VisiData. =( This explains why we have suddenly had an influx of new people running into this.
