### ISSUE TITLE
[editline] Add incremental history search

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1044]
https://github.com/saulpw/visidata/issues/1033  recently requested ordering history in MRU form.  Thank you for adding that,  I find that useful.  

Bash and other tools have incremental history search with Ctrl-R.  It is now possible to have a lot of history in Visidata and it would be useful to be able to use search rather than  up/down keys, which is the only way to get to older history now.

It looks like it is not possible for a plugin to add a single editline command without replacing all of editline.

**Comment by saulpw** [comment]
As always, features implemented beget feature requests :)  Ultimately I can see it being very useful to have all of the features of the CLI input interface, but that's a bit out of scope for me to implement in VisiData for the time being.  @willlmcgugan is making a lot of progress on the willmcgugan/textual TUI library, and if/when the input widget surpasses VisiData's native input functionality we may want to look into using it as a drop-in replacement for people who want those extended features.

Kondo'ed for now.

**Comment by frosencrantz** [comment]
> As always, features implemented beget feature requests :)

:D 

@saulpw are you saying you are open to replace curses with https://github.com/willmcgugan/textual  ?  That sounds very exciting.  It seems like that might open up some options for a lot of exciting new features such as more fine-grained formatting, more than one split, a fuller completion system and much more.

**Comment by frosencrantz** [comment]
@saulpw got distracted by the suggestion of using willmcgugan/textual, which is very exciting.

Two other questions related to this wishlist item:
  1. Is there a way someone could easily add such a feature via a plugin without replacing all of editline?
  2. Would this wish be more appealing to you if instead of doing a search, there was a shortcut that pushed a new table with all the history entries, and way to pick/insert a row from that into the input?  Like fancy-chooser.

Also, it is possible for anyone to look at their own history file with VisiData.  I learned some things about my usage.
