### ISSUE TITLE
Batch loading does not work with +sheet-indexing

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1046]
```
>>
anjakefala:git/visidata ‹stable*›$ bin/vd sample_data/sample-sales-reps.xlsx +sample-salesv4:: -b -o foo.json


opening sample_data/sample-sales-reps.xlsx as xlsx
Traceback (most recent call last):
  File "bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/anjakefala/git/visidata/visidata/main.py", line 320, in vd_cli
    rc = main_vd()
  File "/home/anjakefala/git/visidata/visidata/main.py", line 259, in main_vd
    vd.sync(vs.ensureLoaded())
AttributeError: 'NoneType' object has no attribute 'ensureLoaded'
anjakefala:git/visidata ‹stable*›$ bin/vd sample_data/sample-sales-reps.xlsx -b -o foo.json 


opening sample_data/sample-sales-reps.xlsx as xlsx
saving 1 sheets to foo.json as json

```

**Comment by geekscrapy** [comment]
Unsure if this helps isolate this issue, but I had this same issue recently when I was trying out `-b` for the first time. I was playing with a combo of `--play`, `-b` and `field=value`. 🤷‍♂️

**Comment by anjakefala** [comment]
This bug is happening because

line 258 main.py 

```
vs = vd.getSheet(startsheet)
```

and then in `getSheet`:

```
matchingSheets = [x for x in vd.sheets if x.name == sheetname]
```

the matchingSheets is `None`, because `vd.sheets` only contains the Sheet representing the main Sheet containing a row for each Worksheet. It does not contain the Worksheets themselves, and `startsheet` is the name of those worksheets.

The last working version was `v2.-3`.

**Comment by saulpw** [comment]
I think this actually works, and the only problem is that I got the syntax slightly wrong on IRC.  The manpage lists the usage as:

    vd [options] [input ...] +toplevel:subsheet:col:row

Any of the args for the `+` "starting position" option can be omitted (meaning "current" or "first"), and so to get the named subsheet on the first (only) toplevel sheet would be:

    vd sample_data/sample-sales-reps.xlsx +:sample-salesv4:: -b -o foo.js

Only the single colon after the `+` needs to be added and then it works as intended.   `+Sheet1::` means the toplevel sheet named `Sheet1`.

I've added a warning in this case so it doesn't raise an exception.

**Comment by geekscrapy** [comment]
Firstly, thanks for the write up on this issue

In the example @anjakefala originally gave (`+sample-salesv4::`) does this particular syntax mean that the top level .xlsx file would have to be named `sample-salesv4`, rather than one of the inner sheets?

**Comment by saulpw** [comment]
Yes, exactly, and then it would go to the .xlsx index instead of one of the subsheets.  `foo:::` would go to the first subsheet of the `foo.xlsx` index sheet.
