### ISSUE TITLE
Invert the current selected rows 

### ISSUE THREAD

**Issue by tsibley** [saulpw/visidata#1051]
I'd like to be able to invert the current selection: all unselected rows would become selected and selected rows unselected.

I semi-frequently find myself diving into a dataset by bulk selecting rows of interest (by various criteria) and then examining them in a derived sheet, with aggregates, etc. When I'm done, I often pop the sheet stack back up and then want to invert the selection and examine the other partition of data, e.g. the stuff that wasn't included in what I was just looking at.

For simple cases like rows selected by `|foo`, I know I can construct the inverse by doing `gs` + `\foo`, but there is not always an easy inverse construction (because, for example, I don't recall the criteria or the original was multiple intersecting selections or I manually selected things, etc).

**Comment by anjakefala** [comment]
Hi @tsibley!

If I understood correctly, what you are asking for is doable by the command `gt`. =) It toggles the selection of all the rows on the current sheet, the selected are unselected, and the unselected are selected.

**Comment by tsibley** [comment]
@anjakefala 🤯 not sure how I missed that, as I routinely consult that section of the man page. Best guess is that I skimmed "toggle" and didn't make the connection to "invert". Thank you for pointing it out! :pray:
