### ISSUE TITLE
sqlite: saving cells that were NULL before does not work

### ISSUE THREAD

**Issue by mattenklicker** [saulpw/visidata#1052]
Assuming a sqlite db like:
`sqlite3 test.db "create table testtable(testcol real);insert into testtable values(NULL)"`

If the cell is changed with visidata from NULL to a real number saving fails:
`really change 0 values? sqlite3.OperationalError near "WHERE"`

The opposite of this "Change from NULL" was #969 (Delete to NULL). So extending
https://github.com/saulpw/visidata/blob/dfca91af3a3358dd2f07ec973554669c20885485/visidata/modify.py#L162
to
```python
return (newval is None and curval is not None) or (curval is None and newval is not None) or col.type(newval) != col.type(curval)
```
 fixes it.

**Comment by anjakefala** [comment]
Thanks for the bug report @mattenklicker!

I appreciate you including a sample test dataset to help me reproduce the problem.

**Comment by anjakefala** [comment]
Thanks @mattenklicker!

This should now be fixed on develop, and will be part of the next VisiData release. You were right that that was the best change to make.
