### ISSUE TITLE
[unfurl-col] unfurling a column with TypedWrapper halts unfurl

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1053]
**Small description**
When unfurling a column which has a TypedWrapper a sheet loading halt occurs

**Expected result**
The same response as whatever `options.unfurl_empty` would do for a row without a list.

**Actual result with screenshot**
AttributeError: 'TypedWrapper' object has no attribute 'xyz'
![unfurl](https://user-images.githubusercontent.com/11225502/126625610-ee355763-aa7d-427d-a517-abce6b84adfc.gif)

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
`echo '[{"a":1,"d":{"b":[1,2,3]}},{"a":2,"d":{"c":[1,2,3]}},{"a":3,"d":{"b":[1,2,3]}}]' | vd -f json`

```
sheet	col	row	longname	input	keystrokes	comment
			open-file	-	o	
_	d		addcol-expr	curcol['b']	=	create new column from Python expression, with column names as variables
_	curcol_b_		unfurl-col			row-wise expand current column of lists (e.g. [2]) or dicts (e.g. {3}) within that column

```

**Additional context**
v2.6dev

**Comment by anjakefala** [comment]
Thanks for making such a good report @geekscrapy! Appreciate the repro. =))

**Comment by anjakefala** [comment]
>  The same response as whatever options.unfurl_empty would do for a row without a list.

This is now on `develop`!
