### ISSUE TITLE
[expand-cols] Provide vd.warning when sample rows != number of rows in the sheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1054]
**Small description**
This issue is twofold:
1. Provide `vd.warning` when sample rows != number of rows in the sheet.
2. Change recommendation in the docs (https://www.visidata.org/docs/columns/) to something regarding the use of `options.default_sample_size` (as I presume it's used elsewhere).

> Note that by default the expansion logic will look for nested columns in up to 1,000 rows surrounding the cursor. This behavior can be controlled by adjusting expand_col_scanrows in the Options Sheet, or setting options.expand_col_scanrows in the ~/.visidatarc file.

**Comment by anjakefala** [comment]
Thanks for such a thoughtful issue, @geekscrapy!

I made a small edit in your post to change the code-block to a quotation block, so it would be a bit more easily readable. =)

**Comment by anjakefala** [comment]
I update the docs, too! Their updates will ship with the next VisiData release. =)

**Comment by geekscrapy** [comment]
I've actually been using this for a while and I think it might be best to only show the warning if the number of rows is greater than the sample set.

So I think the following logic might be most helpful.
nRows > sample rows : show warning
nRows < sample rows : don't show warning (as it doesn't matter)

Sorry, I should've considered this instead of just !=...

But its really nice to see this warning to let you know what's happening 👍 gives newer users some insight too

**Comment by saulpw** [comment]
Currently it looks like the opposite is happening!  I've pushed an update, let me know if this is what what you want.
