### ISSUE TITLE
[fdir] Default 'vd' command, hide the 'directory' column

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1057]
> As always, features implemented beget feature requests :)

I prefer the new 'vd' default of running without any arguments to give a listing of the current directory.  Thanks for changing that!

One suggestion, hide the "directory" column by default when the value is "." and the listing is not recursive.   The cursor starts on that column by default, and that is not a very useful column when every value is  ".", sorting and filtering on this value is not helpful.   Starting on the "filename" column is more useful.  

There is already a precedent in Visidata where columns are conditionally hidden depending on certain conditions.

**Comment by saulpw** [comment]
How about we hide the `directory` column when `options.dir_recurse` is false (which means that there could only be one value in the column)?  This is similar to the Columns Sheet where we hide the `sheet` column if it's for only one sheet, and show it for `columns-all` (`gC`).

**Comment by frosencrantz** [comment]
@saulpw, yes that seems like a good solution.

**Comment by frosencrantz** [comment]
This would only be for when visdata generates the list of files?  If the user provides a list of files, like `cmd-that-reports-filenames | vd -f fdir` it should still include the directory name.

**Comment by saulpw** [comment]
I think we can solve this quite effectively with collapsible rows, which I've put on the roadmap.

Kondo'd for now.

**Comment by frosencrantz** [comment]
Looking forward to that.  Collapsible rows sounds useful.  My earlier wishlist item (https://github.com/saulpw/visidata/issues/623)  that lead to you adding the unfurl-command was partly asking for expandable/collapsible rows.  The unfurl command has been a very useful addition.   It would still be nice to expand on a per row basis.

 @saulpw is the roadmap public?  Is this the correct one.  It doesn't look like it mentions collapsible rows:
https://github.com/saulpw/visidata/blob/develop/dev/ROADMAP

I don't to watch this file regularly.   If it is expected that this file is current, I'll keep eyes on it.
