### ISSUE TITLE
go-next-value stalls user interface

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1063]
**Small description**
#996 would maybe assist with this.

With a  large number of rows with a small number of variation of cells, skipping between values with the `go-next-value` (et al) commands freezes the interface

**Expected result**
Maybe some feedback about the search progress, if any other button relating to movement is pressed, this cancels the search.

**Actual result with screenshot**
Just a normal frozen window view

**Steps to reproduce with sample data and a .vd**
Open a large number of rows (I had 163,163 rows) and select a column which has only a few cells which are different to the rest. Make sure those cells are at the bottom using a sort of the column (to simulate a long run), then so a `go-next-value`

**Additional context**
v2.6

**Comment by anjakefala** [comment]
Thanks for the bug report! I liked your usability suggestions. 

I can confirm that `moveToNextRow` is **not** async, so for a very large number of rows the interface will freeze.

**Comment by anjakefala** [comment]
Hi @geekscrapy! I made `go-next/go-prev` family of commands async, and added a progress bar.

Note that you will be able to move yours cursor during the search, and then it will be moved to the found location. Aborting on cursor movement is trickier than I can manage. =)
