### ISSUE TITLE
[syscopyX] copy behavior changes to include a newline

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1064]
**Small description**
Prior to 2.5 a copy to the system clipboard would not include a newline at the end of the contents, in 2. it does

**Expected result**
Consistent behaviour, preferably without the newline so it means easy copy and paste of cell data into other forms.

To be clear:
In 2.4 and before (I tested 2.2, 2.3, 2.4 pip releases) when `syscopy-cell` (and friends) are used, a new line is _not_ appended to the output.

In 2.5 a newline (0x0a, Line Feed) is appended to the output saved to the clipboard

**Comment by saulpw** [comment]
Hi @geekscrapy, which syscopy commands do you mean?  I agree that syscopy-cell should not include a newline, but syscopy-rows **should** have a newline at the end I think, and I'm not sure about syscopy-row or syscopy-cells.

**Comment by saulpw** [comment]
Fixed for this special case.

**Comment by geekscrapy** [comment]
Hey, sorry for not getting back. Yes, syscopy-cell is the command I meant. And, I think you are right, it's the only one which actually makes sense
