### ISSUE TITLE
[slide-left-n] if given value is greater than the number of columns, slide to highest/lowest value

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1065]
IF I have a column at index 10, and I want to move it to position 0, currently I need to know which position it is at to use `slide-left-n`. The feat. request is to allow values greater than the number of columns on the left so if you provide a number which is greater than there are columns (to the left) it just goes as far as it can.

e.g. if you have a column at index 10 and you want it a 0, you provide a value of 100 into `slide-left-n` it will put it on the furthest left it can, which is column index 0. Perhaps a warning should be provided as well?

**Comment by saulpw** [comment]
Have you tried `gH` or `slide-leftmost`?

**Comment by geekscrapy** [comment]
I ~~have~~ had not 🤦‍♂️
