### ISSUE TITLE
Cannot run without installing

### ISSUE THREAD

**Issue by dkogan** [saulpw/visidata#1067]
The local `bin/vd` executable should be executable in-tree. It should know to use the local libraries if I'm running the local binary. Intead I see this:

```
dima@shorty:~/projects/visidata$ bin/vd                  
Traceback (most recent call last):
  File "/home/dima/projects/visidata/bin/vd", line 3, in <module>
    import visidata.main
ModuleNotFoundError: No module named 'visidata'
```

I can workaround with `PYTHONPATH=$PWD bin/vd` instead, but `bin/vd` should be doing that for me. There're are related problems here. If I have visidata installed on the system (via apt, say), then `bin/vd` will run, but it will unexpectedly use the system libraries.

**Comment by saulpw** [comment]
Hi @dkogan, that is a good idea.  I just set my PYTHONPATH, but I've been frustrated by this myself sometimes, so I'd love to know, what's the best practice here?

**Comment by dkogan** [comment]
Hi again. This area of Python bugs me to no end, so I can't say anything
about "best practice", but I can tell you what works for me.

My big Python project is mrcal: http://github.com/dkogan/mrcal

There's a library loadable with "import mrcal" and a bunch of
executables called "mrcal-whatever". There are a number of sub-libraries
(some in Python, some built from C), all combined into one big namespace
in __init__.py

The goal is that "import mrcal" works in-tree and that once the thing is
installed, the same exact "import mrcal" line works, but pulls from the
installed location instead. I do this by putting all the executables in
the toplevel PROJECT/ directory, and all the Python module things into
PROJECT/mrcal. So when running the executables in-tree, "import mrcal"
loads PROJECT/mrcal/__init__.py, which does the rest. Works well.

**Comment by saulpw** [comment]
So would we just have to make a symlink `vd` in the root of the visidata repo, pointing at `bin/vd`?

**Comment by dkogan** [comment]
Maybe? Python imports are surprisingly complicated, but that could be
it. One thing I'm not sure about is how "import visidata.whatever" and
"from . import stuff" would react. I'm in the middle of something else
at the moment. Can you try it out?

**Comment by saulpw** [comment]
I'm also in the middle of a couple other things, and there's no real rush on my end since I'm happy enough with the PYTHONPATH workaround.  Let me know whenever you test it out and if it works for your usecase or not.

Kondo'ed until then.
