### ISSUE TITLE
sort indicator not visible when column is next to keycols or left edge

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1071]
**Small description**
The arrows indicating the sort are not shown if the column is at an edge

**Expected result**
To see the arrows 

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/128688107-02c7eaa8-3611-4a77-b13d-ab497913fa8b.png)

![image](https://user-images.githubusercontent.com/11225502/128688187-fe2d535a-0454-421e-9990-9ece810cd526.png)

**Steps to reproduce with sample data and a .vd**
Open vd, sort, put that column to a left edge

**Additional context**
I have also tried with `--config=/dev/null`

**Comment by anjakefala** [comment]
@geekscrapy Unfortunately, I was not able to reproduce this. =( This is probably very terminal or font dependent. Which terminal are you using?

**Comment by anjakefala** [comment]
Nevermind, @saulpw helped diagnose the issue. The `<` ("not displaying all columns that are to the left") is covering up the sort indicator. Both the sort indicator and `<` use the leftmost character slot. 

I misunderstood "left edge". =)

**Comment by saulpw** [comment]
Okay, the sort indicator seems maginally more useful than the "more" indicator, and so will be drawn on top.  The above fix also only shows one sort indicator, when there are multiple lines in a column name.
