### ISSUE TITLE
[save] Saving a file without a saver saves to tsv by default.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1072]
**Small description**
Saving a file without a saver saves to tsv by default.  Changing expected format of file.

**Expected result**
If a filetype has a loader but not a saver, it should fail. And maybe suggest I save as another format.

**Actual result with screenshot**

It is easy to accidentally corrupt a file with save.  Also, when trying to reload, Visidata is no longer able
to read the file as the original type.  It might be possible to read it as tsv.

**Steps to reproduce with sample data and a .vd**
Load a YAML file, then save as original.  Try to reload.

   https://asciinema.org/a/A0mS0SsaOejokEq92ClXRJV0V

**Additional context**
Please include the version of VisiData. Latest version of develop.

**Comment by anjakefala** [comment]
Hi @frosencrantz!

Specifically, VisiData fallsback to the `--save-filetype`, but you are absolutely right about it being unexpected in trying to save `file.yml` with that name, as a tsv. I can see that going badly.

I am not sure if the correct approach is to fail, but maybe a prompt, "`yml` loader not available, save as `{options.save_filetype}` instead?"

**Comment by geekscrapy** [comment]
@anjakefala , I like this wording. It'd be good to have this as an input so you can change it if you don't want save_filetype?

**Comment by anjakefala** [comment]
Haha, I just got burnt by this, which means it is **definitely** being fixed. xD

**Comment by anjakefala** [comment]
We decided to opt for setting `options.save_filetype` to `''` by default, and then failing if it is not available. Thanks for filing this bug!
