### ISSUE TITLE
[yaml] Add a YAML saver.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1073]
Visidata has a YAML loader, but it is not able to save to YAML.  This feature request is to add the ability to save as YAML.

**Comment by anjakefala** [comment]
Thanks for the wishlist! I agree that would be a good saver to have.

**Comment by saulpw** [comment]
Kondo'd for now.

**Comment by tbleiker** [comment]
@saulpw is this a big thing to implement? With a yaml saver, visidata would be the perfect editor for beets.io! Would you give me some directions to implement this?
