### ISSUE TITLE
[menu]  New menu system flashes and hiding column headers

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1074]
**Small description**
New menu system flashes and hiding column headers

**Expected result**
Menu disappears, or doesn't hide column headers.

**Actual result with screenshot**

  https://asciinema.org/a/VZhEof7fXzRpDmtdvF8ilO1En

**Steps to reproduce with sample data and a .vd**
Open menu, see result.

The new menu system looks great.  I like that it even shows keyboard short-cuts. I think this might be a useful response to those who find it hard to learn all the keystrokes.

It looks like it might have some issues.  I suspect it is still in progress, but I won't be able to post for a while.
In case you are seeing something else, I wanted to inform you.

**Additional context**
Please include the version of VisiData. Latest develop version of Visidata

**Comment by anjakefala** [comment]
Thanks for keeping an eye on the cutting edge, @frosencrantz =)

**Comment by geekscrapy** [comment]
I can also confirm the headers disappearing, my repro:
1. Open vd on any sheet
2. Press ESC (which brings up the menu)
3. Press ESC again (which should hide the menu?)
4. Header of cols are now not shown

This only seems to be an issue if `show_menu` is False

**Comment by anjakefala** [comment]
Thanks for tag-teaming a detailed bug report! This bug should now be fixed on `develop`. =)
