### ISSUE TITLE
[menu] need better binding than ESC to open menu

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1075]
**Small description**
I used to use the combo "^[^J" in my plugin file to dive a row as a dictionary (as the normal dive does not show additional columns). I use something like the following to achieve this.

`Sheet.addCommand('^[^J', 'dive-as-dict', 'vd.push(SheetDict(f"{sheet.name}[{sheet.cursorRowIndex}]", source={(col.name if col.name else " "): col.getDisplayValue(vd.sheet.cursorRow) for col in sheet.visibleCols}))')`

**Expected result**
To be able to continue to use the shortcuts as before

**Actual result with screenshot**
I think a new sheet is opened. I get a blank sheet with a single column with a single uppercase letter

**Steps to reproduce with sample data and a .vd**
Try and use the following command via it's shortcut (ALT+ENTER)

Sheet.addCommand('^[^J', 'dive-as-dict2', 'status("i dont show :(")')

**Comment by saulpw** [comment]
Okay, so ESC was the obvious key to invoke the menu, but it's a bit tricky to use as an independent keystroke in TUIs. The only other key that makes sense to me is `Space`; I think then exec-command would move to `z Space`.  How does this sound as an alternative?

**Comment by geekscrapy** [comment]
From the little I've played with it so far my thought is that just having it visible by default and invoking by ALT+F/E..etc. would be good. The reason I like this as opposed to activation by ESC is that I often got caught in a "menu active/deactive" loop (my fault): If I had entered a command, e.g. select by regex and I decided to escape it, my instinct is to wack ESC a couple of times to get out _any_ mode I was in. With the be menu, this activated the menu and then I'd have to realise this, and have to press ESC again. I'm unsure where I learnt this ESC double tap, but I know others do it (not in vd), and it seems like ESC should be held as a "quit current mode", rather than an "open/activate" action?

Personally, I use exec-command *a lot* so this would be a step back for me, due to the extra key press and relearning muscle mem. But if the menu was activate by ALT+F/E etc. (as above) this is not an issue. What about M to open the menu? Or, of there is more gui/window items to come (maybe this includes the status bar) the key combo should think to include those, by making them in/visible as well? Sorry, more questions 😉

**Comment by saulpw** [comment]
Thanks for the feedback, @geekscrapy, that's really good to know about ESC.  I like Alt+F/etc for the toplevel menu items, and they will also be clickable if that helps.  If the menu was visible by default, would you set the option to disable it or would you just let it take up the top line of the screen?

**Comment by geekscrapy** [comment]
Having it clickable would definitely help. If I think of the audience I believe you are creating this for (to make it more accessible for new users and those that may need a nudge about the long commands due to not using vd in a while), then the clickable aspect is great, maybe even activation on right click would be an option (kinda like a contextual menu)?!

In regards to your second Q, I actually surprised myself with my own answer! I think I would have it visible! My initial thought was to disable it and get the extra row back, but for someone that is halfway between cmdline poweruser and GUI it's nice to see continuity between apps we know already. I can also see myself using it to remind myself of common commands such as select down/up (I can never remember what the combo is), however, my doing so would have to be faster that my current workflow for discovering it which is via 'z^H' then doing a search. So the ALT+F,E etc. would help here. It would be great if the right side of the menu bar could be used as well (maybe the sheets stats could be moved here?), but I'm sure you have thought that already.

Absolutely love the modal popup with the long and key combo, my only thought with this, make it (and the menu) more obvious (visually). I actually missed the bottom modal the first time I opened the menu as it is subtle at the bottom of the screen - but this maybe my tunnel vision ;) I think moving it up by a row might look slightly better too

**Comment by saulpw** [comment]
Good suggestions, @geekscrapy.  I'm going to play around with a few things.

Also, regardless of whether the File/etc toplevel menu line was visible, Alt+F would open up the File menu.  In that case, would you still leave the menu displayed by default, or would you configure it to be invisible when not in use?

**Comment by geekscrapy** [comment]
If show_menu is false, menu is not shown. If user presses ALT+F/E.... the menu pops up and is given focus with the according drop-down unfolded. If the user presses ESC it would quit the menu and it would then be hidden completely, like it was never there.

Personally, if the behaviour was like the above I'd have show_menu = False. This is a change from what I originally said, and I think the difference is that if the menu is easily opened (with ALT+F/E) I don't need it shown

**Comment by frosencrantz** [comment]
Some quick comments:
- The double ESC might be muscle memory from vim.
- The modal popup was hard for me to notice at first.
- If you decide to remove space as exec-command:
    - perhaps move to ":", which is the vi version of enter command
-  Having show_menu control whether the menu shows by default is useful.  I would set it to false
   - default should be true for new or causal users.
- I like:
  - the Alt-F/E idea.
  - additional information on the right-side.
- It might be useful to add dynamic menus, like latest or most frequent exec-command commands.

**Comment by saulpw** [comment]
@jsvine notes that Mac does not have an Alt key, and by default iTerm2 (at least) can make the Option key like Alt, but it's not obvious (can be remapped to "Esc+") and does not work that way by default.  So I guess we do need an alternative easy way to open the menu, besides Alt+F and clicking with the mouse (and we'll be losing the ESC method to open it).

`m` would work and is mnemonic for "menu" but it seems like a waste such a good lowercase letter on this.  ("mark" a la vim would be a better usage).

Other options: `Shift+V`, `Ctrl+W`, `Ctrl+A`, `Ctrl+H` (with remapping other help commands).  Any other suggestions?

**Comment by anjakefala** [comment]
My vote is for `Ctrl+H`, with the menu being moved to `g Ctrl+H`, and with `open-man` given a spot in the Menu. 

Though, I wonder if it will catch hardcore textpunk users off-guard, and that is my only reservation with that decision.

**Comment by saulpw** [comment]
Okay, `Ctrl+H` (and backspace) will open the help menu.  Alt+F etc will open that specific menu.  Clicking on a menu will also open the menu. ESC no longer opens the menu (but does close it).

**Comment by geekscrapy** [comment]
@saulpw not sure if there is a place to specifically capture menu feedback? If there is, please direct me!

Just updated to the latest commit and have the following initial feedback on the menu:

- Feels significantly more responsive and visible than when I first used it, which is great
- "Ctrl+H for help" - Could this be moved to the right, and the sheet name be where it is now? This would fit with other GUI apps location for file name.
- Plot menu - when moving to this menu from the left menu "Data", the "Graph" submenu opens automatically and therefore you have an (unexpected) extra click to get to "sYstem". Maybe submenus should require an extra keypress? This is the behaviour in other apps. In GUI apps if you use the mouse, the submenu is opened automatically if the user hovers on the parent item, but not when the keyboard is used. It requires and extra "->" keypress. Unsure what the reason is, but just an observation.
- FWIW I _currently_ have the menu turned off, as it feels more responsive now and I feel its more accessible with the Alt+ keys. However muscle memory is still telling me to hit Alt+F for the File/Sheet menu!
- Description box: I loved the previous location of the box (bottom left), I just felt it needed more contrast. Now I feel it gets in the way of the menu and the sheet you are working with, and jumps around quite a bit.
- Loving the icons for the menu items (e.g. new sheet)
- Are we able to get the same shade of the menu bar, on the lower status bar? It might join the two parts
- Menu bar coloUr ;) - I like having a bit more contrast to the menu and the colours fit closer to the default theme.
![image](https://user-images.githubusercontent.com/11225502/132299851-702709fe-5399-42fe-a6ec-58f2a9a9cd4c.png)

**Comment by saulpw** [comment]
Okay I've fixed most of these.  We're back to `Alt+F`ile and I guess you're right about the Right-on-submenu inconsistency.

What colour are you using there for the menu?

**Comment by geekscrapy** [comment]
> What colour are you using there for the menu?

Its the same as the keycol colour, cyan?
