### ISSUE TITLE
windows end-of-line on linux

### ISSUE THREAD

**Issue by teto** [saulpw/visidata#1076]
Hi,

I mentioned this on IRC but when saving a csv file on linux, I get CRLF endings instead of LF which messes up git diff etc.
```
$ vd --version
saul.pw/VisiData v2.5
```
To reproduce open a csv, edit a column and save the file with Ctrl+s . 
`cat -A toto.csv` shows `vstruct,,,,,$` before edition, after it shows `vstruct,,,,,^M$` (notice the ^M). Is it possible to change the behavior to avoid this one way or another ?

NB: for now I run `dos2unix` after saving the csv.

**Comment by saulpw** [comment]
Hi @teto, VisiData uses the csv.writer from Python stdlib, and exposes the various dialect options.  In this case, [`Dialect.lineterminator`](https://docs.python.org/3/library/csv.html#csv.Dialect.lineterminator) is set by default to '\r\n', and you can set it to what you want with `--csv-lineterminator=$'\n'`.

**Comment by teto** [comment]
thanks for the pointer.
