### ISSUE TITLE
When searching in Chinese, Chinese search is not supported, whether to support Chinese and other languages

### ISSUE THREAD

**Issue by joytianya** [saulpw/visidata#1077]
We want to hear your ideas about where VisiData can go and anything you think could be made smoother.
We consider all ideas that are feasible, but please don't be offended if we close it--we generally limit our open issues to bugs and small concrete feature requests that are part of the planned roadmap.

If you are a subscriber at the 'Workflow Optimist' level on [Patreon](https://www.patreon.com/saulpw/), you can designate this feature as one you would like to remain open, by adding an "[optimist]" tag in the summary line.

**Comment by saulpw** [comment]
I cannot reproduce.  Please provide a few rows of test data and command that does not work as expected.
