### ISSUE TITLE
[menu] Clicking anywhere but the menu or modal popup should disengage the menu (maybe)

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1079]
An idea is that a mouse click anywhere in the terminal that does not click on the menu or modal sets focus back to the underlying cell or column etc. This is more intuitive of other GUI apps. Not sure if that's the goal though ;)

**Comment by saulpw** [comment]
You're right, and this should work now, along with clicking on menu items while the menu is active.
