### ISSUE TITLE
How hard would it take to port this over to Oracle?

### ISSUE THREAD

**Issue by theplaceboeffect** [saulpw/visidata#108]
This looks like a pretty great tool. Did you develop it with being able to port over to other databases? Would love to help if you had.

**Comment by theplaceboeffect** [comment]
Never mind - I see your loader capability. Something to do over the weekend!

**Comment by saulpw** [comment]
@theplaceboeffect As long as there's a Python3 library for it, should be fairly straightforward.  Let me know if you have any questions or need any help!
