### ISSUE TITLE
[loaders] Support unpickling of more objects 

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1083]
Currently, VisiData supports the unpickling of dataframes with the pandas loaders, and numpy objects with the numpy loader (`--npy-allow-pickle`).

It would be great to support more formats, by unpickling and using `pyobj`.

**Comment by saulpw** [comment]
This would be useful, I agree.  If you would, please provide an example pickle file that does not load, and that will make this easier.

**Comment by saulpw** [comment]
I would need specific example files that don't load in order to grant this wish.

Kondo'ed for now.
