### ISSUE TITLE
vd --help to a non-tty doesn't output the help text

### ISSUE THREAD

**Issue by halloleo** [saulpw/visidata#1089]
**Small description**

vd --help to a non-tty like a file or pipe doesn't output the help text

**Expected result**

`vd --help | cat` exports the complete help to stdout

**Actual result**

`vd --help | cat` writes nothing to stdout, but takes over the screen with a `less`-like TUI.

**Steps to reproduce**

Just type

    vd --help | cat

or

    vd --help >vdhelp.txt

**Additional context**

v2,4,

**Comment by bugsbugsbux** [comment]
seems fixed in `saul.pw/VisiData v2.5`

**Comment by halloleo** [comment]
Confirmed: Works on VisiData 2.5 on macOS.

(The only niggle I have is that the output contains *roff escape sequences. I would prefer plain text, but that's a question of taste and can be easily be filtered out.)
