### ISSUE TITLE
Document Undocumented Features 

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1099]
- [ ] Macros
- [ ] Split pane
- [ ] Menu
- [ ] Memory cell
- [ ] https://github.com/saulpw/visidata/discussions/985
- [ ] VisiData for database loaders
- [ ] editline docstr

**Comment by frosencrantz** [comment]
This might already be covered by this wishlist request. Some menu items don't have help.  It seems like all default menu items should have help.  I noticed this for  System/Macro Sheet, perhaps there are more.

**Comment by saulpw** [comment]
There were a couple, @frosencrantz.  They should all have helpstrs now (and all commands should have a helpstr in general, as noted elsewhere).

**Comment by frosencrantz** [comment]
Side note for anyone else watching this issue.  Saul recently posted a video showing how to join the menu commands with the help-commands sheet:

https://www.youtube.com/watch?v=QixtGeSbSLU

**Comment by anjakefala** [comment]
We are reviewing what our documentation looks like, and are currently experimenting with a [GuideSheet](https://github.com/saulpw/visidata/discussions/1733). I am going to close this issue in favour of us not using the issue tracker as an outdated todo list.
