### ISSUE TITLE
[color]  color_current_col and color_current_row not combining 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1100]
**Small description**
color_current_col and color_current_row not combining 

**Expected result**
For the current cell it is expected that the values combine.

**Actual result with screenshot**
It doesn't look like they combine. It looks like color_current_row overrides the color_current_col.

I tried setting the current col to green, but it looks like the current cell is not shown in reverse green:
https://asciinema.org/a/2LEqjL4H0DD6WM2WyNomqwXwF?t=10

(This from develop head from last week, but the behavior is still the same.)

**Steps to reproduce with sample data and a .vd**

Set the `color_current_col` to something that can combine with `color_current_row` such as `green` and it doesn't appear to work

**Additional context**
Please include the version of VisiData.  Latest version from develop branch.

This came out of discussion https://github.com/saulpw/visidata/discussions/1093 The intention is that the values combine.

**Comment by anjakefala** [comment]
Hi @frosencrantz!

Confusingly, this works as expected if you had changed `color_current_row` to the color, and kept `color_current_column` as the attribute. Something must be happening that depends on the order of operations of colors and attributes being applied. I am looking into it.

**Comment by anjakefala** [comment]
Hi @frosencrantz

I pushed a change that addresses it, but I predict that this will have an affect on other color relationships (for e.g. the current cell colour will now trump selected rows colour).

I chatted with Saul, and we are going for it, and seeing how things feel.

**Comment by frosencrantz** [comment]
It works for me so far.  I haven't noticed issues yet.  Thanks Anja!
