### ISSUE TITLE
[quit]  'Ctrl+Q'  to exit doesn't work

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1101]
**Small description**
'Ctrl+Q'  doesn't quit anymore

**Expected result**
Exits VisiData from any sheet.

**Actual result with screenshot**
It reports `no command for Ctrl+Q`
No screenshot, if you are not able to reproduce I can provide a screenshot.

**Steps to reproduce with sample data and a .vd**
Start VisiData press `Ctrl+Q`

**Additional context**
Please include the version of VisiData.  Latest version from develop.
There were some changes this past week related to renaming key values `^Q` to 'Ctrl-Q`

**Comment by anjakefala** [comment]
Thanks so much @frosencrantz!

This should be fixed on develop now.

**Comment by frosencrantz** [comment]
Wonderful!  Anja, thank you! That has become one of my most used Visidata keys.  Learned about it from a thread this year.
