### ISSUE TITLE
[yaml] Yaml loader traces on no attribute _colnames

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1104]
**Small description**
Yaml loader traces on loading

**Expected result**
Yaml data is loaded.

**Actual result with screenshot**

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 289, in reload
    for r in self.iterload():
  File "/usr/lib/python3.9/site-packages/visidata/loaders/yaml.py", line 17, in iterload
    self._colnames.clear()
AttributeError: 'YamlSheet' object has no attribute '_colnames'
```

**Steps to reproduce with sample data and a .vd**
vd sample_data/states.yml

**Additional context**
Please include the version of VisiData. Latest develop branch.

**Comment by frosencrantz** [comment]
The culprit? https://github.com/saulpw/visidata/commit/cc22f64013cbbf320b7ca0657fda7e1172678c08

**Comment by saulpw** [comment]
Thanks for reporting, @frosencrantz!  Should be fixed now.

**Comment by frosencrantz** [comment]
Works great!  Thanks Saul!
