### ISSUE TITLE
[develop] Error when using disp_menu as cli arg

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1107]
**Small description**
I had `disp_menu` set to `True` in my config and I wanted to test how it acted without it temporarily. I therefore used the following command and args to test it, but got an error (see below) and the menu refuses to open.

**Expected result**
To be able to continue to use vd without the menu being always open

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/132307649-ebf0cca3-fbf2-46c5-b94f-ac9dd552a978.png)

**Steps to reproduce with sample data and a .vd**
`visidata --config=/dev/null --disp_menu=0 /usr/bin/`

**Additional context**
Latest as per today

**Comment by saulpw** [comment]
Thanks for reporting this bug, should be fixed now.
