### ISSUE TITLE
Reverted y axis in SHP visualization

### ISSUE THREAD

**Issue by mficek** [saulpw/visidata#111]
Hi guys,
Thanks for visidata, I absolutely love it!

I spotted that visualization of shp files is y-axis reverted - that is often a reason when "image" is used for drawing, for which canvas 0,0 point is upper left corner, but for graphs and geocoordinates it is lower left corner. I think the solution would be simply mirror y coordinates.

Please find attached a screenshot that compares the same shapefile opened in visidata and QGIS. 
![screenshot 2018-02-02 09 30 01](https://user-images.githubusercontent.com/9933817/35723896-3347da1c-07fc-11e8-95ec-dbe554a4d2c8.png)

**Comment by saulpw** [comment]
Thanks for noticing this, @mficek.  You are exactly right, that the Y-axis is inverted.  Amazingly, I have been testing .shp with a map of my own city's neighborhoods, and I did not notice.  This fix will be in 1.1.
