### ISSUE TITLE
Add instructions to docs or somewhere on how to use with psql

### ISSUE THREAD

**Issue by radostyle** [saulpw/visidata#1113]
Here is how to use as a pager with psql which I find very useful.  I don't know where in the docs to put it.

In psql:
```
\pset format csv
\pset pager always
\setenv PSQL_PAGER 'vd -f csv'
\pset pager_min_lines

```
When you want less back as a pager because you run a psql command that doesn't return tabular data then you can:

`\setenv PSQL_PAGER less
`

**Comment by saulpw** [comment]
Thanks @radostyle, I'm sure that'll be helpful for some other psql users.  We'll find a place to put it.

**Comment by anjakefala** [comment]
Thanks so much @radostyle! I added this to the docs, and it will be added to https://visidata.org/formats with the next release of VisiData. =)
