### ISSUE TITLE
opening TAB delimited files with fields containing carriage returns

### ISSUE THREAD

**Issue by bartender911** [saulpw/visidata#1120]
**Small description**
When opening a tab-delimited text file that has returns in a field, the field spans across multiple lines.

**Expected result**
fields that have returns should not span multiple lines

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
vd test.txt

**Additional context**
saul.pw/VisiData v2.6

[test.txt](https://github.com/saulpw/visidata/files/7226885/test.txt)

**Comment by saulpw** [comment]
Hi @bartender911, thanks for the report.  TSV files can't have newlines (or tabs) within fields.  If your format has quoted fields with embedded newlines, try parsing as a CSV with a delimiter of TAB: `vd -f csv --csv-delimiter=$'\t'`.

**Comment by bartender911** [comment]
I see my error now.
I was trying to open it as tab delimited using -csv-delimiter='\t' instead of -csv-delimiter=$'\t'

Thank you for this.
