### ISSUE TITLE
Excel Saver replaces spaces and special characters with underscore _

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#1122]
**Small description**

When saving a visidata sheet containing spaces or special characters (in my case, spaces and '+' symbols), they are replaced with '_'. e.g. `my sheet` becomes `my_sheet`, `other sheets+` becomes `other_sheets_`. However, I know that Excel supports spaces and special characters in sheet names, because these sheet names came from an Excel sheet to begin with.

**Expected result**

I expect the sheet names to not be changed, as the underlying file format supports these characters.

**Actual result with screenshot**

Original file:
![image](https://user-images.githubusercontent.com/55477181/134829618-e9fb320c-9af9-42f8-8e94-950915e0eb61.png)

Same file after saving with visidata (select required sheets, save with `g^S`):
![image](https://user-images.githubusercontent.com/55477181/134829650-1d92a3d5-3ad0-4515-bbfa-e69170efe46f.png)

**Steps to reproduce with sample data and a .vd**:

[test_excel.xlsx](https://github.com/saulpw/visidata/files/7232532/test_excel.xlsx)
[test_excel.vd.txt](https://github.com/saulpw/visidata/files/7232533/test_excel.vd.txt)

**Additional context**
Please include the version of VisiData

saul.pw/VisiData v2.4

**Comment by anjakefala** [comment]
Thanks for the thorough bug report @davidwales! I am especially grateful for the sample data and `.vd`. I was able to reproduce the issue.

**Comment by saulpw** [comment]
VisiData v2.6 only cleans the sheet name if `options.clean_names` is set.  However, I think the real request here is for the xlsx loader/saver to be round-trippable: loading an xlsx and saving it directly to a different file should result in the two files being functionally identical.  This wouldn't be reasonable for many sheets, but at least it should be possible for sheets saved with VisiData originally.

**Comment by ghost** [comment]
I'm running 2.6.1 (from the PPA).

I've got `options.clean_names = False` in my `.visidatarc`.

But I'm still losing spaces and symbols in my sheet names somehow (same steps as above):

![image](https://user-images.githubusercontent.com/55477181/139606897-c57f5ce6-f94e-43dd-b3af-45ad1297e4ed.png)


Round tripping would be nice, but I'll happily settle for the sheet names not secretly changing when I use `g^s`. 😄

**Comment by ghost** [comment]
I suspect that this line is where the trouble is:
https://github.com/saulpw/visidata/blob/dc8cef4980bdef07fd3640be8c92b9e3dc8be9dc/visidata/loaders/xlsx.py#L85

This is calling the generic `cleanNames` function, rather than an Excel specific function, and includes the following line:
https://github.com/saulpw/visidata/blob/dc8cef4980bdef07fd3640be8c92b9e3dc8be9dc/visidata/utils.py#L54

However, for Excel sheets, the characters to exclude should be just:

`: [ ] * / \ ?`

See: https://stackoverflow.com/a/451488

Apparently, a sheet is also [not allowed to have the name `History`](https://www.accountingweb.com/technology/excel/seven-characters-you-cant-use-in-worksheet-names) (case insensitive):

**Comment by saulpw** [comment]
Ah, I see, this is being cleaned at load time with `maybeClean` and then again separately in xlsx save.  This is my fault, @geekscrapy had it correct in #594 (
https://github.com/saulpw/visidata/pull/594/files).  I'm personally slightly opposed to guardrails in general ("bad" inputs can still be useful), but we'll gate it on `options.clean_names` and I think that should work for everyone.

I can't bring myself to implement the `History` part of it.  Maybe 'options.clean_names' could a regex of some kind :smiling_imp:

**Comment by saulpw** [comment]
I think this also makes xlsx more round-trippable (if it was saved with VisiData in the first place, `gsgCtrl+X` on the top-level index should save a copy).

**Comment by ghost** [comment]
Thank you!
