### ISSUE TITLE
Exception: inconsistent keys--reload join when joining between XlsxSheet and CsvSheet

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#1124]
**Small description**

Attempting to join between an XlsxSheet and a CSVSheet mostly works, but records in the join key column are replaced with the following error cell:

``` python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/visidata/wrappers.py", line 108, in wrapply
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/visidata/column.py", line 280, in getValue
    return self.calcValue(row)
  File "/usr/lib/python3/dist-packages/visidata/join.py", line 76, in calcValue
    raise Exception(f'inconsistent keys--reload join')
Exception: inconsistent keys--reload join
```

**Expected result**

The sheets would be joined, and the join key column would contain the actual values, not an error.

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/55477181/135005477-17dbf0e9-76c8-4f08-ab21-05a9b0c37a8f.png)

**Steps to reproduce with sample data and a .vd**

[joining_error_interesting_records.csv](https://github.com/saulpw/visidata/files/7240186/joining_error_interesting_records.csv)
[joining_error.xlsx](https://github.com/saulpw/visidata/files/7240188/joining_error.xlsx)
[joining_error_records.vd.txt](https://github.com/saulpw/visidata/files/7240187/joining_error_records.vd.txt)

**Additional context**
Please include the version of VisiData.

saul.pw/VisiData v2.4

**Comment by anjakefala** [comment]
Thanks for the bug report @davidwales! I am grateful for the sample data and `.vd`.

**Comment by saulpw** [comment]
I believe this is fixed, @davidwales.  Let us know if you find other cases that seem incorrect.
