### ISSUE TITLE
[pandas] Enable loading of whole hierarchy of parquet files

### ISSUE THREAD

**Issue by sochotnicky** [saulpw/visidata#1126]
Right now when I download a set of parquet files (for example from S3 storage) I get a hierarchy of several directories. I can load them up manually and then merge but as mentioned in https://github.com/saulpw/visidata/issues/1068 the merge performance is relatively slow. 

For example this hierarchy:
```
data
├── date=2021-02-22
│   └── 2021-02-22.parquet
├── date=2021-02-23
│   └── 2021-02-23.parquet
├── date=2021-02-24
│   └── 2021-02-24.parquet
├── date=2021-02-25
│   └── 2021-02-25.parquet
├── date=2021-02-27
│   └── 2021-02-27.parquet
├── date=2021-02-28
│   └── 2021-02-28.parquet
├── date=2021-03-01
│   └── 2021-03-01.parquet
├── date=2021-03-02
│   └── 2021-03-02.parquet
├── date=2021-03-03
│   └── 2021-03-03.parquet
├── date=2021-03-04
│   └── 2021-03-04.parquet
├── date=2021-03-05
│   └── 2021-03-05.parquet
├── date=2021-03-06
│   └── 2021-03-06.parquet
```

Ideally I'd be able to run something like
```
$ vd -f pandas data/
```
And it would load all pandas/parquet files in that subdirectory (as a single sheet). Technically in pandas/pyarrow this works using:
```
import pandas as pd
df=pd.read_parquet("data")
```
But I have not looked too closely how easy it would be to support this mode. I tried a few things to load whole subdirectory as one pandas-backed sheet but haven't found a way. I could have missed something though

**Comment by sochotnicky** [comment]
I'll say - there is a fairly easy workaround - just merge the parquet files using a separate small script before loading to vd. So not a huge deal but might make basic usage easier in some cases?

**Comment by saulpw** [comment]
>  I have not looked too closely how easy it would be to support this mode. I tried a few things to load whole subdirectory as one pandas-backed sheet but haven't found a way.

The pandas loader requires the extension to reflect which pandas loader to use.  So the way to do this, is to rename the dir to `data.parquet` and then use `vd data.parquet -f pandas`.
 
This won't work, however, because VisiData specifically overrides the filetype for directories (so a dir called `lotta.csv/` wouldn't try to use the csv loader).  I don't know if that has ever come up though, and this seems like it should work, so we'll change it in the next version (and if someone has directories with extensions then they can use `-f dir`).

**Comment by sochotnicky** [comment]
Actually renaming the directory to "data.parquet" and running `vd data.parquet -f pandas` makes things work. Or even using '-f parquet' works without even renaming the directory.

So I guess this could be closed unless you'd want some docs changes or perhaps improve handling of `-f pandas` dealing with directories.

**Comment by saulpw** [comment]
A docs change is a good idea.  Where did you look in the first place?  We should put a note there.

**Comment by sochotnicky** [comment]
I think an addition to pandas-specific note in https://www.visidata.org/docs/formats/ would work have worked in my case.

**Comment by anjakefala** [comment]
I added a note to `/formats`! Thanks so much for filing this issue, and figuring it out with us. =)
