### ISSUE TITLE
A list of modules/functions/objects that exist in the expression namespace

### ISSUE THREAD

**Issue by MMesch** [saulpw/visidata#1128]
Hi all and thank for working on this nice tool! I have started playing around with it and had an idea that might be useful for a newcomer:

If I understand correctly, in a python expression column, one can access all imported modules and names that are in the [__init__](https://github.com/saulpw/visidata/blob/dc8cef4980bdef07fd3640be8c92b9e3dc8be9dc/visidata/__init__.py) file. Some of those, such as `math` are dealt with in the documentation and explicitly imported. But many other names are implicitly imported through `*` from other modules. For example, I successfully used `datetime` which I assume is a very common need for sheet-like use cases. I think it would be great to have access and search through this globals namespace (for example in another sheet?) via some help function. This could also be added to the documentation. Does this maybe already exist?

**Comment by ajkerrigan** [comment]
Hi @MMesch - if you run `globals()` via `Ctrl`+`x` (the `pyobj-expr` command), you'll get a new sheet with everything in the VisiData namespace. That will include plugins you've loaded and any custom code you've added to your `~/.visidatarc` file (which ties in a bit to #1129 where you ask about ways to define constants).

Just as an example here's a snippet of what I see - including some built-ins, some constants, imported modules and random junk of my own. There may be other/better ways to get this, but this is something!

```
  File  Edit  View  Column  Row  Data  Plot  System  Help               Ctrl+H for help menu
 key                ║ value
 tanh               ║ <built-in function tanh>
 trunc              ║ <built-in function trunc>
 prod               ║ <built-in function prod>
 perm               ║ <built-in function perm>
 comb               ║ <built-in function comb>
 nextafter          ║ <built-in function nextafter>
 ulp                ║ <built-in function ulp>
 pi                 ║ 3.141592653589793
 e                  ║ 2.718281828459045
 tau                ║ 6.283185307179586
 inf                ║ inf
 nan                ║ nan
 jmespath           ║ <module 'jmespath' from '/home/aj/.local/pipx/venvs/visidata/lib/python3.9/site-packages/jmespath/__init…
 addcol_jmespath    ║ <function addcol_jmespath at 0x7f981a654a60>
 select_by_jmespath ║ <function select_by_jmespath at 0x7f981a60cf70>
 Drawing            ║ <class 'darkdraw.drawing.Drawing'>
 DrawingSheet       ║ <class 'darkdraw.drawing.DrawingSheet'>
 FramesSheet        ║ <class 'darkdraw.drawing.FramesSheet'>
 S3Path             ║ <class 'plugins.vds3.S3Path'>
 S3DirSheet         ║ <class 'plugins.vds3.S3DirSheet'>
 openurl_s3         ║ <function openurl_s3 at 0x7f981a095790>
 vd_getattr         ║ <function vd_getattr at 0x7f981a0210d0>
 debugging_helpers  ║ <module 'plugins.debugging_helpers' from '/home/aj/.visidata/plugins/debugging_helpers.py'>
 kvpairs            ║ <module 'plugins.kvpairs' from '/home/aj/.visidata/plugins/kvpairs.py'>
 split_navigation   ║ <module 'plugins.split_navigation' from '/home/aj/.visidata/plugins/split_navigation.py'>
 vdrepl             ║ <module 'plugins.vdrepl' from '/home/aj/.visidata/plugins/vdrepl.py'>
 vpager             ║ <module 'plugins.vpager' from '/home/aj/.visidata/plugins/vpager.py'>
2› globals()|                                                                                      k  go-up      1038 items  •0
```

**Comment by MMesch** [comment]
Great! That's exactly what I needed. I'd vote for a menu or documentation entry, although arguably it is more useful to discover the `Ctrl + x` command where one can run such things directly.
