### ISSUE TITLE
[2.7dev] [optionsSheet] Disable ability to edit values in the 'option' column

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1132]
**Small description**
While having the cursor on the 'option' column the user is able to do a `delete-cell` (zd) command which makes in the interface throw an error

**Expected result**
Throw an error something like 'cannot edit cell'.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/135398334-cd8f91c2-182f-40d2-95b0-5b45d4b37320.png)

**Steps to reproduce with sample data and a .vd**
Open options sheet with 'SHIFT+O' and do a zd on a cell in the 'option' column.

**Additional context**
Whilst reproing this bug, I also noticed that DirSheet allows edits of (at least) the `modtime` and `size` columns which seem like an odd thing to not throw an error on. Maybe Columns could have an extra flag on them such as "readonly"?

**Comment by saulpw** [comment]
It may not be a good idea, but you can edit the `modtime` and `size` of files, and when you commit it will set them accordingly.  Same with the (hidden) owner/group/mode columns.

**Comment by geekscrapy** [comment]
> It may not be a good idea, but you can edit the `modtime` and `size` of files, and when you commit it will set them accordingly. Same with the (hidden) owner/group/mode columns.

You can arbitrarily edit the size of files? How does that work? 🤔 I'll have to try that out, does it just truncate the file?

**Comment by saulpw** [comment]
Yup!  There's a POSIX command `truncate` and a corresponding system call `truncate(2)`.  Just sets the size, either truncating the file or expanding it with zeroes.  Not often useful, but included because it was easy :)

**Comment by anjakefala** [comment]
Thanks for the bug report for the original issue! That should be straightforward to fix.
