### ISSUE TITLE
labels on scatterplots

### ISSUE THREAD

**Issue by MMesch** [saulpw/visidata#1135]
It would be great to have an option for labels next to each point on scatter plots.

My specific use case: take a sheet with text columns, umap them by similarity to 2D x/y coordinates and then plot them to see which data points are similar to each other.

**Comment by saulpw** [comment]
Hi @MMesch, this is an interesting idea.  How many data points do you usually have?  I would think it would look really messy with even 100 points.

**Comment by MMesch** [comment]
That's true. I think you can keep labels until about 50 with a decreased font size (not sure if that's possible in the terminal). Otherwise scrolling through the points and showing the label for the one selected would be a solution.

**Comment by saulpw** [comment]
If someone wants to do this, it shouldn't be too hard.

Kondo'ed for now.
