### ISSUE TITLE
[2.7] [IndexSheet] Sheets loaded by IndexSheet are not cancellable from within the loading subsheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1136]
**Small description**
When an index sheet opens the loading of the subsheets is cancellable from the index sheet but not from within the actual loading sheet.

For example:
I load an xlsx sheet with a few subsheets which have a large number of rows.
The progress counter shows the loading of these rows while viewing the index sheet and the loading of the subsheets is cancelable. However, when diving into a subsheet that is currently loading, you cannot cancel the load.

A visual example of this is adding the following column to an index sheet type:

`Column('Progress', getter=lambda _,r: r.progressPct)`

When indexSheets with subsheets (that take a long time to process) are loaded with this column, nothing is shown. This indicates that the async loading is occurring from the IndexSheet, not the individual subsheet.

If you cancel the IndexSheet load and reload from within a subsheet, then the progressPct is shown.

**Expected result**
Loading of all sheets takes place from the context of itself, not IndexSheet.

**Comment by saulpw** [comment]
You are totally right, @geekscrapy!  This has been fixed on develop and will be in the next release.
