### ISSUE TITLE
slide-bottom and slide-up don't work with Shift+ up/down arrow keys

### ISSUE THREAD

**Issue by a-y-u-s-h** [saulpw/visidata#1137]
**Small description**
`Shift+Left Arrow Key` and `Shift+Right Arrow Key` moves the columns left and right, but moving rows up and down doesn't work with `Shift+Up/Down` - the bindings don't exist. `Shift+J/K` works though. But it would be better to have arrow key support for this as well.

**Comment by saulpw** [comment]
What platform are you working on, @a-y-u-s-h ? Also, what gets printed on the status line when you press `Shift+Up/Down`?

**Comment by a-y-u-s-h** [comment]
I installed `visidata` package from `aur` version `2.6.1-1`. I'm running `Garuda Linux x86_64` (which is a flavor of Arch) with Kernel `5.14.8-zen1-1-zen`. Just noticed the status bar, it says `slide-right` or `slide-left` even if I press Shift with up or down keys as demonstrated in this video.


https://user-images.githubusercontent.com/19586719/135767025-068586df-74eb-480b-b282-ae357de5ee82.mp4

**Comment by anjakefala** [comment]
This has been fixed on the `develop` branch, and will be part of the next VisiData release. =) Thanks for the report!
