### ISSUE TITLE
Graphs do not show any points within tmux

### ISSUE THREAD

**Issue by mficek** [saulpw/visidata#114]
Hi Saul!
If I'm not mistaken, the visualization (graphs) does not show any points when visidata runs in tmux. Is there something I should just configure or is that some side effect? Many thanks, please let me know if you need any further info/screenshots/support.

**Comment by saulpw** [comment]
If it works outside of tmux, but not inside tmux, then it might be due to a different TERM that tmux is using.  Can you try with e.g. `xterm-256color`?  If that doesn't work, please share the TERM that is set both inside and outside of tmux.

**Comment by mficek** [comment]
Yep, thanks for pointing me at the TERM variable. It was set to "screen" so I changed it to "screen-256color" and all works perfectly. Thanks!

**Comment by unhammer** [comment]
You can `set -g default-terminal "tmux-256color"` in your ~/.tmux.conf cf.  https://github.com/tmux/tmux/wiki/FAQ which also gives colors in visidata
