### ISSUE TITLE
Replay with a `join-sheets` operation hangs on 2.6.1

### ISSUE THREAD

**Issue by agjohnson** [saulpw/visidata#1141]
:wave: 

I noticed an issue with a replay file on version 2.6.0/2.6.1. If I replay a cmdlog with a join operation, visidata hangs right after the join operation. I get a blank sheet and the status is "Processing...". If I try to close the sheet and redo the join, it still hangs. I even have to `kill -9` the pid to exit.

![image](https://user-images.githubusercontent.com/1140183/136290649-b28df854-6861-41ed-b88e-3d96ccec00d3.png)

I don't have any problems manually joining the sheets, it just seems to be the replay that is affected.

If I back down to 2.5.0, replay works as expected.

System is linux, Python version 3.9.4.

#### Reproducing

Here's an example gist:

https://gist.github.com/agjohnson/6b0d639b2aa622b338d2ab3fa3f2bef6

I am running:

```poetry run vd -p bug.vd```

If I install 2.6.1, I can reproduce the hang with my gist. If I back down to 2.5.0, visidata does not hang.

**Comment by anjakefala** [comment]
Hi Anthony!

This caught me off-guard because our join tests run using replay, but perhaps the hanging only happens outside of batch mode. I will for sure take a look! Thanks for filing a bug report. =)

**Comment by agjohnson** [comment]
Ah good guess! I tried with batch mode and did not experience the bug:

```
$ vd -b -o out.csv -p bug.vd
opening bug.vd as vd
"foo.csv"
opening foo.csv as csv
toggle current column as a key column
Open file or URL
"bar.csv"
opening bar.csv as csv
toggle current column as a key column
open Sheets Stack: join or jump between the active sheets on the current stack
toggle selection of current row
toggle selection of current row
slide current row up
merge selected sheets with visible columns from all, keeping rows according to jointype
loading 0 sheets
replay complete
saving 1 sheets to out.csv as csv
$ vd --version
saul.pw/VisiData v2.6.1
```

**Comment by anjakefala** [comment]
```
21:07 <kefala> 9f27946da82eabb896f1c07e3db5c14216c239e7 is the first bad commit
21:07 <kefala> commit 9f27946da82eabb896f1c07e3db5c14216c239e7
21:07 <kefala> Author: Saul Pwanson <code@saul.pw>
21:07 <kefala> Date:   Mon Aug 9 18:33:41 2021 -0700
21:07 <kefala> [join] ensure sheets are loaded before joining; show rows/cols incrementally
```

**Comment by anjakefala** [comment]
Thanks @agjohnson! This should now be fixed on `develop`, and will be part of the next release. =)
