### ISSUE TITLE
After installing 2.6.1 I get a ModuleNotFoundError

### ISSUE THREAD

**Issue by halloleo** [saulpw/visidata#1145]
**Small description**

After installing 2.6.1 I get a ModuleNotFoundError when starting up `vd file.csv`.

**Expected result**

No Error after startup.

**Actual result with screenshot**

Here the stack trace via `Ctrl-E`:

```
Traceback (most recent call last):
  File "[...]/lib/python3.6/site-packages/visidata/settings.py", line 364, in loadConfigAndPlugins
    vd.addGlobals(importlib.import_module(modname).__dict__)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
```

**Additional context**

The problem even happens when I just execute `vd` without any file.

New version 2.6.1, old version 2,4

**Comment by anjakefala** [comment]
Thanks a lot! This is a known issue =) https://github.com/saulpw/visidata/issues/1131

I talked to Saul about the proposed fix, but apparently have not gotten to pushing it yet. Should be soon.

**Comment by halloleo** [comment]
Thanks @anjakefala. Can I alleviate this in my install by creating an empty plugin folder?

**Comment by anjakefala** [comment]
Yes! A `~/.visidata/plugins`. I think you can also set `options.imports=None` in your `~/.visidatarc`.

**Comment by anjakefala** [comment]
This is now fixed on develop @halloleo !

**Comment by halloleo** [comment]
Thanks. Can live with the workaround and will wait until it is on PyPi. :-)
