### ISSUE TITLE
[loader] HTML directory index pages

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#1149]
Web servers can automatically generate index pages to list the content of some
directory on the web.

Visidata is currently able to load the entries from the ones which render the
lists in HTML tables. This is however not the format used by all web servers:
some are rendering their lists in some sort of TSV-like format in HTML `<pre>`
tags. For example: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/.

Some Python library already exists for extracting multiple formats of HTML
listings: https://github.com/gumblex/htmllisting-parser. It could be used to
create a loader supporting most index pages.

However, I'm not sure whether it's possible to automatically detect those, so
that both the usual tables and directory listings can automatically be
extracted when supplying Visidata with an URL, without explicitly selecting a
particular loader to use.

**Comment by saulpw** [comment]
Interesting idea, @pacien.  I think this is a reasonable wishlist item.

Kondo'd for now.
