### ISSUE TITLE
add support for RTL languages

### ISSUE THREAD

**Issue by hossam-houssien** [saulpw/visidata#1153]
We want to hear your ideas about where VisiData can go and anything you think could be made smoother.
We consider all ideas that are feasible, but please don't be offended if we close it--we generally limit our open issues to bugs and small concrete feature requests that are part of the planned roadmap.

If you are a subscriber at the 'Workflow Optimist' level on [Patreon](https://www.patreon.com/saulpw/), you can designate this feature as one you would like to remain open, by adding an "[optimist]" tag in the summary line.

**Comment by hossam-houssien** [comment]
for Arabic text, data in columns not perfectly adjusted and there is no text (left/right) justification (couldn't find the option)

**Comment by saulpw** [comment]
Hi @hossam-houssien, I don't speak Arabic and so I don't have a good sample or know what it should look like.  It would be helpful if you could supply one!

**Comment by hossam-houssien** [comment]
[ar_data.csv](https://github.com/saulpw/visidata/files/7356204/ar_data.csv)
<img width="960" alt="ar-data" src="https://user-images.githubusercontent.com/6001135/137558396-4e3bd323-7cdf-4e28-9b2d-34fea76d0105.png">

uploaded samples of arabic csv and a png show how it looks, I think adding option to adjust text left/right would be nice also.

**Comment by saulpw** [comment]
Awesome, thank you!  Is the text itself displayed correctly, or is it in reverse order?  That is, does it just need to be right-justified in order to be correct?

As for the alignment, that would depend on your terminal and font.  It looks like you're on Windows; what terminal/font are you using?

**Comment by hossam-houssien** [comment]
the text displayed correctly for reading, but it need to be right-justified as you mentioned, I'm running visidata on on windows, I also tried different terminals standard cmd (Arabic chars don't display correctly) , cmder (Arabic chars displayed correctly, but not right-justified, as per pic above), new windows terminal (Arabic chars displayed correctly, not right-justified, but column vertical bar separator also displayed correctly, it much nicer than cmder)

**Comment by saulpw** [comment]
Hi @hossam-houssien, I did some experiments and it looks like bidirectional (bidi) text is poorly supported in many terminals.  We can add an `rtl` attribute on Column that does a simple right-justify, but the rest of the issues that you are seeing would need to be handled at the terminal layer.  On MacOS, it seems like the builtin Terminal works; on Linux, mlterm; but I'm not sure which terminals on Windows do bidi-text properly, especially Arabic.  If you have advice on which terminals work best (with other text applications, or even just typing on the command line directly), I'd love to know what your experience and recommendations are!

**Comment by saulpw** [comment]
Closed pending further information.

**Comment by hossam-houssien** [comment]
the best terminal to be used is the new windows terminal , however it's still need to add right justification option.
