### ISSUE TITLE
Issue with Enter key

### ISSUE THREAD

**Issue by hossam-houssien** [saulpw/visidata#1154]
**Enter key issue**

On my laptop pressing Enter key in any visidata screens doesn't do any action and it displays at the screen bottom Ctrl+M ,
It only work when writing command and search

**Comment by saulpw** [comment]
Hi @hossam-houssien, what version, platform, etc are you using?

**Comment by hossam-houssien** [comment]
$ visidata -v
saul.pw/VisiData v2.6.1

OS Name			Microsoft Windows 10 Pro
Version				10.0.18362 Build 18362
System Manufacturer	HP
System Model		HP EliteBook x360 1030 G3
System Type			x64-based PC
System SKU			2ZV66AV
Processor			Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by hossam-houssien** [comment]
I also tried different terminals, standard windows CMD, CMDER and new windows terminal, all have same behavior.

**Comment by saulpw** [comment]
Possible regression of #741.

**Comment by saulpw** [comment]
Seems to work now!  Let me know if you still see issues, @hossam-houssien.

**Comment by hossam-houssien** [comment]
hi, the bug you are referencing is  #741 and it is on visidata v 2.0.1,mine is the latest 2.6.1 the issue still exists

**Comment by anjakefala** [comment]
@hossam-houssien The bug is fixed on the `develop` version of VisiData! `pip3 install --upgrade https://github.com/saulpw/visidata.git@develop`. It will be available on the next release of VisiData, v2.7. =) To be shipped, soon.

**Comment by hossam-houssien** [comment]
yes, i tested on 2.7.1 and **ENTER** key is now working fine
