### ISSUE TITLE
Home and End key actions

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1161]
Something I noticed that I think has changed recently (purely based on my muscle memory!!) is the behaviour of the `Home` and `End` keys.

In apps such as `less`, the keys will _only_ move you to the top and bottom rows, maintaining horizontal position.

In `vd` `Home` moves you to the absolute first cell in the top left, and `End` moves you to the absolute last row, first cell. This feels a little odd, as I would expect that `End` might take you to the last row, rightmost cell at least.

To reflect the way other apps work, I would therefore expect Home to be bound to `go-top` and End to `go-bottom`? As a middle-ground, maybe `End` could do `go-right`+`go-bottom`?

**Comment by saulpw** [comment]
Hm, I thought these were set to go to the "first" (leftmost top) and "last" (rightmost bottom) positions, but they were bound to `go-leftmost` and `go-rightmost`, and not entirely correct at that.  I don't use these myself, and I think someone else wanted Home/End to act as you're suggesting, so we'll change the bindings to `go-top` and `go-bottom` as you suggest.
