### ISSUE TITLE
Select does not match - |$

### ISSUE THREAD

**Issue by typo3ua** [saulpw/visidata#1163]
I input | $ in current column and I get the result where row does not match

Look at my screen.... is it normal?

![image](https://user-images.githubusercontent.com/638022/139461527-1d2df023-b498-4df4-abd0-887b5549dbfe.png)

...or I input | $25000 ... the result

![image](https://user-images.githubusercontent.com/638022/139463849-e421fe19-f798-4939-9fda-a29859e034f7.png)

version 2.6.1
OS Ubuntu 20.4

**Comment by saulpw** [comment]
Hi @typo3ua, the `|` "select-col-regex" command, like several others in VisiData, takes a [Python regular expression (or "regex")](https://docs.python.org/3/howto/regex.html).  In regex, `$` means "end of line".  If you want to match a literal `$`, you would use `\$`.

**Comment by typo3ua** [comment]
Thanks!
