### ISSUE TITLE
show column headers for current row

### ISSUE THREAD

**Issue by need47** [saulpw/visidata#1172]
I rely on VisiData daily. Here is one feature I really like to have.

When you open a TSV file with header, highlight a row (Fig 1), then press Enter.  It displays the current row vertically (Fig 2) . What an awesome feature. If VisiData can display the column headers to the left, that would be super. So users know which is which, especially when some cells are empty.

Thanks for your favorable consideration.

Best,

![image](https://user-images.githubusercontent.com/1194165/140547944-e1c4ba73-0323-44dc-9ec5-4b96db6830f6.png)
![image](https://user-images.githubusercontent.com/1194165/140548032-ba7695b9-f364-40e4-9690-280dbb352bb9.png)

**Comment by saulpw** [comment]
Good idea, @need47!  I think this makes a lot of sense.
