### ISSUE TITLE
color_keystrokes: add a space also on the right

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1176]
### Discussed in https://github.com/saulpw/visidata/discussions/1169

<div type='discussions-op-text'>

<sup>Originally posted by **aborruso** November  4, 2021</sup>
Hi,
I think it would be better to have a space also on the right of keystrokes, it seems to me more readable.

Thank you

![image](https://user-images.githubusercontent.com/30607/140397099-a0719d38-97ba-48ce-9807-3fab29f253cf.png)
</div>

**Comment by anjakefala** [comment]
Added to develop! Let me know what you think. =) Thanks @aborruso!

**Comment by aborruso** [comment]
Wow, now it's much nicer, thank you very much

![image](https://user-images.githubusercontent.com/30607/140601944-2e81f7f3-8b5f-4714-a0fa-daded70feb77.png)
