### ISSUE TITLE
Add clean-names as command

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#1177]
To have a not cleaned column name is an every day thing, than I think `clean-names` should be a VisiData command, not only a command line option.

My request is to add [this](https://github.com/saulpw/visidata/discussions/1170#discussioncomment-1598311) to VisiData core.

Thank you

**Comment by saulpw** [comment]
Thanks for the request, @aborruso.  I'm not sure exactly where it belongs, but I can put it in vdplus for now!
