### ISSUE TITLE
[progress] Add progress to batch mode

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1182]
It would be great to have some feedback in batch mode for long running operations. Opening large files make it appear as though vd has stopped

**Comment by saulpw** [comment]
Good idea, @geekscrapy!  This is a very reasonable request.

**Comment by saulpw** [comment]
Is this what you wanted, @geekscrapy?

**Comment by geekscrapy** [comment]
Hi, unfortunately I still haven't been able to upgrade python to test all the new features... this will be top of my list when I do though!
Thanks for revisiting!
