### ISSUE TITLE
Saving multiple tables: no function to save as type , set options.save_filetype 

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#1185]
**Small description**

I open some tables form web source. When I try to save all I have `no function to save as type , set options.save_filetype ` error.

It happens when I save to current folder `./`. If I use `sqlite` format output I have no problem.

**Expected result**

To have all tables saved. 

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/30607/140935469-8368f7d2-1015-4d86-acda-881fefe8db7e.png)

`Ctrl-E` give me "no error"

**Steps to reproduce with sample data and a .vd**

My log

```
sheet	col	row	longname	input	keystrokes	comment
global		null_value	set-option			
			open-file	https://lab24.ilsole24ore.com/ecosistema-urbano/indexT.php	o	
indexT			select-rows		gs	select all rows
indexT	name		setcol-incr		gi	set current column for selected rows to incremental values
indexT			dive-selected		gEnter	open sheet with copies of rows referenced in selected rows
```

**Additional context**
Please include the version of VisiData.

I'm using saul.pw/VisiData v2.7dev.

Thank you

**Comment by geekscrapy** [comment]
Linked #1180

**Comment by geekscrapy** [comment]
Do you have options.save_filetype set to "csv" or "tsv"?

**Comment by aborruso** [comment]
> Do you have options.save_filetype set to "csv" or "tsv"?

Month ago it wasn't necessary https://github.com/saulpw/visidata/discussions/965#discussioncomment-661910

But I will try. Thank you

**Comment by aborruso** [comment]
@geekscrapy I have solved in this way, thank you

```
vd https://lab24.ilsole24ore.com/ecosistema-urbano/indexT.php --save-filetype=csv
```

**Comment by geekscrapy** [comment]
No problem, personally I think this is more of a useabilty bug.
Maybe I can put together a small pull request which asks for the path, then asks for the file type? Would this be more instinctive?

**Comment by geekscrapy** [comment]
Although, looking at the error in detail, it looks like the format string expects a file type but doesn't get it

**Comment by aborruso** [comment]
> Maybe I can put together a small pull request which asks for the path, then asks for the file type? Would this be more instinctive?

thank you very much
