### ISSUE TITLE
sqlite3.OperationalError on certain SQLite databases

### ISSUE THREAD

**Issue by mzmm70000** [saulpw/visidata#119]
Working with SQLite databases doesn't seem to be working as expected - I have included a sample SQLite database that causes an error when opened in VisiData. The traceback is as follows:
```
 Traceback (most recent call last):                                                            
   File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 1117, in exec_command       
     exec(cmd.execstr, vdglobals, LazyMap(self))                                               
   File "<string>", line 1, in <module>                                                        
   File "/usr/lib/python3.6/site-packages/visidata/vdtui.py", line 854, in push                
     vs.reload()                                                                               
   File "/usr/lib/python3.6/site-packages/visidata/loaders/sqlite.py", line 24, in reload      
     self.columns = self.getColumns(tblname)                                                   
   File "/usr/lib/python3.6/site-packages/visidata/loaders/sqlite.py", line 32, in getColumns  
     for i, r in enumerate(self.conn.execute('PRAGMA TABLE_INFO(%s)' % tableName)):            
 sqlite3.OperationalError: near "'2017-08-17 08:07:18.807'": syntax error
```
The command log that led to this error is also rather simple:
```
sheet	col	row	keystrokes	input	comment
			o	vd-debug.sqlite	open file
vd-debug_tables		0	^J		load the entire table into memory
vd-debug_DEBUG		1	^J		load the entire table into memory [sqlite3.OperationalError: near "'2017-08-17 08:07:18.807'": syntax error]
```

From what I can determine from a cursory inspection, VisiData confuses the date stored in the database with the table name and then fails on PRAGMA TABLE_INFO with an invalid table name. Here is the database:
[vd-debug-table.tar.gz](https://github.com/saulpw/visidata/files/1785157/vd-debug-table.tar.gz)

**Comment by saulpw** [comment]
The ENTER command to select the table to load, was also on the table sheet itself (due to how the sqlite loader is implemented).  So it was trying to load the date as a table.  Nothing is actually wrong; ENTER just shouldn't do anything on the sqlite table sheet (which are readonly).  Use `g'` to duplicate/freeze the sheet if you want to edit the data in memory (for example, to save as a different format like .tsv). 

This issue is addressed with b627e94e8fbb918e3d8fe8bfc6f8d06a469c9fd1.
