### ISSUE TITLE
Labeling for multi-column graphs is off if exactly 9 columns are plotted

### ISSUE THREAD

**Issue by tdussa** [saulpw/visidata#1198]
**Small description**

If you plot 9 data columns, then the first 8 columns are listed in the graph legend as expected (i. e., by their actual column name), but the ninth column is listed as `[other]`.  This makes sense for any plots that contain *more* than 9 data sets, but plotting *exactly* 9 columns doesn't make that necessary.

**Expected result**

The ninth column should be labeled with its column name.

**Steps to reproduce with sample data and a .vd**

```
cat > foo.csv << EOF
Nr.,A,B,C,D,E,F,G,H,I
0,1,2,3,4,5,6,7,8,9
EOF

cat > foo.vd << EOF
sheet	col	row	longname	input	keystrokes	comment
			open-file	foo.csv	o	
foo	Nr.		key-col		!	toggle current column as a key column
foo	Nr.		type-int		#	set type of current column to int
foo	A		type-int		#	set type of current column to int
foo	B		type-int		#	set type of current column to int
foo	C		type-int		#	set type of current column to int
foo	D		type-int		#	set type of current column to int
foo	E		type-int		#	set type of current column to int
foo	F		type-int		#	set type of current column to int
foo	G		type-int		#	set type of current column to int
foo	H		type-int		#	set type of current column to int
foo	I		type-int		#	set type of current column to int
foo			plot-numerics		g.	plot a graph of all visible numeric columns vs key columns
EOF

vd -p foo.vd
```

**Additional context**

Version 2.6.1.

**Comment by tdussa** [comment]
Update: The issue still exists in 2.7.1.  Also, find a screenshot attached.  The `[other]` plot should really be `I` instead.

![2021-11-16T11:35:13-Screenshot](https://user-images.githubusercontent.com/6197517/142058673-e6788811-ae53-4525-a17f-cfb8153150e4.png)

**Comment by tdussa** [comment]
Yeah, I probably agree that while VD is not behaving as expected, it's a long shot to call this a bug. XD

**Comment by tdussa** [comment]
FTR, 2.8.0 is also affected.

**Comment by anjakefala** [comment]
Thanks for suggesting a nice bit of polish. =) @tdussa, your suggested change is on `develop`!

It will be part of the next VisiData release (v2.9). If you want it sooner, you can install the `develop` branch with: `pip3 install git+https://github.com/saulpw/visidata.git`.
