### ISSUE TITLE
Visidata launching whenever a new terminal window is opened (macOS)

### ISSUE THREAD

**Issue by George9000** [saulpw/visidata#1199]
**Small description**
Using macOS Monterey (12.0.1) on an M1 laptop, after installation of VisiData with pipx, open Terminal.
VisiData immediately launches in the directory.

**Expected result**
Open terminal. VisiData does not launch unless called with `vd`.

**Actual result with screenshot**
Ctrl-E does not show errors.
![vd](https://user-images.githubusercontent.com/16549651/142037005-ebfa795b-63b8-4ec0-bd7d-a135de504bb1.png)

**Steps to reproduce with sample data and a .vd**
As above. Ctrl-D output below.
[command.txt](https://github.com/saulpw/visidata/files/7548640/error.txt)

**Additional context**
Python 3.9.8 with Pyenv 2.2.0 and Poetry 1.1.11

In .zshrc:
```
# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PIP_REQUIRE_VIRTUALENV=true
```
Please include the version of VisiData
v2.7.1

**Comment by ajkerrigan** [comment]
Ooh that's an interesting one @George9000 - and thanks for sharing your `.zshrc`! On a related note, do you have anything in `.zprofile` or `.zlogin` that might be invoking vd? Also, when you quit VisiData does it kill the whole terminal window or put you back at a zsh prompt?

**Comment by George9000** [comment]
Here are my complete `.zshrc`, `.zprofile`, and `.zshenv`. I don't have a `.zlogin` in my home directory.

And.... as I was posting these, I saw my mistake in `.zshrc`. I'm installing favorite software, including vd, on a new laptop. In the process of keeping a log of installs in my text editor, I mistakenly added the log entry for vd in my `.zshrc`. So every time a new terminal launched, it was executing `brew install saulpw/vd/visidata`. I like `vd`... but not _that_ much.

Thanks for your help.

.zhsenv
```
source ~/perl5/perlbrew/etc/bashrc
```

.zprofile
```
eval "$(/opt/homebrew/bin/brew shellenv)"
# Created by `userpath` on 2021-11-16 00:09:25
export PATH="$PATH:/Users/foo/.local/bin"
```

.zshrc
```
# python userpath and pipx modules path
#export PATH="/Users/foo/Library/Python/3.9/bin:$PATH"
## old path before manual adjustment below
#/Users/foo/Library/Python/3.9/bin:/Users/foo/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/foo/.local/bin

## per https://github.com/rybodiddly/Poetry-Pyenv-Homebrew-Numpy-TensorFlow-on-Apple-Silicon-M1
export PATH="/opt/homebrew/bin:/Users/foo/Library/Python/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:$PATH"
export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Created by `userpath` on 2021-11-16 00:09:25  ## seems to duplicate what's already in path; comment out
# export PATH="$PATH:/Users/foo/.local/bin"


# python3 Alias
alias python="python3"

# pipx
export PATH="~/.local/bin:$PATH"


### Add these next lines to protect your system python from
### pollution from 3rd-party packages
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
 
# commands to override pip restriction above.
# use `gpip` or `gpip3` to force installation of
# a package in the global python environment
# Never do this! It is just an escape hatch.
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
gpip3(){
   PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}



# Visidata
# ========
# brew install saulpw/vd/visidata
```

**Comment by anjakefala** [comment]
This was a spark of joy for my morning @George9000!

**Comment by ajkerrigan** [comment]
Glad you got it sorted out! Thanks for taking us along for the ride, it's nice to have company sometimes :).

**Comment by George9000** [comment]
I commend you on the positive, helpful responses to an issue. That is out of the ordinary and reflects well on the future of VisiData.
