### ISSUE TITLE
Undo functionality

### ISSUE THREAD

**Issue by TMiguelT** [saulpw/visidata#12]
I think adding undo/redo functionality is pretty important, as without it you have to restart the whole editor to undo your changes. Luckily it shouldn't be too difficult since most actions can be described as either a cell edit, or a row/column add or delete

**Comment by saulpw** [comment]
What I'm planning for this, is to have an editlog that tracks all edits and transforms in such a way that they can be replayed on top of the source sheet (the same one or a similarly structured one with different data).  Then you could jump to the editlog sheet (`M` for modifications, or `T` for transformations?  `E` is currently 'errorlog' but maybe that should move to `^E`) and:

* change or delete any edits manually
* push a new sheet with current/selected/all edits applied to the same or different source sheet
* `^S`ave the editlog for later reuse.
* '^R'eload on the source sheet re-applies the editlog

So undo would be a simple command:

`command('u', 'editlog.rows.pop(); reload()', 'undo last edit')`

or `Mgjdq^R`

if done manually. 

This would also allow for a tight test framework, with source + editlog + golden output being a complete functional test.

A possible problem is that `u`ndo might take a long time with a lot of edits or a large dataset.  But I feel like that should be dealt with in a different way.

**Comment by saulpw** [comment]
Implemented as of v0.59.
