### ISSUE TITLE
not able to open xls

### ISSUE THREAD

**Issue by Shahin-rmz** [saulpw/visidata#1203]
**Small description**
xls 2007 does not show an data
**Expected result**
show like a normal csv!
**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/32805117/142264415-ecfd95d9-b983-40fb-a1b9-b86cc2475227.png)

**Additional context**
2.6.1

Hello, 
first of all thanks for "vimalizing" spreadsheet world. from the moment I git to now Visidata always used it for my data.
recently I got an excel file, which is normal size and not that big.
but I can not open it via visidata. by other tools such as libre office calc or gnumuric it's fine.
what is the problem?
The excel is not confidential I will upload it here.

[Book1_edit.xlsx](https://github.com/saulpw/visidata/files/7557262/Book1_edit.xlsx)
Thanks for support

**Comment by ajkerrigan** [comment]
Hi @Shahin-rmz - looks like there are some empty cells in your sample sheet that were tripping up VisiData's Excel loader. Good news though, this looks like the same issue discussed in #1121 / resolved in VisiData 2.7!

**Comment by anjakefala** [comment]
Can confirm that it loads with 2.7.1! =) Please upgrade with `pip3 install --upgrade visidata`.

**Comment by Shahin-rmz** [comment]
with updating the Visidata the file works perfectly.
problem has been solved.
Thanks
