### ISSUE TITLE
How to merge lines in text file

### ISSUE THREAD

**Issue by Shahin-rmz** [saulpw/visidata#1206]
I have a .txt file, which can be opened without problem.
the problem is, each line will be shown as one separate row.
I may want to merge the rows together and see multiple lines as *one row*. But haven't seen such feature.
Also tried ```wrap``` but that was something else.
Thanks for considering this feature.

**Comment by geekscrapy** [comment]
Great idea, I sometimes have this usecase when working with log files which contain mulitline exceptions (e.g. java). I'd like to be able to define a starting match, and an ending match, anything in-between is merged.

**Comment by saulpw** [comment]
Hi @Shahin-rmz, you can use create a column that indicates which 'line' each line is supposed to be on, and `+list` on the text column, and then Shift+F (freq) on the new column to turn the text into a list of lines per group.  Then you can use `='\n'.join(text_list)` to create a column with the lines joined together.

I would need actual example data and the desired result to guide you further.
