### ISSUE TITLE
[] Question: How to reference a relative row/cell in an expression?

### ISSUE THREAD

**Issue by samuelludwig** [saulpw/visidata#1210]
Sorry I don't know if there's a better place to ask this question (I don't have an IRC setup)

Is there a way to reference a "cell above" in an expression? I have a table of a series of measurements, where each row `RX` in column `C` contains aggregate values of the rows above/before it, as in, `R1` may contain the value of the initial measurement `5`, and `R2` may contain the value `7` (`R1` plus the second measurement of `2`). I suppose you could say I'm looking to get the delta of each row in `C`. In excel, I would try to create a column whose values are (`$C$X` minus `$C$X-1`), subtracting the value of `RX` by the value above it `RX-1`. Am I able to do something similar with expressions in VisiData?

**Comment by saulpw** [comment]
Hi @samuelludwig, what you want is "windowed aggregates", which aren't implemented yet.  There's an open issue #1129 but it may be some time before it's implemented.  There are also some hacks to do what you want but the performance is not great so I'm reticent to share them.

You can also come chat with us on Discord if that's easier than IRC (https://visidata.org/chat for an invite).
