### ISSUE TITLE
[Progress] Progress instantly goes to 99%

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1214]
**Small description**
When I use Progress it seems to instantly go to 99%. See the repro below.

Additionally, it doesn't seem to want to take the `gerund`

**Expected result**
For the value to increase as the iterable returns values

Set the `gerund` as specified.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/143057845-25426af8-b7e2-45ae-9a4c-dd6c1ab954c4.png)

**Steps to reproduce with sample data and a .vd**
Add the following to `.visidatarc`. Notice that the Progress is instantly at 99%
```
@asyncthread
def asyncme():

    import time

    def iter():
        for i in range(1,100):
            time.sleep(1)
            yield i

    leng = len(list(range(1,100)))
    vd.status(f'length:{leng}')

    for i in Progress(iter(), gerund=f'doing stuff', total=leng):
        continue

addGlobals({'asyncme': asyncme})

Sheet.addCommand(None, 'asyncme', 'asyncme()')
```
Version 2.7.1

**Comment by anjakefala** [comment]
Related to #1175

**Comment by saulpw** [comment]
Hi @geekscrapy, a lot has been changed since v2.7, and this seems to work correctly for me now.  Let me know if you're still seeing issues with Progress in other cases.
