### ISSUE TITLE
[help-command] shows all commands, not subset for sheet feature/bug req

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1217]
- `help-commands` should show commands only relevant for the current sheet? But I don't think it does? I believe it shows all the commands? I dont see any filtering logic in `HelpSheet` regarding the sheet provided in the long command.
- `help-commands-all` shows all commands for all sheet types

This feature request is twofold, to check the above (`help-commands` in particular), and secondary, to request the menu item `Command list` to be changed to `Sheet command list` (uses `help-commands`) and a new item be created `Global command list` (uses `help-commands-all`)

**Comment by saulpw** [comment]
Thanks @geekscrapy!  Should be fixed now.
