### ISSUE TITLE
[sqlite views] SQLite views show no rows.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1222]
**Small description**
VisiData shows no rows in a  view.  The index sheet shows the zero rows in views.

**Expected result**
VisiData shows all the rows in a view.  The index sheet shows the correct count of rows in views.

**Actual result with screenshot**
Sorry no screenshot, but this will look the same as https://github.com/saulpw/visidata/issues/1111

**Steps to reproduce with sample data and a .vd**
It is easy to create sample data with the steps below, using the [`sample_data/employees.sqlite`](https://github.com/saulpw/visidata/blob/develop/sample_data/employees.sqlite) file.

`cp sample_data/employees.sqlite employees_view.sqlite`
`vd`
`gCtrl-X`, Import library: `sqlite3`
`exec-expr`:   `sqlite3.connect('employees_view.sqlite'); con.cursor().execute('create view emp_view as select * from emp'): con.commit()`
`Ctrl-O`: open the file:  `employees_view.sqlite`

VisiData should show that the `emp` and `emp_view` sheets have the same columns and rows, but it will show that `emp_view` is empty and has no rows.

**Additional context**
Latest `develop` branch version of VisiData.

**Comment by frosencrantz** [comment]
This was mentioned in https://github.com/saulpw/visidata/issues/1111 but there was no useful data to help debug this issue.

See additional notes here: https://github.com/saulpw/visidata/issues/1111#issuecomment-922348218

One simple way to see if a table is a view is if the `sql` table starts with `CREATE VIEW`

**Comment by saulpw** [comment]
I did add a view as you suggested, and loaded the resulting db into vd, and it seems to work fine for me.  I'm not sure what the difference is, that would cause it to not work for you.

![vd-sqlite-view](https://user-images.githubusercontent.com/236498/143724874-cdf0d6c0-8074-4b38-af7b-bcf15ff62658.png)

Also thanks for providing this explicit test case.  We will add this VIEW to the sample sqlite database to make sure it works.

**Comment by frosencrantz** [comment]
The behavior changed this year.   This link says that rowid is not supported for views in 3.36 or later. https://sqlite.org/forum/forumpost/250fe78dbcdca6e3?t=h

After importing sqlite3 you can run sqlite3.sqlite_version
What do you get?  I have 3.36.0, which doesn’t allow rowid access for views.

**Comment by anjakefala** [comment]
@frosencrantz I am actually trying to build Python on the newest version of `sqlite3`, in order to reproduce this bug, and am having a lot of trouble.

1. Can you check the fix on `develop`?
2. How did you build Python on the newest version of sqlite3?

**Comment by frosencrantz** [comment]
Haven't had much time to response recently...
1. Can confirm `develop` branch now works with sqlite3 views.  🎉 
2. Unsure.  It was using what came with my version of Python.   Not sure it matters, but the sqlite 3.36.0 release from June is no longer the latest version, there is now a 3.37.0 version. https://www.sqlite.org/changes.html
