### ISSUE TITLE
[all columns] The gC command doesn't show all SQLite columns

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1223]
**Small description**
The `gC` command from a SQLite index sheet doesn't show all the columns from all the tables.

**Expected result**
The `gC` command shows all the columns from all the SQLite tables in the database.  VisiData already knows all the columns, as part of loading the SQLite index sheet.

**Actual result with screenshot**
Sorry no screenshot.  (My system is to create those is no longer available)

**Steps to reproduce with sample data and a .vd**
Open a SQLite database with multiple tables, run the gC command.  notice that the ColumnIndex sheet doesn't include all columns from all the tables from the SQLite database.  It will only show columns from any tables that you visited before  running the `gC` column.

**Additional context**
Using the latest version on the `develop` branch of VisiData.

**Comment by saulpw** [comment]
`columns-all` shows all columns from all sheets on the sheets on the sheet stack.  If you push all the sheets and then do `columns-all` (`gsg Enter gC`) then it works as expected.  I've updated the helpstr for this command; we can update the docs in other places too.

**Comment by frosencrantz** [comment]
Thank you for looking.  I should know this, but how do you push all the sheets onto the sheet stack?

I feel like if you are on a SQLiteIndex sheet, and you run the `columns-all` command you would get all the tables/columns from the SQLite database.  VisiData is presenting all the tables, and has all the columns.

**Comment by saulpw** [comment]
Sorry, I put the commands in there but didn't make it explicit.  `gs` then `gEnter` to push them all.
