### ISSUE TITLE
[columns-all join] Pick join columns from a columns-all sheet.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1224]
Currently, you need to go to the SheetsSheet, select two or more sheets, and join them.  If you are doing a join based on columns, the sheets need to have the join columns already set as key columns.  If the key columns are not what you want to join on you need to first unset the current key columns, then set the key columns to join on, then you go back to the SheetsSheet to do the join.

For joins (such as inner/outer) based on columns it would be useful if the columns could be selected from the ColumnIndex sheet (gC).

**Comment by saulpw** [comment]
I think this is a good idea, @frosencrantz!  I went ahead and implemented it and bound it to `&` on the ColumnsSheet (and unbound `&` for the `join-cols` command that it was previously used for on the ColumnsSheet).  It won't work for the `extend` jointype yet but I believe it should work for the other types.  Let me know what you think.

**Comment by frosencrantz** [comment]
Yippee!  I did some simple tests, and this appears to work.  Thanks @saulpw, this is a nice interface improvement!
