### ISSUE TITLE
Color number is greater than COLORS-1 (-1)

### ISSUE THREAD

**Issue by ajkerrigan** [saulpw/visidata#1227]
**Small description**

When running VisiData on Python 3.10.0 and replaying saved command log files, I was _sometimes_ seeing an error related to colors while drawing the right status.

**Expected result**

There are no errors, and everyone is happy, and my tea is hot enough to drink but not hot enough to burn my tongue.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

```
Traceback (most recent call last):
  File "/home/aj/.local/pipx/venvs/visidata/lib/python3.10/site-packages/visidata/statusbar.py", line 194, in drawRightStatus
    cattr = colors.get_color(coloropt)
  File "/home/aj/.local/pipx/venvs/visidata/lib/python3.10/site-packages/visidata/color.py", line 153, in get_color
    r = self.colorcache[optname] = self._colornames_to_cattr(colornamestr, precedence)
  File "/home/aj/.local/pipx/venvs/visidata/lib/python3.10/site-packages/visidata/color.py", line 121, in _colornames_to_cattr
    fg, bg, attrlist = self.split_colorstr(colornamestr)
  File "/home/aj/.local/pipx/venvs/visidata/lib/python3.10/site-packages/visidata/color.py", line 93, in split_colorstr
    if self._get_colornum(x) is not None:   # only set known colors
  File "/home/aj/.local/pipx/venvs/visidata/lib/python3.10/site-packages/visidata/color.py", line 114, in _get_colornum
    curses.init_pair(255, r, 0)
ValueError: Color number is greater than COLORS-1 (-1).
```

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

I hit this error using [this vdj file](https://github.com/ajkerrigan/advent_of_code/blob/master/2021/02/part1.vdj)... but not consistently :-/.

**Additional context**
Please include the version of VisiData.

v2.8dev (e53c1a5f82bdb2f3ebd6843ac8a6b00c14f4ebe4).

There were [curses changes](https://docs.python.org/3/whatsnew/3.10.html#curses) in Python 3.10 which may have something to do with this. When I did hit this error, I found that making a local change like [this](https://github.com/ajkerrigan/visidata/commit/b32a582d1b63f43c626391843b0308476c4ea355) worked around it. But... I don't know if that's a reasonable thing to do.

So this _may_ end up just being a placeholder issue in case someone else runs into the same problem while doing stuff that's less weird. Feel free to kondo in the meantime!

**Comment by anjakefala** [comment]
> curses.init_color(color_number, r, g, b)
>    Change the definition of a color, taking the number of the color to be changed followed by three RGB values (for the amounts of red, green, and blue components). The value of color_number must be between 0 and COLORS - 1. Each of r, g, b, must be a value between 0 and 1000. When init_color() is used, all occurrences of that color on the screen immediately change to the new definition. This function is a no-op on most terminals; it is active only if can_change_color() returns True.

> curses.init_pair(pair_number, fg, bg)
>    Change the definition of a color-pair. It takes three arguments: the number of the color-pair to be changed, the foreground color number, and the background color number. The value of pair_number must be between 1 and COLOR_PAIRS - 1 (the 0 color pair is wired to white on black and cannot be changed). The value of fg and bg arguments must be between 0 and COLORS - 1, or, after calling use_default_colors(), -1. If the color-pair was previously initialized, the screen is refreshed and all occurrences of that color-pair are changed to the new definition.

Of note: **The value of fg and bg arguments must be between 0 and COLORS - 1, or, after calling use_default_colors(), -1.**

I wonder if this is related to the **(-1)** in  `ValueError: Color number is greater than COLORS-1 (-1).`

**Comment by ryanmjacobs** [comment]
EDIT:
(This might be a completely separate error from @ajkerrigan, neverless I can't run visidata without exporting the TERM variable.)

I ran into a similar issue today. I can reproduce/fix my particular error on Docker.

You might want to try running `TERM=xterm-256color visidata` on your system.

## to reproduce
```
$ docker run -it --rm --entrypoint /bin/bash python:3
$ pip install visidata
$ vd
Traceback (most recent call last):
  File "/usr/local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/local/lib/python3.10/site-packages/visidata/main.py", line 327, in vd_cli
    rc = main_vd()
  File "/usr/local/lib/python3.10/site-packages/visidata/main.py", line 292, in main_vd
    run(vd.sheets[0])
  File "/usr/local/lib/python3.10/site-packages/visidata/vdobj.py", line 34, in _vdfunc
    return func(visidata.vd, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 333, in run
    ret = vd.mainloop(scr)
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 201, in mainloop
    self.draw_all()
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 105, in draw_all
    vd.draw_sheet(vd.win1, ss1[0])
  File "/usr/local/lib/python3.10/site-packages/visidata/mainloop.py", line 30, in draw_sheet
    scr.bkgd(' ', colors.color_default)
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 62, in __getattr__
    return self.get_color(optname).attr
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 153, in get_color
    r = self.colorcache[optname] = self._colornames_to_cattr(colornamestr, precedence)
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 121, in _colornames_to_cattr
    fg, bg, attrlist = self.split_colorstr(colornamestr)
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 93, in split_colorstr
    if self._get_colornum(x) is not None:   # only set known colors
  File "/usr/local/lib/python3.10/site-packages/visidata/color.py", line 114, in _get_colornum
    curses.init_pair(255, r, 0)
ValueError: Color pair is greater than COLOR_PAIRS-1 (63).
```

## solution
```
$ export TERM=xterm-256color
$ vd
# works as expceted
```

**Comment by ajkerrigan** [comment]
Interesting, I've had TERM set to xterm-256color the whole time so that doesn't seem to be the issue. Good call checking it though @ryanmjacobs - I honestly wasn't sure!

I did nail down a consistent repro though...

From a clean (or cleanish) Python 3.10.0 environment, in a directory with the attachment from this comment downloaded/extracted:

```
python -m pip install git+https://github.com/saulpw/visidata#8afbe2f903e817e796643b27ffb158638601880a
python -m visidata --config=/dev/null --visidata-dir=./.visidata -b -p 1227-repro.vdj
```

(Context: `--config=/dev/null` to take any of my `.visidatarc` settings out of the picture, `--visidata-dir=./.visidata` to avoid plugin side effects)

Removing the `-b` may land you at a place where you can `Ctrl-E` to see an error traceback, or may completely whack out your terminal. I've seen both on my machine.

There was some IRC discussion about commenting out [this line](https://github.com/saulpw/visidata/blob/d655caf44295c3c95af397206a46f1f637681367/visidata/mainloop.py#L293), but that had no effect. The only things I've seen fix it so far are falling back to a Python version earlier than 3.10, or trying [this blunt change](https://github.com/ajkerrigan/visidata/commit/b32a582d1b63f43c626391843b0308476c4ea355).

Thanks for the ideas and additional context though @ryanmjacobs and @anjakefala ! If there are any other things I can try from here lemme know :). 

[vd-1227-repro.zip](https://github.com/saulpw/visidata/files/7657862/vd-1227-repro.zip)

**Comment by anjakefala** [comment]
```
kefala@rivendell:git/visidata ‹develop*›$ python3.10 -m visidata -b -p 1227-repro.vdj                                                                      
opening 1227-repro.vdj as vdj
Think about what you're doing.
ValueError: Color number is greater than COLORS-1 (-1).
ValueError: Color number is greater than COLORS-1 (-1).
ValueError: Color number is greater than COLORS-1 (-1).
ValueError: Color number is greater than COLORS-1 (-1).
replay aborted during open-file

kefala@rivendell:git/visidata ‹develop*›$ python3.6 -m visidata -b -p 1227-repro.vdj                                                                       
What size do you want to be?
opening 1227-repro.vdj as vdj
"test.txt"
opening test.txt as txt
replay complete
```

**Comment by ajkerrigan** [comment]
Okie more info on this thanks to a hypothesis from @anjakefala . It looks like one magic problem combo is this [replay_sync](https://github.com/saulpw/visidata/blob/b8afb57df2dca088bdabc3624d51951ff6e80980/visidata/main.py#L303) call when there's a command in the log that takes input. In those cases I see this callstack-o-breadcrumbs:

```
_get_colornum (/home/aj/code/visidata/visidata/color.py:118)
split_colorstr (/home/aj/code/visidata/visidata/color.py:93)
_colornames_to_cattr (/home/aj/code/visidata/visidata/color.py:121)
get_color (/home/aj/code/visidata/visidata/color.py:153)
drawRightStatus (/home/aj/code/visidata/visidata/statusbar.py:194)
input (/home/aj/code/visidata/visidata/_input.py:322)
inputFilename (/home/aj/code/visidata/visidata/_open.py:9)
execCommand2 (/home/aj/code/visidata/visidata/basesheet.py:69)
execCommand (/home/aj/code/visidata/visidata/basesheet.py:167)
replayOne (/home/aj/code/visidata/visidata/cmdlog.py:326)
replay_sync (/home/aj/code/visidata/visidata/cmdlog.py:348)
main_vd (/home/aj/code/visidata/visidata/main.py:303)
vd_cli (/home/aj/code/visidata/visidata/main.py:327)
<module> (/home/aj/code/visidata/visidata/__main__.py:3)
```

And if I swap in an inputless command to `1227-repro.vdj` (say `s/open-file/resize-cols-max/` for example) the color error goes away. Anja was right on the money with this, that the replay bits are firing before `run()` and trying to use colors that haven't yet been initialized.

Adding these lines right before [this try block](https://github.com/saulpw/visidata/blob/6feb4c523e14188ef24614b9254ea4e72005c269/visidata/color.py#L114) as a test also prevents the error:

```
curses.initscr()
curses.start_color()
```

So maybe that means there's a better/additional spot we need to call `initCurses()` from or something? Sorry still more questions than answers.

**Comment by anjakefala** [comment]
@ajkerrigan Thanks so much for all of your work on this bug!! This was a big one, and will prompt an update of homebrew and debian at least. 

@ryanmjacobs, this is a good issue to document, and I am going to move it to its own place!
