### ISSUE TITLE
Visidata fails to recognize Postgres loader.

### ISSUE THREAD

**Issue by ryanmjacobs** [saulpw/visidata#1229]
**Small description**
Can't connect to Postgres using Visidata 2.7.1. Tested that it works on 2.5.

**Expected result**
It should connect to Postgres.

**Actual result with screenshot**
```shell
ryan@ww ~ $ vd postgres://ryan@localhost/ryan
Error: no loader for url scheme: postgres
```

**extra**:
I have psycopg2 installed. Everything works fine on 2.5 -- I just took a guess and picked an older version -- no idea if it works on 2.6, etc.

It has something to do with the `_open.py` loader, around line 46:
```python
        openfunc = getattr(vd, openfuncname, None) or vd.getGlobals().get(openfuncname, None)
```
openfunc never gets returns properly. I've tried `postgres` and `postgresql` (given the recent patch that someone merged)

**Comment by anjakefala** [comment]
Hi @ryanmjacobs! Thanks for filing a bug report. This is now on `develop`, and will be in the next release (tbr next week). 

If you would like to get `develop` earlier, the command is `pip3 install --upgrade git+https://github.com/visidata.git@develop`
