### ISSUE TITLE
Quitting sheet with "quit-sheet-free" throws error

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1236]
**Small description**
When `quit-sheet-free` is used on multiple sheets it seems to throw an error

**Expected result**
Quit the sheet as per `quit-sheet-free`

**Actual result with screenshot**
Open vd with:
`vd https://raw.githubusercontent.com/saulpw/visidata/stable/sample_data/StatusPR.csv https://raw.githubusercontent.com/saulpw/visidata/stable/sample_data/StatusPR.csv --config=/dev/null`

Then do `quit-sheet-free` on the first sheet (no issues), then do a `quit-sheet-free` on the second sheet. It will throw the following error:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/visidata/basesheet.py", line 162, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/local/lib/python3.8/site-packages/visidata/basesheet.py", line 66, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "quit-sheet-free", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "/usr/local/lib/python3.8/site-packages/visidata/sheets.py", line 1100, in releaseMemory
    vd.allSheets.remove(vs)
ValueError: list.remove(x): x not in list
```

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
v2.8 (7848ba98ae2faefd24a9098d17d0cc001aec7a08)

**Comment by geekscrapy** [comment]
It seems to be due to the fact that when multiple sheets are provided on the cli, only the top one is loaded (and added to `vd.allSheets`). 
When you quit with `quit-sheet-free` the next sheet in the stack isn't loaded into `vd.allSheets`

**Comment by anjakefala** [comment]
Thanks for the bug report @geekscrapy =) Should be fixed on develop.
