### ISSUE TITLE
Need some way to save different type than file extension

### ISSUE THREAD

**Issue by ssadedin** [saulpw/visidata#1242]
We have a lot of TSV files saved with `.txt` extensions. The problem is, I can't edit them at all with VisiData because even when I give it every option to try and tell it that these are TSV files, on save it ignores them and treats them as text files, losing the headers and inserting spaces etc.

For example even when I run

```
visidata --filetype=tsv --save-filetype=tsv test.txt
```

When I press Ctrl-s in Visidata and change the extension back to `.txt` it ignores these flags and overwrites my original file
with the text format.

I'm not sure what the most ergonomic / clear / simple way to achieve this functionality is, but currently its quite confusing that you can give it these very explicit sounding flags and it still ignores you.

One option I'd suggest is to allow to map extensions, for example - let me treat txt as tsv:

```
visidata --extension-format txt=tsv
```

This would perhaps have an upside of offering more flexibility for supporting custom extensions for other random file types too? Eg: if someone has a `.foo` file that happens to be CSV they can program Visidata to simply treat `.foo` as CSV without any other arguments.

**Comment by saulpw** [comment]
Hi @ssadedin, I see your point.  I guess the `save-filetype` option should override the file extension instead of the other around.  This is now changed on develop branch and will be in the next release.

**Comment by jsvine** [comment]
An idea, though I haven't thought it fully through: What if there were a long-command (perhaps `save-filetype`?) that allowed you to save the current sheet as an arbitrary filetype of your choosing? First, you'd get a prompt re. the filetype, and then one for the save path — or vice versa?

**Comment by saulpw** [comment]
Interesting idea, @jsvine!  At the moment though, we can't have multiple input values for a command.  This may change in the future when VisiData gets "forms" and we can put an arbitrary dict in the input field of the command log.

**Comment by jsvine** [comment]
Ah, right! Sounds good 👍

**Comment by ssadedin** [comment]
thanks @saulpw appreciate the followup!

**Comment by saulbert** [comment]
Update from the `per-path-filetype` work (PR #3139): input and output formats are now separate, so a mis-extensioned file can be opened and saved as its real format.

- `-f` / `-if` / `--input-filetype` sets the loader for input paths (e.g. `vd -f tsv data.txt` opens a `.txt` that is really TSV).
- A new `-of` / `--output-filetype` sets the saver for the `-o` output, overriding its extension:

  ```
  vd -b -f tsv data.txt -of tsv -o cleaned.txt   # save as TSV despite the .txt name
  ```

- Interactively, the `open-file` and `save-sheet` prompts have an *as filetype:* field for the same override.

Together with the confirm-before-fallback change (#3014), VisiData no longer silently rewrites a known-format file as plain text on save.

[this message written by Claude Opus 4.8 and approved by @saulpw]
