### ISSUE TITLE
[menu/input]  Some minor imperfections.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1243]
Noticed several small issues in the vd UI.  Great for someone looking to help out and contribute or anyone to do some minor polishing.

- Input history
   - [x] Choosemany() doesn’t provide a history based on type.  Like it would be useful for when doing joins.  It is using general histiory.
   -  [x] g^X import-module  doesn’t tag the type of input.  So history is not as useful.
- Menu
  - [x] Edit>copy> selected rows — doesn’t exist
  - [x] Row > toggle.   — Name is all lowercase

**Comment by saulpw** [comment]
Thanks @frosencrantz, I pushed fixes for 3 of these. chooseMany would be a bigger change, and should be replaced by a much better mechanism anyway as for #1027

**Comment by frosencrantz** [comment]
Thanks, @saulpw!  I am really interested in #1027 being added.  I feel like the menu system works really well, and makes VisiData more accessible to new users. I look forward to seeing how you implement #1027.
