### ISSUE TITLE
Narrow terminals/wide headings  garble/hide status line info

### ISSUE THREAD

**Issue by sirg** [saulpw/visidata#1245]
**Small description**
80-column terminal causes status line info to be incomplete or hidden, when a column has a wide heading. Particularly inconvenient on operations, that prompt and output on the status line, e.g. column agg (memo-aggregate / z+).

**Expected result**
- Prompts, responses and results are visible on the status line in preference to other status line info
- Maybe a way to recall last computed result that appeared on the status line?

**Actual result with screenshot**
[Prompt](https://drive.google.com/file/d/130DHeGvcGHunKwcPc1gege0HjAbQOVaA/view)
[Result](https://drive.google.com/file/d/17XrA_YOjy8xF0OK3TKiCE0ed6glAMyxm/view)

**Steps to reproduce with sample data and a .vd**
Easy to reproduce with any data where column heading is 20+ chars:
- set term width to 80 columns
- load a table
- choose a column with wide heading (or create one)
- sum the column

**Additional context**
v2.7.1

**Comment by anjakefala** [comment]
Thank you for this issue! Related to https://github.com/saulpw/visidata/issues/1035.

> Maybe a way to recall last computed result that appeared on the status line?

I just wanted to let you know about `Ctrl+P` =). It opens the **StatusSheet**, which has a record of status outputs.

**Comment by sirg** [comment]
That's awesome - beats having to resize the term and redo the command. Thanks!

**Comment by saulpw** [comment]
Fixed by moving the status messages to the sidebar.
