### ISSUE TITLE
Unable to edit SQLite data

### ISSUE THREAD

**Issue by dettmering** [saulpw/visidata#1249]
I am unable to edit any data in my SQLite database. The database is not protected in any way. 

**Expected result**

After selecting a cell and pressing 'e', I expect to be able to edit the text and save it by pressing 'Enter'.

**Actual result with screenshot**
I get an error message.

![grafik](https://user-images.githubusercontent.com/1725685/146749545-5a624e0d-e791-4007-be4a-514f79f671d6.png)

**Steps to reproduce with sample data and a .vd**
The actual db file cannot be shared openly. 

```
till@mars:~/doc/cv$ cat cmdlog-1.vd
sheet   col     row     longname        input   keystrokes      comment
                        open-file       db/cv.db        o
cv_tables               2       dive-row                ^J
cv_SKILLS       ID      キ1     edit-cell       1       e
cv_SKILLS       NAME_DE キ2     edit-cell       sdfcsdf e
cv_SKILLS       NAME_DE キ62    edit-cell       B blah ootstrap 4       e
```

**Additional context**
v1.5.2

**Comment by dettmering** [comment]
I retract my bug report, had an old version installed. Please consider updating your website or the apt packages. `apt instal visidata` installs a really old version.

**Comment by anjakefala** [comment]
What update to the website would have been helpful?

**Comment by dettmering** [comment]
Remove any reference to `apt install` to avoid having users install old versions.
