### ISSUE TITLE
Connection to mysql fails

### ISSUE THREAD

**Issue by twutz** [saulpw/visidata#1252]
**Small description**
Since VisiData version 2.7 I get the error 'no loader for url scheme: mysql' when I try to connect to MySQL with 'vd mysql://username:password@hostname:port/database'.

**Expected result**
VisiData table with MySQL tablenames

**Actual result with screenshot**
Error: no loader for url scheme: mysql

**Steps to reproduce with sample data and a .vd**
pip install -U visidata==2.7(2.7.1 or 2.8)
mysql://username:password@hostname:port/database

**Additional context**
If I go back to version 2.6.1 with 'pip install -U visidata==2.6.1', everything works as expected again

**Comment by anjakefala** [comment]
I believe this was fixed in `v2.8`! https://github.com/saulpw/visidata/issues/1229

Can you please confirm?

**Comment by twutz** [comment]
In v2.8 it was fixed for postgre but it still exists for mysql.

**Comment by anjakefala** [comment]
The fix was merged here! https://github.com/saulpw/visidata/pull/1257

It will be in the next release of VisiData. =)

To use it at this point: `pip3 install git+https://github.com/saulpw/visidata.git@develop`

**Comment by twutz** [comment]
Many thanks to all involved and a happy new year
