### ISSUE TITLE
Progress of GZIP data appears to calculate from compressed size

### ISSUE THREAD

**Issue by bitwisecook** [saulpw/visidata#1255]
**Small description**
When opening a log that's gzip'd the progress percent appears to be calculated from the compressed size. Here I'm using f5log, internally that just uses `iterload()` with no wrapper for progress.

**Expected result**
Parsing should finish at 100%

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/2267430/147278976-a77eb6fe-9384-4a81-ae67-846f4e032a08.png)

**Steps to reproduce with sample data and a .vd**
Open any compressed log large enough to take time to parse and go to shift-S.
[sheets.vd.txt](https://github.com/saulpw/visidata/files/7770896/sheets.vd.txt)

**Additional context**
2.9.0-dev with f5log 0.2.4

**Comment by anjakefala** [comment]
Most likely related to https://github.com/saulpw/visidata/issues/1175 =)
