### ISSUE TITLE
new option: edit if 0-9 are pressed

### ISSUE THREAD

**Issue by schmeisers** [saulpw/visidata#126]
scim has a handy option where upon pressing a digit 0-9, the current cell is put into edit mode and the pressed digit is entered (and the cell stays in edit mode).  Since there are no keyboard shortcuts that begin with a digit, could this be an option in visidata?  

Or if this can be done in `.visidatarc.py` I'd appreciate some help with the correct commands!

**Comment by saulpw** [comment]
Hi @schmeisers, thanks for the suggestion.  

I've consciously avoided binding anything to `0-9` keys, leaving them available for things like user-defined macros.  (In fact, most of my experimental commands are initially bound to '1' before I know where they should go).  I've thought about using them for some other shortcuts, like quickly jumping to sheet N, but nothing has been compelling enough yet.  vim users of course want commands to be prefixable with a number, which is an interesting idea but doesn't fit the command structure.

I feel like the particular behavior you're suggesting would be part of a more sophisticated 'data-entry' mode, which I can see being totally useful, but would need a fair amount of additional design work.

I thought about how you might add this functionality yourself into `.visidatarc`, and unfortunately it's not quite possible in the current version.  Two changes are necessary:

1. A small tweak to `editCell` would allow a value to be passed in (like the other `input()` functions); this is entirely reasonable and I went ahead an implemented it for consistency (a05d47a7d84dcff0cb807ad2df4be9f9c79ff395).

2. The second problem is that the line editor clears the initial/default value on first keypress. Of course that's not what you want at all.  So I added an `append` kwarg to the line editor, which puts the cursor at the end of the initial value and disables the clearing behavior.  (6b4159f8856d1aaec737a6a34942dc7dcbd31ece)

With these changes, a command for each digit could be added to your `.visidatarc`:

`globalCommand('1', 'cursorCol.setValues([cursorRow], editCell(cursorVisibleColIndex, value="1", append=True))', 'replace cell value with input starting with 1')`

(I just took the generic command for `e`dit and added the `value="1", append=True` kwargs).

This seems to work for me.  The supporting changes will be rolled into the next release, and in the meantime you can use the `dev` branch if you like.  Let me know if this does what you need or if it needs to be tweaked some more.

**Comment by schmeisers** [comment]
Thanks for the quick update!  I'd be happy to try this out but I'm not sure how to run from source.  (not a python coder)

**Comment by saulpw** [comment]
@schmeisers That's okay, look for v1.2 and you can put it in your `.visidatarc` then.

**Comment by Freed-Wu** [comment]
> vim users of course want commands to be prefixable with a number, which is an interesting idea but doesn't fit the command structure.

I am curious about why it doesn't have number prefix :smile: Is it because number prefix is very hard to realize?
