### ISSUE TITLE
How to convert "long" format into "wide" one?

### ISSUE THREAD

**Issue by mukund109** [saulpw/visidata#1260]
Hi, thanks for building this amazing tool.

I have a source table which looks like this.

| id | var | val  |
|----|----------|--------|
| 01 | state    | Delhi  |
| 01 | airport  | IGI    |
| 02 | state    | Mumbai |
| 02 | airport  | BOM    |

and I'm trying to do the reverse of a melt operation

| id | state | airport |
|----|-------|---------|
| 01 | Delhi | IGI     |
| 02 | Mumbai | BOM     |

I'm not able to figure out how to do it. Would be great if someone could guide me in the right direction.

**Comment by saulpw** [comment]
Make `id` a key column with `!`, use `+max` on the `val` column, and press `Shift+W` to pivot on the `var` column.

**Comment by mukund109** [comment]
Thanks a lot @saulpw
