### ISSUE TITLE
Does not properly install on windows

### ISSUE THREAD

**Issue by schiltz3** [saulpw/visidata#1268]
## Small description

When following the instructions to install on windows, the vd file created is for Linux. It starts with a shebang and does not have an extension, so a dialog always opens asking what program you want to open it with.
Secondly, "curses" does not come on windows, so you have to install "windows-curses" with pip.

## Expected result

After I install visidata I should be able to call `vd <filename>` from my terminal.

## How I Fixed

I fixed the issue by removing the shebang from the vd file, and renamed it to vd.py so that it would open with python
This is the resulting file:
```python

import visidata.main

if __name__ == '__main__':
    visidata.main.vd_cli()
```

The command ` vd.py <filename>` opens the file correctly
## Additional context

Visidata v2.8

**Comment by saulpw** [comment]
Thanks for the report, @schiltz3.  How did you install VisiData on Windows in the first place?

**Comment by daviewales** [comment]
In my experience, `pip install windows-curses visidata` should get it working on Windows (e.g. in PowerShell).
However, this gives me a `visidata.exe` command, not a `vd` command.

Normally I use VisiData from WSL, rather than PowerShell, as it's very slightly glitchy in PowerShell with windows-curses.

**Comment by saulpw** [comment]
Thanks @daviewales, that's helpful.  The executable on Windows is named `visidata.exe` for some stupid Windows reason (I forget exactly which one).  @schiltz3 has a good solution if someone wants to type `vd.py` instead of `visidata`.

**Comment by schiltz3** [comment]
> Thanks for the report, @schiltz3. How did you install VisiData on Windows in the first place?

Sorry for responding to this so late.

I installed visidata through pip `pip3 install visidata`

**Comment by ghost** [comment]
Would it be possible to make `windows-curses` a platform specific dependency, so it installs automatically when running `pip install visidata` on Windows?

e.g. using [Environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) in `setup.py`?

**Comment by saulpw** [comment]
Yes, good idea @davidwales.  There are some windows-specific things in vdplus we can pull back in, too.
