### ISSUE TITLE
Enter key does not work (only) on the menu, on Linux

### ISSUE THREAD

**Issue by gphilip** [saulpw/visidata#1269]
**Pressing the Enter key has no effect on menu items; Enter seems to work fine elsewhere**

Pressing Enter on any *menu* item has no effect. 

Pressing Enter on *other parts* of the screen *does* have the intended effect:

1. On the screen that shows the directory listing, pressing Enter on a file name *does* open the file
2. If I press Enter on a row in one sheet, the contents of that row *do* get displayed in a new screen.

All other keys (that I tried) seem to be working fine.

This seems to be similar to #1154 and #741 , except this time it is on Linux.

**Expected result**

The menu item should get "executed".

**Additional context**
This is on Linux Mint:

$vd --version
saul.pw/VisiData v2.7

$uname -a
Linux Desktop 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Visidata was installed in Anaconda, with

$ conda install -c conda-forge visidata

**Comment by gphilip** [comment]
I face the exact same issue when I installed Visidata (using conda, the same way as above) on a different machine, this one running Ubuntu 20.04.

**Comment by anjakefala** [comment]
Hi @gphilip!

I just updated the version of VisiData on conda to `v2.8`. =) Thanks for the reminder. Please try updating it now, and using `Enter` on the menu.

**Comment by gphilip** [comment]
The Enter key works as expected after I updated VisData to v2.8. Thank you, @anjakefala !
