### ISSUE TITLE
[Wishlist] Searchable help menu (like macOS help menu)

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1272]
In macOS, there is a search bar in the Help menu.
Searching can be used to find menu items when you know the name of what you want to do, but don't know what menu it's in.

https://user-images.githubusercontent.com/2499066/149930570-44a98a8f-d47b-44e9-af20-b68bbac09474.mp4

 Could something similar be added to the Help menu in Visidata?

**Comment by saulpw** [comment]
Hi @daviewales, this is an interesting idea.  I can see how this would be useful from the menu system itself, but as a workaround, you can use `z Ctrl+H` to go to the Commands Sheet, and then `g/` (or other commands) to search there.

Kondo'ed for now.

**Comment by geekscrapy** [comment]
Just wanted to +1 this idea for the future. That is all ☺️
