### ISSUE TITLE
Not recognizing `CTRL` when running in tmux

### ISSUE THREAD

**Issue by robertdefilippi** [saulpw/visidata#1273]
**Small description**

When running `visidata` inside a tmux window, the `ctrl` key is not being recognized. So, common commands like `ctrl h` cannot be called. I don't have this problem when running `visidata` outside of tmux.

**Expected result**

Have the `ctrl` key be recognized

**Additional context**

I would like to be able to send my logs, however, I cannot without the use of the `ctrl` key. I can see `tmux` recognizes the `ctrl` key, because I can see call `tmux` commands. I'm getting the impression the `ctrl` is just not being recognized first by `tmux` and not by `visidata`/

```
$ vd --version
saul.pw/VisiData v2.8
```

**Comment by saulpw** [comment]
Hm, that's really weird, @robertdefilippi.  Ctrl isn't a separate key so this can't really happen as you're describing.  If you try all Ctrl+Letter combinations, do *any* of them do anything (or show up in the lower status bar)?  What OS/version are you using, what terminal/version, which version of tmux?

**Comment by robertdefilippi** [comment]
Actually I do ^^

I'm seeing output for some of the commands but not others. This leads me to believe the keys are simply remapped and not being registered.

I'm going to close this ticket, because the issues seems to be local rather than with `visidata`.

Thanks for the help @saulpw
