### ISSUE TITLE
Row down in "exploded row" view [] 

### ISSUE THREAD

**Issue by fourjay** [saulpw/visidata#1275]
When hitting return/enter visidata enters (for want of a better phrase) "vertical expanded row" view with name/value pairs for the row displayed vertically. I'd like a keyboard "next row" function.

Use case, to page through long rows which extend well past 150 characters in horizontal mode.
I've wanted to use visidata to explore long rowed datasets, either with many values or with long individual values.
Paging through a vertical version of rows would be nice. as it'd give a very quick way to get the sense of a small block of rows in their totality.

**Comment by ajkerrigan** [comment]
Hi @fourjay - while it's certainly not as useful as native support, I had a similar need a little while back and wrote a plugin to add those functions/keybindings. It's possible that it needs some tweaks, but a quick test with the latest VisiData version seems to handle the use case I think you're describing:

[![asciicast](https://asciinema.org/a/463306.svg)](https://asciinema.org/a/463306)

In case that sounds like a useful road, the plugin is available [here](https://github.com/ajkerrigan/visidata-plugins/blob/master/plugins/split_navigation.py). Happy to talk through any questions/issues that pop up if you give it a shot.

**Comment by anjakefala** [comment]
May I add this to plugins.jsonl, @ajkerrigan? =)

**Comment by ajkerrigan** [comment]
> May I add this to plugins.jsonl, @ajkerrigan? =)

Hmm I like the idea! But it needs a shower. Opened ajkerrigan/visidata-plugins#18 to track some tidying I'd want to take care of first.

**Comment by anjakefala** [comment]
@ajkerrigan has kindly updated the plugin! We have added it to plugins.jsonl.

To install the plugin you can follow the instructions here: https://github.com/ajkerrigan/visidata-plugins#parent_navigation-helpers-for-navigating-a-parent-sheet-from-its-child

You can also install it through the **PluginsSheet**. 
* Within VisiData, press Spacebar, and type *open-plugins*
* Scroll down to `parent_navigation` and press `a`.
* If `parent_navigation` does not appear in your `~/.visidatarc`, please empty your cache by removing `~/.visidatarc/cache`, and then repeat the steps.
* In your `~/.visidatarc` add

```
TableSheet.bindkey(ALT + "j", "next-parent-row")
TableSheet.bindkey(ALT + "k", "prev-parent-row")
```

Where `ALT + "j"` can be whichever binding you like, but that is a great suggestion by @ajkerrigan. I like its elegance.

Many, many thanks to @ajkerrigan!
