### ISSUE TITLE
[2.9dev] using "d" to delete a selected row doesn't remove from sheet.selectedRows

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1284]
**Small description**
When a row is deleted with `d`, it is not removed from `sheet.selectedRows`.

**Expected result**
For the row to be removed like when `gd` is used.

**Steps to reproduce with sample data and a .vd**
1. open with `vd --config/=/dev/null file.csv`
2. select a row with "`t`" 
3. delete that row with "`d`"
4. `=vd.sheet.selectedRows` < should be 0

**Comment by anjakefala** [comment]
This is in develop now! =)
