### ISSUE TITLE
Feature request: Transposing rows and columns

### ISSUE THREAD

**Issue by adelq** [saulpw/visidata#129]
Is it possible to transpose (switch) the rows and columns in visidata? If not, it would probably be useful in a lot of scenarios, where the transpose of the data is relevant.

**Comment by saulpw** [comment]
Hi @adelq, thanks for the suggestion!  I agree, this would be useful.  It was pretty simple so I implemented it.  It will be on `T` in v1.2.

**Comment by adelq** [comment]
Thanks Saul!

**Comment by hi2u** [comment]
Is there a CLI argument I can add to the `vd` command to start in transposed view? (without having to hit shift-T)
