### ISSUE TITLE
Support for SVGs

### ISSUE THREAD

**Issue by rschwiebert** [saulpw/visidata#1292]
It seems svg files (as extensions of xml) are already parsed, but so far I haven't found support for rendering the svgs. Even if rendering in the terminal is a limitation, maybe it could pop open a window like you can when calling .draw methods on svg objects in python?

I'm also not sure if my svg data itself is being parsed and displayed as cleanly as an xml file. Maybe the organization of an svg just makes it look complicated when presented as an xml.

visidata is a pretty nifty tool: thanks for making it!

**Comment by saulpw** [comment]
I was working on an svg displayer in the terminal with @eliasdorneles, but we didn't get it past the prototype stage.  There is an svg saver in vdplus which may be helpful (or you can use for inspiration): https://github.com/visidata/vdplus/blob/develop/graphing/svg.py

Otherwise, Kondo'ed for now!
