### ISSUE TITLE
[v2.9dev] unknown aggregator accepted in columns-sheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1299]
**Small description**
Previously when manually adding the name of an aggregator in the `aggregators` column in the `columns-sheet`, if you didn't add the name correctly it would refuse to change the value. Now the input accepts _any_ value and you do not know it is wrong until you create a frequency analysis sheet.

**Expected result**
To show a warning telling the user that it is invalid input and revert back to the previous state (as per previous vd releases)

**Actual result with screenshot**
![aggregator](https://user-images.githubusercontent.com/11225502/155372097-03234958-75f9-4da1-9589-9968c052b80d.gif)

**Comment by anjakefala** [comment]
Aggregators on Columns Sheets are coded in `visidata/aggregators.py`:

```
ColumnsSheet.columns += [ColumnAttr('aggregators','aggstr')]   
```

No checks are performed here. `ColumnAttr` accepts any value passed its way.

We may need to use a regular `Column()` so that the `setter` can be over-ridden to have a check added.

**Comment by anjakefala** [comment]
Thanks @geekscrapy! This is now fixed on `develop`.

**Comment by geekscrapy** [comment]
Unsure if this has cropped up due to the fix but when trying to do a `zd` on the aggs column in columnsSheet I get the following error (which I didn't get historically):

```
Traceback (most recent call last):
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/column.py", line 370, in setValueSafe
    return self.setValue(row, value)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/column.py", line 364, in setValue
    self.putValue(row, val)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/column.py", line 357, in putValue
    return self.setter(self, row, val)
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/aggregators.py", line 144, in <lambda>
    setter=lambda c,r,v:setattr(r, 'aggregators', v))
  File "/Users/geekscrapy/Documents/pyv/py3.7/lib/python3.7/site-packages/visidata/aggregators.py", line 46, in aggregators_set
    newaggs = [agg.name for agg in aggs]
TypeError: 'NoneType' object is not iterable
```

**Comment by anjakefala** [comment]
Fun!

**Comment by anjakefala** [comment]
For this fix, do we want `zd` to set the cell in the `aggregators` column to `None` or to `''`?

**Comment by geekscrapy** [comment]
Hmm, I'd say set it to whatever the aggregator column is by default when you open a sheet. I think it's `''`?

**Comment by anjakefala** [comment]
Thanks @geekscrapy! This is now fixed on `develop`.
