### ISSUE TITLE
Map enter to edit

### ISSUE THREAD

**Issue by TMiguelT** [saulpw/visidata#13]
Currently, enter doesn't seem to be mapped to anything. I think the best action for enter would be to make it edit the current cell, since editing is the primary action you want to perform, and enter is a fairly primary key. This would help non-vim users to use visidata because it would be fairly intuitive and allow them to edit a file using only the arrow keys and enter (and whatever they want to type, of course)

**Comment by saulpw** [comment]
That's an interesting idea.  My current plan is to allow 'plugins' to be created for other workflows, i.e. defining sheets and commands that allow custom curses apps--like a git branch explorer.  Those sheets very likely want to map ENTER to another action, like diving into a branch or file.  (The DirectoryBrowser already does this, where ENTER goes into a subdir or pushes a sheet with the current file as the source).  You can also see this in action if you load a .json file/object and start diving into the sub-objects.

So while I think making 'edit' the default action for ENTER makes sense for some of the current data sheets, it seems like it would be confusing to establish that as a standard, only to have other workflows override it.

That said, in the next version (released in a few days, hopefully), you'll be able to have an autoloaded .visidatarc.py (or something) file with a line like:

command(ENTER, 'cursorCol.setValues([cursorRow], editCell(cursorVisibleColIndex))', 'edit this cell')

which will accomplish exactly what you want.

Does that work for you?

**Comment by multimeric** [comment]
Was this customisation ever implemented? I can't find documentation for it anywhere

**Comment by saulpw** [comment]
Documentation is in progress.  A v1.0 will be shipped by July 1st, and this should not be a problem then.
