### ISSUE TITLE
Sniff file type from data

### ISSUE THREAD

**Issue by bitwisecook** [saulpw/visidata#130]
Visidata already sniffs compressed files by their file extension.

As seen in https://www.sqlite.org/fileformat.html#database_header for sqlite, the first 16 bytes of an sqlite3 file are "SQLite format 3\000".
As seen in https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers, the first 4 bytes of a ZIP file are 0x04034b50
As seen in http://www.forensicswiki.org/wiki/Bzip2, the first 4 bytes of a bzip2 file are "BZ[h0][1..9]"
As seen in https://tukaani.org/xz/xz-file-format-1.0.4.txt, the first 6 bytes of an xz file are 0xfd377a585a00

Perhaps it's a bit more reliable to read the first, say, 256 bytes of the file, and let Sheets define a function for magic matching if there's nothing passed in with -f

**Comment by saulpw** [comment]
I like the idea of giving the loaders a filetype check function.  That same mechanism could handle the file extensions too, and remove the need for the `open_` functions.   Thanks for the suggestion, @bitwisecook!

**Comment by nickray** [comment]
Maybe this could also help with the Pandas integration, and `vd -pandas .` use case? It would be very ergonomic, e.g. in the case of a `.tsv` file to a) figure out this is a CSV file with an alternate separator, and call `pandas.read_csv`, or b) fallback on the non-Pandas loader for TSV files.

**Comment by anjakefala** [comment]
Since this issue has not been added to the roadmap, it has been moved to our [someday/maybe list](https://github.com/saulpw/visidata/blob/develop/dev/ROADMAP-someday.md).
