### ISSUE TITLE
[v2.9dev] Disable adding new row in DirSheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1300]
**Small description**
Unless used, `add-row` should probably be disabled on DirSheet as it creates an error

**Expected result**
A warning to be shown to the user that a new row/file cannot be created.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/155373843-aeef6d8e-cc96-4559-b3e6-dc9690aab25f.png)

**Steps to reproduce with sample data and a .vd**
Open vd directory with vd (`vd .`) and press `a`

**Comment by anjakefala** [comment]
@geekscrapy Good one!

**Comment by anjakefala** [comment]
On `develop`, adding a row is now disabled on **DirSheet**. =)
