### ISSUE TITLE
[learnability] Add a status message teaching commit on Deferred Sheet 

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1301]
The commit keystroke is different from the standard save, and is not-intuitive.

This can result in confusion where users do not know how to propagate their changes.

> In Emacs dired-mode, when you enter the wdired minor mode (where you can interactively rename files) it shows a message at the bottom saying "Press C-c C-c when finished or C-c ESC to abort changes"

This seems like a useful status message or wizard to be added.

**Comment by saulpw** [comment]
The sidebar guide is helping with this now.
