### ISSUE TITLE
Issue report command

### ISSUE THREAD

**Issue by Gurkenglas** [saulpw/visidata#1306]
There should be a command that:
  1. Saves the current session, errors, and copies of all involved files.
  2. Reproduces the session on the copies, checking whether the same errors happen.
  3. Shrinks the command log by one line at a time, finding the minimal reproduction.
  4. Opens github.com/saulpw/visidata/issues/new with the relevant files uploaded.

**Comment by saulpw** [comment]
Fun idea, @Gurkenglas!  I'm not sure how feasible some of these are, and we'd need to make sure that people still wrote text describing their issue.  But I'd be open to a plugin that does this!
