### ISSUE TITLE
[col height] New vertical max-resize-col command

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1307]
Wishing for a command like `resize-col-max` but for vertical height of the current column.               
Also, it would be useful if there were commands of a similar ilk to the other `resize-col` commands for vertical height.

The current workaround is to go to the column sheet and set the height of the column or change the options.  You need to go to a different sheet to do these
 
Not sure what letter I would put this new command on.  Maybe 'Shift+I' since it looks like it is one row height.  Or change around with the 'v' bindings.

**Comment by saulpw** [comment]
How about `zv`/`gzv` for `setcol-height-input`?

The existing command (`toggle-opt-visibility`) is not that useful and maybe could be unbound entirely.

**Comment by frosencrantz** [comment]
That all makes sense to me, and matches up with how `resize-col` commands work.

**Comment by saulpw** [comment]
Okay, I added `resize-height-input` and `resize-height-max` bound to `zv` and `gzv` respectively.  `gzv` sets the height for all rows to the max height needed for the current row.  Let me know how this works for you, @frosencrantz!
