### ISSUE TITLE
[replay] Playback has issues when column names are numbers.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1309]
**Small description**
Playback is confused by column names that are integers.

**Expected result**
Playback identifies the column based on the name rather than position, when the name matches the number

**Steps to reproduce with sample data and a .vd**

Data and cmdlog below.  When I playback it makes column 'b' an int column, but the original intention and behavior when recording was to make the column named '1' an int column.

https://asciinema.org/a/PZE0vLiNr2kQtBkLUSYU9tmDW

Perform an operation on a column with an integer name, save the cmdlog, play it back on the same data, and get a different
result.

```csv
a,b,c,1
a1,b1,c1,1
a2,b2,c2,2
a3,b3,c3,3
```

Cmdlog:
```csv
sheet   col     row     longname        input   keystrokes      comment
                        open-file       data-number-cols.csv    o
data-number-cols        1               type-int                #       set type of current column to int
```

**Additional context**
Please include the version of VisiData. Latest version on develop.

It is easy to create a column with an integer number with the addcol-expr command with integer input.  My plan was to the edit the values for some rows.

**Comment by anjakefala** [comment]
This is such a fun bug, @frosencrantz! Thanks!

**Comment by anjakefala** [comment]
Thanks @frosencrantz! This made things a lot better.

This is fixed on `develop`. If the cell contains a string, the replay is going to look for a column name of that string.

To reference a column based on its number, `.vdj` format needs to be used, and the cell needs to be an int type. `z=` (e.g. `z=1`) can be used to set the cell as an int.

**Comment by frosencrantz** [comment]
Thank you @anjakefala that works great for my .vd file. 🎉  Happy that was a fun bug!  It was surprising to find!
