### ISSUE TITLE
Join bug: Docs or Code?

### ISSUE THREAD

**Issue by cclark** [saulpw/visidata#131]
I'm new to vd so this could be a PEBKAC but I have been trying to follow the docs on joining two datasets: http://visidata.org/docs/join/

When I get to step 5 of selecting the Key Column I get a message: `AttributeError: 'list' object has no attribute 'toggleKeyColumn'.`

I thought there might be something with my data so I recreated two very simple .csv files and had the same error.

Two sample .csv files

sheet1.csv
```
ID,Name,Country
1,Foo,US
2,Bar,CA
3,Baz,NZ
4,Qux,DE
5,Quux,AU
```

sheet2.csv
```
Valid_ID
1
3
4
```

My cmdlog
```
sheet   col     row     keystrokes      input   comment
                        o       sheet1.csv      open file
                        o       sheet2.csv      open file
sheet2                  S               open Sheets Sheet
sheets          1       s               select current row
sheets          2       s               select current row
sheets                  gC              open Columns Sheet with all columns from selected sheets
all_columns             キsheet2,Valid_ID       !               pin current column on the left as a key column on source sheet [AttributeError: 'list' object has no attribute 'toggleKeyColumn']
all_columns             キsheet1,ID     !               pin current column on the left as a key column on source sheet [AttributeError: 'list' object has no attribute 'toggleKeyColumn']
```

My lasterror
```
last_error
Traceback (most recent call last):
  File "/usr/local/Cellar/visidata/1.0/libexec/lib/python3.6/site-packages/visidata/vdtui.py", line 1117, in exec_command
    exec(cmd.execstr, vdglobals, LazyMap(self))
  File "<string>", line 1, in <module>
AttributeError: 'list' object has no attribute 'toggleKeyColumn'
```

**Comment by cclark** [comment]
The above was found in VisiData 1.0. I have just upgraded to VisiData 1.1 and I no longer see the error. However it appears that the docs saying to select the key column in each sheet by highlighting the row for each sheet in the Columns Sheet and pressing `!` might not work as it seems to toggle the Columns Sheet and not set the column as key in each sheet.

**Comment by anjakefala** [comment]
Hi @cclark, you actually caught both a doc bug and a code bug!

Yes, `!~@#$%` behaviour on the Columns sheet has been changed for 1.1.  We decided that it was confusing to have them behave differently on the Columns sheet compared to every other sheet.

In 1.1, to set the selected source Columns as a key column the command is `g!`. So the docs do need to be updated (thank you for drawing my attention to that).

However, when using `g!`, the bug you identified does pop up. =) @saulpw is currently investigating it. Thank you very much for documenting it in an issue.

I will write up an updated join workaround in my next message in this issue. This will appear in the visidata.org/docs when it is next updated.

**Comment by anjakefala** [comment]
# How to join two datasets
1. Load the datasets into VisiData.
    a. `vd d1.tsv d2.tsv`
    **or**
    b. Press `o` and enter a filepath for each file.
4. Press `S` to open the **Sheets sheet**.
5. For each sheet which you wish to merge:
     a. Scroll down to the row referencing the sheet and press `Enter` to open it.
     b. Press `!` on the column which references the index on which the join will be performed. At least one key column, per sheet, should be set.
     c. Press `Ctrl+^` or `S` to return to the **Sheets sheet*
6. Optional: If performing a left outer join, use `J` or `K ` to reorder the sheets. The first sheet will be the one for whom all rows will be retained.
7. Press `&` followed by the *jointype* to execute the join.

**Comment by anjakefala** [comment]
To do: 

* Update the documentation and ensure that every documentation which references the Columns sheet is properly updated.
* Write a test to catch `gC` related join bugs in the future.

**Comment by cclark** [comment]
Thanks! Glad to assist and I really appreciate the speedy response.

In your updated doc you have 

> Press `^^` or `S` to return to the *Sheets sheet

The `^^` seems to just put me into an edit mode of the column header. Using `S` does work though and I've successfully joined the sheets I had.

**Comment by anjakefala** [comment]
@cclark Oh, sorry, by `^^` I had meant `Ctrl+^`. That is confusing, you are right. I also ended up changing `^^` to `Ctrl+^` in all of the docs. 

Updated docs are now live here: http://visidata.org/docs/join/ .

Ticket will be closed once the dev part of this Issue has also been handled. =)
