### ISSUE TITLE
KeyError 'p33' when trying to use aggregators.

### ISSUE THREAD

**Issue by pnfnp** [saulpw/visidata#1312]
**Small description**
Using the `tertiles` `quartiles` `quintiles` `deciles` there's a key error with the first value `p%s` e.g `p33` or `p25` etc.
 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/38131266/156943247-09ec2c74-d39f-407a-a1e4-1aaf983c616f.png">

**Expected result**
Being able to use that `qn` functionality.

**Actual result with screenshot**
<img width="175" alt="image" src="https://user-images.githubusercontent.com/38131266/156944411-19525176-2560-40d6-b2cb-09ef617dcdc5.png">
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/38131266/156943345-212b0647-ffbc-472a-8b4f-2169c492306f.png">

**Steps to reproduce with sample data and a .vd**
1. Open a file.
2. Select a column
3. `+` select `q3` or `q5`
4. Hit enter.

**Additional context**
VisiData v2.8
Python3.9
macOS BigSur version 11.6.4 (20G417)
I've added an additional option, `minetile` 😅 please don't pay attention, but it's not impacting the behaviour.

**Comment by geekscrapy** [comment]
Just wanted to add (away from computer atm), I have a (different) stdev agg plugin which this occurs with as well. It uses the same tertial logic (producing 3 columns, from 3 functions). I saw this error and thought it was something I needed to change as I'd not used it for a long while, but it appears that it might have the same underlying issue as this (I basically get the same error, just a different function name)

**Comment by anjakefala** [comment]
## Debugging Info In-Progress

There is a `quantiles()` function which de-composes the quartiles (e.g. `q3`) into percentiles (e.g. `p33`, `p66`). However, a check in `vd.aggregators` later on cannot find those percentile aggregators. They were not added to the list:

```
  File "/home/kefala/git/visidata/visidata/aggregators.py", line 36, in aggregators_get
    return list(vd.aggregators[k] for k in (col.aggstr or '').split())
```

I believe the fix will be to make sure `vd.aggregators` knows about the pctiles somehow...Reading the code.

**Comment by anjakefala** [comment]
Commit whic broke this behaviour: bb29b6e8f04dd5410132a6eb0ae6bdd2092e52fd

**Comment by anjakefala** [comment]
This has now been fixed on `develop`! I added a test to catch if this ever regresses again. This has been broken since v2.8.

**Comment by pnfnp** [comment]
Checked out `develop` working like a charm ✨

<img width="503" alt="image" src="https://user-images.githubusercontent.com/38131266/157393687-a43f5a4c-303c-49a4-9cab-b8126dcdfe5a.png">

Thanks @anjakefala 🌟
