### ISSUE TITLE
"NameError: name 'PandasSheet' is not defined" when creating a new sheet from selected rows.

### ISSUE THREAD

**Issue by jasonwirth** [saulpw/visidata#1315]
**Small description**
Reading a Parquet file uses the pandas loader. 
Selecting rows and pressing the quote `"` to duplicate the sheet with the selected rows throws a `NameError`.

**Expected result**
New sheet with the selected rows

**Actual result with screenshot**
[error_PandasSheet_not_defined.txt](https://github.com/saulpw/visidata/files/8194318/error_PandasSheet_not_defined.txt)

```python
Traceback (most recent call last):
  File "/Users/jasonwirth/code/visidata/visidata/basesheet.py", line 170, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/Users/jasonwirth/code/visidata/visidata/basesheet.py", line 72, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "dup-selected", line 1, in <module>
NameError: name 'PandasSheet' is not defined

```

**Steps to reproduce with sample data and a .vd**
[select_parquet.vd.txt](https://github.com/saulpw/visidata/files/8194355/select_parquet.vd.txt)
```
sheet	col	row	longname	input	keystrokes	comment
			open-file	sample_data/sample.parquet	o	
sample		0	select-row		s	select current row
sample		1	select-row		s	select current row
sample		2	select-row		s	select current row
sample			dup-selected		"	open duplicate sheet with only selected rows

```

**Additional context**
Please include the version of VisiData.
```
❯ vd --version
saul.pw/VisiData v2.9dev
```

**Comment by anjakefala** [comment]
This was fixed by @jasonwirth! The fix is now on `develop`.

**Comment by jasonwirth** [comment]
Thanks! Glad to contribute. VD is awesome. Thanks for everyone's hard work!
