### ISSUE TITLE
Input mysteriously stopped working

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1319]
### Discussed in https://github.com/saulpw/visidata/discussions/1251

This has come up for more than one person, and I want to set aside time to investigate this. I do not usually have a habit of looking in the Discussions tab for my bug queue, so I opened an issue.

Please continue adding relevant comments to the Discussion itself!

The biggest challenge for resolving this is that we do not have a repro yet. I was only able to reproduce this by commenting out code.

**Comment by ghost** [comment]
I just had a thought about this today.
In a Python prompt, pressing `Ctrl-S` suspends input. Pressing `Ctrl-Q` resumes input.
I was wondering if something like this might have occurred, as `Ctrl-S` is a fairly common shortcut in VisiData.
However, I've tried pressing `Ctrl-S` at random places in the VisiData interface, and it doesn't reproduce the issue.
So maybe this is a red herring.

**Comment by anjakefala** [comment]
Might be related: https://github.com/saulpw/visidata/issues/1347

**Comment by saulpw** [comment]
This might be fixed with the fix for #1347, but it's not clear.  Please continue to report issues of input not working.
