### ISSUE TITLE
Make it possible to 'just open' a gpkg [sqlite] 

### ISSUE THREAD

**Issue by rduivenvoorde** [saulpw/visidata#1324]
Thanks fro visidata!

In the 'geo'-world we try to push 'GeoPackages' as an open alternative for the ancient shapefiles (.shp + sidecars).

The geopackage standard is still being worked on (https://www.geopackage.org/) but in essence it is: an sqlite db with some standardized metadata tables.

So currently you can open it with:  `vd -f sqlite world.gpkg`  with this old (zipped) gpkg file:

[world.zip](https://github.com/saulpw/visidata/files/8230456/world.zip)

But it seems an easy feature to accept *.gpkg files to be opened by default with sqlite? To start with. 

Next stop would maybe be to hide all the ugly metadata stuff (toggable to view it or not)?

And next stop ;-) is to use QGIS machinery to create a map of it in the terminal, see: https://github.com/NathanW2/ascii_qgis :-) 

Again thanks for what already is here!

**Comment by frosencrantz** [comment]
@rduivenvoorde This looks like it will be cool. 

Given that this is still just an in progress standard, it seems like it would be great for a Visidata Plugin.
If you (or someone else) were willing to write such a plugin, I think the Visidata developers would be very happy to add it as a registered plugin. [external plugin]

[external plugin]: https://github.com/saulpw/visidata/blob/577f34127c09116e3cbe1fcb3f67d54484785ae7/docs/contributing.md#submitting-an-external-plugin-plugins

Check this out for how to create a plugin: https://www.visidata.org/docs/api/plugins
It is not too hard to implement new [loaders].  It is possible to use existing loaders as a starting point, especially the [sqlite loader] for this format.

[loaders]: https://github.com/saulpw/visidata/tree/develop/visidata/loaders
[sqlite loader]: https://github.com/saulpw/visidata/blob/develop/visidata/loaders/sqlite.py

- Is there already a Python module that knows how to read gpkg files?  Something that exposes the actual data of interest?

**Comment by LtGlahn** [comment]
Geopackage is mature, robust and well supported. Version 1.1 was released in 2015, we're now at 1.3.1. It is wrong to classify gpkg as an _in progress_ standard. It is of course _evolving_, but in a mature and grown up way. 

My typical python workflow is to read and write gpkg using geopandas https://geopandas.org/en/stable/ , which I've used professionally for at least 5 years, replacing spatiaLite as my go-to file format for all things geospatial. (I also use desktop tools such as FME or QGIS, but that is irrelevant here). Geopandas uses fiona for R/W operations https://github.com/Toblerity/Fiona

Gpkg is special in that it is by definition always valid sqlite: Any tool capable of opening sqlite can open gpkg. So by definition, having sqlite support also means you can read .gpkg, **including visidata** using the flag `--filetype sqlite`. 

One caveat: In addition to the data table(s), the sqlite file will contain a bunch of other tables with metadata, geographical indexes, coordinate system definitions and so on. Finding 20-something tables where you expect only one may be confusing to the end user, and it should be a deliberate design discussion if tables named `gpkg*`, `rtree*` and `sqlite_sequence` should be visible by default or not (possibly implementing a command line flag for showing all metadata files). 

# Reading is trivial (its sqlite), but drop write support 

I suggest you don't aim for write support for .gpkg (unless it means piping tabels through other tools, such as geopandas). Native gpkg write support basically means you must transform visidata into a GIS-capable tool, which probably should be considered as out of scope. However, if that is something you wish to aim for I suggest you dig into the librares for shapely, fiona (which is used by geopandas) and https://github.com/realiii/pygeopkg 

That being said, some simple editing of attributes in existing rows in existing tables should probably work OK, as long as you don't touch the geometry.

**Comment by saulpw** [comment]
Thanks for the suggestion, @rduivenvoorde, I think this would be really neat!  It doesn't sound too difficult, and @frosencrantz is right, it's perfect for a plugin.  I don't have time myself to make it happen, but if you start to pull it together and need guidance, stop by the IRC or Discord chat and we'll help you out!

Kondo'ing this for now.
