### ISSUE TITLE
[selection expansion] Expand current selection with a comma command that expands all matching selection.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1327]
There is already a comma command (select-equal-cell) that will select all rows that match the current cell. Very useful command.
It would be useful if there was a similar command that would expand the selection based on all the selected cells in the current column.

The equivalent of running the comma command in all the selected cells in the current column. 

This is useful where you select multiple rows based on one quality (e.g. via a FreqSheet),
but each row might part of a group of rows.   And for each of the selected rows you want to include the full group of rows it is part of.

**Comment by anjakefala** [comment]
I would like some clarification! =)

Clarification 1. Your request is for a `,` that operates on the current column for all selected rows?

Clarification 2.

>  but each row might part of a group of rows. And for each of the selected rows you want to include the full group of rows it is part of.

Do you mean that a row in the frequency table is a summarised collection of rows from the source sheet? When you select the rows on the Frequency table, you also want the rows that were grouped into it to be selected on the source sheet? Because, this should already be the default behaviour!

If this is not what you meant, could you clarify?

**Comment by frosencrantz** [comment]
Clarification 1: Correct.  Basically a comma command that would loop over every selected row, and  expand the selection based on the cell in the current column, for each of those rows.  

Clarification 2:  
Here is an example using the benchmark.csv file.  I first select all rows with a  RETURN via the FreqSheet.  But I want to see everything bought by those customers. So I go back to the base sheet, and repeatedly use the comma command on the customer column to expand the selection.  
https://asciinema.org/a/iPRK2Qe6gKtihAxzv0F1osi7S


Note: For this example, I didn't need to use the frequency sheet, I could have just found the RETURNs and then done the same thing.  So it doesn't matter how the selection came to be, just that I want to expand it now.  I only mentioned the FreqSheet since that is how I commonly build a big selection. 

Does that help?

**Comment by frosencrantz** [comment]
For reference, in case this wish isn't granted. Saul offered some code in https://github.com/saulpw/visidata/issues/1328 that could be used as a starting point for this wishlist item.

**Comment by saulpw** [comment]
I believe `select-equal-selected` from vdplus will work for this.

**Comment by frosencrantz** [comment]
That's great, @saulpw. Thank you!

I have to admit I have looked but I haven't used the VDPlus plugin.  I want to make sure I follow the licensing.  It looks like if I used it for me to understand some data on a job, I might infringe on the license.

**Comment by saulpw** [comment]
Yes, that's correct, vdplus is not free by default if you're using it in your paid work.  You'd have to support me on [Patreon](https://patreon.com/saulpw) or contact me to negotiate.  I'm open to discussing it!
