### ISSUE TITLE
[selection expansion]  Add ability to expand current selection by N rows 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1328]
The grep command has flags -A-/-B/-C which print additional lines around a matching line.  [grep help]

[grep help]: https://explainshell.com/explain?cmd=grep+-A+5+-B+5+-C+5+

It would be useful if there were equivalent selection expanding commands in Visidata.  The commands would select additional rows around the currently selected rows based on the requested context length

I was recently looking at a log file with VisiData, and it would have been useful to expand the selection around the interesting areas of the log.

**Comment by geekscrapy** [comment]
I would absolutely love this as a plugin

**Comment by frosencrantz** [comment]
I was recently looking at some log files with Visidata and was thinking of you @geekscrapy . You had mentioned using Visidata for log files. I was wondering if you were already doing something like this.

**Comment by geekscrapy** [comment]
Not yet, but I've always had a need, just other things have come up.
A natural progression of this (for me) would be to be able to select rows surrounding, not based on count, but by a time delta. Say, you select a few rows, then you run a command which asks you how many minutes/hours/etc. either side of the selected rows you want to so select. This would require a time based column, but completely doable with log files.

I have a lot of need to open a log file, look for something bad, then just trim (or we call, zoom) the log file in by 5 mins surrounding that row which cuts out a lot of superfluous log lines.

**Comment by saulpw** [comment]
This seems to work:
```
@Sheet.api
def window(sheet, before:int=0, after:int=0):
    for i, r in enumerate(sheet.rows):
        a = max(0, i-before)
        yield r, sheet.rows[a:i+after+1]


@Sheet.api
@asyncthread
def select_around(sheet, n):
    sheet.select(list(itertools.chain(*(winrows for row, winrows in sheet.window(n, n) if sheet.isSelected(row)))))

Sheet.addCommand('', 'select-around', 'select_around(input("select around selected: ", value=1))')
```

I'm planning to add something like `Sheet.window` in the near future (though it probably won't look exactly like the above).

**Comment by frosencrantz** [comment]
Brilliant!  Thanks, @saulpw!  That works. I was concerned that referencing the original selection and changing the selections could cause some sort of feedback. 

I'm very much looking forward to the new `Sheet.window`.  You've seen some of my questions/requests around referencing values around window function,

**Comment by geekscrapy** [comment]
Adding my 2 cents, `sheet.window` sounds awesome! My usecase would be to use it as described above, but also based on time. I.e. based on the selected rows (where each row has a date typed column) allow me to select a window -/+/-+5m around the selected rows.

Thanks for the example though, I'll give that a spin!

**Comment by saulpw** [comment]
> I was concerned that referencing the original selection and changing the selections could cause some sort of feedback.

@frosencrantz Yes, that was the case at first, and hence the `list` which iterates through the whole chain before calling `select`.  In fact `select_around` should be marked `@asyncthread` so that this remains responsive in large datasets [fixed now].

**Comment by saulpw** [comment]
Add to vdplus.  If there's enough interest we can merge it into core.
