### ISSUE TITLE
vd --help doesn't play well with pipes and non-ttys

### ISSUE THREAD

**Issue by halloleo** [saulpw/visidata#1332]
**Small description**

    vd --help | col -b > ~/tmp/vd-help.txt

has garbled codes in the resulting file.

**Expected result**

A nice plain text file containing the help text to vd.

**Additional context**

This happens in version 2.6.1 and version 2.8

See also [issue 1089](https://github.com/saulpw/visidata/issues/1089).

_Side note:_ I personally think `vd --help` should not use _any_ control characters  and be rather brief, while a full man page could be produced with `--man` - but that's obviously subjective.

**Comment by anjakefala** [comment]
## Debugging Notes

The output of ` vd --help | col -b` changed in 7ab2f1249c2099dc506e92c8603df005f5fc980e which was between v2.4 and v2.5.

**Comment by anjakefala** [comment]
We do package a `.txt` version of the manpage with VisiData, and the simplest change may be that `vd --help` outputs that. I will give that a whirl!

**Comment by anjakefala** [comment]
This is now on the `develop` branch, and will be part of the next release! =)
