### ISSUE TITLE
Fix documentation on website

### ISSUE THREAD

**Issue by gruberma** [saulpw/visidata#1334]
Not sure if this belongs here, but I believe to have found a small issue on the website.

Paragraph # 7 in [10 Ways to Use VisiData](https://www.visidata.org/blog/2020/ten/) says you should use `visidata.view_pandas(df)` to view a dataframe in pandas.

I believe that should be `visidata.vd.view_pandas(df)`

![image](https://user-images.githubusercontent.com/14904570/158566552-df4f22c0-cb08-476c-a2d9-076577ebad5c.png)

**Comment by anjakefala** [comment]
This might actually be a bug! 

I need to check in with @saulpw, but `def view_pandas` has a `VisiData.global_api` decorator, which should support `visidata.view_pandas`. But, you are right that currently `visidata.vd.view_pandas` is what works, and possibly the documentation should be changed in the meanwhile.

**Comment by anjakefala** [comment]
VisiData is moving towards a model of `visidata.vd.func`, so I went ahead and updated the documentation! The change should go live soon. 

I will keep this issue open until it is understood why `visidata.view_pandas` stopped working. It appears to have broken in this commit: 44429926151f99cfc45665bfe46b99f57f85c9d6.

Thanks for drawing our attention to this!

**Comment by anjakefala** [comment]
We addressed this bugfix by updating the documentation, and fixing the bug so that the previous command will work as well! Bugfix will be available in the next `visidata` release. =) But, going forward `visidata.vd.view_pandas` is the way we will recommend viewing pandas dataframes.
