### ISSUE TITLE
`kDN` and `kUP` prettykeys don't actually exist

### ISSUE THREAD

**Issue by djpohly** [saulpw/visidata#1336]
**Small description** [PR incoming]

The pretty keys `kDN` and `kUP` are used in two places in the code, but they are not defined in the translation dictionary.

**Expected result**
Default keybindings should include "Shift+Up", "Shift+Down", "gShift+Up", and "gShift+Down".

**Actual result with screenshot**
Bogus keybindings:
![2022-03-21-184238_958x528_scrot](https://user-images.githubusercontent.com/521294/159380709-97d6451c-1a8e-404c-ae30-f4ce4ad4351f.png)

**Additional context**
Running visidata-2.8 on Arch Linux.

**Comment by djpohly** [comment]
I did some digging based on @saulpw's comment on PR #1337. It turns out the real complication is that the system curses library can return not only standard curses key names, but also the names of custom terminfo strings. These names can be arbitrary; `kDN` and `kUP` come from an [xterm convention](https://invisible-island.net/ncurses/man/user_caps.5.html#h3-Extended-key-definitions). Shifted special keys might yield a curses key name on one system but a terminfo string name on another.

(documenting tonight's investigation/thoughts here to revisit after getting some sleep)

A full implementation would require handling a number of potential synonyms. To handle multiple modifiers, the code would need to make sure that different ways to write a keystroke all resolve to the same canonical name, e.g.
  - "Alt+Ctrl+Down", "Ctrl+Alt+Down", "kDN7"
  - "Shift+Alt+X", "Alt+Shift+X", "^[X", "^[Shift-X"
  - "Shift+Down", "kDN", "kDN2", "KEY_SF"

This could be accomplished either by programmatically inserting a lot of entries in the prettykeys map, or by inserting a few entries in the table and adding some logic in the parsing function.

**Comment by djpohly** [comment]
After a lot of thought, it seems like the root of the issue (and related problems) is trying to represent sequences of key combinations as strings.  Some hacks are in place to try and mitigate the clunkiness: `allPrefixes` for one, plus some of the logic from keys.py.

I'd propose changing how keys are represented internally to something easier to canonicalize:
- Invididual keys: strings still make sense, especially given curses behavior noted above. Examples: `'x'`, `'Down'`
- Combinations: add a Flag (or just a set[str]) to represent the modifiers.  Examples: `(Mods.NONE, 'x')` or `(set(), 'x')`; `(Mods.CTRL|Mods.ALT, 'Down')` or `({'c', 'a'}, 'Down')`.  Combinations could also be represented as a string if absolutely necessary, but canonicalization would be a little more complicated.
- For sequences, a *list* of whatever is used for key combinations.

User-facing APIs where backwards compatibility is desired would need a bit of shim logic derived from the existing code, but the internal representation would be more consistent.

Thoughts?

**Comment by saulpw** [comment]
Hey @djpohly, sorry, this fell between the chairs.

We'll fix the kDN/kUP omission in the short term, and in the longer-term, I agree that the bindings should be clarified.  I'm thinking that VisiData should translate via the keymap and then e.g.  `Shift+Up` would be the actual binding string, instead of the platform-specific `kUP`.  But I think we'll keep the basic string format, as strings are easier to work with than tuples/lists. We could make it space-separated though, so a simple `.split()` would yield the key sequence.
