### ISSUE TITLE
[v2.9dev] open-row fails to open a SheetDict 

### ISSUE THREAD

**Issue by Gurkenglas** [saulpw/visidata#1341]
**Small description**
![Screenshot from 2022-03-30 15-09-26](https://user-images.githubusercontent.com/1489801/160842018-fdda7633-9c51-45ab-b4fa-8761e187384e.png)
![Screenshot from 2022-03-30 15-17-30](https://user-images.githubusercontent.com/1489801/160843676-23714782-b3e3-4181-9fc8-f21e4bdc97d4.png)

**Expected result**
![Screenshot from 2022-03-30 15-09-52](https://user-images.githubusercontent.com/1489801/160842120-7d587f1f-3b24-4d4e-b1f9-023b318a5b76.png)
![Screenshot from 2022-03-30 15-10-36](https://user-images.githubusercontent.com/1489801/160842242-c8a1582e-9159-46a3-9db4-bb3ce84d0409.png)

**Actual result with screenshot**
![Screenshot from 2022-03-30 15-11-16](https://user-images.githubusercontent.com/1489801/160842384-9e9ee84e-b922-439e-8aa5-6869f6f6af5d.png)
![Screenshot from 2022-03-30 15-11-35](https://user-images.githubusercontent.com/1489801/160842450-0340527b-cc36-493c-98de-eae5086a35f8.png)

**Steps to reproduce with sample data and a .vd**
[example.zip](https://github.com/saulpw/visidata/files/8380785/example.zip)
```
unzip example.zip
vd -p example.vd example.json
```
Then `q` and `Enter` to get the expected behavior.
Furthermore, I consider that this reporting workflow must be convenienced.

**Comment by ajkerrigan** [comment]
Thanks for including a detailed description and repro steps! It looks like when I try this locally with `vd -p example.vd example.json`, `example.json` isn't being completely loaded. The SheetsSheet after loading looks like this:

```
 name      ║ type        | pane#| shortcut | nRows#| nCols#| nVisibleCols#| cursorDisplay | keyColNames | source       | progressPct ║
 sheets    ║ SheetsSheet |    1 | Shift+S  |     3 |    11 |           11 | sheets        | name        | [3]          |             ║
 example[] ║ PyobjSheet  |    1 | 1        |     0 |     3 |            3 |               | attribute   |             ⌀|             ║
 example   ║ JsonSheet   |    1 | o        |     0 |     1 |            1 |               |             | example.json |             ║
 ```

Where `nRows == 0` in the bottom row looks significant to me. `PyobjSheet` will punt to `SheetDict` depending on the data it's trying to open. So if it doesn't have any data, it can't make that choice.

We can make this seem to work by adding a `reload-sheet` command before `open-row`... but I'm really not sure if this indicates that there's something wrong or if it's just an edge case to be aware of.

**Comment by Gurkenglas** [comment]
I'd say what you need to do here is continue loading `example` as part of loading `example[]`.

**Comment by anjakefala** [comment]
@ajkerrigan did a good job in getting to the bottom of this problem! 

Without the `open-file` command, the CmdLog was not actually loading the `example.json`. 

If you add a row to your `.vd` with a `reload-sheet` **longname**, before the `open-row`, that will have the behaviour you want (you can leave all of the other fields blank). 

Perhaps if there is no `open-file` at the start, VisiData should `reload-sheet` by default, but that feels like a seperate issue. Automatic reloads require a lot of thought, because for large files that is an expensive operation.

**Comment by saulpw** [comment]
Thanks @Gurkenglas for the bug and @ajkerrigan for the investigation!  The fix is to push the 'active' sheet when using it during replay, which causes it to reload if it's unloaded.
