### ISSUE TITLE
Documentation incorrect for .visidatarc: bindkey('i', 'edit-cell') not working as stated

### ISSUE THREAD

**Issue by Aljendro** [saulpw/visidata#1344]
**Small description**
The following documentation: 

```
Example: Bind i to edit-cell globally
In VisiData, pressing e enters edit mode for the current cell. Seasoned vim users might prefer to press i instead.

Open ~/.visidatarc in an editor.
Add the line bindkey('i', 'edit-cell') to globally bind the keystroke i to the longname edit-cell.
Launch VisiData, and press i.
```

does not rebind 'i' to the command. What worked for me was using

```
TableSheet.bindkey('i', 'edit-cell')
```

**Expected result**

The expected results was to have the steps from the documentation rebind the 'i' key to edit-cell

**Actual result with screenshot**
The original 'i' command ('addcol-incr') is run instead

![Screen Shot 2022-04-03 at 6 38 47 PM](https://user-images.githubusercontent.com/7899307/161460263-3393b182-019d-480b-bc81-771b46984755.png)

**Steps to reproduce with sample data and a .vd**
Exactly as the small description

**Additional context**
saul.pw/VisiData v2.8
MacOS 11.6.4
Python 3.9.12

**Comment by anjakefala** [comment]
Really good catch! Since that was written `i` had gotten bound to another keystroke, and that changes the instructions a bit. I will update the documentation.

**Comment by anjakefala** [comment]
I updated the docs in the repo! They will get upload to the website with the next VisiData release. Thanks!
