### ISSUE TITLE
Read the background color from an xlsx cell?

### ISSUE THREAD

**Issue by bfloog** [saulpw/visidata#1345]
I personally don't like use colors to describe data in a spreadsheet, but other people have different ideas; when filtering this is about entirely useless.

However, my job requires that I use a sheet like this, so any idea if there is a way to read the background color for the formatting of the cell within visidata?

I saw there are some things about colorizers, but they appear to be for if you want to change the color of a cell, I want to be able to read the color of a cell.

**Comment by anjakefala** [comment]
In https://github.com/saulpw/visidata/pull/1098 (VisiData v2.7), an option was added that creates meta-columns in the sheet, one of them for `fillcolor`!

To use it at start-up `vd --xlsx-meta-columns file.xlsx`, and to have them by default for every xls(x) sheet add `options.xlsx_meta_columns=True` to a `~/.visidatarc`. =)

**Comment by anjakefala** [comment]
I think with that we can consider this closed? =) Please re-open the issue if you have further related questions!
