### ISSUE TITLE
Cannot copy/paste with MS Excel sheet

### ISSUE THREAD

**Issue by jungle-boogie** [saulpw/visidata#1348]
Hello,

Copying and pasting data in the same sheet results in `TypeError: cannot pickle '_io.BufferedReader' object

**Expected result**

Copy/paste to function

**Actual result with screenshot**

![visidata_1](https://user-images.githubusercontent.com/1111743/162527439-e1004295-a341-4d09-81d2-6c92601bfb97.png)
![visidata_2](https://user-images.githubusercontent.com/1111743/162527445-cbf38095-f715-425c-872d-bd995bcd8ac2.png)

**Steps**

1. vd myfile.xlsx +:Stats:14:0
2.  Press `y`
3.  Go down a few spaces
4. Press `p`
5. Look for error to be generated

Python 3.10.4

```
~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

saul.pw/VisiData v2.8

**Comment by jungle-boogie** [comment]
I am able to copy/paste a row when the file type is csv.

**Comment by saulpw** [comment]
Thanks for the bug report, @jungle-boogie!  Paste should work now for xlsx sheets.

**Comment by jungle-boogie** [comment]
I don't believe this to be fixed and I think I'm using the correct develop build:

```
$ pip install --upgrade git+https://github.com/saulpw/visidata.git@develop
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/saulpw/visidata.git@develop
  Cloning https://github.com/saulpw/visidata.git (to revision develop) to /tmp/pip-req-build-3xsmg9r5
  Running command git clone --filter=blob:none --quiet https://github.com/saulpw/visidata.git /tmp/pip-req-build-3xsmg9r5
  Running command git checkout -b develop --track origin/develop
  Switched to a new branch 'develop'
  Branch 'develop' set up to track remote branch 'develop' from 'origin'.
  Resolved https://github.com/saulpw/visidata.git to commit 4f9a1d5e74f6801e3f17bd8c53c734cef4a24150
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil in ./.local/lib/python3.10/site-packages (from visidata==2.9.dev0) (2.8.2)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.10/site-packages (from python-dateutil->visidata==2.9.dev0) (1.16.0)
```

**Comment by anjakefala** [comment]
Hi @jungle-boogie!

Unfortunately, I can confirm that the bug appears to be fixed in `develop`. Your command for updating VisiData to the `develop` branch is correct, but you likely have a version of VisiData somewhere else on your system that is conflicting. 

How did you install VisiData previously? Can you try `locate visidata` to find it? Do you see `v2.9dev` when you launch VisiData?

**Comment by jungle-boogie** [comment]
Verified this is fixed. Sorry for the confusion.
