### ISSUE TITLE
Please invert mousewheel scroll direction...

### ISSUE THREAD

**Issue by marcobra** [saulpw/visidata#1351]
**Small description**
When i use visidata the keyboard "down" or "up" arrowkey scroll the data in right direction, if i use mouse wheel the scroll direction is inverted scrolling by rotating mouse wheel is different by the keyboard "down"/"up" arrowkey scroll logic

**Expected result**
the same mousewheel and keydown/keyup browse/data scroll logic

**Actual result with screenshot**
nothing

**Steps to reproduce with sample data and a .vd**
scroll data with arrows key and mouse wheel

**Additional context**
saul.pw/VisiData v2.8

**Comment by anjakefala** [comment]
I agree that the inverted mousewheel is not for everyone! There is a `scroll_incr` option that is currently set to *3*. Negating it will invert the mousewheel movement to what you expect.

So in your `.visidatarc` have:

```
options.scroll_incr = -3
```

Maybe that is the better default, and we end up changing the default. But for now, that will get you the behaviour you want!

**Comment by anjakefala** [comment]
We did decide to invert the default direction!

That change is on `develop`, and will be in the next release. The option setting in `~/.visidatarc` will will though, until then. =)

**Comment by marcobra** [comment]
good decision, thanks
