### ISSUE TITLE
[bug/feature] stop all async* when vd.run returns

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1357]
When you have a long running acync thread and exit a `vd.run` session, the thread continues. My expectation is that everything `VisiData` is stopped/garbage collected when `vd.run` returns.

**Comment by saulpw** [comment]
Before `main_vd()` returns, it waits for saver threads to finish as per #389, and we want to keep that behavior. Other threads can be canceled though. Let me know if this fix works for you.
