### ISSUE TITLE
CSV parsing error with quotes?

### ISSUE THREAD

**Issue by led** [saulpw/visidata#136]
Using the 1.1 version, I'm getting incorrect column data for a CSV file. 

The quotes of the `data` column seem to be confused/dropped leaving the wrong character escaped and the string incorrectly quoted. eg a csv file like this…

    "pid","yaml"
    1387,"{\"f_file36_target\":\"_top\"}"

is parsed as this…

     pid    | data                             ‖
     1387   | {\f_file36_target\":\"_top\"}"   ‖

Test case and command log attached.

[error-test-case.csv.zip](https://github.com/saulpw/visidata/files/1876616/error-test-case.csv.zip)
[cmdlog-1.vd.zip](https://github.com/saulpw/visidata/files/1876618/cmdlog-1.vd.zip)

**Comment by saulpw** [comment]
Hi @led, thanks for the report.  The Python `csv` module requires `escapechar` to be set to `\` for this case.  I added a fix to forward all `csv_` options to the csv reader/writer, and this will go into v1.2.  So in v1.2 (or on current `dev` branch) you can add a `--csv-escapechar='\'` option to the command-line and it will parse this correctly.
