### ISSUE TITLE
[pyexpr] Hidden column value used rather than visible

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1360]
**Small description**
A name is used for multiple columns, it is possible to use the hidden value rather than the visible value.

**Expected result**
Visible columns are preferred in expressions, over hidden columns.

**Actual result with screenshot**

https://asciinema.org/a/P3PsKbeaR88gSyqeXdDIilSeZ

**Steps to reproduce with sample data and a .vd**

Have 2 or more columns with the same name.  Hide the leftmost one.  Reference the column name in an expression.

You get the unexpected result using the value from the hidden column not the visible column.  In this case, I froze the original column, hide the original, and then rename the frozen column to the original.  Since new columns are added to the right, expressions are using the original (and hidden value).

**Additional context**
Please include the version of VisiData. Latest version of develop

Commonly I will clean up the value of a column.  Hiding the original and intermediate values, and renaming the final column back to the name of the original.  It was surprising to get the original value.  It seems like Visidata should prefer the visible value over hidden values, since that is the least surprising value to use.

There are many issues Visidata can have with multiple columns with the same name, so this is really just one of many possible issues around this condition.

**Comment by saulpw** [comment]
Thanks for writing this up, @frosencrantz.  I agree that this seems like reasonable behavior on the surface, though there may be some cases when the hidden column would be preferred.  I'll look into it and see if it can be changed as you suggest.

**Comment by frosencrantz** [comment]
From the last part of the demo of this bug, I can see how some one might rely on this behavior. Many times I will freeze a column that I might go through several steps to process, to prevent a side-effect of additional edits.

I think it is fine to continue to use hidden columns, but perhaps they are searched after visible columns.  Visidata expression columns are dynamic like spreadsheets, so it is easy to disrupt the value of an expression with renaming.

Thanks @saulpw !

**Comment by geekscrapy** [comment]
Personally I would opt for a behaviour whereby a visible column is always used over a hidden one, _unless_ there are no visible columns with the required name. Then I'd like for it to use the hidden column value

**Comment by frosencrantz** [comment]
Agreed.  That is what I'm suggesting. Visidata currently uses the first column found with the name to use as the value in expressions,  ignoring visibility.  I'm suggesting search all visible columns first, then hidden ones.  Like now, the first one found wins (is used), just using a different sort order for the search.

The danger is if you are doing something like I was doing but don't freeze along the progression, you could end up with a circular dependency, where a column value depends on itself because you've renamed the final column with the name of the original column.  

As an aside, I keep thinking I want a freeze&replace command, that freezes the current column, hides the original column, and names the new frozen column with the original column's name.

**Comment by anjakefala** [comment]
This appears to have been addressed by @saulpw on `develop`! I added a test. It will be part of the next release.

**Comment by frosencrantz** [comment]
Brilliant!  Thank you @saulpw and @anjakefala!
