### ISSUE TITLE
Inconsistent CRLF behaviour between Windows and Linux

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1362]
**Small description**

If I open a CSV with `LF` line endings in VisiData on Windows, make a change, then save the file, I get `CRCRLF` line endings.
Note that this is not just `CRLF` line endings, which is what you get on Linux (see #1076). Note that there are somehow two `CR` characters before the `LF`!

**Expected result**

The line endings should either be `LF` (preserve original) or `CRLF` (Python and VisiData default for CSV writer on Linux).
The line endings should not be `CRCRLF`...

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**

**Original file** (note the LF (`0a`) line ending:
[lf.csv](https://github.com/saulpw/visidata/files/8599982/lf.csv)

```
$ xxd lf.csv
00000000: 612c 620a 312c 320a                      a,b.1,2.
```

**New file** (note the CRCRLF (`0d 0d 0a`) line ending!)
[lf.csv](https://github.com/saulpw/visidata/files/8599988/lf.csv)

```
xxd lf.csv
00000000: 612c 620d 0d0a 332c 340d 0d0a            a,b...3,4...
```

**CommandLog (zipped)**:
[lf.zip](https://github.com/saulpw/visidata/files/8599990/lf.zip)

**Additional context**
Please include the version of VisiData: saul.pw/VisiData v2.7.1

**Comment by saulpw** [comment]
Thanks for the report, @daviewales. You're right, this is incorrect. Ideally it would detect the csv options and set them on the source sheet so it would save in an identical format (though derived sheets wouldn't inherit this format, which may or may not be desired).

**Comment by daviewales** [comment]
The strange thing is that on Linux, it does: `LF` -> `CRLF`. But on Windows we get `LF` -> `CRCRLF`. I haven't checked the source, but there's something strange going on there... (I know that VisiData doesn't exactly support Windows, but it's strange all the same.)

**Comment by saulpw** [comment]
Interesting.  This is due to `options.csv_lineterminator` being set to `'\r\n'` by default, and on windows `\n` is CRLF.  So you can set this option manually to `\x0a` to get LF-only line-endings.  I guess the default should be explicit bytes as well.

**Comment by daviewales** [comment]
@saulpw I did some more digging, and I think the issue is because the CSV file should be opened with `newline=''` for `csv.writer`.

See this note on the csv.writer docs:
https://docs.python.org/3/library/csv.html#id3

I'll send through a pull request with a fix.
