### ISSUE TITLE
vdj variable name issues

### ISSUE THREAD

**Issue by jungle-boogie** [saulpw/visidata#1364]
Hello,

I'm using `visidata` version 4f9a1d5e74f6801e3f17bd8c53c734cef4a24150 and I've created a very simple vdj file with a variable in place, but I'm getting an error on playback.

```
$ cat test.vdj
#!vd -p
{"longname": "open-file", "input": "myfile_{date}.xlsx", "keystrokes": "o"}
```

And here's the error:

```
$ vd -b -p test.vdj date=2022-05-02 myfile_{date}.xlsx
myfile_{date}.xlsx does not exist, creating new sheet
And yesterday things went on just as usual.
Traceback (most recent call last):
  File "/home/zeke/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/zeke/.local/lib/python3.10/site-packages/visidata/main.py", line 332, in vd_cli
    rc = main_vd()
  File "/home/zeke/.local/lib/python3.10/site-packages/visidata/main.py", line 305, in main_vd
    vs = eval_vd(vdfile, *fmtargs, **fmtkwargs)
  File "/home/zeke/.local/lib/python3.10/site-packages/visidata/main.py", line 36, in eval_vd
    log = log.format(*args, **kwargs)
KeyError: '"longname"'
```

Saul says `{varname}` is acceptable with `vd` or `vdj` files:
https://github.com/saulpw/visidata/discussions/1350#discussioncomment-2536775

What am I doing wrong?

**Comment by jungle-boogie** [comment]
Results with a `vd` file:

```
$ cat test.vd
sheet   col     row     longname        input   keystrokes      comment
                        open-file       myfile_{date}.xlsx      o
```

and the replay:
```
$ vd -b -p test.vd date=2022-05-02 myfile_{date}.xlsx
myfile_{date}.xlsx does not exist, creating new sheet
You're enough to try the patience of an oyster!
opening test.vd as vd
"myfile_2022-05-02.xlsx"
opening myfile_2022-05-02.xlsx as xlsx
replay complete
```

**Comment by anjakefala** [comment]
Thank you for opening an issue for this! This is on my todo list. Variable names are not supported yet in `.vdj`. 

The fix is being prioritised by me in the near future. =)

**Comment by jungle-boogie** [comment]
That’s great. Thank you.

**Comment by anjakefala** [comment]
I added support on `develop` @jungle-boogie! It will be part of `v2.9`.

For `.vdj`, you need to use the following syntax `${variableName}` instead of the `{...}` used in `.vd`. This felt like the cleanest approach to supporting a `jsonl-like` format. 

On the cli, you would still do `variableName=foo`.

**Comment by jungle-boogie** [comment]
Great job. That was much quicker than I anticipated.

When I update my visidata, I’ll check the other issue as well.

**Comment by jungle-boogie** [comment]
Works create:

```
$ cat test.vdj
#!vd -p
{"longname": "open-file", "input": "myfile_${date}.xlsx", "keystrokes": "o"}
```

Reply:

```
$ vd -b -p test.vdj date=2022-05-02 myfile_{date}.xlsx
myfile_{date}.xlsx does not exist, creating new sheet
opening test.vdj as vdj
"myfile_2022-05-02.xlsx"
opening myfile_2022-05-02.xlsx as xlsx
Why, it fills the whole window!
replay complete
```

**Comment by anjakefala** [comment]
That looks right!

It looks like variable substitution is not going to work with filenames passed through the CLI. It only alters the passed in `.vd(j)`. That is why you have the: `myfile_{date}.xlsx does not exist, creating new sheet`.

Thanks for checking! Also, this confirms that you managed to update your VisiData in your environment.
