### ISSUE TITLE
How do you delete columns?

### ISSUE THREAD

**Issue by metov** [saulpw/visidata#1366]
I am a new user and apologies if this is an obvious question. Visidata does a lot right! However, one think I couldn't figure out is how to delete columns. I can easily find how to add/delete rows, and adding columns with the menu or `za` is straightforward. However the only ways of deleting columns I found was switching to column view (`Ctrl+C`) which brings up the table schema, then delete that column's row.

On https://www.visidata.org/docs/columns/ searching for `delete` brings up no results. There are instructions for hiding columns, but this sounds different from what I'm trying to do - hiding would leave the column's data in and make it invisible. I want to remove the column of data entirely.

**Comment by geekscrapy** [comment]
As you noted you can use `-` (hyphen) to hide the column. This is good enough for most of my use cases, but to actually delete the column you'll need to open the columns sheet `SHIFT+C` and press delete (`d`) on the column you want to remove 👍

**Comment by tahir-hassan** [comment]
This information should probably be in the documentation

**Comment by saulpw** [comment]
Where did you look, @tahir-hassan ?  It's definitely in the documentation *somewhere* but of course easily findable by people who are looking for it is a separate issue.

**Comment by tahir-hassan** [comment]
I had a look at [columns](https://www.visidata.org/docs/columns/) but couldn't find it there, so I googled it and landed here.

**Comment by xurizaemon** [comment]
I also wound up here. The docs @tahir-hassan links to above refer to "hide (remove)" and "unhide (restore)", personally I would understand remove as meaning delete (remove from the file), not hide (remove from display?).

**Comment by sludgeFudge** [comment]
@xurizaemon If you save with columns hidden, the hidden columns will not be saved to the file you write to. I found this out the hard way. 
That's why the terminology is written as such in the docs I guess.

**Comment by baranelitez** [comment]
i googled and it landed me here. needs to be in documentation, or at least the beginner's guide on the page as an example.

**Comment by saulpw** [comment]
Where did you look, @baranelitez?  More specifically than "documentation", there's a lot of it and I'm pretty sure this is documented in there somewhere already.
