### ISSUE TITLE
Save without confirming

### ISSUE THREAD

**Issue by metov** [saulpw/visidata#1367]
Is there a way to save without confirmation?

The current flow seems to be:
* Press `Ctrl+S` (or other save command)
* Press enter for file filename
* Press y to confirm overwrite

This comes out to quite a few keypresses. It also seems like surprising UX - one would expect to either confirm the filename or the overwrite, not both.

It seems like visidata's keymap is inspired by vim; vim has `:w!` to simply save which does not ask to confirm filename (unless the buffer has no file associated with it). Often people use `ZZ` to save and exit (also no confirmation).

Is there a "save without confirming" fetaure in visidata, or are users expected to map their own key for this? Can it at least be added to the `File` menu as an option, in addition to existing ones?

**Comment by saulpw** [comment]
Hi @metov, if you set `options.confirm_overwrite=False`, then you can save without confirmation.  Or you could add this to your `.visidatarc`:

```
BaseSheet.addCommand('Ctrl+S', 'save-sheet-really', 'vd.saveSheets(Path(getDefaultSaveName()), sheet, confirm_overwrite=False)', 'save current sheet without confirmation')
```

which will override `Ctrl+S` to save immediately, without asking for a filename or confirmation.
