### ISSUE TITLE
Apache Arrow support

### ISSUE THREAD

**Issue by d-miketa** [saulpw/visidata#1369]
Hi and thanks for the great tool! It's super helpful when looking at raw data.

It'd be useful if it could also load Apache Arrow files, which is lately becoming quite popular as a format for machine learning applications.

**Comment by saulpw** [comment]
Hi @d-miketa, what kind of Arrow files are you using?  Parquet files (already supported, via pandas), or arrow IPC files?  Can you provide a link to a sample Arrow file of the kind you're trying to view?

**Comment by d-miketa** [comment]
I _think_ it's the IPC format, the file extension is `.arrow`. It's used by [Huggingface Datasets](https://huggingface.co/docs/datasets/index) and very useful for machine learning.

Here's a zipped example (taken from https://huggingface.co/datasets/imdb): https://file.io/VNSrn48WwLur

**Comment by saulpw** [comment]
Here you go, @d-miketa, let me know if this works for you!

**Comment by d-miketa** [comment]
Hmm I'm getting some very strange formatting, even on that IMDB dataset. I'm trying to open `dataset.arrow` and it produces a lot of gibberish rather than a well formatted table.

**Comment by anjakefala** [comment]
@d-miketa, how did you update VisiData?

Some guesses on might be going on:

This change is currently on the `develop` branch of VisiData, not released. To update, via `pip`, you would need to do `pip3 install --upgrade git+https://github.com/saulpw/visidata.git@develop`.

If the extension of the file is not `.arrow`, you would need to pass to VisiData `-f arrow`, so it would know to use the `arrow` loader. Do you see `opening SHEETNAME as arrow` in the status? (`Ctrl+P` to see the **Status History**.)

**Comment by d-miketa** [comment]
@anjakefala Ha, that was exactly it, thanks! I updated it correctly (using `pip` to install the `develop` branch) and even checked that `where visidata` showed that installation at the top, but somehow ended up checking with the wrong version anyway! It's working very well now, thank you both!!
