### ISSUE TITLE
z; leaves a newline

### ISSUE THREAD

**Issue by justin2004** [saulpw/visidata#1370]
**Small description**
if you have a csv like:

|one                 |two    |three  |
|--------------------|-------|-------|
|2012\-03\-20T14:18:25\.000\+04:00|hello  |3434   |
|2013\-03\-20T14:18:25\.000\+04:00|bye    |99     |
|2""012\-03\-20T14:17:25\.000\+04:00|wave   |3434   |

and you do:
z;
echo $three | grep 3

you get a newline in each new cell that has a result. 
e.g. here is one of the resultant cells piped through `od -tx1 -c`:
0000000  33  34  33  34  0a
          3   4   3   4  \n
0000005

**Expected result**
i think a single line result should not have the newline character, right?
shouldn't visidata trim the trailing newline?

i'm using the HEAD of the visidata stable branch.

**Comment by geekscrapy** [comment]
When using the syntax that you have provided (`echo $three | grep 3`) this is to be expected, although probably not desirable.
You may have noticed that 2 columns are produced for the command, stdout and stderr. Vd is purely taking the output from the shell command you provide and putting it in these columns.
The issue is that you have a command that ends with a new line character. If you don't want this use something like: `echo -n $three | grep 3` which will exclude a new line when echoing

**Comment by frosencrantz** [comment]
I would also agree this is not desirable behavior.  It would be useful if visidata did remove that trailing line ending.  But that is a feature request that I agree with

You can select all the rows `gs` and do a `g=` and use rstrip() to remove the trailing whitespace.  Depending on your settings, you might need to rename the column so it can be used in a python expression.

So if your column name is three, then you would input 
 - `gs` 
 -  `g=` 
 - `three.rstrip()`

It would also help here if these feature requests were implemented you wouldn't need to worry about the column name:
  - https://github.com/saulpw/visidata/issues/989
  - https://github.com/saulpw/visidata/issues/1031

**Comment by geekscrapy** [comment]
Personally, I think it is appropriate to not change any of the output. It can be achieved very easily with the rstrip method, and it provides the _exact_ output

In addition it would probably be extremely quick and easy to implement running z; with rstrip within a new command in .visidatarc

**Comment by justin2004** [comment]
@geekscrapy
 
>If you don't want this use something like: echo -n $three | grep 3 which will exclude a new line when echoing

that addresses the output of echo but grep still emits a trailing new line.
in general command line utils emit newlines at the end of "records" and since vd is cell/record oriented i think it makes sense for vd to ignore the trailing new line as it is not part of the content -- rather the newline signals "this is the end of the record."

**Comment by justin2004** [comment]
> In addition it would probably be extremely quick and easy to implement running z; with rstrip within a new command in .visidatarc

oh, that might be an acceptable approach. (though i still think the newline will be undesirable for 98% of uses of z;.)
do you have example of a .visidatarc that will do that?

**Comment by saulpw** [comment]
Remember, `Column.type` can just be any old function/callable.  So how about this?

```
Sheet.addCommand('z$', 'type-bytes-rstrip', 'cursorCol.type=bytes.rstrip')
```

I think I'll make this be the default type for those output columns anyway, and then the cases which want exact output can use `z~` to get at the raw bytes.

**Comment by justin2004** [comment]
@saulpw i just tried it on the develop branch and it works as expected! thanks!
