### ISSUE TITLE
[loader]  Plugin idea: Use pooch to add more loading types and caching

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1372]
Less of a wishlist, and a suggestion for anyone who wanted to contribute a plugin.

I recently heard about this library: https://github.com/fatiando/pooch

It provides some generic file downloading capabilities:
* Download a file only if necessary (it's not in the data cache or needs to be updated).
* Verify download integrity through SHA256 hashes (also used to check if a file needs to
  be updated).
* Designed to be extended: plug in custom download (FTP, scp, etc) and post-processing
  (unzip, decompress, rename) functions.
* Includes utilities to unzip/decompress the data upon download to save loading time.
* Can handle basic HTTP authentication (for servers that require a login)
* Easily set up an environment variable to overwrite the data cache location

**Comment by saulpw** [comment]
That sounds interesting!  Would love to work with someone on it.  Kondo'ed for now.
