### ISSUE TITLE
[aggregates/duplicate sheet] When duplicating a sheet, aggregates are not copied.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1373]
**Small description**
When duplicating a sheet, aggregates are not copied.

**Expected result**
Aggregates remain sticky to the duplicated/copied sheet.

**Actual result with screenshot**
https://asciinema.org/a/FZzMlQ32DfNX48frDa5ah6u7M

Here, I add aggregates to multiple columns.  Use selection and the `"` operator to duplicate a subset.
The new sheet doesn't have the aggregates.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

```json
#!vd -p
{"longname": "open-file", "input": "benchmark.csv", "keystrokes": "o"}
{"sheet": "benchmark", "col": "Date", "row": "", "longname": "aggregate-col", "input": "max", "keystrokes": "+", "comment": "Add aggregator to current column"}
{"sheet": "benchmark", "col": "Unit", "row": "", "longname": "type-currency", "input": "", "keystrokes": "$", "comment": "set type of current column to currency"}
{"sheet": "benchmark", "col": "Paid", "row": "", "longname": "type-currency", "input": "", "keystrokes": "$", "comment": "set type of current column to currency"}
{"sheet": "benchmark", "col": "Paid", "row": "", "longname": "aggregate-col", "input": "max", "keystrokes": "+", "comment": "Add aggregator to current column"}
{"sheet": "benchmark", "col": "Unit", "row": "", "longname": "aggregate-col", "input": "max", "keystrokes": "+", "comment": "Add aggregator to current column"}
{"sheet": "benchmark", "col": "Customer", "row": "", "longname": "freq-col", "input": "", "keystrokes": "Shift+F", "comment": "open Frequency Table grouped on current column, with aggregations of other columns"}
{"sheet": "benchmark", "col": "Customer", "row": "0", "longname": "select-equal-cell", "input": "", "keystrokes": ",", "comment": "select rows matching current cell in current column"}
{"sheet": "benchmark", "col": "", "row": "", "longname": "dup-selected", "input": "", "keystrokes": "\"", "comment": "open duplicate sheet with only selected rows"}
{"sheet": "benchmark_selectedref", "col": "Customer", "row": "", "longname": "freq-col", "input": "", "keystrokes": "Shift+F", "comment": "open Frequency Table grouped on current column, with aggregations of other columns"}
{"sheet": "benchmark_selectedref", "col": "", "row": "", "longname": "columns-sheet", "input": "", "keystrokes": "Shift+C", "comment": "open Columns Sheet: edit column properties for current sheet"}
```

**Additional context**
Please include the version of VisiData. Latest develop version

This has been around for a while.  I have been using aggregates and it became more noticable.

**Comment by anjakefala** [comment]
Great bug!


We essentially can't use the same columns list or even the same columns on two different sheets.
So we have to copy the attributes from the column objects (even the types of the columns change, so we can't use copy()).

`StaticColumn` contains the code that explicitly copies the attributes from one column and passes it to a new `ColumnItem`. We could just add `aggstr` to that list, but that is just a band-aid. Ideally, we take this opportunity to see if there is a better way. Really, it should copy all attrs that are saveable.

**Comment by frosencrantz** [comment]
@anjakefala what do you think would be a better solution?

The ColumnsSheet already has a list of additional attributes, that might be a starting point.  For a more generic solution, does the column need to have a property that says which attributes should be copied when copying a column?

**Comment by saulpw** [comment]
@frosencrantz Those are both interesting ideas, I especially love the idea of linking this with the columns sheet.  So maybe we should add a Column property of saved attributes, and then rework the columns sheet to populate its own columns from those (automatically updating for special column types).

**Comment by frosencrantz** [comment]
@anjakefala I would be happy with that.  It would scale as new column types are added in the future in Visidata or plugins.

**Comment by anjakefala** [comment]
Gonna give it a try @frosencrantz! =)

**Comment by anjakefala** [comment]
@frosencrantz I ended up going with a simpler version @frosencrantz that did not integrate with the **Columns Sheet**! It was just too big of an undertaking for me. But, this should now be fixed on `develop`!

**Comment by frosencrantz** [comment]
@anjakefala this is brilliant!   Thank you for all the hard work to add this functionality!

I do notice one issue that it doesn't copy the aggregates with `g'`, `freeze-sheet`:
 - https://asciinema.org/a/34FAwwDylxAaBezYbrPvPFA2K

Not sure if that is expected or not. The other ways I've tried to check that it works, seem to work,   like `dup-selected`.

**Comment by anjakefala** [comment]
Nice catch! This is now fixed on `develop`, and I added tests for the discussed cases.
