### ISSUE TITLE
Save configuration from Edit Config File (Shift-O)

### ISSUE THREAD

**Issue by lucamanga** [saulpw/visidata#1375]
Hello,

it seems that is not possible to save my modified settings in the Edit Config File. The official documentation [1] is not explaining this step. 

[1] https://jsvine.github.io/intro-to-visidata/advanced/configuring-visidata/#the-global-options-sheet

**Comment by aborruso** [comment]
Ciao Luca,
to save an option, you could add it to `.visidatarc` file. In example

```
options.color_status = 'bold black on 255'
```

A useful official page https://www.visidata.org/docs/customize/

**Comment by saulpw** [comment]
@lucamanga you can also `Ctrl+S` from the Options Sheet and save as `foo.visidatarc`, which you can then rename to `~/.visidatarc`.
