### ISSUE TITLE
Add geopackage (.gpkg) to the supported formats list 

### ISSUE THREAD

**Issue by LtGlahn** [saulpw/visidata#1376]
Thanks for a FANTASTIC COOL tool I've just discovered today!. 

While waiting for the resolution of native geopackage support https://github.com/saulpw/visidata/issues/1324 , I would very much like to supplement the "supported formats" with a description of how you can use `vd filename.gpkg --filetype sqlite` to read geographical data in geopackage format. https://www.geopackage.org/ 

Would you like me to submit a PR with this update to your "supported formats" documentation?

**Comment by saulpw** [comment]
Hi @LtGlahn, thanks for the offer!  Based on what you said in the other thread, I don't think it's quite fair to say we support .gpkg just because we can open sqlite files.  It's a neat hack, though!  How about adding it to the wiki?

**Comment by LtGlahn** [comment]
Sure, @saulpw , shall I just add another page here (next to the mariadb page), or would you like it another way? 
![image](https://user-images.githubusercontent.com/4352037/167792383-1b35fc3f-0a0c-4345-a5fd-a087dfc9173d.png)

**Comment by saulpw** [comment]
That seems fine, @LtGlahn.
