### ISSUE TITLE
How to use datetime instead of date ? 

### ISSUE THREAD

**Issue by LeNouveau** [saulpw/visidata#1380]
Hi, 

I'm discovering VisiData and I like it. 
But there is a point I don't understand : is there a way to manage datetimes ? 

The date format only goes up to days. 
I would like to group by hours, for example. 

Am I supposed to mark the field as an integer to get more details ? 

Regards, 
LeNouveau

**Comment by saulpw** [comment]
Go to the columns sheet with `Shift+C` and set the `fmtstr` attribute on a `date`-typed column to e.g. `%Y-%m-%d %H`.  Grouping is by the displayed value, so you can then `Shift+F` on that column to group by hours.

**Comment by anjakefala** [comment]
Hi @LeNouveau! 

There is a brief tutorial here under "How to format columns": https://www.visidata.org/docs/columns/

Basically, you can edit the `ftmstr` column in the **ColumnsSheet** (`Shift+C`) to adjust how the datetime is displayed on a case by case basis.

Or you can add: `options.disp_date_fmt = '%m/%d/%Y'` to your `~/.visidatarc` to make a change to the date formatting for all columns that will exist for every session. You can also pass `--disp-date-fmt=""` on the commandline to change for all columns for a specific session.

You can find the format codes for dates here: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes. My guess is you would do something like "%Y-%m-%dT%H:%M".

**Comment by LeNouveau** [comment]
Efficient ! 

And I think I understood. 
Let's go back to my tests. 

Thank you both ! :)

**Comment by saulpw** [comment]
I added `type-datetime` (unbound) to type the column as date and set the fmtstr to show H:M:S time.
