### ISSUE TITLE
[v2.9dev] excessive "sheet modified, really quit" for multiple open sheets when quit-all is used

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1381]
Not a bug, not really a feature...

"Issue":
1. `quitguard` is enabled
2. Open a directory of csvs with `vd .`
3. Select the csv files you want to open with `t`
4. Open all these files with `g+ENTER`
5. Decide you dont actually want any of these sheets open and want to close `vd`, so you use `quit-all`
6. A dialog pops up for the first sheet asking to confirm closure
7. Same for the second sheet
8. Same for the third, etc. etc. 😬

A couple of points for this:
1. Would it be worth gathering a count of all modified sheets in the stack and asking if you want to close them? Do we choose to close all unmodified and then ask to close the other sheets? I would say, no. Sometimes I realise I was working on something (haven't saved it) and actually need all the other sheets to continue...
2. No modifications have actually been made to the sheets during opening, so the dialog is sort of incorrect. (#1037 ?). This may have been fixed by now anyways for CSV...

Additionally, `Ctrl+z` does not work when the confirmation dialog is open. Just something I noticed...

I'm on commit 82c9753509385706c0df851683ad23a341d14c46

**Comment by anjakefala** [comment]
Thanks @geekscrapy! There was a small bug in the fix here: 397249d6e61ee444a9c6f8414b90408dde8e38a4. Should be fixed on `develop` for **SequenceSheet**s. Please keep these coming!
