### ISSUE TITLE
[usv] Unicode Separators swapped

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1383]
**Small description**
USV loader has the RecordSeparator and UnitSeparator flipped

**Expected result**
Record and Unit separator swapped.  The UnitSeparator is like the tab or the comma.

**Actual result with screenshot**
**Steps to reproduce with sample data and a .vd**
Open a usv file, example from the miller request, it should be three rows of three characters:

```shell
echo -n "a␟b␟c␞d␟e␟f␞g␟h␟i" | vd -f usv
```
When saved as csv we don't see those three rows of three characters we see:

```csv
a,
b,
c,d
e,
f,g
h,
"i
",
```

There is a similar request for miller: https://github.com/johnkerl/miller/issues/245

**Additional context**
Please include the version of VisiData. Latest develop.

Reported on Hacker News: https://news.ycombinator.com/item?id=31375435  (just writing it up).

From this comment: https://github.com/johnkerl/miller/issues/245#issuecomment-494503438
Unicode Character 'SYMBOL FOR RECORD SEPARATOR' (U+241E)
Unicode Character 'SYMBOL FOR UNIT SEPARATOR' (U+241F)

From the current develop we see that the values are swapped.  RecordSeparator (value ending in E) should be used for the row delimiter.  And UnitSeparator (Value ending in F) should be the delimiter: 
https://github.com/saulpw/visidata/blob/82c9753509385706c0df851683ad23a341d14c46/visidata/loaders/usv.py#L8-L9
https://github.com/saulpw/visidata/blob/82c9753509385706c0df851683ad23a341d14c46/visidata/loaders/usv.py#L16-L17

As part of trying to reproduce this, I realized that loading the value as a USV, you can’t then save the value as a TSV file, since it will use the USV set delimiter and row_delimiter.  That is unexpected, and a bug.  Perhaps we need usv_delimiter/usv_row_delimiter options.  Does this format even need an override if we have CSV and TSV?

**Comment by frosencrantz** [comment]
The sample data is  two rows of the three columns, plus the header row (a,b,c).  I counted the header as a row.

**Comment by saulpw** [comment]
Thanks, @frosencrantz.  Swapping the delimiters is easy enough, but you're right, that saving a usv sheet as tsv will not work.  I guess it was too much of a hack in the first place :)  We'll have to fix this!

**Comment by anjakefala** [comment]
This seems to now be fixed on `develop`! I will add a test.

**Comment by frosencrantz** [comment]
Thanks for making Visidata properly handle USV data.  It always makes me happy when I know Visidata can handle a new data format that might come my way.

It's nice that there is a fix for a bug that became visible on Hacker News.  Is it possible to follow up on that thread at this point?  Does it make sense?

**Comment by anjakefala** [comment]
https://news.ycombinator.com/item?id=31375435

I do not seem to be able to reply?
