### ISSUE TITLE
Ability to batch process differently named files using replays

### ISSUE THREAD

**Issue by pbsds** [saulpw/visidata#1389]
Is it possible to use visidata to batch process files that have different filenames from the file used to record the command log?

My workflow:

* open foo.csv in vd
* do stuff
* save the comand log as procedure.vd
* `vd -p procedure.vd -b -o -` work as expected
* `vd foo.csv -p procedure.vd -b -o -` does not, due to "multiple sheets with same name"
* edit procedure.vd in text editor, removing the "open foo.csv" line at the top
* `vd foo.csv -p procedure.vd -b -o -` work as expected
* `vd bar.csv -p procedure.vd -b -o -` does not work

The final point errors with the message

```
opening procedure.vd as vd
no sheet named foo
replay canceled
```

It seems the replay files are dependent on the file / sheet name. **Is it possible to make a replay work for any file?**

*Possible solutions:*

1. ability to set sheet name from cli *(i haven't found such a feature?)*
2. ability to rename the active sheet  at the top of replay file
3. make vd assume the first sheet name in the replay file should refer to the the only sheet currently open, then rename the sheet before continuing the replay.

**Comment by jungle-boogie** [comment]
You can use variables in your vd/vdj files. Is that what you're asking?

> Yes, use {varname} in the .vd or .vdj file, and then specify varname=value on the cli when replaying.

See here:
https://github.com/saulpw/visidata/discussions/1350

**Comment by pbsds** [comment]
huh. This is a cursed solution, but i just managed to make it work by replacing the `open-file` with this (header included):

```
sheet         col   row  longname      input         keystrokes  comment
                         sheets-stack                Shift+S     open Sheets Stack: join or jump between the active sheets on the current stack
sheets        name  1    edit-cell     foo           e           edit contents of current cell
```

**Comment by pbsds** [comment]
Any interest in implementing "possible solution" number 3? This is for me a major pain point still.

**Comment by saulpw** [comment]
Hi @pbsds, if you blank the sheet field in the .vd/.vdj, then it will always use the top sheet, which should work in most circumstances.  Then you can just remove the open-file and you should be able to replay the .vd against whatever source you give on the CLI.
