### ISSUE TITLE
Give newcomers a visual impression of VisiData [README/www] 

### ISSUE THREAD

**Issue by kirtangajjar** [saulpw/visidata#139]
It would be nice if we could see visidata in action in readme itself. 

Would save new users pain to install it just to see what and how it does what it does.

**Comment by anjakefala** [comment]
Agreed @kirtangajjar! I am going to expand this issue to cover both the website and the readme. 

We have one screenshot on the website, but having several gifs, or linking to a video, would probably be better.

Thanks 😊

**Comment by tekknolagi** [comment]
If there are gifs, it might be helpful to have overlays of what keys are pressed in the demo.

**Comment by saulpw** [comment]
Here's an outline of what we'd want in the initial 30-second video:

1. open file from command line with 500k rows (enough that it takes a few seconds to load to show off async loading)
2. move to a different column
3. Freq analysis (should take a few seconds, good to see the results tally up)
4. search with `/` and maybe `n`
5. dive into those rows with `Enter`
6. hide a column or two with `-`
7. sort with `[` on a different column
8. save to a different format

**Comment by aborruso** [comment]
@saulpw what about this one?

![](https://i.imgur.com/FVrYsvF.gif)

**Comment by saulpw** [comment]
@aborruso Originally we had an animated .gif on the front page but it soon was driving me nuts. So our plan for this is a short video that requires you to press play, so it's not distracting from the start.  Basically what you have here, though I saw another video of yours which showed the keystrokes pressed in a large font, which seems like it might be very useful.  What program do you use to make these?

**Comment by aborruso** [comment]
@saulpw in some way I'm the evil, I'm a Windows user :( 

The utility I use is [carnac](https://github.com/bfritscher/carnac)

If you need a mp4 video as my last one gif, and adding to it the keystrokes pressed, I can create it in few minutes

**Comment by anjakefala** [comment]
Since the source files for visidata.org have been migrated to their own repo, this issue was migrated to that repo.

It can be found at https://github.com/saulpw/visidata.org/issues/8
