### ISSUE TITLE
[freeze-sheet] freeze-sheet  has all null values for some sheet types

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1395]
**Small description**
freeze-sheet doesn't work for some data like jsonl/lsv files.  Also for other internal sheets like ColumnSheet.

**Expected result**
freeze-sheet would copy the data from the original sheet

**Actual result with screenshot**
https://asciinema.org/a/En93ThqVzQdXCzil2ym7QICEk

Freeze sheet on the lsv and jsonl files creates a duplicate sheet, but all the data is nulled out.

**Steps to reproduce with sample data and a .vd**
Try the 'freeze-sheet' `g'` command

**Additional context**
Please include the version of VisiData.  Latest version of develop

**Comment by anjakefala** [comment]
First commit with regression: 54d3885feb5ae47f4fc88cdd59904ec6b02ca68e.

The line: `colcopy.__setstate__(col.__getstate__())` in **StaticSheet** is resulting in the regression.

The problem is specifically in the setting of the `expr` attribute.

**Comment by saulpw** [comment]
Thanks, @anjakefala !  That really helps.  A `ColumnItem` (now called `ItemColumn`) needs its `.expr` attribute to be the 'item' to get.  It should be set in the constructor (it's missing here, which would also be a bug without the setstate), but the setstate overwrites it with the expr from the non-static column, which is probably wrong for this new sheet.  So we need to reset the expr back.

**Comment by anjakefala** [comment]
Great catch @geekscrapy =))

**Comment by frosencrantz** [comment]
@anjakefala that's great!  Thank you for fixing this, it works for me.
