### ISSUE TITLE
Feature Request: Disable sort criteria

### ISSUE THREAD

**Issue by rlue** [saulpw/visidata#1397]
`[` and `]` can turn on sorting, but then there's no way to turn it off. (I hit it by mistake in a file for which sorting makes no sense—visidata is probably overkill for editing my CSV of flashcard questions, but hey, I like the interface!)

Would be really cool to have the "sort" key bindings **toggled** sorting rather than just enabling it.

Thanks for an amazing utility!

**Comment by anjakefala** [comment]
There is an `undo` button! (`Shift+U`) Does that help you with your particular use-friction? 

I am really, really delighted by you using VisiData for editing your CSV of flashcard questions.

**Comment by anjakefala** [comment]
There is also a way to unbind keystrokes, if you never want to sort.

`Sheet.unbindkey('[')`
`Sheet.unbindkey(']')` in your `~/.visidatarc` should do the trick!

You can change them to different keystrokes then with

`Sheet.bindkey('u', 'sort-asc')`
`Sheet.bindkey('b', 'sort-desc')`

Where `u` and `b` could be whatever you like.

**Comment by rlue** [comment]
Wow, thanks for this speedy and detailed response.

`U` totally does it for me. Toggling sort with `[`/`]` would still be _nice_ but not essential. Maybe I'll submit a PR one day instead? :)

**Comment by geekscrapy** [comment]
> Wow, thanks for this speedy and detailed response.
> 
> `U` totally does it for me. Toggling sort with `[`/`]` would still be _nice_ but not essential. Maybe I'll submit a PR one day instead? :)

A toggle for them would be appreciated from my side 👍

**Comment by saulpw** [comment]
So, you can make there be "no sort criteria" using `g[` with no key columns.  But this just means that it won't change the order of the rows, not that it reverts to a "natural" sort order--it'll leave them as they were already sorted.  To revert, you'll have to use undo as @anjakefala suggested; it's the only place that the original sort order is stored.
