### ISSUE TITLE
Provide a way to filter hidden spreadsheet rows

### ISSUE THREAD

**Issue by kbd** [saulpw/visidata#1398]
A lot of times I get spreadsheets with rows that are "deleted" by hiding them. So, the data is still in the spreadsheet but when you view the file in Excel the rows aren't visible. It would be nice if VisiData had a way to toggle hidden rows so that I could process in VisiData what people see in Excel.

**Comment by saulpw** [comment]
Hi @kbd, can you provide a sample data file that has this characteristic?  Also, to be clear, VisiData is showing you all the rows, but you only want to see some of them, correct?  Would it suffice to color/dim the invisible rows?

**Comment by kbd** [comment]
> but you only want to see some of them, correct?

Ideally, one could toggle between showing and hiding hidden rows. Or, if it were possible to *select* hidden or visible rows then the rest of VisiData's filtering is all that's needed, since you can filter by selection and then select further from there, right?

> Would it suffice to color/dim the invisible rows?

Ideally, the sheet would open showing all rows, with hidden rows in a dimmed color. That would be extremely helpful to avoid confusion (what just happened to me ;)

Here is an article about this common problem with regard to Pandas, with code showing how to identify hidden rows (and columns) when reading with `openpyxl`:

https://towardsdatascience.com/how-to-load-excel-files-with-hidden-rows-and-columns-into-pandas-19d445fa5c47

**Comment by kbd** [comment]
Forgot the sample file, I'll make one.

**Comment by kbd** [comment]
This spreadsheet has 3 columns and 3 rows. The middle row and middle column are hidden.

[hidden.xlsx](https://github.com/saulpw/visidata/files/8904128/hidden.xlsx)

**Comment by saulpw** [comment]
Thanks for the sample file, that really helps.  Unfortunately it doesn't look like `openpyxl` exposes the `hidden` attribute anywhere.  If you can write some Python code that loads your file and determines whether a row or column is hidden, then we can do this.  Otherwise we'd have to write our own .xlsx parser (which is not out of the question, but not really on the list of things we want to do, either).
