### ISSUE TITLE
How to access content of previous row, in expression?

### ISSUE THREAD

**Issue by maxigit** [saulpw/visidata#1399]
I'm new to visidata and I am so far loving. However there is something simple that I can't manage to do.
How do you access the previous row  when writing a column expression.
One example is to do a running total (when the formula is  : r0c-1 + r-1c0) 
Or what I am trying to achieve , filling blank of column with the previous value.
For that in need to create a new column and use something like : curcol or <value of the row above, current column>.

I can think I could use something like  : rows[currentRowIndex -1][currentColumnIndex]

But I haven't find a way to get the value of currentRowIndex and currentColumnIndex
.

**Comment by maxigit** [comment]
Ok, I realize there is a setcol-fill command which does exactly that (Except that I need somehow to convert blank string to None).
The question remains, how to reference a cell by its coordinate and is there a way to find the index current row ? (I found that one can insert an incremental column for that).

**Comment by anjakefala** [comment]
> How do you access the previous row when writing a column expression. One example is to do a running total (when the formula is : r0c-1 + r-1c0)

Currently, it is an experimental feature on the `develop` branch, but Saul is implementing the first bits of "windowing": ef0cbac56bfa943e4de764d1719827a00864a262
94f1c9df0dea95ac2660fef4fbbc8ee3124e5101
8ecb47f098e80fbd0396d6770fe1f8688eea469a

The intent of windowing is for functions like running totals. 

Previous issues which mentioned this are:
https://github.com/saulpw/visidata/issues/1210
https://github.com/saulpw/visidata/issues/1129

Since we do have #1129 for tracking this work, I am going to close this issue, and move your comments there. I encourage you to follow that one! 

> (Except that I need somehow to convert blank string to None).

Move your cursor to a cell with a blank string. Press `,` (comma) to select all rows in the current column with that value. Then do `gzd` to set them all to `None`.

> I can think I could use something like : rows[currentRowIndex -1][currentColumnIndex]

This was a clever attempt! =)

**Comment by anjakefala** [comment]
To install `develop` to play with this (with the note that it is experimental, and we welcome feedback):

```
pip3 install git+https://github.com/saulpw/visidata.git@develop
```

I have not played with it very much yet, and Saul might have better guidance. But this is from my cursory playing.

To get a running total for the column `foo`, you can do:

`w` leave the default *1 1*

This creates a new column `foo_window` in which each cell contains a list of values. If you wanted a window of 1 row before, and 1 row after, for each row it will contain 2-3 values. The value in the current row, and the values in the row before and after.

And then, you can do e.g. `=` *sum(foo_window)*

and for each row, you will get a running total.

**Comment by maxigit** [comment]
Thank you very much for you answers. I didnt' realize they were already issues on this topic.
I'll have a go to the develop version and give you some feedback.

**Comment by maxigit** [comment]
I've just tried the develop version and you said "sum(foo_window)".
The only way to do a running total is to include All row before (ie set the
"before number" to the total number of row), which is a bit inefficient.
Would it no be simpler to just add a "last" (or "previous) variable
available in the calculation (which is bound the previous value calculated
in loop calculated all the values of a column).
This way a running total can be computed with

    cursorCol + (last or 0)

**Comment by saulpw** [comment]
Hi @maxigit, you can use `-1` (or any negative value) to mean "all rows before/after current row".  You're right that it's a bit inefficient, but given VisiData's current architecture, it would be a larger change to allow references to the "previous" row.  Every row is independent and does not know its position in the list of rows, and it would require a separate index to make finding the index faster than O(nrows).

**Comment by maxigit** [comment]
You don't need an index to access the previous row, you just need to "remember" it and makes it available in the formula.
Exactly has it is done for setcoll-fill but with a user given expression.
