### ISSUE TITLE
Private mode  (no swap file)

### ISSUE THREAD

**Issue by charlielewisme** [saulpw/visidata#140]
Does visidata store buffers to RAM or to disk?
Can I run visidata without saving anything to disk?

I run a Python2 script that pulls private data for a list of unique IDs. I can pipe the output to vd without saving to disk but, because the data is sensitive, I can only use vd if it doesn't create swap files etc.

A workaround could be to set the temp storage path to a ramfs folder.

**Comment by saulpw** [comment]
Hi @chalewis!  You'll be happy to know that VisiData doesn't store any of the data on disk unless you explicitly save it with Ctrl-S.  Everything is loaded into RAM.

**Comment by saulpw** [comment]
@anjakefala just reminded me also that Ctrl-O (open in external $EDITOR) will save the contents of the edited field to a tempfile, which is usually in /tmp but could conceivably be stored to disk.  But otherwise you should be safe.

**Comment by charlielewisme** [comment]
That is great news. And thanks for the heads up about open in $EDITOR -- got it.
