### ISSUE TITLE
Can't output table to stdout

### ISSUE THREAD

**Issue by maxigit** [saulpw/visidata#1400]
From reading the doc, I understand that one can use vd as filter by sending a table to stdin and getting the result to stdout.
I tried that but which ever I do quit (I tried q Ctr-q Ctrl-Q etc ) but I always get an empty result.
Am I missing something ?

Many thanks

**Comment by saulpw** [comment]
Try adding `-o -` or piping/redirecting the output, and then Ctrl+Q (no shift).

**Comment by maxigit** [comment]
OK, it works indeed if I pipe the output. I was trying `ls | vd` and it
doesn't work.
However `ls | vd | cat'  and Ctrl-q works.

Thank you very much for the quick response.
