### ISSUE TITLE
Trouble with mouse on macbook

### ISSUE THREAD

**Issue by holderbp** [saulpw/visidata#1401]
Is there an option to disable the mouse interaction? I cannot find such a thing in the options. 

It seems that the mouse is not working for me.  I'm using:

saul.pw/VisiData v2.8  (installed with homebrew)
MacOS 12.4
iterm2 terminal

Whenever I click with the mouse in a running vd window, I get something like this in the bottom row:

capture regex: 11M

This occurs if I just try to return to the terminal, after working in a different window/terminal, and click anywhere except the title bar of the window.  Sometimes a click will make it highlight a random column (still with the "capture regex" message).  Using the mouse scroll wheel does not cause scrolling, but brings up a similar kind of response, e.g.:

capture regex: 12M64;12M64;12M

This happens both with an external bluetooth mouse and with the macbook touchpad.

I guess a second questions is: how do I fix the mouse interaction.  But I would be happy to just use vd without the mouse, just with keystrokes (and in that case it would be useful to have all mouse interaction disabled).

**Comment by anjakefala** [comment]
This was really helpful reporting! 

For now, I can answer your question on how to disable the mouse in VisiData.

Add to your `~/.visidatarc`:

`options.mouse_interval = 0` for the mouse-click.
`options.scroll_incr=0` for the scroll wheel.

During your session, you can also press the `Spacebar` and type `mouse-disable`.

**Comment by anjakefala** [comment]
@holderbp, there is a possibility that the mouse events not working is a terminal configuration problem? What is your `$TERM`?

(`iTerm2` should, in theory, be working out of the box with python curses mouse events.)

**Comment by holderbp** [comment]
Thanks for the help!  (And, sorry, I thought I replied to this a few days ago... but must not have sent)

My $TERM is `xterm`.  There certainly could be a terminal configuration problem... the settings on Iterm2 have always been too voluminous for me to make the effort to understand them.  But if you have a suggestion, I'd appreciate it.

I put those options into my `~/.visidatarc` file.  Weirdly, for the first few times I tried it afterwards, a session of `vd`  ignored the mouse, but only for the first "clicks"... then it would start giving the same error.  I've tried it again now, and that behavior has stopped (mouse is ignored... although I can use the scroll wheel still despite the `options.scroll_incr=0`, but it works without errors, so I'm happy with it).  

Thanks for the great tool, I love visidata!

**Comment by holderbp** [comment]
UPDATE:

The mouse disable does not seem to persist for me.  I have the lines in `~/.visidatarc` and the mouse does seem to be ignored when starting a `vd` session.  But after a few commands, the mouse errors start again. This also seems to be the case if I invoke `Spacebar` + `mouse-disable`.  Mouse will be ignored for a while, but the error returns.

These seem to be reproducible ways to get the error:

* Hide my `~/.visidatarc` file. Open a csv file with `vd`. Click or scroll within the window.  (As described in original comment)

* Hide my `~/.visidatarc` file. Open a csv file with `vd`. Invoke `Spacebar` + `mouse-disable`.  Mouse actions are at first not recognized (although scroll works properly). But then.... If I do almost anything (see some exceptions below), e.g., 

   * start a `select regex` with `|` (or an *expr* search with `z|`) but then cancel with `Ctrl-C`
   * successfully perform a `select regex` (or do an *expr* search with `z|') 
   * search within a column with `/`  (or start to search but cancel with `Ctrl-C`)
   * edit a cell with `e`

  The mouse errors return.

* Restore my `~/.visidatarc` file.  Open a csv file with `vd`. Mouse actions are disabled at first (although scroll works properly). But any action from the list in the previous item will bring back error.

I did find some actions that won't initiate mouse errors:
* navigating around sheet
* moving columns/rows with `J` `K` `H` `L`
* select current row with `s`
* visit the Columns or Sheets Sheets
* just pressing `Ctrl-C`
* setting column type with `#`
* resize a column with `_`
* sorting with `[` (or
* making a column "key" with `!`

**Comment by saulpw** [comment]
Thanks @holderbp, this was very helpful.  The common thread between the commands that enable the mouse are that they take input.  And sure enough, when we take a line of input we unset the mouse mask, and then were always turning it back on instead of checking `options.mouse_interval` as we do on startup.  

Thanks again for the great sleuthing and bug reporting!

**Comment by saulpw** [comment]
@holderbp Did this fix your issue?
