### ISSUE TITLE
[xlsx] save fails when file contains errant control characters

### ISSUE THREAD

**Issue by LaPingvino** [saulpw/visidata#1402]
**Small description**
Sample file to test with: https://gist.github.com/LaPingvino/095fdd935cc3e056d7412226f7be4d48
When you try to save this file as xlsx, you get the following error:
`openpyxl.utils.exceptions.IllegalCharacterError`

**Expected result**
Save normally as xlsx, maybe with a warning or question to replace invalid characters.

**Actual result with screenshot**
Didn't manage to do Ctrl-E or screenshot, might attach later

**Additional context**
pip develop version

**Comment by anjakefala** [comment]
Researched this error, and what common approaches to it are.
Recommendations from the internet:
* Use the [XlsxWriter engine](https://pypi.org/project/XlsxWriter/). It handles these characters, apparently?
* Use the regex `ILLEGAL_CHARACTERS_RE` from `openpyxl` to substitute the illegal characters with something else.
* Escape the illegal unicode characters.

**Comment by saulpw** [comment]
It was a control-character (0x0c, line-feed), not a unicode character.  `ILLEGAL_CHARACTERS_RE` only looks for control characters, so now they'll be replaced with a space character when that exception happens.
