### ISSUE TITLE
[loader] CSV with nested JSON columns

### ISSUE THREAD

**Issue by klauern** [saulpw/visidata#1405]
I am not able to expand a column in a .csv file that contains nested JSON in it.  I think that this is either a bug, a lack of skill on my end to be able to do it ( typing `(` doesn't seem to do anything), or a new loader that would need to be implemented to support it.

**Comment by saulpw** [comment]
Try `=json.loads(curcol)`; does that parse it for you?

**Comment by ajkerrigan** [comment]
In case it's useful I've got a little `~/.visidatarc` helper snippet to parse/add json columns, might be handy if you are parsing embedded json columns regularly. It's not _that_ useful beyond what @saulpw already mentioned, but it's a bit less to type and the new column name will be derived from the source column:

```
import json

from visidata import ExprColumn, TableSheet

@TableSheet.api
def parseJsonColumn(sheet, col):
    newcol = ExprColumn("json.loads(curcol)", curcol=col)
    newcol.name = f"{col.name}_json"
    sheet.addColumnAtCursor(newcol)

# adapt keybinding to fit your needs...
TableSheet.addCommand(" j", "addcol-json", "sheet.parseJsonColumn(cursorCol)")
```

**Comment by klauern** [comment]
Oh, that does seem to do something.  What is the process to enter that column (where I'm seeing a lot of `{15}`, `{11}`, etc) and select one key as a new column to pull up to the parent sheet?  If there's a doc for that, I'll read into it, but I'm not sure how to extract nested fields.

<img width="1076" alt="CleanShot 2022-07-05 at 20 50 39@2x" src="https://user-images.githubusercontent.com/4735/177450387-7d3aea5e-a16e-4615-b0ad-35b3f8c7f125.png">

**Comment by klauern** [comment]
Apologies for the slow reply.  I honestly missed this one entirely, and it got buried with all the other notifications that come daily.  This is pretty useful already, however, so I'm hopeful I will be able to figure the rest out eventually.

**Comment by saulpw** [comment]
`(` will expand the `{N}` into columns, which you can then use like any other.

**Comment by arilou** [comment]
> In case it's useful I've got a little `~/.visidatarc` helper snippet to parse/add json columns, might be handy if you are parsing embedded json columns regularly. It's not _that_ useful beyond what @saulpw already mentioned, but it's a bit less to type and the new column name will be derived from the source column:
> 
> ```
> import json
> 
> from visidata import ExprColumn, TableSheet
> 
> @TableSheet.api
> def parseJsonColumn(sheet, col):
>     newcol = ExprColumn("json.loads(curcol)", curcol=col)
>     newcol.name = f"{col.name}_json"
>     sheet.addColumnAtCursor(newcol)
> 
> # adapt keybinding to fit your needs...
> TableSheet.addCommand(" j", "addcol-json", "sheet.parseJsonColumn(cursorCol)")
> ```

I know it's a really old issue but if someone runs into it and uses this script and you are working on big datasets
Add:
newcol.setCache(True)

Everything will be significantly faster, otherwise VD will keep calling calc for the display (calc_height etc.)
