### ISSUE TITLE
[display dict/list]  Option to specify count of elements shown

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1411]
In https://github.com/saulpw/visidata/commit/1d05c497780199401bd3230dde066838e2c4f223 
Saul added the ability to show the first 10 elements of lists/dicts.   Wonderful! Thanks!

It would be useful to be able to provide an option that allows the user to specify how many elements are shown, including 0, the previous default.  Depending on the data and screen size, smaller or longer previews would be useful. 

There are cases where it is useful to be able to use the type-len of the dict/list to distinguish the values.  But there are currently some stack traces I found:  https://github.com/saulpw/visidata/issues/1410
This new feature broke how I was using the values for dict as sizes, with some null values mixed in, causing me to find some issues with numeric_binning when trying an alternate way to look at the values.

Saul already provided a workaround for format control: https://github.com/saulpw/visidata/issues/846
This issue also has some additional ideas on formatting lists & dicts.

**Comment by saulpw** [comment]
Now elements are shown until the width is filled.  There is still the issue with saving lists and dicts in saved formats which should be addressed separately.
