### ISSUE TITLE
Docs make clear that new opened filtered sheets are referenced back

### ISSUE THREAD

**Issue by miguelfg** [saulpw/visidata#1416]
Hi,

Thanks for such great tool!

I am not sure if the quotes keystroke has changed:
      "               open duplicate sheet with only selected rows

I have the feeling that in previous versions I used to open new sheets were all changes were not referenced back to original sheet, so once closing smaller filtered sheets changes were lost if not saved. 

Now it is not like this, I like it. I filter down some rows my original/first-open sheet, modify something, close it, and changes are updated or back in to my first original sheet. Great!

But I think the Guide reference and 'Editing Contents' section are not very clear about this, so it would be cool a docs place to explain how it behaves when.

**Comment by saulpw** [comment]
Hi @miguelfg, thanks for this issue!  It has been this way from the very beginning, and it is a natural consequence of VisiData's architecture, so I would love to make this clearer in the documentation.  Thanks for calling out the specific pages that would be helpful to have it on.

**Comment by miguelfg** [comment]
No, thanks to you for such a great tool and clarify it. I might be mixing up uses of " and ' , and now when I read 'open a duplicate sheet'  in the docs I wasn't sure if it is linked to first sheet or not.

**Comment by saulpw** [comment]
These were rolled into a7813a7f6d5b09fd98582e6c0d54af1f5dea7873.  Thanks for the suggestion!
