### ISSUE TITLE
Support command line column filter

### ISSUE THREAD

**Issue by nickos556** [saulpw/visidata#1417]
For large files/sheets, it would be useful to provide a column filter on the command line. e.g.

`vd -f csv mycsv.csv --filter-columns col_a,col_b,col_z`

This would cause visidata to show a sheet with all columns hidden, except col_a, col_b, col_z

**Comment by saulpw** [comment]
Hi @nickos556, this is a good idea!  I have some ideas, and I'll give it some more thought.   Kondo'ed for now.
