### ISSUE TITLE
default column numbering when --header=0

### ISSUE THREAD

**Issue by rafalcode** [saulpw/visidata#1419]
Hi
Excuse me if this has been asked before, I did search beforehand, honest!
If I use --header=0, I'd like the columns to have default names based on their index, i.e. 1, 2, 3, or A1, A2, A3 etc.
without my having to set them individually with ^.
I could of course add a header to the spreadsheet with such a naming scheme and drop the --header=0, but I was wondering if there was another way to do this?
Cheers.

**Comment by saulpw** [comment]
You could do this:

1. Go to the Columns Sheet with `Shift+C`.
2. Use `gs` to select all columns.
3. Use `gi` to set the `name` column to incremented.
4. `q` to go back to the main sheet.

Or you can just think of it as `Cgsgiq` :)
