### ISSUE TITLE
Request to change the numeric format symbols

### ISSUE THREAD

**Issue by AKS2346** [saulpw/visidata#1425]
I am enjoying using visidata and would like more of my team to use it.  However, small quirks make new users fail to see/read the data quickly.  The most obvious issue is the symbols you use to denote integer, float, etc.  Using a % sign for float when some of the actual data in are percentages and some are not has thrown me off and hard for others who are even newer.  

Since that symbol is highlighted in any case, can you just use normal python or c printf type indicators? f, i, etc.?

**Comment by saulpw** [comment]
Hi @AKS2346, thanks for the suggestion. There's a deeper coherence to those type indicators: they also map to the key to set the column to that type.  I don't think I'm going to change them in the stock VisiData.  But! You can configure them yourself very easily by putting something like this in your `.visidatarc`:

```
vd.typemap[int].icon = 'ⓓ'
vd.typemap[date].icon = '⏲ '
```

And so if you want to put together a helpful configuration and theme to share with your team, then this should get you what you want!  and I would love to hear the results, maybe there is something like a "C" theme that we can provide out of the box that has a bundle of changes to the display like this.

**Comment by AKS2346** [comment]
Yes  - I do use those keys naturally myself at this point and realize there would be a disconnect between the key pressed and the symbol shown.   I did not realize you had such customization available and I will avail our team of your suggestion.  Many thanks for responding. 

Visidata really is a fascinating and great product..  It has really cut down my exploration and experimentation cycle for excel, pandas, and a number of tabular data sets.   Thanks for creating it.
