### ISSUE TITLE
edit-cell commands that don't resolve, cause all subsequent session commands to be dropped

### ISSUE THREAD

**Issue by Dieterbe** [saulpw/visidata#1426]
Hello!
I'm establishing a "sanitization process" for account transaction logs (.csv) from my bank,
ie. a session.vd file which opens the csv file, removes unneeded columns, sets some aggregations, column types, and makes some adjustments to the data. (using shift-f to open a frequency table and changing the names of some of the values returned)

In theory, such a session file could be used for any similar csv file by updating the "open" command and sheet name throughout the .vd file.

However, I notice that as soon as a command "doesn't resolve" (a value to edit using using-cell is not found), all subsequent commands are dropped.
This is problematic because it drops any customizations (including column format setting, aggregators etc), that follow such a command, are not executed, nor are they persisted upon running 'ctrl-D'.

For example, let's say we have these 2 files:
```
/t/visidata ❯❯❯ cat data1.csv
name,height,location
jeff,180,NY
dieter,178,CY
JOHN,178,DE
/t/visidata ❯❯❯ cat data2.csv
name,height,location
jeff,180,NY
dieter,178,CY
```

To show this data how i like it, i create a session file which changes JOHN to john, makes height numeric, sets a sum aggregator, and hides the location column from display.
The file looks like so:
```
/t/visidata ❯❯❯ cat data1.vd                                                                                                                                                                                    ✘ 1 
sheet	col	row	longname	input	keystrokes	comment
			open-file	data1.csv	o	
data1	name		freq-col		Shift+F	open Frequency Table grouped on current column, with aggregations of other columns
data1_name_freq	name	キJOHN	edit-cell	john	e	edit contents of current cell
data1			columns-sheet		Shift+C	open Columns Sheet: edit column properties for current sheet
data1_columns		キlocation	delete-row		d	delete current row
data1			columns-sheet		Shift+C	open Columns Sheet: edit column properties for current sheet
data1_columns	aggregators	キheight	edit-cell	sum	e	edit contents of current cell
data1	name		freq-col		Shift+F	open Frequency Table grouped on current column, with aggregations of other columns
data1			columns-sheet		Shift+C	open Columns Sheet: edit column properties for current sheet
data1	height		type-int		#	set type of current column to int
data1	height		freq-col		Shift+F	open Frequency Table grouped on current column, with aggregations of other columns
data1	name		freq-col		Shift+F	open Frequency Table grouped on current column, with aggregations of other columns
```

running `vd -p data1.vd` works as expected. all desired changes are applied, and running `ctrl-D` creates a session file which is identical to the one we launched with.

But now, if we do this:

```
/t/visidata ❯❯❯ cp data1.vd data2.vd
/t/visidata ❯❯❯ sed 's/data1/data2/g' -i data2.vd
/t/visidata ❯❯❯ vd -p data2.vd
```

Many of the commands are not applied. In particular all desired changes to the columns are not applied. Why? Because the csv file doesn't happen to have the 'JOHN' name in it. running `ctrl-D` confirms that all commands after the 'JOHN' rename are taken out:

```
/t/visidata ❯❯❯ cat data2_name_freq.vd
sheet	col	row	longname	input	keystrokes	comment
			open-file	data2.csv	o	
data2	name		freq-col		Shift+F	open Frequency Table grouped on current column, with aggregations of other columns
```

I'm probably using the session files for something they're not meant for. But it would be nice to be able to somehow declare how to set up a sheet, even if the file we're looking at may not have certain records that we've set up sanitation rules for.

**Comment by Dieterbe** [comment]
BTW, first time visidata user here. this tool is pretty awesome! just wish i had a better process to declare "rules" for sanitizing csv files, rather than mucking around with session files. it seems pretty finnicky in general and not very clear how to edit them.

**Comment by saulpw** [comment]
This is fantastic feedback, @Dieterbe.   I agree that in the longer run it would be nicer to have a better process, I'm just not sure what it is yet.   In the meantime the easiest thing we can do is add an option `replay_ignore_errors` so that all the commands in a session log will be executed, and it won't abort on error.  This should be in 2.9.

**Comment by Dieterbe** [comment]
I was thinking about a declarative config file where one could declare how to remap column and value strings , column config, etc. But actually I will move all my value processing to a separate shell script and work with the output of that, leaving only the column manipulations for the session file. That should do the job.
