### ISSUE TITLE
Open tab separated files

### ISSUE THREAD

**Issue by Tegomena** [saulpw/visidata#1427]
Maybe this is a stupid question, but how can I open CSV files with a tab as delimiter? The command

 vd -d '\t' jacke.csv

don't work, the file is messed up.

**Comment by saulpw** [comment]
You might want `vd -f tsv` if it's actually a TSV file (no quoting), but if it really is just a CSV with a tab delimiter, you have to do `vd -d $'\t'`.  It's a shell thing.

**Comment by Tegomena** [comment]
Thanks for your fast answer, but it still does not work:

vd -d $'\t' jacke.csv

In other commands the "$" syntax works well, for example:

grep $'\t' jacke.csv

Data looks like this (tab between the columns):

Wast    Großwallstadt   9.136015        49.874680
Weste   Eichenbühl      9.340539        49.657569
Wästn   Schwarzenbruck  11.242053       49.357141
Wästn   Grettstadt      10.365063       50.002209

(Its a normal Ubuntu installation with Bash)

**Comment by saulpw** [comment]
Please upload an actual file.  I use `-f tsv` with data as you posted and it works fine.

**Comment by Tegomena** [comment]
Ah great, with "-f tsv" it works perfect, sorry for the trouble ;-)
