### ISSUE TITLE
[unzip-http] Loading percentage progress

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1429]
From the thread: https://github.com/saulpw/visidata/discussions/1413

When loading a file from a zip file over the web it would be useful to show percentage loading progress.
It is possible for a web based file to take longer to load.

Example from the thread:
Here is what I'm seeing: https://asciinema.org/a/QLu6ec9m49qnWCPPcR6VnAjWQ
I quit before the larger table fully loads, but you can see that I'm not seeing any percentage progress.  

This was the command from the demo:

```
vd 'https://files.digital.nhs.uk/publicationimport/pub18xxx/pub18273/nhs-staf-2015-healthcare-gp-csv.zip'
```

Since the demo was made there have been changes made to the unzip-http loader that make it much faster, and less need for this.  It is possible for the loading to be slow, and it would help the user understand progress in those situations.

**Comment by saulpw** [comment]
This would be nice, but seems not that necessary at the moment.  Kondo'ed for now.
