### ISSUE TITLE
Portable clipboard handling

### ISSUE THREAD

**Issue by chocolateboy** [saulpw/visidata#143]
Currently, copying to the system clipboard must be configured manually for every platform apart from macOS. Although it's documented (e.g. [here](http://visidata.org/man/)), I assumed the option was only needed for advanced customization (e.g. on non-standard platforms), and didn't realize that it must be set on Linux until it errored when I tried to use it (and I saw it mentioned in a [comment on a closed issue](https://github.com/saulpw/visidata/issues/98#issuecomment-379616663)).

Why not set it up automatically on all systems, rather than just Macs? There's a library which supports writing to and reading from the clipboard <s>portably and painlessly</s>: [pyperclip](https://github.com/asweigart/pyperclip). It could either be added as an optional dependency, or — better still — copy 'n' pasted into the project (it's a [single file](https://github.com/asweigart/pyperclip/commit/df268c11d1b9bdfcb322e7fdcb61191e572e316c)). The current `options.clipboard_copy_cmd` option could be kept for advanced usage/non-standard platforms.

**Comment by saulpw** [comment]
Hi @chocolateboy, thanks for the feedback.  Around the time of that comment, I tried including pyperclip as you suggest but had issues getting it to work on my (Linux) computer.  I don't remember the details but I think it was going to require more hackery than I was up for at the time.  If you have the time, I'd love if you gave it a go!  If you get it working (it may be easier than I thought), please submit a PR against the dev branch and we'll be happy to include it in 1.3!

**Comment by saulpw** [comment]
Thanks, @chocolateboy!  This is much appreciated.
