### ISSUE TITLE
Wrong version on v2.9 tag

### ISSUE THREAD

**Issue by jpalus** [saulpw/visidata#1435]
`v2.9` tag has `2.10dev` version instead of `2.9`:
https://github.com/saulpw/visidata/blob/v2.9/setup.py#L6
https://github.com/saulpw/visidata/blob/18b57b03cc89268772d87e4781040dbf7bcec6cb/setup.py#L6

**Comment by anjakefala** [comment]
Thanks for letting me know @jpalus! This has now been fixed. =)
