### ISSUE TITLE
[develop loading] Unable to load files from stdin and web

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1439]
**Small description**
Unable to load files from stdin and web

**Expected result**

Loading files from web or stdin works.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 206, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 941, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 927, in optlines
    yield next(it)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/csv.py", line 39, in iterload
    yield next(rdr)
  File "/usr/lib/python3.9/site-packages/visidata/path.py", line 355, in __next__
    r = next(self.rf.iter_lines)
  File "/usr/lib/python3.9/codecs.py", line 1054, in iterdecode
    output = decoder.decode(input)
  File "/usr/lib/python3.9/codecs.py", line 321, in decode
    data = self.buffer + input
TypeError: can't concat str to bytes
```

**Steps to reproduce with sample data and a .vd**

Stack traces:

```
vd -f csv < sample_data/benchmark.csv
vd  https://raw.githubusercontent.com/saulpw/visidata/develop/sample_data/benchmark.csv
vd  https://raw.githubusercontent.com/saulpw/visidata/develop/sample_data/benchmark.jsonl
```

Works:
```
vd -f csv  sample_data/benchmark.csv
```

**Additional context**
Please include the version of VisiData. Latest version of develop

**Comment by anjakefala** [comment]
Known issue with the cutting edge of `develop`! =) This is why the build is currently red. Replay also has the same Exception. Thank you for documenting it.

**Comment by anjakefala** [comment]
I believe this is the commit resulting in the problem: https://github.com/saulpw/visidata/commit/c07e5ded67fd149f246806add3d12970f105c171

**Comment by frosencrantz** [comment]
Brilliant!  Achievement Unlocked! This bug breaks something basic in Visidata, and the robotic watchdogs have already caught it.  That makes me happy. I was worried why something basic was not being reported.  Also, happy this is not in 2.9.1

Maybe someday the build can be the gatekeeper, and make sure that commits have to pass the build before being merged.

A build!   Build status can be found here?
https://app.circleci.com/pipelines/github/saulpw/visidata?branch=develop

**Comment by saulpw** [comment]
Different philosophies about software development.  Some projects insist that their development branch is always functional and never regresses, and they use build pass/fail as a gatekeeper for code.  Their PRs are necessarily larger and take longer to review and merge.  I prefer making smaller individual commits that move the *intent* of the project forward, even as they might regress individual features.  This is because I'm often not sure of how a design or architecture will play out and I want to see how it works for awhile (and what people think of it), without having to do all of the legwork to make everything perfect at the outset.  Then we put more deliberate effort into releases to keep them stable.

That said, I know this is a pretty basic regression, but I wanted to see if I could make some progress towards your previously filed bugs, which pointed to an even more fundamental architectural misstep.  I'm on vacation now but will dive into this fully once I return.

**Comment by anjakefala** [comment]
Also, I really love fixing bugs. When Saul pushes something that makes the build red, I love being the one to fix it. 

If they always stay on his computer until he fixes things himself, then I do not get that bit of joy.

**Comment by anjakefala** [comment]
>A build! Build status can be found here?
https://app.circleci.com/pipelines/github/saulpw/visidata?branch=develop

Yup!

We may move off of CircleCI at one point, but for now that is where they are.

**Comment by frosencrantz** [comment]
This is your project and you can decide how things work. The net result has been great.

Build pass/fail as a gatekeeper doesn’t imply that PRs have to be larger and take longer to review (Is there a review process?)  This is just saying existing tests and any new tests continue to work before committing.  I think this can help with developing new features, and reviewing code. It could take a little longer to code since the new code might identify problems in existing code. But I think that is useful to learn sooner. The process might be faster overall since there is less cleaning up later. It might be better to fix these bugs before committing. 

This won’t prevent all bugs, so there will still be plenty to fix. 😄  It might make the ones found less basic.

Maybe as a first pass, if there was a small subset of the tests that could be used as a pre-commit hook?

Swayed any opinions?  Doubtful…  

Perhaps a less objectionable  way would be to  tag the latest  develop commit to pass tests?  That might allow someone like me who likes to use the develop branch, but doesn’t want to have to deal with basic breakages like this.   To help this project, I feel it is important to report issues. I’m not able to provide feedback or use other fixes if the code doesn’t work for me.  I don’t want to waste time reporting a known issues.  It is not clear to me if there is any effort to keep the tests green, except for maybe when doing a release? So this might not be useful.

The README already has a badge for the CircleCI stable branch, but it doesn't have it for the develop branch.  It might be helpful  to add that badge.  It looks like the CircleCI tests stop at the first failure, so there might be multiple failures being hidden by the first failure. Would it be useful to automatically create bugs for failed tests?

Anyways, it feels like develop has been more broken than in the past, and maybe I should just use stable.   I do feel like the tests have gotten better over time.  I worry that non-functional code might give the wrong impression to new users trying out Visidata from the branch that Visidata doesn’t work, and might discourage them from using it or helping add code.

**Comment by saulpw** [comment]
Thanks for the input, @frosencrantz.  I really appreciate the issues you report, and I'm sorry this breakage has made you more cautious about using the `develop` branch in your daily work.  We'll definitely try to improve the visibility of the test status so you can check before updating and/or reporting bugs, so you don't feel frustrated or like your efforts are wasted.  We do try to keep the `develop` build green even between releases (@anjakefala at least gives me a hard time almost daily whenever they are failing), and will continue to do so, especially knowing that you and other people are actively using that branch.

In any event, this bug should now be fixed.

**Comment by anjakefala** [comment]
@frosencrantz On my end, I am going to proactively file issues for bugs that are known to us, and we are working on!

**Comment by frosencrantz** [comment]
@saulpw glad to hear that.  Thank you for your responses.
@anjakefala thanks for proactively filing bugs.  I think that would be very helpful when things are broken.  Thanks for giving Saul a hard time on broken tests... 😄
