### ISSUE TITLE
v2.9: Parameter in recent commit often evaluates to `None*2`, seems to lead to strange behavior in column-width detection

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#1442]
**Small description**

Commit https://github.com/saulpw/visidata/commit/0ba4f87d065f92d1cdc94b4b21c62ba285efe341 introduces a calculation that often evaluates to `None*2` — line 341 of `column.py`, which reads: 

```python
dw.display = self.format(typedval, width=self.width*2) or ''
```

I don't know the codebase well enough to fully track the effects of this, but some observations:

The line is within a `try` block. Adding `vd.warning(stacktrace())` immediately within the `except` block reveals/confirms the exception: `TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`.  Otherwise, it seems to just sort of fail silently, with no obvious error messages/flags in the interface.

I'm not sure I fully grok all the downstream implications, but one thing it seems to affect (and how I ultimately ended up noticing the bug): the column widths on frequency sheets. Before the commit (i.e., at 0dde5777), a frequency sheet would look like this (using the frequency of `ext` on the directory sheet of the VisiData repo as an example):

<img width="1088"  src="https://user-images.githubusercontent.com/534702/180625644-2ec2d7f9-f8de-4324-b6dc-f6b42e9fe286.png">

But then, with 0ba4f87d, it looks like this:

<img width="1095" src="https://user-images.githubusercontent.com/534702/180625574-2c12537e-63e6-4b90-8669-30ad8cd9b34a.png">

If you go in and manually edit `width=self.width*2` to instead be `width=(width or 0)*2`, the columns go back to correctly auto-resizing. That makes me think that the issue really does stem from the error and not, instead, from the particular math or some other logic introduced in the commit.

**Expected result**

- That the width calculation does not generally raise exceptions.
- That the frequency sheet columns auto-resize, as they did before the commit.

**Actual result with screenshot**

See above.

**Steps to reproduce with sample data and a .vd**

I believe `Shift-F` on any sheet/column will reproduce this.

**Additional context**

See above.

**Comment by saulpw** [comment]
Hey @jsvine, you are correct on all counts.  When `width` is None, it means the column is not hidden, but its width hasn't been determined yet, and will be determined on first display.  I committed your change myself and it seems to work fine.  Thanks for putting in the legwork on this one!

**Comment by jsvine** [comment]
Thanks for the confirmation and the quick fix!
