### ISSUE TITLE
v2.9: Switch from .vd to .vdj for cmdlogs appears to be incomplete

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#1443]
**Small description**

As of https://github.com/saulpw/visidata/commit/b6e71931139325b7a9d5af4bd05273277a04124a, `Control-d` now defaults to saving cmdlogs as `.vdj` files, instead of `.vd` files. But executing `Control-s` from a cmdlog still defaults to `.vd`, I believe due to this line:

https://github.com/saulpw/visidata/blob/8a768b785ad833e908ba00b1ccdbd1259239a51a/visidata/cmdlog.py#L171

**Expected result**

That saving a cmdlog via `Control-d` and executing `Control-s` from the cmdlog suggest the same default file extension (and perhaps also the same filename?).

**Actual result with screenshot**

Using `Control-d`:

<img width="310" alt="Screen Shot 2022-07-26 at 10 15 50 AM" src="https://user-images.githubusercontent.com/534702/181028339-eece8913-3a90-4c80-a000-6919030fdcab.png">

Using `Control-s` from cmdlog:

<img width="299" alt="Screen Shot 2022-07-26 at 10 16 03 AM" src="https://user-images.githubusercontent.com/534702/181028345-ead7dcc8-a64f-41d1-8a93-638ecf4ee96b.png">

**Steps to reproduce with sample data and a .vd**

- `vd sample_data/benchmark.csv`
- `Control-d` to see one default
- `Shift-D` followed by `Control-s` to see the other

**Additional context**

VisiData v2.9.1

**Comment by anjakefala** [comment]
This actually took a bit of work! =) But it is now merged to `develop`. Thank you, @jsvine for pointing out this inconsistency!
