### ISSUE TITLE
Enable setting HTTP User-Agent header 

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1446]
I'm trying to explore this API, but it has aggressive 'security' controls which block the default requests user agent.
This doesn't make much sense for an API, but I can work around it in requests by using the Firefox User-Agent. However, I'd really like to do this in visidata so I can hit the endpoint directly, rather than downloading the JSON, then loading it with visidata.

This is what I'm doing in requests at the moment:

``` python
import requests as rq
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT x.y; Win64; x64; rv:10.0) Gecko/20100101 Firefox/10.0'}
r = rq.get('https://myhospitalsapi.aihw.gov.au/api/v1/datasets/8980', headers=headers)
r.json()
```

But I'm not sure how to get visidata to do that when I try to load a URL.

Not sure if it makes more sense to add this as a CLI flag or a config file setting?
I'm guessing one would start by adding a headers option here?
https://github.com/saulpw/visidata/blob/5e476e1bce454373f1253697dc9a4460839fd77d/visidata/loaders/http.py#L11

**Comment by saulpw** [comment]
Hi @daviewales, you're totally right, that's where it should go.  In fact, the VisiData way would be just add `**vd.options.getall('http_req_')` to the calls to `requests.get()`.  This unpacks all options with that prefix as kwargs to the function call.  Then you can set `options.http_req_headers = { ... }` in your visidatarc as needed.

**Comment by daviewales** [comment]
Thanks @saulpw. I had a crack at making the required changes, but I'm in too deep for my limited VisiData knowledge!

With this diff, I get the error below when trying to load `https://httpbin.org/get` (using `o`):

``` diff
diff --git a/visidata/loaders/http.py b/visidata/loaders/http.py
index ec3313e7..6e2db917 100644
--- a/visidata/loaders/http.py
+++ b/visidata/loaders/http.py
@@ -5,7 +5,7 @@ content_filetypes = {
 }

 vd.option('http_max_next', 0, 'max next.url pages to follow in http response') #848
-
+vd.option('http_req_headers', {}, 'dictionary of headers for requests.get') #1446

 @VisiData.api
 def openurl_http(vd, path, filetype=None):
@@ -19,7 +19,7 @@ def openurl_http(vd, path, filetype=None):

     import requests

-    response = requests.get(path.given, stream=True)
+    response = requests.get(path.given, stream=True, **options.getall('http_req_'))
     response.raise_for_status()

     if not filetype:
@@ -60,7 +60,7 @@ def openurl_http(vd, path, filetype=None):
                 break

             vd.status(f'fetching next page from {src}')
-            response = requests.get(src, stream=True)
+            response = requests.get(src, stream=True, **vd.options.getall('http_req_'))

     # add resettable iterator over contents as an already-open fp
     path.fp = RepeatFile(_iter_lines())
```

``` python
Traceback (most recent call last):
  File "/Users/dwales/Code/not-my-code/visidata/visidata/threads.py", line 206, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/dwales/Code/not-my-code/visidata/visidata/pyobj.py", line 27, in reload
    for r in self.iterload():
  File "/Users/dwales/Code/not-my-code/visidata/visidata/loaders/json.py", line 23, in iterload
    for L in fp:
  File "/Users/dwales/Code/not-my-code/visidata/visidata/path.py", line 355, in __next__
    r = next(self.rf.iter_lines)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 1054, in iterdecode
    output = decoder.decode(input)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 321, in decode
    data = self.buffer + input
TypeError: can't concat str to bytes
```

I've tried running VisiData inside the VS Code debugger, which works pretty well, but I just don't know enough about how everything fits together to figure out where the bytes and strings are coming from.

**Comment by saulpw** [comment]
Sorry, this is my fault, and a bug on the develop branch that needs to be fixed (I'm working on it).  If you apply the same diff to v2.9.1 code, it should work.

**Comment by saulpw** [comment]
Thanks for putting this together, @daviewales !  I fixed the bug and applied the changes myself and have pushed them up.  Please let me know if this works for your case.

**Comment by daviewales** [comment]
Thank you! Yes, it works!

**Comment by geekscrapy** [comment]
You could set these via cmdline args too?
