### ISSUE TITLE
[unzip-http] Extracting a file doesn't check for overwrite or fails.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1452]
**Small description**
Extracting a file doesn't check for overwrite or fails

**Expected result** 
Visidata will prompt if it is ok to overwrite a file of the same name.

**Actual result with screenshot**
Sorry no screenshot, but if my report is not clear I can generate one.

**Steps to reproduce with sample data and a .vd**
```
vd https://files.digital.nhs.uk/publicationimport/pub18xxx/pub18273/nhs-staf-2015-healthcare-gp-csv.zip
```
When there is already a file with the name of a file to extract, Visidata doesn't report any issues when extracting the file again.
Using the `x` (`extract-file`) command will not check if the file already exists, and overwrites the existing file.
Using the `gx` (`extract-selected`) also has this issue.
The `zx` (`extract-file-to`) seem to stack trace if the file exists.

**Additional context**
Please include the version of VisiData. Latest develop  (Which is working again for me!)

**Comment by saulpw** [comment]
Thanks for the report, @frosencrantz.  Should be fixed now.
