### ISSUE TITLE
When editing a cell, how do I enter a new line?

### ISSUE THREAD

**Issue by jingxixu** [saulpw/visidata#1456]
See the title. Many thanks!

**Comment by anjakefala** [comment]
There might be something better, but this is what I do:

Press `e` to edit the cell. Press `Ctrl+O` to open the text in the cell in your [$EDITOR](https://askubuntu.com/questions/432524/how-do-i-find-and-set-my-editor-environment-variable). Add newlines within your [$EDITOR](https://askubuntu.com/questions/432524/how-do-i-find-and-set-my-editor-environment-variable) as you normally would (e.g. `ENTER`).

Save and close, you will be back to VisiData. =)
