### ISSUE TITLE
Impossible to read the active record value

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#146]
Hi,
when I open the frequency table of a field it's impossible to read the active record value.

Visadata is great!

![immagine](https://user-images.githubusercontent.com/30607/39981333-7e277350-5750-11e8-81f6-c8cf1cc40713.png)

**Comment by saulpw** [comment]
Hi @aborruso, this works fine for me. I think it may be a color scheme issue. What platform are you using?  Thanks for enjoying VisiData!

**Comment by aborruso** [comment]
@saulpw I'm using

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by saulpw** [comment]
That's what I'm using too.  It is probably your terminal or terminal configuration that is not working with the color 81/cyan+bold+reverse.  You can try putting `options.color_key_col=''` in your `.visidatarc` for the time being.  Otherwise you can play with your terminal settings, or try a different terminal or font (I use rxvt-unicode with Inconsolata).

**Comment by aborruso** [comment]
Hi @saulpw I have inserted `options.color_key_col=''` in my `.visidatarc` file. 

But when I run `SHIFT + F` for a column, I still cannot read the first cell

![immagine](https://user-images.githubusercontent.com/30607/40279506-0d05b6de-5c44-11e8-8389-817f425b2b60.png).

Thank you

**Comment by saulpw** [comment]
I'm sorry, @aborruso, I don't know what is going wrong.  What is the value supposed to be?  It looks like the most common is just empty (this happens a lot).

**Comment by aborruso** [comment]
Hi @saulpw , no, it's not empty :(

![visidata](https://user-images.githubusercontent.com/30607/40281286-2259a3bc-5c60-11e8-82a5-38cbf42879b4.gif)

**Comment by saulpw** [comment]
Try that same animated screenshot with `options.color_key_col=''`.

**Comment by aborruso** [comment]
@saulpw now it works!!

I had already done the same test, but it did not work.
I will have made a mistake.

Thank you
