### ISSUE TITLE
Confusing model and keystroke consumption in menu bar

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#1470]
From [a discussion](https://github.com/saulpw/visidata/discussions/1464#discussioncomment-3368730):

I would think that once the menubar is active (ctrl+h) I can press those letters to go to their sub-menus.

Additionally, if I hit alt+c for the column, and then change my mind and want to go to the row menu:

1. `r` does nothing;
2. `alt+r` calls a `row key by regex` command; I suspect the menu ate the `alt` key and escaped the menu and then executed `r`.

This is confusing because is the menu system eating characters or not?

**Comment by anjakefala** [comment]
@reagle There was indeed something going on!

Support for the key-presses (e.g. pressing `f` to navigate to `File`) while in the menu has been added to the `develop` branch. It will be part of the next release.

@saulpw What do you think about removing `^[` from https://github.com/saulpw/visidata/blob/02f1b80c5ea9d27d019d4cc07d0bf7c71765f5c7/visidata/menu.py#L741 to solve the `Alt+` being eaten issue?

**Comment by anjakefala** [comment]
Oh whoops, that conversation is here: https://github.com/saulpw/visidata/pull/1473#issuecomment-1212318544
