### ISSUE TITLE
Load command line file arguments from the start

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#1471]
VisiData does not load sheets until they are visited, which means I cannot bounce to the third, for example, sheet once launched with `Alt+3`. I'd like a config option to load the sheets from the start.

**Comment by anjakefala** [comment]
Oh, this is different from what was requested in the discussion! In the discussion I believe you requested the ability to jump to that sheet when opened. https://github.com/saulpw/visidata/discussions/1469

On the **Sheets Sheet*, you can also use `gs` to select all of the rows and `g Ctrl+R` to load them all.

**Comment by reagle** [comment]
First, thank you for your help @anjakefala, you are fantastic.

Two, no, I'd like to start using `alt` to go to my 3 (or however) sheets without having to go to the sheets sheet.

Thank you for the suggestion, I'll try that, but that's 4 keystrokes.

**Comment by saulpw** [comment]
We could make `options.load_lazy` apply to sheets specified on the command line, in addition to subsheets. The only problem is that this option is False by default, meaning 'load everything immediately', which runs counter to the goal of not seizing the means of computation of someone does an accidental `vd *.csv` with several huge csv files.  But I guess we could/should recommend this option be set by people who use large datasets, and then for everyone else it just works more nicely in the first place.

**Comment by reagle** [comment]
That'd work for me.

Another option: I use Sublime Text, which is famous for quickly loading large files, though syntax highlighting huge files can be an issue. This past year they let users set the limit on highlighting: `syntax_detection_size_limit` (default 16MiB). 

In any case, given my request is to simply have the files in the command line arguments assigned `alt` shortcuts at launch, could this be done without actually loading the files?

**Comment by saulpw** [comment]
Hey @reagle, I made a `pw22_noload_on_push` branch with a fix that might work for your case.  Would you mind testing it out?

**Comment by reagle** [comment]
I don't see it on github, maybe I'm not looking in the right place?

https://github.com/saulpw/visidata/branches/active

**Comment by anjakefala** [comment]
@reagle, it was just pushed!

**Comment by reagle** [comment]
Am I suppose to configure something? Do I have to install first? When I run vd from bin/vd on test files, they aren't getting shortcuts.

    ❯ bin/vd tests/xlsx*.vd
     ~/tmp/visidata  pw22_noload_on_push

![SCR-20220912-gjk](https://user-images.githubusercontent.com/596814/189700355-a3434bda-dd2c-4dc7-a7de-58c6a239096b.png)

**Comment by anjakefala** [comment]
Yes, you would need to ensure the VisiData code being imported is from the branch.

Did you originally install VisiData with `pip`? If so, it is quite simple.

`pip3 install git+https://github.com/saulpw/visidata.git@pw22_noload_on_push`

or 

```
git clone https://github.com/saulpw/visidata.git
cd visidata
git checkout pw22_noload_on_push
pip3 install -e .
```

^ This would result in your VisiData installation shifting to whatever is on the branch you have checked out.

You can also try `export PYTHONPATH=/tmp/visidata`, and then executing code from that repo. It is possible that it is still picking up on your installation.

**Comment by reagle** [comment]
@anjakefala, thanks for the pip command. @saulpw, it is working as I expected. Thank you.  

![SCR-20220915-cpa](https://user-images.githubusercontent.com/596814/190412082-fc4bf427-4964-4064-a66a-5038391e6ab4.png)

**Comment by frosencrantz** [comment]
@saulpw and @anjakefala I think this last commit https://github.com/saulpw/visidata/commit/3fb5bc746d95a13989a08559e362c4b845f672a6 has changed the default sheet that comes up when multiple inputs are provide on the command line.  It was a recent change, I haven't confirmed it was this commit, but this looks like it is it.

I have a tool that save data in a directory, and then starts VisiData with args to all the important data files and lists the directory last.  With this new commit, VisiData no longer shows the intended first file initially, but the directory.  The default behavior has changed which makes me need to change my tools.  Would it be possible to restore the default behavior for which data is shown initially?

**Comment by saulpw** [comment]
Yes, the first file on the CLI should be shown as the top sheet.  We'll restore the previous behavior soon.

**Comment by saulpw** [comment]
Should be fixed now, @frosencrantz.

**Comment by frosencrantz** [comment]
Thanks for the quick response, @saulpw!
