### ISSUE TITLE
[colorizer] Show positive / negative numbers in green / red

### ISSUE THREAD

**Issue by chrism2671** [saulpw/visidata#1474]
I expect Visidata can already do this, but I've searched thoroughly and can't find it.

I believe this would be a helpful addition, particularly for those viewing sparse or financial data.

**Comment by geekscrapy** [comment]
Hey @chrism2671 !

Take a look at https://www.visidata.org/docs/api/interface#colors

You could add a colorizer in your .visidatarc which will do exactly what you want. Unfortunately I'm AFK atm so can't give a specific example, but it would be something like:

```
visidata.Basesheet.addColorizer(
    visidata.cellColorizer(1, None, lambda s,r,c,v: 'green' if v>=0 else 'red')
)
```

No guarantees that will work 😅 treat it as pesudo code

**Comment by chrism2671** [comment]
Wow, this is an awesome API, seriously well done!

I think I'm almost there. I've modified your code:
```
TableSheet.addColorizer(
  visidata.CellColorizer(100, None, lambda s,c,r,v: 'green' if v>=0 else 'red')
)
```
The one issue I'm having is:

`addColorizer() missing 1 required positional argument: 'c'`

It's defined as `addColorizer(self,c)`, so I think I'm supposed instantiate a class to get `self`; just not quite sure how to in the `.visitdatarc`.

Thanks so much for your help, and your hard work on this project, really much appreciated!

Also I found a broken link:
![image](https://user-images.githubusercontent.com/456541/184382988-78e70e7a-6163-4a5e-a2da-631603c79836.png)

**Comment by geekscrapy** [comment]
No problemo, happy to help (but so you know, I'm only another happy user like you 😉)

Did you try (without `visidata`):

```python
from visidata import TableSheet, CellColorizer
TableSheet.addColorizer(
    CellColorizer(100, None, lambda s,c,r,v: 'green' if v>=0 else 'red')
)
```

**Comment by geekscrapy** [comment]
Also, what types of data are you trying to use this on? What file format?

**Comment by chrism2671** [comment]
Thank you so much for your help @geekscrapy!

Yep, I did, no difference. I think it's instantiated wrong.

I'm running this on parquet (exported from pandas), and using floats.

**Comment by saulpw** [comment]
Hey @chrism2671 and @geekscrapy, this is really close.  For adding a colorizer to a whole class of sheets, you have to do `TableSheet.colorizers += [ CellColorizer(...) ]`.  I'd love a better API but I'm not that clever of a Python coder yet =)

**Comment by chrism2671** [comment]
Well that, my friends, is a thing of beauty:

![image](https://user-images.githubusercontent.com/456541/184404709-212e337c-3df8-47c1-93d0-3627b4e10934.png)

Final code:

```
def colors(s,c,r,v):
  if v and isNumeric(c):
    if v.value>.0:
      return 'green'
    if v.value<.0:
      return 'red'

TableSheet.colorizers += [visidata.CellColorizer(100, None, colors)]

```

Thank you all so much for your help! (I might try and do a heatmap next!)

PS I will leave it to you to decide whether to close this issue, or keep it open as a feature request. Thank you again!

**Comment by saulpw** [comment]
Great @chrism2671, I'm glad you got it working!  One minor comment, you might want to change the name of the function, to e.g. `color_posneg` or something more specific, as `colors` is already an object in VisiData.  It (apparently) doesn't matter here in your visidatarc, but might cause problems in other circumstances (like if you want to actually use the `colors` object for something after the function was defined).

**Comment by chrism2671** [comment]
@saulpw I'll update that, thank you! One question- what colors are supported? (I tried HTML hex codes, but they didn't work.)

**Comment by geekscrapy** [comment]
Run the command: `open-colors` and it'll show you the palate available 👍

**Comment by saulpw** [comment]
BTW @chrism2671, I just noticed that there are a bunch of errors in your screenshot.  What do you see when you press Ctrl+E?

**Comment by chrism2671** [comment]
It says `no error`, despite the fact it shows an error in the status bar. Is there a way to see the python console?

This is my code:
```
def redgreen(s,c,r,v):
  if v and isNumeric(c):
    if v.value>.0:
      return 'green' 
    if v.value<.0:
      return 13 

TableSheet.colorizers += [visidata.CellColorizer(100, None, redgreen)]
```

Line 2 is the type check; it might be that isNumeric is getting called on something it doesn't understand.

**Comment by geekscrapy** [comment]
~~Have you tried testing to see if the column is a float type? Maybe instead of isNumeric? This might process faster as well rather than isNumeric pulling the column value~~

```python
def redgreen(s,c,r,v):
  if c.type = float and v:
...
```

Edit: just looked up what isNumeric does 🤦‍♂️

@saulpw is this related to the depreciation of isNumeric, vs vd.isNumeric? Try vd.isNumeric @chrism2671

**Comment by chrism2671** [comment]
@geekscrapy visidata.isNumeric has this problem, but it seems like vd.isNumeric doesn't - I hadn't realised they were different.

**Comment by geekscrapy** [comment]
A general rule I follow when deving in visidatarc is to try and use methods exposed from `vd`:
``` python
from visidata import vd
vd.isNumeric(xyz)
```
Same as `vd.status` etc. which got moved to the `vd` namespace recently
I think this is the preferred way to find exposured methods; generally correct @saulpw ?

**Comment by saulpw** [comment]
Yup! Prefer using methods on vd to global methods.  The global methods are there as a vestigial convenience in most cases.

**Comment by gennaro-tedesco** [comment]
Is the method `v.value` still up-to-date after the recent changes? When trying to use
```{python}
def colors(s,c,r,v):
  if v and vd.isNumeric(c):
    if v.value>.0:
```
I get 
> TypeError: '>' not supported between instances of 'str' and 'float'

shouldn't `vd.isNumeric(c)` ensure that each element `v` in the column `c` is indeed a float?

**Comment by saulpw** [comment]
That seems like it should be the case.   Can you post some sample data that exhibits this?

**Comment by gennaro-tedesco** [comment]
I can reproduce it on the following `example.csv`
```
numbers
1
2
```
using an empty `visidatarc` only containing a function of the type
```
def colors(s,c,r,v):
  if v and vd.isNumeric(c):
    if v.value>.0:
      return
```
When opening a file then and setting the column to numeric the exception occurs.

**Comment by saulpw** [comment]
I'm sorry, @gennaro-tedesco, I am not seeing this issue.  Plus I don't understand how defining a function by itself would cause a problem, since it's not being called by anyone.  There must be something else in your visidatarc or something.

**Comment by gennaro-tedesco** [comment]
Let me try to provide a recording: see below


https://github.com/user-attachments/assets/df4b08a0-d81e-427c-8597-b45eaf3c2b2c

the `~/.visidatarc` only contains the function above (I had failed to indicate that I `TableSheet.colorizers += [visidata.CellColorizer(100, None, redgreen)]` in the comment before, apologies).

**Comment by saulpw** [comment]
Ah, I see.  `v.value` is the "base" value (which in CSV is always text), and `v.typedval` is the value after type conversion.  Here (and usually) you want to use `v.typedval`.

**Comment by gennaro-tedesco** [comment]
> Here (and usually) you want to use v.typedval.

Awesome, it works now in fact! 

Thanks for always looking into each single question or comment we users make!
