### ISSUE TITLE
Question: Possible to show columns for non existing key values in json

### ISSUE THREAD

**Issue by DanEEStar** [saulpw/visidata#148]
When I have the following JSON file:

```
[
    {"a": "a1", "b": "b1"},
    {"a": "a2", "b": "b2", "c": "cc", "d": "dd"}
]
```

then visidata does not show the columns `c` and `d`. It only shows `a` and `b`:
```
 a    | b    ‖
 a1   | b1   ‖
 a2   | b2   ‖
```

Is it somehow possible to show also columns for keys which do not exist on every json-object in the array?

**Comment by saulpw** [comment]
Hi @DanEEStar, which version are you using? This issue was fixed (not sure of the exact version), and the example json shows all columns for me with v1.2.

**Comment by DanEEStar** [comment]
I must have been somehow on an older version. I thought I had the newest...

It works now with v1.2!
Thank you!
