### ISSUE TITLE
[addcol-sh] addcol-sh generates stack trace

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1480]
**Small description**
addcol-sh generates stack trace

**Expected result**
No stack trace shown

**Actual result with screenshot**

```
FAILED: addcol-sh Traceback (most recent call last):
  File "/home/runner/work/visidata/visidata/visidata/basesheet.py", line 169, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/home/runner/work/visidata/visidata/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "addcol-sh", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "/home/runner/work/visidata/visidata/visidata/shell.py", line 46, in addShellColumns
    sheet.addColumnAtCursor(
  File "/home/runner/work/visidata/visidata/visidata/sheets.py", line 524, in addColumnAtCursor
    self.cursorVisibleColIndex = self.visibleCols.index(firstnewcol)
ValueError: <visidata.shell.ColumnShell object at 0x7ffb90c40610> is not in list
```

**Steps to reproduce with sample data and a .vd**

Open a sheet, run the `addcol-sh` - `z;` command, type in a shell command,

**Additional context**
Please include the version of VisiData.  Current head.  Currently breaking GitHub actions.  Visidata tool outside of the tests is also generating the stack trace, but the command works.  It has done most of the work needed before it fails.

It looks like the issue is here:
  https://github.com/saulpw/visidata/blob/develop/visidata/sheets.py#L524
It looks like a bad assumption that an added column is visible, so it might not be in the visibleCols list.

The `ColumnShell` column is not visible by default. (right?) It will not be found in the visibleCols.  
One simple fix might be just reorder the columns passed here: https://github.com/saulpw/visidata/blob/develop/visidata/shell.py#L47
Move the ColumnShell to the end of the list rather than the start of the list.

**Comment by anjakefala** [comment]
Thanks @frosencrantz! I ended up going with your suggestion. =)

**Comment by frosencrantz** [comment]
Wonderful!  Thank you, @anjakefala!  Also, I see the addcol-sh test was failing so you removed it.  Now all the tests are passing. 
💚 💚💚
