### ISSUE TITLE
[input] Add a way to paste current cell value into the input line. 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1481]
As part of giving feedback for the unzip-http feature, I was looking at various links to test Visidata.  I put these links in a json files, so that I could remember them.  If I wanted to pass the contents of the current cell and give it to the `o`/`open-file` command input, I need to use the native cut and paste features of my terminal. 

It doesn't look like there is a way to do this with native Visidata keystrokes?  It would be useful if there was a mechanism to use data in a cell as an input prompt.  My initial thought is just a keystroke to grab the current cell value.  But maybe you would want to make it be based on what last yanked, or was put in the memo sheet.

There is a sort of workaround, I could put these links in an html file, and the latest Visidata changes would allow me to open these links.  Though Visidata doesn't allow me to easily create a table of links in html.  Visidata lets me easily create and edit the json file.

**Comment by frosencrantz** [comment]
This is already possible.  Yank the cell value with `zy` / `copy-cell`, then when typing input use Ctrl+Y to paste the contents.

**Comment by saulpw** [comment]
You beat me to it, @frosencrantz !  If there's a way we can make this easier to figure out, maybe that would help others in the future.
