### ISSUE TITLE
[docs] -d is not a well-documented alias for --delimiter

### ISSUE THREAD

**Issue by GiulioCentorame** [saulpw/visidata#1491]
Hi all,
Thanks for this, so far I am loving it. Would it be possible to find a way to open space-separated tsvs without using `vd -f tsv --delimiter=" " filename.extension`? 
I was thinking either by parsing the delimiter automatically (e.g. finding the delimiter in the first x lines of code) or by creating a shorter flag for `--delimiter`?

Edit: premature sending

**Comment by anjakefala** [comment]
Hey @GiulioCentorame, can you please provide more information in your description? How the current CLI looks, and what your proposal is for how you would like it to be different?

Have you tried the `-f fixed` format for space-seperated .tsvs?

**Comment by GiulioCentorame** [comment]
Sorry, you've beaten me in editing the issue! I pressed Enter by mistake

**Comment by GiulioCentorame** [comment]
I did try `-f fixed`, but if they're separated by a single whitespace character, the result isn't great.
This is with `vd -f fixed myfile.txt`:
![image](https://user-images.githubusercontent.com/46871438/186535200-1b0c4a93-0722-4060-8e5c-95934bcc6999.png)

vs `vd -f tsv --delimiter=" " myfile.txt`:

![image](https://user-images.githubusercontent.com/46871438/186535356-495e01c9-be03-434f-b9fe-e19b25d1e680.png)

Ideally, one should be able to either specify `vd -f tsv` and get the 2nd result, or at the very least `vd -f tsv -d " "`. I am aware a lot of functions in e.g. R have excellent parsing of delimiters from the file, one of the best ones being [`vroom::vroom()`](https://github.com/tidyverse/vroom/blob/main/R/vroom.R)

**Comment by saulpw** [comment]
Doesn't `vd -f tsv -d "  "` work?

**Comment by GiulioCentorame** [comment]
...it does. I didn't find the abbreviated version on the docs page so I just assumed it didn't exist

**Comment by saulpw** [comment]
We'll add it to more of the docs, but specifically which docs did you look in?

**Comment by GiulioCentorame** [comment]
`vd --help`, both in visidata and [online](https://www.visidata.org/docs/man/), in the [formats](https://www.visidata.org/docs/formats/) page, and [loading](https://www.visidata.org/docs/loading/) page.
