### ISSUE TITLE
make sheet name from final extension only

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1494]
**Small description**
If you have a file with multiple `.` (periods) in the name, only the first substring is shown as the sheet name.

**Expected result**
To show all of the filename, minus the extension (if there is one). So for the below example, I believe `"services.test.public"` should be shown by default

**Actual result with screenshot**
Opening a file with the name `services.test.public.jsonl` I get the following sheet name

Sheet Status
<img width="189" alt="image" src="https://user-images.githubusercontent.com/11225502/186848860-2ba25dd8-a93e-4230-9c0e-739637e121c2.png">

SheetsSheet
<img width="472" alt="image" src="https://user-images.githubusercontent.com/11225502/186848900-63354eb1-da26-4a69-94ff-85dce9451adc.png">

**Steps to reproduce with sample data and a .vd**
Open a file with multiple `.` in the filename

**Additional context**
Latest as of now

**Comment by anjakefala** [comment]
Oh wow, this is tricky.

 How do you tell the difference between a full filename with `.` and [multiple suffixes](https://github.com/saulpw/visidata/pull/1493/commits/6d26df4a601fe2e3fb62b95fcadb4e59300cdff0)?

**Comment by geekscrapy** [comment]
How do you determine which sheet type to open it as? If you have a file named abc.123.csv, it is always opened with the CSV sheet right? So the same sort of logic could be applied?

**Comment by saulpw** [comment]
Thanks for the report, @geekscrapy!  I agree with you, and I've added some tests to make sure `.foo` `foo.` and `foo` also work as expected (name is entire filename, there is no suffix indicating filetype).
