### ISSUE TITLE
Mention "F1" (help) somewhere in the main window

### ISSUE THREAD

**Issue by zormit** [saulpw/visidata#15]
Although I've used it before, I could not remember that `<F1>` was the key for help. A hint to it somewhere would be help-ful.

**Comment by saulpw** [comment]
The only real place to put this in the program would be on the status line at the start (along with the version information).  Do you think that would be sufficient, to mention it only once at program start?

**Comment by zormit** [comment]
Yup, that should do.

**Comment by saulpw** [comment]
`F1` and `z?` mentioned on status line on startup.
