### ISSUE TITLE
feature request: create a .visidatarc file from option sheet

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#150]
Hi,
it would be very confortable to be able to create a `.visidatarc` file, starting from options sheet (SHIFT + O).

Thank you

**Comment by saulpw** [comment]
Thanks for the suggestion, @aborruso.  That would work the first time, but it would not work if there is already a `.visidatarc`, since we wouldn't want to erase the settings and code already in there.  I agree it would be convenient though.  Are you finding it difficult to edit your `.visidatarc` file properly?

**Comment by aborruso** [comment]
@saulpw if there is already a `.visidatarc` file the user could have the classic "would you like to overwrite ...?" question. Or alternatively if it's exist the user could save it only in another folder, and than choose to overwrite or to copy and paste in the way he/she prefers.

Any difficult to edit it, but to have a gui is confortable.

**Comment by saulpw** [comment]
Okay, we could have `^S` on the Options sheet save in Python format to the given file, providing `~/.visidatarc` as the default, with confirm before overwrite.  If you or anyone else want to implement this, it shouldn't be too hard, and I'd be happy to merge it in.

**Comment by aborruso** [comment]
@saulpw I have no idea on where to start :)

But no problem, it's ok also in this way

**Comment by aborruso** [comment]
Wow, as @anjakefala has written, now it's possible to do it with 1.5.1 https://github.com/saulpw/visidata/releases/tag/v1.5.1

Thanks!!
