### ISSUE TITLE
Date comparison gives wrong result from custom date

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1507]
**Small description**

I have a sample CSV file (attached) with dates in `%d%m%Y` format (`31012022`).
I converted these to proper dates using `z@`.
Then I tried to find all the dates after July 2021, using the following:

`=date(2021, 7, 1) <= dates`

However, this gives me the _opposite_ boolean values to what I was expecting!

|dates       |date\(2021, 7, 1\) <= dates|
|------------|---------------------------|
|2017\-09\-22|True                       |
|2021\-09\-28|False                      |

**Expected result**

I expected to get:
|dates       |date\(2021, 7, 1\) <= dates|
|------------|---------------------------|
|2017\-09\-22|False                       |
|2021\-09\-28|True                      |

**Steps to reproduce with sample data and a .vd**

[test.zip](https://github.com/saulpw/visidata/files/9494126/test.zip)

**Additional context**
Please include the version of VisiData.

saul.pw/VisiData v2.9.1

**Comment by saulpw** [comment]
Thanks @daviewales !  This was a typo/cut-n-paste error in the date class itself, that literally only affected `<=` (seemingly, anyway).  Sorry for getting it wrong.

**Comment by daviewales** [comment]
Thank you @saulpw! Don't apologise!
