### ISSUE TITLE
Open path or URL in a cell?

### ISSUE THREAD

**Issue by jakemayfield** [saulpw/visidata#1512]
Is there a hotkey or command I can run to quickly open up a path or url that is the value in a cell in VisiData? Thanks!

**Comment by anjakefala** [comment]
In v2.10, a `Links` Sheet was added to the html loader: https://github.com/saulpw/visidata/discussions/1424#discussioncomment-3292976

Files linked to could be loaded in VisiData with `Enter`.

This does not generally exist for other loader types, so it would be a feature request. I think the current process if `zY` (copy to clipboard), then `o` and `Ctrl+V`. 

There is a "memo" command which allows you to set a cell value to a variable. However, when I tried `Alt+m` (`memo-cell`), and then used the cell's variable name in `o` (`open-file`), VisiData did not seem to treat my variable name as a variable name. That might be something I can look into. In theory, if that worked, a simple macro could be made.

**Comment by saulpw** [comment]
@jakemayfield I have a `z Ctrl+O` in my own visidatarc that launches an external web-browser on the link in the cell, but haven't had need myself yet for the functionality you're asking about.  I think @anjakefala is on the right track, though I would use `zy` to copy into the local VisiData clipboard, and then `Ctrl+Y` to paste that into the `o` input line.  `zyo Ctrl+Y Enter` is a bit of a handful though and I can totally see adding a command like `zo` to do as you suggest.

**Comment by anjakefala** [comment]
>  zyo Ctrl+Y Enter is

Oh, clever! This can be macro'd!

**Edit**: Nevermind, it cannot be macro'd. `Ctrl+Y` does not work with macro-ing. It saved my input in the macro.

Press `m`, then do `zyo Ctrl+Y Enter` and then press `m` again. Assign this command to the keystroke of your choice (you can use e.g. `1`, `2`, etc). Then you can use that keystroke to open the url as a sheet in VisiData. This is using VisiData's internal clipboard, and will not affect your system clipboard. This will work on `v2.9`, but not on `v2.10`. We will have a macro fix for the next patch release.

**Comment by anjakefala** [comment]
I ended up adding `zo` which does what you asked for! Should be part of the next release. =)

**Comment by rambip** [comment]
Wow, I did not think someone implemented that ! So cool !
I would like to know if this command is documented somewhere. I get "lxml is not installed", but I just would like to open it in my external browser.

**Comment by rambip** [comment]
For reference, here is the config I ended up using to open the current link in the browser:
```py
import subprocess
Sheet.addCommand('go', 'open-url-in-browser', 'subprocess.run(["xdg-open", sheet.cursorDisplay])')
```
