### ISSUE TITLE
more complex tsv file recognition?

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#152]
Sometimes the tsv files I'm dealing with have quoted fields with tabs and newlines (CRLF or LF) within them, and visidata can't properly read them, it assumes a newline designates a new row, even though it's inside quotes. Could this be maybe handled?

Thanks again for this marvelous program, I use it daily !!

**Comment by saulpw** [comment]
Hi @sfranky!  You could try using the `csv` filetype with `csv_delimiter` set to '\t'.  If that doesn't work, please upload a small sample .tsv file to this issue and we'll see if we can figure out an easy way to get it working.

**Comment by sfranky** [comment]
I had actually tried that and it hadn't worked, but for some reason this time instead of typing '\t', I actually typed the tab character by escaping it first, (C^v<TAB>) and it works!!
many thanks, this is making my life so much easier !!
