### ISSUE TITLE
[DirSheet] `Enter` no longer opens a file from the DirSheet

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1527]
**Small description**
`Enter` no longer opens a file from the DirSheet

**Expected result**
`Enter` opens the file in the current row.

**Actual result with screenshot**
https://asciinema.org/a/Uqck07yZJFLhoTfqEkv3Rw7vQ

**Steps to reproduce with sample data and a .vd**

```
vd  sample_data
```
Hit enter on a row for a data file, it doesn't open the file, but does a `pyobj-row`

**Additional context**
Please include the version of VisiData. Close to the latest develop version.

**Comment by saulpw** [comment]
Thanks @frosencrantz, nice catch.  We'll issue another patch release shortly.

**Comment by frosencrantz** [comment]
Thanks @saulpw, works great now.
 
I found this bug partly because of another commit https://github.com/saulpw/visidata/commit/3fb5bc746d95a13989a08559e362c4b845f672a6  has changed the default sheet that comes up when multiple inputs are provide on the command line.   I'll follow up on the original request https://github.com/saulpw/visidata/issues/1471
