### ISSUE TITLE
Exception with `entry_points().get('visidata.plugins', [])` upon startup

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1529]
### Discussed in https://github.com/saulpw/visidata/discussions/1528

<div type='discussions-op-text'>

<sup>Originally posted by **jsdealy** September 15, 2022</sup>
I may be doing something stupid, but my attempts to install have continually just produced this: 

```
Traceback (most recent call last):
  File "/home/justin/.local/bin/visidata", line 8, in <module>
    sys.exit(vd_cli())
  File "/home/justin/.local/lib/python3.10/site-packages/visidata/main.py", line 350, in vd_cli
    rc = main_vd()
  File "/home/justin/.local/lib/python3.10/site-packages/visidata/main.py", line 209, in main_vd
    vd.loadConfigAndPlugins(args)
  File "/home/justin/.local/lib/python3.10/site-packages/visidata/settings.py", line 378, in loadConfigAndPlugins
    for ep in entry_points().get('visidata.plugins', []):
  File "/usr/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 1015, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 453, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 1012, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 947, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 616, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
I'm running Arch Linux. 

Assistance would be greatly appreciated, thank you! </div>

**Comment by anjakefala** [comment]
@jsdealy What is your version of VisiData and your version of `importlib-metadata`?

**Comment by anjakefala** [comment]
While we debug, if you set

```
options.plugins_autoload=False
```

in a `~/.visidatarc` that block of code will not execute, and you should have a working VisiData.

**Comment by anjakefala** [comment]
I bet this is exactly what is going on: https://github.com/pypa/twine/issues/774#issuecomment-880348230

From the thread:

> The error message indicates that importlib_metadata is attempting to load the entry points for every package on the system, but encountering a package whose name is not text (probably None). Thinking I'd seen this message before, I searched the importlib_metadata project for the error message, but I came up empty.

> I suspect you have a package with invalid metadata (missing or corrupted).

> I'd do this:

>>> import importlib_metadata as md
>>> dists = md.distributions()
>>> broken = [dist for dist in dists if dist.name is None]
>>> for dist in broken:
...     print(dist._path)
...     print('metadata length', len(dist.metadata()))

> I'd then inspect the metadata in each path that's printed.

> The issue isn't a twine issue. It just happens to affect twine because twine switched to using this newer importlib_metadata that happens to trip up on this environment. It's possible importlib_metadata should be more lenient in this case, but let's defer that consideration until we determine the cause.

**Comment by jdttt** [comment]
Visidata version: 2.10.1-1
`importlib-metadata` version: 4.8.3

**Comment by anjakefala** [comment]
@jsdealy, would you mind investigating and reporting back?

@saulpw I propose we monitor for this exception, not autoload plugins if it comes out, and print out a helpful warning.

**Comment by jdttt** [comment]
Here's what that produced: 

```
Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata as md
>>> dists = md.distributions()
>>> broken = [dist for dist in dists if dist.name is None]
>>> for dist in broken:
...     print(dist._path)
...     print('metadata length', len(dist.metadata()))
... 
/usr/lib/python3.10/site-packages/protobuf-4.21.5-py3.10-linux-x86_64.egg/EGG-INFO
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
TypeError: 'Message' object is not callable
>>> 
```

**Comment by anjakefala** [comment]
This person is also encountering that: https://github.com/pypa/twine/issues/774#issuecomment-886657451

I cannot reproduce that error, I bet it has to do with versions of `importlib_metadata`... I am not quite sure how to do this post-Python 3.10.

**Comment by jdttt** [comment]
Removing `/usr/lib/python3.10/site-packages/protobuf-4.21.5-py3.10-linux-x86_64.egg/EGG-INFO` and reinstalling visidata has me up and running. 

Thank you for such quick and useful assistance. Hope that this is useful in preventing similar hiccups for others.

**Comment by anjakefala** [comment]
@jsdealy What was the magic to identify the problematic package?

**Comment by jdttt** [comment]
I just followed the instructions you gave (or that the person you quoted gave) for using python to search my importlib-metadata distributions for one with name `None`. Only one path was identified, and I axed it.

**Comment by saulpw** [comment]
> @jsdealy, would you mind investigating and reporting back?
> 
> @saulpw I propose we monitor for this exception, not autoload plugins if it comes out, and print out a helpful warning.

I agree, please tag this issue in an inline comment.
