### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by WizzardUU** [saulpw/visidata#1532]
I noticed some odd behavior and am wondering if anyone else can recreate this (maybe on other distros):

Memory usage increases with time, without any interaction. It seems not related to data as having only a directory listing loaded (vd) and having several tsv files loaded (vd a.tsv b.tsv c.tsv) had the same increase rate of about 1 MB per 80 to 120 seconds. One time I could let it rise to 3 GB.

As an aside, the process had idle CPU usage of about 3-4%, which seems high, but in and of itself not problematic. Though it could point to some unwanted activity related to the memory increase.

I am on Arcolinux (rolling) with 5.19.9-zen1-1-zen
visidata v2.10.1 (installed from the arch repository)
monitored with bpytop 1.0.68

The behavior is consistent over several kernel and visidata updates (at least within the last 2 months) and reboots.

**Comment by saulpw** [comment]
Thanks for filing this issue, @WizzardUU.  VisiData shouldn't be doing anything in its idle state, and definitely shouldn't be using increasing memory during that time.

**Comment by saulpw** [comment]
So, there might still be a memory leak which we should look into, but the above change should stop it from doing anything at all when idling.  This hopefully stems the memory leak too.

**Comment by WizzardUU** [comment]
Just wanted to confirm, that the change (v2.10.2) did work for me. Memory is stable, CPU load is down to Zero. Thanks.
