### ISSUE TITLE
Open files and listing subdirectories via `vds3` plugin not working anymore

### ISSUE THREAD

**Issue by spren9er** [saulpw/visidata#1534]
**Small description**

When using visidata with S3 via `vds3` plugin, `Enter` command is not listing subdirectories or opening a file anymore. Instead, it shows a metadata overview (`name`, `type`, `size`, `modtime`) of current subdirectory or file. This only happens with visidata version 2.10.1. In previous versions it worked fine.

**Expected result**

- Opening a S3 directory should display contents of directory, not metadata.
- Opening a S3 data file should display tabular data like usual, not metadata.

**Actual result with screenshot**

Press `Enter` on directory called `core-pdf` in S3 bucket leads to

<img width="174" alt="visidata" src="https://user-images.githubusercontent.com/5602551/191434130-6980eeb1-ccb7-45b9-9c4c-7c6dd45f76f9.png">

**Additional context**

visidata 2.10.1, macOS 12.5

**Comment by saulpw** [comment]
Hi @spren9er, thanks for bringing it to our attention.  We'll fix it soon.

**Comment by ajkerrigan** [comment]
Thanks for the report here, I'm going to track it separately since it's most likely something funky I did that's just coming to light now.

**Comment by ajkerrigan** [comment]
There's an update [here](https://github.com/ajkerrigan/visidata-plugins/blob/b0ad8c0865acbac6c2b986d6d5488f61476f829b/plugins/vds3.py) which I believe will work around this issue. There are some updates in the area of packaging coming separately, but this seemed worth a hotfix. Let me know if it gets you back up and running or if you continue to have trouble. Thanks!

Note: For the moment, updating means replacing the contents of `~/.visidata/plugins/vds3.py`.

**Comment by spren9er** [comment]
Great, above fix works on my machine!
Thanks!
