### ISSUE TITLE
Show current row number on status line 

### ISSUE THREAD

**Issue by tekumara** [saulpw/visidata#1536]
It would be nice to be able to show the current row number on the status line, to quickly figure out where in a sheet one is. 
That is, if it's not already possible.

**Comment by saulpw** [comment]
Hi @tekumara, try adding this to your visidatarc:

    options.disp_rstatus_fmt += '  {sheet.cursorRowIndex}/{sheet.nRows}'

You can, of course, configure this to include any information about the sheet that's available.

**Comment by reagle** [comment]
@saulpw, thanks for the tip. I've done this but will add my voice to row number being somewhere in the UI as a default, especially since we lost `ctrl+g` to sidebar cycling.
