### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by tekumara** [saulpw/visidata#1537]
When navigating around a large file I'd like to be able to set bookmarks on rows so I can easily return to them.

**Comment by saulpw** [comment]
Thanks for the suggestion, @tekumara!  I'd like this too.

**Comment by saulpw** [comment]
Kondo'ing this for now, but this wouldn't be that difficult of a feature to implement.  I'd consider re-opening it and implementing it, if we had a more detailed description of how it would work, e.g. commands and keybindings and helpstrings and general workflow.
