### ISSUE TITLE
The -d option seems not work properly

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#154]
Hi,
I have [this csv](https://cdn.rawgit.com/aborruso/d0cd18ea6fb8a63ebc23eed8e858886d/raw/46879900b555d87344a18d46bc9b6eb58dc3675a/_22022013172115.csv). When I run `vd -d ";" _22022013172115.csv`, I have only one column.

Am I making some error?

Thank you

![immagine](https://user-images.githubusercontent.com/30607/40887844-f4423bb6-674e-11e8-9844-8d8f84715ffe.png)

**Comment by saulpw** [comment]
For csv files, use `--csv-delimiter`.  All `csv_` options are passed into csv.reader.
