### ISSUE TITLE
[freq-sheet] Ability to add an aggregator column to the freq-sheet without regenerating

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1541]
I often have a situation where I generate a freq sheet, start working with the data and realise I want another aggregated field. This feature would allow me to add a new aggregated column to the freq sheet without navigating away from the already edited, sorted etc. freq-sheet.

**Comment by saulpw** [comment]
Here you go, @geekscrapy, with `addcol-aggr`.

**Comment by geekscrapy** [comment]
Wow, thanks @saulpw
