### ISSUE TITLE
[v2.11dev] incorrect column widths when binary data is used

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1544]
**Small description**

When using the following command to expand base64 data, some binary data causes misaligned column boundaries.

**Expected result**
For the column boundaries to line up. Previously this was the case

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/193052380-116ca854-fd95-4a16-959a-f5c5b5b9566c.png)

**Steps to reproduce with sample data and a .vd**
input
```
+3GgZkHPAm5YmUYxiJXqxKKJJqMCTIW46eJaA2nAep9QIwZ14/NFAs4ObV8CAwEAATANBgkqhkiG
+KoQ9bLyax8cbvViGGju0SlVhquloZmKOfHr8TukIoV64h3uCGFOVFtQjCYDOq6NbfRvMh14UVF5
+V+g/Wjx8zmNoXsARD0qZrrDjZBJEr7HS1vTAMhg
```

command: `base64.b64decode(codecs.encode(text))`

**Additional context**
v2.11dev

**Comment by anjakefala** [comment]
First of all, thanks for such a clear reproduction!

![Screenshot from 2022-10-08 17-14-01](https://user-images.githubusercontent.com/7489659/194731881-d3de9ed9-9348-41dd-a505-7973a3be31ce.png)

I could not reproduce it. =( If you can catch a commit where you are not seeing the mis-alignment, could you try `git bisect` to see if you can find an origin commit? This might be Mac specific.

**Comment by geekscrapy** [comment]
Hey, just looking at the data output, it seems like there is a mismatch in the way the data is displayed.

If we take a look at the first converted line (note the spaces):
Mine: `qfA•`
Yours: `qf A •`

Is this something to do with the bytes that vd considers printable?

**Comment by saulpw** [comment]
Hi @geekscrapy, I can't repro this either.  I think it might be due to how your terminal is displaying Surrogate Escapes, as the default for `encoding_errors` is `surrogateescape`.  Try setting `options.encoding_errors = "replace"` and see if the display is aligned again.  I also have a small fix to `clipdraw` so that surrogate escapes are considered "odd spaces", which seems reasonable to me.

**Comment by geekscrapy** [comment]
Hmm ok, I'll give it a spin. I've not tested in recent versions

**Comment by geekscrapy** [comment]
This doesn't seem to be an issue with the latest version. Thanks for trying to repro, must have been my env
