### ISSUE TITLE
[sqlite] `SqliteIndexSheet` is not `precious`

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1547]
**Small description**
`SqliteIndexSheet` is not `precious`

**Expected result**
`SqliteIndexSheet` is  `precious` and it will show up in the `sheets-all` `SheetsSheet`

**Actual result with screenshot**
When I `q` from a `SqliteIndexSheet`
https://asciinema.org/a/FhCoHauY6qBOqW7JfUJglekLP

**Steps to reproduce with sample data and a .vd**
```
vd employees.sqlite benchmark.csv
```
`q` from page SqliteIndexSheet, then `gS` to get `sheets-all`, missing `SqliteIndexSheet`.

**Additional context**
Please include the version of VisiData.  Latest develop

**Comment by anjakefala** [comment]
This is now fixed on `develop`! It will be in the next patch release.

Thank you for all of the bug reports. =))

**Comment by frosencrantz** [comment]
@anjakefala Thank you.  I was hitting this one a bit recently. I would go into a table, but not get back to the index sheet.

It made me think it would be useful if there was a **parent** command, that would take you to the parent of the data in the sheet you are viewing.  So for a file it would take you to the directory of the file, for a SQLite table it would take you to the index sheet. I don't think all objects have a parent, but those two would be useful.  URLs and zip files also have parent-like connections.

**Comment by saulpw** [comment]
Hi @frosencrantz, the 'parent' command is called `open-source` (we could certainly rename this to `open-parent` which might be a better name too).  This command is unbound, though I've toyed with the idea of binding it to `\`` (backtick), which is semantically similar to its usage in DarkDraw.  All derived sheets have a source/parent sheet; the source of a loaded data sheet is its Path, which is not useful (should raise an error here).

**Comment by frosencrantz** [comment]
Thanks for the reply @saulpw .  I wasn't aware of the `open-source` command.  That is very close to what I want.  It would have helped with this issue.  It helps with a common problem I have where I've filtered down a couple levels how to get back along my tracks to take a different path without quiting.

I still think there is a use for a a `parent` command for the database itself, or when opening a file, the parent might be the directory, even if the file was just passed as an argument on the CLI.  I sometimes create a directory for running VisiData with a data file, and I have to pass in the directory as a argument so I can find the directory and related files, like the query used to generate the output.  I guess some of this could be found via yanking the source of the file, and pasting or if that is the current directory to open dot. Or maybe a command that is open-source, and when the we get the pathname or url level, it starts to go to parent directory
