### ISSUE TITLE
[mouse] Error: getmouse() returned ERR

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1553]
**Small description**
I get the following "bomb out" with no stacktrace (even with --debug) when "slinging" the trackpad mouse up or down.

**Expected result**
To not crash, or give a stacktrace

**Actual result with screenshot**
This just gets printed once returned to the cli: `Error: getmouse() returned ERR`

**Steps to reproduce with sample data and a .vd**
Open a file with more rows than can be fit on the screen
"sling" scroll the view and the crash comes. You need to give it momentum so it scrolls on its own. This occurs in macos

**Additional context**
This seems to occur for me on any commit, so it maybe my setup... If someone could test doing a "sling" scroll that would be good. If it doesn't occur dont waste time on this, it might be my unique setup and I'll try feedback when/if I find a solution... TIA!

**Comment by anjakefala** [comment]
Hey @geekscrapy!

We are not quite sure what is going on, but we just made sure all of the `vd.parseMouse()` calls (the only function which calls `getmouse()`) were in `try`/`except` blocks. https://github.com/saulpw/visidata/commit/c4e2a43bf46278708f14b071e5175ed3ba372485

Could you pull `develop` and check it out?

**Comment by geekscrapy** [comment]
Yea it's very odd. It happens in both my terminals. Same bash -l session though 

I'll test with a generic bash session and see if it's any env variables messing it up 

~~Sorry forgot to say, yea this is in the current commit too~~

I'll try with the new commit

**Comment by geekscrapy** [comment]
OK, so, when using the latest commit (c4e2a43bf46278708f14b071e5175ed3ba372485) it works fine (no error, no stacktrace, its like the issue does not exist), but bc39516261516343aefe1bde9e5728fe5b76afd7 crashes for me.

Anything you want me to try to get the stacktrace?

**Comment by anjakefala** [comment]
We are okay with just having the silent failure! Thanks for the offer and for checking the fix. =)

**Comment by frosencrantz** [comment]
Thanks for fixing this @anjakefala.   Thanks for reporting this @geekscrapy! 
I was seeing this also, but wasn't quite sure what the cause was.  I'll report back if I see it again.
