### ISSUE TITLE
[sqlite] Selecting table from the CLI not working

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1555]
**Small description**
Selecting a sqlite table from the CLI is not working

**Expected result**
Go directly to a sqlite table from the CLI args.

**Actual result with screenshot**

https://asciinema.org/a/oizQ0C2Wmz8D9XOrUesiU69Sq

**Steps to reproduce with sample data and a .vd**

```
vd employees.sqlite +:emp_view::
```

**Additional context**
Please include the version of VisiData. latest develop version

**Comment by anjakefala** [comment]
Thank you @frosencrantz! Just in time for the patch. I need to add an automatic test for that one. :grimacing: What a cursed feature. Do you use it?

**Comment by frosencrantz** [comment]
@anjakefala that's why I rushed the bug report. I could see you were prepping.  Thanks for fixing it quickly! Especially for a non favorite feature of yours. I have been using it recently.  Simonw has these https://github.com/dogsheep utilities that are great at making SQLite databases, but they end up with a lot of tables, so it is useful to be able to jump into the ones of interest.  

I'm always in favor of new helpful tests.  👍

**Comment by frosencrantz** [comment]
And thank you for doing all these recent releases, @anjakefala! :heart: Also, is has been great to see that the GitHub actions have been mostly green 💚 for a while now.
