### ISSUE TITLE
2.10.2 unavailable in PyPI

### ISSUE THREAD

**Issue by zachvalenta** [saulpw/visidata#1557]
<img width="1728" alt="Screen Shot 2022-10-08 at 1 21 43 PM" src="https://user-images.githubusercontent.com/11388735/194719825-b3e6cdeb-da92-4370-aa62-6e47cdf113a9.png">

I installed the dev branch of Visidata to get around [1550](https://github.com/saulpw/visidata/issues/1550).

```sh
pipx install git+https://github.com/saulpw/visidata.git
  installed package visidata 2.11.dev0, installed using Python 3.10.6
  These apps are now globally available
    - vd
    - visidata
done! ✨ 🌟 ✨
```

When I saw [bugfix for 1500](https://github.com/saulpw/visidata/commit/39cbe730f28b42d6e80ace3ae24fc812c6f8a567) and [the 2.10.2 release](https://github.com/saulpw/visidata/commit/bc39516261516343aefe1bde9e5728fe5b76afd7#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3), I reinstalled:

```sh
pipx install visidata
  installed package visidata 2.10.1, installed using Python 3.10.6
  These apps are now globally available
    - vd
    - visidata
done! ✨ 🌟 ✨
```

I thought that maybe pipx was fetching 2.10.1 from its cache but after force upgrading I realized that 2.10.2 just doesn't seem to be available yet.

**Comment by anjakefala** [comment]
`v2.10.2` is not actually released, yet! The `stable` branch reflects the released version. `develop` is the in-development version.

We are planning to release [very soon](https://github.com/saulpw/visidata/pull/1551). =)

**Comment by anjakefala** [comment]
If you do not want to wait, you can always install from github!

`pip3 install git+https://github.com/saulpw/visidata.git` should do the trick.

**Comment by zachvalenta** [comment]
Gotcha, good to hear.

I just worked around by reinstalling from dev:
```sh
pipx install git+https://github.com/saulpw/visidata.git
```

**Comment by anjakefala** [comment]
Aaaand, it is now in PyPi. =))
