### ISSUE TITLE
Ignore comment lines on delimiter-separated files

### ISSUE THREAD

**Issue by GiulioCentorame** [saulpw/visidata#1559]
Hi there,
In the current version, visidata loads delimited files by including the comment lines at the beginning as the first column: 
![Screenshot from 2022-10-10 12-03-56](https://user-images.githubusercontent.com/46871438/194790490-ce7e2bc7-fb6b-4ace-b6ef-fad016793d5e.png)

I think it would be useful to ignore those by default, as they are still relatively common in some delimiter-separated files.

Would that be feasible?

Cheers

**Comment by anjakefala** [comment]
Yes!

You can use `--skip N` to denote how the *#N* rows of the file that you want skipped.

**Comment by saulpw** [comment]
@anjakefala That will only work if the number of lines at the start of the file is a fixed number.  I'm guessing @GiulioCentorame might have a variable number of lines, and I'm wondering if we couldn't provide a `skip_prefix` option or a `skip_regex' option..

**Comment by anjakefala** [comment]
That is not a bad idea!

**Comment by geekscrapy** [comment]
`skip-regex` sounds like a great idea!

I might also use it to prefilter certain rows from input 👍

Question though, how would this work for non-line separated rows like JSON or XML?

**Comment by GiulioCentorame** [comment]
> @anjakefala That will only work if the number of lines at the start of the file is a fixed number. I'm guessing @GiulioCentorame might have a variable number of lines, and I'm wondering if we couldn't provide a `skip_prefix` option or a `skip_regex' option..

Yes, that is the scenario I have encountered most commonly. The first few lines depend on the command that generated it, so the n of lines varies.

**Comment by anjakefala** [comment]
> Question though, how would this work for non-line separated rows like JSON or XML?

I think if I were to implement this, I would first try to implement it for **SequenceSheet**s: https://github.com/saulpw/visidata/blob/2cf8721ae10e46892fc7e385f68d953e084933d8/visidata/sheets.py#L935

**SequenceSheets** have rowtypes which are Python `iterators`, so I should be able to dip into `row[0]` for the `skip_regex`. It would not matter what the datasource is like.

**SequenceSheet** formats that would be supported are csv, fixed width, ods, tsv, and xlsx.

Would you want to use it prefilter json rows? Could you give an example?

**Comment by saulpw** [comment]
@anjakefala interesting idea.  I was thinking of putting it on `visidata.Path` when reading text files, so that it could apply to any text loader.

**Comment by geekscrapy** [comment]
> Would you want to use it prefilter json rows? Could you give an example?

I don't really, comment was more of a consideration

**Comment by frosencrantz** [comment]
There is a CSV module https://github.com/alan-turing-institute/CleverCSV that looks like it can handle these leading comments, and other issues with poorly formatted CSV.  It is supposed to be able to be a drop-in replacement for the builtin csv module.  Would it be useful to change the default CSV loader to be able to take an option that allows it to specify alternative modules?  I’ve been interested in using CleverCSV with VisiData.

The ability to use other parsers as drop-in replacement might also make sense for other loaders, like JSON has at least one drop-in replacement.

**Comment by saulpw** [comment]
If it's truly a drop-in replacement, I wonder if you could add something to `.visidatarc` that does something like `import clevercsv as csv`, such that VisiData would just use it?  It might be as simple as that, or it might require a bit of extra code, but it should definitely be possible.

**Comment by frosencrantz** [comment]
I wasn't able to verify your suggestion to add the import to my .visidatarc file, I'll try when I have some time.  
CleverCSV comes with a CLI tool that will read a bad CSV file and convert it to a good one, this tool doesn't remove leading comment lines.  I was wrong, I now think CleverCSV will not do this sort of clean up.

**Comment by GiulioCentorame** [comment]
Upon reflecting on it, I do not think that using a `skip_regex` flag would be of great use, as I could just almost universally `grep -v` the file and it would probably be reasonably quick even for a few MB. Personally, I would probably prefer a default behaviour editable with a flag (e.g., [R's read.table()](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/read.table)) or just do `grep -v \# filename | vd`

**Comment by scrambldchannel** [comment]
I have a niche use case that I touched on tangentially in https://github.com/saulpw/visidata/issues/1632 where I want to ignore lines starting with `#`

It's trivial to grep around but might be nice if this is a common trope in csv like files. Especially when I get stuck in a powershell world and don't know how to use `select-string` :shrug:

**Comment by saulpw** [comment]
Okay, I added a generic `regex_skip` option for tsv/csv and json (and variants). By default it's set such that it will ignore lines with a leading `#` (and with leading `//` for json), but this can now be disabled by setting the option to an empty string, or changed to some other regex.

@frosencrantz I also changed the csv import to be lazy, so that you can add this to your .visidatarc to monkey-patch the csv module to clevercsv:

    import clevercsv
    import sys
    sys.modules['csv'] = clevercsv

And then the csv loader will use clevercsv throughout.
