### ISSUE TITLE
How can I customize the mouse scrollwheel events to reverse the motion?

### ISSUE THREAD

**Issue by deinspanjer** [saulpw/visidata#156]
I'm using a MacBook, and I'm set in my ways, so the first thing I do is change the touchpad configuration to not be "Normal".  This means if I swipe downward, the window scrolls down, and if I swipe upward, it scrolls up.

Unfortunately, OSX ties the scroll direction together for both the touchpad and the mousewheel, so that means when I swipe upward, Python receives this as a BUTTON4_PRESSED event, and downward is a BUTTON2_PRESSED.

I'd like to reverse these, but I haven't found the right part of the code yet to hopefully find an example of a Command() I can override in .visidatarc.

**Comment by saulpw** [comment]
Hi @deinspanjer!  It's even easier than overriding the command. You can just set the `scroll_incr` option, which by default is 3, to its inverse (-3), in your `.visidatarc`:

```
options.scroll_incr = -3
```

**Comment by deinspanjer** [comment]
That is a great little hack. Thanks Saul.  I am really really loving visidata.
