### ISSUE TITLE
[sqlite/addcol-incr] addcol-incr column shows only null values in dup-selected sheet

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1568]
**Small description**
In a SQLite sheet, addcol-incr `i`, then select some rows, then `"` dup-select.  New sheet has the column but only with null values.

**Expected result**
The incr column would have the values from the original sheet.

**Actual result with screenshot**

https://asciinema.org/a/xIcI3lNiGpYtQGdlM765gOKFU

**Steps to reproduce with sample data and a .vd**

```
vd sample_data/employees.sqlite +:emp::
```
Then  `i` `,` `"`

**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by saulpw** [comment]
Thanks, @frosencrantz !  Now, modifications to user-added columns are not deferred, even if their parent sheets are marked as `defer`.  So the column added by `addcol-incr` is set properly and its values will be copied over when the sheet is duplicated.
