### ISSUE TITLE
Docs on how to customize colors in the user interface

### ISSUE THREAD

**Issue by farzadmf** [saulpw/visidata#1570]
**Small description**

Hi, sorry, I don't have any steps to reproduce or something like that.

I'm looking for documentation on how to customize colors; I've seen things here and there, and I see a lot of links going to [docs/colors](https://www.visidata.org/docs/colors), but that page unfortunately seems to be the only page missing from the docs.

Can you please point me to where I can find docs about the colors. (reason: `visidata` in my terminal is using too bright colors and I'm hoping to be able to customize it)

**Comment by frosencrantz** [comment]
@farzadmf the colors are specified by the options, see https://www.visidata.org/docs/customize/

Also, these might help:
- https://github.com/saulpw/visidata/issues/290
- https://github.com/saulpw/visidata/discussions/1205
- https://github.com/saulpw/visidata/discussions/1093

**Comment by saulpw** [comment]
Hi @farzadmf, thanks for pointing this out.  I wrote up some docs, including for the new inline text coloring syntax, and they'll go live with VisiData v3.0.  Check them out in the meantime and let us know what you think!  https://github.com/saulpw/visidata/blob/develop/docs/colors.md

**Comment by farzadmf** [comment]
Thank you @saulpw ; will check it out and get back if there are any issues (for me I mean :slightly_smiling_face: )
