### ISSUE TITLE
v2.10.2 repeats part of filename suffix

### ISSUE THREAD

**Issue by kunliugithub** [saulpw/visidata#1571]
Create a file say a.diff.csv

In v2.10.2 of vd, open the directory the file resides in. I am seeing a.diff.diff.csv rather than a.diff.csv

**Comment by anjakefala** [comment]
This is a wild bug, @kunliugithub, thanks for the heads up!

This bug originated in v2.10.1. This is the commit it originated in: 3ffb5ea4c002bee1dc57f612209507f5d8a53a87.

**Comment by anjakefala** [comment]
The problem is that `.diff.csv` are considered "suffixes` *and* `a.diff` is considered the name. So when VisiData splices the name and the suffixes together, you get `a.diff` + `diff.csv`. 

Not sure on what the best approach will end up being, but whatever it is should come with tests!

**Comment by saulpw** [comment]
The ultimate fix should be for `visidata.Path` to be more PathLike, with the `name` attribute being the full filename (instead of the stem).  For the time being, I decided to just change the DirSheet to use the internal `_path.name`.
