### ISSUE TITLE
How do I show both date *and* time in a date column type

### ISSUE THREAD

**Issue by ivanmemruk** [saulpw/visidata#1572]
**Small description**
I store a datetime column into a parquet file using pandas/pyarrow.

**Expected result**
Expect to see date _and_ time when viewing the file in vd.

**Actual result with screenshot**
<img width="124" alt="image" src="https://user-images.githubusercontent.com/1493188/197667373-84a73530-dede-4a5f-9431-6df784cbd859.png">

**Steps to reproduce with sample data and a .vd**
Note that `parq` from [https://github.com/chhantyal/parquet-cli] shows the date and time correctly, so the issue is not on the serialization end.

**Additional context**
v2.10.2

**Comment by anjakefala** [comment]
The **fmtstr** column on the Columns Sheet (`Shift+C`) allows you to specify the formatting for specific columns within that session, without affecting the default for the others. It uses the `strftime` formatting language: https://docs.python.org/3/library/datetime.html

The `--disp-date-fmt` argument can be passed through the commandline to set the formatting for all columns of type TYPE in that session. `options.disp_date_fmt` in a `~/.visidatarc` can set a default formatting for all columns of that TYPE always.

If you adjust the formatting, does the full `datetime` show up?

**Comment by anjakefala** [comment]
@ivanmemruk I am going to close this issue as "question answered". =) If you are still unable to get both date and time to show up, please do comment.

**Comment by ivanmemruk** [comment]
Confirming the suggestion above helped, thanks @anjakefala !

**Comment by saulpw** [comment]
I added `type-datetime` (unbound) to type the column as date and set the fmtstr to show H:M:S time.
