### ISSUE TITLE
terminal is corrupted when replaying a save that requires confirmation

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1575]
**Small description**
When replaying a save, with options.confirm_overwrite=True, if the saved file already exists, the save gets stuck waiting for keyboard confirmation, and the drawing on screen gets corrupted.

**Expected result**
The form to confirm the save will be shown, waiting for the user to confirm the save.

**Actual result with screenshot**
While the form waits for user input, the screen draws random characters in random places continually. Sometimes visidata behaves as if keys have been pressed.
https://asciinema.org/a/9bBIfPgOAnZxK5Ugcq1ziAr92

**Steps to reproduce with sample data and a .vd**
Create a file called "existing.tsv"
```
col1	col2
```
Run this cmdlog, ```vd -p cmdlog.vdj```
```
#!vd -p
{"sheet": null, "col": null, "row": null, "longname": "open-file", "input": "existing.tsv", "keystrokes": "o", "comment": null}
{"sheet": "existing", "col": "", "row": "", "longname": "save-sheet", "input": "existing.tsv", "keystrokes": "Ctrl+S", "comment": "save current sheet to filename in format determined by extension (default .tsv)"}
{"sheet": "existing", "col": "", "row": "", "longname": "quit-all", "input": "", "keystrokes": "gq", "comment": "quit all"}
```

**Additional context**
VisiData v2.10.2, Python 3.8.10, Ubuntu 20.04.5

A workaround is to set options.confirm_overwrite=False (or run vd as "vd -y").

There is a separate issue in a code path reached during this bug. In form.py, FormCanvas.run(scr) does not ever reference its scr argument.
https://github.com/saulpw/visidata/blob/924563a0b7eeede80834dc02d8c1f237fe1949c1/visidata/form.py#L48

**Comment by midichef** [comment]
On a different version of Ubuntu (22.04.1), with Python 3.10.6, and still Visidata 0.10.2, the behavior is different.
The terminal is not corrupted. But when a key pressed by the user in response to the form, the response varies. Sometimes the key is received by the form to confirm or disconfirm the save. Other times it is interpreted by visidata as a command: ```y``` ```(copy-row)``` or ```n``` ```(search-next)```.

**Comment by saulpw** [comment]
Thanks for filing this issue, @midichef !  I'll be getting back into VisiData and friends again soon now that [Hannukah of Data](https://hanukkah.bluebird.sh) is finished, and this is definitely on my list of things to fix.

**Comment by saulpw** [comment]
This took some lifting, but should be fixed!  Replay is now reworked to be single-threaded and contained within the mainloop, so it should be cleaner and more robust overall.  Let us know if there are other issues.
