### ISSUE TITLE
Update README to point to GitHub Actions status rather than CircleCI

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1586]
### Discussed in https://github.com/saulpw/visidata/discussions/1580

<div type='discussions-op-text'>

<sup>Originally posted by **frosencrantz** October 29, 2022</sup>

   - Also, should the top level README.md file point at the GitHub action rather than the circleci link?

**Comment by anjakefala** [comment]
Thank you for opening these!
