### ISSUE TITLE
Structured data to SQLite JSON fields

### ISSUE THREAD

**Issue by LaPingvino** [saulpw/visidata#1589]
As it is, when saving e.g. a jsonl file with structured contents in one of its fields to SQLite, it is saved the same way the interface shows the data. This is hard to work with. As SQLite has native JSON support, I think it's more useful to (add the - option to) save structured data fields as JSON.

**Comment by saulpw** [comment]
Thanks for the suggestion, @LaPingvino!  This should be implemented now.
