### ISSUE TITLE
Permission issue for system-wide installation via pypi source

### ISSUE THREAD

**Issue by icp1994** [saulpw/visidata#1591]
In the [visidata pypi source tarball](https://pypi.org/project/visidata/#files), the files under the egg-info folder have the following permission structure:
```
$ ls -l visidata-2.10.2/visidata.egg-info/
total 24
-rw-r----- 1 icp icp 3922 Oct  8 23:20 PKG-INFO
-rw-r----- 1 icp icp 3133 Oct  8 23:20 SOURCES.txt
-rw-r----- 1 icp icp    1 Oct  8 23:20 dependency_links.txt
-rw-r----- 1 icp icp   50 Oct  8 23:20 entry_points.txt
-rw-r----- 1 icp icp   88 Oct  8 23:20 requires.txt
-rw-r----- 1 icp icp    9 Oct  8 23:20 top_level.txt
```
As these don't have read permissions for non-owner/group, when built and installed system-wide it yields a permission error for standard users (`pkg_resources` needs read access)
```
$ ls -l /usr/lib/python3.11/site-packages/visidata-2.10.2-py3.11.egg-info/
total 24
-rw-r----- 1 root root 3902 Nov 10 19:43 PKG-INFO
-rw-r----- 1 root root 3143 Nov 10 19:43 SOURCES.txt
-rw-r----- 1 root root    1 Nov 10 19:43 dependency_links.txt
-rw-r----- 1 root root   50 Nov 10 19:43 entry_points.txt
-rw-r----- 1 root root   88 Nov 10 19:43 requires.txt
-rw-r----- 1 root root    9 Nov 10 19:43 top_level.txt
$ vd
...[Traceback]...
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/visidata-2.10.2-py3.11.egg-info/PKG-INFO'
```
I checked some other packages and their egg-info files provide universal read access. For example [Glances](https://pypi.org/project/Glances/)
```
$ ls -l Glances-3.3.0.4/Glances.egg-info/
total 48
-rw-r--r-- 1 icp icp 16460 Nov  3 20:00 PKG-INFO
-rw-r--r-- 1 icp icp  8786 Nov  3 20:00 SOURCES.txt
-rw-r--r-- 1 icp icp     1 Nov  3 20:00 dependency_links.txt
-rw-r--r-- 1 icp icp    41 Nov  3 20:00 entry_points.txt
-rw-r--r-- 1 icp icp   680 Nov  3 20:00 requires.txt
-rw-r--r-- 1 icp icp     8 Nov  3 20:00 top_level.txt
```

**Comment by icp1994** [comment]
Relevant I suppose: https://github.com/scrapy/scrapy/issues/377

**Comment by anjakefala** [comment]
Hm, weird. These are files that are generated by `setup.py`. Every file in VisiData seems to have appropriate permissions.

I will make sure to add `chmod a+rX` to our deployment process.

**Comment by icp1994** [comment]
Same issue with the recent v2.11 tarball from pypi.
```
$ ls -l visidata-2.11/visidata.egg-info/
total 28
-rw-rw---- 1 icp icp 4580 Jan  1  1970 PKG-INFO
-rw-rw---- 1 icp icp 3256 Jan  1  1970 SOURCES.txt
-rw-rw---- 1 icp icp    1 Jan  1  1970 dependency_links.txt
-rw-rw---- 1 icp icp   51 Jan  1  1970 entry_points.txt
-rw-rw---- 1 icp icp   88 Jan  1  1970 requires.txt
-rw-rw---- 1 icp icp    9 Jan  1  1970 top_level.txt
```

**Comment by anjakefala** [comment]
I do not know how to fix this problem, sorry! Everything had the appropriate permissions when I uploaded it to PyPI,

**Comment by saulpw** [comment]
Hi @icp1994, do you know how to fix this issue?

**Comment by icp1994** [comment]
No, I don't have any experience with uploading to pypi. Last I searched, only relevant thing I found was the issue linked above which they resolved with: `umask 0022 &&  chmod -R a+rX . && python setup.py sdist upload`

Looks like currently they are using PyPA's build for generating sdist https://github.com/scrapy/scrapy/blob/2.7.1/.github/workflows/publish.yml#L24-L31
