### ISSUE TITLE
How do I import a custom module?

### ISSUE THREAD

**Issue by iainelder** [saulpw/visidata#1592]
**Small description**

I have in my working folder a file called stackstatus.py. I can import the module when I run the Python interpreter in my virtual environment by running `import stackstatus`.

I can't import `stackstatus` when running Visidata in the same virtual environment.

**Expected result**

I expect to be able to do the same in Visidata, but I can't get it to work.

I type `g^X` as documented to load a Python module. This works for stock modules such as `math`, but not for `stackstatus`.

When I try it with my module I get the following full stack trace after the error.

```text
Traceback (most recent call last):
  File "/home/isme/.cache/pypoetry/virtualenvs/.../lib/python3.8/site-packages/visidata/basesheet.py", line 182, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/home/isme/.cache/pypoetry/virtualenvs/.../lib/python3.8/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "import-python", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'stackstatus'
```

**Additional context**

Version: saul.pw/VisiData v2.10.2

I want to import `stackstatus` because it defines a function that transforms the data in my sheet. I want to apply it to one column to create a new column using an expression. The function is too complex for an inline expression.

If importing a custom module is not the right way to do this, what is?

**Comment by anjakefala** [comment]
Hi @iainelder!

I would recommend adding the Python module's contents to a `~/.visidatarc`. That will then get imported into the VisiData session everytime you run VisiData, by default.

**Comment by anjakefala** [comment]
Also, is your PYTHONPATH set to include the location with `mymodule.py`? You could try `export PYTHONPATH=/location/to/module.py:$PYTHONPATH`, and seeing if that allows you to import it in VisiData with `gCtrl+X`.

**Comment by saulpw** [comment]
Yes, @anjakefala is right, if you add `import stackstatus` to your `.visidatarc` it should import the same as in any Python REPL.

**Comment by iainelder** [comment]
Thanks for the suggestions. I got it working with the PYTHONPATH environment variable.

I use Poetry to manage my virtual environment.

When I start Visidata like this, I get the error I reported.

```bash
poetry run visidata stackdata.csv
```

When I start Visidata like this, I set the PYTHONPATH to include the working folder in the module search path. This works!

```bash
PYTHONPATH="$(pwd):$PYTHONPATH" poetry run visidata stackdata.csv
```

I tried setting `import stackstatus` in a file called `~/.visidatarc`, but it gives an error similar to the one reported. The difference is that this time the error happens as soon as Visidata starts and not when I explicitly import the module

```
Traceback (most recent call last):
  File "/home/isme/.cache/pypoetry/virtualenvs/.../lib/python3.8/site-packages/visidata/settings.py", line 335, in loadConfigFile
    exec(code, _globals)
  File "/home/isme/.visidatarc", line 1, in <module>
    import stackstatus
```

The PYTHONPATH solution is good enough for me just now, but I'm surprised that it is necessary. Why doesn't Visidata just search the working directory as normal Python does? Is there something else I'm missing here?

P.S. Sorry for the confused naming of `mymodule` versus `stackstatus`. My redacting was sloppy. Let's just call the module `stackstatus` from now on, because that is its name!

**Comment by saulpw** [comment]
If you do `poetry run python -c 'import stackstatus'`, does that work?  VisiData is just calling `exec()` on `.visidatarc` so it should work the same.

**Comment by iainelder** [comment]
It appears to work with `python -c` as well. The command has no output and Bash shows error code 0.

```console
$ poetry run python -c 'import stackstatus'
$ echo $?
0
```

**Comment by anjakefala** [comment]
@iainelder I actually was not able to reproduce.

I put a `foo.py` in my current directory, and I was able to import it using `g^X` without any custom PYTHONPATH shenanigans. My default PYTHONPATH, though is `.`.

**Comment by anjakefala** [comment]
Update, even when I fiddled with my $PYTHONPATH to a completely different directory, I was still able to import the file in the current directory with `g^X`. I wonder if there is something finicky going on with `poetry`'s shell. (I do not use `poetry`, I use `conda`).

**Comment by iainelder** [comment]
It turns out that my default PYTHONPATH is not set. Would that matter?

This gives no output:

```
env | grep 'PYTHONPATH'
```

**Comment by anjakefala** [comment]
It is hard to tell! Because I cannot reproduce (even with `unset`ting my `PYTHONPATH`), it is hard to say.

I do not think it would hurt to have `PYTHONPATH=.` in your environment by default. If you do have that set, do things just work? Do you know about what `poetry` does with your environment?

I can set aside time at another point to take a look with `poetry`. For the sake of this issue, do you have something that works for you?

**Comment by iainelder** [comment]
For the sake of the issue, setting PYTHONPATH explicitly in the command works for me.

I'm happy to close it as resolved before you spend any more  time on this.

It's highly likely that I've done something weird to my Python installation that even I don't know how to reproduce.

I'll be rebuilding my system soon so my problem may just disappear.

If I have the same problem after the rebuild I'll open another issue referencing this one.

Thanks to both of you, @anjakefala and @saulpw, for the warm welcome and the great support. Now I feel more confident investing my time into learning Visidata beyond the absolute basics.
