### ISSUE TITLE
[html loader] Links found in the columns should be wrapped with canonicalize_url()

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1599]
**Small description**
Links found in an html table don't always work when they are relative 

**Expected result**
Links in the generated link# columns can be opened directly 

**Actual result with screenshot**
Relative paths do not work properly with commands  that open urls like `zo`

**Steps to reproduce with sample data and a .vd**

I had sample data but lost it.  If the fix below doesn't work or if context is needed I can find data.

**Additional context**
Please include the version of VisiData.  Latest version of develop

It looks like this line has canonicalize_url():  https://github.com/saulpw/visidata/blob/develop/visidata/loaders/html.py#L77
And it should be added to this line: 
   https://github.com/saulpw/visidata/blob/develop/visidata/loaders/html.py#L110

**Comment by saulpw** [comment]
Thanks, @frosencrantz !  It turns out there wasn't a `canonicalize_url` function after all, but what we actually want to do is turn relative links into absolute links with `urllib.parse.urljoin`, in both cases.  Should be fixed now.
