### ISSUE TITLE
[hdf5] array of scalars not displaying properly

### ISSUE THREAD

**Issue by linwaytin** [saulpw/visidata#1602]
**Small description**
I have a h5 file generated by python (h5py). I assume I can see the data in vd, but a lot empty field showed up (see the screenshot).

**Expected result**
Should be able to see the data.

**Actual result with screenshot**
https://imgur.com/ygtkYqa

**Steps to reproduce with sample data and a .vd**
open with `vd my_data.h5`

**Comment by anjakefala** [comment]
@linwaytin It is impossible to debug this without the sample data or script that produced it! =( I cannot reproduce it on my own h5 files. 

Can you provide either?

**Comment by linwaytin** [comment]
I can give the h5 file, but where can I put it?

**Comment by saulpw** [comment]
Create the smallest .h5 file you can, and submit a PR into our `sample_data` directory with that data.  If it's under 10k we'll merge it, otherwise it can just stay in the PR but we'll be able to get it from your branch.

**Comment by linwaytin** [comment]
OK I found it is actually very easy to reproduce what I saw, using the following python script.
```python
import h5py
import numpy as np

arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

f = h5py.File("test.h5", 'w')
f.create_dataset("/x", data=arr)
f.close()
```
This creates a file `test.h5`. When I run `visidata test.h5`, the result is like what I mentioned in the first post.

**Comment by saulpw** [comment]
Thanks for the report, @linwaytin!  Should be fixed in develop now.

**Comment by linwaytin** [comment]
Awesome. Thank you!
