### ISSUE TITLE
copy row/cell to system clipboard (Windows + Remote Linux via SecureCRT)

### ISSUE THREAD

**Issue by need47** [saulpw/visidata#1603]
This is by no means a buy report.

I have read posts here and googled, but I couldn't find a solution. My situation might be unusual. Any clue is appreciated.

I'm on Windows using SecureCRT to connect to a remote Linux machine. Usually, I just select a piece of text with left mouse button. The data is copied to Windows system clipboard and can be pasted into either SecureCRT terminal or Windows applications like Notepad.

With Visidata (launched within SecureCRT terminal), it seems not allow me to select text with left mouse button, or I haven't figured it out. So I tried keys such Y and zY, none works for me.

Thanks in advance

**Comment by saulpw** [comment]
Does Shift+mouse allow you to select?  (Maybe it's Ctrl+ or Alt+mouse on Windows)

**Comment by need47** [comment]
Bingo! It's Shift+mouse. Thanks a lot.
