### ISSUE TITLE
New change_precision plugin

### ISSUE THREAD

**Issue by andycraig** [saulpw/visidata#1609]
Hi, I've created a plugin repo here: https://github.com/andycraig/visidata-plugins

There's only one at the moment but letting you know in case you'd like to add it to the list of known plugins.

Creating a plugin was very easy - thank you for designing VisiData to make it so straightforward!

**Comment by saulpw** [comment]
Hi @andycraig, thanks for contributing!  I had your change_precision command in mind as a possible solution for #1650.  How do you feel about us incorporating it into core VisiData at some point?

**Comment by andycraig** [comment]
@saulpw I'd be very happy for it to be incorporated into core VisiData! If you'd like me to do anything let me know, and/or feel very free to copy-paste the code from my plugin into VisiData and edit as much or as little as you'd like.

**Comment by saulpw** [comment]
I've incorporated this plugin into VisiData as a standard feature.  It also supports date columns, as part of the request in #1650.

@andycraig Thanks again for contributing this plugin.  If you'd like some stickers, please send me an email with your mailing address and I'd be happy to send you some!

**Comment by andycraig** [comment]
@saulpw Great outcome, thank you!
