### ISSUE TITLE
Documentation: viewtsv fixes

### ISSUE THREAD

**Issue by cstork** [saulpw/visidata#1610]
**Small description**

The link to `viewtsv.py` at the beginning of https://www.visidata.org/docs/viewtsv/ is missing the extension.

At the end of the article it seems that an old name `vdtui` for the utility is used.

Furthermore, it's not clear from the explanations/annotations what purpose `viewtsv` is supposed to serve. How is it different from just opening the tsv-files with `vd`?

**Comment by saulpw** [comment]
Hi @cstork, thanks for reporting these stale bits, they should be fixed now.  It should be cleaned up further to use the actual viewtsv.py code, which has been updated, but it's not critical at the moment.

I'm afraid I don't know how to make its purpose much clearer, though.  As the page says at the top, viewtsv is "great example of a minimal VisiData application".  It's not meant to be a replacement for viewing TSV files in VisiData.  But if you wanted to create your own application based on VisiData, or a loader for a new format, you could start with this skeleton and add your own rows and columns, and have something that works.
