### ISSUE TITLE
pytests fails without ~/.visidatarc

### ISSUE THREAD

**Issue by gunchev** [saulpw/visidata#1611]
**Small description**
Running pytest on 2.10.2 results in FileNotFoundError

**Expected result**
successful tests

**Actual result with screenshot**
    + /usr/bin/pytest-3
    ============================= test session starts ==============================
    platform linux -- Python 3.6.8, pytest-3.4.2, py-1.5.3, pluggy-0.6.0
    rootdir: /builddir/build/BUILD/visidata-2.10.2, inifile:
    collected 22 items

    visidata/tests/test_commands.py F                                        [  4%]
    visidata/tests/test_date.py .                                            [  9%]
    visidata/tests/test_edittext.py ...................                      [ 95%]
    visidata/tests/test_path.py .                                            [100%]

    =================================== FAILURES ===================================
    ________________________ TestCommands.test_baseCommands ________________________

    self = <visidata.tests.test_commands.TestCommands object at 0x7f91690ae160>
    mock_screen = <Mock id='140262509306264'>

        def test_baseCommands(self, mock_screen):
            'exec each global command at least once'
        
            cmdlist = visidata.vd.commands
        
        
            vs = visidata.Sheet('test_commands')
            vs.reload()
            vd = visidata.vd
        
            nerrs = 0
            ntotal = 0
            for longname in cmdlist.keys():
                if not isTestableCommand(longname, cmdlist):
                    continue
                ntotal += 1
                print(longname)
                self.runOneTest(mock_screen, longname)
                vd.sync()
                if vd.lastErrors:
                    # longname, execstr, and vd.lastErrors
                    print("FAILED: {0}".format(longname), '\n'.join('\n'.join(x) for x in vd.lastErrors))
                    nerrs += 1
                    break
                vs.checkCursor()
            print('%s/%s commands had errors' % (nerrs, ntotal))
            if nerrs > 0:
    >           assert False
    E           assert False

    visidata/tests/test_commands.py:103: AssertionError
    ----------------------------- Captured stdout call -----------------------------
    open-config
    FAILED: open-config Traceback (most recent call last):
    File "/builddir/build/BUILD/visidata-2.10.2/visidata/basesheet.py", line 182, in execCommand
        escaped = super().execCommand2(cmd, vdglobals=vdglobals)
    File "/builddir/build/BUILD/visidata-2.10.2/visidata/basesheet.py", line 69, in execCommand2
        exec(code, vdglobals, LazyChainMap(vd, self))
    File "open-config", line 1, in <module>
        'VisiData: a curses interface for exploring and arranging tabular data'
    File "/builddir/build/BUILD/visidata-2.10.2/visidata/_open.py", line 113, in open_txt
        with p.open_text(encoding=vd.options.encoding) as fp:
    File "/builddir/build/BUILD/visidata-2.10.2/visidata/path.py", line 222, in open_text
        return self.open(mode=mode, encoding=encoding or vd.options.encoding, errors=vd.options.encoding_errors, newline=newline)
    File "/builddir/build/BUILD/visidata-2.10.2/visidata/path.py", line 262, in open
        return FileProgress(path, fp=self._path.open(*args, **kwargs), **kwargs)
    File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
        opener=self._opener)
    File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
        return self._accessor.open(self, flags, mode)
    File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
        return strfunc(str(pathobj), *args)
    FileNotFoundError: [Errno 2] No such file or directory: '/builddir/.visidatarc'
    1/1 commands had errors
    ===================== 1 failed, 21 passed in 0.27 seconds ======================
    error: Bad exit status from /var/tmp/rpm-tmp.Wqn9GJ (%check)
        Bad exit status from /var/tmp/rpm-tmp.Wqn9GJ (%check)

**Steps to reproduce with sample data and a .vd**

    rm .visidatarc
    pytest

A simple `touch ~/.visidatarc` allows the tests to complete.

**Comment by anjakefala** [comment]
Our CI servers currently create the `.visidatarc` as part of the test run. I think my ideal change would be catch the exception and print out, "test run requires `~/.visidatarc`". 

That test is running through all of the commands, and `open-config` is one of them.

**Comment by anjakefala** [comment]
Thanks @gunchev! Tests should now not fail without a .visidatarc.
