### ISSUE TITLE
visidata.vd.view_pandas(<df>) showing wrong number

### ISSUE THREAD

**Issue by YasserKa** [saulpw/visidata#1612]
**Small description**
Stated in title

**Expected result**
Correct number

**Steps to reproduce with sample data and a .vd**
```
import visidata
import pandas as pd

df = pd.DataFrame([1427519497238458390])
visidata.vd.view_pandas(df)
```
Shows:
```
0                                  #
1427519497238458368
```

**Additional context**
saul.pw/VisiData v2.10.2

**Comment by saulpw** [comment]
This is due to DataFrame `.iloc` returning the value as a `float` which is naturally imprecise. This is the same as:

```
>>> int(float(1427519497238458390))
1427519497238458368
```
