### ISSUE TITLE
Custom-date column not recognized as numerical value when plotting

### ISSUE THREAD

**Issue by tdussa** [saulpw/visidata#1613]
When a column with a custom date format is parsed using the custom-date type, it is correctly converted into a datetime structure.  However, when this data is plotted, it is not recognized as a numerical type.

**Expected result**

"Normal" date fields (those that are interpretable as the standard `type-date` type by pressing `@`) can be plotted as numerical values, both as data columns (on the y axis) and as key columns (on the x axis).

**Actual result with screenshot**

Custom-format date colums interpreted as `type-customdate` (by pressing `z@` and entering a fitting type string) are _interpreted_ correctly into a timestamp, but are not recognized as numerical values when plotting.  When trying to plot such a column as values (on the y axis), the error message `is non-numeric` is displayed; when trying to plot some data using a custom-date column as key column, a plot is created, but the time series is not displayed as such but as a number of discrete data points (effectively plotting one time series per data row).  See the attached screenshot.

**Steps to reproduce with sample data and a .vd**

See the attached sample CSV and VDJ files.

**Additional context**

I'm running VisiData version 2.10.2.

[test.csv](https://github.com/saulpw/visidata/files/10089444/test.csv)
[test.vdj.gz](https://github.com/saulpw/visidata/files/10089459/test.vdj.gz)
![Incorrect_plot](https://user-images.githubusercontent.com/6197517/203924153-3402c189-b97e-474a-98a5-11038d4381a1.png)

**Comment by geekscrapy** [comment]
@tdussa , I think I have got around this quasi bug by converting the date col to epoch (a float) with `.timestamp()`

**Comment by tdussa** [comment]
Oooh, interesting idea! I'll try and see how far I get with it.  THX! :)

**Comment by tdussa** [comment]
Excellent!  So this turns out to be a viable workaround:
 - Create a derivative column of the custom-format date column by appending a `.timestamp()`
 - Then set the derivative column to type `date` (`@`)

This seems to do the trick. :)

### Addundum:

This workaround also means that the x axis is labeled with complete date strings (e. g., `2022-12-20`), not with the custom-format dates, so it is not a _complete_ workaround unfortunately.  Still, you get 90 % of the way, I guess.

**Comment by anjakefala** [comment]
@tdussa I checked with my own custom-date, and I believe that @saulpw has resolved this issue as of v2.11. I am going to close it @tdussa, but please feel free to re-open if it is still an issue for you.
