### ISSUE TITLE
Packages very old

### ISSUE THREAD

**Issue by PaluMacil** [saulpw/visidata#1617]
**Small description**

I'm not sure how or who packages this tool for Ubuntu, but the version is old enough that there isn't even a menu in the current deb provided via apt. This was pretty confusing since the docs start off showing a menu, and trying to activate or show it was the first order of business for someone like me that prefers this convenience. This might be an apt only thing, but I left this issue general so that other packages can be checked. I also considered this to be a bug rather than feature since the doc mismatch and time spent trying to show the menu is uncomfortable.

**Expected result**

**Actual result with screenshot**

```
$ sudo apt install visidata
...
Get:1 http://ca.archive.ubuntu.com/ubuntu jammy/universe amd64 visidata all 2.2.1-1 [157 kB]
```

**Steps to reproduce with sample data and a .vd**

NA

**Additional context**

```
$ vd --version
saul.pw/VisiData v2.2.1
```

**Comment by anjakefala** [comment]
Hi @PaluMacil!

We are planning on updating the packages in Debian and Homebrew in the near future. Because updating a package in Debian is so time-consuming, and any bugs found historically have required me to push an update within 2-weeks or the package was removed, I only update it when we are very comfortable in the stability of the current release. We are reaching that point for 2.10, and it is very likely to be the version updated in Debian.

I currently have other priorities, but it is very likely that we will publish an update in Debian in 2023.

**Comment by anjakefala** [comment]
> This was pretty confusing since the docs start off showing a menu, and trying to activate or show it was the first order of business for someone like me that prefers this convenience.

This is a very good point!

**Comment by PaluMacil** [comment]
I've hoped before to find time to first learn Debian packaging and then assist, but the requirement you describe is a bit demanding. Thanks for the fast response. This tool looks fantastic.

**Comment by daviewales** [comment]
@PaluMacil You might consider installing visidata with [pipx](https://pypa.github.io/pipx/) as an interim solution. It will install visidata into an isolated virtual environment from Python's pip package manager, and will add the executable script to your path. This gives you the latest version of visidata without adding any packages (except pipx) to your system Python packages. The pipx method also works on Windows and Mac.

**Comment by IzzySoft** [comment]
@anjakefala if it's just getting the packages into the repo and it's not the creation of the packages themselves, two more options come to mind:

* attaching them to your [releases](https://github.com/saulpw/visidata/releases)
* make them available to me (e.g. by the previous step) to add them to [my apt repo](https://apt.izzysoft.de/ubuntu/dists/generic/) (don't be confused about the "ubuntu" in the URL, that has historical reasons)

Meanwhile, thanks for the hint with `pipx`, didn't know about that!

**Comment by anjakefala** [comment]
We did update the Homebrew, and submitted the updated package to Debian testing!
