### ISSUE TITLE
Help me debug an environment problem

### ISSUE THREAD

**Issue by PaluMacil** [saulpw/visidata#1618]
**Small description**

After running `pip3 install visidata` in an activated **Python 3.10** environment in **PyCharm** on **Ubuntu 22.04**, I tried to run `vd` but saw `bash: /usr/bin/vd: No such file or directory` instead of expected output. Either the docs or the script itself seem to be incorrect.

**Expected result**

Running the install and command as the docs specify should find the binary.

**Actual result with screenshot**

NA

**Steps to reproduce with sample data and a .vd**

Opened Terminal in Pycharm (which activates the venv--in this case anaconda) folloed by the following:

```
(scientificProject) me@my-box:~/Source/scientificProject$ pip3 install visidata
Collecting visidata
  Downloading visidata-2.10.2-py3-none-any.whl (329 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 329.2/329.2 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil in /home/me/anaconda3/envs/scientificProject/lib/python3.10/site-packages (from visidata) (2.8.2)
Collecting importlib-metadata>=3.6
  Downloading importlib_metadata-5.1.0-py3-none-any.whl (21 kB)
Collecting zipp>=0.5
  Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)
Requirement already satisfied: six>=1.5 in /home/me/anaconda3/envs/scientificProject/lib/python3.10/site-packages (from python-dateutil->visidata) (1.16.0)
Installing collected packages: zipp, importlib-metadata, visidata
Successfully installed importlib-metadata-5.1.0 visidata-2.10.2 zipp-3.11.0
(scientificProject) me@my-box:~/Source/scientificProject$ vd --version
bash: /usr/bin/vd: No such file or directory
(scientificProject) me@my-box:~/Source/scientificProject$ python --version
Python 3.10.4
(scientificProject) me@my-box:~/Source/scientificProject$ python -m vd
/home/me/anaconda3/envs/scientificProject/bin/python: No module named vd
(scientificProject) me@my-box:~/Source/scientificProject$ vd
bash: /usr/bin/vd: No such file or directory
```

**Additional context**

Due to https://github.com/saulpw/visidata/issues/1617 making the deb install not very helpful for me, I can't currently enjoy this tool at all.

**Comment by PaluMacil** [comment]
I was just able to run the tool with `visidata` instead of `vd`. I'm not sure if that's a packaging issue or environment, though I suspect it's some form of user error based upon the lack of other complaints from the wide community here.

**Comment by ajkerrigan** [comment]
Wonder if there were some remnants left behind from the apt install related to #1617? Good catch finding that running `visidata` works though :+1: . A command like `which -a vd | xargs ls -l` might help reveal if you've got multiple dueling `vd` binaries floating around, where maybe one one is an unwanted leftover. Also if `/usr/bin/vd` is gone but your shell is too emotionally attached to the memory, `hash -r` may help it forget.

**Comment by anjakefala** [comment]
@PaluMacil If you are still having trouble, or want more attention to help debug, please re-open the issue!

**Comment by PaluMacil** [comment]
I can certainly alias another command and I'm not using the tool enough to care so I don't feel the need to keep the ticket open. Thanks for the help! And thanks for the great tool
