### ISSUE TITLE
Aborting Read Of SQLite Database with WAL Leaves wal and shm Files

### ISSUE THREAD

**Issue by cwarden** [saulpw/visidata#1622]
**Small description**

If I load a large sqlite database created with write-ahead logging enabled in vd, then quit before vd is done counting all rows in the tables, it leaves behind the wal and shm files.

**Expected result**

No writes to disk when opening a database, or at least no leftover files when quitting vd.

**Actual result with screenshot**

```
$ vd big-wal.db
<quit vd>
$ ls big-wal.db*
big-wal.db  big-wal.db-shm  big-wal.db-wal
```

**Steps to create sample database**

```
$ wget https://download.cms.gov/nppes/NPPES_Data_Dissemination_December_2022.zip
$ unzip NPPES_Data_Dissemination_December_2022.zip endpoint_pfile_20050523-20221211.csv
$ sqlite3 big-wal.db
sqlite> PRAGMA journal_mode=WAL;
sqlite> .mode csv
sqlite> .import "endpoint_pfile_20050523-20221211.csv" big
sqlite> .quit
```

**Additional context**

Visidata ad8b7f1b7eb55cf9dd986132b38cda5d57079962

**Comment by saulpw** [comment]
According to [the sqlite docs](https://www.sqlite.org/uri.html#uriimmutable), we have to  pass `immutable=True` as part of the query string; adding `mode=ro` still leaves the files around.  Also note that immutable doesn't mean read-only, it also means that no other app is modifying it either (which is true in many/most cases).

I added passthrough options to sqlite for both connect kwargs and query params, so you can set `sqlite_param_immutable=True` and then it will behave as you want (and this should work in your .visidatarc too).

There should probably be a short option `--readonly` that works for everything.  I'll add it to the list.

**Comment by cwarden** [comment]
I think what I want is a way to have visidata execute `PRAGMA journal_mode=DELETE` right after opening the database.

**Comment by saulpw** [comment]
Okay, we can add an optional statement to be executed before running any statements.  What should the option be called?  `options.sqlite_onconnect` ?
