### ISSUE TITLE
[status bar] Clicking on status bar does nothing

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1625]
**Small description**
Clicking on the status bar does not do the expected operations.

**Expected result**
Per Saul https://github.com/saulpw/visidata/discussions/1616#discussioncomment-4301100:
> Clicking on the sheet name itself (not the whole status bar) should do something: left-click to go to the sheets sheet, right click to rename the sheet.

**Actual result with screenshot**

- https://asciinema.org/a/gvx09hw5fHdpCK3ive93bRW1Y
  -  I click on  the sheet name with both left and right buttons and it does not do anything.  The clicking does cause the cursor to change columns.
 
- https://asciinema.org/a/cwIvucYMi1VohpbPO9teKhX4p

**Steps to reproduce with sample data and a .vd**

Click with the mouse on the sheet name

**Additional context**
Please include the version of VisiData.  Latest develop version.  Based on discussion https://github.com/saulpw/visidata/discussions/1616

**Comment by anjakefala** [comment]
Commit where right-click to edit stopped working: e2cd508610e82f1cf12189b64c3676f39c31f548

Code where the right and left-click buttons for statusbar are meant to be set: https://github.com/saulpw/visidata/blob/54dff5e29ce88bea19eb30492cf8da4ec14fa1de/visidata/statusbar.py#L131

**Comment by saulpw** [comment]
Thanks for reporting, @frosencrantz, and @anjakefala for the extra info!  It was working in splitpane mode but not non-splitpane mode. Should be fixed now.

**Comment by frosencrantz** [comment]
Works great now.  Thanks @saulpw and @anjakefala
