### ISSUE TITLE
Menu hotkeys don't work on Windows

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1630]
I press Alt-P on Windows 7, the plot menu doesn't show.

Versions:
 * Python 3.10.7
 * `visidata==2.10.2`

**Comment by ni-asutcliffe** [comment]
FWIW - I can confirm this on Windows 10 when run from within Powershell. The functionality works as expected when using wsl

**Comment by cool-RR** [comment]
Screenshot from Windows 10 on PowerShell (see error message at bottom):

![Windows 10 x64-2023-02-19-14-02-20](https://user-images.githubusercontent.com/56778/219946737-c9b4320d-bade-4164-8df5-cbef0e124847.png)

**Comment by saulpw** [comment]
Thanks for this, @cool-RR.  Can you try adding this to your .visidatarc and seeing if it works:

```
bindkey('ALT_F', 'Alt+F')
```

If so, we'll start a windows compatibility module, like we have with macos already.

**Comment by cool-RR** [comment]
I tried that, but as soon as I create a `.visidatarc` file I get this error when starting VisiData: `ValueError: source code string cannot contain null bytes.`

I'm not sure what that happens, I just copied your line into `.visidatarc`. This bug didn't happen when working with the same setup but WSL instead of PowerShell.

**Comment by saulpw** [comment]
That's a separate issue to debug.  I mean does your `.visidatarc` file have a null byte in it somehow?

**Comment by cool-RR** [comment]
Predictably, it was a file encoding issue. Fixed now.

But that line didn't work. Interestingly, now when I press `Alt-F`, the error message is `no command for ALT_F` while for other menus it's `no command for "ALT_E"`, with quotes.

**Comment by saulpw** [comment]
Apologies, internally it's actually `^[f` which is more awkward.  I'll fix that, but this should work more reliably:

```
bindkey('ALT_F', 'menu-file')
```

**Comment by cool-RR** [comment]
That does work.
