### ISSUE TITLE
[config] save presets of column width/type/fmtstr

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1631]
I go through lots of CSV files. Many of them are similar in structure. When I tell Visidata that I want to customize the way I view a CSV file (e.g. show one column as a date, change column widths, hide columns etc.) I want to be able to save this as a preset so I could apply it with one keypress to any other CSV file I'll open, without having to go through the entire customization process every time.

**Comment by frosencrantz** [comment]
@cool-RR take a look at this thread, there is a workaround near the end.
https://github.com/saulpw/visidata/discussions/1488

**Comment by saulpw** [comment]
Thanks for the suggestion, @cool-RR!  You're not the only one who wants something like this.  As @frosencrantz pointed out, there are some workarounds which might be helpful.

**Comment by saulpw** [comment]
As per #1488, I added a `Sheet.knownCols` property, to specify properties of known columns, in `visidatarc`:

    Sheet.knownCols.timestamp.type = date
    Sheet.knownCols.timestamp.fmtstr = '%H:%M:%S'

which will set the `type` and `fmtstr` of any column named `timestamp` after the sheet finishes loading.

This manual configuration in visidastarc is the simplest solution for this issue.  Saving metadata presets for a whole sheet, to be applied to other data sources, would probably be better handled with .vds metadata-only files, as suggested in #892.  Let's give this a try for now and see how far it gets us.  Maybe we can add some "AI" that notices when you've applied the same metadata multiple times to the same-named column, and then automatically adds it to the knownCols in your .visidatarc.

**Comment by cool-RR** [comment]
Thanks @saulpw
