### ISSUE TITLE
Esc should exit out of the menu bar

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1636]
When you enter the menu bar (for example by pressing Alt-F), you should be able to press Esc to exit out of the menu bar.

**Comment by cool-RR** [comment]
I see that pressing Esc twice works, but I'm not really sure why we'd need to press it twice.

**Comment by saulpw** [comment]
`Esc` is a special key/character in the terminal.  If we want `Alt+Letter` to work, then there needs to be some delay before accepting `Esc` keypresses as their own.  I've tried to make this work in the past but couldn't do it while keeping other functionality.

**Comment by cool-RR** [comment]
I understand. I saw now that `q` works to exit the menu bar, so that's good enough for me.
