### ISSUE TITLE
Command for going to parent folder: open-dir-parent

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1642]
I love using `vd` like Norton Commander to navigating my folders. One limitation is that you can't easily go to folders above the folder you opened it in. I wish there was a command and key binding for that.

**Comment by saulpw** [comment]
There is `open-dir-parent`, bound to backtick (`), added for #1601.

**Comment by cool-RR** [comment]
While I do see this comment defined in `shell.py` in my local VisiData installation, pressing the backtick doesn't go to the parent folder. Trying to run the command manually causes an error message "no command open-dir-parent" to be shown. Also, the command doesn't show in the commands sheet.

Either I'm missing something, or this issue should be changed into a bug.

**Comment by cool-RR** [comment]
This has happened for me both on Windows and on Linux.

**Comment by anjakefala** [comment]
@cool-RR I have confirmed that it does work on the `develop` version of VisiData! I suspect you have an issue with your local VisiData environment. There is an earlier version of VisiData on your system that is being picked up.

**Comment by cool-RR** [comment]
I have tested this as well now, and indeed under the `develop` version, this feature works. I don't think I have a problem with my local environment. I'm running the latest version `2.10.2` and that feature was implemented after this version. I didn't realize it was that new. Thanks anyway!
