### ISSUE TITLE
Allow disabling esoteric Unicode characters

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1643]
Visidata uses some cool Unicode characters like ⌀ and ⎘. These can sometimes not work in some shells, making the output confusing because it has rectangles with question marks in them.

I think there should be an option to VisiData to gracefully degrade these symbols to more common characters that can be displayed everywhere.

**Comment by saulpw** [comment]
Hi @cool-RR, the problem is probably not the terminal, but the font it's using, which doesn't include these characters.  You could try installing the GNU Unifont which should include everything in the BMP.

If we make an option/theme like this, it should also:

- change all colors to white/black since some terminals can't display colors
- remove all display attributes since some terminals can't display underline/bold
- uppercase all characters since some terminals can't display lowercase

**Comment by cool-RR** [comment]
> Hi @cool-RR, the problem is probably not the terminal, but the font it's using, which doesn't include these characters. You could try installing the GNU Unifont which should include everything in the BMP.

I installed Unifont now and carefully defined it as an alternative font in ConEmu. This works so I'm happy. I'm still confused by the fact that both Chrome and the Ubuntu shell are [able to show these icons perfectly](https://stackoverflow.com/questions/74956602/how-does-chrome-display-esoteric-unicode-characters) without Unifont, under the same fonts I tried in Conemu.

Still, this feature would be useful so I think we should keep it open. I agree with your first two points but I think that the last one is too extreme.

**Comment by saulpw** [comment]
Glad you got something working!

> Still, this feature would be useful so I think we should keep it open.

We like to keep a clean issues list, so we proactively close wishlist items that we don't plan to work on.  They're still in the backlog and anyone is welcome to submit a PR or try to convince us that it'd be worthwhile to prioritize.  And if you [sponsor me on Patreon](https://patreon.com/saulpw), you can choose to designate an issue to keep open.

**Comment by cool-RR** [comment]
I'm trying to figure out which font to use for the demo. The trick with Unifont won't work, because it only worked in a different shell program that didn't show colors correctly.

Do you use a font that shows all VisiData icons correctly? I can't find one that does.

**Comment by saulpw** [comment]
Try the `ascii8` theme, which should be ascii only (and only 8-colors to boot).

**Comment by cool-RR** [comment]
Tried it, I don't like the colors. I think I'll just be okay with the broken characters.

**Comment by cool-RR** [comment]
Do you have a comprehensive list of all the funky characters that you use in VisiData? This would mean  ⌀ and ⎘, the brailler characters, that chevron thing, and anything else that might not appear in some fonts.

**Comment by saulpw** [comment]
They're all in the `disp_` options.  You should be able to listify the default, unfurl, and select only rows with non-ascii chars, to get the comprehensive list you want.

**Comment by cool-RR** [comment]
Awesome. Good thing I just learned how to save a column to file 😎
