### ISSUE TITLE
[reload-rows] Don't scroll to top on reload

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1655]
I've used vd to open a text file that is being continuously updated. After some more content was written to it I pressed Ctrl-R to reload. It did reload but it also scrolled back to the top. This is jarring because I was already looking at some data somewhere in the middle of the file.

**Comment by saulpw** [comment]
Hi @cool-RR, this is tricky.  We could disable checkCursor if the sheet is loading.  We need to make a formal isLoading() anyway, and then we could try it out and see if there are any weird side effects..

**Comment by saulpw** [comment]
Okay, I added a new `reload-rows` command (and corresponding `Sheet.reload_rows()`) that does not reset the columns, and also maintains the cursor position.

**Comment by cool-RR** [comment]
Awesome, thank you! 

I'm not on the latest version. Is that something I can copy-paste into my `.visidatarc` or does it depend on new code that doesn't exist in 2.11.1?

**Comment by cool-RR** [comment]
(Obviously I'll copy-paste the `Sheet.reload_rows()` method, I'm asking whether there's anything beyond that it depends on.)

**Comment by saulpw** [comment]
Yes, this depends on a recent refactor, so you can't just copy-paste this one.

**Comment by cool-RR** [comment]
I understand. Crossing fingers for a release soon.
