### ISSUE TITLE
Imprecise integer conversion

### ISSUE THREAD

**Issue by xlucn** [saulpw/visidata#1674]
**Small description**
When I use `#` key to convert a column of integer strings to actual integers, those larger than `2**53` will be converted imprecisely.

**Expected result**
For 64-bit integers larger than `2**53` (not sure about even larger ones), perform exact string to integer conversion.

**Actual result with screenshot**
The integers in the range above are converted to `int(float(number))`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

1. `vd test.csv`
2. Press `#` key
3. See 9007199254740993 (`2**53+1`) converted into 9007199254740992

Data file `test.csv`:
```
number
9007199254740993
9007199254740992
9007199254740991
```

Commandlog:
```
#!vd -p
{"longname": "open-file", "input": "test.csv", "keystrokes": "o"}
{"sheet": "test", "col": "number", "row": "", "longname": "type-int", "input": "", "keystrokes": "#", "comment": "set type of current column to int"}
```

**Additional context**
Please include the version of VisiData.
VisiData v2.10.2

There was a similar case in a very recent issue #1612, but that one is limited to pandas' `iloc` already converting numbers to float. However my case happens directly to plain text data file, I would like visidata to perform precise conversions, i.e., as if `int(number)`, for the fore-mentioned integer range.

At last, here is my use case if anyone is interested. I am viewing some scientific data (of Gaia telescope) with some columns being source IDs. The IDs are large 64-bit integers (so they are very close to `2**63`). Although it's not necessary to convert the IDs to integers, but it's weird to see them being converted into another number when I explicitly asked to "set their type to integer" while knowing they are definitely small enough to be stored in a common 64-bit integer type.

**Comment by saulpw** [comment]
Okay, so the issue in *this* case is that VisiData's default format string for `int` is `{:.0f}`, which I chose over `{:d}` for some small edge case that I don't remember.

As people seem to like their huge integers being shown with perfect precision, we may change this default ultimately.  For now, you can fix it yourself by adding this to your .visidatarc:

```
options.disp_int_fmt = '{:d}'
```

**Comment by xlucn** [comment]
Oh, thanks for the reply. I definitely remember noticing that format string, but didn't relate to that when writing this issue. Silly me :(

Now I have tried the fix, and it's behaving as I expected now. 

In case you consider changing this later, I will keep the issue open for now.
