### ISSUE TITLE
[join] error when joining sheets with different numbers of key columns

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1678]
**Small description**
When sheets have different numbers of key columns, joining them fails with a traceback.

**Expected result**
I'm not sure what behavior to expect. Is a join valid if there are different numbers of columns? Should there be a warning?

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/visidata/threads.py", line 198, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/visidata/join.py", line 137, in reload
    self.addColumn(JoinKeyColumn(cols[0].name, keycols=cols)) # ColumnItem(c.name, i, sheet=sheets[0], type=c.type, width=c.width)))
  File "/usr/local/lib/python3.10/dist-packages/visidata/sheets.py", line 510, in addColumn
    col.recalc(self)
  File "/usr/local/lib/python3.10/dist-packages/visidata/join.py", line 97, in recalc
    c.recalc()
AttributeError: 'NoneType' object has no attribute 'recalc'
```

**Steps to reproduce with sample data and a .vd**
```vd -p join.vdj```
[a.csv](https://github.com/saulpw/visidata/files/10419263/a.csv)
[b.csv](https://github.com/saulpw/visidata/files/10419264/b.csv)
[join.vdj.txt](https://github.com/saulpw/visidata/files/10419265/join.vdj.txt)

**Additional context**
v2.10.2
The key code starts here with zip_longest():
https://github.com/saulpw/visidata/blob/38c2203076bab7eeb73f9cebafb6560d56f10f97/visidata/join.py#L170

**Comment by saulpw** [comment]
Thanks for the report, @midichef !  We already `fail()` if a sheet has no key columns, so I extended the check to make sure that all sheets have the same number of key columns.
