### ISSUE TITLE
[sql] pressing 'Shift+Q' in a subsheet loses the sheet for full session

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1679]
**Small description**
When viewing a SQL table in a SqliteSheet, hitting 'Shift+Q' causes all rows in the table to be lost. The row count for that table goes to 0 in the SqliteIndexSheet.

**Expected result**
'Shift+Q' should return to the index sheet and leave the table intact.

**Steps to reproduce with sample data and a .vd**
```vd -p quit-wipes-rows.vdj```
[a.db.zip](https://github.com/saulpw/visidata/files/10421244/a.db.zip)
[quit-wipes-rows.vdj.txt](https://github.com/saulpw/visidata/files/10421245/quit-wipes-rows.vdj.txt)

**Additional context**
v2.10.2

**Comment by anjakefala** [comment]
@midichef What is your goal with using `Shift+Q` instead of `q` in this context? By design, `Shift+Q` frees a sheet from memory.

**Comment by saulpw** [comment]
I think the issue might be that for loaders with subsheets (like sqlite), if a subsheet is quit-free `rows` should be reset to `UNLOADED`, so if the sheet is pushed again, the sheet is automatically reloaded.

**Comment by anjakefala** [comment]
@saulpw That makes sense!

**Comment by anjakefala** [comment]
With [6b2e78e](https://github.com/saulpw/visidata/commit/6b2e78efcc1f20cffad716b02403df9ddb8b1675), the row count is still set to 0, but the table can be re-loaded again with `Enter`. I think that makes sense with `Shift+Q` behaviour, and am going to mark this as fixed. Please re-open if you disagree @midichef!
