### ISSUE TITLE
Create New Table from Clipboard

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1680]
It would be nice to have a command which can create a new table directly from the clipboard.

For example, suppose I have tab separated data in my clipboard.
I would like to be able to execute a visidata command to load a table from the clipboard.
The command might ask me what filetype I am loading (tsv in this case).
Then it would load the data directly from the clipboard.

This would be particularly handy for quick file format conversions. e.g. if I copy a table from OneNote and want to convert it to a Markdown table, I could just import it into Visidata form the clipboard, and copy it back to the clipboard as a markdown table.

**Comment by geekscrapy** [comment]
This sounds like a great idea!
I do something similar at the moment on Mac. I use the following to take in clipboard data, the same might exist for Windows/Powershell?

`pbpaste | vd -f json -`

**Comment by daviewales** [comment]
Windows has a copy command (`clip.exe`), but not a paste command.
However, you should be able to do:

```
echo 'paste content here' | vd -f tsv -
```

(I forgot the trailing `-` when I tried it earlier.)

**Comment by saulpw** [comment]
I just pushed an `open-syspaste` command which I think is a good start on what you want. 

@daviewales Would you be up for sponsoring this feature?  It could use a sentence or two docstring at the top of the file, and if you wanted it to ask for an input filetype, you could extend it to do that too.  And any other little tweaks that might be useful.

(I put it in the new `features/` toplevel folder to indicate that it's a standalone little feature.  We're importing them all by default for now, and may provide an option to enable/disable them individually in the future.)

**Comment by daviewales** [comment]
Thanks @saulpw! I'll have a look. 😄 I would definitely use the input filetype, so I'll see if I can figure it out.
