### ISSUE TITLE
Feature request: Add command `reload-rows`

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1683]
The `reload-rows` command could used on CSV and JSON sheets (and others probably), and it will reread the file in case there are new rows. Unlike `reload`, it won't reset the column types or anything else in the sheet.

Previous discussion: https://github.com/saulpw/visidata/discussions/1663

**Comment by saulpw** [comment]
Okay, I added a new reload-rows command (and corresponding Sheet.reload_rows()) that does not reset the columns, and also maintains the cursor position.
