### ISSUE TITLE
Using Ctrl+T to swap nonexistent characters leads to IndexError

### ISSUE THREAD

**Issue by gfrmin** [saulpw/visidata#1684]
**Small description**

When searching with regex, pressing Ctrl+T before any characters are inputted results in an `IndexError: string index out of range` error.

**Expected result**

Nothing should happen, just when one character is inputted.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/416374/213660475-23fe0d42-1eb2-44c0-83c8-3bd03a24a124.png)

**Steps to reproduce with sample data and a .vd**
Press "|", for example, to search for rows in current column with regex, then immediately type Ctrl+T to see error.

**Additional context**
Version saul.pw/VisiData v2.10.2

**Comment by gfrmin** [comment]
This seems to result from using the `splice` function (https://github.com/saulpw/visidata/blob/develop/visidata/_input.py#L225) with an empty string.

**Comment by saulpw** [comment]
Thanks for reporting this, @gfrmin!   Should be fixed in `develop` branch shortly.
