### ISSUE TITLE
Show cell value in sidebar plugin

### ISSUE THREAD

**Issue by radostyle** [saulpw/visidata#1685]
I created this plugin because it was a feature I wanted.

Sometimes I want to see the text of a long column in a larger view without having to hit "e" then "Ctrl-o", so when you press F2 then this will show the text in the new sidebar and if it still isn't enough then you can hit "e" and "Ctrl-o".

Here is a demo:
https://asciinema.org/a/QNgsIlv3QDYZxvqHdcngk1Gfr

```
'''
Show cell value in sidebar plugin.  Press F2 to show the current cell in the sidebar when moving row up or down.
.visidatarc: `import plugins.show_cell_in_sidebar`
'''

__author__ = 'Jon Alvarado <radostyle@github.com>'
__version__ = '1.0'

from visidata import vd, BaseSheet
from visidata import Sheet

Sheet.__show_cell_in_sidebar = False

@Sheet.api
def cursorDown(sheet, amount):
    cursorDown.__wrapped__(sheet, amount)
    if Sheet.__show_cell_in_sidebar:
        vd.status(sheet.cursorRowIndex)
        sheet.sidebar = str(sheet.cursorCell.value)

@Sheet.api
def show_cell_in_sidebar(sheet):
    Sheet.__show_cell_in_sidebar = not Sheet.__show_cell_in_sidebar
    sheet.sidebar = str(sheet.cursorCell.value) if Sheet.__show_cell_in_sidebar else ""


BaseSheet.addCommand('KEY_F(2)', 'show-cell-in-sidebar', 'status(show_cell_in_sidebar())')
```

**Comment by frosencrantz** [comment]
@radostyle this looks very useful.   I have to try it first, but it looks like something I would use.  

Question, why is only cursorDown defined, don't you also need cursorUp?

**Comment by radostyle** [comment]
cursorDown() appears to be used for moving up a row or down a row depending
on whether the supplied parameter is positive or negative.  Changing the
sidebar when moving between columns also would be the intuitive thing to
do, but I didn't implement that because I only care about one column.  I'm
not sure if it is the best way to implement, but it seems to be an
expected implementation based on the documentation.

**Comment by saulpw** [comment]
Hey @radostyle, this is a clever use of the sidebar!  I got to thinking about it, and I wound up adding `options.disp_sidebar_fmt` to make it easier to configure stuff like this.  Ultimately your command could be something like:

```
Sheet.addCommand('KEY_F(2)', 'sidebar-cell', 'options.disp_sidebar_fmt = "{sheet.cursorDisplay}" if not options.disp_sidebar_fmt else ""')
```

and maybe at some point it would cycle through a list of options instead of just on/off.

Thanks for putting this together and mentioning it here!

**Comment by radostyle** [comment]
Thanks @saulpw, I tried it out and it works great!  It fixes an issue with my plugin where searches would not change the sidebar content.  I guess I needed to intercept all changes to the `self.cursorRowIndex` but I couldn't figure out how to do that with the Extensible api.  I like that the sidebr view only takes as much room as it needs and not more.

Thanks for such a useful and elegant piece of software.

**Comment by frosencrantz** [comment]
Hi @saulpw I've tried using the suggestion from https://github.com/saulpw/visidata/issues/1685#issuecomment-1399842221 can you suggest how to make it sticky to the column I hit the F2 on?  So as I move the cursor to new rows the value changes, but as I move the cursor to a different column the sidebar value remains connected to the original column.

I really like the sidebar for show big values, and typically for me that is a specific column.

**Comment by saulpw** [comment]
Try this:

```
@Sheet.property
def cursorDisplayStickyCol(sheet):
    return sheet.stickyCol.getDisplayValue(sheet.cursorRow) + "\n\n"

Sheet.addCommand('KEY_F(2)', 'sidebar-sticky-col', 'sheet.stickyCol = cursorCol; options.disp_sidebar_fmt = "{sheet.cursorDisplayStickyCol}" if not options.disp_sidebar_fmt else ""')
```

The trick with these is usually to make a python property that returns the value you want, then make a command that gets that property to work :)
