### ISSUE TITLE
Feature request: Support tail

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1686]
This feature request is related to #1683. I want to be able to tail CSV files. I've got a running experiment that's writing to a CSV file, one row every few minutes. I want to open this CSV file with VisiData, and after setting up the columns to be the right type, I want new rows to automatically appear in the sheet as they are written to the file. i.e. I want to keep the sheet open, and once in a few minutes, see another row pop on the screen.

**Comment by saulpw** [comment]
Have you tried `tail -f foo.csv | vd` and then just letting it run?

**Comment by cool-RR** [comment]
That works well, thank you. But I use VisiData to explore folders and then open CSV files from there. Is there a way to make this work when opening a file from a `DirSheet`? Or better yet, maybe there should be a command when a CSV is already open to switch to tail mode?

**Comment by saulpw** [comment]
So, pulling together your various asks, it sounds like the full feature request is:

- notice whenever a source file is updated
- progressively add new rows
- don't update the cursor
- don't change the columns

Some questions:
- do we need the row order to be stable if the user changes it (i.e by sorting)? (can we make a `reload-rows-every` which does a full `reload-rows` as mentioned in #1683)
- do we want the rows to continue to flow into derived sheets (like a Frequency Sheet of the source sheet)?

**Comment by cool-RR** [comment]
> So, pulling together your various asks, it sounds like the full feature request is:
> 
> * notice whenever a source file is updated
> * progressively add new rows
> * don't update the cursor
> * don't change the columns

Exactly. And we should be able to toggle any CSV file between "static" and "tail" modes.

Another useful toggle would be whether we want the cursor to always go to the last row whenever a new row is produced, which is useful sometimes, but that's minor enough to ignore for now.

> 
> Some questions:
> 
> * do we need the row order to be stable if the user changes it (i.e by sorting)? (can we make a `reload-rows-every` which does a full `reload-rows` as mentioned in [Feature request: Add command `reload-rows` #1683](https://github.com/saulpw/visidata/issues/1683))

Good question. We could support sorted insertion of new rows in case there's sorting on the sheet, and it might be useful, but I think that 95% of the use cases for tailing would not involve sorting, and I don't want that to be a blocker. So what I'd do is just not support tailing if the sheet has sorting, and if people ask for that feature, open it as a separate feature request. 

Is there any other row order changing that could cause problems besides sorting?

I understand that the `reload-rows-every` command you're suggesting would just do `reload-rows` in a loop. I'm not sure that's right, because I imagine `reload-rows` to read the file from the beginning to the end and repopulate the sheet, while in tail we only read from the last position in the file that we were in. If you're going that route, you might want to give `reload-rows` an argument that tells it whether to read from the start or from the last position. But I'm not sure you'd even want these two functionalities in the same command, this might be better as a separate command.

Also, since your command is called `reload-rows-every` I'm assuming you're thinking of polling the file. This isn't as nice as doing a watch on the file like `tail` does, but it's an okay compromise.

> * do we want the rows to continue to flow into derived sheets (like a Frequency Sheet of the source sheet)?

Oh, I didn't consider it. I don't know how they're implemented. I can break this question into two questions: (1) Do I want any new derived sheet that I open to be updated with new rows and (2) Do I want any derived sheet that was opened from before to be updated with new rows. The answer to (1) is definitely yes. The answer to (2) is yes, but it's not critical if it's too difficult.

**Comment by saulpw** [comment]
Okay, so I added a `reload-modified` command that spawns a thread to reload the sheet whenever the source file is modified.  A proper tail a good idea, particularly if it would trickle down into derived sheets, but that's more architectural work than it's worth right now.  I'm guessing `reload-modified` is sufficient for most use cases.

**Comment by cool-RR** [comment]
Awesome, thank you!

Same question as the other thread: I'm not on the latest version. Is that something I can copy-paste into my .visidatarc or does it depend on new code that doesn't exist in 2.11.1?

**Comment by saulpw** [comment]
It's all very self-contained, so you should be able to copy-paste it: https://github.com/saulpw/visidata/commit/f83943327d51031c27991f974b2d73d9b4e89e36

**Comment by cool-RR** [comment]
I tried `reload-modified` now. It resets the column typing and folding, which is what I was looking to avoid. I want the sheet to look exactly the same besides the new rows.

**Comment by saulpw** [comment]
Then change the `reload` to `reload_rows`.

**Comment by cool-RR** [comment]
Works, thank you!
