### ISSUE TITLE
[themes] Default theme missing

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1691]
**Small description**
When setting theme to the default from the menu, it says: `no "" theme available`

**Expected result**
Theme reset to the original theme

**Actual result with screenshot**
https://asciinema.org/a/b9uPtpGWEjS85XymvYw2BbEnv

No stack trace.

**Steps to reproduce with sample data and a .vd**
Use menu:  "View"/"Set theme"/"default"

**Additional context**
Please include the version of VisiData. Latest version of develop.

**Comment by saulpw** [comment]
Thanks, @frosencrantz!   Should be fixed now.
