### ISSUE TITLE
JSONL sheet guesses int for float

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1698]
I'm loading this JSONL sheet: https://www.dropbox.com/s/n082mwbv7j85cee/progress.jsonl?dl=0

It guesses the `flaunt.hawkiness.4` column to be an int, even though it's a float. I think it guesses that because one of the values is an int.

**Comment by yphillip** [comment]
Hi @cool-RR , would you be able to provide a screenshot where you see `flaunt.hawkiness.4` is being guessed as an int? Is there a specific line in your data where this can be seen?

I looked at a few lines manually, and they all show up as floats, even ones where `flaunt.hawkiness.4` is 0.0, like in line 75 (generation = 75).

![image](https://github.com/saulpw/visidata/assets/7872350/549d7f56-f912-44c3-b11f-4c7c014b6717)

I'm using saul.pw/VisiData v2.11 and python 3.11.

**Comment by cool-RR** [comment]
I can't reproduce this now. I'm sure this happened, but it's been 6 months since I reported it and I don't remember. Thanks anyway.
