### ISSUE TITLE
Feature request: Allow specifying ticks in GraphSheet

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1699]
I want to be able to specify that a graph sheet will always show the ticks 0 and 1. Right now I want to set the y axis to `-0.2 1.2` so I could see the data between 0 and 1 comfortably, but when I do that, there are no ticks for 0 and 1 because they happen to not be where the automatically-placed ticks are.

**Comment by midichef** [comment]
Hi @cool-RR 
Add this to your `.visidatarc` and it should do what you want.

```
class ExtraTicksGraphSheet(GraphSheet):
    def createLabels(self):
        super().createLabels()
        try:
            for x_tick in graph_extra_x_ticks:
                x_frac = (x_tick - self.visibleBox.xmin) / self.visibleBox.w
                if x_frac > 0 or x_frac < 1:
                    self.add_x_axis_label(x_frac)
        except NameError:
            pass
        try:
            for y_tick in graph_extra_y_ticks:
                y_frac = (y_tick - self.visibleBox.ymin) / self.visibleBox.h
                if y_frac > 0 or y_frac < 1:
                    self.add_y_axis_label(y_frac)
        except NameError:
            pass
# Put the extra values you want to appear on the x axis in a list here.
graph_extra_x_ticks = []
# Put the extra values you want to appear on the y axis in a list here.
graph_extra_y_ticks = [0, 1]

Sheet.addCommand('.', 'plot-column', 'vd.push(ExtraTicksGraphSheet(sheet.name, "graph", source=sheet, sourceRows=rows, xcols=keyCols, ycols=numericCols([cursorCol])))', 'plot current numeric column vs key columns; numeric key column is used for x-axis, while categorical key columns determine color')
Sheet.addCommand('g.', 'plot-numerics', 'vd.push(ExtraTicksGraphSheet(sheet.name, "graph", source=sheet, sourceRows=rows, xcols=keyCols, ycols=numericCols(nonKeyVisibleCols)))', 'plot a graph of all visible numeric columns vs key columns')
```
But be aware, if you add ticks to the x-axis, when two x labels get too close together and their text overlaps, both labels will disappear. I'll look into what is causing that at some point.

**Comment by saulpw** [comment]
> But be aware, if you add ticks to the x-axis, when two x labels get too close together and their text overlaps, both labels will disappear. I'll look into what is causing that at some point.

That's deliberate, in `Canvas.draw._mark_overlap_text`.  Drawing overlapping labels makes both of them unreadable, and possibly makes nearby labels confusing too (esp on a .shp map).  We could do a bit better and draw only one of them, but it was hard to choose which one.  Feel free to improve it as long as it still looks reasonably good :)

**Comment by midichef** [comment]
Ah okay. I'll leave it as is then.

**Comment by cool-RR** [comment]
@midichef : I tried this code now and it works well. Thank you.
