### ISSUE TITLE
Feature request: Don't show graph selection box until prompted

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1700]
I think that the graph selection box is a nice feature, but most use cases for graphs don't require it. It's eye sore. I like to see pretty graphs, and I don't like to see that selection box there. I know I could push it sideways, but I'd hate to do that every time. Maybe it can only appear after the first time the user tries to move it? 

And also, is there a programmatic way to make it disappear?

**Comment by anjakefala** [comment]
Writing as a fellow user, not as a developer.

> Maybe it can only appear after the first time the user tries to move it?

I am a -2 for this suggestion, actually! It will add more steps to learning about the existence of the feature, and some may never learn about it. Also of note is that the cursor is essential for DarkDraw, which uses **CanvasSheet**. I personally feel more comfortable with options that allow @cool-RR (and others) to opt out of seeing it, than removing it by default for everyone.

**Comment by anjakefala** [comment]
Programmatically, `Canvas.cursorBox` is the attribute you would be playing with! You could try playing with this function https://github.com/saulpw/visidata/blob/dd98cafabfc4c966ffc51447bbade08698af5e5e/visidata/canvas.py#L382

**Comment by saulpw** [comment]
Yeah, I'm not sure about this either.   You should be able to remove by setting the `.xmin`/`.ymin` attributes outside the bounds of the `canvasBox`.

**Comment by cool-RR** [comment]
Cool, I'll add it to my autotune. Thank you.

**Comment by cool-RR** [comment]
Are you sure that `.xmin` and `.ymin` determine that block? Because I set them to -100 and it didn't move that selection block.

**Comment by saulpw** [comment]
Hm, I just used this command:

```
GraphSheet.addCommand('', 'hide-cursor', 'cursorBox.ymin=-1000')
```

and it worked fine.  Maybe something else went wrong?

**Comment by frosencrantz** [comment]
@cool-RR can you share your autotune?  It sounds like it would be interesting.

**Comment by cool-RR** [comment]
Sure. This is absolutely customized to me and it's a constant work-in-progress. Use at your own risk: https://gist.github.com/cool-RR/0a2222468c5673b4dcb6c772e110620c
