### ISSUE TITLE
Feature request: Support column groups on CSV sheets

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1702]
From #1688 :

> If you can change the column names, one idea I've had is to collapse columns with a common subprefix (e.g foo.a and foo.b) into one unexpanded foo column group that would act just like the above. This would require some changes in the csv loader but wouldn't be too big a deal.

**Comment by frosencrantz** [comment]
I like this suggestion.   I sometimes generate data that has more columns than I need, and it would be very useful to hide groups of columns easily, but having them easily accessible when I wanted them 

One thing that seems like it would be useful if this format is also compatible with `mlr` as mentioned in https://github.com/saulpw/visidata/issues/1457

**Comment by cool-RR** [comment]
@frosencrantz You asked in another thread what's happening with this feature request. I guess it's not important enough for anyone to implement. I moved from CSV files to JSONL files so I could use column groups.

**Comment by saulpw** [comment]
How about a command on the ColumnsSheet that combines selected columns into a single column that can then be expanded/contracted?  This should be fairly straightforward to implement.

**Comment by cool-RR** [comment]
Could be useful, but doesn't help me much here. My experiments are generating sheets with hundreds of columns divided into a hierarchy of groups. I'm not doing that manually.

**Comment by saulpw** [comment]
I went ahead and implemented `contract-source-cols`, bound to `)` on the columns sheet, which combines the selected columns into a single column, named after their longest common prefix.  If someone wants an automatic `foo.bar.baz` column grouper I would listen to pleas and bargains.
