### ISSUE TITLE
Feature request: Python shell

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1703]
I just thought of this idea, and it could be so useful that I'm surprised I didn't think about it before. I thought about it because it would help in developing my scripts, but it could actually be useful for the actual data exploration too.

I want to be able to open an IPython shell on any sheet, and then have all the rows and columns in that sheet available for me to run commands on.

**Comment by ajkerrigan** [comment]
Hey @cool-RR , I find this sort of thing super helpful too. I've done it with [this plugin](https://github.com/ajkerrigan/visidata-plugins/blob/main/plugins/vdrepl.py) and a keybinding in my `.visidatarc`:

```python
BaseSheet.bindkey("`", "open-repl")
```

It was more of a crude "hack for me" thing than anything else (it bakes in my own expectations around ptipython for example), but in case it helps your goal of dropping into an IPython shell... have fun.

**Comment by cool-RR** [comment]
@ajkerrigan This is brilliant, thank you! I added it to my `.visidatarc`.

I do notice that it messes up the screen on my Windows shell (Conemu). I guess I'll have to live with that.
