### ISSUE TITLE
Feature request: Flexible loading of text files

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1707]
When I run experiments, some of the the output is in a huge text file called `output`. When I browse my experiment directories with VisiData, and I open that file, it takes around 40 seconds to load. This is partially because the file is huge, and partially because it's on a network drive.

I often want to see the text at the bottom of the file, because that's the most recent output. But that's only ready once the file has completely loaded.

It would be cool if VisiData would open the file in a flexible way, i.e. I do want it to load as much into memory as possible, but if I scroll to the bottom, I want it to first load the bottom so I could see it immediately instead of waiting for the entire thing to be done.

**Comment by saulpw** [comment]
Interesting idea, @cool-RR !  In general we're heading in more of a 'streaming' direction, but maybe a negative value for `options.skip` could `fseek()` to ~N lines before the end of the file before starting to read.  Might be handy for large files over HTTP as well.

Kondo'ed for now.
