### ISSUE TITLE
[open-cell-file] open file from zip file in editor with `zo`

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1708]
**Small description**
Unable to open file from zip file in editor with `zo` `open-cell-file`

**Expected result**
The file from the zip would be saved to a temporary file, and the editor opened on it.
VisiData is able to open the file as a sheet, but not in the editor.

**Actual result with screenshot**
https://asciinema.org/a/3c8CmL81WGEV2R10ihIO9PR45

**Steps to reproduce with sample data and a .vd**
Open a zip file, and try to use `zo` on one of the files in the archive, and it will say the file does not exist.

```
vd file.zip
```
**Additional context**
Please include the version of VisiData. Latest version of VisiData.

I'm classifying as a bug.  I can see how this could be considered a feature request.

**Comment by saulpw** [comment]
I added a custom `sysopen-row` command on ZipSheet, bound to `Ctrl+O`.  I think this is closer to the intent than the suggested `open-cell-file` (which would open the cell in VisiData).

`zo` does something unexpected (tries to open the cell value as a file in the current directory), and maybe should be disabled or reworked.
