### ISSUE TITLE
Configure default filetype when reading from stdin

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#1710]
I frequently get CSV files from a vendor which have no header. The vendor ships the header file separately. So I end up frequently concatenating the header file with the different body files and piping them to Visidata for inspection.

```
$ cat header.csv 20230130.csv | vd -f csv
$ cat header.csv 20230123.csv  20230116.csv | vd -f csv
```

That works. But the majority of my Visidata use is still with normal files that include headers and have proper extensions, so I'm not in the habit of adding `-f csv`. I often forget to add it it when piping these headerless files into Visidata.

Ideally, it would be great if Visidata could look at the data being piped in via stdin and make a guess about the filetype. But I understand that could be fraught with peril, so a simpler solution that would still address my forgetfulness would be if I could just configure a default filetype of CSV which Visidata would always use when reading from stdin (unless I explicitly overwrite it with `-f`).

**Comment by saulpw** [comment]
Okay, so I just made it so it will check for filetype by pathname, if it's not otherwise overridden.  Now you can put this in your visidatarc:

```
options.set('filetype', 'csv', '-')
```

and then it will open `-` as csv by default.
