### ISSUE TITLE
BOM is part of first column name?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#1711]
I had two CSV files I was trying to append to one another, hoping column names would not be duplicated. However, the result had two `Date` columns; I did eventually notice one had a space before it. Turns out one file had BOM and was included in column name.

<img width="59" alt="SCR-20230130-qdi" src="https://user-images.githubusercontent.com/596814/215625039-4ccf7cea-c5e5-4488-b36b-6360caa4696d.png">

![SCR-20230130-qcz](https://user-images.githubusercontent.com/596814/215625050-08bbc4a8-5363-4719-be6a-9fef89275ef8.png)

Is this related to #200 ?

**Comment by reagle** [comment]
saul.pw/VisiData v2.10.2 on macOS 13.1 22C65 arm64

**Comment by reagle** [comment]
Here are two test files, sheet2.csv is encoded as UTF-8-BOM, which means the the `b` column is not properly appended.
[sheet1.csv](https://github.com/saulpw/visidata/files/10551246/sheet1.csv)
[sheet2.csv](https://github.com/saulpw/visidata/files/10551247/sheet2.csv)

**Comment by saulpw** [comment]
I changed the default for `options.encoding` to `utf-8-sig` which should detect the BOM and skip it.  Thanks for the writeup and the test files, @reagle!
