### ISSUE TITLE
Replay of command log aborts erratically

### ISSUE THREAD

**Issue by tdussa** [saulpw/visidata#1714]
**Small description**

When replaying a (probably fairly long) command log file against a (probably fairly extensive) data set, VisiData encourters errors sporadically and non-reproducably, triggering the replay to be aborted.  Interestingly, this does not seem to be a problem if the same command log file is run in batch mode (with the `-b` command-line switch).

Every once in a while, the replay _does_ run through completely.

**Expected result**

A reliable and reproducable replay of the command log.

**Actual result with screenshot**

The actual errors vary from call to call, but are generally of the nature `no sheet named XXX` or `no "YYY" column`.  A screenshot and stack trace of an example run are attached.

**Steps to reproduce with sample data and a .vd**

See attached files (I had to zip up the command log file because `.vd` files are not accepted for upload); replaying the command log with
```
vd -p Sample_command_log.vd
```
is unreliable, while replaying it with
```
vd -b -p Sample_command_log.vd -o Sample_data.tsv
```
works just fine.

**Additional context**

Using VisiData version 2.11 at the moment, though this problem has been around ever since I started using VisiData about a year ago.  Also, this problem exists on all of the machines I have tried so far (four different sets of hardware).

[Sample_command_log.vd.zip](https://github.com/saulpw/visidata/files/10568236/Sample_command_log.vd.zip)
[Sample_data.csv](https://github.com/saulpw/visidata/files/10568188/Sample_data.csv)
[Sample_run_-_Screenshot](https://user-images.githubusercontent.com/6197517/216308497-2b5ebce6-6077-4e9d-9b8b-bda445ed2a78.png)
[Sample_run_-_Stack_trace.txt](https://github.com/saulpw/visidata/files/10568197/Sample_run_-_Stack_trace.txt)

**Comment by daviewales** [comment]
I experienced an issue where playing a command log which simply attempts to open the following file would crash immediately, even though I can open it fine under normal circumstances:

https://github.com/saulpw/visidata/blob/develop/sample_data/y77d-th95.json.gz

Command log:
[y77d-th95.vdj.zip](https://github.com/saulpw/visidata/files/10741915/y77d-th95.vdj.zip)

**Comment by saulpw** [comment]
Thanks a lot for these reports, @tdussa and @daviewales.  Every bit of information is useful.  If this is easily reproducible for you, I would love it if you could use `git bisect` and find the commit that seems to have caused the issue.  It sounds like a race condition, where the main replay thread is moving on the next command while a thread from the previous command is still running, and it's responsible for putting the sheet on the sheet stack.  But there should be a `vd.sync()` after every command, that waits for all threads to complete.

**Comment by daviewales** [comment]
And... today it's not reproducing.

**Comment by tdussa** [comment]
I've done some bisecting, and I haven't found a commit that will work cleanly.  Commit e722feff9284076a62108ce4144d262a3675458c already shows this erratic behavior, and anything before that throws Python errors right at the start on my machine.

**Comment by tdussa** [comment]
On a potentially related side note, I have noticed something that I cannot quite explain, and it _might_ have something to do with this, but I might also completely misunderstand this.

When I run a replay, at the bottom right-hand corner, there is a running counter of what I interpret as the currently-executed command, and what I interpret as the total number of commands to be replayed.  Something like, for instance, `915/3925`.

Thing is, if I am interpreting these numbers correctly, I would assume the second number to depend only on the VD file that I replay, but it _changes_ with almost every replay run (and the variation is, in fact, considerable -- for the above sample VD file, I see numbers almost as low as 2000 but also numbers approaching 4000).  Seems to be fairly random to me.

**Comment by tdussa** [comment]
Oh, one more observation: Even if a run passes successfully, very occasionally some commands seem to have been omitted from the replay, and as far as I can tell, those are always `hide-col` commands.  So maybe there's something going on here that makes `visidata` drop commands from the VD file at random (or maybe even not so randomly), and the replay finishes only if the commands that were dropped happened not to be critical for whatever came after them?

**Comment by saulpw** [comment]
Thanks, @tdussa!  This is very helpful, it means this issue has been around for awhile now.

Are you really running a replay with thousands of commands?  That gives me a bit of a clue.

One thing we could try, is offering an option to make the interactive `replay` into `replay_sync` like in batch mode (`main.py:~347`).  This means that you wouldn't see the display, nor be able to interact with it (including pausing/canceling replay), until it's finished the replay.  But it should be faster to replay this way anyway, and if you have many commands maybe you just need it to get to the end quickly.  Would this be an acceptable solution?

**Comment by tdussa** [comment]
> Thanks, @tdussa! This is very helpful, it means this issue has been around for awhile now.

Indeed.

> Are you really running a replay with thousands of commands? That gives me a bit of a clue.

I am indeed. :)

> One thing we could try, is offering an option to make the interactive `replay` into `replay_sync` like in batch mode (`main.py:~347`). This means that you wouldn't see the display, nor be able to interact with it (including pausing/canceling replay), until it's finished the replay. But it should be faster to replay this way anyway, and if you have many commands maybe you just need it to get to the end quickly. Would this be an acceptable solution?

That would be totally acceptable for my concrete situation.  In fact, I am way more interested in having the replay done as quickly as possible than in having the possibility for manual interaction, which I have no use for (in this particular case).  So a separate "replay mode" would be excellent from my point of view. :)

Thanks a lot for the quick reply!

**Comment by anjakefala** [comment]
Hi @tdussa! @saulpw implemented the discussed changes.

There is now a flag `-i` which you can add to use interactive mode. `vd -p foo.vd -b -i` will run the replay in synced batch mode, and then load the final sheet to be interacted with. 

I am going to close this issue as "bug fixed", but please feel free to re-open if you are still running into issues!
