### ISSUE TITLE
Feature request: Add a `DirSheet` command to expand all folders

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1715]
I want a `DirSheet` command that when I press it, all first-level folders in the current folder will be scanned for files, and all of these files will appear as new rows below the folder's row. (This will all happen in a new sheet, obviously.)

Since each row has a `directory` column, the new files will be visibly different than the files in the root folder.

**Comment by saulpw** [comment]
Is this like the `dir_recurse` option, but only for a single level?   (What if `dir_recurse` was an int instead of a bool, to indicate number of levels expanded, with `-1` or some sentinel meaning 'all levels'?)

**Comment by cool-RR** [comment]
I didn't know about this option. How is one supposed to use it to view a folder recursively? (I've only set options in `.visidatarc` so far)

**Comment by saulpw** [comment]
`vd -r .`, for example (`-r` is an alias for `--dir-recurse`).  Or go to the options sheet, change the option, go back to the DirSheet, and Ctrl+R to reload.

**Comment by cool-RR** [comment]
Oh awesome. So let's rephrase this FR:

* `dir_recurse` will remain a `bool`.
* A new option `dir_recurse_depth` will be added, with a default value of `float('inf')`.
* I'll be able to write a command that opens a new sheet with `dir_recurse=True` and `dir_recurse_depth=1`.

Is the code for this `vd.push(DirSheet(sheet.source, dir_recurse=True, dir_recurse_depth=1)`?

**Comment by saulpw** [comment]
I would prefer to change `dir_recurse` to an int, since `dir_recurse_depth` would be useless when `dir_recurse` is False, anyway.  Then `-r` would be equivalent to `--dir-recurse=10000`.  If you then wanted a command to expand directories one level on the current sheet, it would be `sheet.options.dir_recurse=1; sheet.reload()`.  Maybe you would want `sheet.options.dir_recurse += 1` so you could incrementally expand levels.

**Comment by cool-RR** [comment]
Sounds good.

**Comment by saulpw** [comment]
Renamed `dir_recurse` to `dir_depth`.  `-r` now means `--dir-depth=100000`.

Here's that command you wanted:

```DirSheet.addCommand('', 'expand-dir-depth', 'sheet.options.dir_depth += 1; reload()')```

**Comment by cool-RR** [comment]
Thank you!

**Comment by cool-RR** [comment]
I'm trying this now and it works, but I also want to show the `directory` column automatically so I'll know which file belongs in which subfolder.

For some reason this doesn't work:

```
DirSheet.addCommand(
    '',
    'dir-depth-expand',
    (
        'sheet.options.dir_depth += 1; '
        'unhide_cols(columns, visibleRows); '
        'reload()'
    )
)
```

When you run it, it doesn't unhide any columns. (I previously had `(c for c in columns if c.name == "directory")` instead of `columns` but since that didn't work either, I just put `columns` there for debugging.)

**Comment by saulpw** [comment]
The directory column is always shown in DirSheet on my setup.  Are you hiding it in your .visidatarc somehow?

**Comment by cool-RR** [comment]
Ah yeah, I forgot about that. Thanks.

**Comment by cool-RR** [comment]
I'm a little confused here. I've got these lines in my `.visidatarc`:

```python
(dir_sheet_directory_column,) = (column for column in DirSheet.columns
                                 if column.name == 'directory')
dir_sheet_directory_column.width = 0
```

I'd like to keep that because I usually don't want to see the directory.

But shouldn't `unhide_cols` automatically set the width to something reasonable? I also tried this: 

```python
DirSheet.addCommand(
    '',
    'dir-depth-expand',
    (
        'sheet.options.dir_depth += 1; '
        # 'unhide_cols(tuple(c for c in columns if c.name == "directory"), visibleRows); '
        '[setattr(column, "width", 7) for column in columns]; '
        'unhide_cols(columns, visibleRows); '
        'reload(); '
        'autotune()'
    )
)
```

**Comment by saulpw** [comment]
You want `reload_rows()`. Or you do the reload before the unhiding.

Also you can use `sheet.column("directory")` to get that column (though not on the class). And if you want to do all columns you can also use `Fanout(sheet.columns).width = 7`.

**Comment by cool-RR** [comment]
Works now, thank you. This is my code:

```
DirSheet.addCommand(
    '',
    'dir-depth-expand',
    (
        'sheet.options.dir_depth += 1; '
        'unhide_cols((sheet.column("directory"),), visibleRows); '
        'reload_rows()'
    )
)
DirSheet.addCommand(
    '',
    'dir-depth-reset',
    'sheet.options.dir_depth = 0; hide_col(sheet.column("directory")); reload_rows()'
)
```

I couldn't get autotune to work automatically after that so I have to invoke it manually, but I can live with that.
