### ISSUE TITLE
[xlsx]  Add colorizers for xlsx files (RGB colors to 256 colors)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1718]
In https://github.com/saulpw/visidata/pull/1098 @hoclun-rigsep added extra columns including colors for xlsx sheets. 🎉 

It would be really helpful if VisiData could also make these colors visible via the colorizers VisiData provides.

I had suggested this on that thread in: https://github.com/saulpw/visidata/pull/1098#issuecomment-962657645

Will McGugan recently fixed an issue in Rich related to converting RGB to 256 colors that has information that might be useful for this wish.  

See details here:
- Release Notes: https://github.com/Textualize/rich/releases/tag/v13.3.1 
- PR: https://github.com/Textualize/rich/pull/2785
- Helpful write up: https://fathy.fr/carbonyl#color

I couldn't find my original request since it was hidden in the closed PR, so I've made this a wishlist item to help make it easier to find.

**Comment by daviewales** [comment]
I got curious about this and started playing with an xlsx file and the `--xlsx_meta_columns=True` option from #1098.
Interestingly, if you use Excel's 'theme colours' you don't get real colour values in the file. You get a small integer such as 7, 8, or 9. However, if you use the non-theme colours, you get real colour values.

<img width="195" alt="Screen Shot 2023-02-15 at 9 03 59 pm" src="https://user-images.githubusercontent.com/2499066/218997393-b5560f2b-350e-4a8e-aaab-f382420d2225.png">

[colours.xlsx](https://github.com/saulpw/visidata/files/10741778/colours.xlsx)

**Comment by saulpw** [comment]
Thanks @frosencrantz and @daviewales for doing the research and collecting it all here.  You managed to make it easy enough to nerd-snipe me :)  So now it seems to work, at least for the colours.xlsx file above.

This colorizing code is about 100 lines, which doubled the size of the xlsx loader.  I would never have considered this worth it if you hadn't been persistent about it.

FWIW, this answer from StackOverflow was extremely helpful in converting theme colors (I mostly just copied and adapted the code): https://stackoverflow.com/a/65426130

**Comment by frosencrantz** [comment]
Thanks @saulpw!  This is exciting and useful.

It looks like the code might be broken:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 196, in _colorize
    r = colorizer.func(self, col, row, value)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 44, in <lambda>
    CellColorizer(5, None, lambda s,c,r,v: c and r and s.colorize_xlsx_cell(c,r))
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 206, in colorize_xlsx_cell
    fg = sheet.xlsx_color_to_xterm256(fg)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 222, in xlsx_color_to_xterm256
    return sheet.theme_and_tint_to_rgb(color.value, color.tint)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 230, in theme_and_tint_to_rgb
    h, l, s = rgb_to_ms_hls(rgb)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 269, in rgb_to_ms_hls
    h, l, s = rgb_to_hls(red, green, blue)
NameError: name 'rgb_to_hls' is not defined
```

https://asciinema.org/a/LULezlK0yvLpO9NxA5adu4Dvr

**Comment by saulpw** [comment]
Sorry, missed an import.  If you have more issues with this, please include a .xlsx (the colours.xlsx from above didn't exhibit the issue you saw).

**Comment by frosencrantz** [comment]
It looks like you fixed one more error I was seeing. But there are still two different traces I'm seeing from sample_data:

https://asciinema.org/a/8co2PmYgo8CEUBvcUi8s3YG3t

from `sample_data/empty_cell.xlsx`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 196, in _colorize
    r = colorizer.func(self, col, row, value)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 45, in <lambda>
    CellColorizer(5, None, lambda s,c,r,v: c and r and s.colorize_xlsx_cell(c,r))
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 208, in colorize_xlsx_cell
    fg = getattrdeep(row, col.column_letter+'.font.color')
  File "/usr/lib/python3.9/site-packages/visidata/utils.py", line 110, in getattrdeep
    return getter(obj, attrs[-1])
AttributeError: 'NoneType' object has no attribute 'color'
```

From the `sample_data/sample-sales-reps.xlsx`
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 196, in _colorize
    r = colorizer.func(self, col, row, value)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 45, in <lambda>
    CellColorizer(5, None, lambda s,c,r,v: c and r and s.colorize_xlsx_cell(c,r))
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 210, in colorize_xlsx_cell
    fg = sheet.xlsx_color_to_xterm256(fg)
  File "/usr/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 220, in xlsx_color_to_xterm256
    if color.type == 'rgb':
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by saulpw** [comment]
Thanks @frosencrantz!  Fixed these :)

**Comment by daviewales** [comment]
That is very very cool! Thank you!

**Comment by krackout** [comment]
Any way to disable colorizer? I recently updated from 2.11 to 3.0.2 and now xlsx files open with fill colours. Actually a motive for me to open them using visidata was to avoid the fill colours some colleagues use :)

I've tried ` --xlsx-meta-columns=False` parametre, but unfortunately colours are still on. Also switch theme to asciimono, yet xlsx still load with colours.
