### ISSUE TITLE
[left sidebar] Sheet list sidebar doesn't go away

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1736]
**Small description**
Sheet list sidebar doesn't go away, and hides data in bottom part of screen

**Expected result**
Sidebar goes away or doesn't block data.  The regular sidebar does disappear after I start to use keyboard commands.

**Actual result with screenshot**
https://asciinema.org/a/ie1wMYMHkXixZW6zyXS945x97
https://asciinema.org/a/ccuPKQVCClC44YVCqK0AghB90

**Steps to reproduce with sample data and a .vd**
Go to FreqTableSheet and see sheet names listed in a stack on the left of the screen.

**Additional context**
Please include the version of VisiData. Latest develop branch

@saulpw not sure if you want this feedback here or on the discussion thread.  I like that this is trying to give more context.
I would personally be ok with a second status line showing these values with some sort of separator.
Also, notice in the second [screnshot](https://asciinema.org/a/ccuPKQVCClC44YVCqK0AghB90) that the sheet name by diving on a row from the FreqTableSheet has a bunch of undescores between the names `sample_data_s_a_m_p_l_e___d_a_t_a_/_`.  And try doing quiting that sheet, and diving into the rows again.

**Comment by saulpw** [comment]
This is fine, I appreciate the feedback. I don't entirely like the new sheet panel myself, especially since the other experiment of making the sheets sheet a list of leaves (instead of the entire path to get there) didn't work out as well as I'd hope.  So I've been sitting with it, but it may just be reverted here soon, in favor of the previous single-line sheetname  (which is more workable now that status messages are in the sidebar).

**Comment by anjakefala** [comment]
I vote in favour of reverting it!

**Comment by frosencrantz** [comment]
The sheets panel has a couple bugs that make it not useful as is:
1) It covers the current sheet name.
2) It doesn't disappear automatically, and there is no way to make it disappear/appear.

I'm ok with an extra  status line that lists the ancestor sheets separated by spaces or some other useful separator.

**Comment by saulpw** [comment]
Maybe it can come up as part of a HUD with `Space` (which I'd like to develop into a general command search).

**Comment by frosencrantz** [comment]
HUD.  I would like to see that. 👀 

@saulpw you seem to have completely removed the name of the current sheet.  The status bar does not list the current sheet, which it did before.  This is less useful than before.

**Comment by saulpw** [comment]
Ah, so it is, my apologies.  Will be fixed shortly.

(It's fixable yourself though, in the meantime: just add `"{sheet.name}"` to `options.disp_status_fmt`.)
