### ISSUE TITLE
[guard-sheet] Command line option to guard the first sheet

### ISSUE THREAD

**Issue by wendrul** [saulpw/visidata#1737]
I'm not entirely sure if this is already implemented some way or another, but I believe it wouldn't be a big change if it isn't.

I would like to have a command line option (maybe `--guard-root-sheet`) that would have the same effect as:
1) opening visidata 
2) pressing Space 
3) executing the command `guard-sheet`

For context, I'm using visidata a lot, and decided to make a `.desktop` file to be able to open csv files with vd when double clicking them. This opens a terminal with vd and the sheet. However, as soon as I quit the root sheet, the terminal closes and I have to double click to open the file again. I would like to prevent this by automatically executing guard-sheet as soon as vd is opened.

I've tried to make it work but the command `--quit-guard` is not exactly what I want, as I want the sheet guarded even when there are no modifications. I also tried to play with .visidatarc, but I only want this behaviour for the files I double-click, meaning the ones executed by the `.desktop`. If this is already possible I apologize for the feature request.

I am open to contributing to add this if there is a need, so please let me know your opinion.

Also unrelated but maybe it's worth considering making this .desktop a default feature, it is really handy!

**Comment by saulpw** [comment]
Hey @wendrul, thanks for the request.  There's actually a special case for the `quitguard` option (note, no hyphen in there), so that if it's set specifically on a sheet (i.e. not globally), then it asks for confirmation before quitting, even if the sheet has not been modified.  So running `vd --quitguard foo.csv` and then pressing `q` will ask for confirmation.

As for the `.desktop`, can you post the contents of your file here?

**Comment by wendrul** [comment]
Oh my bad, I was using it with the hyphen so that's why! It does work indeed! Thank you so much this is exactly how I wanted it to behave.

As for my .desktop file, it really is only a simple hack that makes it work on my system. 

Here is my `~/local/share/applications/visidata.desktop`:

```.desktop
[Desktop Entry]
Type=Application
Terminal=true
Name=VisiData
Icon=utilities-terminal
Exec=bash -i -c '/home/edethoma/anaconda3/bin/visidata --quitguard %f'
Categories=Application;
```

As far as my limited understanding goes, this should not use aboslute paths but be placed together with the install files and binaries. It should also be somewhere pointed to by the variable `$XDG_DATA_DIRS`. This works for me so I'm using it like this
