### ISSUE TITLE
Feature request: Show nicer error messages instead of ModuleNotFoundError

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1739]
As I'm working on the VisiData talk, I'm trying to open different file formats with VisiData. Some of these require modules such as `psycopg2` or `xlrd`. When you don't have these modules, you get a message like `ModuleNotFoundError: No module name 'xlrd'`.

It's usually easy for me to understand that I should just run `pip install xlrd`, but in some cases it isn't trivial, like `pdfminer` which actually requires `pdfminer.six`, and `png` which actually requires `pypng`. Also, VisiData should be usable for people who know nothing about Python.

Therefore, I think that we should have nice error messages like "Please run in the shell: pip install pdfminer.txt". If we'll ever want to go the extra mile, we could show a dialog that allows calling Pip automatically from within VisiData.

**Comment by anjakefala** [comment]
Duplicate of #1765

**Comment by anjakefala** [comment]
I added these for as many modules as I could identify! 

This was a change that required lots of careful modifications, and it is possible I mucked up somewhere. Anyone is welcome to submit a PR for a module I missed or mistook, or open an issue. 

The pattern is

```
from visidata import vd
module_name = vd.importExternal(module_name, package_name_if_different)
```

**Comment by cool-RR** [comment]
Thank you!
