### ISSUE TITLE
[menu] Can the menu system be removed?

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#174]
**Are any users currently taking advantage of the menu system as a learning tool?**

### Some background

The menu system was created to help users discover and learn the plethora of commands and features. 

In the meantime, @saulpw, @jsvine, and @deinspanjer have explored other avenues for achieving the same goal such as the [case studies](https://www.youtube.com/watch?v=N1CBDTgGtOU&list=PLxu7QdBkC7drrAGfYzatPGVHIpv4Et46W), [VisiData tutorial](https://jsvine.github.io/intro-to-visidata/index.html) and [keyboard cheatsheets](https://github.com/saulpw/visidata/issues/160). 

Additionally, the menu system was built from the longnames which have since been [completely reworked](https://github.com/saulpw/visidata/pull/170).

It would be a serious undertaking to recover the menu system, and at this point I am unsure if that undertaking is worth it considering the other lovely learning materials we have built up.

**Comment by anjakefala** [comment]
A bonus of removing it is that we can then remap `exec-longname` from `^A` to the coveted `Space` key. :D

**Comment by deinspanjer** [comment]
I have tried it a few times, but I didn't find it helped me really learn the commands as effectively as a keyboard cheatsheet does.
