### ISSUE TITLE
[confirmation dialog] Add mouse support and keyboard focus

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1740]
The file over-write dialog only seems to only allow 'y' or 'n' as input.  It would be useful if we could add more GUI like features.
It looks like GUI type confirmation dialog, but it does not accept mouse clicks on the Yes or No buttons.  It is also common for confirmation dialog boxes to allow one button to have focus, and the ability to use the tab key to change the button that has focus.  If you hit enter the focus button is clicked.

I think this issue has been in my head for awhile, and why I've provided a  more feedback on specific UI features for wizards and dialogs.

**Comment by saulpw** [comment]
The confirm dialog was definitely meant as a prototype "form", so these features would be reasonable, and especially once we create more involved forms for the wizards/guides.

**Comment by frosencrantz** [comment]
That is why I have been quiet about this before.  I was waiting for an update, but felt I needed to give feedback.

**Comment by saulpw** [comment]
The confirm buttons are now clickable as per #2075.  I don't think the confirm dialog needs to have button focus right now, since we are heading a different direction for other input forms with `inputMultiple()`, which already has Tab to change focus.
