### ISSUE TITLE
[macros sheet] Add a long name column to the Macros Sheet 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1741]
This is a repeat. Creating a separate issue so it is easier to find, but originally from geekscrapy's excellent macos bug: https://github.com/saulpw/visidata/issues/1569#issuecomment-1374947202

The Macros sheet doesn't list the long name of the macro command.

**Comment by anjakefala** [comment]
This issue is a bit bigger, because it also seems like the automatic longnames being created are not actually viable.

**Comment by frosencrantz** [comment]
Tell me more. I don't understand.  It sort of looked like the command column from the macros.tsv could be used.

**Comment by saulpw** [comment]
I updated the macros sheet to have `longname` and `keystrokes` columns now.
