### ISSUE TITLE
[SheetsSheet] Add a column  to show quitguard status of sheets

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1742]
In the Sheet Sheets add a column to show the quitguard status of the the sheets in the listed sheets.

**Comment by frosencrantz** [comment]
Also, the column should be live, so you can update the status from a sheets sheet.

**Comment by saulpw** [comment]
This would be pretty straightforward.  I could probably do it on a videocall with you if you're up for it!

Kondo'ed for now.
