### ISSUE TITLE
PostgreSQL database shows no tables

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1743]
Connecting to this Postgres database shows no tables:

```
vd postgres://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs
```

Same error happens with `vdsql`. I used `psql` to confirm this database has tables.

**Comment by anjakefala** [comment]
@cool-RR This is a remote public postgres server?

**Comment by anjakefala** [comment]
Duplicate of #1854

**Comment by cool-RR** [comment]
@anjakefala Yes it is. You can simply run the command I included in the first message.

I'm not sure why you marked the two issues as duplicates of each other. They might be related but the content seems different.

**Comment by anjakefala** [comment]
They will both be addressed by the same bugfix, and I am struggling to keep track of all of the issues.

**Comment by saulpw** [comment]
I don't know why `vd` shows no tables, but `vdsql` works now as of df3d8a0cb1809a2f10888c089ccc4c794cd064c3 (it was not replacing vd functionality with its own).
