### ISSUE TITLE
Improve colors on Windows Terminal + PowerShell

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1746]
I just tried using VisiData on Windows Terminal + PowerShell on Windows 10. I understand that it's a very popular terminal. (87K stars on GitHub.)

VisiData doesn't look terrible, but there are a couple of problems:

![1](https://user-images.githubusercontent.com/56778/219946547-142026f1-04eb-472b-bb2d-c361b2772c42.png)

![2](https://user-images.githubusercontent.com/56778/219946548-8bb1e929-7f60-4b3f-b9d5-9462e27387bc.png)

The purple color is barely visible. The red isn't great. The gray foreground text at the bottom is bad too.

I know that I can probably tweak the colors in Windows Terminal, but I think that VisiData should look good out of the box, the same way it does on Ubuntu.

Update: I checked on Windows Terminal + Ubuntu WSL and the colors are good there. (Except the text foreground on the bottom bar which I feel is too faint, but I'm not sure whether that's on purpose.)

**Comment by saulpw** [comment]
Can you try using the light theme?  (not released, in develop)

**Comment by cool-RR** [comment]
How does one activate the light theme?

**Comment by saulpw** [comment]
`View > Set theme > choose`

**Comment by cool-RR** [comment]
Here are a few examples of how it looks like. Is it better? It's more legible, but I wouldn't even consider using a light theme. I probably won't look into Windows Terminal anymore. It looks like my favorite solution for the talk would be to use Putty to SSH into an Ubuntu VM.

![screenshot_TURING_2023-02-19_234221](https://user-images.githubusercontent.com/56778/219976941-97ee176c-2b76-4a7c-aa28-3fffb64f52b3.jpg)
![screenshot_TURING_2023-02-19_234242](https://user-images.githubusercontent.com/56778/219976944-7529b1f6-4016-4da8-91e6-0dbb9db3fc63.jpg)
![screenshot_TURING_2023-02-19_234258](https://user-images.githubusercontent.com/56778/219976945-7c4771b8-3de1-4c14-aa5e-8b87f24a475b.jpg)

**Comment by saulpw** [comment]
Yes, this looks a lot better to me.  Legibility is paramount, and this doesn't seem ugly, even if it's not pretty (I'm not a fan of light themes either).  But the standard dark mode isn't pretty either, it's designed to be nondescript and stay out of the way.

**Comment by cool-RR** [comment]
@saulpw I really want to hardcode the color of the gray text in the bottom row to a specific color. Is this something I can do?

**Comment by cool-RR** [comment]
Oh, found it, I set the global option of `color_status` to `white` and now it looks great.
