### ISSUE TITLE
Characters that take up two character widths result in unintuitive editing behaviour

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#175]
1. Use `edit-cell` (`e`) on a cell containing East Asian text -> [example](https://github.com/saulpw/visidata/blob/develop/tests/remove-errors.vd#L13)
2. Move the cursor around. Press `Backspace`. Notice that the character underneath the cursor is erased (as opposed to the character preceding the cursor).
3. Enter some new text. Notice that the text appears after the cursor (it is expected that it precedes the cursor).

This is caused by the presence of characters which are rendered to encompass two character widths.

**Comment by anjakefala** [comment]
As a tangent, we should also document the features we have available in VisiData for properly displaying and handling ambiguous width characters.

**Comment by saulpw** [comment]
Thanks for finding and reporting this, @anjakefala!  Now we handle full-width characters correctly (or at least, better) in filenames, status messages, and input areas.

Maybe we should have a sample_data file with full-width characters in the filename for future testing :)
