### ISSUE TITLE
Site says VisiData can open Git?

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1753]
VisiData.org says that VisiData can open git repositories like `vd vgit`. Tried it, didn't work, I don't see it on the list of formats either. Is this a mistake?

**Comment by saulpw** [comment]
`vgit` is a separate app you can install via pip.  But I wouldn't bother right now, it's kind of a mess.  I'm in the middle of integrating it into vd core but it won't be ready for a few weeks probably.  Best to stick with vd 2.11 for the time being.
