### ISSUE TITLE
Implement `__repr__` for many objects

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1757]
I'm using a Python shell to inspect a VisiData sheet. When I list the columns, I see this: 

```
In [1]: columns
Out[1]:
[<visidata.column.ItemColumn at 0x7f95f90083a0>,
 <visidata.column.ItemColumn at 0x7f95f9008520>,
 <visidata.column.ItemColumn at 0x7f95f90084f0>,
 <visidata.column.ItemColumn at 0x7f95f90084c0>,
 <visidata.column.ItemColumn at 0x7f95f9008490>,
 <visidata.column.ExprColumn at 0x7f95f9008460>,
 <visidata.column.ItemColumn at 0x7f95f9008430>,
 <visidata.column.ItemColumn at 0x7f95f9008400>]
```

This is frustrating. I have to go over them one-by-one to figure out which one is which. Would have been cool if they showed something like `<visidata.ItemColumn: 'country'>`.

I think all the major types in VisiData should get this treatment. This also makes debugging easier.

**Comment by saulpw** [comment]
Added a repr for the base Column.  Sheet already has one.
