### ISSUE TITLE
[loader] markdown tables

### ISSUE THREAD

**Issue by g-simmons** [saulpw/visidata#1758]
It would be great to be able to load markdown tables in visidata. These tables are typically embedded in a larger markdown document (.md or .markdown extension). Maybe for documents with multiple tables we could first open something like the sheets sheet to select which table to edit, then edit each table as a typical vd sheet. 

1) A small sample representative dataset in that format.

Without alignment:

```
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
```

With alignment:

```
| Syntax      | Description | Test Text     |
| :---        |    :----:   |          ---: |
| Header      | Title       | Here's this   |
| Paragraph   | Text        | And more      |
```

Embedded in a markdown document:

```
# Lorem Ipsum Header
Lorem ipsum

| Syntax      | Description | Test Text     |
| :---        |    :----:   |          ---: |
| Header      | Title       | Here's this   |
| Paragraph   | Text        | And more      |

Lorem ipsum
```

2) A basic Python script which queries and dumps the data (possibly using an external package).

TODO

**Comment by frosencrantz** [comment]
I would like something like this.  VisiData is already able to save sheets in different types of markup tables, there is no support for additional  formatting.  For my limited use, I've been able to use [pandoc] to convert the tables into html and then read the data back into Visidata, which might handle your case 2.


[pandoc]: https://pandoc.org/

**Comment by saulpw** [comment]
Hi @g-simmons, this would be useful, I agree. If you can write or find some code using a Python library that will parse markdown tables, we can incorporate it pretty readily.  We're always open to PRs for new loaders.

Kondo'd for now.

**Comment by daviewales** [comment]
For future reference, I wonder if the ElementTree produced by Python-Markdown would be useful here:
https://python-markdown.github.io/extensions/api/#working_with_et
