### ISSUE TITLE
[develop] failure reading data from a pipe

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1759]
**Small description**
When reading from a pipe, the file guessing code breaks.

**Actual result with screenshot**
```StopIteration: 
ValueError: I/O operation on closed file
ValueError: I/O operation on closed file
ValueError: I/O operation on closed file
unknown "" filetype
opening - as txt
Traceback (most recent call last):
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/_open.py", line 48, in guessFiletype
    filetype = f(p)
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/loaders/archive.py", line 13, in guess_zip
    if not p.is_url() and zipfile.is_zipfile(p.open_bytes()):
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/path.py", line 275, in open_bytes
    return self.open(mode=mode)
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/path.py", line 245, in open
    return FileProgress(self, fp=BytesIOWrapper(self.fptext), **kwargs)
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/path.py", line 40, in __init__
    super(BytesIOWrapper, self).__init__(text_io_buffer, **kwargs)
```

**Steps to reproduce with sample data and a .vd**
`echo "a" |vd`

**Additional context**
saul.pw/VisiData v2.12dev
Ubuntu 22.04.2

**Comment by aborruso** [comment]
> **Steps to reproduce with sample data and a .vd**
> `echo "a" |vd`

If I run it, it works, but I have `saul.pw/VisiData v2.10.2`

![image](https://user-images.githubusercontent.com/30607/221400849-9184726c-bf15-4160-98b7-e02320c70f3d.png)

**Comment by anjakefala** [comment]
Interestingly, if you use `-f fixed` on `dev` that does resolve it. It might be related to the recent filetype guessing changes.

**Comment by anjakefala** [comment]
Yup, the error starts in 4743f92bb855cf931d896e65845c549ce6027e2f.

**Comment by anjakefala** [comment]
One question @saulpw , `zipfile.is_zipfile` seems to accept a filename as an argument (https://docs.python.org/3/library/zipfile.html#zipfile.is_zipfile).

Is there a reason you pass it the bytes from the file, instead? (https://github.com/saulpw/visidata/blob/9098f7d9b590d3872896ded222c5f1934959b3db/visidata/loaders/archive.py#L13)

**Comment by saulpw** [comment]
@anjakefala from the docs:

>  filename may be a file or file-like object too.

`Path.open_bytes()` doesn't return the bytes, it returns a file (or file-like anyway) object open to those bytes.

**Comment by anjakefala** [comment]
:facepalm: Oh, right. I have been away from Python for too long.

**Comment by anjakefala** [comment]
The basis of the bug is that rgw `guess_` were written for open filepointers in mind. The contents pointed to by a stdin filepointer are read once, and then it is closed.

There are several ways we could approach this:
1. Use the fact that stdin files have the path name `-` to skip guessing the filetype for stdin:

```
 def guessFiletype(vd, p):
     '''Call all vd.guess_<filetype>(p) functions and return best candidate sheet based on file contents.'''
 
+    if p.name == "-": #1759
+        return #stdin source is closed
     guessfuncs = [getattr(vd, x) for x in dir(vd) if x.startswith('guess_')]
     filetypes = []
     for f in guessfuncs:
```

This is an easy bandaid that I am tempted to open a PR for, but then the `guessFiletype` feature is not supported for stdin, where it might be useful.

2. See if it is possible to adapt some of the `guess_` functions to be able to accept text from `vd.stdinSource.fptext`. E.g. I think `guess_csv` might be adaptable? But maybe not, because it then loads the contents with a dialect in mind.

**Comment by saulpw** [comment]
Yeah, the filetype guessing feature is *most* useful for piping in data from stdin or a URL.  So let's not remove the error, but make it work for stdin too.

The visidata.Path objects do read from stdin and will cache the results for future "opens".  I have a fix for this locally.  The larger issue I think is that stdin is text and not binary, but raises errors when a binary format guesser tries to open it as binary.  The guesser should just fail in this case, as you wouldn't be piping a .zip (or other binary format) into vd anyway.

**Comment by anjakefala** [comment]
I am still seeing an error that is occurring in a different place if you do `echo "a" | vd`:

```
Traceback (most recent call last):
  File "/home/anja/git/visidata/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/anja/git/visidata/visidata/sheets.py", line 231, in reload
    for r in self.iterload():
  File "/home/anja/git/visidata/visidata/textsheet.py", line 25, in iterload
    yield from self.readlines(self.source)
  File "/home/anja/git/visidata/visidata/textsheet.py", line 30, in readlines
    for startingLine, text in enumerate(source):
  File "/home/anja/git/visidata/visidata/path.py", line 269, in __iter__
    for i, line in enumerate(fd):
  File "/home/anja/git/visidata/visidata/path.py", line 399, in __next__
    r = next(self.rf.iter_lines)
ValueError: I/O operation on closed file.
```

if you do `cat benchmark.csv | vd`, it guesses appropriately that the file is a csv:

```
[{'filetype': 'csv', '_likelihood': 0, 'csv_delimiter': ',', 'csv_doublequote': False, 'csv_escapechar': None, 'csv_lineterminator': '\r\n', 'csv_quotechar': '"', 'csv_quoting': 0, 'csv_skipinitialspace': False}]
```

but then fails to load it. Different stacktrace

```
Traceback (most recent call last):
  File "/home/anja/git/visidata/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/anja/git/visidata/visidata/sheets.py", line 897, in reload
    for r in vd.Progress(itsource, gerund='loading', total=0):
  File "/home/anja/git/visidata/visidata/threads.py", line 70, in __iter__
    for item in self.iterable:
  File "/home/anja/git/visidata/visidata/loaders/csv.py", line 50, in iterload
    yield next(rdr)
  File "/home/anja/git/visidata/visidata/path.py", line 399, in __next__
    r = next(self.rf.iter_lines)
ValueError: I/O operation on closed file.
```

**Comment by anjakefala** [comment]
Oh, I think after the `guessFiletype`, a filepointer gets passed to the `reload()`s that is running into I/O operation on closed file. It is appropriately guessing the filetype, but then something else has gone wrong.

**Comment by anjakefala** [comment]
This is now fixed on `develop`!
