### ISSUE TITLE
Deleting column not documented

### ISSUE THREAD

**Issue by Dmitrii-I** [saulpw/visidata#176]
Hi,

I was trying to delete the column and did not know the key for this operation.

visidata.org quick reference, the documentation, and https://jsvine.github.io/intro-to-visidata/ do not seem to document how to remove/delete/drop a column.

Could you please add docs for it?

**Comment by saulpw** [comment]
Hi @Dmitrii-I, I think you want to 'hide' a column: http://visidata.org/docs/columns/

**Comment by anjakefala** [comment]
Hello! =)

If you want to actually 'delete' a column permanently, you could:
1. Press `C` to open the **Columns sheet**.
2. Press `d` on the row referencing the column you wish to delete.

However, this does permanently remove that column from the sheet in the current session. Generally, we recommend using `hide` instead because it is easily reversible (like @saulpw recommended).

One thing we should consider is whether to reword the 'How to' title for that doc to contain the word 'remove'.

**Comment by anjakefala** [comment]
Clarification has been added @Dmitrii-I! Thanks for submitting a bug report for our docs. :D

**Comment by Dmitrii-I** [comment]
@saulpw Doesn't hiding mean that when I save the file, the column is still there in the file? What I would want is to delete the column. So when I delete the column and save the file it is gone forever.

@anjakefala Apparently the key for deleting column is a minus sign (-). This does not require going into Columns sheet.

I could not find the docs re: minus sign key shortcut hence why I opened this issue.

**Comment by anjakefala** [comment]
@Dmitrii-I Oh! I understand the confusion now!

The only columns that get saved to a tsv file are the `Visible` ones.

https://github.com/saulpw/visidata/blob/stable/visidata/loaders/tsv.py#L109

where `visibleColumns` are the non-hidden columns. (`-` hides a column.) So yes, hiding a column will definitely ensure that column does not appear when you save the sheet to disk.

This is definitely something we should clarify in the docs and in the helpstr for `save-sheet`

The procedure that I walked you through is for deleting a column from a VisiData session, such that the reference to that column in the **Columns sheet** disappears.

**Comment by anjakefala** [comment]
@saulpw please correct me if anything I said was incorrect.

**Comment by Dmitrii-I** [comment]
Hmm, so I can open a.csv file, hide a column, save it as b.csv, then unhide the column and save it as c.csv. The contents of a.csv and c.csv will be the same while b.csv will be missing the column that was hidden during the visidata session?

**Comment by anjakefala** [comment]
Yes, exactly!

**Comment by saulpw** [comment]
Seems right to me, @anjakefala.

**Comment by yozlet** [comment]
This could still do with being documented on the man page: https://github.com/saulpw/visidata/blob/stable/visidata/man/vd.1#L150

**Comment by anjakefala** [comment]
That's a good idea @yozlet. Would you mind modifying [vd.inc](https://github.com/saulpw/visidata/blob/develop/visidata/man/vd.inc#L150) and making a PR against the [develop](https://github.com/saulpw/visidata/tree/develop) branch?
