### ISSUE TITLE
http loader: guess filetype based on magic bytes

### ISSUE THREAD

**Issue by niv** [saulpw/visidata#1760]
Hello! Thank you for offering VisiData. It's a fantastic piece of software, and I've been enjoying playing with it so much I started experimenting with adding more file loaders.

This worked out really well for the most part, except one piece: I have a custom file format that canonically has no file extension; the filename is just a SHA1 hash. It is served over HTTP.

I'm currently on 2.11. However, I saw that a recent commit added `guess_*` to divine type based on file contents (e.g. magic bytes). This is perfect for my usecase and I am happy to wait for this to hit stable.

Unfortunately, from what I saw in the code on `develop`, the http loader will not currently invoke this function.

On 2.11, I can work around this by giving a explicit filetype: `vd -f <mytype> http://.../aabbccddeeff0011...`, but this introduces the problem that it also considers all other sources this format, which is not what I want (e.g. other CLI args, or even sheets openSource()d programmatically from the initial load also inherit this incorrect filetype unless overridden explicitly).

What would be a good way to solve this, either on 2.11 or develop? Maybe fetching the first few bytes at least, and invoking `guess_*` on that (giving them the stream to fetch more if needed)?

**Comment by saulpw** [comment]
Hey @niv, thanks for the kind words!

The `-n` (or `--nonglobal`) option at the CLI will help, at least in the short term.  It makes subsequent options only apply to sources given on the CLI, and not future sources as well.

The `guess_<filetype>()` functions should be called for any files of unknown filetype, whether from the local filesystem or over http or otherwise.  (It might be difficult with some protocols or formats, but we can try our best.)

I'm curious to see your loader, too, if you'd be willing to share.

**Comment by niv** [comment]
> The `-n` (or `--nonglobal`) option at the CLI will help, at least in the short term. It makes subsequent options only apply to sources given on the CLI, and not future sources as well.

Great, thank you. This can go into an alias for now.

> The `guess_<filetype>()` functions should be called for any files of unknown filetype, whether from the local filesystem or over http or otherwise. (It might be difficult with some protocols or formats, but we can try our best.)

I admit I haven't tried actually running this on develop yet (I like stable software), I just read the code on github, where the http loader does not call guess_ at all. But maybe I am reading the python code wrong [and I am missing a implicit call somewhere](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/http.py#L29).

> I'm curious to see your loader, too, if you'd be willing to share.

Certainly: https://github.com/niv/neverwinter.visidata

For background, this enables browsing and extracting some data formats for the game "Neverwinter Nights". I really like how vd allows to drill down all the way from a container format into specific data rows. The one part I haven't figured out yet is how to save back modifications in nested formats - I'll just call it a stretch goal. :) This is using a separate nim library I wrote earlier to do all the heavy lifting. I was actually planning on writing a TUI for the pre-existing lib/tools, but then I found vd, went down a tooling happiness rabbit hole, and decided to attempt making the UI in vd instead.

The specific usecase I mentioned in the initial post is loading so-called manifests over http; the filename of which is just a sha1 hash with a binary payload inside. There's a few magic bytes at the front that help discern the type; the URL could also be used. An example URL would be `http://curated.nwn.beamdog.net/manifests/a488db20a16ca3a42b52dd1ec520e9fd55c92e46`.

I thought about adding a custom url scheme handler at some point, but that will require more thought, as there's a few more data types and maybe some other browsing options I'd like to enable.

**Comment by anjakefala** [comment]
> For background, this enables browsing and extracting some data formats for the game "Neverwinter Nights". 

This is so cool, @niv <3 Thanks for sharing.

I read through this, and my understanding is that your request is supported on `develop`? It isn't a support filetype ("octet stream"), but it correctly interprets that that is the filetype.

Relevant commit: [2b36f3bde21937d24c3a762ff953034707fde667](https://github.com/saulpw/visidata/commit/2b36f3bde21937d24c3a762ff953034707fde667#diff-57cc65d61918298d01253ca3c411be31f30eee53dfa9aba0538f826537b265e5R30)

Is there anything else you need for this issue?

**Comment by niv** [comment]
> > For background, this enables browsing and extracting some data formats for the game "Neverwinter Nights".
> 
> This is so cool, @niv <3 Thanks for sharing.

No, visidata is way cooler. Thanks for working on it.

> Relevant commit: [2b36f3bde21937d24c3a762ff953034707fde667](https://github.com/saulpw/visidata/commit/2b36f3bde21937d24c3a762ff953034707fde667#diff-57cc65d61918298d01253ca3c411be31f30eee53dfa9aba0538f826537b265e5R30)

I read the code and tried it on develop by cloning the git repo and running from there.

A sample `guessurl_nwn` returning the dict based on a url regex matcher, like the sample you linked, made it all work without `-f`. I like how the guess call bubbles down and makes it work the same across protocols!

This is OK for some usecases where the URL is distinct. What I couldn't make work is determine the filetype based not on url, but stream content; e.g. magic bytes or other known file headers. I guess I could simply re-fetch the URL inside the guesser, but that seems a hacky/bad solution to me, even with something like requests_cache in place (not all requests might be immutable and hitting a server n times for a single cli invocation will be unexpected behaviour).

To support that, I think it would need the existing response object passed to guessurl somehow, so the stream could be open_byte()ed. Something like this maybe:

```python
def guessurl_nwn(vd, p, ??response??):
  pos = response.tell()
  hdr = response.read(10)
  response.seek(pos)
  if hdr == "MAGICBYTES":
    return dict(..)
```

**Comment by saulpw** [comment]
@niv You should be able to use `p.open_bytes().read(10)`, although there seems to be a bug in that (#1880).  Would you still need the response object in that case?  We should probably pass it along anyway though so that guessers can inspect the headers.

**Comment by niv** [comment]
> @niv You should be able to use `p.open_bytes().read(10)`, although there seems to be a bug in that (#1880). Would you still need the response object in that case? We should probably pass it along anyway though so that guessers can inspect the headers.

As I read the code: `p` here is just `Path(url)` as I gave it as an arg, passed through from `openurl_http`, with no knowledge of the already-fetched response. I do want to avoid hitting the http servers twice or more, but I did try open_bytes and it failed with an error (It seemed to not understand the http:// scheme or something; and if it would, wouldn't it just recurse?). I agree that the existing response object would be very useful to have for headers as well.

**Comment by saulpw** [comment]
Are you using `visidata.Path(url)` instead of the pathlib Path?  This should start the HTTP GET and provide a file pointer that reads the stream as necessary and caches the result.  It shouldn't be hitting the HTTP servers multiple times.

**Comment by niv** [comment]
Sorry, my python might just be too weak here. I tried this snippet:

```
@VisiData.api
def guessurl_nwsync(vd, p):
  try:
    print(p.given)
    with p.open_bytes() as bp:
      print(bp.read(4))
  except Exception as inst:
    print(inst)
```

It prints the URL correctly (`http://my.url/path`), then throws this exception: `[Errno 2] No such file or directory: 'http:/my.url/path'`  (note the single slash). After that, it aborts out of the guessurl handler and opens the URL as txt fallback.

**Comment by saulpw** [comment]
Hm, okay.  That should work, we'll look into it.  (It might just be `open_bytes` as  mentioned; does it work with `p.open_text` (now renamed to just `p.open` in develop as of a few minutes ago)?

**Comment by niv** [comment]
> Hm, okay. That should work, we'll look into it. (It might just be `open_bytes` as mentioned; does it work with `p.open_text` (now renamed to just `p.open` in develop as of a few minutes ago)?

Just tested: No, neither open_text() nor open() work. They error out the same as open_bytes(). 

I'm confused though. How does the path object know to not hit the http server again? The way I understand it, invoking open on the url would call openurl_http, which invokes the request again (hitting the server, unless something like request_cache is in play), which then hits guessurl, and so forth.

Passing the already-existing response object seems neater to me.

Thanks for looking at this!

**Comment by saulpw** [comment]
The visidata.Path object caches the result as it is read, without reading the whole thing first.  This is what the RepeatFile object does.

Will the response object do the caching itself?  Be aware that we're moving from the `requests` library to the stdlib urllib, so we won't benefit from request_cache anymore.

**Comment by saulpw** [comment]
Hey @niv, I made a change to pass the response object into `guessurl_` functions, but I'm not sure it would work as you're thinking of using it, since `response.read()` doesn't cache as the file-like returned by `visidata.Path.open()`.  It would basically only be usable to get at the headers or other metadata.

Anyway, ideally anything that needs to guess based on the file contents should be a `guess_` function, so that contents saved as local files can be inspected the same as contents read from a web server.  (Though this is still imperfect because you can't currently read random-access from a web socket like you could a file.)

> I'm confused though. How does the path object know to not hit the http server again? The way I understand it, invoking open on the url would call openurl_http, which invokes the request again (hitting the server, unless something like request_cache is in play), which then hits guessurl, and so forth.

To answer this earlier question, the `guessurl_` functions are currently only called by the http/https "loader".  So first the protocol is used to find the `openurl_` transport, and then `openurl_http` calls `guessurl_foo` to get the filetype, and then `guess_foo` if that didn't work, and then finally calls `open_foo` to return the sheet.

It sounds like you've gotten a guesser working by looking at the URL though, and passing along the response might help a bit if you want to look at some metadata.  Otherwise, if using `visidata.Path.open()` doesn't work to guess the filetype, that would be a bug or shortcoming in visidata.Path (which we may or may not be able to address reasonably).
