### ISSUE TITLE
Feature request: Add command `sort-disable`

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1762]
Discussion: #1761 

Add command `sort-disable` that disables sorting and reverts back to the default sort. There doesn't need to be a key binding.

**Comment by saulpw** [comment]
Here you go:

```
@Sheet.before
def orderBy(sheet, *args, **kwargs):
    if not hasattr(sheet, 'origSortedRows'):
        sheet.origSortedRows = list(sheet.rows)

@Sheet.api
def sort_disable(sheet):
    sheet.orderBy()
    sheet.rows = sheet.origSortedRows

Sheet.addCommand('', 'sort-disable', 'sort_disable()', 'disable sorting and revert back to original sort')

vd.addMenuItems('''
     Column > Sort by > original ordering > sort-disable
''')
```

**Comment by cool-RR** [comment]
Why not add it to VisiData?

**Comment by saulpw** [comment]
This code has some issues: for example, if you sort, delete some rows, and then sort-disable, the deleted rows will reappear.  I'm guessing it will work for your use case but I don't think robust enough data-wise to include in VisiData as it is.

**Comment by cool-RR** [comment]
I understand. Thank you.
