### ISSUE TITLE
Go to line number in menu

### ISSUE THREAD

**Issue by snooppr** [saulpw/visidata#1766]
In menu -> column -> Goto there is a function to go to column number (zc).  In Menu -> Row -> Goto there is no jump to row number.  Why?  

I also looked into the tooltip and didn't [find](https://jsvine.github.io/visidata-cheat-sheet/en/)  one of the most requested features, found the tooltip in help(zr).

Add to the Row menu, jump to row number.

**Comment by anjakefala** [comment]
Good suggestion, thanks! I added it on `develop`.
