### ISSUE TITLE
html encoding error

### ISSUE THREAD

**Issue by snooppr** [saulpw/visidata#1767]
`vd http://stat.latlon.org/ru/amur/latest/users.html`

The problem with the display of krillitsy in html.  Cyrillic is the second most popular content on the Internet.

In the screenshot below, there is a problem with displaying utf-8, because the server does not return the encoding, see curl.
![curl](https://user-images.githubusercontent.com/61022210/221524366-a3d9cab0-b45c-4fbc-a85a-a916a276b2e4.jpg)

But the correct encoding is present in the source code of the html page: "utf-8".
![source html](https://user-images.githubusercontent.com/61022210/221524690-34ac9bce-2342-40b2-b7ec-d2de0ee8f0ee.jpg)

And here's the actual problem, displaying the Cyrillic alphabet (krakozyabry).  For Russian speakers, this problem is critical.
![krakozyabry](https://user-images.githubusercontent.com/61022210/221525456-8cfd2413-5784-44fd-af39-a919aa2b9978.jpg)

Instead of relying on a response from the server about the encoding in case there is none, the **best thing to do is to parse the tag from the source code of the html** page (forcing utf-8 is also not good, because there are sites on the Internet with cp1251 encoding, this will also create problems  with Cyrillic display).  

I suspect that the default in this case is returned, some kind of "... iso ...".  But on the Internet, this has long been outdated.

example test url:
http://stat.latlon.org/ru/amur/latest/users.html

**Comment by saulpw** [comment]
Thanks for the issue, @snooppr.  What you say makes sense, but it is tricky to get that information from the html to the decoder at the right time.  But as a workaround, you should be able to set `options.encoding` manually; in this case, to `utf-8`.  This is the default though; does this not work correctly?  I don't know what version of VisiData you're using, or what your exact expectations are.  Please refile with a bug report properly filled out if setting options.encoding isn't working properly.

**Comment by snooppr** [comment]
@saulpw I wrote the report in sufficient detail.  I don't see utf-8 being applied by default.  Among other things, I have attached a url for tests.  Can you share your screenshots where encoding=utf-8 at the given url as an example?

visidata v2.11
test url:
http://stat.latlon.org/ru/amur/latest/users.html
