### ISSUE TITLE
[develop] Improve the interaction of `warning()` and sidebar markdown colorizers

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1769]
The warning message that pops up when you try to modify an expression column is a good example.

![Screenshot from 2023-02-27 15-01-17](https://user-images.githubusercontent.com/7489659/221708963-6d3c9966-30d9-48ac-9dd1-0dd8354f92d1.png)

**Comment by saulpw** [comment]
Should be fixed with 32f08ea97ffc62557dcd645744637990e5d886b9 and subsequent commits.  Now we're experimenting with sidebar, menu/status, and warning/error colors that work well together.
