### ISSUE TITLE
[disp_sidebar_fmt] Cannot disable side bar

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1771]
**Small description**
I just tried to disable the sidebar as it was obscuring some data, but it doesn't seem to set the value to `None`.

**Expected result**
To set the `disp_sidebar_fmt` to `None` in the options window

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/221823883-fc3b91a8-caaa-4375-a941-76331337ee43.png)

**Steps to reproduce with sample data and a .vd**
Use latest version (`@develop`) and  press `b`

**Comment by geekscrapy** [comment]
Also using the input as the following doesn't set the option value to None. I also tried `zd`:

```
sheet	col	row	longname	input	keystrokes	comment
mysheet			exec-python	sheet.options.disp_sidebar_fmt = None		execute Python statement with expression scope
```

**Comment by anjakefala** [comment]
```
def sidebar(sheet):
   [...]
   fmt = sheet.options.disp_sidebar_fmt or sheet.help
```

Ah, this is because `sheet.help` seems to be always on as a fallback.

**Comment by geekscrapy** [comment]
FWIW Also just noticed that `b`/toggle works _if_ you have `disp_sidebar_fmt` set to something (any string). But this bug still limits setting it to `None`.
Wasn't sure if this was covered by the identified issue by @anjakefala above.

Update: I forgot to try a " " as the `disp_sidebar_fmt` value which works to disable the sidebar completely as expected.

**Comment by anjakefala** [comment]
@geekscrapy Saul has a fix for this on the way! Thanks for all of the additional debugging info. =)

**Comment by anjakefala** [comment]
The fix is now on `develop`!
