### ISSUE TITLE
Unable to replay commandlog when loading an HTML table

### ISSUE THREAD

**Issue by mokalan** [saulpw/visidata#1773]
**Small description**
After saving the commandlog, it's not possible to replay it

**Expected result**
open the row and get the HTML table

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/64436128/221941537-45fdecaf-9eee-4d43-8be3-74000fefc09b.png)

**Steps to reproduce with sample data and a .vd**
1. Open the attached HTML
2. Shift-D and save the commandlog
3. Try to replay `vd -p table_0_cmdlog.vdj table.html`
4. Get the error as in the screenshot

**Additional context**
- +: syntax works ok `vd table.html +:table_0:0:0`
- Latest develop branch

[table.html.gz](https://github.com/saulpw/visidata/files/10853404/table.html.gz)
[table_0_cmdlog.vdj.gz](https://github.com/saulpw/visidata/files/10853492/table_0_cmdlog.vdj.gz)

**Comment by anjakefala** [comment]
Hey @mokalan!

Thanks so much for providing the sample data and .vdj. As far as I can tell, @saulpw's recent commit fixes the issue.

I am going to resolve this as fixed, but please re-open if you are still running into problems replaying your cmdlog.

**Comment by mokalan** [comment]
Interactive mode is working, but batch mode does not. I'm getting:
```
opening table.html as html
opening table_0_cmdlog.vdj as vdj
no "キtable_0" row
replay canceled
```

**Comment by saulpw** [comment]
Fixed now.  This was an issue with .vdj (and presumably .vd) files but not .vdx, since cursor movements are separate commands in .vdx.

**Comment by mokalan** [comment]
Sorry... I wasn't clear. The scenario I've described in the beginning is fixed now. But if you try it with batch mode, it's not working.

i.e. : `vd -b -p table_0_cmdlog.vdj table.html`

**Comment by saulpw** [comment]
@mokalan Did you try it with the commit 60c9cbb?

**Comment by mokalan** [comment]
Sorry... my mistake. Venv mixup. Thanks!
