### ISSUE TITLE
[FreqSheet] When diving into rows from a FreqSheet, the name is m_a_n_g_l_e_d

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1777]
**Small description**
As per description

**Expected result**
Name should be normal string

**Actual result with screenshot**
![split rec](https://user-images.githubusercontent.com/11225502/222155606-de6e83f4-01ce-4c8d-9d05-1086d1208ae3.gif)
When diving into the def row, note the new sheet name is `d_e_f` instead of `def`

I haven't looked, but I presume this is due to the Freq'd row name to be give to the new sheet and it is expecting a list of names, and since a string can be a list it just takes that and joins it with the join char.

**Comment by anjakefala** [comment]
It seems like @saulpw fixed this on `develop`! =)

**Comment by geekscrapy** [comment]
Working as expected. Thanks both!
