### ISSUE TITLE
[capture-col] When nothing is captured, "IndexError: list index out of range" is thrown

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1778]
_Minor user exp bug_

**Small description**
When using `capture-col` on a column and the regex does not capture any values, the below error is thrown. No new column is created (as expected)

**Expected result**
Just to show the "no columns to add" error. Preferably, change the error to something more informative such as "no matches found, didn't add column"

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/Users/geekscrapy7/lib/python3.7/site-packages/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/geekscrapy7/lib/python3.7/site-packages/visidata/features/regex.py", line 77, in addRegexColumns
    vs.addColumnAtCursor(*cols.values())
  File "/Users/geekscrapy7/lib/python3.7/site-packages/visidata/sheets.py", line 473, in addColumnAtCursor
    firstnewcol = [c for c in cols if not c.hidden][0]
IndexError: list index out of range
```
I presume this error is from an insufficient catch of an exception and it is attempting to create the column even though there are no groups to show.

**Steps to reproduce with sample data and a .vd**
`# echo -e 'helloooo\nthere' | vd -f txt --config=/dev/null --visidata_dir=/dev/null`

```tsv
sheet	col	row	longname	input	keystrokes	comment
-	text		capture-col	(ABC)	;	add new column from capture groups of regex; requires example row
```

**Additional context**
v2.12dev

**Comment by midichef** [comment]
Good improvement! I suggest that the error message should match the case when the user forgot to specify a capture group. I often forget to, and I'm probably not the only one.

**Comment by anjakefala** [comment]
I implemented both of the things. =D

**Comment by Freed-Wu** [comment]
Why not provide a better prompt like `no capture group`? `IndexError: list index out of range │ no columns to add` is too hard to understand for new users :smile:

**Comment by anjakefala** [comment]
@Freed-Wu Unfortunately, the error pops up for other regex commands as well! It is within a general helper function used by `:` and `;`. 

I agree, it is not as clear. Maybe, I can figure something out.
