### ISSUE TITLE
[bug reporting] Add detail to the Bug reporting template to include a suggestion of how to run without user config

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1779]
_This is a multipart Q_

1. I'd like to propose a change to the "Bug Report" issue template to include text which asks the user to attempt to replicate their issue without a user config, like so:

`# echo "abc" | vd -f txt --config=/dev/null`

2. Is/should `visidata_dir` required to completely exclude user configuration from a VisiData run? This is something I personally have to do to disable all my config, do others have to do this also? If so, probably add this arg to the point 1. example

**Comment by saulpw** [comment]
Hey @geekscrapy, good suggestion!  For (2), try using `-N` (a recent addition in v2.11), which should mean "load nothing extra": no plugins, no visidatarc, just the base and that's it.

**Comment by anjakefala** [comment]
This was a great suggestion. I implemented it!
