### ISSUE TITLE
[sidebar] UI issues

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1786]
**Small description**
Mostly discussed on https://github.com/saulpw/visidata/discussions/1733

- [x] :new: There may be an off by one-error for showing the last line, when the sidebar text is larger than the sidebar. the bottom line of the sidebar box is modified.
- [x] add help text saying how to close the guide
- [x] If the terminal height is too small, the guide is truncated, but there is no visual indication that it has been truncated.  There does not appear to be a way to scroll the guide if it has been truncated
- [x] the sidebar/guide doesn't absorb mouse clicks.  When there are mouse clicks on the sidebar, Visidata behaves as if the sidebar wasn't there, and moves the cursor within the current sheet.

**Expected result**
- Shown text fits inside sidebar box.  Now it can overwrite the bottom line of the box.
- Communicate mechanism to close the sidebar
- Visual indicator(s) for when the shown text scrolls off the top/bottom.
- Absorb mouse clicks.

**Actual result with screenshot**
https://asciinema.org/a/iV8cG7hJOBBRWmVLjeZ1Col92

**Steps to reproduce with sample data and a .vd**
Run `vd` on a directory or open a frequency sheet.

**Additional context**
Please include the version of VisiData.  Latest develop.

There was already a good discussion on the guide on https://github.com/saulpw/visidata/discussions/1733, so putting this in a specific bug.

**Comment by anjakefala** [comment]
I added task boxes, and updated the section on closing the sidebar. `b` closes it, but I think we still need to integrate teaching the user about `b`.

**Comment by anjakefala** [comment]
I think @saulpw addressed all of these issues with the latest changes! When the full sidebar cannot be displayed, there is a "full sidebar with `gb` message" :))

Thank you for this thoughtful reflection.

**Comment by frosencrantz** [comment]
Thanks @saulpw and @anjakefala!
I was able to try it a little today.  It works much better with all the changes.  

Hmm...  Maybe I should try the split screen.
