### ISSUE TITLE
Customize status line 

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1791]
Can I customize status line? I want a colorful status line like [vim-airline](https://github.com/vim-airline/vim-airline):

![demo](https://github.com/vim-airline/vim-airline/wiki/screenshots/demo.gif)

**Comment by saulpw** [comment]
You can customize the text with `options.disp_status_fmt` and `options.disp_rstatus_fmt`.  You can't use colors or attributes yet but that should be coming soon!
