### ISSUE TITLE
AttributeError: 'VisiData' object has no attribute 'addMenuItems'

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1792]
I got this error when trying to run VisiData on Windows 10 WSL:

```
 Traceback (most recent call last):
   File "/home/ramrachum/.local/lib/python3.8/site-
 packages/visidata/settings.py", line 335, in loadConfigFile
     exec(code, _globals)
   File "/home/ramrachum/.visidatarc", line 220, in <module>
     vd.addMenuItems('''
 AttributeError: 'VisiData' object has no attribute 'addMenuItems'
```

This isn't the first time I got this error, but now since I upgraded to Windows 10, it's a blocker for my talk.

**Comment by cool-RR** [comment]
Oh, silly me, it's not a block because it's in my scripts. In fact it's the code you suggested here: https://github.com/saulpw/visidata/issues/1762#issuecomment-1445548894

Still... Why is this happening?

**Comment by saulpw** [comment]
vd.addMenuItems has been added since the latest release (v2.11).

**Comment by cool-RR** [comment]
This happens on VisiData 2.11:

```
Administrator@Turing MINGW64 ~/Desktop
$ vd --version
saul.pw/VisiData v2.11
```

Sidenote: Might be useful if the exception page will also contain the VisiData version and operating system, so people could copy-paste the entire thing. 

(This issue isn't a blocker for me anymore because I don't particularly care about showing a new menu item, so I'm just putting this information here in case it's useful for you.)

**Comment by saulpw** [comment]
Sorry, I meant, it is not in v2.11, it has been added since then.  addMenuItems is so far unreleased .
