### ISSUE TITLE
[sidebar] Large amount of status updates, fill the screen vertically

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1797]
**Small description**
When Freqing a sheet with many rows, unselecting and deselecting on the FreqSheet creates a lot of lines for the sidebar

Unsure how to fix, maybe limit to the last X statuses? This will actually force status messages to be more explicit as well

**Expected result**
For the sidebar to remain a fairly static size. Differences in size, e.g. larg(ish) for guides, and smaller sized box for status, subtly indicates to the user what might be being shown without even looking at it.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/11225502/224103633-a78e8f3c-6b4b-416e-b3ff-3ecddb129160.png)

**Steps to reproduce with sample data and a .vd**
Open a large sheet and freq a column. Now do a `gt` on the freq sheet. This will cause a lot of status updates which could fill a large portion of the screen vertically.

**Comment by saulpw** [comment]
So, what if we fixed this exact particular case, and made it so that these same/similar status messages from a single command were compressed into a single message?  Like with the `[80x]` notation but with a little more fuzziness (so these might say e.g. `[80x] unselected some dicts`)

**Comment by saulpw** [comment]
In general I agree though, the sidebar should have a maximum height (and width?), at least for status messages, if not for everything.

**Comment by geekscrapy** [comment]
> So, what if we fixed this exact particular case, and made it so that these same/similar status messages from a single command were compressed into a single message? Like with the `[80x]` notation but with a little more fuzziness (so these might say e.g. `[80x] unselected some dicts`)

Hmm, I do like to see the total amount of dicts that have been affected. Is there maybe a way to just update the counter for the amount of rows affected, rather than printing a new status line? Maybe something like the progress context?

I use statuses to validate the amount of rows I'm affecting, so having a total is a really nice to have

**Comment by anjakefala** [comment]
With the recent changes, now it should not overflow the screen!

**Comment by geekscrapy** [comment]
Nice @anjakefala ! Today is update day for me 🤓
