### ISSUE TITLE
Allow users to transform columns with regex

### ISSUE THREAD

**Issue by vbrown608** [saulpw/visidata#18]
Visidata currently allows users to search by regular expression. Users should also be able to
* Edit a column using a sed-like syntax
* Create a new column based on an existing column using a sed-like syntax

**Comment by vbrown608** [comment]
We also want "split": create a new column for each capture group

The syntax for that will be `;regexp`, ex `;(.*) - (.*)`

**Comment by saulpw** [comment]
`;` now does regex split by capture group, and `*` creates a new column based on regex transform (e.g. `(.*) - (.*)/\2: \1`.  Mass edit by regex not yet supported; considering "mass edit with values from another column" command to use in conjunction with regex transform.
