### ISSUE TITLE
How can let directory display the short path

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1801]
```sh
cd ~
vd Desktop
```

The directory is `Desktop`

Press ``\``` to go up, The directory is `Desktop/..` not a shorter `.`.

How can I let directory display a short path?

**Comment by saulpw** [comment]
It's a good question, @Freed-Wu.  How would you do this in Python?

**Comment by Freed-Wu** [comment]
```sh

cd ~
vd Desktop
```
![screen-2023-03-20-16-15-11](https://user-images.githubusercontent.com/32936898/226282869-6f7cbb6e-da7b-4a52-9d01-59c887ea4d65.jpg)

go up:
![screen-2023-03-20-16-15-21](https://user-images.githubusercontent.com/32936898/226282921-a0cf7bc9-6f06-4904-8949-12f5be0551c9.jpg)

**Comment by anjakefala** [comment]
@Freed-Wu One corollary is that if we remove `..`, then once the user opens the parent of the current working directory, we have to switch to working with absolute paths. 

Otherwise, the parent of `'.'` is always `'.'`.

**Comment by anjakefala** [comment]
Check it out on the `develop` branch, and let me know how it feels!

**Comment by Freed-Wu** [comment]
> Check it out on the develop branch

It works!
