### ISSUE TITLE
Feature request: split-col but for lists

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1802]
I wish there was a command like `split-col`, except instead of splitting a column by regex, it just takes a list columns and splits it to the items in the list.

I figured something like this exists, but I couldn't find it in the help menu.

**Comment by saulpw** [comment]
You can just use `=col.split(", ")`, which should do the same.  Though I've been actually thinking about making the command you suggest (`split-col-list`?), and binding it to `:` instead of `split-col`, because you can just `(` to expand it anyway.

**Comment by anjakefala** [comment]
Oh, I use `split-col` all of the time! It is one of my frequently used commands. I use it on non-lists.

**Comment by saulpw** [comment]
Oh, maybe I misunderstood.  @cool-RR do you just want `(` to expand a list column?

**Comment by cool-RR** [comment]
Oh exactly, `(` is what I want here, thank you.
