### ISSUE TITLE
First sheet seen should be first arg on CLI

### ISSUE THREAD

**Issue by Freed-Wu** [saulpw/visidata#1804]
`a.json`:
```json
[{"a": 1, "b": 1}]
```

`b.json`:
```json
[{"b": 2, "c": 2}]
```

Then
`vd a.json b.json`.

the 1st table will be `b.json` and 2nd table will be `a.json`. However, in command line arguments, `a.json` is first and `b.json` is second. Why not make the order same?

**Comment by saulpw** [comment]
It pushes the sheets in the order they appear on the CLI.  The last sheet pushed is always the top sheet, or the first one that is seen.

I seem to remember trying it as you suggest, but there were some subtle issues with the rest of argument parsing.  I don't recall the specifics.  In any event I'm reluctant to change the behavior at this point.  If others weigh in with strong opinions maybe that could change.
