### ISSUE TITLE
Add read-only flag

### ISSUE THREAD

**Issue by fwdekker** [saulpw/visidata#1805]
## The problem
I personally only use VisiData to inspect the contents of SQLite databases used by software on my server, as this is much more secure and requires less maintenance than using a public-facing web interface. These databases may contain logs or user accounts, and I only need to read them; all the writing and updating is handled by the software that created the database. However, I'm not all too familiar with all the shortcuts that VisiData has, and sometimes I press one by accident, and suddenly a table is marked for deletion, at which point I need to make very sure I don't confirm this change, and should immediately quit the application.

## The solution
It would give me significant peace of mind if I could run `vd --read-only ./my_database.db` and then rest assured that no changes are ever written back to disk. An alternative would be to run `sudo -u myspecialuser vd ./my_database.db` and ensure that the user `myspecialuser` has read access but not write access to the file, but unfortunately my databases need a specific user and group assigned to it, and Linux and *BSD do not have fine-grained access control.

## The implementation
I can imagine several ways of implementing a read-only mode for VisiData, and they're all fine with me:
1. The [`nano`](https://en.wikipedia.org/wiki/GNU_nano) way: Similar to when a user runs `nano file.txt` and they have read but not write access to `file.txt`, the editor shows `File file.txt is unwritable` in the bottom, but still allows the user to perform any changes they want inside the editor. However, the editor gives an error when the user tries to save the file.
2. The other `nano` way: Similar to when a user runs `nano -v file.txt` or `nano --view file.txt`, VisiData refuses actions that would edit the database (such as deleting a table, inserting a new row, opening the editor for a record, etc.), showing the message `Key is invalid in view mode`.
3. The cheaty way: VisiData copies the database to `/tmp/visidata-<random>/database.db` and then opens the copy. The user can write changes, but they are stored to the temporary file, which is deleted afterwards, so the changes do not affect the original database. This can potentially be confusing for the user, though, and I'm not sure what the security implications are of copying a database to a directory where other users could potentially see it.

**Comment by saulpw** [comment]
Hey @FWDekker, thanks for the suggestion.  There are only two commands that could conceivably write to a file, `Ctrl+S` and `z Ctrl+S`. It would be pretty straightforward to disable these commands; I think that would be basically your option (1).  Option (2) would be more difficult, since there are so many ways to modify data.  Option (3) is not really an option though, for several reasons.

**Comment by saulpw** [comment]
Okay, there's a new CLI option `--ro`/`--readonly` which will prevent existing paths from being overwritten, and also disables commit (`z Ctrl+S`).  You can still save to a new path that doesn't yet exist, however.  `--ro` is the opposite of the existing `-y` option which overwrites without confirmation.  The default still asks for confirmation before overwriting.  I added a little `[RO]` flag on the status line if overwrite is disabled like this.

Let me know if this would gives you the peace of mind you're looking for!

**Comment by fwdekker** [comment]
Yay! I tried out the dev branch, and it works exactly as I'd want to. Thank you! :-)

**Comment by midichef** [comment]
Here's a delayed followup, to mention another way to solve this problem with a feature I just found out about. There is an alternative way to make SQLite databases read-only in Visidata. You can add the equivalent of SQLite's URI parameter [`mode=ro`](https://www.sqlite.org/uri.html#recognized_query_parameters).

That can be done by adding this to .visidatarc:
```
# for more info on "mode=ro"  see https://www.sqlite.org/uri.html#recognized_query_parameters
vd.options.sqlite_param_mode = 'ro'
```
Or by running visidata as `vd --sqlite_param_mode=ro testfile.sqlite`

Then SQLite files will opened read-only at the level of the SQLite connection. Then visidata simply cannot edit the database through that connection. When `commit-sheet` is run, visidata will raise an exception:
```
sqlite3.OperationalError: attempt to write a readonly database
```

There's not much benefit to doing this. It gives similar overall protection as doing:
```
SqliteSheet.options.readonly = True
```
but at a lower layer than Visidata. Hypothetically if you created your own `commit-*` commands that ignored the value of `readonly`/`overwrite`, your file would be protected from even those ill-behaved commands, as long as you used the `sqlite_param_mode='ro'` method.


The `readonly` option is more versatile. It applies to all kinds of sheets. I use `DirSheet.options.readonly = True` to make sure I can't accidentally delete files from inside a `DirSheet`.
