### ISSUE TITLE
Feature request: Provide command `reopen-closed-sheet` like Chrome's Ctrl-Shift-T

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1811]
It often happens that I close a sheet by mistake and immediately curse because I've already done a bunch of manipulations on this tab that I'll now have to repeat. (I know I can guard a sheet but that doesn't fit my workflow.)

I wish VisiData had a feature like Chrome's Ctrl-Shift-T. Basically a command that just opens that sheet that was closed most recently, with all the manipulations that I've done to it. 

Of course, this command is challenging because it means VisiData has to keep this information around. Maybe limit it to last 3 sheets.

**Comment by saulpw** [comment]
Actually there is already `g Shift+S` which has a list of all sheets ever made, and you can select the closed sheet from there to reopen it.  (`Shift+Q` will quit it without recourse, however.)  It wouldn't be too difficult to make this command.  The question is, what to bind it to?  `zq`?  `g Shift+U`?

**Comment by cool-RR** [comment]
Good to know about `g Shift+S`! This almost solves the problem for me. I do notice that it's sorted by name though. I'm interested in the most recently closed sheet, so this might be hard to find if I have more than a dozen sheets there. It would make sense to me if these were sorted according to datetime of closing. 

I figure that maybe I can use the `shortcut` column as a proxy for last closing, which might work. One weird thing I found is that when sorting by that column, either descending or ascending, it stays in the ascending order of 1-2-3-4. Setting the column as int or float and then trying to sort again makes no difference.

Regarding a key binding, I don't know. Your intuition is probably better than mine. I'm okay with both of the options you suggested.

**Comment by saulpw** [comment]
So I think this command is just:

```
BaseSheet.addCommand('zq', 'open-last-closed', 'push(allSheets[-1])'.  'reopen most recently closed sheet')
```

Can you try this out and see how it feels?  I'm not sure about `zq`, it felt kind of awkward, but please try `zU` and `gU` and see how they all feel.  Submit a PR if you like one of them (and include `vd.addMenuItems('...') with where it goes in the menu scheme).
