### ISSUE TITLE
[yaml] Loader not working, cannot find `vd`

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1815]
**Small description**
YAML loader not working, cannot find `vd`

**Expected result**
YAML loader works.

**Actual result with screenshot**

https://asciinema.org/a/EBtOGbMbNShWxXgi0mZmV9SeY

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/pyobj.py", line 27, in reload
    for r in self.iterload():
  File "/usr/lib/python3.9/site-packages/visidata/loaders/yaml.py", line 14, in iterload
    yaml = vd.importExternal('yaml', 'PyYAML')
NameError: name 'vd' is not defined
```
**Steps to reproduce with sample data and a .vd**
`vd sample_data/states.yml`

**Additional context**
Please include the version of VisiData. Latest develop branch.

**Comment by anjakefala** [comment]
Fixed! And added a test, so we would know next time. =) https://github.com/saulpw/visidata/commit/d4a5f0217b0593c96f21442b1780bb137e95a942

**Comment by frosencrantz** [comment]
Thank you  @anjakefala.  I appreciate all these fixes and tests!
