### ISSUE TITLE
cron / no-tty

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#182]
Can vd be run in cron? i have this line in a script: 'vd -b /tmp/ob.fixed -o /tmp/obt.csv'

It works when run in terminal, but get this error in cron log:

CMDOUT ([Errno 6] No such device or address: '/dev/tty'

**Comment by saulpw** [comment]
I am using batch mode within cron myself.  I do remember having to fix this bug a little while ago.  What version are you using?  Does this happen with 1.3.1?

**Comment by ghost** [comment]
I upgraded now, and the same error persists.

**Comment by saulpw** [comment]
Okay, will investigate.  It is running in a nightly cronjob for me, but I may have set an option in the script or made some other external adjustment.

**Comment by ghost** [comment]
Did you get the same error, or that line works for you?

**Comment by ghost** [comment]
This seems to work for me:

faketty () { script -qfc "$(printf "%q " "$@")" /dev/null; }
faketty vd -b /tmp/ob.fixed -o /tmp/obt.csv

**Comment by saulpw** [comment]
Nice find, @blawiz!  It was a weird interaction between no-tty and batch mode without a script to play.  (My usage with cron always replays some script.)  This checkin fixes it and we'll include the fix in 1.3.2.
