### ISSUE TITLE
YAML fails reading files with tuples

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1822]
Example file:

```
foo: !!python/tuple
- 1
- 2
- 3
```

Error:

```
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'·
```

**Comment by saulpw** [comment]
This is a problem for the `yaml` library itself.  If you can get that library to parse tuples itself, then the problem can be fixed in VisiData.

**Comment by cool-RR** [comment]
If I can solve the problem by calling `yaml.add_constructor` rather than making any modifications to the `yaml` library, would you merge that?

**Comment by saulpw** [comment]
Of course, that's how it should be. Maybe we could add a comprehensive .yml file to test against too.
