### ISSUE TITLE
statusbar describes Alt+Shift as "Alt+Shift+Shift+"

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1828]
**Small description**
When pressing 'Alt' and 'Shift' and any character (for example, 'M'), the statusbar shows the keypress as "Alt+Shift+Shift+M", where "Shift+" is added twice.

**Expected result**
I expect the statusbar to show "Alt+Shift+M".

**Actual result with screenshot**
![shiftshift](https://user-images.githubusercontent.com/67946319/228633671-9f5c486d-3648-434a-8522-baf3ee26bfe6.png)

**Additional context**
saul.pw/VisiData v2.11
saul.pw/VisiData v2.12dev
Ubuntu 22.04.2

It looks like the first "Shift+" is added from prettykeys() in mainloop.py:
https://github.com/saulpw/visidata/blob/2edee996ba2f80a9a50bc18994dc01c3ce9affb4/visidata/mainloop.py#L210
and the second "Shift+" is added in statusbar.py
https://github.com/saulpw/visidata/blob/2edee996ba2f80a9a50bc18994dc01c3ce9affb4/visidata/statusbar.py#L183

**Comment by saulpw** [comment]
Thanks @midichef, should be fixed now!
