### ISSUE TITLE
the key combination Alt+Shift+A is rejected

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1829]
**Small description**
After pressing `Alt+Shift+A`, the key combination is rejected with the warning "duplicate prefix: A"

**Expected result**
I expect to see the message 'no command for "Alt+Shift+A"' that is shown for most other Alt+Shift+character combinations, like `Alt+Shift+Z`

**Actual result with screenshot**
![alt-shift-a](https://user-images.githubusercontent.com/67946319/228635917-e3f28578-d6c4-4e89-89bf-cfc2e3d29a2a.png)

**Additional context**
saul.pw/VisiData v2.12dev

**Comment by saulpw** [comment]
Thanks @midichef.  Should be fixed now.
