### ISSUE TITLE
Why are keys following ^ (control) in upper case in Quick Reference Guide?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#1832]
The [Quick Reference Guide](https://www.visidata.org/man/) has inconsistent casing. Ordinary keys are case sensitive, but control keys are always capitalized? For example: 'g^C' . Not sure why?

**Comment by anjakefala** [comment]
It was an aesthetic choice, to go with the `Shift+` aesthetic. I felt that it allowed the user to better see the connection between e.g. `Shift+D` and `Ctrl+D`. It is also a style convention I noticed other publications following.

Quick example: https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-word-95ef89dd-7142-4b50-afb2-f762f663ceb2

**Comment by reagle** [comment]
Please re-open. The MS resource is consistent, visidata resources are not.

On Visidata, case is sensitive when distinguishing between `j` and `J`, but not for any character coming after `ctrl`.

It should be:

`J, shift+J, ctrl+J, ctrl+shift+J` (or all the "j"s could be lower case)

or

`j, J, ^j`

**Comment by reagle** [comment]
BTW  @anjakefala, I'm trying to create an Anki deck for visidata keyboard shortcuts.
