### ISSUE TITLE
Feature request: Save regex histories between different runs

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1834]
I like it when I use a command that asks for regex, and I can see the history of previous regexes I used. This saves me time.

I wish that this list would persist between VisiData runs.

Bonus points: Allow me to open that history list and see its contents rather than browse it line-by-line.

**Comment by geekscrapy** [comment]
I'm pretty sure that this is stored in a history attribute somewhere.
A sheet could then be build to list them.
Either that, or the inputs asking for regex could have a "ctrl+x" option to show a chooser sheet like we had a while back to select a historic regex

**Comment by saulpw** [comment]
This exists; set this in your .visidatarc:

```
options.input_history='~/.visidata/lastinputs.jsonl'
```

This is not set by default, because we have a general policy of not saving user input without their explicit opt-in.

**Comment by cool-RR** [comment]
Excellent, thank you!
