### ISSUE TITLE
Feature request: Optional zero-based numbering for plots

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1836]
I wish there was an option to start numbering for multi-column plots at 0. I've got columns like "agent_0", "agent_1", "agent_2" and it's quite frustrating to see them mapped to 1, 2 and 3.

**Comment by saulpw** [comment]
Do you mean the legend keys that enable/disable certain colors?  .  I've been frustrated by this too, sometimes I even rearrange the rows so the mapping makes more sense (they are assigned in the order they appear in the data).  Maybe if a shortcut appears in a column name, it could be assigned that way?  In any event, needs some design.

Kondo'ed for now.

**Comment by cool-RR** [comment]
I do mean the legend keys. What you propose is cool, but for starters I imagined a simpler solution: An option `plot_labels_start_at_zero` that defaults to `False`. It's possible that I have a volunteer who might implement this, and hopefully might work on other features and bugs later.

**Comment by saulpw** [comment]
I'm not sure about the `plot_labels_start_at_zero` option, but I'd love to chat with this volunteer, and see if we can't get something that works for you.

**Comment by cool-RR** [comment]
My personal workaround if it helps:

```python
# Monkeypatch to start legends at 0 rather than 1:
def plotlegends(self):
    from visidata.canvas import colors
    # display labels
    for i, (legend, attr) in enumerate(self.legends.items()):
        self.addCommand(str(i), 'toggle-%s'%(i),
                        'hideAttr(%s, %s not in hiddenAttrs)' % (attr, attr),
                        'toggle display of "%s"' % legend)
        if attr in self.hiddenAttrs:
            attr = colors.color_graph_hidden
        self.plotlegend(i, '%s:%s'%(i,legend), attr, width=self.legendwidth+4)
        
visidata.Canvas.plotlegends = plotlegends
```
