### ISSUE TITLE
http loader: Support disabling SSL verification 

### ISSUE THREAD

**Issue by dufferzafar** [saulpw/visidata#1839]
Something similar to:

```
curl -k <URL>

requests.get(url, verify=False)
```

https://stackoverflow.com/a/33770290

**Comment by anjakefala** [comment]
Can you walk me through your usecase? Why do you want to be able to disable SSL verification?

**Comment by geekscrapy** [comment]
> Can you walk me through your usecase? Why do you want to be able to disable SSL verification?

There are quite a few sources I would like to use this with as well. Internal servers and the like.
Current workflow is to use curl to grab the data then open it in vd

**Comment by saulpw** [comment]
Hm, interesting.  What if we were to disable SSL verification all the time?  Does it matter at all when downloading data?

**Comment by geekscrapy** [comment]
> Hm, interesting. What if we were to disable SSL verification all the time? Does it matter at all when downloading data?

Let's not do this please 🙃

**Comment by saulpw** [comment]
@geekscrapy I mean shouldn't it just give a warning?  Are you concerned that someone is going to MitM your .csv files and you won't notice?

**Comment by dufferzafar** [comment]
I for one have no issues disabling ssl verification by default. All my usecases of visidata are for internal csv where I'm not really concerned about MitM.

**Comment by geekscrapy** [comment]
> @geekscrapy I mean shouldn't it just give a warning? Are you concerned that someone is going to MitM your .csv files and you won't notice?

This is the reason SSL was introduced 🙃

Yes, I am worried, I actually *see* this stuff happening 😬. As a plus, I work with a lot of unsanitised data so noticing something like that might not rear its head for a while.

Can we have it per session? Toggled by an option? On by default! Like every other tool 😌

**Comment by saulpw** [comment]
Some tools only warn instead of refuse to connect :)  but okay, what would the option be called? `https_no_verify`?

**Comment by anjakefala** [comment]
If it was named `http_req_verify` would this just work? https://github.com/saulpw/visidata/blob/fd74d4c1fef44e4afb582a617d5c594365fe3d6a/visidata/loaders/http.py#L27 ?

**Comment by saulpw** [comment]
Oh I was even thinking of this case when I did that, but forgot to tag this issue.  Nice find, @anjakefala!  @dufferzafar can you use `http_req_verify=False` with the develop branch, and does that fix your issue?

**Comment by anjakefala** [comment]
As far as I can tell, setting `options.http_req_verify=False` on `develop` branch does the trick! I am going to close this issue, but please comment if you are still running into trouble or want to suggest something different.

**Comment by anjakefala** [comment]
Please note, the option got changed to `http_ssl_verify`.

Please see: https://github.com/saulpw/visidata/issues/1939
