### ISSUE TITLE
Visidata 1.3 a bit slow (on house pricing dataset)

### ISSUE THREAD

**Issue by JPFrancoia** [saulpw/visidata#184]
Hi,

First of all, I think visidata has some good potential. Following my comments here: https://github.com/TabViewer/tabview/issues/155#issuecomment-416278809, I'm opening an issue.

Visidata is a bit slow (I think) when scrolling my dataset. Meaning: there is a lag when a press a key and see the line moving up or down. My dataset is attached:

[housing.csv.zip](https://github.com/saulpw/visidata/files/2328242/housing.csv.zip)

It has 20,640 entries, and 10 columns (so not that much data).

As mentioned before, is it because of the architecture changes in V 1.3 ?

Also, small question: is there a way to display the index of the entries in a column (far left, like with tabview?). Very useful to identify problematic entries.

Cheers

**Comment by saulpw** [comment]
Hi @JPFrancoia, thanks for the bug report.  It should not be so slow on a plain .csv no matter the size of the data (once it's loaded).  In fact it is perfectly fine for me with that dataset.  What platform are you using (Mac, Linux, etc) and how fast is your computer?

As for the other question, you can make the current column a 'key' column with `!`.

**Comment by JPFrancoia** [comment]
Thanks for your answer.

I'm on Archlinux 64 bits (i7-6700 @ 3.40GHz), with 16 GiB of ram. It's not *that* slow, but if I press J for 2 seconds and release it, the cursor will still be moving for another 2 seconds.

> As for the other question, you can make the current column a 'key' column with !.

Ok maybe I expressed what I would like in a wrong way: can I display the line number?

**Comment by saulpw** [comment]
Hm, that is very weird.  I don't have that problem using that same dataset and I think your computer is even faster than mine.  One thing you can do, is press `Ctrl+_` (underscore) to toggle profiling on, then do your scrolling test (it should be even a bit slower with profiling enabled).  Then `Ctrl+T` to go to the Threads sheet, and press `Enter` on the main thread, which will take you to a sheet with the timings.  Then `Ctrl+S` to save it as .tsv and attach that .tsv here.  (You can also explore it yourself if you know how to interpret it.)

**Comment by saulpw** [comment]
Oh and it is not possible to display the row number yet.  It's a good feature request though, I think some other people might find it useful too.

**Comment by JPFrancoia** [comment]
Ok, I did the test you asked for:

[MainThread_profile.tsv.txt](https://github.com/saulpw/visidata/files/2339503/MainThread_profile.tsv.txt)

But I don't really know how to interpret it.

What I did is view my data set, scroll down with J pressed for a few seconds, waited a few seconds the cursor stopped moving, repeated that, and then exported the profiling.

**Comment by busyworker** [comment]
I'm experiencing a similar issue. When I try to scroll down by pressing j many times / holding it down, it lags for sometime and keeps scrolling until it reaches the needed number of presses even if I press Ctrl+C. I'm sshing through Kitty if it makes a difference (although I don't think it should)

**Comment by saulpw** [comment]
Thanks for the report, @busyworker.  I was just looking into this tonight.  I notice that @JPFrancoia is using the pandas reader; are you using pandas too?

**Comment by saulpw** [comment]
Thanks so much for these reports, that was a fun one to track down.  9dba108 should fix the pandas performance issue.  Btw, how do you use pandas with vd? Are you using it from the Python REPL?

**Comment by JPFrancoia** [comment]
It's indeed much faster!

To answer your question, I use it in the ipython shell. I initialize my pandas dataframe, and then I view it with vd. At the moment it's just for visualization.

Cheers!
