### ISSUE TITLE
fixed width saver truncates data if columns are not fully expanded

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1849]
**Small description**

If you save or syscopy a table as `fixed` format, and the visible column width is less than the width of the data in the column, the data is truncated. Also, the resulting file is not a valid fixed width format file as the columns are not aligned with the headers.

**Expected result**

Saving or copying a table when the columns are not fully expanded should yield the same result as when the columns are expanded.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/2499066/231616002-553a1a46-0b56-4950-b3eb-90507a77b823.png)

**Steps to reproduce with sample data and a .vd**
[test-vd-fixed.zip](https://github.com/saulpw/visidata/files/11217144/test-vd-fixed.zip)

**Additional context**
saul.pw/VisiData v2.11

**Comment by daviewales** [comment]
Hmm... Looking at the code, it looks like the truncation behaviour is intentional?
https://github.com/saulpw/visidata/blob/d40fc931fc63c72a7d94a00b1a818bb4ac24b13e/visidata/loaders/fixed_width.py#L87

I wouldn't normally expect a display mode to change the underlying data.

Also, I suspect there's something funny going on here, which is leaving us with a missing space in the truncated version:
https://github.com/saulpw/visidata/blob/d40fc931fc63c72a7d94a00b1a818bb4ac24b13e/visidata/loaders/fixed_width.py#L95

**Comment by saulpw** [comment]
Yes, this behavior is (somewhat) intentional; the widths of the columns indicate the fixed widths of the fields.  This is so you can set them precisely, in case the fixed file format has an exact specification.  I agree though that it's undesirable to have the data truncated otherwise.  What's the better thing to do here?  Find the max width and use it instead of the column width, if it's larger?  and warn or ask for confirmation if this is the case?

**Comment by anjakefala** [comment]
@daviewales, do you have a preference wrt:

> What's the better thing to do here? Find the max width and use it instead of the column width, if it's larger? and warn or ask for confirmation if this is the case?

**Comment by daviewales** [comment]
My preference would be to always use the true max width by default, so data is never truncated. Truncation could be a separate feature which you explicitly opt into. (Save view vs save data?)

Admittedly, my use case for this is non-standard.
I use the fixed width saver to paste tables into emails and into MS Teams within code blocks. (`gY fixed`)
They look beautiful, but it's a surprise when the data is truncated.

**Comment by anjakefala** [comment]
Okay, I pushed that change to `develop` @daviewales! Try it out, and let me know how it feels. =)

**Comment by daviewales** [comment]
Thanks @anjakefala. I've had a play, but it's not quite what I had in mind.
I've pushed a PR which better captures my intent: #1890
Try it out with `test-vd-fixed.tsv` in the attached zip from the first comment.

Both this:
<img width="527" alt="Screen Shot 2023-05-07 at 10 13 38 pm" src="https://user-images.githubusercontent.com/2499066/236676790-548dc1d9-33ed-4a30-aba6-06d8ac267cfc.png">
and this:
<img width="675" alt="Screen Shot 2023-05-07 at 10 14 09 pm" src="https://user-images.githubusercontent.com/2499066/236676810-285ce068-473d-4399-a1ab-d6b7d385806e.png">
save to the exact same output:
<img width="684" alt="Screen Shot 2023-05-07 at 10 15 25 pm" src="https://user-images.githubusercontent.com/2499066/236676895-661a0dd4-7a0b-42cc-b803-995d7bde61e5.png">

**Comment by geekscrapy** [comment]
Hey @daviewales ! Can you draw in ascii what you are intending to happen? With the example lines above?

**Comment by daviewales** [comment]
Hi @geekscrapy,

In ASCII:

```
# The original data
very_long_column_name                  another_long_column_name                    
very long data wider than the column   more very long data wider than the column   

# The view in visidata when columns are displayed narrower than the width of the data:
very_long_column_n…   another_long_colum…        
very long data wide   more very long data

# How visidata used to save this as .fixed
very_long_column_name another_long_column_name 
very long data wider more very long data  

# How anjakefala's patch saves it as .fixed:
very_long_column_name another_long_column_name 
very long data wider more very long data     

# How my patch saves it as .fixed
very_long_column_name                  another_long_column_name                    
very long data wider than the column   more very long data wider than the column   
```

Perhaps I have misunderstood how @anjakefala's patch works?

**Comment by daviewales** [comment]
Looking at the code in 77ae017377c79e4286da2fbddc1d88472b698916, I can see that if I set the sheet `default_width` to `0` using `zShift+O`, it will set the save width to the max width of the data rather than the width of the columns.

However, this has other side-effects. It's not something that you'd want to set in your `~/.visidatarc`.
(Columns resize to hidden, when all columns are hidden `self.cursorRowIndex` becomes `None`, which causes errors which prevent you from unhiding the columns from the columns sheet)

**Comment by saulpw** [comment]
> Columns resize to hidden

This is a bug; if `default_width` is 0 it should act as you suggest (always use maxwidth).

**Comment by daviewales** [comment]
I guess my issue is that I _like_ having `default_width` as 20. I just don't like my viewing choices to change how the data is saved unless I explicitly opt in to that.
