### ISSUE TITLE
Empty new sheet created from selected rows when using duckdb backend

### ISSUE THREAD

**Issue by radostyle** [saulpw/visidata#1855]
cat << EOF > /tmp/test.csv
col_one,col_two,col_three
first,second,third
fourth,fifth,sixth
EOF

pip install vdsql
pip install duckdb
pip install 'ibis-framework[duckdb]'

> Downloaded duckdb cli and unzipped from https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_cli-osx-universal.zip

./duckdb my.duckdb
create table ihub as select * from '/tmp/test.csv';
Ctrl-d to exit
vdsql my.duckdb

<img width="622" alt="image" src="https://user-images.githubusercontent.com/151909/210689546-cb518cd6-748a-413c-8b59-e9e3fcfbc672.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/151909/210689566-4fcdfb42-3648-4b76-93e6-df14d7e62ec1.png">

|f       to select rows with 'f' in them

<img width="623" alt="image" src="https://user-images.githubusercontent.com/151909/210689589-a36c83b9-4bfe-4905-a709-365f6614178c.png">

"        to create a new sheet from selected rows

<img width="623" alt="image" src="https://user-images.githubusercontent.com/151909/210689615-7fbd7af3-9c63-4caf-a387-5aa161a0db96.png">

Notice the table is empty

**Comment by radostyle** [comment]
This works in version v2.12dev.  Where it requires you to select a column as the key column before you can select rows.

**Comment by saulpw** [comment]
Hi @radostyle, this appears to be a bug in Ibis with the DuckDB backend, which I've filed (see above).  When it's fixed there, it should work in vdsql again.
