### ISSUE TITLE
Can't open duckdb file

### ISSUE THREAD

**Issue by radostyle** [saulpw/visidata#1856]
```
pip install vdsql
pip install duckdb
pip install 'ibis-framework[duckdb]'
# Downloaded duckdb cli and unzipped from https://github.com/duckdb/duckdb/releases/download/v0.6.1/duckdb_cli-osx-universal.zip
./duckdb my.duckdb
create table ihub as select * from 'messages3.csv'
Ctrl-d to exit
vdsql my.duckdb
```

I received error
"DBAPIError: (builtins.RuntimeError) IO Error: Trying to read a database file with version number 3"
in the UI

**Comment by radostyle** [comment]
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/151909/208228871-f2e40ea3-4230-4790-884a-352b9b2133db.png">

**Comment by saulpw** [comment]
Thanks for reporting this, @radostyle!  I'll be getting back into VisiData and friends again soon now that [Hannukah of Data](https://hanukkah.bluebird.sh) is finished.

**Comment by radostyle** [comment]
Looks like it was due to the new version of duckdb cli 6.1 mismatching to the version of duckdb python library that expects something created with duckdb 3.* 

If downloading the older cli from here and using that then it works
https://github.com/duckdb/duckdb/releases/download/v0.3.4/duckdb_cli-osx-universal.zip

**Comment by radostyle** [comment]
However it seems to limit to 500.  Not sure if there is a way to fix that.

**Comment by saulpw** [comment]
Hey @radostyle, glad you figured it out.  Yes, results are default limited to 500; you can load a fresh sheet with a new limit using `z"`.

**Comment by radostyle** [comment]
When the sheet with the new limit is created is it loading all of that into memory or is it something that gets added to the sql statements or something?

**Comment by radostyle** [comment]
I found a new issue when I tried to create a new sheet from selected rows and one of the columns is sorted
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/151909/210687098-ec8d671e-75e3-40f5-9158-37364254972a.png">

**Comment by saulpw** [comment]
> When the sheet with the new limit is created is it loading all of that into memory or is it something that gets added to the sql statements or something?

By default a `LIMIT 500` is added to sql statements; if you use `z"` it changes or removes the LIMIT.

**Comment by saulpw** [comment]
Thanks @radostyle!  The sort/filter issue should be fixed now too.
