### ISSUE TITLE
Identifiers need to be quoted in Postgres

### ISSUE THREAD

**Issue by cstork** [saulpw/visidata#1859]
Connecting to Postgres opens the PgTablesSheet successfully and I can navigate to tables with lower-case names.

When trying to access a table with a name that contains upper-case letters I get the error

> UndefinedTable: relation "something.thatwaspartiallycapitalized" does not exist

The reason, I suspect, is that vdsql/ibis does not by default (double)quote identifiers in Postgres. To be sure, all identifiers (schema name, relation name, column name) need to be properly double-quoted.

BTW, vdsql is absolutely mind-bogglingly great!  Thank you so much for all the work you're doing on visidata!

**Comment by saulpw** [comment]
Hm, I thought @cpcloud fixed this!  It might be an Ibis version issue.  I've been away for a bit working on [Hanukkah of Data](https://hanukkah.bluebird.sh/5783/), so now that's finished, I'll be getting back into vd and vdsql here shortly.

**Comment by saulpw** [comment]
This works in `vdsql` now (but not with the vd loader).
