### ISSUE TITLE
Hiding a column that is referenced by a generated column causes stack trace.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1861]
### Discussed in https://github.com/saulpw/visidata/discussions/1579

<div type='discussions-op-text'>

<sup>Originally posted by **frosencrantz** October 29, 2022</sup>

Since discussions are not setup on https://github.com/visidata/vdsql, I take it they should happen here.
One big question I have is what library is converting between python and SQL functions?  That is brilliant!

I did try using `vdsql` but had a couple issues.

3. Also, when adding a new column like `a.lower()` and then trying to hide `a`, and look at the side panel it says `name 'a' is not defined` and there is stack trace.</div>

**Comment by saulpw** [comment]
Thanks for reporting the issue, @frosencrantz.  Should be fixed now.
