### ISSUE TITLE
brew formula for vdsql

### ISSUE THREAD

**Issue by LiamKearn** [saulpw/visidata#1866]
As the title says, I'd guess we can't use `saulpw/homebrew-vd` since thats a different org/user on github.

**Comment by anjakefala** [comment]
`saulpw` is the creator / main maintainor of `visidata`! Brews for the plugins is a very interesting idea. 

Also, @saulpw maybe https://github.com/saulpw/homebrew-vd should move to be underneath the `visidata` org?

**Comment by LiamKearn** [comment]
> `saulpw` is the creator / main maintainor of `visidata`! Brews for the plugins is a very interesting idea.

Yup I figured based on commits! I was commenting along the lines of it might not be a good idea to host this orgs plugins on @saulpw's personal tap since that might confuse people looking for src.

> Also, @saulpw maybe [saulpw/homebrew-vd](https://github.com/saulpw/homebrew-vd) should move to be underneath the 
`visidata` org?

Agreed here, If this was done it's probably a wise idea to look into homebrew to see if it supports aliasing a tap prior since we don't want to cut off people using `saulpw/homebrew-vd`. I'd guess there are no homebrew statistics to see how many people are using it but I believe github offers insights on unique cloners.

**Comment by LiamKearn** [comment]
While we're discussing brew would we open to adding a HEAD to vd formulae? (build from head).

**Comment by anjakefala** [comment]
> While we're discussing brew would we open to adding a HEAD to vd formulae? (build from head).

I had no idea this was a thing! Of course! Either open a PR or open an issue in that repo. I will be updating the tap soon for VisiData v2.10, and can incorporate that in then.

**Comment by saulpw** [comment]
The repo has already been moved; github maintains a redirect for it.  saulpw/visidata should be the only VisiData repo that's hasn't been moved already.

And yes, let's add a brew tap for vdsql!  Feel free to submit and/or review a PR on the existing repo, and we'll merge it once it seems to work.

**Comment by LiamKearn** [comment]
Awesome, I'll have a look after work, no promises haven't worked with python env stuff in a hot minute. Thanks!

**Comment by anjakefala** [comment]
@LiamKearn If you decide not to work on it, even if you open an issue in `homebrew-vd` that would be helpful!

**Comment by anjakefala** [comment]
`vdsql` has been moved into the VisiData repo, and will be installed by the VisiData homebrew in the next release!

@saulpw please re-open if you think `vgit` or `vdsql` would benefit from their own homebrews or `.deb`.
