### ISSUE TITLE
sav loader throws Exception on Python 3.10+

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1867]
When loading a [`.sav` file](https://study.sagepub.com/aldrich3e/student-resources/ibm%C2%AE-spss-%C2%AE-sample-files) on Python 3.10+, you get the following stacktrace:

```
  File "/home/anja/anaconda3/envs/visidata/lib/python3.10/site-packages/savReaderWriter/__init__.py", line 138, in <module>
    from savWriter import *
  File "/home/anja/anaconda3/envs/visidata/lib/python3.10/site-packages/savReaderWriter/savWriter.py", line 8, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/anja/anaconda3/envs/visidata/lib/python3.10/collections/__init__.py)
```
Unfortunately this is happening because the `Iterable` abstract class was removed from collections in Python 3.10, and [savReaderWriter has not been updated to support Python 3.10]( https://github.com/fomcl/savreaderwriter).

`pandas` has added a [read_spss in 2.0](https://pandas.pydata.org/docs/reference/api/pandas.read_spss.html). I did a bit of research, and it in turn relies on [`pyreadstat`]( https://github.com/Roche/pyreadstat).

So my inclination is that we should switch to using `pyreadstat`. It seems more mature, and being a `pandas` dependency probably has more weight on it for ongoing maintenance.

**Comment by anjakefala** [comment]
Blech, it seems `pyreadstat` depends on `pandas`, and that it returns `pandas` dataframes. So maybe the best thing to do is to wrap `.sav` into the `pandas` loader?

**Comment by saulpw** [comment]
Wow, everything is terrible.  I guess let's roll it into the pandas loader.

**Comment by saulpw** [comment]
I don't see the `from collections import Iterable` line anywhere in the savReaderWriter repo:

https://github.com/search?q=repo%3Afomcl%2Fsavreaderwriter%20collections&type=code

Where did you install savReaderWriter from?  Can you provide the .sav you were trying to load?

**Comment by anjakefala** [comment]
The `.sav` I was trying to load is any of the ones in this zip file! https://study.sagepub.com/aldrich3e/student-resources/ibm%C2%AE-spss-%C2%AE-sample-files 

This is what I installed: https://pypi.org/project/savReaderWriter/. v3.4.2.

You are right! `savWriter.py` does not seem to have that line in the repo. I wonder if the PyPI is not actually the most "recent" version. I will try installing from the repo.

**Comment by anjakefala** [comment]
The PyPI actually links to this project: https://bitbucket.org/fomcl/savreaderwriter/src/master/.

Here it is: https://bitbucket.org/fomcl/savreaderwriter/src/03e436b2f19ec29dbe0713bd805b79430681f68a/savReaderWriter/savWriter.py#lines-8

Same author. They quietly moved the project to GitHub it seems.

I am going to test an older version of savReaderWriter.

**Comment by anjakefala** [comment]
The older versions are not installable with modern pip. We would need to fork the bitbucket software, and make the changes there.

**Comment by anjakefala** [comment]
I updated the dependency to use my fork, which supports Python 3.10+! I will add a basic test, and then close this.
