### ISSUE TITLE
[visibility-sheet] Causes traceback

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1874]
**Small description**
`visibility-sheet` causes traceback

**Expected result**
No tracback when making rows mult.

**Actual result with screenshot**

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/mainloop.py", line 38, in drawSheet
    sheet.draw(scr)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 705, in draw
    y += self.drawRow(scr, row, self.topRowIndex+rowidx, y, rowcattr, maxheight=self.windowHeight-y-1, **drawparams)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 767, in drawRow
    height = min(self.calc_height(row, displines), maxheight) or 1  # display even empty rows
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 732, in calc_height
    lines = _splitcell(self, cellval.display, width=colwidth-2)
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 133, in call_if_not
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 26, in _splitcell
    for L in s.splitlines():
AttributeError: 'generator' object has no attribute 'splitlines'
```

https://asciinema.org/a/S3OgdQfnBL8cyOL3TAfWMgDTI

**Steps to reproduce with sample data and a .vd**
While in a sheet, type `v`, and get multiple tracebacks due to issue.

**Additional context**
Please include the version of VisiData. Latest version from develop.

**Comment by anjakefala** [comment]
Thanks for filing an issue! 

We had a fix but it caused a problem with the sidebar, so we decided to not commit it to the repo. Still thinking about how to address this.

**Comment by frosencrantz** [comment]
I am glad to see new fixes being added to the develop branch.  This bug would also be very useful to fix if there is time.

**Comment by frosencrantz** [comment]
Looks like it was reported again  https://github.com/saulpw/visidata/issues/2019 but with  a possible  fix from @ajkerrigan (https://github.com/saulpw/visidata/issues/2020)  Hooray!

**Comment by ajkerrigan** [comment]
> We had a fix but it caused a problem with the sidebar, so we decided to not commit it to the repo. Still thinking about how to address this.

Heh looks like I missed multiple flavors of history when looking into this 🙈. What sort of sidebar issues though? Wonder if my PR would have similar effects.

**Comment by saulpw** [comment]
I believe this is fixed now.  Thanks to @ajkerrigan for providing the patch!
