### ISSUE TITLE
[sort] failure when interrupting a sort with another sort

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1878]
**Small description**
On a large dataset, if a sort direction is reversed while another sort operation is in progress, there will be a traceback, and the data will end in an inconsistent order.

**Expected result**
I expect the first sort command to stop, and the second sort to succeed.

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/sort.py", line 61, in sort
    self.rows.sort(key=lambda r,self=self,prog=prog: self.sortkey(r, prog=prog))
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/sort.py", line 32, in __eq__
    return other.obj == self.obj
AttributeError: 'str' object has no attribute 'obj'
```

**Steps to reproduce with sample data and a .vd**
Load a file with enough lines that sorting is noticeably slow (like a few hundred thousand lines) then hit `[` and quickly hit `]` while the first sort is not yet done.

**Additional context**
saul.pw/VisiData v2.11
saul.pw/VisiData v2.12dev

**Comment by saulpw** [comment]
This shouldn't be able to happen now since df4f51e884cd4e45faf88a2e6f2c24b9ec125c8f.  The sort commands now will only set the ordering while the sheet is loading, and one sort happens after loading is complete.
