### ISSUE TITLE
[sort] failure when sorting while a file is loading

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1879]
**Small description**
When I sort data with `[` before a file has finished loading, I get a traceback.

**Expected result**
Either the sort command should be queued to occur when loading is over, or the command should be rejected with an error message, as it does not make sense to sort data while it continues to be modified.

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/home/midichef/.local/lib/python3.10/site-packages/visidata/sort.py", line 61, in sort
    self.rows.sort(key=lambda r,self=self,prog=prog: self.sortkey(r, prog=prog))
ValueError: list modified during sort
```

**Steps to reproduce with sample data and a .vd**
Load a file with many lines (1 or 2 million lines works for me), then quickly hit `[` before the file has finished loading.

Please include the version of VisiData.
saul.pw/VisiData v2.11
saul.pw/VisiData v2.12dev

**Comment by saulpw** [comment]
This was fixed in df4f51e884cd4e45faf88a2e6f2c24b9ec125c8f along with #1148.  Commands that would spawn threads will fail if other threads are already running.
