### ISSUE TITLE
Enhancements to keyboard cheatsheets

### ISSUE THREAD

**Issue by deinspanjer** [saulpw/visidata#188]
Things I'm looking at as enhancements based on the work started in #160:

- [ ] Add checkbox/pushbutton to put the page into keyboard listening state
- [ ] Change state of display whenever one of the modifier keys are pressed (held?)
- [ ] Show summary and link to doc for action when key is hovered over

**Comment by saulpw** [comment]
BTW we migrated the www (including kblayout) to a new repo at saulpw/visidata.org, so submit PRs against its `master`.

**Comment by anjakefala** [comment]
Issue has been migrated to: https://github.com/saulpw/visidata.org/issues/7 since the files related to this issue have been moved there.
