### ISSUE TITLE
[develop] reading from stdin drops 32 bytes of data

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1880]
**Small description**
When reading data from standard input with no file type given, once the file is beyond a certain size, 32 bytes of data are lost.

**Steps to reproduce with sample data and a .vd**
`seq 2000 |vd` will have less than 2000 lines, but
`seq 2000 |vd -f txt` will have 2000 lines as expected.
`seq 1000 |vd` does not have the problem.

**Additional context**
saul.pw/VisiData v2.12dev
Ubuntu 22.04.2

The problem is in `guess_xls()` and `guess_sqlite()`. Each eats 16 bytes.

https://github.com/saulpw/visidata/blob/641bd058a358bb1c20a5167af530b6a85f6e22fc/visidata/loaders/xlsb.py#L7
https://github.com/saulpw/visidata/blob/641bd058a358bb1c20a5167af530b6a85f6e22fc/visidata/loaders/sqlite.py#L22

**Comment by saulpw** [comment]
Hmmm...each `open_bytes()` should return a fresh RepeatFile object with those bytes pre-loaded, so that they are returned before more bytes are gotten from stdin.  It's definitely a bug that this isn't the case.

e.g. `p.open_bytes().read(16)` should always return the first 16 bytes of the file.

**Comment by anjakefala** [comment]
I confirmed what @midichef is seeing, and that those two lines are the cause. It starts at 1893 rows.

**Comment by anjakefala** [comment]
@midichef This issue should now be resolved on `develop`!
