### ISSUE TITLE
[develop] STDIN redirections are guessed incorrectly as `tar`

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#1881]
```
vd < sample_data/sample.tsv
saul.pw/VisiData v2.12dev
guessed "tar" filetype based on contents
```

This is because [`if tarfile.is_tarfile(p.open_bytes())`](https://github.com/saulpw/visidata/blob/ae6bca7a9b82705f11cf1583f112ae714a323dc9/visidata/loaders/archive.py#L18) is returning `True`.

**Comment by ajkerrigan** [comment]
You know, I noticed the same weird tar-by-default behavior when trying to explore zip files (specifically, opening files inside Python wheels). I suspected it was something weird I did though :laughing: .

It looks like this makes things behave closer to what I'd expect, though I'm not sure it's the right/best change:

```diff
- if tarfile.is_tarfile(p.open_bytes())
+ if tarfile.is_tarfile(p)
```

**Comment by anjakefala** [comment]
Yup, that was the fix!

Thanks. =)

**Comment by saulpw** [comment]
If that works, great, but then we should still fix `p.open_bytes()` to do the right thing!

**Comment by anjakefala** [comment]
`p.open_bytes()` is doing the wrong thing here? What is the wrong thing that it is doing?

**Comment by saulpw** [comment]
Sorry, was conflating this one with the other issue.
