### ISSUE TITLE
[visibility-sheet] Extend column delimiters down for the height of the row

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#1893]
Column delimiters are only shown for the height of 1 row (as shown below, my column delimiters are red)

<img width="600" alt="image" src="https://github.com/saulpw/visidata/assets/11225502/68d28537-d41d-45b2-b66d-ff9bd02bb365">

I was trying to figure out why I was hard to differentiate between rows, and I think this is the reason. Especially when there is a lot of content in the cell

**Comment by geekscrapy** [comment]
To also assist, it would probably be a good idea to have a line at the bottom of the row when in `visibility-sheet` mode

**Comment by saulpw** [comment]
There are different separators; `disp_rowmid_sep` and `disp_rowbot_sep` are `⁝` by default.  Maybe that's not defined in your font?

This is how it looks for me (on develop):

![vd-multiline](https://github.com/saulpw/visidata/assets/236498/b11c5a8c-c99a-44ef-9a73-66a538ccb864)
