### ISSUE TITLE
[choices]  The size of the choices sheet should use as many rows as possible. 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1899]
The choices menu should use more lines of the screen.  This screen has 28 rows, and it only shows half of the 8 available choices.  

https://asciinema.org/a/hHyM3Moq3UvJ8LmvBJeu3FLcd

Could this line be removed or updated to use all of the screen?

https://github.com/saulpw/visidata/blob/develop/visidata/choose.py#L32

**Comment by saulpw** [comment]
Now using the input palette instead of the choices sheet as per #1027
