### ISSUE TITLE
slow navigation

### ISSUE THREAD

**Issue by Quaddroo** [saulpw/visidata#1903]
# Small description
Opening any file at all and pressing j or k, or other navigation keys - there is a delay. The delay is certainly small, but it is easily perceptible, especially to someone that is used to the terminal environment. If you perform the same action in sc, sc-im, vim, or basically any other TUI application, the movement will be instant, or imperceptible. Here it's maybe 60ms, somewhere in that range I think, but I can't figure out a way to measure it precisely. 
# Expected result
the movement occurs so fast I can't perceive any delay, it feels "instant"
# Actual result with screenshot - N/A
# Steps to reproduce with sample data and a .vd
it will work with any data and any file, it is unrelated to the data as far as I can tell.
I also really don't believe a commandlog is necessary - I'm really saying just regular movement is slightly slower than I expect it to be.
# Additional context
Python version: Python 3.7.3
Visidata version: saul.pw/VisiData v2.11
Debian 10
Intel i5
nothing else is relevant I think, the machine is not particularly underpowered, and nothing like this appears in other tools.

**Comment by saulpw** [comment]
> nothing else is relevant I think

VisiData version, Python version.  Please answer the questions in the [issue template](https://github.com/saulpw/visidata/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by anjakefala** [comment]
Hey @Quaddroo, do you mean there is a lag between pressing a movement key, and the cursor moving?

I have not been able to reproduce this, there is no delay that I can perceive. Can you please include the information @saulpw  requested? 

If we cannot reproduce with that version information, and you are comfortable with performance benchmarking tools, we might be able to interpret the log output to see the problem. Otherwise, I will be limited in how much I can help out. 

If you supply any new information, or if anyone else does, I will re-open the issue. Until then I will close with `can't reproduce`.

**Comment by Quaddroo** [comment]
> > nothing else is relevant I think
> 
> VisiData version, Python version. Please answer the questions in the [issue template](https://github.com/saulpw/visidata/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

Hey. I've updated the original post to fit the format - sorry I missed the format the first time around.

**Comment by Quaddroo** [comment]
> Hey @Quaddroo, do you mean there is a lag between pressing a movement key, and the cursor moving?
> 
> I have not been able to reproduce this, there is no delay that I can perceive. Can you please include the information @saulpw requested?
> 
> If we cannot reproduce with that version information, and you are comfortable with performance benchmarking tools, we might be able to interpret the log output to see the problem. Otherwise, I will be limited in how much I can help out.
> 
> If you supply any new information, or if anyone else does, I will re-open the issue. Until then I will close with `can't reproduce`.

Yes, I mean that which you wrote.

I'd love to help, but I could also use some pointers.  I performed a quick google search of "visidata performance benchmarking" and did not find anything that seemed relevant. If you could point me to just the name of a utility or a place I should read, that would help me a ton.

**Comment by saulpw** [comment]
I only see this navigation slowness with huge terminal sizes.  @Quaddroo what terminal size are you running VisiData with when you have this issue?  If you try it in something reasonable, like 80x25 or 132x50, does it go away?

Also, I wrote up a perf analysis document here:

https://github.com/saulpw/visidata/blob/develop/dev/perf-analysis.md

While writing it, I realized that it might be too involved for someone who's not steeped in Python development, but if you're interested, you could still give it a shot.  Your best bet is still to figure out a case that we can repro ourselves.

**Comment by Quaddroo** [comment]
Hey.
Just updated to the latest version. The (new?) sidebar seems to make it a lot slower - with it open, it is maybe 200ms on my system to navigate. With it closed, it is similar to before.

I can confirm that terminal size impacts what I'm observing. With a very small terminal it's fine - around 40x20. But to me that's a tiny size, not exactly reasonable? You mean columns x lines, right?

I'll get around to trying to fix this sometime, I'm documenting this so I know it when I get back to it.

I think it's likely you either don't notice the delay, or your machine is way more powerful than mine. Still, I don't think my laptop should be too old for a terminal application, haha.
