### ISSUE TITLE
[question] How do I guard a sheet from closing? 

### ISSUE THREAD

**Issue by Quaddroo** [saulpw/visidata#1904]
It takes a bare slip of the finger to close Visidata with the default configuration and lose potentially significant progress with no prompt and no way to undo it as far I can tell.

I would say this borders on an actual bug, no other software does this as far as I can tell, and it makes the software dangerous from my POV. 

This can probably be fixed with a clever-enough custom function, but I think it's a major feature that should be part of the main software.

**Comment by saulpw** [comment]
`--quitguard` or put `options.quitguard=True` in your .visidatarc.

**Comment by anjakefala** [comment]
Others asking similar questions:
*  https://github.com/saulpw/visidata/issues/1737
*  https://github.com/saulpw/visidata/issues/538

**Comment by frosencrantz** [comment]
You can enable it with the `File > Guard > on`  menu option.
