### ISSUE TITLE
insert - no command for key_ic

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#191]
Hope this is not a noob mistake, but the Insert key doesn't seem to change insert-mode, just gives error "no command for key_ic"

~ ᛝ vd -v   
saul.pw/VisiData v1.3.1

**Comment by saulpw** [comment]
Hi @blawiz, `KEY_IC` works in edit mode, which you can get into with `e` to edit the current cell.  There is no command for the Insert key outside of edit mode yet; what did you expect it to do?

**Comment by ghost** [comment]
Ah, so it was a noob mistake, sorry.
