### ISSUE TITLE
[loaders]  Support builtin data formats

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1910]
This is meant to be an aspirational wishlist request.  For developers who would like to contribute, this can be used as a map to what loaders could be added.

In https://github.com/saulpw/visidata/issues/1587#issuecomment-1369263933 it was suggested that:

> When Python includes the batteries, VisiData should as well.

This was within the context of talking about the new toml module data format.  If Python supports a data format it would be reasonable to expect that VisiData also supports that data format.

So I asked a generative chatbot what data formats the Python Standard Library module supports.  Below is the answer, some of these may work better as column formats than file formats.  And it likely missed some formats.  

There are some formats that are deprecated as described in [PEP 594] that do not make sense to include since they will eventually be removed from Python.

Other formats are useful as building blocks for other formats, like the email parsers can be used for email, but are also useful for things like Python METADATA files  (e.g. [Source distribution format])

[Source distribution format]: https://packaging.python.org/en/latest/specifications/source-distribution-format/)

[PEP 594]: https://peps.python.org/pep-0594

| Format | Module | Description | Documentation |
|--------|--------|-------------|---------------|
| CSV | csv | Comma Separated Values | [CSV Module Documentation](https://docs.python.org/3/library/csv.html) |
| JSON | json | JavaScript Object Notation | [JSON Module Documentation](https://docs.python.org/3/library/json.html) |
| XML | xml.etree.ElementTree | eXtensible Markup Language | [XML Etree Module Documentation](https://docs.python.org/3/library/xml.etree.elementtree.html) |
| HTML | html | Hypertext Markup Language | [HTML Module Documentation](https://docs.python.org/3/library/html.html) |
| INI | configparser | Configuration file format | [ConfigParser Module Documentation](https://docs.python.org/3/library/configparser.html) |
| Pickle | pickle | Python object serialization | [Pickle Module Documentation](https://docs.python.org/3/library/pickle.html) |
| ZIP | zipfile | Archive file format | [Zipfile Module Documentation](https://docs.python.org/3/library/zipfile.html) |
| TAR | tarfile | Archive file format | [Tarfile Module Documentation](https://docs.python.org/3/library/tarfile.html) |
| GZIP | gzip | Compression format | [Gzip Module Documentation](https://docs.python.org/3/library/gzip.html) |
| BZ2 | bz2 | Compression format | [BZ2 Module Documentation](https://docs.python.org/3/library/bz2.html) |
| LZMA | lzma | Compression format | [LZMA Module Documentation](https://docs.python.org/3/library/lzma.html) |
| Base64 | base64 | Binary-to-text encoding | [Base64 Module Documentation](https://docs.python.org/3/library/base64.html) |
| Structured Binary files | struct | Binary data manipulation | [Struct Module Documentation](https://docs.python.org/3/library/struct.html) |
| Email | email | Email message format | [Email Module Documentation](https://docs.python.org/3/library/email.html) |
| MIME | email.mime | Multipurpose Internet Mail Extensions | [MIME Module Documentation](https://docs.python.org/3/library/email.mime.html) |
| Python Code | ast | Abstract Syntax Trees | [AST Module Documentation](https://docs.python.org/3/library/ast.html) |
| Python Code | dis | Python byte code disassembler | [Dis Module Documentation](https://docs.python.org/3/library/dis.html) |
| Python Code | tokenize | Tokenizer for Python source | [Tokenize Module Documentation](https://docs.python.org/3/library/tokenize.html) |
| WAV | wave | WAV audio file format | [Wave Module Documentation](https://docs.python.org/3/library/wave.html) |
| Calendar | calendar | Calendar data and manipulation | [Calendar Module Documentation](https://docs.python.org/3/library/calendar.html) |
| Colorsys | colorsys | Color space conversions | [Colorsys Module Documentation](https://docs.python.org/3/library/colorsys.html) |
| URL | urllib.parse | URL parsing and manipulation | [Urllib.parse Module Documentation](https://docs.python.org/3/library/urllib.parse.html) |
| UUID | uuid | Universally Unique Identifiers | [UUID Module Documentation](https://docs.python.org/3/library/uuid.html) |
| IP Address | ipaddress | IPv4 and IPv6 manipulation | [IPaddress Module Documentation](https://docs.python.org/3/library/ipaddress.html) |
| Binary | binascii | Binary-to-ASCII conversions | [Binascii Module Documentation](https://docs.python.org/3/library/binascii.html) |
| Quoted-Printable | quopri | Quoted-Printable encoding and decoding | [Quopri Module Documentation](https://docs.python.org/3/library/quopri.html) |
| Apple plist | plistlib |  Apple .plist file format | [Plistlib Module Documentation](https://docs.python.org/3/library/plistlist.html) |
| Netrc | netrc | Netrc files format used by ftp | [Netrc Module Documentation](https://docs.python.org/3/library/netrc.html) |

**Comment by ssnkhan** [comment]
IP address is being progressed in https://github.com/saulpw/visidata/issues/1782

**Comment by saulpw** [comment]
Thanks @frosencrantz!  We'll of course entertain PRs for any formats or types, especially ones that are supported in the standard library.  Kondo'ing this for now.

**Comment by frosencrantz** [comment]
One more: robots.txt - https://docs.python.org/3/library/urllib.robotparser.html 

See: https://www.robotstxt.org/orig.html
