### ISSUE TITLE
(Unnecessary) hidden dependency on setuptools; debian package broken

### ISSUE THREAD

**Issue by LaPingvino** [saulpw/visidata#1911]
**Small description**

When installing visidata from the package-manager without having python3-setuptools installed, the following error appears when starting visidata:

```
Traceback (most recent call last):
  File "/usr/bin/vd", line 3, in <module>
    import visidata.main
  File "/usr/lib/python3/dist-packages/visidata/__init__.py", line 102, in <module>
    import visidata.main
  File "/usr/lib/python3/dist-packages/visidata/main.py", line 19, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```

**Expected result**

visidata starts normally

**Additional context**
Python 3.11.2
Visidata 2.11
Debian Sid ARM64 on Crostini (Chromebook)

The dependency is only invoked in main.py and help.py, mostly for displaying the provided help file. I don't think this justifies importing the whole setuptools universe, as the function is only used to find files in the installation directory.

**Possible fixes**
This has previously been fixed for Arch by adding setuptools to the dependencies.
Long term fix is probably not to rely on resource_filename instead, a possible backup for when setuptools is not installed is using something like https://stackoverflow.com/questions/5137497/find-the-current-directory-and-files-directory to figure out the directory the files are in to invoke the right help files.

**Comment by anjakefala** [comment]
Thanks to @zormit! This will be addressed in the next release.
