### ISSUE TITLE
Median calculation is unexpected when number of records is even

### ISSUE THREAD

**Issue by daviewales** [saulpw/visidata#1914]
**Small description**

The median is normally defined as the middle number of an odd set of ordered numbers, or the arithmetic mean of the two middle numbers of an even set of ordered numbers.

```
median([1, 2, 3]) == 2
median([1, 2, 3, 4]) == 2.5
```

Currently, visidata calculates the median by indexing the sorted list with `len() // 2` (integer division):
https://github.com/saulpw/visidata/blob/069fdbc124f039590340b7318cb2ffcc4b8fc8cb/visidata/aggregators.py#L95

This gives:

```
median([1, 2, 3]) == 2
median([1, 2, 3, 4]) == 3
```

Would it make sense just to use the Python built-in [statistics.median](https://docs.python.org/3/library/statistics.html#statistics.median) here? (For that matter, would it make sense to use the Python built-ins for the other aggregation functions?)

We could also add `median_low` and `median_high` as aggregators to return the lower or higher value rather than the average of the two middle values to match the functions in `statistics`.

Happy to submit a PR if it would be accepted.

**Comment by saulpw** [comment]
Hm, I always thought median_low was the proper median!  It makes no sense to me to have a "median value" that's not in the actual dataset.  But I guess that was just my misunderstanding.

It looks like we're already using `stdev` and `mode` from the statistics library, so it's easy enough to use `median` from there too.  I'd like to make a better aggregator selection dialog before we add all of them for completeness' sake, but if there are any others that you find yourself needing, feel free to submit a PR to add them specifically.

Thanks for filing the issue!

**Comment by daviewales** [comment]
Thank you!
