### ISSUE TITLE
[zip] open Parquet files from inside an archive

### ISSUE THREAD

**Issue by ajkerrigan** [saulpw/visidata#1916]
**Small description**

If we open a Zip file in VisiData and then try to open a Parquet file inside that Zip, the pyarrow.parquet reader looks for the file on the local filesystem _outside_ the zip.

**Expected result**

What happens in the Zip stays in the Zip. Or something.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

The screenshot is an empty sheet, which isn't super helpful.

**Steps to reproduce with sample data and a .vd**

Adapted from [here](https://github.com/saulpw/visidata/pull/1913#discussion_r1223267202):

Create a Parquet file, then add it to a zip in the same directory:

```
├── test.zip
│   ├── benchmark.parquet
benchmark.parquet
```

- Try to run `vd test.zip` and open the Parquet file inside. It should work.
- Quit VisiData and remove the Parquet file outside the zip.
- Try opening `test.zip` again and then the Parquet file inside. It should _not_ work anymore.

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.

**Comment by saulpw** [comment]
Thanks for the report, @ajkerrigan !  This would be useful, but I think it would be tricky without extracting the parquet file to disk first.  I think it's more of a wishlist item.  At best we could fail with a more appropriate error instead of trying to incorrectly read from the filesystem.

Kondo'ed for now.
