### ISSUE TITLE
Unable to use any commands that need input

### ISSUE THREAD

**Issue by 42triangles** [saulpw/visidata#1930]
**Small description**

As unhelpful as that is, I don't know what exactly was the thing that caused it; but at some point as soon as I tried running a command that requires any input, it just took an input I entered a few commands ago, so I wasn't able to input anything; and ended up being unable to save.

It happened with an input from `=` (adding a column with a Python script), if that helps?

I don't know how to reproduce this issue.

**Expected result**

Being able to enter something, at the very least for being able to save the results so I can open them up again.

I don't know how the internal logic for input works; but there should at least be some way of not losing all progress that was being made.

**Actual result with screenshot**

I sadly don't have a screenshot.

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

I have not been able to reproduce it.

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.

saul.pw/VisiData v2.11

Python 3.11.3

**Comment by saulpw** [comment]
Hi @42triangles, I'm sorry this happened to you.  Unfortunately I don't know how to diagnose this either.  I'll keep your request for some kind of auto-save in mind.  If it happens again (and especially if you get any kind of repro), please post here and maybe other people will have some ideas or similar reports.

**Comment by 42triangles** [comment]
Sorry for the late reply, will do!  

Seems unlikely that it will happen again because I don't often tend to do that kind of data wrangling like this, where visidata undoubtedly helped me immensely (minus the issue of it "soft crashing" that way ofc) though
