### ISSUE TITLE
Problem connecting to Mysql/MariaDB.

### ISSUE THREAD

**Issue by ManuGraiph** [saulpw/visidata#1932]
Hi!

I'm having some trouble connecting to a Mysql database. I've tested using a local db and a remote db with diff configuration, so, it's not a problem in the db i think.

I manage to open the connection and get the tables, but every single one of them is shown as empty and in the statusbar i'm getting the following error:

[pymysql.err.OperationalError] [2003, "Can't connect to MySQL server on -connection string here- [[Errno -2] Name or service not known]"] [Background on this error at: https://sqlalche.me/e/14/e3q8]

As i said, i guess the connection is fine since i can see the tables, but not their content, any idea what could it be?

Thanks in advance!

**Comment by saulpw** [comment]
Hi @ManuGraiph, there's not enough information here to diagnose your issue.  If you're still trying to figure this out, hop on our Discord at visidata.org/chat and let's get a sync conversation going.
