### ISSUE TITLE
[loader] RDATA

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#1940]
I need to use a data source now that's only available in RDATA format (i.e. the format used by the R programming language.) Here are the main 2 files: https://github.com/DomArchive/DomArchive/tree/master/data

Would be cool if VisiData could open those.

**Comment by saulpw** [comment]
I agree, @cool-RR!  How are you viewing them now?  Do you have a small snippet of Python code that can read an RDATA file into its constituent rows?

**Comment by anjakefala** [comment]
This is the list of stuff we request for help with for loader requests =) https://github.com/saulpw/visidata/blob/develop/.github/ISSUE_TEMPLATE/loader-request.md

- [X] A small sample representative dataset in that format.
- [ ] A basic Python script which queries and dumps the data (possibly using an external package).

**Comment by cool-RR** [comment]
@saulpw So far I've just inspected them using RStudio, but my trusty colleague ChatGPT whipped up some code for you: 

```
import pyreadr
result = pyreadr.read_r('dom.metadata.rdata')
df = result['dom.metadata']
print(df.columns.tolist())
print(df.head(3))
```

**Comment by saulpw** [comment]
Try adding `vd.view_pandas(df)` to that and it might just work!

If there's a non-dataframe (row-based) library, we could write a custom loader, but as long as we have the Pandas loader, we should just use it for columnar data like this.
