### ISSUE TITLE
[main] interactive batch mode fails when there is no data

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1943]
**Small description**
When -b and -i are combined but no sheets are loaded, visidata raises an error.

**Actual result with screenshot**
```
Traceback (most recent call last):
File "/home/midichef/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/main.py", line 376, in vd_cli
    rc = main_vd()
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/main.py", line 350, in main_vd
    vd.sheets[0].rows = visidata.UNLOADED
IndexError: list index out of range
```

**Steps to reproduce with sample data and a .vd**
`touch empty-cmd.vdj; vd -p empty-cmd.vdj -b -i`

**Additional context**
saul.pw/VisiData v2.12dev

There are two ways to fix the `IndexError`, I'm not sure which is right, so I listed them here:
https://github.com/midichef/visidata/commit/2c32516164533e0ac78968149173215fd50276f5

**Comment by saulpw** [comment]
Okay so that forced unload was unnecessary and incorrect, so I removed it.  Now we just need to handle #1992.
