### ISSUE TITLE
[forms]  Some UI issues with forms

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1947]
**Small description**
Several issues with develop version of forms.  
  - [X] When the input field over the statusbar is empty, and that field doesn't has focus the left hand side of the status bar shows
  - [x] When help is on you get both the sheet help and the input field help
  - [x] History only records the field that had focus when hitting Enter.
  

**Expected result**

- Statusbar on left does not show when there is an input field
- Only one help sheet is shown
- History includes details about all input fields.

**Actual result with screenshot**
https://asciinema.org/a/R0di0wpmWrYgJeOxemqCcDMQO
**Steps to reproduce with sample data and a .vd**

1. Get a long sheet name.
2. Do a search
3. Use Tab to switch between fields
4. Use CtrlG to turn on help

**Additional context**
Please include the version of VisiData and Python.  Latest develop version. Python: Python 3.9.2

**Comment by saulpw** [comment]
The input help (enabled with `options.disp_help=2`) has been moved to the sidebar, so there's no longer any competition between help windows.  `Ctrl+G` should cycle through the various help panels: the sheet-specific  help, the input-specific help, and the general input help.
