### ISSUE TITLE
Tables are shown empty on Mysql DB

### ISSUE THREAD

**Issue by ManuGraiph** [saulpw/visidata#1948]
Hi!
I'm trying to connect to a mysql db, the connection works and i can see the tables on it, but all of them are shown as empty, any idea what could it be?

**Comment by saulpw** [comment]
Hi @ManuGraiph, I would need a lot more information than this to diagnose.  If you're still trying to figure this out, hop on our Discord at visidata.org/chat and let's get a sync conversation going.
