### ISSUE TITLE
Support for snappy compression format ?

### ISSUE THREAD

**Issue by mycaule** [saulpw/visidata#195]
Hello following #112, I wanted to open a parquet file using

```
$ vd -f pandas myfile/snappy.parquet 
...
  File "/home/michel/.local/lib/python3.6/site-packages/fastparquet/compression.py", line 144, in decompress_data
    (algorithm.upper(), sorted(decompressions)))
RuntimeError: Decompression 'SNAPPY' not available.  Options: ['GZIP', 'UNCOMPRESSED']
```

How can I use it with Snappy compression?

Thank you.

**Comment by anjakefala** [comment]
Hi! 

From what I gather from:
https://github.com/dask/fastparquet/issues/366
and
https://github.com/dask/fastparquet/issues/142

This could be an issue where either:
* snappy was not compiled correctly;
* a namespace conflict where you have multiple packages installed named 'snappy'.

I hope exploring those two avenues fixes your problem. =)

**Comment by mycaule** [comment]
I haven't installed snappy python package actually.

**Comment by mycaule** [comment]
It works thank you `pip3 install python-snappy`
