### ISSUE TITLE
Can't open the clickhouse example 

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/visidata#1953]
This thread started here: https://github.com/saulpw/vdsql/issues/33

@anjakefala, thank you for the quick answer.

> * vdsql has been moved to the [core VisiData repo](https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql). Please reinstall it from there. There are lots of updates there to fix the problems you are seeing with the clickhouse loader.

> * you will need at least Python 3.9. [ibis-framework](https://github.com/ibis-project/ibis), the most important dependency of the project, dropped support for https://github.com/ibis-project/ibis/pull/6491.
> * The test url is now clickhouse://play:clickhouse@play.clickhouse.com/?secure=1

I tried Python 3.9 and 3.10. I tried to use a Linux machine with an Intel processor.

I installed vd: `pip3 install git+https://github.com/saulpw/visidata.git@develop`

I tried to connect to another clickhouse instance (which I was able to connect succesfuly using DBeaver).

Nothing worked. What else can I try?

Suggested by you address gives me this error even before showing me a list of tables:

`vd -f ibis clickhouse://play:clickhouse@play.clickhouse.com/?secure=1` 

<img width="1322" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/cf7821a3-14c9-4750-930e-4f8443a0b474">

and 

`vd -f ibis clickhouse://explorer@play.clickhouse.com:9440/?secure=0`

gives me the error when I open the `recipes` table:

```
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/visidata/threads.py", line 200, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/visidata/sheets.py", line 235, in reload
    for r in self.iterload():
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/vdsql/clickhouse.py", line 39, in iterload
    for row in self.query_result:
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/clickhouse_driver/util/helpers.py", line 16, in chunks
    item = list(islice(it, n))
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/clickhouse_driver/client.py", line 213, in iter_receive_result
    for rows in result:
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/clickhouse_driver/result.py", line 114, in __next__
    packet = next(self.packet_generator)
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/clickhouse_driver/client.py", line 220, in packet_generator
    packet = self.receive_packet()
  File "/Users/user/miniconda3/envs/p310/lib/python3.10/site-packages/clickhouse_driver/client.py", line 237, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 26.
DB::ParsingException. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '1'. Stack trace:

0. ./build_docker/./src/Common/Exception.cpp:92: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e32b635 in /usr/bin/clickhouse
1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::ParsingException::ParsingException<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000e3914fd in /usr/bin/clickhouse
2. ./build_docker/./src/IO/ReadHelpers.cpp:0: void DB::readQuotedStringInto<false, String>(String&, DB::ReadBuffer&) @ 0x000000000e380760 in /usr/bin/clickhouse
3. ./build_docker/./src/Core/BaseSettings.h:820: DB::TCPHandler::receiveQuery() @ 0x0000000014c77de0 in /usr/bin/clickhouse
4. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::receivePacket() @ 0x0000000014c6e32e in /usr/bin/clickhouse
5. ./build_docker/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x0000000014c65750 in /usr/bin/clickhouse
6. ./build_docker/./src/Server/TCPHandler.cpp:2045: DB::TCPHandler::run() @ 0x0000000014c7bbb9 in /usr/bin/clickhouse
7. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000017bc3c54 in /usr/bin/clickhouse
8. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x0000000017bc4e71 in /usr/bin/clickhouse
9. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000017d41b27 in /usr/bin/clickhouse
10. ./build_docker/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017d3f55c in /usr/bin/clickhouse
11. ? @ 0x00007fd70835a609 in ?
12. __clone @ 0x00007fd70827f133 in ?
```

**Comment by maxim-uvarov** [comment]
In all the cases that I described previously, I also installed vdsql using the command in README:

`pip3 install git+https://github.com/visidata/vdsql.git`. Which, probably, I shouldn't have done (please remove this section from the [readme](https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql) file then).

However, when I use vd after executing `pip3 install 'ibis-framework[clickhouse]'`, it gives me such error:
```
❯ vd -f ibis clickhouse://play:clickhouse@play.clickhouse.com/?secure=1
saul.pw/VisiData v2.12dev
no loader for url scheme: clickhouse
```

**Comment by anjakefala** [comment]
>pip3 install git+https://github.com/visidata/vdsql.git. Which, probably, I shouldn't have done (please remove this section from the [readme](https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql) file then).

I'm so sorry, this is indeed wrong. We need to update that. That is the archived repo, and not the current repo.

```
git clone git@github.com:saulpw/visidata.git
cd visidata/visidata/apps/vdsql
pip3 install .
```

**Comment by maxim-uvarov** [comment]
@anjakefala thank you so much. I'm sorry for not being skilled enough to understand these basics.

Now I did
```
git@github.com:saulpw/visidata.git
cd visidata/visidata/apps/vdsql
pip3 install .
```

and both commands 
- `vdsql clickhouse://play:clickhouse@play.clickhouse.com/?secure=1`
- `vd -f vdsql clickhouse://play:clickhouse@play.clickhouse.com/?secure=1`

are giving me this error when I open the recipies table:

<img width="1267" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/f67ba979-263a-42a0-8e2e-07467eed1dae">

Is anything that can be done here on my side?
thank you!!! 🙏

**Comment by anjakefala** [comment]
@maxim-uvarov You are totally fine!! `vdsql` is in a liminal space. It is much younger than VisiData, and has pretty big dependencies which are changing their API at a pretty rapid pace. This means there are some kinks to iron out.

What level of comfort do you have with debugging Python environments? I am going to write out some things to check, but if your comfort is low, please feel free to ask me for more detailed help.

The dependencies are a little confusing, and I think this might be a dependency version problem. 

Can you try: `pip3 install "clickhouse-connect[arrow,numpy,pandas]==0.6.4"` and `pip3 install clickhouse-driver==0.2.6`? And let me know how that goes?

**Comment by maxim-uvarov** [comment]
> What level of comfort do you have with debugging Python environments? I am going to write out some things to check, but if your comfort is low, please feel free to ask me for more detailed help.

I'm comfortable to figure it out:)

> Can you try: pip3 install "clickhouse-connect[arrow,numpy,pandas]==0.6.4" and pip3 install clickhouse-driver==0.2.6

It didn't help.

My steps were:

I set up a fresh Ubuntu instance inside new VM. There was no python. 
I installed miniconda. I created an env with python 3.10 inside. 

I installed vdsql from the repository. `pip install .`
I installed vd from the repository. `pip install .`
I did `pip3 install "clickhouse-connect[arrow,numpy,pandas]==0.6.4"`
and `pip3 install clickhouse-driver==0.2.6`

And the problem persists with the same error 
<img width="720" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/7fb2cbe0-e164-4195-a592-696cabef7ca7">

<img width="1638" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/22614257-3436-405c-be2e-28b57e7def5a">

What's next?

**Comment by ajkerrigan** [comment]
I'm seeing the same issue on my end. Not being super familiar with ibis _or_ clickhouse, i started following breadcrumbs to see where things seemed to be going off the rails. And it looks like...

- vdsql gets a connection using `ibis.connect()` [here](https://github.com/saulpw/visidata/blob/34808745232e798b0f25e893bb444fc9f3c034eb/visidata/apps/vdsql/_ibis.py#L90)
- under the hood, ibis calls out to _clickhouse_connect_ to [get a client](https://github.com/ibis-project/ibis/blob/c27a42f901c81fa1d961c65e8b8094a5765d83b3/ibis/backends/clickhouse/__init__.py#L178C6-L189), which produces a `clickhouse_connect.driver.httpclient.HttpClient` object
- this all works fine for initially loading the sheet, but then diving into a row tries to query the underlying ibis backend
- as part of that dive vdsql tries to [call `execute_iter`](https://github.com/saulpw/visidata/blob/34808745232e798b0f25e893bb444fc9f3c034eb/visidata/apps/vdsql/clickhouse.py#L37), which doesn't exist on `clickhouse_connect.driver.httpclient.HttpClient` but _does_ exist on `clickhouse_driver.client.Client`

As for the fix, eh... really not sure :-/. Maybe we expect the ibis clickhouse backend to return a client from `clickhouse_driver` rather than `clickhouse_connect`? Or maybe we shouldn't expect `execute_iter()` to exist on whatever we get back? ...and it's always possible these are all red herrings and there's a more sensible place to be looking.

...all that aside, I'm seeing the same issue and happy to test/tweak things if it'd be helpful.

**Comment by anjakefala** [comment]
Hi @maxim-uvarov! We just merged the change that would hopefully resolve this problem.

Are you able to update your VisiData clone (`git pull`), and go through the re-installation again? I think should fix your problem!

**Comment by maxim-uvarov** [comment]
Hurray! It seems like it works with the playground example. I will battletest it soon.
Thank you, guys!
