### ISSUE TITLE
[guess] file guessing code fails for stdin, as RepeatFile behaves like a text file, not binary

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1957]
**Small description**

**Expected result**
When visidata tries to read a binary file from stdin, the sheet gives errors and opens an empty sheet.

**Actual result with screenshot**
The output from `vd --debug` is:
```
guess_csv: 'utf-8' codec can't decode byte 0x82 in position 16: invalid start byte
guess_html: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
guess_json: 
guess_jsonla: 
guess_sqlite: startswith first arg must be str or a tuple of str, not bytes
guess_xls: startswith first arg must be str or a tuple of str, not bytes
guess_zip: seek() takes 2 positional arguments but 3 were given
unknown "" filetype
opening - as txt
```

The guess_csv errors come from trying to interpret binary data as utf-8 text.
The guess_sqlite errors come because `.startswith()` is being called on a string (that was read from a file opened in text mode), but here it should be called on bytes (that would be obtained when reading a file in binary mode).

I got more detail on the guess_zip error by creating a traceback in `RepeatFile.seek()`:
```
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/loaders/archive.py", line 13, in guess_zip
  if not p.is_url() and zipfile.is_zipfile(p.open_bytes()):
File "/usr/lib/python3.10/zipfile.py", line 206, in is_zipfile
  result = _check_zipfile(fp=filename)
File "/usr/lib/python3.10/zipfile.py", line 192, in _check_zipfile
  if _EndRecData(fp):
File "/usr/lib/python3.10/zipfile.py", line 271, in _EndRecData
  fpin.seek(-sizeEndCentDir, 2)
```
So the problem with `seek()` not having enough arguments comes from `RepeatFile.seek()` being called by `zipfile` as `seek(offset=-22, whence=2)`. `RepeatFile.seek` does not expect whence, since it does not implement seeking relative to the end of the file.

**Steps to reproduce with sample data and a .vd**
`cat sample_data/color-merged-cells.xlsx |vd --debug`

**Additional context**
saul.pw/VisiData v2.12dev
Python 3.10

**Comment by saulpw** [comment]
Hm, doesn't this seem kind of reasonable?  If we open an unknown binary file on the CLI (not from stdin), it shows it as a text file, isn't this the same?  I'm not sure creating a new sheet is the right thing here.

**Comment by saulpw** [comment]
Thanks, @midichef !  I believe this issue is fixed as of your PR.
