### ISSUE TITLE
Current HEAD zsh-completion.py needs option_aliases update

### ISSUE THREAD

**Issue by dbaynard** [saulpw/visidata#1959]
**Small description**

`option_aliases` was removed in ce497f444db6d2f3fc0b8309f5ca839196c33c8b but is still referred to in the zsh completion code.

https://github.com/saulpw/visidata/blob/34808745232e798b0f25e893bb444fc9f3c034eb/dev/zsh-completion.py#L11C41-L11C41

I think the script needs a slight rejig to use the (present) `vd` import instead.

I wonder whether this can be included in future CI?

**Expected result**

The command succeeds.

**Actual result**

```
       > /build/visidata-src
       > Traceback (most recent call last):
       >   File "/build/visidata-src/dev/zsh-completion.py", line 11, in <module>
       >     from visidata.main import option_aliases
       > ImportError: cannot import name 'option_aliases' from 'visidata.main' (/build/visidata-src/visidata/main.py)
```

**Steps to reproduce**

```
python dev/zsh-completion.py
```

**Additional context**
~~Please include the version of VisiData and Python.~~

https://github.com/saulpw/visidata/tree/34808745232e798b0f25e893bb444fc9f3c034eb but I listed the commit above that causes the breakage — I suspect this is a two minute fix for somebody familiar with the codebase, though not me. I can help with extending CI, though it might just be a case of adding

```yaml
    - name: Ensure VisiData can create completions
      run: python dev/zsh-completion.py
```

(I guess you might want to run a linter, instead.)

**Comment by dbaynard** [comment]
I'm also seeing failing tests, but my build tooling isn't letting me past this so I can't check whether they're still broken on develop: `describe-through`, `histogram`, `petsdiet` and `remove-errors`.

```
AttributeError: 'NoneType' object has no attribute 'erase'
```

**Comment by anjakefala** [comment]
Could you please open a PR with the fixes you mention?

The zsh plugin has not been added by the maintainers, and we are not in the best place to update it ourselves. We appreciate it if the community can help out.

**Comment by anjakefala** [comment]
Ah, I see, the problem was an API change on our end. I will take a look before the next release.

**Comment by dbaynard** [comment]
I'm just making the zsh change, now — I think it may be fairly small.

Edit — yes, and the tests aren't broken.

**Comment by dbaynard** [comment]
(I only tested the development version because I wanted to use light theme, which I don't think is available in a released version, yet. Glad I did!)

**Comment by anjakefala** [comment]
:clap:

**Comment by anjakefala** [comment]
:100:

**Comment by dbaynard** [comment]
Incidentally, as soon as I opened the file, https://github.com/microsoft/pyright complained at me about the invalid import. It's probably better than _just_ trying to build the completions… but for now this should at least catch regressions.
