### ISSUE TITLE
Support JSON dicts in other sheet types

### ISSUE THREAD

**Issue by wpietri** [saulpw/visidata#196]
Thanks for this amazing tool!

From a logging system, I have a TSV dump that includes a log timestamp and a JSON dict of data. I expected I would be able to use the `(` command to expand the column with the JSON dict, but it doesn't do anything.

As a simple example, consider `example1.json`:
```
{"a": 1, "b": 2}
{"a": 2, "b": 3}
```
Visidata opens that file and automatically expands the columns.

It does this just fine with nested data, as in `example2.json`:
```
{"a": 1, "b": 2, "c": {"d": 3, "e": 4}}
{"a": 2, "b": 3, "c": {"d": 4, "e": 5}}
```

When I open that, it shows the a and b columns expanded, and c collapsed but recognized as a dict. If I navigate to c and hit `(` it expands `c` into `c.d` and `c.e`, which is exactly what I want.

However, consider `example3.tsv`:
```
seq	data
1	{"a": 1, "b": 2}
2	{"a": 2, "b": 3}
```

What I'd like visidata to do is to recognize that the `data` column is a dict, allowing me to press `(` on it so as to end up with three columns, `seq`, `data.a`, and `data.b`. But currently that does nothing, and I can't find a way to ask visidata to treat the data column as a dictionary.

**Comment by saulpw** [comment]
Hi @wpietri, thanks for the suggestion.  I can see trying to incorporate this functionality to `(` in the future. In the meantime, try `=eval(data)`, and then `(` to open the resulting dict.  This takes advantage of the fact that JSON dict strings are (usually) also Python dict strings.  Let me know if this works or doesn't for you.

**Comment by wpietri** [comment]
Ah, slick. I figured I wasn't the first person with this use case. I'll try it out! Thanks for the speedy suggestion.

**Comment by wpietri** [comment]
Alas, this doesn't work for me in that there are `null` values in the json. I'll just turn the whole file into JSON rather than having the mix, so I'm good to go, but I appreciate the suggestion. Thanks again.

**Comment by saulpw** [comment]
I don't know why I didn't think of this before, but you can also do `=json.loads(data)` which should be able to parse any JSON you can throw at it.  Hopefully this helps others too.
