### ISSUE TITLE
[options/forms] Provide per-option help text

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1961]
The `develop` branch VisiData can now show help at the user input prompt.  The input for regex pattern flags have details about what the different flags are.

It would be great if there was per option help when doing input for the options sheet.  There are many options that are color, it would be useful if there was color-specific help for those.  For values that take date formatting options, it would be helpful if there was help about what the different formats are.  This could be used for any similar options.

**Comment by saulpw** [comment]
That's a great idea, @frosencrantz.  Help boxes everywhere!

**Comment by saulpw** [comment]
Okay, I added the framework for per-option extra help, with the format strings filled out, and `HELPTODO` stubs for the rest:

- [ ] visidata/aggregators.py:vd.help_aggrs = 'HELPTODO'
- [ ] visidata/features/join.py: vd.help_join = 'HELPTODO'
- [x] visidata/color.py:vd.help_color = 'HELPTODO'
- [x] visidata/path.py:vd.help_encoding = 'HELPTODO'
- [x] visidata/path.py:vd.help_encoding_errors = 'HELPTODO'
- [x] visidata/text_source.py:vd.help_regex = 'HELPTODO'

I'd love some 'help' with writing these!

**Comment by saulpw** [comment]
vd.help_join part of #2313 now
