### ISSUE TITLE
loading large sheets is occasionally slow and nonresponsive

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1964]
**Small description**
About 1 out of 10-20 times I run visidata, the file is slow to load and the screen is totally blank and nonresponsive during loading.

**Expected result**
I expect the usual loading behavior during loading:  the screen appears, "loading" is shown, and the percentage of the file updates as the file loads.

**Actual result with screenshot**
But 1 out of every 10-20 times, the loading seems to hit a rough patch. The file takes 3-5x as long as usual to load. The screen starts out completely blank, and stays blank during that entire loading period. It is also nonresponsive, neither Ctrl-C or Ctrl-Q have any effect. Then after a long delay, the sheet finally appears, fully loaded with rows of data, and Visidata can be used as usual.

**Steps to reproduce with sample data and a .vd**

I can trigger it with this:
```
python -c 'for _ in range(1_000_000): print("1,2,one,two,three,four,five")' > bigfile.csv
while true; do; vd -N bigfile.csv; sleep 0.1; done
```
To quickly check for the problem, I run the while loop and hit `Ctrl-Q` in the first few seconds if I see Visidata draw any text to the screen. I.e. if it says "loading" and updates the progress percentage, I hit Ctrl-Q to quit and try again. What I'm looking for is a long pause with a blank screen, lasting more than a few seconds.

The effect seems easier for me to reproduce with this larger, more complicated file:
```
wget https://github.com/datablist/sample-csv-files/raw/main/files/customers/customers-2000000.zip
unzip customers-2000000.zip
while true; do; vd -N customers-2000000.csv; sleep 0.1; done
```

One observation: the nonresponsive time does seem to scale with the size of the CSV.
For this file with 2M rows, [datablist's customers-2000000.zip](https://github.com/datablist/sample-csv-files/raw/main/files/customers/customers-2000000.zip) normal loading takes 14 seconds. Buggy loading takes 56 seconds.
For similar test data with half the number of rows, [datablist's customers-1000000.zip](https://github.com/datablist/sample-csv-files/raw/main/files/customers/customers-1000000.zip), it's about half as long:  normal loading takes 7 seconds, buggy loading takes 24 seconds.

And I suspect there are other ways to trigger the problem than CSV data. I have the same blank nonresponsive screen if I try to load a large JSON file that is not actually JSON:
```
seq 1000000 > not-json.json
vd -N -f json not-json.json
```
That's a bit harder to trigger though. It can take up to 100 runs to trigger the problem with that data.

**Additional context**
Ubuntu 22.04.2
visidata 2.11.1 or  latest develop version
Python 3.10.12

**Comment by saulpw** [comment]
Good characterization, @midichef, I'm sure I've seen this myself.  I'm betting it has to do with one or more of the `vd.sync()` calls stepping on each other.  I would love if we could figure out what's causing this and get a fix for it.

**Comment by midichef** [comment]
I'm looking into it. I'll update when I have more clarity on what's happening.

**Comment by midichef** [comment]
Okay, after studying a lot of logs of events in different threads, I finally got to the bottom of this bug. This is a fun one.

**Repro for demonstration**
In normal visidata, the original bug happens on my system maybe 5-10% of the time. Once I understood why it was happening, I created a pathological loader that coordinates timing with the display code, to make it happen every time: https://github.com/saulpw/visidata/commit/897aed5abb797d2f6a8db3eba1dfdb55eb9bdeed
Test it by creating an empty file called `a.slow` and running `vd a.slow`. The screen should stay blank for several seconds, and then a sheet with many rows will appear fully loaded.


**Walkthrough of the thread interactions causing the bug**
When a sheet is being loaded, there are two threads. One for the main loop that is displaying the sheet, and one for the sheet loader, running `reload()`.

In the main loop, when it's time for the display to calculate the column widths, `getMaxWidth()` runs and starts looking at the rows. Critically, every now and then, something unusual happens: when it counts the rows for the first time, there are only a small number, at most 1000. It starts looking at all the rows one by one and measuring the cells precisely. That is a relatively time-consuming task. Sometimes it takes long enough that before it can finish, `getMaxWidth()` must pause, while execution gets handed off to the thread that is loading rows.

In that other thread, `reload()` keeps adding new rows quickly. The problem is that it adds them to the end of the very same list that `getMaxWidth()` is working through! `reload()` eventually pauses because it is forced by the thread scheduler to make time for the main loop. But it has added a lot of rows, more rows than `getMaxWidth()` will work through in its next interval of execution.

The two threads take turns running like this: `getMaxWidth()` slowly examines a few rows, and `reload()` quickly adds a lot of rows. And every time `getMaxWidth()` resumes, it has more and more rows to work through.

Eventually, the loader thread reads the last rows from the file. Then it ends, and the main loop becomes the only thread to run. `getMaxWidth()` continues uninterrupted until it finishes processing every single row in the sheet. While that drags on, the main loop can't draw the screen or respond to keys. For a million rows, that can last tens of seconds.

And that's the problem. It's as if under rare conditions `calcColLayout()` is replaced by `calColLayout(); time.sleep(self.nRows/50000)`

The crucial condition that triggers the bug is:  when `draw()` runs `getMaxWidth()`, the number of rows that has been loaded is small (at most 1000), but still large enough to take some time for `getMaxWidth()` to work through. And that's somewhat rare. But luckily not too rare to track down!


**The fix**
It is simple enough, make sure `getMaxWidth()` keeps its own separate list of rows. https://github.com/saulpw/visidata/commit/f8eaa565353cda79534eae8debd19c2cc94a0ada


**Related problems**
The problems in this code could have shown up in another way that is more subtle, and probably very rare. A sheet's columns could have different widths each time a file loads. I've been able to construct a two-column test case to reproduce that. The rare condition that makes that happen is, when it comes time to measure the max width of each column in `calcColLayout()`, only a few ~~columns~~ rows are loaded for the first column, but for the second one, many are loaded. @saulpw, maybe you have run into that behavior before, though I would expect it to be very rare. In any case, my proposed fix also fixes that as well.


**Broader issues**
This is likely not the only subtle threading bug that is in Visidata. Perhaps we should put systematic thread-safe protection around the key data structures that visidata uses? Preventing these kind of timing bugs will be particularly important for replay scripts.

However, I am not informed enough to recommend a solution. The little that I know about Python threads, I have learned in the last week and a half while looking into this bug.

**Comment by saulpw** [comment]
Wow @midichef, amazing detective work, and great writeup!  We'll definitely take your fix.

I agree there could be other similar issues.  I think if we want a broader fix, we could wrap `draw()` or `drawSheet()`with a timeout so that worst case it only draws part of the screen, instead of hanging outright.  I don't believe these issues should cause any problems with replay though, at least in batch mode where there is no display thread (and all commands should be run in the single main thread too).

As for systematic thread-safe protection, that's what the GIL is for :)  Note that the behavior isn't actually data-incorrect (it doesn't lose rows or corrupt anything), and it eventually completes, so it's officially "thread-safe", even if the actual timing is undesirable.  So I think we should fix these as they come up, and not worry about making it perfect, unless a simple small-code solution presents itself.

**Comment by aborruso** [comment]
thank you very much @midichef

**Comment by midichef** [comment]
A timeout around `draw()` would be a good fix, and very robust.

Yes, good point, it's true that there is no data corrupted or lost. As long as the issues are confined to the display, desigining explicit data-access synchronization would be a lot of complexity and risk, for very little benefit.

**Comment by saulpw** [comment]
Looks like adding a timeout to `draw()` would be [tricky](https://stackoverflow.com/questions/6947065/right-way-to-run-some-code-with-timeout-in-python): a signal-based approach wouldn't work on windows, and any more general solution would require at least another thread, if not another subprocess.  I don't think it's worth the complication at this point; I'd rather fix the underlying issues as they come up.

Thanks again for fixing the original issue, @midichef!
