### ISSUE TITLE
[file system] allow deleting of directories that are not empty 

### ISSUE THREAD

**Issue by charris-msft** [saulpw/visidata#1965]
I can browse the file system and easily delete files, but if I mark a directory for deletion that is not empty then press `zCtrl+s` I get an error: `OSError: [Errno 39] Directory not empty: 'parent/directory'

I don't know if this scenario applies to committing a delete in a non-filesystem context, but perhaps since I am already confirming via the delete confirmation dialog box, visidata could handle the error and tell me that the directory is not empty and prompt me a 2nd time? 

![image](https://github.com/saulpw/visidata/assets/74415662/587c8b50-813b-4ef1-8a7f-f3a5dc33d6a1)

**Comment by saulpw** [comment]
Hi @charris-msft, thanks for the suggestion.  I think it makes sense, though we could also consider just recursively deleting the whole directory.  It seemed like too much of a footgun in the first place, but I think it would fit in with the general VisiData ethos.

The mechanism you describe would be more difficult, as the confirm is handled in `Sheet.commit()` which runs in the main (UI) thread, whereas the exception is raised from `Sheet.putChanges()`, which runs in a separate thread, so as to not freeze the UI. I also wonder about having multiple confirm dialogs, and how many is too many.

I'd love to get peoples' opinions on which one makes more sense!

**Comment by charris-msft** [comment]
@saulpw - I should have said that personally, my preference is to just perform the delete with a single confirm dialog, but I was trying to make it a bit safer for folks who are used to working in linux and have to pass the `-r` flag to `rm`. Now I think I was over-thinking it. 

It seems there are plenty of safeguards in place already. After I press `d` to mark a directory for deletion I still have to press `zCtrl+s` and then approve the confirm dialog before anything is actually deleted.

**Comment by saulpw** [comment]
Okay, I'm a little wary of this one, but it's something I've wanted too.  Hopefully no one shoots their foot off.
