### ISSUE TITLE
[input/help] Help for input is sticky position, and doesn't turn off

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1971]
**Small description**

Help for input is sticky position, and doesn't turn off

**Expected result**
Help is in a fixed position relative to the input field or in a fixed position.  It is possible to toggle the help with Ctrl-G

**Actual result with screenshot**

https://asciinema.org/a/2c4TKwqjfzJRTWDKGyJ0bjMfD

**Steps to reproduce with sample data and a .vd**

Go to an input field hit the `e` command, hit Ctrl-G, help shows up.  Hitting Ctrl-G does not turn off help.

**Additional context**
Please include the version of VisiData and Python.  Latest develop branch.  with Python 3.9.2

This might be connected to the last item in https://github.com/saulpw/visidata/issues/1947

EDITED: Added comment about related issue.

**Comment by frosencrantz** [comment]
I got lost in reporting the issue.  @saulpw I had not noticed the help for input mode until recently.  This is a great addition. Thank you!  I think this can be helpful to all users.  I don't know all the keys for input mode.

**Comment by saulpw** [comment]
Yeah we only turned it on by default recently.  I'm not sure what to do about it, because it gets in the way for me to have it on by default.  I'm thinking maybe `options.help` could an int, with `1` being the sidebar, and `2` given menu help.  Or maybe it should be a string/bitmask?

**Comment by frosencrantz** [comment]
I think it would be ok with a bitmask or string.  If it is an option for users, I like a string with simple keywords that control the different help options.
