### ISSUE TITLE
[repeating actions] A feature to remember and offer to apply some basic actions to columns with the same names?

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/visidata#1974]
@saulpw, have you considered remembering applying same column types and aggregations (and other basic actions) for specific columns in files with the same column name sets?

Column name sets can be considered as a fingerprint that identifies a common data type file. When VisiData opens a new file, it can check its column set to see if similar files have been manipulated in VisiData before. If there were files with the same set of column names, VisiData can offer to apply the same kind of manipulations to the current file. 

This issue might be related to already discussed ones:
- https://github.com/saulpw/visidata/issues/1681
- https://github.com/saulpw/visidata/discussions/1488
- https://github.com/saulpw/visidata/discussions/1969

**Comment by saulpw** [comment]
As per #1488, I added a `Sheet.knownCols` property, to specify properties of known columns, in visidatarc:

    Sheet.knownCols.timestamp.type = date
    Sheet.knownCols.timestamp.fmtstr = '%H:%M:%S'

which will set the `type` and `fmtstr` of any column named "timestamp" after the sheet finishes loading.

This manual configuration in visidastarc is the simplest solution for this issue. Saving metadata presets for a whole sheet, to be applied to other data sources, would probably be better handled with .vds metadata-only files, as suggested in #892. Let's give this a try for now and see how far it gets us. Maybe we can add some "AI" that notices when you've applied the same metadata multiple times to the same-named column, and then automatically adds it to the knownCols in your .visidatarc.
