### ISSUE TITLE
[sorting]  Stack trace when sorting a column with different type

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1987]
**Small description**
Stack trace when sorting a column with different type

**Expected result**
Sorting can handle different types when sorting.

Maybe when the types can't be compared, the code should failover to changing the sort key into a tuple: `(type, value)` so that all strings are sorted, and all lists are sorted.

**Actual result with screenshot**

https://asciinema.org/a/6sIS2S0ka5qMyJcWBfm3kRRnq

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/sort.py", line 61, in sort
    self.rows.sort(key=lambda r,self=self,prog=prog: self.sortkey(r, prog=prog))
TypeError: '<' not supported between instances of 'str' and 'list'?
```
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

```
vd sample_data/benchmark.jsonl
```

Then  sort the `Customer` column `[` or `]`

**Additional context**
Please include the version of VisiData and Python.
Latest develop version.
Python 3.9.2

**Comment by ajkerrigan** [comment]
I could see a friendlier error here perhaps, but automatically sorting across types that don't have a defined sense of ordering feels pretty risky.

Having a column sort "just work" when you've got string and list values feels more surprising than getting an error.

**Comment by saulpw** [comment]
I think I agree, @frosencrantz's idea of autoconverting to `(type, value)` is clever, but perhaps too clever, and might yield surprising (and subtly inaccurate) results.  Remember that you can use `~` to convert a column to string type, which guarantees it will be sortable.

+1 for friendlier error if someone wants to submit a PR.

**Comment by frosencrantz** [comment]
While I agree the sorting order might not make much semantic sense,  I think it has a practical use.  By sorting by type, Visidata would group rows by type, and that is useful in both understanding the data and for filtering the data.  

Originally, I was surprised that Visidata hadn't just converted the list values to the string type as part of sorting. As part of trying to explain why this is a real bug, it feels to me that providing a simple way to sort by type would be helpful.

Also, part of the reason I reported this was I thought this error would also apply to how VisiData deals with sorting None types vs other values.  It is not clear to me if  there is a bug there, and if  not, why not. I wasn't able to quickly reproduce this case.

The suggested solution while converting to string type is not as useful if the values to sort are numeric, since you need to sort, filter, and then sort again.

**Comment by saulpw** [comment]
VisiData does sort `None` values (and error values), because it uses `getTypedValue`, which uses `wrapply`, which returns a TypedWrapper in the case of None and error, and TypedWrappers are comparable with any type.  This would be a bug if it could not.

If the values to sort are numeric, then you can set the column to a numeric type first; values which can't be converted will be errors, which again are sortable as per above.

And of course you can create a new column for the type if you want: `=builtins.type(colname)`.  (You can't use `=type(colname)` because `type` refers to the actual column type).

**Comment by frosencrantz** [comment]
Yesterday I was trying to use the `type()`  builtin and it was not working.  And I see what you mean about the numeric columns, that sorts fine even with non-numeric values.  I tried `builtins.type(colname)`, but you cannot sort types 😄, but you can covert those to strings `=str(builtins.type(colname))`  and then sort.

@saulpw, thank you for your reply it  helps me understand what is happening, and I have some new tricks to work with.
It does make sense to improve the error message with some suggestions for handling the error.
