### ISSUE TITLE
[sheet naming] Diving into a json object adds a list index.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#1988]
**Small description**
Diving into a json object adds a list index.

**Expected result**
No `[INDEX]` is added to the sheet name.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**

https://asciinema.org/a/4Zhdtdvw0Sk7WX30fwlUTC2D6

```
$ jo a=1 b=2 c="$(jo d=4 e="$(jo f=6 g=7)")" | jq .
{
  "a": 1,
  "b": 2,
  "c": {
    "d": 4,
    "e": {
      "f": 6,
      "g": 7
    }
  }
}
$ jo a=1 b=2 c="$(jo d=4 e="$(jo f=6 g=7)")" | vd
```

When diving into the dicts `zCtrl+Y`  `pyobj-cell` the sheet name includes indexes `-[0].c[1].value`

When using `Enter` `open-row` the sheet naming ends only with underscores: `-[]_c_e_`

The sheet name should better match the naming seems like it should be more consistent.  Also, it should be more consistent with the name you would get with the columns  `c.d`

I listed this as a bug, but I realize this should be categorized as a `wishlist`

**Additional context**
Please include the version of VisiData and Python.
Latest `develop` version.
Python 3.9.2

**Comment by saulpw** [comment]
Okay, I made the sheet names be more similar.  This might break some cmdlogs.

**Comment by frosencrantz** [comment]
Thanks, @saulpw!  It is  nice to see more consistency.
