### ISSUE TITLE
[mainloop] early pressed arrow keys are parsed as 'Alt+', '[', 'A'

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#1993]
**Small description**
Right when visidata is starting up, if I quickly press any arrow key, let's say `Up`, the key is handled as three individual keystrokes:
`^[` `[` `A`, so the response is:
`no command for "Alt+["` in the status history, and then a new sheet opens in response to `A`, since the command run is `open-new`.

**Expected result**
I expect `go-up` to run.

**Additional context**
visidata 2.11.1 or develop
Ubuntu 22.04.2
Python 3.10.12

**Comment by midichef** [comment]
To home in on the problem, I made a stripped down version of the visidata mainloop. It only does curses initialization and handles key input. It runs no extra threads.
https://github.com/midichef/visidata/tree/curses_test
To test for the bug, I run `python tests/test_curses_mainloop.py` and hold `Up` during the hardcoded 1-second startup time.

I was able to get some improvement by discarding all keyboard input right after initializing curses, by doing `drainPendingKeys()` or `curses.flushinp()`. That lessens the chances of the first `Up` arrow key being read as `^[` `[` `A`. But it does still happen, about one in five times.

My next step is to look at other projects that use `getch()` and `get_wch()` and see how they handle early keyboard input. This seems like a problem that is probably discussed somewhere with a simple solution, but I haven't been able to find it yet.

After that maybe I will script the input to the terminal to control its precise timing. Maybe once I know how to trigger the problem and how not to, I'll get a clue of how to fix it.

**Comment by saulpw** [comment]
I added a `curses.flushinp()` at the end of `initCurses()` and I don't see this issue anymore.  If this still comes up, please try changing that to `vd.drainPendingKeys(); vd.pendingKeys.clear()`, though that should be equivalent anyway.

Closing for now, please comment if you are still seeing this issue.
