### ISSUE TITLE
Detect utf8/utf16 Byte-Order-Marker and set encoding

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#200]
In `Path.open_text`, autodetect UTF-16 Byte-Order Marker (BOM) and set encoding on file accordingly.

**Comment by anjakefala** [comment]
This issue has been added to our [someday/maybe list](https://github.com/saulpw/visidata/blob/develop/dev/ROADMAP-someday.md). If anyone wants to take it on, they are welcome to reopen the issue.

**Comment by daviewales** [comment]
The someday/maybe link above is broken. Is it perhaps
https://github.com/saulpw/visidata/blob/stable/dev/WISHLIST.md
?

**Comment by anjakefala** [comment]
@daviewales, instead of writing things to the list, we changed strategies to just filtering by the wishlist label! Fewer steps. =)

**Comment by saulpw** [comment]
Now that we have a separate `options.save_encoding`, I changed the default for `options.encoding` to `utf-8-sig` which should detect the BOM and skip it.

**Comment by Shahin-rmz** [comment]
Hi, I am not sure if my issue is here in right place.
an old user of Visidata here.
I am trying to copy some rows in German to clipboard and I get this error.

```
copying 1 rows to system clipboard as tsv                             │
saving 1 sheets to /tmp/tmpo2rldvpn.tsv as tsv                        │
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in  │
position 294: surrogates not allowed                                  │

```

As far as I see, there is no problem in opening the file, how ever the ö,ä,ü,ß characters can not be shown, which is ok. but I can not copy and paste to the clipboard because of this error.

**Comment by daviewales** [comment]
@Shahin-rmz, you might not get much visibility on a closed issue. Perhaps post a reproducible example as a new issue?

Ideally, attach a file which exhibits the issue.
