### ISSUE TITLE
[...] No ellipses character

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#2005]
**Small description**
I believe there used to be a ellipses character (...) at the end of the visible cell content if the full content could not be shown. In the latest version this has disappeared. In the example below in the `Customer` and `Item` column:

![image](https://github.com/saulpw/visidata/assets/11225502/5e329359-a7ad-42b1-8937-2b7631f80c5c)

**Expected result**
To show the ellipses character when there is more data in the cell that can be shown

**Actual result with screenshot**
See above

**Steps to reproduce with sample data and a .vd**
`vd --config=/dev/null https://raw.githubusercontent.com/saulpw/visidata/develop/sample_data/benchmark.csv`

**Additional context**
v2.12dev

**Comment by saulpw** [comment]
Yeah I broke this a few months ago.  I've looked into it a couple of times without success.  Maybe @midichef would dig into this?  I think it goes along with #1918 too.

**Comment by saulpw** [comment]
Should be fixed now.
