### ISSUE TITLE
vgit broken in visidata v2.11.1

### ISSUE THREAD

**Issue by filbranden** [saulpw/visidata#2007]
**Small description**
Running vgit breaks with:

```
Traceback (most recent call last):
  File "bin/vgit", line 4, in <module>
    from visidata.apps.vgit.main import vgit_cli
ModuleNotFoundError: No module named 'visidata.apps'
```

Importing module `vgit` fails the same:

```
$ python3
Python 3.10.12 (main, Jun 12 2023, 08:09:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vgit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/vgit/__init__.py", line 1, in <module>
    from visidata.apps.vgit import grep, abort, statusbar, config, branch, remote, blame
ModuleNotFoundError: No module named 'visidata.apps'
>>>
```

Looks like this was fixed in commit 3fa124c038143197317526f98d3e6ed4c946ebdb, but this commit didn't make it to the v2.11.1 release. Can we get a new release that would fix this please?

cc @anjakefala 

**Additional context**
visidata v2.11.1 installed from PyPI
Python 3.10.12

**Comment by anjakefala** [comment]
> Can we get a new release that would fix this please?

This is aimed to be part of 3.0! It is part of a major release bump. 

Are you able to install VisiData off of the develop branch in the meanwhile?
