### ISSUE TITLE
Visidata is now available on NixOS

### ISSUE THREAD

**Issue by CMCDragonkai** [saulpw/visidata#201]
https://github.com/NixOS/nixpkgs/issues/48852

To install just use `nix-env -i visidata`.

The package set is not yet released but will be on the latest one. Not a problem if you are using the latest package set directly and not through a channel.

**Comment by anjakefala** [comment]
Oh! This is exciting! =)

Thank you for driving this @CMCDragonkai and to @7c6f434c for packaging it.

I am going to leave this open until I had a chance to take a deeper look and then potentially add it to our install info.

^_^

**Comment by anjakefala** [comment]
Added to the website: https://github.com/saulpw/visidata.org/commit/6e00fd4d9d3eb2c8194eea4ec3a04de3c7d2ad02

Will be visible the next time the website is deployed. =)
