### ISSUE TITLE
[indexsheet]  The `g<` or `g<` keyboard commands not working without command name

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2011]
**Small description**
The indexsheet.py adds `g<` and `g>`  keyboard commands that do not work.

**Expected result**
The commands do something

**Actual result with screenshot**
https://asciinema.org/a/LHr1J0AZck9ncjnKXTI4qXRMI

No stack trace.  Just a message saying `no command for "g<"`

**Steps to reproduce with sample data and a .vd**

`vd sample_data/bencmark.csv`

Type `g<` or `g>`

Notice that commands are listed in help.

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**

Please include the version of VisiData and Python.
Python 3.9.2
VisiData latest develop branch
https://github.com/saulpw/visidata/blob/develop/visidata/indexsheet.py#L97-L98

**Comment by anjakefala** [comment]
Thanks @geekscrapy! The longnames were missing. I also added very basic error handling. You need to have an index sheet as a parent, like `employess.sqlite` or a Sheets Sheet with multiple sheets to play with this feature.

Could you screenshot where you saw this command in the help page?

**Comment by frosencrantz** [comment]
The screenshot shows the help sheet issue which is now gone:

https://asciinema.org/a/LHr1J0AZck9ncjnKXTI4qXRMI?t=15.5&speed=.1

I found the short cuts in the source code.  :)

Thanks @anjakefala!
