### ISSUE TITLE
[csv] Text formats save displayed values instead of raw typed values

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#2014]
When I save a file in which I have applied some display option, the output is not the raw data, but the data that I see on screen.

I have in example these options:

```
options.disp_float_fmt = '{:,.02f}'
options.disp_int_fmt = '{:,}'
```

Using these I see the number `1370` as `1,370`. If I save as CSV I have `1,370` in the CSV and not the input and raw value that is `1370`.

**Expected result**

To save the raw data and to have `1370` in the CSV.

**Actual result with screenshot**

![image](https://github.com/saulpw/visidata/assets/30607/19bcb2d5-c027-420e-83c7-589bed3133ec)

![image](https://github.com/saulpw/visidata/assets/30607/36a8f778-3e29-4c6f-8e6e-692d6c054cbc)

![image](https://github.com/saulpw/visidata/assets/30607/2df0c151-ccc6-4ea2-9869-218cb75ff960)

**Steps to reproduce with sample data and a .vd**

Use these options

```
options.disp_float_fmt = '{:,.02f}'
options.disp_int_fmt = '{:,}'
```

Then

```
echo '{"a": 1370}' | vd -f jsonl
```

And then save it as CSV file.

**Additional context**

- saul.pw/VisiData v2.11
- Python 3.9.2

**Comment by saulpw** [comment]
This is by design.  Text formats like csv will show what is displayed.  If you want to save the raw data, you would need to use a typed format like JSON.

**Comment by aborruso** [comment]
> This is by design. Text formats like csv will show what is displayed. If you want to save the raw data, you would need to use a typed format like JSON.

Ok, then the display options are not display options if you save as CSV.
In my opinion if those are display options, they should have nothing to do with the content of the saved data.
At least by default.

And the user may have the opt-in option, to save not typed format in the format you see on the screen.

In any case, all clear, now I know, thanks

**Comment by saulpw** [comment]
> Ok, then the display options are not display options if you save as CSV.

Well, how would you get it to save a csv with different precision, if the display format didn't change it?  Also I know that the `disp_` options are usually cosmetic and don't affect saving data, so I can see why this would be confusing.  Maybe the options should be renamed since they can affect the saved data.

**Comment by aborruso** [comment]
> Well, how would you get it to save a csv with different precision, if the display format didn't change it? 

In the same way vd do for the typed fields format (as json).
Or does it change the saved data for the typed fields format too, if I set a precision display option?

> Also I know that the `disp_` options are usually cosmetic and don't affect saving data, so I can see why this would be confusing. Maybe the options should be renamed since they can affect the saved data.

That would probably be better, but I don't have any clever ideas for a new name.

**Comment by aborruso** [comment]
I'm adding a related thing about field type and display option.

I have this a.jsonl file

```
{ "id": 1, "name": "andy" }
{ "id": 2003, "name": "bandy" }
```

and b.jsonl one

```
{ "id": 1, "color": "yello" }
{ "id": 2003, "color": "orange" }
```

And I have these display options:

```
options.disp_float_fmt = '{:,.02f}'
options.disp_int_fmt = '{:,}'
```

If I open the files `vd a.jsonl b.jsonl` and then I do a inner join using `id` field I have this error: `ValueError: invalid literal for int() with base 10: '2,003'`

![image](https://github.com/saulpw/visidata/assets/30607/b0aa481f-8684-4248-adb0-995f11879594)

**Comment by saulpw** [comment]
This is definitely a separate issue, join should work with the typed values, not the display values.

**Comment by aborruso** [comment]
> This is definitely a separate issue, join should work with the typed values, not the display values.

Thank you. I have created a new [issue](https://github.com/saulpw/visidata/issues/2015).
