### ISSUE TITLE
Excel (xls, xlsx) files have no column names in the header

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#202]
Hi,
I have [this](https://github.com/saulpw/visidata/files/2537991/a.xlsx) input file.

If I run `vd a.xlsx` and open the sheet inside I have the header cells values are row values and not header values.

![image](https://user-images.githubusercontent.com/30607/47845337-06f7d080-ddc5-11e8-8fe4-3c0a337c767f.png)

But I think it should be in this way.

![image](https://user-images.githubusercontent.com/30607/47845140-7f11c680-ddc4-11e8-9fd1-9bbdf825dcae.png)

I have openpyxl 2.4.11 and and visidata 1.4.

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, this is because Excel sheels can have any number of headers and it is impossible to know how many there are.  You can ["hoist" the current row into the header with `g^` and then `d`delete the row](https://jsvine.github.io/intro-to-visidata/basics/working-with-excel/) to get the result you want.

**Comment by aborruso** [comment]
@saulpw a feature requests: enable `--header=int` option also for xls and xlsx.

Thank you

**Comment by saulpw** [comment]
This is also addressed in v1.5 with the `--header` option (defaulting to `1`).

**Comment by aborruso** [comment]
@saulpw  I'm very happy, I feel myself an influencer :D :D :D 

Great, thank you

**Comment by aborruso** [comment]
Hi @saulpw ,
when I open the sheet inside [this xls](https://github.com/saulpw/visidata/files/2649133/mr.zip) file it has no column names.

I'm using vd 1.5.

Thank you



![image](https://user-images.githubusercontent.com/30607/49519450-4a9c9900-f8a1-11e8-83cc-54fbefa355f3.png)

**Comment by saulpw** [comment]
This works for me.  Could you try with current develop branch?  If that works, then this will be fixed in 1.5.1.

**Comment by aborruso** [comment]
hi @saulpw I'm not able to install and use vd via pip visidata, I have always python environment problem (not able to solve [this](https://github.com/saulpw/visidata/issues/192)).

The the way for me to have an update version is only to use the [deb version](https://github.com/saulpw/deb-vd/).

Than I cannot make any test with develop branch :(

**Comment by saulpw** [comment]
@aborruso did 1.5.1 fix this issue for you?

**Comment by aborruso** [comment]
@saulpw  I have always the same :(

```
Traceback (most recent call last):
  File "/home/andybandy/miniconda3/bin/vd", line 152, in <module>
    main()
  File "/home/andybandy/miniconda3/bin/vd", line 130, in main
    vdtui.run(*sources)
  File "/home/andybandy/miniconda3/lib/python3.6/site-packages/visidata/vdtui.py", line 2838, in run
    ret = wrapper(cursesMain, sheetlist)
  File "/home/andybandy/miniconda3/lib/python3.6/site-packages/visidata/vdtui.py", line 2828, in wrapper
    return curses.wrapper(setupcolors, f, *args)
  File "/home/andybandy/miniconda3/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/andybandy/miniconda3/lib/python3.6/site-packages/visidata/vdtui.py", line 2825, in setupcolors
    return f(stdscr, *args)
  File "/home/andybandy/miniconda3/lib/python3.6/site-packages/visidata/vdtui.py", line 2851, in cursesMain
    return vd().run(_scr)
  File "/home/andybandy/miniconda3/lib/python3.6/site-packages/visidata/vdtui.py", line 866, in run
    keystroke = self.getkeystroke(scr, sheet)
  File "/home/andybandy/miniconda3/lib/python3.6/site-packages/visidata/vdtui.py", line 734, in getkeystroke
    k = scr.get_wch()
AttributeError: '_curses.window' object has no attribute 'get_wch'
```
