### ISSUE TITLE
[Loader] .rec loader fails to load files with valid %sort field

### ISSUE THREAD

**Issue by DefaultGen** [saulpw/visidata#2022]
visidata fails to load valid .rec files with the legal field "%sort: <fieldname>"

```
%rec: Item
%type: Expiry date
%sort: Title

Title: Emergency Rations
Expiry: 10 August 2009

Title: First Aid Kit
Expiry: 2 May 2009

Title: Liferaft
Expiry: 2 March 2009
```

This file would fail to load with an error "No column matching "Title". To be clear visidata already ignores and deletes all of these special fields when loading a .rec file, so I wouldn't expect it to sort anything, just to not hang up on it. It looks like vd does try to sort though and it fails.

<img width="838" alt="sort_err" src="https://github.com/saulpw/visidata/assets/706002/061e18c1-822e-43d1-a5f0-3691d3fe6f5f">

Recreated on Windows 11 and Arch Linux, Visidata v2.11.1, Python 3.11.3.

**Comment by saulpw** [comment]
Thanks for the issue, @DefaultGen!  Should be fixed now.
