### ISSUE TITLE
Adding rows to a join sheet

### ISSUE THREAD

**Issue by whatisaphone** [saulpw/visidata#2024]
If you open a join sheet according to [these docs](https://www.visidata.org/docs/join/), you can press `a` to add a new row, but when you try to fill it with data you get errors. It would be handy if you could add new rows that propagate back to the source sheets. (Hopefully it's clear what I'm talking about, if not I can write out an example)

**Comment by anjakefala** [comment]
@whatisaphone Which source sheet would it propagate back to?

**Comment by whatisaphone** [comment]
Ok sorry yeah that wasn't very clear. Say you have these two files:

**one.csv**

```csv
key,col1
1,a
2,b
```

**two.csv**

```csv
key,col2
1,x
2,y
```

In VisiData join them into an in-memory join sheet:

| key | col1 | col2 |
| --- | ---- | ---- |
| 1   | a    | x    |
| 2   | b    | y    |

The join sheet would remember references to the source sheets and columns it was built from, in this case:

- key --> one.csv:key and two.csv:key
- col1 --> one.csv:col1
- col2 --> two.csv:col2

Now press `a` to add a row:

| key | col1 | col2 |
| --- | ---- | ---- |
| 1   | a    | x    |
| 2   | b    | y    |
| ⌀   | ⌀    | ⌀    |

Fill in some data:

| key | col1 | col2 |
| --- | ---- | ---- |
| 1   | a    | x    |
| 2   | b    | y    |
| 3   | c    | ⌀    |

Since col1 came from one.csv, VisiData would add a row to one.csv with the new data. It would also turn the join sheet's "3" and "c" cells into references to those new cells in one.csv. one.csv now looks like this (in memory):

```csv
key,col1
1,a
2,b
3,c
```

Now edit the join sheet again:

| key | col1 | col2 |
| --- | ---- | ---- |
| 1   | a    | x    |
| 2   | b    | y    |
| 3   | c    | z    |

This time we added data to col2, so do the same thing, this time with the source being two.csv. two.csv now looks like this (in memory):

```csv
key,col2
1,x
2,y
3,z
```

Then I'd finish up by saving one.csv and two.csv to disk.

Does that makes sense?

**Comment by saulpw** [comment]
Hey @whatisaphone, thanks for the suggestion.  I can see how this would be a pretty great feature.  However, after reviewing the join code and giving it some thought, it seems pretty complicated to do correctly and completely.  In particular, it seems like you want (reasonably) for the source rows to be created only once the data is filled in, which would be a challenge for the current join architecture.

I'm not up for implementing this right now--we have a lot of other bugfixes and more basic functionality and usability issues that we'd like to fill out before such an advanced feature gets on our roadmap.  But if you or anyone wants to give it a sincere try, I'd be willing to support you in that effort.

Kondo'ed for now.
