### ISSUE TITLE
[operation] allow for expression to reference another (preceding) row

### ISSUE THREAD

**Issue by yarikoptic** [saulpw/visidata#2033]
The idea is to be able to create difference views between rows. In my case e.g. having

```
 callback_duration_…│ state │ client_time        
 226                │ 1     │ 1695668360.9675374 
 226                │ 0     │ 1695668754.9680738 
```
I want to have another column which would include differences in the `client_time` column.  I thought may be about supporting some generic syntax of adding `[+-INDEX]` reference before column name, so I could say smth like `client_time - [-1]client_time` to signal difference between current row `client_time` and `client_time` in prior  row.  Frankly ATM I do not see any use case where I would need an arbitrary INDEX besides "prior row", so may be it would be over-engineering and there simply could be some helper "function" so I could say `client_time - prev(client_time)`?

**Comment by saulpw** [comment]
Hi @yarikoptic, we made a window command for just this case.  Use `w` and specify `1 0` and you'll get a column with the previous row value and the current row value, which you can subtract in another expression column.  I can also see something like a (currently unimplemented) `zw` command that takes the window pre/post size and an aggregator and automatically applies it to the list of values--though we'd need a weird `diff` aggregator to accomplish what you want here.  

I'm open to alternate interfaces as I get that the windowing command is a bit clunky, but unfortunately `prev()` is not a reasonable function to implement, as a row isn't able to know its predecessor without scanning the entire list of rows for itself (which can be quite expensive with even a medium number of rows).

**Comment by saulpw** [comment]
Kondo'ed for now.
