### ISSUE TITLE
Bug: .csv to .vds produces invalid files

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#2037]
**Small description**

Opening a `.csv` file and saving the sheet into a `.vds` results in a `.vds`
that cannot be read back properly.

**Expected result**

The sheet data should be saved and read-back.

**Actual result with screenshot**

Data cells all contain `∅` in visidata.
No error message.

**Steps to reproduce with sample data and a .vd**

Create some `test.csv`:

```csv
first,second
0,1
```

Open it with `vd test.csv`, then run this `cmdlog.vdj`:

```
#!vd -p
{"longname": "open-file", "input": "test.csv", "keystrokes": "o"}
{"sheet": "test", "col": "", "row": "", "longname": "save-sheet", "input": "test.vds", "keystrokes": "Ctrl+S", "comment": "save current sheet to filename in format determined by extension (default .tsv)"}
```

This produces a `test.vds` as follows:

```
#{"name": "test"}
#{"name": "first", "width": 7, "height": 1, "expr": 0, "keycol": 0, "formatter": "", "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "ItemColumn"}
#{"name": "second", "width": 8, "height": 1, "expr": 1, "keycol": 0, "formatter": "", "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "ItemColumn"}
{"first": "0", "second": "1"}
```

Open this file with `vd test.vds`, open the sheet.
Observe the `∅` instead of the values in the cells.

**Additional context**

- visidata v2.11
- python 3.10.12

Creating a sheet from scratch and saving to a `.vds` usually results in the
`expr` field being set as the name of the column for `ItemColumn`s.

Here, it is set to an integer instead.
Editing the file manually to set those fiels as the column names allows
properly loading the files again with the values properly displayed in the
cells.

**Comment by saulpw** [comment]
Thanks @pacien!  This bug should be fixed now.

**Comment by pacien** [comment]
Quoting Saul Pwanson (2023-09-27 05:48:36)
> Thanks @pacien!  This bug should be fixed now.

I confirm that applying 198fcc4 solves the issue.
Thanks!
