### ISSUE TITLE
Bug: flickering confirm dialog box

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#2040]
**Small description**

The confirm dialog box sometimes (but not always) flickers.

**Expected result**

It shouldn't flicker.

**Actual result with screenshot**

https://github.com/saulpw/visidata/assets/1449319/2d3b2fd9-3190-469b-b2e0-2be85189c351

**Steps to reproduce with sample data and a .vd**

- Open `vd sample_data/sample.tsv`.
- C-S to save with the same name.
- Confirm dialog shows, sometimes flickering, sometimes not.

**Additional context**

- visidata v2.11
- terminal emulator: alacritty 0.12.0
- desktop: sway 1.8.1 (wayland)

**Comment by saulpw** [comment]
Hey @pacien, thanks for the report.  The video you posted seems to be corrupted, and I can't reproduce this on my setup.  How often does it seem to happen for you?

**Comment by pacien** [comment]
The video should play with mpv.
Otherwise, here is a gif version:

![272017464-2d3b2fd9-3190-469b-b2e0-2be85189c351](https://github.com/saulpw/visidata/assets/1449319/478db84d-5418-42e3-b900-9f141d6c36d3)

It is happening quite consistently with any file.
Within the same launch of vd, the dialog is sometimes (rarely) stable.

The issue only seems to show in alacritty.
The dialog is stable in kitty.

**Comment by saulpw** [comment]
Thanks, @pacien, this information helps.  I don't know why it's happening in alacritty but not other terminals, but we can stop redrawing the whole screen for every keypress timeout in the confirm dialog.  We'll have to see if this has any other negative display side effects, but it should be limited to the confirm dialog at least.

**Comment by pacien** [comment]
I confirm that applying commit 0917f89a698dafef3a732260d0644f8407b44bf9
solves the flickering issue. Thanks!
