### ISSUE TITLE
[whishlist]  Completions for `help-search` without strict word order

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/visidata#2043]
I made a config `TableSheet.bindkey(ALT + "h", "help-search")` and I use it very frequently. However, I really miss the completions feature from `exec-longname`.

I'm asking to add completions to this function in a form that would allow entering words one by one without strict order but filtering the next words' completions selection.

<img width="603" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/4bef4be3-5877-4eb6-8e0e-d37926f1caaa">

As I see it, it should suggest values from a module column and split words from a longname column in the following way:

When I call `help-search`, the input field appears. I enter "all" and the next suggested words would be: "threads", "cancel", "cmdlog".

If I choose "threads" after "all", then only the completion for "cancel" would be available.

Please consider developing such a feature.

**Comment by saulpw** [comment]
I think what you want will be possible with #247, which @zormit is working on!

**Comment by maxim-uvarov** [comment]
@saulpw Yes, definitely! Should we close this issue?
