### ISSUE TITLE
Add parquet writer

### ISSUE THREAD

**Issue by mr-majkel** [saulpw/visidata#2044]
Hi,

let me start by saying I really love visidata :). One thing that bugs me, though, is that it seems it's not possible to write a parquet file. When trying to save a file with .parquet extension the "no function to save parquet" message appears. Is it really not possible? If so, I am more than willing to create a PR for this feature, if someone can tell me where the "writers" should go (quick search in the repo shows loaders as a place, but is that correct?).

**Comment by anjakefala** [comment]
Yes! The loaders are the place. Contributions are very welcome.

This is the documentation: https://www.visidata.org/docs/api/loaders

You are welcome to come to `https://bluebird.sh/chat` or `#visidata` on libera, if you have any questions while you are developing.

**Comment by anjakefala** [comment]
@mr-majkel granted this wish! =)
