### ISSUE TITLE
[question] Reading vds files shows data as "⌀" (U+2300)

### ISSUE THREAD

**Issue by ezequiel-garzon** [saulpw/visidata#2046]
I imagine I'm doing something wrong when saving to .vds format, as I'm getting just "⌀" symbols (U+2300) as the only cell values. Searching the web hasn't led to any relevant explanations, so pretty sure it's me! My first attempt at saving `.vds` was with multiple sheets, but I kept making the examples smaller, ending up with just one sheet with the following canonical dataset, to no avail.

~~~
$ cat f4.tsv
Name	YOB
George	1943
John	1940
Paul	1942
Ringo	1940
~~~

I ran `vd f4.tsv` and sorted the second column in ascending order, and saved (^S) the result as `f4.vds`. This gave me:

~~~
$ cat f4.vds
#{"name": "f4"}
#{"name": "Name", "width": 8, "height": 1, "expr": 0, "keycol": 0, "formatter": "", "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "ItemColumn"}
#{"name": "YOB", "width": 6, "height": 1, "expr": 1, "keycol": 0, "formatter": "", "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "ItemColumn"}
{"Name": "John", "YOB": "1940"}
{"Name": "Ringo", "YOB": "1940"}
{"Name": "Paul", "YOB": "1942"}
{"Name": "George", "YOB": "1943"}
~~~

Upon loading this file as `vd f4.vds` I see:

~~~
name ║ rows   #│ cols#│ keys │ source ║
f4   ║       4 │    2 │      │ f4.vds ║
~~~

But when I hit Enter I get:

~~~
Name   │ YOB  ║
      ⌀│     ⌀║
      ⌀│     ⌀║
      ⌀│     ⌀║
      ⌀│     ⌀║
~~~

Any ideas on why I'm getting this instead of the following?

~~~
Name   │ YOB  ║
John   │ 1940 ║
Ringo  │ 1940 ║
Paul   │ 1942 ║
Ringo  │ 1943 ║
~~~

I've tested this with v2.11 on Mac, and v2.11.1 on Ubuntu, same situation. The puzzling part is that the `.vds` file does show the corresponding data on the shell. Thanks in advance.

**Comment by saulpw** [comment]
Hi @ezequiel-garzon, this is #2037 in 2.11.x, which should be fixed on develop now.  Sorry about that.  Let me know if you experience this or other issues with the vds format after upgrading to the develop branch.

**Comment by ezequiel-garzon** [comment]
Hi @saulpw, thanks a lot for your prompt reply, and for this amazing project! I'll try to use the develop branch, I'm sorry I missed the opened issue.

**Comment by marcopaganini** [comment]
Oh wow, this is exactly what I'm seeing here! Thanks for the prompt reply @saulpw!
