### ISSUE TITLE
[s3 zip] unzip_http does not work over s3

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2050]
I'm having trouble opening zip files over s3. The error I get is:

```
URLSchemeUnknown: Not supported URL scheme s3
```
I can open CSV and other files over s3, but not zip.  The comment above says `.zip` is supported.  Is this the case, and if so, what, if anything can I do to get opening of zip files working over s3?

_Originally posted by @tonycpsu in https://github.com/saulpw/visidata/issues/1184#issuecomment-1679280924_

**Comment by saulpw** [comment]
Hey @tonycpsu, this is because [unzip_http](https://github.com/saulpw/unzip-http/) has some magic hacks that work over http/https (though not on all servers), and I haven't seen a similar library for s3.  It might be feasible but would require some work, I'd be happy to review a PR if someone wants to try their hand at implementing it as a subclass of RemoteZipFile.

Kondo'ed for now.

**Comment by horw** [comment]
Hello, @saulpw. Maybe I can try to implement this S3 functionality? Could you please assign it to me?

**Comment by saulpw** [comment]
Sure, @horw!  Let me know if you get stuck or have any questions.
