### ISSUE TITLE
Display column as bar /histogram [] 

### ISSUE THREAD

**Issue by maxigit** [saulpw/visidata#2052]
At the moment it is possible to display an histogram of values (with '*****").
It would be nice to be able to do the same but use the value of column instead. The easiest would probably to be able add a column so that

    Apple, 3, ###
    Orange, 10, #########

It probably can be done by using a python expression, but it would be easier if the scaling was done automatically (using min and max value as well as column width).

**Comment by saulpw** [comment]
Hi @maxigit, thanks for the suggestion.  I added it as an unbound command `addcol-histogram`.
