### ISSUE TITLE
Documentation Additions

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#206]
- [ ] Write a tutorial for [VisiData Case Study 5](https://youtu.be/0iJ9F4uTkz8?t=28)
- [ ] Diffing two sheets
- [x] Taking a random sample from a large csv (add to /rows)
- [ ] Explore a python module
- [ ] [DirSheet tutorial](https://www.youtube.com/watch?v=l2Bpmm0yAGw)
- [ ] Section on the pandas loader
- [ ] How to unmelt a table
- [ ] Loading csv
- [ ] Doing queries

**Comment by saulpw** [comment]
Github issues is not a todo list :)
