### ISSUE TITLE
[open-colors] ColorSheet preview not showing proper colors for all rows.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2061]
**Small description**
ColorSheet preview not showing proper colors for all rows.

**Expected result**
Preview squares are not white, but match the colors of the rows in the ColorSheet

**Actual result with screenshot**

- https://asciinema.org/a/a3RSIgQMHBIzKp7jCvZIjLJSt

**Steps to reproduce with sample data and a .vd**

Run the `open-colors` command

**Additional context**
Please include the version of VisiData (latest develop) and Python 3.9.2. 

I had a few more minutes before it got too late.

**Comment by saulpw** [comment]
Thanks @frosencrantz, should be fixed now.
