### ISSUE TITLE
[windows] no windows-curses<2.3.1 for Python>=3.11

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2062]
This is on Windows 10 using the Bash shell that comes with Git.

```
$ pip install git+https://github.com/saulpw/visidata@bb0c95af89b03d28f79a3103d3d38785b50023a0
Collecting git+https://github.com/saulpw/visidata@bb0c95af89b03d28f79a3103d3d38785b50023a0
  Cloning https://github.com/saulpw/visidata (to revision bb0c95af89b03d28f79a3103d3d38785b50023a0) to c:\users\administrator\appdata\local\temp\pip-req-build-revt5xrz
  Running command git clone --filter=blob:none --quiet https://github.com/saulpw/visidata 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-revt5xrz'
  Running command git rev-parse -q --verify 'sha^bb0c95af89b03d28f79a3103d3d38785b50023a0'
  Running command git fetch -q https://github.com/saulpw/visidata bb0c95af89b03d28f79a3103d3d38785b50023a0
  Resolved https://github.com/saulpw/visidata to commit bb0c95af89b03d28f79a3103d3d38785b50023a0
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil in c:\program files\python311\lib\site-packages (from visidata==2.12.dev0) (2.8.2)
Requirement already satisfied: importlib-metadata>=3.6 in c:\program files\python311\lib\site-packages (from visidata==2.12.dev0) (6.8.0)
INFO: pip is looking at multiple versions of visidata to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement windows-curses<2.3.1; platform_system == "Windows" (from visidata) (from versions: 2.3.1a2, 2.3.1)
ERROR: No matching distribution found for windows-curses<2.3.1; platform_system == "Windows"
```

**Comment by cool-RR** [comment]
I understand why it's happening now. I'm running Python 3.11 on Windows. VisiData requires `windows-curses<2.3.1` on Windows because of #1841 , which practically means `windows-curses==2.3.0`. However, because that version was released in 2021, it has binaries for Python versions 3.6 to 3.10, and no binary for Python 3.11.

**Comment by saulpw** [comment]
It looks like windows-curses just released an alpha for 2.3.2 yesterday: https://github.com/zephyrproject-rtos/windows-curses/releases/tag/v2.3.2a1

There aren't any release notes that I can find, however; do we know if #1841 would be fixed with v2.3.2?  If so, we could update the requirements to just exclude 2.3.1.

**Comment by saulpw** [comment]
Okay, I updated the requirement to be `windows-curses != 2.3.1` to just work whenever 2.3.2 is released.  Thanks for figuring it out and bringing it to our attention.

**Comment by cool-RR** [comment]
Thank you. Now I'm dealing with #2099.

**Comment by anjakefala** [comment]
This will be fixed in the next release of VisiData!

Until then, you can `pip3 install git+https://github.com:saulpw/visidata.git` or `pip3 install windows-curses>=2.4`. =)

**Comment by cool-RR** [comment]
Thanks. I gave up on using VisiData directly on Windows because of the many issues it has on Windows. I use it on WSL so I don't have these issues.
