### ISSUE TITLE
'sampling {n} rows' is annoying

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2066]
Because I'm using autotune which samples rows, I get an `'sampling 100 rows'` warning on every sheet I open. I don't understand why it exists, let alone why it's a warning. It seems to me like it should be a debug-level notification.

**Comment by saulpw** [comment]
Sorry you find it annoying.  See #1054 for why this warning exists.  Happy to entertain user interface improvements but please do the least bit of research before griping about Chesterton's Fence.
