### ISSUE TITLE
Insert binding doesn't have dash

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2067]
I can't find the bug in which we previously talked about an `Insert` key binding. Now with the new versions I was able to bind a command to `Insert-C` successfully, except I had to call it `Insc` where I thought it'd be `Ins-C`. Not a big deal so if it's not easy to fix I can just have a comment in my `.visidatarc` to explain it.

**Comment by saulpw** [comment]
We've never used `-` as a keystroke separator; only `+` to indicate shift combinations (like `Alt+b`).  I just committed a change to allow spaces to separate keystrokes, which should make your keybinding feel nicer though: `Ins c`.
