### ISSUE TITLE
Make sorting work asynchronously

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#207]
When I'm sorting a large sheet, it takes a while, but I can't tell when it's done. I end up thinking I pressed the wrong button, and I try it again with the other bracket, which of course only compounds the problem. Could it show some more info about whether it's working or done? 

Likewise, I can't tell what happens to commands I issue while it's working. It'd be nice to have some feedback that my new commands are queued up.

Version 1.5

**Comment by saulpw** [comment]
Hi @apnewberry, thanks for the request. There are many commands which operate asynchronously, like deletion and the selection commands (`|` `gt` etc).  You can tell that one of these is in progress by an active percentage indicator on the right status bar (lower right).  If you want to see all tasks, both completed and currently in progress, you can press `Ctrl+T` to go to the tasks sheet.

I've tried making sorting async in the past but ran into a few issues.  Your request got me thinking though, and I gave it another shot.  I'm worried that data might be lost if the wrong command is executed during the sort, but everything I've tested so far seems okay.   

It's in the `develop` branch now, but if you would like to experiment with it yourself in 1.5, add the following to your `.visidatarc`:

```
@asyncthread
def orderBy_async(self, *cols, **kwargs):
    with Progress(self.rows) as prog:
        self.rows = sorted(self.rows, key=lambda r,cols=cols,prog=prog: prog.addProgress(1) and tuple(c.getTypedValue(r) for c in cols), **kwargs)

Sheet.orderBy = orderBy_async
```

If there are other operations besides sort which you think should be asynchronous, please file another issue and we will consider those independently.  Thanks for helping make VisiData better!

**Comment by cwarden** [comment]
Displaying the synchronous action that's being performed in the status bar where progress is displayed might be sufficient, e.g. `Sorting...`

**Comment by ghost** [comment]
That would help me to understand what state the program is in, why it's hung, and to know when it's completed and I can go back to work.
