### ISSUE TITLE
[pivot] Missing setitem import

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2078]
**Small description**
Pivot uses setitem, which hasn't been imported

**Expected result**
The import is there, and there is no stack trace

**Actual result with screenshot**
There is a call to setitem here that is missing an import:
https://github.com/saulpw/visidata/blob/b4387c9fd50666c83d7dfec760423766389ea633/visidata/pivot.py#L97

**Steps to reproduce with sample data and a .vd**

Visual inspection.  

Found deep in a script, and this is the easiest way to report.  I was trying to understand why VisiData was exiting after running an initial playback script.  I do not think this is only cause, but it would be helpful for tracking down the other problem.

**Additional context**
Please include the version of VisiData and Python. Latest version of develop.

**Comment by anjakefala** [comment]
Thanks! =)
