### ISSUE TITLE
Expression columns with pandas filetype

### ISSUE THREAD

**Issue by nickray** [saulpw/visidata#208]
Love the Pandas integration, which allows browsing Parquet files.

However, there is a small bug, when trying to create an expression column (e.g., `=column_a - column_b`): 
it outputs `ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()`. I assume/hope this is a minor issue, perhaps an expression returning a (pandas) Series instead of an (expected) scalar value.

**Comment by saulpw** [comment]
Hi @nickray, thanks for the report.  Could you post a small example dataset here, and/or the output of `Ctrl+E` when you get that error?

**Comment by nickray** [comment]
An example (assuming pandas and pyarrow are installed):
```
import pandas as pd
df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
df.to_parquet('example.parquet')
```

Then I do `vd -f pandas example.parquet`; two observations:

- the columns are not loaded as the `int64` they were; I use `#` to mark them as integers (same issue below when using `$` to mark them as floats)
- typing `=a - b` gives errors in the column marked with `!`, inspection reveals the `ValueError` I quoted above.

Hope this helps!

**Comment by saulpw** [comment]
6788679 fixes the second issue. To fix the first issue, we'll need a translation between the possible dtypes of the DataFrame and the Python int/float/etc types.  Do you know if something like this already exists?

**Comment by nickray** [comment]
I'm not sure if there's an official API, perhaps in the depths of pandas' or numpy's submodules?

The relevant mappings I believe are:
* python int = numpy.int64
* python float = numpy.float64
* python datetime.datetime = pandas.Timestamp
* python string = pandas "object" (which covers everything not explicitly mapped in pandas)

```
>>> import datetime, pandas
>>> df = pandas.DataFrame({'float': [1.0], 'int': [1], 'datetime': datetime.datetime(2018, 11, 21, 13, 25), 'string': ['foo']})
>>> {k: type(v[0]) for k, v in df.to_dict().items()}
{'float': float,
 'int': int,
 'datetime': pandas._libs.tslibs.timestamps.Timestamp,
 'string': str}
>>> {k: type(v) for k, v in df.iloc[0].items()}
{'float': numpy.float64,
 'int': numpy.int64,
 'datetime': pandas._libs.tslibs.timestamps.Timestamp,
 'string': str}
```

One annoying thing in this enterprise is that numpy and pandas promote integer columns containing nulls to float columns implicitly (https://pandas.pydata.org/pandas-docs/stable/missing_data.html), although I think due to recent work with `wesm/feather` there is interest in properly supporting nulls.

**Comment by saulpw** [comment]
Okay, please test and let me know if this works for you.  Thanks for reporting the issues, these fixes are definite improvements.

**Comment by nickray** [comment]
I'm impressed by your responsiveness, thanks! I can use expression columns now, and load data with appropriate types.

The pandas parquet loader is doing something strange now though (I am using commit 275acb8ac5e65b8031cc980468454a1e846da6d5).

The attached file [flaky.parquet.zip](https://github.com/saulpw/visidata/files/2609078/flaky.parquet.zip) which consists of a couple integers stored as strings, loads with embedded gibberish (the `-11-22` parts don't belong):

![flakey parquet](https://user-images.githubusercontent.com/1092423/48919231-d53ccb80-ee91-11e8-842b-e4e4efbddfd7.png)
Loading it via `pandas.read_parquet` directly "works", but admittedly it is a bit of a broken parquet file.

Just adding this in case you would like to use it to exercise corner cases in your conversion code, otherwise I will close this issue soonish.

**Comment by saulpw** [comment]
I had a hard time trying to figure out how to compare pandas types; `is` did not work, and ultimately `==` works for int64 and float64.  But I did not test pandas.Timestamp, and that's what's happening here (note that the columns are `date` typed).  Could you attach a parquet file with proper dates in them?

**Comment by anjakefala** [comment]
Closing:
* original issue has been addressed
* the tangential conversation has dropped in activity

=)
