### ISSUE TITLE
[input] Add a ctrl-r command for input like the shell it allows you to search for previous input that you have entered.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2081]
Subject says it all:

Add a ctrl-r command for input like the shell it allows you to search for previous input that you have entered.

When configured VisiData can have useful history, it would be useful to be able to search it from the input.

Originally mentioned in Issue #2075 (another thread too, but I didn't find it.)

**Comment by saulpw** [comment]
Thanks for suggesting this, @frosencrantz.  I think it sounds useful, but would be a fair amount of work.  Kondo'ed for now.

**Comment by frosencrantz** [comment]
@saulpw Is it possible the code almost here.  Would it be possible to make use of the new fuzzymatcher to also have a mode for looking at past values?  Without looking at the code, it feels like the big change would be providing a different source of input to the matcher.
