### ISSUE TITLE
[samples] Allow percentage input for random-sample (or even other things like resize-col-input)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2082]
Allow percentage input for random-sample (or even other things like resize-col-input). Currently you need to enter calculate the value yourself if say you only want 10% if the values. This makes parsing the input more complicated since you need to handle % values and specific counts.

For input values that take a value from the user, and there is a maximum value, it might be useful if the input could specific values, or percentages.  Like for random-sample there is max based on the numbers of rows, so it is possible to calculate 10% or 50%, but it would be nice if VisiData could assist.  This can help with scripting where the script might not know the max number, and adding a percentages might make the script more generic.

Originally mentioned in Issue #2075.

**Comment by saulpw** [comment]
I'm wondering if we could make it really simple, such that if `input()` is given a numeric starting `value`, and you type `10%`, then it returns 10% of the starting value.  Then we'd just make sure that the starting value for each input is the 100% value (so random-sample would be given the total number of rows by default).  Does this seem reasonable?

**Comment by frosencrantz** [comment]
That seems like a reasonable solution, @saulpw.  It seems like random-sample by default provides the 100% value

**Comment by saulpw** [comment]
Okay @frosencrantz, try this on for size

**Comment by frosencrantz** [comment]
It looks like there is an issue with the variable name:
https://asciinema.org/a/WDk4eLAwCAzI0IWCogCWnvRIf

```
Traceback (most recent call last): 
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 208, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "random-rows", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 461, in input
    ret = self.editText(y, promptlen, w=w,
  File "/usr/lib/python3.9/site-packages/visidata/_input.py", line 337, in editText
    v = pct*value/100
NameError: name 'value' is not defined
```

**Comment by anjakefala** [comment]
@frosencrantz Fixed the typo, and it works for me. =)

This feature is a cute idea, btw! And nice demonstration of the cmd pallette!

**Comment by frosencrantz** [comment]
Yes, works great!  Thanks @anjakefala!
