### ISSUE TITLE
[macros] Macros broken at head returning KeyError

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2084]
**Small description**
Trying to run macros is failing with a KeyError

**Expected result**
Macro is run.

**Actual result with screenshot**
```
raceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 208, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "add-col-sh-date", line 1, in <module>
    'VisiData: a curses interface for exploring and arranging tabular data'
KeyError: 'add-col-sh-date'
```

https://asciinema.org/a/VLcFbkSi3Wlg2mKpBoArnqacz

**Steps to reproduce with sample data and a .vd**

Try running a saved macro by it's long name.

**Additional context**
Please include the version of VisiData and Python.  Latest from develop.

**Comment by saulpw** [comment]
Thanks, @frosencrantz, now the macro filenames will be the given longname or keystroke.

**Comment by frosencrantz** [comment]
It still does not work for my existing macros.  Is it expected that existing users will need to rename their macro files?  Macros are already released.  If someone was using a  released version of VisiData and already has a macro would they be broken?  I think that is ok as long as that is documented as an  incompatibility or there is a quick way to fix it.

**Comment by saulpw** [comment]
Hm, I'd rather not force people to manually rename their macro files without good reason.  I admit that I don't use macros myself, so I'm relying on these second-hand reports to both diagnose the problem and what might fix it. @frosencrantz, are you ever available for a sync chat, so we can investigate the issue together and resolve it without too much time spent going back and forth?

**Comment by frosencrantz** [comment]
I did try it again with the debug flag which appears to show more information.

https://asciinema.org/a/hWyDQ66lHUF3e0vXHLccDI6tj

```
Traceback (most recent call last):
  File "/usr/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/usr/lib/python3.9/site-packages/visidata/main.py", line 379, in vd_cli
    rc = main_vd()
  File "/usr/lib/python3.9/site-packages/visidata/main.py", line 339, in main_vd
    run(vd.sheets[0])
  File "/usr/lib/python3.9/site-packages/visidata/vdobj.py", line 33, in _vdfunc
    return getattr(visidata.vd, func.__name__)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 65, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 65, in wrappedfunc
    return oldfunc(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/mainloop.py", line 302, in run
    ret = vd.mainloop(scr)
  File "/usr/lib/python3.9/site-packages/visidata/mainloop.py", line 213, in mainloop
    sheet.execCommand(self.keystrokes, keystrokes=self.keystrokes)
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 79, in wrappedfunc
    r = oldfunc(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 211, in execCommand
    err = vd.exceptionCaught(e)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 208, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "exec-longname", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/visidata/features/cmdpalette.py", line 107, in exec_longname
    sheet.execCommand(longname)
  File "/usr/lib/python3.9/site-packages/visidata/extensible.py", line 79, in wrappedfunc
    r = oldfunc(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 211, in execCommand
    err = vd.exceptionCaught(e)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 208, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 73, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "add-col-sh-date", line 1, in <module>
KeyError: 'add-col-sh-date' 
```


This is what my macros-sheet looks like:

| longname   | keystrokes       |   num_commands | source                            |
|------------|------------------|----------------|-----------------------------------|
| macro      | split_keystrokes |              3 | /home/felix/.visidata/macro.vdj   |
| macro-1    | add-col-sh-date  |              1 | /home/felix/.visidata/macro-1.vdj |

**Comment by anjakefala** [comment]
@frosencrantz The longnames you are using are actually in the keystrokes column, do you remember how that happened? Did you manually place them there? Did that work before?

**Comment by saulpw** [comment]
@frosencrantz is this how you want your macros to work, by their command longname only?

**Comment by frosencrantz** [comment]
> @frosencrantz The longnames you are using are actually in the keystrokes column, do you remember how that happened? Did you manually place them there? Did that work before?

That is how they were created by VisiData.  That has always confused me, I see that in more than one installation of mine.  
When I try it now VisiData asks me what I want to bind the macro too, and both long name and keystrokes end up with the same value.  When I try to type the command only the name of keystrokes column is shown, not the value from the longname column

https://asciinema.org/a/AkuivRKN3loNW3Ho7i3USmRwM


> @frosencrantz is this how you want your macros to work, by their command longname only?

I think VisiData must have done this before.  Command longname is fine, it makes sense to me.  But I think the behavior has changed.

**Comment by anjakefala** [comment]
@frosencrantz If I remember, there was a breaking macros change made at one point, that I think muddled with those macros. =( I would edit your `~/.visidata/macros.tsv` so that the longname is in the longname column, and a keystroke is in the keystrokes column, and let me know if that helps. I agree that needing to migrate like this is not ideal.

**Comment by saulpw** [comment]
Please don't edit your macros.tsv by hand.  Let's try and figure out how to fix the code so a manual migration isn't necessary.

**Comment by anjakefala** [comment]
@saulpw He's trying to use a longname that is actually a keystroke in the macros.tsv. We didn't end up implementing the feature that let you rename a longname from within VisiData. I'm not sure what else to do other than implement that feature?

**Comment by anjakefala** [comment]
@frosencrantz Do you remember how you set up these macros? Did those longnames used to work? Or did this stop working recently?

**Comment by frosencrantz** [comment]
@saulpw I just used VisiData to create the macros.  This is my current ~/.visidata/macros.tsv file (I tried adding some new macros and now both the filename name and the command column end with same value.

I think VisiData only allowed me to input one value and that was the long name.  You can also see the new command palette showing the value in the keystroke column above.   

```
cat -T ~/.visidata/macros.tsv
command^Ifilename
split_keystrokes^I/home/felix/.visidata/macro.vdj
add-col-sh-date^I/home/felix/.visidata/macro-1.vdj
my-new-macro^I/home/felix/.visidata/my-new-macro.vdj
my-new-macro2^I/home/felix/.visidata/my-new-macro2.vdj
```

**Comment by frosencrantz** [comment]
I think sometime after commit 192808c. macros might have changed behavior.  I only pick that commit since I started having some issues with other things, and so froze at that commit.  I think the other things issue I had (and still have) is that playback became a lot more strict, so if there are errors it crashes/exits  VisiData, while previously it would remain open.
I have at least one crash from line 263 in cmdlog.py where it failed to find an expected column.  Possibly this should stop playback, but not crash/exit VisiData.

Now it is crashing

**Comment by saulpw** [comment]
@frosencrantz VisiData should never crash/abort like that unless `--debug` is given.  I repro'ed the issue you're referring to and fixed it, sorry it's been broken like that for you.  We're approaching the finish line for this round of bugs, so if you know of or come across others, please report them as new issues so we can triage and/or fix them before 3.0!

**Comment by frosencrantz** [comment]
@saulpw as always I will try to report any issues I find.   I had not reported this one until now, since I had not had a chance to make a repo. I've been busy.   I am happy that was enough information.  Given I have a frozen installation, it was possible to see macros behavior changed recently, too.  I'll report back tomorrow if your latest fix resolves my playback issue.

**Comment by frosencrantz** [comment]
Thanks for the amazing amount of recent work you and @anjakefala  have been doing.  I have not had a chance to try everything new.

**Comment by frosencrantz** [comment]
Your change fixed the issue with playback.  Thanks @saulpw!  

Though I still have the macros issue.  I think the problem with macros came in after commit 192808c

**Comment by saulpw** [comment]
@frosencrantz Thanks for sharing your macros.tsv.  I've committed a fix, so hopefully your existing macros and new macros should both work now.

**Comment by frosencrantz** [comment]
Macros also working again.  Thank you again @saulpw!

As part of fixing playback, I found a new issue. I reported it in #2102
