### ISSUE TITLE
[input help] Please add input help back.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2085]
I already miss visidata/ddw/input.ddw. I prefer that detailed help message over the new message.

**Comment by saulpw** [comment]
Hey @frosencrantz, can you tell me more? I had no idea anyone cared, especially not a long-time user.  What did you like about it?  Can that be added to the sidebar input help instead?

**Comment by frosencrantz** [comment]
It just seemed like a complete help message, it provided information about all the different control codes for input.  And it was compact and nicely formatted. The new input help does not have the same completeness of details.

**Comment by saulpw** [comment]
Okay I put it back, but moved it to the sidebar.  How does it feel now?  I'm working on getting Ctrl+G to cycle through all the various help modes.

**Comment by frosencrantz** [comment]
It does not seem to work at all for me. Running latest develop version. I tried hitting Ctrl+G  and it doesn't seem to show the help for the input mode.

https://asciinema.org/a/YPYpaAVCDh4Ah2h35vWILFwzq

**Comment by saulpw** [comment]
Ah, set `options.disp_help=2` in your .visidatarc.

(Still trying to figure out how all the help options should work and interact.)

**Comment by frosencrantz** [comment]
That looks like it works.  Thanks, @saulpw!  I see the format was made more compact, but has all the same information.
