### ISSUE TITLE
Binding Command to Enter + modifier Doesn't Work

### ISSUE THREAD

**Issue by brooksvb** [saulpw/visidata#2087]
**Small description**
I wanted to bind 'view-cell' to Ctrl+Enter.

I did this by adding one of the following lines to my ~/.config/visidata/config.py (I tried all 3)
```
visidata.BaseSheet.bindkey('Ctrl+Enter', 'view-cell')                                                 
visidata.BaseSheet.bindkey('Shift+Enter', 'view-cell')                                                
visidata.BaseSheet.bindkey('^Enter', 'view-cell')
```

Viewing the Command List inside Visidata, I can clearly see that my bind shows up in the keystrokes column for 'view-cell', but every time I tried to trigger the keybind, it would be registered as just "Enter" no matter what, performing that action instead.

As soon as I tried a different keybind (^V), it works, but I really wanted this action to be on the Enter key.

**Steps to reproduce**
1. Create config file with one line: `visidata.BaseSheet.bindkey('Ctrl+Enter', 'view-cell')`
2. Open a CSV with visidata
3. Confirm keybind was set for 'view-cell' in Command List
4. Hover over a cell and try pressing Ctrl+Enter
	i. Enters into row view
	ii. Bottom status bar shows "Enter" keypress was last triggered

**Additional context**
saul.pw/VisiData v2.11.1
Python 3.11.5

**Comment by saulpw** [comment]
Hi @brooksvb, unfortunately `Ctrl+Enter` is not distinguishable from `Enter` in the terminal.  The keys shown on the bottom status bar are those received by VisiData, so unless you can get something unique there, you can't use it as a keybinding.  Maybe `Alt+Enter` would work for your situation?

**Comment by brooksvb** [comment]
Alt+Enter does work and is acceptable. I didn't know about that limitation of the terminal.

Thanks for the quick response!
