### ISSUE TITLE
[vds] hidden columns used in expressions not saved in .vds export

### ISSUE THREAD

**Issue by pacien** [saulpw/visidata#2089]
**Small description**

Hidden (zero-width) columns are removed from .vds exports.

**Expected result**

Those columns and their expressions should be preserved,
especially when used as intermediary columns for other expressions.

I think it would make more sense in terms of intent between `-` (hide, setting
width to zero) vs. removing the column from the columns sheet.

**Actual result ~~with screenshot~~**

The hidden columns are missing.

After opening the file again,
this results in expression computation errors (red `!`) on columns depending
on those.

**Steps to reproduce with sample data and a .vd**

```vdj
#!vd -p
{"sheet": "global", "row": "numeric_binning", "longname": "set-option", "input": "True", "keystrokes": ""}
{"longname": "open-file", "input": ".", "keystrokes": "o"}
{"col": "", "row": "", "longname": "open-new", "input": "", "keystrokes": "Shift+A", "comment": "Open new empty sheet"}
{"sheet": "unnamed", "col": "", "row": "", "longname": "add-row", "input": "", "keystrokes": "a", "comment": "append a blank row"}
{"sheet": "unnamed", "col": "A", "row": "0", "longname": "edit-cell", "input": "a", "keystrokes": "e", "comment": "edit contents of current cell"}
{"sheet": "unnamed", "col": "A", "row": "", "longname": "addcol-expr", "input": "A*2", "keystrokes": "=", "comment": "create new column from Python expression, with column names as variables"}
{"sheet": "unnamed", "col": "A*2", "row": "", "longname": "rename-col", "input": "B", "keystrokes": "^", "comment": "rename current column"}
{"sheet": "unnamed", "col": "B", "row": "", "longname": "addcol-expr", "input": "B*2", "keystrokes": "=", "comment": "create new column from Python expression, with column names as variables"}
{"sheet": "unnamed", "col": "", "row": "", "longname": "save-sheet", "input": "all.vds", "keystrokes": "Ctrl+S", "comment": "save current sheet to filename in format determined by extension (default .tsv)"}
{"sheet": "unnamed", "col": "B", "row": "", "longname": "hide-col", "input": "", "keystrokes": "-", "comment": "Hide current column"}
{"sheet": "unnamed", "col": "", "row": "", "longname": "save-sheet", "input": "with_hidden.vds", "keystrokes": "Ctrl+S", "comment": "save current sheet to filename in format determined by extension (default .tsv)"}
{"sheet": "unnamed", "col": "", "row": "", "longname": "columns-sheet", "input": "", "keystrokes": "Shift+C", "comment": "open Columns Sheet: edit column properties for current sheet"}
```

This creates two files:
- `all.vds`, with all the columns, which loads fine, and
- `with_hidden.vds`, with a hidden intermediary column.

That last one loads but is incomplete:
- the intermediary column no longer shows in the columns sheet, and
- thus the expression in the third column can no longer be computed.

**Additional context**

- saul.pw/VisiData v2.11
- Python 3.10.13

**Comment by saulpw** [comment]
Hi @pacien, you make a very good point, and as stated, would be a very easy fix.  However, this would be different from all other savers, which only save `visibleCols`.  I'm wondering if it would be worth the effort to figure out which hidden columns are used in expressions in visible columns, and only save those?  Looking also for input from other people who save with the .vds format.

**Comment by pacien** [comment]
Hi Saul,

I think that there is a different intent depending on the format:

- .vds -> **save** snapshot of the sheet's state, which can be edited later, vs
- .jsonl (for example) -> **export** of the result (no expression).

In the first case, I don't expect intermediary but not-yet-used columns to be
"garbage collected" when saving, even if they're hidden, because I still see
them existing on the underlying columns sheet. It's a bit surprising to me
to have it changed after loading the .vds again.

**Comment by saulpw** [comment]
Okay, so if there were hidden data columns, would the values for those columns all be saved in every row also?  We can save all the expression columns but only save the data for visible columns (which is my first intuition for solving this issue).

**Comment by pacien** [comment]
Removing hidden data columns could also lead to other expressions not being
computable anymore after loading the file again.

I also expect seeing the data again when setting the width >0 on the columns
sheet, and not an empty column.

**Comment by saulpw** [comment]
Thanks for pushing on this, @pacien.  We merged the changes to include both column metadata and row data for hidden columns.  This sets us further on the path of making .vds even more like a program-state-saving format, compared with other formats which are more like data exports.  Which does make sense I think.  I was a bit resistant because I'm a little worried about the scope of program-state that wants to be saved, and how that will complicate changing the internals, since we probably want to maintain compatibility of .vds files in future versions of VisiData.  But I can see why it's useful and so we'll cross those bridges when they come.
