### ISSUE TITLE
[Request] .zst compression support

### ISSUE THREAD

**Issue by pshelly** [saulpw/visidata#209]
Hello,
Thank you for this awesome project! Would you consider adding support for [lzip](http://www.nongnu.org/lzip/lzip.html) and [zstd](https://facebook.github.io/zstd/) compression? Specifically when opening files. 

**Solution**
I see lzip has no python bindings so this is definitely harder and possibly out of scope.
[Zstd](https://github.com/indygreg/python-zstandard) has bindings.

Thanks!

**Comment by saulpw** [comment]
Thanks, @pshelly, glad you're enjoying VisiData! Adding support for zstd is definitely possible.  Can you attach a small sample dataset in the zstd format for our testing?  What does the filename look like? (Is there a standard extension for zstd?)

I can't promise that I'll be able to get around to it very quickly, but if you were to submit a PR (see how we do other compression formats already in `path.py`), that would certainly speed things along.

**Comment by pshelly** [comment]
Thanks for the quick  response! For the example I am going to use [countrypositions.csv](https://github.com/petewarden/dstkdata/blob/master/countrypositions.csv)
I am attaching the original and compressed file.
[files.tar.gz](https://github.com/saulpw/visidata/files/2569963/files.tar.gz)
Which contains:
countrypositions.csv      - Original File
countrypositions.csv.zst - Compressed File

Is this ok @saulpw? I will start checking `path.py`.

**Comment by saulpw** [comment]
@pshelly That's the right idea, but the .csv that's here is actually an HTML page (which also happened to expose a bug in the csv parser, so thank you for that, it's fixed now).  If you would, upload an actual .csv and the .csv.zst in a .zip file (.zip is more universally standard).

Also when you look into path.py, notice that all of the supported compression libraries include an `open()` function which acts just like Python `open()`, including taking the same arguments (like `encoding`, etc). After looking for a few minutes, I don't see a corresponding function like this in `zstandard`, so the first order of business would be writing one of those.  Ideally it would be included in the zstandard library itself but I recognize that may not be possible in the short term.

**Comment by pshelly** [comment]
@saulpw sorry for that (but I guess good for bug removal). I've uploaded new files from: https://catalog.data.gov/dataset/demographic-statistics-by-zip-code-acfc9
[Demographic_Statistics_By_Zip_Code.zip](https://github.com/saulpw/visidata/files/2592450/Demographic_Statistics_By_Zip_Code.zip)
This contains the :
- Demographic_Statistics_By_Zip_Code.csv
- Demographic_Statistics_By_Zip_Code.csv.zst

Agree on the unfeasability of implementing it short term. Will begin to work on it.

**Comment by pshelly** [comment]
I got data decompressed like this:
```
with open('Demographic_Statistics_By_Zip_Code.csv.zst', 'rb') as compressed:
    data = compressed.read()
    decomp_data = zstd.ZstdDecompressor().decompress(data)
    print(decomp_data)
```

Does this help @saulpw ?

**Comment by pshelly** [comment]
@saulpw I don't think the `encoding` arguments will matter since we open the file with the normal `open()`. What parameters are passed to the `open(mode=)`?

**Comment by saulpw** [comment]
The `encoding` definitely matters for the decompressed data; it should not be applied to the compressed data (which is always 8-bit binary).  If we have a UTF16 .csv file compressed with zstd, we need to have the .csv data decoded properly *after* the decompression has happened.

**Comment by saulpw** [comment]
Yes, @pshelly, that helps as a first pass.  We'd need to make it streaming, do you know how to make that happen?

**Comment by saulpw** [comment]
When zstd supports the same semantics as other Python stdio (open, encoding, streaming, iterator over lines) it will be very straightforward to add.  Closing this for now, reopen when zstd is ready.
