### ISSUE TITLE
Confusing message when committing changes to folder

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2090]
When you make a change to a folder (like delete a file) and commit it, you get a dialog like so:

```
my_folder already exists. delete 1 files?
```

The second part of the message makes sense (modulo a capital letter), but the first part is confusing.

**Comment by anjakefala** [comment]
I think that first part was written for when modifying something like an sqlite file, and you noticed that it makes less sense for a **DirSheet**. 

What should be the behaviour be for when you set overwrite to `confirm` but are changing files in a **DirSheet**? Ask for an additional layer of confirmation? Or do we only want the message to pop up when we are overwriting e.g. sqlite files? 

My gut is to ask for an additional layer of confirmation.

**Comment by saulpw** [comment]
Okay we have the previous message again for the commit case.

@anjakefala I'd rather not have multiple levels of confirmation if we can avoid it, that's part of the reason for the confirm string in the first place, figure it all out and present one confirmation before doing any of it.
