### ISSUE TITLE
ValueError: path 'share/applications/' cannot end with '/'

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2099]
When attempting to install on Windows, I get the following error:

```
    File "C:\Program Files\Python311\Lib\site-packages\setuptools\_distutils\util.py", line 141, in convert_path
      raise ValueError("path '%s' cannot end with '/'" % pathname)
  ValueError: path 'share/applications/' cannot end with '/'
```

[Full output](https://gist.github.com/cool-RR/44e706555ec429c1d6444d965bd08754).

Possibly this is caused by this line in `setup.py`:

```
      data_files=[('share/man/man1', ['visidata/man/vd.1', 'visidata/man/visidata.1']), ('share/applications/', ['visidata/desktop/visidata.desktop'])],
```

Maybe `'share/applications/'` needs to be changed to `'share/applications'`. [Context](https://stackoverflow.com/questions/20356482/valueerror-path-conf-cannot-end-with).

**Comment by anjakefala** [comment]
Hey @cool-RR,

Oh no! =( This should just silently no-op, not Exception like this. 

Are you able to install VisiData from a branch if I give you the installation command? I'm going to need your help to figure out something that works. The challenge is that this setup.py needs to be able to work for multiple Operating Systems, and I have a Linux machine. I'll find a Mac person to help test, too.

Later today, I'll test removing the `/` on my machine, and push and ask you to check if it works for you (or at minimum silently does nothing).

Are you able to use an older version of VisiData in the meanwhile? Or to modify the setup.py locally and install?

**Comment by cool-RR** [comment]
> Oh no! =( This should just silently no-op, not Exception like this.
> 
> Are you able to install VisiData from a branch if I give you the installation command? 

Yes.

> I'm going to need your help to figure out something that works. The challenge is that this setup.py needs to be able to work for multiple Operating Systems, and I have a Linux machine. I'll find a Mac person to help test, too.
> 
> Later today, I'll test removing the `/` on my machine, and push and ask you to check if it works for you (or at minimum silently does nothing).

Sounds good. 

> 
> Are you able to use an older version of VisiData in the meanwhile? 

Because VisiData doesn't work well on Windows anyway, I mostly use it only on Linux, so I'm okay with it not working on Windows for a while.

**Comment by anjakefala** [comment]
Okay, I ended up having time to test locally. Could you please try `pip3 install git+https://github.com/saulpw/visidata.git@develop`?

1. Does it install without problem?
2. If it does, can you search for the `visidata.desktop` file on your computer, and tell me if you found it installed somewhere?

**Comment by anjakefala** [comment]
https://github.com/saulpw/visidata/commit/cf5a6282b7783b2a4d695e03c3408ccc2dee8e30

**Comment by cool-RR** [comment]
It indeed installs without problem, thank you. 

I couldn't find a file `visidata.desktop` on my `C:` drive. If there's any specific location you'd like me to specifically check, lemme know.

**Comment by anjakefala** [comment]
Great!

> I couldn't find a file visidata.desktop on my C: drive. If there's any specific location you'd like me to specifically check, lemme know.

Yeah, I don't think you would have the manpage installed either. The problem is that `data_files` is not cross-platform by default. It also seems it is deprecated (https://discuss.python.org/t/should-there-be-a-new-standard-for-installing-arbitrary-data-files/7853/17).

I think that is a seperate problem though, which I will add to my list. I might message you for help with testing on Windows. Thanks!

(What it is supposed to do is install the [visidata.desktop file](https://github.com/saulpw/visidata/blob/develop/visidata/desktop/visidata.desktop) such that you can right click on a `.csv` file, and specify that VisiData launches and loads it when you double-click.)
