### ISSUE TITLE
Reconsider use of curses.COLOR_BLUE on black background

### ISSUE THREAD

**Issue by DataBranner** [saulpw/visidata#21]
`curses.COLOR_BLUE` (for [column-separators](https://github.com/databranner-forks/visidata/blob/develop/visidata/vd.py#L87)) seems to me harder to make out on a black background than other colors.

I think other (though perhaps not named) colors can be added using `stdscr.addstr()`, and that would be useful to optimize.

**Comment by saulpw** [comment]
The default is a lighter blue as of 9147e2cd6c84184a819a13a66bd3437f548a9b1a.  There are also 256 colors to play with.
