### ISSUE TITLE
Merge Delimiters

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#210]
Given a TSV file with the following contents:

```
A	B		C
first entry	second entry		third entry
```

(Those are actual tab separations, not spaces.)

Visidata will open this as a 4 column sheet, with an empty column between "B" and "C". Is there a way to tell visidata to merge the delimeters, such that this is seen as only three columns despite the two tab characters between "B" and "C"?

For comparison, `column` does the right thing by default:

```
$ column -t -s $'\t' test.tsv
A            B               C
first entry  second entry    third entry
```

`awk` defaults to thinking the third column is empty, like visidata, but since it accepts regular expressions as delimiters I can achieve the desired behaviour.

```
$ awk -F $'\t' '{ print $3 }' test.tsv



$ awk -F $'[\t]+' '{ print $3 }' test.tsv
C
third entry
```

**Comment by saulpw** [comment]
Hi @pigmonkey.  It's not possible to do what you're asking, but it sounds like there are just same blank columns in your data. Can you use `-` to hide the column(s) or is there another requirement?  If there are many blank columns you could go to the Columns Sheet and select the blank ones with `|^$`, then delete them with `gd`.

**Comment by pigmonkey** [comment]
Yes, I can avoid the problem by hiding the columns, though I sometimes deal with data that has a variable number of delimiters on different rows -- perhaps the header row uses two tabs to separate columns, and subsequent data rows use a single tab.

I think some sort of optional `--merge-delimeters` flag would be a useful addition. This would only be appropriate when there are no empty cells. Something [as simple as this](https://stackoverflow.com/a/40217080) would solve my problem.

**Comment by saulpw** [comment]
One of the other StackOverflow answers from that question you posted gave me an idea. With these commits, now you can put this in your .visidatarc and the `sep` keyword argument will be passed along to pandas.read_csv:

    options.pandas_csv_sep=r'[\t]+'

Then you can run `vd -f pandas foo.csv` and the file will be interpreted as you want.  Note that the filename extension must be `csv`, as the pandas loader looks for `pandas.open_<ext>`.

This option can't be set from the command-line because it is not predeclared in the source.  Let me know if this solves your issue.  It's a small and safe change so we'll include it in 1.5.1.

**Comment by pigmonkey** [comment]
I think the idea will work for me, however I'm getting an error from pandas when I add that line to my `~/.visidatarc` and try to use the development branch.

    pandas.errors.ParserError: Expected 5 fields in line 26, saw 6. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

**Comment by saulpw** [comment]
I guess that means that the first 25 rows had 5 fields, and the 26th had one more. If you can post the data we can try to figure out how to deal with this, and if it's even the right strategy.  An error like this often means that the way we're interpreting the data is wrong, or that it needs cleaning, so Pandas is rightfully strict about this. Either way the raw data is the place to start.
