### ISSUE TITLE
reload-rows messes up melted sheet

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2101]
Open a sheet. Melt it. Then invoke `reload-rows`. The columns get duplicated. Invoke it again, they get duplicated again.

![screenshot_TURING_2023-11-03_110120](https://github.com/saulpw/visidata/assets/56778/386a6ca0-a078-462f-b0b8-2afffbc37ff2)

**Comment by saulpw** [comment]
Thanks, @cool-RR.  Should be fixed now.  What's the use case for `reload-rows` on a melted sheet, anyway?

**Comment by cool-RR** [comment]
Thanks. No real use case, I was just fucking around.
