### ISSUE TITLE
[playback] Playback failing says existing column is missing

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2102]
**Small description**
Playback failing says existing column is missing

**Expected result**
No errors due to columns that exist

**Actual result with screenshot**

https://asciinema.org/a/4Kop1pUil70qoHUWMpoCfvvBW

Using sample_data/benchmark.csv

No error other than in the status log:

- `no "Date" Column on benchmark`
- `visidata/cmdlog.py:263:moveToReplayContext()`

**Steps to reproduce with sample data and a .vd**

```
vd -p /tmp/benchmark_cmdlog.vdj  sample_data/benchmark.csv
```

 cat /tmp/benchmark_cmdlog.vdj
```
#!vd -p
{"sheet": "benchmark", "col": "Date", "row": "", "longname": "type-date", "input": "", "keystrokes": "@", "comment": "set type of current column to date"}
{"sheet": "benchmark", "col": "Quantity", "row": "", "longname": "type-int", "input": "", "keystrokes": "#", "comment": "set type of current column to int"}
{"sheet": "benchmark", "col": "Unit", "row": "", "longname": "type-currency", "input": "", "keystrokes": "$", "comment": "set type of current column to currency"}
{"sheet": "benchmark", "col": "Paid", "row": "", "longname": "type-currency", "input": "", "keystrokes": "$", "comment": "set type of current column to currency"}
```

**Additional context**
Please include the version of VisiData and Python. Latest develop and Python 3.9.2

I will note that on different hosts I see the behavior, in slightly different ways.  Sometimes I need to pipe the input on STDIN to see it.  But in example here it did not require it.  But if you have difficulty reproducing then it could be related to some sort of timing.

**Comment by saulpw** [comment]
Thanks @frosencrantz.  `moveToReplayContext` needed to make sure the sheet was loaded before moving the cursor.  Should be fixed now.

**Comment by frosencrantz** [comment]
Thank you again, Saul!  It looks like it worked.

**Comment by reagle** [comment]
I'm having a similar problem of it choking on a column name during playback. Should this be reopened or should I create a new issue?

In the attached I'm trying to create a macro that will show Reddit dumps consistently. My goal is to hide all columns but 5 and create an iso column.

https://asciinema.org/a/sKvTyL5MfBqdeZCE5t9xTpOTo

```
m
C
| ^(author|created_utc|selftext|title|url)$
gt
c width
ge 0
q
c created
= e2iso(created_utc)
^ created
h
-
m
```

**Comment by saulpw** [comment]
@reagle Please open a new issue, thank you! [I did for you, #2435]
