### ISSUE TITLE
How to make visidata.run() respect the .visidatarc settings?

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#211]
I'm using the mouse-scrolling setting from https://github.com/saulpw/visidata/issues/156 and it works normally but it doesn't work under `visidata.run` from https://github.com/saulpw/visidata/issues/162#issuecomment-400488487 -- scrolling goes the other way than I expect.

**Comment by saulpw** [comment]
Do you have `options.scroll_incr = -3` in your `.visidatarc`?  `visidata.run` does not load `.visidatarc`, so you might have to set it yourself manually.

**Comment by ghost** [comment]
I do have `options.scroll_incr = -3` in my `.visidatarc`. How can I set `visidata.options` to use all of my `.visidatarc` config?

I'll change the issue name to match.

**Comment by saulpw** [comment]
This is how `vd` does it, just `read()`, `compile()`, and `exec()`:

https://github.com/saulpw/visidata/blob/stable/bin/vd#L52

**Comment by ghost** [comment]
Thanks. I've added this to my IPython `c.InteractiveShellApp.exec_lines`, and it works. It might be nice to have a function `visidata.load_configfile()` or an option `visidata.run(df, load_configfile=True)` so this wouldn't be necessary for future users.

```python
textwrap.dedent(
    """\
    def load_visidata_config_file():
        import pathlib

        import visidata

        fnrc = pathlib.Path.home() / '.visidatarc'
        p = pathlib.Path(fnrc)
        if p.exists():
            try:
                code = compile(open(p.resolve()).read(), p.resolve(), 'exec')
                exec(code, globals())
            except Exception as e:
                visidata.exceptionCaught(e)
    load_visidata_config_file()
    del load_visidata_config_file
"""
)

```

**Comment by saulpw** [comment]
With commit c121c49 this has been refactored into `visidata.loadConfigFile(fn)`. This should make it a bit simpler, and will be in 1.5.1.

**Comment by dufferzafar** [comment]
With v2.1 you can use it like so: `visidata.loadConfigFile(os.path.expanduser('~/.visidatarc'), visidata.vd.getGlobals())`

**Comment by mchels** [comment]
I was surprised that the user config is not loaded automatically when visidata is started from python. Since `vd` from the command line automatically loads `~/.visidatarc` if it exists, should python not have the same behavior? Or is there a good reason that they should behave differently?

edit: I believe dufferzafar's one-liner above should be `visidata.settings.loadConfigFile(visidata.vd, os.path.expanduser('~/.visidatarc'))` now. I got some errors (e.g., `*** AttributeError: module 'visidata' has no attribute 'loadConfigFile'`) on visidata 2.8 before changing the command.

**Comment by geekscrapy** [comment]
Give `vd.loadConfigFile` a go

**Comment by saulpw** [comment]
With the above commit, `vd.loadConfigFile()` no longer needs a filename argument and will use `options.config` by default.  This should make it a bit nicer to use.

@mchels  Config loading may be expensive and may not be desired within a single REPL session; e.g. if you change an option that you set in your config, it seems to me that subsequent calls to `run()` should keep the changed option.

But we could add another `vd.run_with_config()` (or `vd.run2()` or `vd.r()` or I'm open to ideas) that calls `vd.loadConfigFile()` and then calls `vd.run()`.

**Comment by mchels** [comment]
Or maybe just add a parameter `vd.run(load_options=True)` to keep the api simple. That would make it transparent to the user that the config deliberately isn't loaded by default.

edit: or `load_config=True` or whatever is more in line with existing terminology.
