### ISSUE TITLE
[unzip-http] RecursionError when opening a file within a remote zip file

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2110]
**Small description**

RecursionError when opening a file within a remote zip file.  e.g. `vd https://github.com/jart/cosmopolitan/releases/download/3.0.1/cosmos-3.0.1.zip` and press Enter.

**Additional context**

The visidata unzip_http is no longer a simple copy of unzip_http.py from the upstream unzip-http project.  It has two `def open()` functions, and the second one calls `self.open` which is just calling itself.

This was broken in a1affe7d8, which renamed `open_text` to `open`.

**Comment by frosencrantz** [comment]
Referenced in #2105.

**Comment by anjakefala** [comment]
The completion of the fix was in https://github.com/saulpw/visidata/issues/2127
