### ISSUE TITLE
[graph] zoom-in and zoom-out misaligned

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2111]
### Discussed in https://github.com/saulpw/visidata/discussions/2106

Zooming in and then back out of a graph should take you back to your original starting point. Now, it goes slightly off until eventually the plot disappears off the screen.

## Expected Behavior

This is the expected behavior when you zoom-in and out on a graph with your mouse-wheel:

![correct](https://github.com/saulpw/visidata/assets/7489659/53a7f0a8-451d-4606-851d-b7c67e5cd6da)

And this is the develop behavior:

![incorrect](https://github.com/saulpw/visidata/assets/7489659/3df773cf-184a-4a46-89f7-1c3628927594)

**Comment by isosphere** [comment]
Zooming in with the mouse or keyboard triggers `incrZoom`, it might behave more predictably if the zoom level were modified linearly (`+`) rather than geometrically (`*`):

https://github.com/isosphere/visidata/blob/216bb5aab865375cc9017e56d85f4d124dab6813/visidata/canvas.py#L523-L527

Combined with floating point imprecision that might cause drift; a `Decimal` type for the zoom properties could help with that. 

I'm having trouble reproducing the behaviour or I'd try it, I haven't used plots much yet.

**Comment by saulpw** [comment]
@isosphere This was working fine before with geometric zoom.  I tried linear zoom and it didn't 'feel' right.  This isn't a precision issue; likely just an off-by-one error from a change we made to the canvas in ~august or so.

**Comment by midichef** [comment]
@anjakefala
I am leaving a comment here so you can assign this to me, as you asked in the Discussion related to this.

I've figured out what's happening here. `Graph` and`InvertedCanvas` use a different coordinate system from Canvas. Their y-axis grows in the opposite direction and starts from a different origin point. `zoomin/out-mouse` incorrectly rely on `Canvas.fixPoint()`, which uses the y-coordinate system for `Canvas`. `InvertedCanvas` needs its own version of `fixPoint()`. I'm testing a fix now.

If there are more such bugs in `graph.py` discovered in the future, the fix would follow this general rule: look for functions being called in `graph.py` that are in `Canvas` that involve y-coordinate calculations. Override them in `InvertedCanvas` and modify them to use inverted y-coordinates.

**Comment by anjakefala** [comment]
> If there are more such bugs in graph.py discovered in the future, the fix would follow this general rule: look for functions being called in graph.py that are in Canvas that involve y-coordinate calculations. Override them in InvertedCanvas and modify them to use inverted y-coordinates.

This was such a helpful write-up, thank you!
