### ISSUE TITLE
When pressing Ctrl-o from a cell to edit text in default editor, I get the error "Permission denied.

### ISSUE THREAD

**Issue by kalyan860** [saulpw/visidata#2118]
**Small description**
I am on windows OS. When pressing Ctrl-o from a cell to edit text in default editor, I get the error "Permission denied. C:/Users/MyUserName/AppData.... etc. I am unable to see or copy the rest of the error message.

**Expected result**
Expected result will to open the cell text in my default editor, neovim. 

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
![image](https://github.com/saulpw/visidata/assets/95114049/38cd7a78-333f-401c-8d95-fe5314bb176c)

**Steps to reproduce with sample data and a .vd**
Pressing e on a cell to edit it, and then press Ctrl-o

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
#!vd -p
{"longname": "open-file", "input": "test.xlsx", "keystrokes": "o"}
{"sheet": "test", "col": "", "row": "\u30adtest", "longname": "open-row", "input": "", "keystrokes": "Enter", "comment": "open current row with sheet-specific dive"}

**Additional context**
Please include the version of VisiData and Python.
Python 3.11.1
saul.pw/VisiData v2.11.1

**Comment by saulpw** [comment]
Thanks for filing the issue, @kalyan860.  We need to close the file before reopening it on Windows, as per https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file.  Should be fixed now on develop.

**Comment by kalyan860** [comment]
Thanks for the response, but what is the solution  now? Do  I have to download the develop branch?

**Comment by anjakefala** [comment]
@kalyan860 Yes!

If you installed VisiData via pip, you can use `pip3 install git+https://github.com/saulpw/visidata`.

We are planning to ship the next release, v3.0, in December.
