### ISSUE TITLE
Does the "q" command delete the current saved sheet?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#212]
Hi,
when I create a new sheet, using a filter applied to an existing one, and then use "q" to go back to original sheet, I do not find the new on in the list of the sheets.
Does the "q" command delete the current saved sheet? If yes in the manual I think it's better to change "q quit current sheet" in something like "q quit (and in some cases delete) current sheet"

In this video an example https://www.youtube.com/watch?v=-zvbqzcVaj4&feature=youtu.be&hd=1

Thank you

**Comment by saulpw** [comment]
That is correct, `q` drops the current sheet.  But it is still visible in the graveyard sheet with `gS` and you can resurrect it until it gets garbage collected.

You can also use `Ctrl+^` to toggle the last two sheets (like in vim).  Do you find yourself losing sheets often?

**Comment by aborruso** [comment]
Hi @saulpw `gS` is the solution, I had no idea of it.

Probably a note about `q` with `quit and drop`, or a new FAQ question could be useful. If you agree I can write a draft of it.
