### ISSUE TITLE
How do I use the confirm dialog?

### ISSUE THREAD

**Issue by kalyan860** [saulpw/visidata#2120]
**Small description**
For eg., I opened a file called test.xlsx. Made few changes and then CTRL+S and save it as test.xlsx again, overwriting the same file. But a confirm pop up launches and becmoes unresponsive. 

**Expected result**
When I click on the confirm pop up button for yes, it should save the file.

**Actual result with screenshot**
![image](https://github.com/saulpw/visidata/assets/95114049/9590944e-7a97-4858-a47f-1917270362d6)

**Steps to reproduce with sample data and a .vd**
#!vd -p
{"longname": "open-file", "input": "test2.xlsx", "keystrokes": "o"}
{"sheet": "test2", "col": "", "row": "\u30adtest2", "longname": "open-row", "input": "", "keystrokes": "Enter", "comment": "open current row with sheet-specific dive"}

**Additional context**
Please include the version of VisiData and Python.
saul.pw/VisiData v2.11.1
Python 3.11.1
uname: windows32
Locale
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

**Comment by anjakefala** [comment]
@kalyan860 Does typing `y` work for confirming yes in the pop-up?

**Comment by saulpw** [comment]
Also clicking now works on develop, please try using the develop branch.

**Comment by anjakefala** [comment]
https://github.com/saulpw/visidata/issues/1740

**Comment by kalyan860** [comment]
> @kalyan860 Does typing `y` work for confirming yes in the pop-up?

Yes, That does work. Thank you.
