### ISSUE TITLE
delimiter specificartion in hex

### ISSUE THREAD

**Issue by GiulioCesare** [saulpw/visidata#2121]
Hello VD team.
I have many utf8 text files with 0x01 (ASCII SOH Start Of Header) as field delimiter.
Reading the documentation I could not find a way to specify such a delimiter.

The best I could come up with was using the backslash. Eg. "vd --csv-delimiter=\| tb_titolo.out.bytes" 
But the file I handle are huge and cannot convert 0x01 to \|, also because the data itself contains pipe characters

I tried "vd --csv-delimiter=\ tb_titolo.out.bytes" where the funny character is the SOH, but the deimiter was not recognized.
Is there any way this could be accomplished?
After all 0x01 (SOH) is a pure ASCII character, even though  a particular one.

Is it possible to specify the delimiter with an hex value for the character? Liike "vd --csv-delimiter=\x01 tb_titolo.out.bytes"

Thanks for any help or suggestion

Giulio Cesare

**Comment by saulpw** [comment]
`vd --delimiter=$'\x01' -f tsv tb_titolo.out.bytes` should work.  You probably want the tsv loader (since the data isn't quoted or escaped like csv data is) with the `delimiter` option, and you need to use the `$'...'` bash ANSI-C quoting to get the proper character into the option.

**Comment by GiulioCesare** [comment]
Thank you Saul.
It works great.
