### ISSUE TITLE
AttributeError: property 'keyColNames' of 'CsvSheet' object has no setter

### ISSUE THREAD

**Issue by isosphere** [saulpw/visidata#2122]
Context: `SheetsSheet`

Use case: opening many files that have common columns

I'd like to be able to copy the `keyColNames` from one sheet to all sheets, to avoid doing it manually or otherwise concatting them together with an external tool. 

A `zy` and `zp` could hypothetically do this, if the setter were implemented. Then I could join them in `visidata` relatively quickly and easily. 

I think this would be especially handy when working with mixed data sources (CSV, SQL, etc.).

**Comment by saulpw** [comment]
This should be implemented now!  Thanks for the suggestion.
