### ISSUE TITLE
Saved datasource configuration for quick connection (speed dial)

### ISSUE THREAD

**Issue by isosphere** [saulpw/visidata#2123]
I'd like to be able to define datasource details (hostname, port, username, password, type, etc.) in a configuration file, for easy connection later. An RDS databsae for example has a very long hostname, and I don't want to have to copy and paste it all the time.

Ideally it would be easy to open these in the user interface, so that multiple datasources can be opened ad-hoc for joining, etc. 

Perhaps via a reserved URL schema like saved://db-name

**Comment by saulpw** [comment]
Hi @isosphere, thanks for the suggestion!  Here's a quick implementation that you can put in your .visidatarc to try out:

```
vd.speedDial = {}

@VisiData.api
def openurl_saved(vd, p, filetype=None):
    if p.name not in vd.speedDial:
        vd.fail(f'no saved datasource named "{p.name}"')
    return vd.openSource(vd.speedDial[p.name])

@BaseSheet.api
def save_speed_dial(sheet, speedname):
    with Path('~/.visidatarc').open(mode='a') as fp:
        print(f"vd.speedDial['{speedname}'] = '{sheet.source}'", file=fp)

vd.addCommand('', 'save-speed-dial', 'save_speed_dial(input("save to speed dial as: ", value=source.name))', 'save source to speed dial')
```

Let me know how this works for you!  If other people want to use it and we settle on the workflow and polish the helpstrings a bit, we can certainly add this as a VisiData feature in the future.

**Comment by isosphere** [comment]
I've tweaked the above slightly - `vd` does not extend `addCommand` but `BaseSheet` does, and it's a bit safer if the saving bit  outputs a newline before the new speeddial item:

```python
vd.speedDial = {}

@VisiData.api
def openurl_saved(vd, p, filetype=None):
    if p.name not in vd.speedDial:
        vd.fail(f'no saved datasource named "{p.name}"')
    return vd.openSource(vd.speedDial[p.name])

@BaseSheet.api
def save_speed_dial(sheet, speedname):
    with Path('~/.visidatarc').open(mode='a') as fp:
        print(f"vd.speedDial['{speedname}'] = '{sheet.source}'\n", file=fp)
        
BaseSheet.addCommand('', 'save-speed-dial', 'save_speed_dial(input("save to speed dial as: ", value=source.name))', 'save source to speed dial')
```

I can then open a speed-dialed item using a URL like `saved://speed-dial-item-name`. 

Thank you.

**Comment by saulpw** [comment]
Cool, @isosphere !  Yeah, `vd.addCommand` was added as an alias for `BaseSheet.addCommand` since the last release, and will be in 3.0.  Thanks for calling out the actual usage too.
