### ISSUE TITLE
CSV: how to read empty cells as nulls?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#213]
Hi,
when I open the below CSV, the empty cells are not nulls and I cannot use the `f` command.
I have the same result using `vd --null-value="" input.csv`. I'm using vd 1.4.

How to convert these to nulls?

Thank you

```
fieldA,fieldB
a,b
a,
,b
```

**Comment by saulpw** [comment]
Hm, when I use `--null-value=""`, the `f` command works fine for me in both 1.4 and 1.5.  Are you sure your data has completely empty strings?

**Comment by aborruso** [comment]
Hi @saulpw you are right, it works.

I was blocked because I did not see the `Ø` symbol, as you have below. Why I do not see it?

Thank you

![image](https://user-images.githubusercontent.com/30607/48892318-15725e80-ee3e-11e8-9974-9a88a07f9dfc.png)

**Comment by saulpw** [comment]
The null symbol is currently only shown for `None` values (see [vdtui.py:getCell](https://github.com/saulpw/visidata/blob/stable/visidata/vdtui.py#L2136)). I agree, it would be nicer if it used the same isNullFunc as fill/rollup; I will see about making that happen when I refactor the display code.  For now, it is too much of a performance risk to change the existing code for this nicety.  Sorry about that :/

**Comment by dufferzafar** [comment]
@saulpw Is there an easier way replace some value with nulls? I want `<null>` string to be treated as Null/None.

I first tried something like `=` (addcol-expr) with `column_data.replace('<null>', None)` but ofc that fails because 2nd param should be string as well.

Currently i use: `None if column_data == '<null>' else column_data`

**Comment by saulpw** [comment]
@dufferzafar treated like null, in what context?  For aggregation, you can just set `--null-value='<none>'`.  Otherwise you can go to the column with those null strings, select all the rows with those strings (using `|` or otherwise), and then `gzd`.
