### ISSUE TITLE
New binding for `help-hint` clobbered `menu-help`

### ISSUE THREAD

**Issue by isosphere** [saulpw/visidata#2130]
**Small description**

CTRL+H is the bound key for menu-help. In 0a100054178991d5a9359d49e224b1ca5443fd0f, a binding for CTRL+H was created for `help-hint`. This is now the primary function of this key combination in development; `menu-help` can't be triggered.

**Expected result**
I should be able to trigger the menu

**Actual result with screenshot**
![image](https://github.com/saulpw/visidata/assets/163370/186b0196-a4e8-47fb-a8a3-7bff341bc990)

**Steps to reproduce with sample data and a .vd**
Press CTRL+H

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Installed from git, https://github.com/saulpw/visidata/commit/0e1afd8b7d2979eb2b136df45a428974b8124428
Python 3.10.4
Windows 10

----

I've fixed this for me by adding the following to my `.visidatarc`:

```
BaseSheet.bindkey('Ctrl+H', 'menu-help')
```

**Comment by anjakefala** [comment]
My proposal is that since folks already have a muscle memory of `Ctrl+H` opens up the Help tab in the menu, to move `help-hint` to use `Alt+h` instead.

(Currently, `menu-help` is bound to both `Ctrl+H` and to `Alt+h` to mirror how the other tabs can be quickly opened.)

**Comment by anjakefala** [comment]
I believe this got resolved by educating that the binding for `menu-help` is now `Alt+H`, leaving `Ctrl+H` for `help-hint`.

@saulpw can this be closed?

**Comment by saulpw** [comment]
> I believe this got resolved by educating that the binding for menu-help is now Alt+H, leaving Ctrl+H for help-hint.

This is the direction we're headed, so all our docs should start using `Alt+H`.  But we also reverted back to the previous behavior and are letting it stay a legacy keystroke, until help-hint becomes more useful.  Agreed we can close it for now.
