### ISSUE TITLE
JSONL converts float to int, based on formatting of first line

### ISSUE THREAD

**Issue by dpercy** [saulpw/visidata#2131]
I have a JSON log file containing floats, but where any floats that have zero fractional part are formatted without the decimal point:
```
$ cat tmp.jsonl 
{"a":0}
{"a":0.1}
```

VisiData guesses they're all integers:
```
$ vd tmp.jsonl
```
![Screenshot 2023-11-20 at 2 37 24 PM](https://github.com/saulpw/visidata/assets/349909/8724f9bb-d9b1-4c5c-9892-c7cc665ac0e7)

I think it's guessing based on the first line, because when I change the order it correctly guesses the type to be float:
```
$ sort -i tmp.jsonl | sponge tmp.jsonl 
$ cat tmp.jsonl 
{"a":0.1}
{"a":0}
$ vd tmp.jsonl
```
![Screenshot 2023-11-20 at 2 38 03 PM](https://github.com/saulpw/visidata/assets/349909/c29b1d56-847c-4ffa-9390-bf6c78110598)

I wonder if this was also the cause of https://github.com/saulpw/visidata/issues/1698.  If the decision is based on the first line, then you may can get different results based on which part of the large log file you sample.

**Comment by saulpw** [comment]
Okay, as the JSON spec itself only has one Number type (decimal, or floating point), I changed the JSON loader to always infer the type for columns with numeric values as "float".
