### ISSUE TITLE
Feature request: `.ron` file support

### ISSUE THREAD

**Issue by jfaz1** [saulpw/visidata#2143]
Been using visidata for `.csv` and `.json` and it's been great! Would love if we could get some [`.ron` support](https://github.com/ron-rs/ron) as well:

`.ron` is a data serialization format similar to `.json`/`.yaml` that's quite popular in the Rust world, it looks like:
```rust
GameConfig(
    window_size: (800, 600),
    window_title: "PAC-MAN",
    fullscreen: false,
    mouse_sensitivity: 1.4,
    key_bindings: {
        "up": Up,
        "down": Down,
        "left": Left,
        "right": Right,
    },
    difficulty_options: (
        adaptive: false,
    ),
)
```

I recently migrated from `.json` to `.ron` for the game I'm working on, and I miss being able to edit the file in `visidata`.

**Comment by saulpw** [comment]
Hey @jfaz1, I've never heard of the `ron` format before.  Is there a python package that parses and/or saves data in this format?

**Comment by jfaz1** [comment]
Admittedly I know very little Python, but there is this library:
https://github.com/cswinter/pyron
It has an example converting `.yaml` to `.ron`; whether it meets your criteria I have no clue though! :laughing:

**Comment by saulpw** [comment]
Alas, that library has no license, and is written in Rust.  If anyone can find or write some Python code to parse this Rusty Object Notation format, we'd be happy to create a loader for it and integrate it into VisiData.

Kondo'ed for now.
