### ISSUE TITLE
[windows] Frequency Histogram character width variance

### ISSUE THREAD

**Issue by isosphere** [saulpw/visidata#2144]
**Small description**

I created a frequency histogram on a column. There's a huge disparity between the size of the histogram bar characters when selected and when unselected. 

If I use the resize column to max functionality, it operates on the smaller selected size, so the bars always exceed the max width.

**Expected result**

- Selecting a row should not change the size of the histogram bars.
- Resizing a histogram column to max should contain all histogram bars within the confines of the table

**Actual result with screenshot**
![image](https://github.com/saulpw/visidata/assets/163370/b5b02a0f-fdd9-4939-b455-cf4aaff8dec9)
![image](https://github.com/saulpw/visidata/assets/163370/fabb80d5-6efe-401f-b2af-bdb5a84b6c10)

**Steps to reproduce with sample data and a .vd**
Open any table that has a category column you can run a frequency distribution on. 

**Additional context**
Running https://github.com/saulpw/visidata/commit/34aaa9238fe9f8549ee379d1b81f422f467ceb58 on Windows 10.

**Comment by saulpw** [comment]
I'm not sure if other Windows users are experiencing this; it might be your specific font or terminal.  There's not much we can do, unfortunately; if it's all Windows users, we can set the `disp_histogram` character on Windows back to `*`.  If it's just your particular setup, you can add this to your .visidatarc:

    options.disp_histogram = '*'

**Comment by isosphere** [comment]
The screenshot font is [Iosevka](https://github.com/be5invis/Iosevka); I have retested with the latest release of that font - no change. 

Here's the result with Consolas, a typical Windows default fixed width font:

![image](https://github.com/saulpw/visidata/assets/163370/bcb42147-0bd6-48d7-bd2a-9fe0aa8e8c2b)
![image](https://github.com/saulpw/visidata/assets/163370/f5bb6426-d95d-454b-bd7b-a281f1454756)

Dang. Might go for the character change, myself. 

----

For future reference and other Iosevka users, "⣿" looks rather good as an alternative. Here's how to do it:

`.visidatarc`
```
# Ioveska shows the default character inconsistently when highlighted
options.disp_histogram = '\u28FF'
```

... and how it looks:

![image](https://github.com/saulpw/visidata/assets/163370/37f8831b-d14b-4c54-ba34-583b49f06146)

This character is a more direct replacement:
```
options.disp_histogram = '\u2588' # "full block"
```
... but it fills the entire character block. When selected the inverted colour makes it disappear due to a lack of any contrasting outline. 

----

`\u2593' might look better than '\u28ff'; it offers a bar-like shape with some contrast when highlighted:

![image](https://github.com/saulpw/visidata/assets/163370/0787b4a6-7596-4b57-9479-0922c61de62f)

**Comment by saulpw** [comment]
Ah, yeah.  Iosevka looks really nice, but of course the issue with using more exotic Unicode characters is that not every font will render them adequately.  I do like how the new box character looks in all the default fonts (thanks @daviewales for finding it!) so you'll have to change it locally.
