### ISSUE TITLE
How to add a column with row number?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#215]
Hi,
how is it possible to add an "ID" column with row number cell values?

Thank you

**Comment by anjakefala** [comment]
Hi @aborruso! 

Is this what you needed?

1. Press `za` to create a blank new column. Set the column name to `ID`.
2. Move the cursor to the newly created column.
3. Press `gz=` followed by `range(a)` where instead of *a*, you type the number of rows.

**Comment by aborruso** [comment]
When I write gze, I have

![image](https://user-images.githubusercontent.com/30607/49345321-86f2ae00-f683-11e8-8720-e4c7ae23c379.png)

I'm using visidata 1.4.

Thank you

**Comment by aborruso** [comment]
Hi, probably it's `gz=` and it works.

But in the manual there is

> gz= expr         set current column for selected rows to the items in result of Python sequence expr

But it works also when you have selected no rows.

Probably it's necessary a manual edit.

Thank you

**Comment by saulpw** [comment]
Hi @aborruso!  Most commands that work on "selected rows" will work automatically on "all rows" if none are selected.  This is for our convenience and it feels intuitive (to me, anyway :)

**Comment by ghost** [comment]
For people coming to this in the future, there's now a built-in visidata command to add a column with row numbers. Just press `i`. (Search `iota` in the built-in help)

**Comment by neo1312** [comment]
if I use i the index begins at 1, how can I start from other number, for example 10 instead of 1??  thank you

**Comment by saulpw** [comment]
@neo1312 set `options.incr_base = 10`, for instance.

**Comment by neo1312** [comment]
@saulpw it works great !
