### ISSUE TITLE
Get VisiData commit when running `vd --version`

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2155]
For #2154 I wanted to get the exact commit of the VisiData version that I have so you'll know the exact version. Unfortunately when I run `vd --version` it just says: 

```
saul.pw/VisiData v2.12dev
```

Would be cool if it showed the commit hash.

**Comment by saulpw** [comment]
How did you install this version of VisiData, @cool-RR?

**Comment by anjakefala** [comment]
@saulpw It was `v2.12dev` before we changed the version to `v3.0dev`. It seems like he has an old `develop`!

**Comment by saulpw** [comment]
@anjakefala I'd like to know whether he used `pip` directly on the repo url, or `pip -e` on a local checkout, or something else.

**Comment by cool-RR** [comment]
I installed it with something like: 

```
pip install git+https://github.com/saulpw/visidata@develop --upgrade
```

Actually at first I installed the `develop` branch like above and it get the `v3.0dev` VisiData, but there were bugs with it, and I wasn't sure whether these were actual bugs or just clahses with my `.visidatarc` file, so I decided to stay on an older version until 3.0 stabilizes. So I installed again but instead of specifying `develop` I specified a specific commit, which I can't remember now.

**Comment by midichef** [comment]
@cool-RR 
Here's a bash script that will identify what visidata commit is in your pip directory. It puts files in `/tmp`.
Edit `PIP_DIR` and `TMP_DIR` to match your setup, and `SINCE_DATE` to adjust how far back you search.

[vd-pip-search.bash.txt](https://github.com/saulpw/visidata/files/13598426/vd-pip-search.bash.txt)

And in the future, it is faster to find the commit if you install visidata with -e, via `pip install -e 'git+https://github.com/saulpw/visidata@develop#egg=visidata' --upgrade`
which keeps the git source files around indefinitely. Then this script will tell you what commit you installed.
```
#!/usr/bin/python3
# source:  https://stackoverflow.com/a/49971670
import os
import subprocess
import visidata
output = subprocess.check_output(('git', '-C', os.path.dirname(visidata.__file__), 'log', '-1', '--format=%H %cd'))
output_str = output.decode(encoding='utf-8', errors='strict')
# print short hash, then full hash and time
print(output_str[:7], output_str)
```

**Comment by cool-RR** [comment]
@midichef Thanks for the workaround (and it's a pretty crazy workaround...) I would like to just have that information shown in `vd --version` though.

**Comment by cool-RR** [comment]
Now that I think about it, this sounds too complicated to implement, so I'll close this issue and next time install using your line. Thanks @midichef .

**Comment by saulpw** [comment]
Yeah I've been thinking about how to implement this, and haven't come up with a good way.  Best is to just use `pip install -e` and then you can get the commit with a simple `git status` in the working directory.
