### ISSUE TITLE
Status: reflect when file is saved

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2157]
When I save a file, the status says "saving ..." but doesn't reflect when it's done and when I can safely quit. I would like it to say "saved" when it is safely saved.

saul.pw/VisiData v3.0dev

**Comment by saulpw** [comment]
We can add a "comfort" status for this, but you're already safe; as per https://github.com/saulpw/visidata/issues/389#issuecomment-596347425, VisiData will still finish saving the file after you've quit.

**Comment by geekscrapy** [comment]
I'd like this too. Tbh I had a feeling something was missing during the save process, just never realised it might be something like this. Good suggestion @reagle

**Comment by saulpw** [comment]
9 of our most common savers already had this status message.  So implementing this was actually -8 lines of code.  Thanks for the suggestion, @reagle!
