### ISSUE TITLE
How do I choose the theme?

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#2158]
Following the documentation on the [customizing visidata page](https://www.visidata.org/docs/colors/), i was expecting to be able to go to `View > Set theme` to change the theme, but this menu option does not exist for me.  Furthermore, using `--theme` on the command line gives the warning `setting unknown option theme`, and the searching the options sheet for `theme` returns no results.  

I'm using version `saul.pw/VisiData v2.11` on debian (apt shows `Version: 2.11-1`).  `python3 --version` is `Python 3.11.2`.

**Comment by anjakefala** [comment]
Hi @iwouldrathernotusegithub!

This feature is part of `develop` VisiData, and will be released in the next version, v3.0. The plan is to ship by the end of the year.

To install `develop` via Python, use `pip3 install git+https://github.com/saulpw/visidata`.

**Comment by ghost** [comment]
Oh cheers, sorry for the confusion.  In that case i wonder if the documentation website could make it clearer that they are talking about the `develop` version and not the latest stable release?
