### ISSUE TITLE
[parquet] can't load parquet directory anymore: `IsADirectoryError`

### ISSUE THREAD

**Issue by mr-majkel** [saulpw/visidata#2159]
**Small description**

Hi @saulpw @anjakefala @takacsd - it seems that forcing opening the path as file with `.open()` - introduced with #2133 - breaks the use case where the multiple parquet files are stored in a directory, and this directory is then read by visidata. This is common with Hive partitioning or when working with spark. A simple fix would be to check if the path is a directory with `os.path.is_dir()` and then retaining old behavior of passing it as a string to `read_table()`. If it is not an existing directory, we move to the new way of opening as a binary buffer.

I have already added this workaround to my clone of visidata, and it fixes my issue, but maybe you have some better ideas how to handle it instead of `if-else` statement in the `ParquetSheet`.

**Expected result**

```bash
vd -f parquet parquet_dir
```
should load a parquet into visidata

**Actual result with screenshot**
![image](https://github.com/saulpw/visidata/assets/9008816/f262c403-704e-47f0-8994-68bf214b3db6)

**Additional context**

```bash
# freshest develop
visidata@9fd728b72c115e50e99c24b455caaf020381b48e

pyarrow==12.0.0
python 3.10.2
```

**Comment by saulpw** [comment]
This is perfect, thanks for the report and the fix @mr-majkel !
