### ISSUE TITLE
How to read values from another column

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#216]
Hi,
I have tried with `gz=` and than the name of column, but I have "NameError: name 'MyInputField' is not defined".

I need to do it, after creating a new empty one with `za`.

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, you want `g=`.  `gz=` sets the value according to a Python iterator, whereas `g=` sets the value according to a Python expression.

**Comment by aborruso** [comment]
@saulpw thank you.

But is there a way to do it. I'm able to do only creating new columns.

**Comment by saulpw** [comment]
@aborruso can you explain what you'd like to do exactly?

**Comment by aborruso** [comment]
Hi @saulpw ,
I'm able to create new column using expression:

- first `=`;
- then `myField1.lower()`.

But how to apply lower() to a column that already exists? If I select the column `myField1`, and than `gz=` and write `lower()`, nothing happens.

I'm adding another related question. How to do in example a global search and replace, how to apply the same expression to all fields of a sheet?

Thank you

**Comment by aborruso** [comment]
Hi @saulpw I have solved for the first:

- first `g=`
- then `myField1.lower()`

But why in the reference there is "set current column for selected rows to result of Python expr"? It works for all rows even if I have not selected any rows.

I would change it in "set current column to result of Python expr. If there are some selected rows it apply expr only to these".

Thank you

**Comment by saulpw** [comment]
Glad you were able to solve it!  The manpage does say "In most cases, commands that affect selected rows will affect all rows if no rows are selected."  Maybe that should be worded better, or in a more prominent place, what do you think?

**Comment by aborruso** [comment]
> Maybe that should be worded better, or in a more prominent place, what do you think?

@saulpw I have not smart solution :(
I read that part and I did not use it, because it was not my case, I had not selected any rows. My fault, but it's a reach and long manual.

The only idea in this moment is to write for every line something like my example above. I must mumble.

Is there a way to do a global (for all fields) search and replace? Do I open another issue?

Thank you

**Comment by saulpw** [comment]
There is no way to do global search and replace yet.  You could put this in your .visidatarc:

```
def globalSearchAndReplace(cols, rows, rex):
    for c in cols:
        setValuesFromRegex(c, rows, rex)

Sheet.addCommand('gz*', 'setcol-subst-all', 'rex=input("transform column by regex: ", type="regex-subst"); globalSearchAndReplace(visibleCols, selectedRows or rows, rex)')
```

Then `gz*` can be your global search and replace.
