### ISSUE TITLE
[vd/vdj/vdx/vds] Update documentation

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2161]
I understand VisiData supports the following formats:

- `.vd` is the first cmdlog format, which is just a tsv of the cmdlog (to be eventually deprecated)
- `.vdj` is the next generation cmdlog format in jsonl
- `.vdx` is an experimental format which is just text of commands, not a table
- `.vds` is the saved sheets including all data (opens as sheet of sheets)

The following pages will need to be updated.

- [Supported Formats | Docs | VisiData](https://www.visidata.org/docs/formats/)
	- add `.vdj` and `.vdx`
- [Quick Reference Guide | Docs | VisiData](https://www.visidata.org/docs/man/): 
	- `.vdj` is associated with `^D` but `.vd` is used in subsequent example
	- `.vds` (and `.vdx`) need to be added
- [Save and Restore | Docs | VisiData](https://www.visidata.org/docs/save-restore/)
	- replace `.vd` with `.vdj`; explain the differences, while adding  `.vds` (and `.vdx`)

**Comment by saulpw** [comment]
Hey @reagle, thanks for finding these and calling them out clearly and explicitly!  It made it that much easier to do.  We're going to do a docs push after 3.0, so please file more like this if/when you see them!
