### ISSUE TITLE
[loaders] Plugin Idea: Simple  general way to create aliases and formats from CLI tools

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2167]
What if there was a simple no code way to add reading formats easily based on either simple aliases or with command line filter that converts the data into a format that VisiData already handles.  It would be useful if there was a way to do simple aliases via a configuration file:

- Zip-like files like `whl`: https://github.com/saulpw/visidata/discussions/1539
   - Solved this way: https://github.com/saulpw/visidata/blob/develop/visidata/loaders/archive.py#L29-L32
- Using pandoc to convert Markdown tables to html:  https://github.com/saulpw/visidata/issues/1758
- Jc formats: https://github.com/kellyjonbrazil/jc/discussions/301
- Ability to use format name to specify format options `fixed6` or `fixed_noheader` to say to limit fixes format with 6 columns or fixed format with no headers.

It seems like the configuration file would have a row per alias, you would need these details (columns):

- Alias: Input format name ‘whl’ (required)
- Output format “zip” (required). 
   - This would need to be a format that VisiData already know how to parse.
- Format options dict of format options (optional)
   - For the fixed format aliases above you would need to be able to specify the headers as 0, or the maximum columns 
- Command line filter for reading (optional)
   - For formats that need to be converted like using pandoc to convert markdown format to html
   - Maybe there would be the need to have separate read and write commands.  I'm not sure how well this works for write, but I think reading should work well with a command.
- Guesser Regex or Python Expression
   - Maybe provide a way to allow VisiData  to identify this format.
- Mime details
   - Maybe allow loading from the mimetype details.

If you want to propose a command, please include:

I don't think there would be any new commands, since this would be a no code solution for adding new data formats that can be added.  You might want a to have a command to open sheet with the configuration file. 

- [] what should the helpstring say
- [] where should this command go in the menu system

**Comment by frosencrantz** [comment]
Two more thoughts:
- An additional column could point to a playback script or a macro to execute after loading the file.
- This could also be used as a summarizing filter for filetypes.  For example, to generate summary statistics about a datasource.  So the input file type name might be called "summ", the filter command might be to run the data through `mlr`, is has several commands to provide statistics about an input file or use pandas to provide a summary.

**Comment by saulpw** [comment]
Hey @frosencrantz, thanks for sharing this idea.  Do you think there are a lot of pseudo-formats like this, that can be defined entirely descriptively?  And you know how it is, it will have bugs and will need something extra to handle some simple case we hadn't thought of, so it becomes an additional feature that wants to be maintained and improved.  In general this is why VisiData can be extended with arbitrary Python, so we don't have to make up a new DSL ourselves.

Anyway, I'm open to considering a plugin or something that makes this easier, but I'm not sure it's overall less work to implement/document/etc this no-code solution, than to just add code for additional formats.  Interested in others' thoughts.

Kondo'ed for now.

**Comment by frosencrantz** [comment]
I do think this makes sense as a plugin.  The `jc` command has several hundred converters now, and there are multiple formats that PanDoc can convert. Also, it would be useful to have some basic aliases for things like saying noheaders, or limiting fixed to a max number of columns.
