### ISSUE TITLE
Make the tab key move cursor to adjacent cell like excel

### ISSUE THREAD

**Issue by kalyan860** [saulpw/visidata#2169]
Although visidata is excellent to summarize data, and make quick edits easily on data using vim like keys, it is cumbersome to entry data. My use case is that I create lot of short tables for personal use, for eg to keep track of payments I made this month etc. For that, I need to enter data manually from scratch. I don't want to do this in excel as it's slow and bloated and makes me leave command line. 

So, I wish visidata has more easier, friendlier editing. Currently tab key is for autocomplete which is rarely used. It is much better to make tab behave like excel to move to adjacent right cell for quick editing. And shift+tab to move to the cell left. Also, if tab is pressed at the end of a row, cursor should go to the first cell in next row like in excel.  

Currently shift + arrow keys are used to move in insert mode, however this is cumbersome as it requires leaving the homerow constantly. If tab cannot be changed, some key combo on the home row should be used to move cells instead of tab.

**Comment by saulpw** [comment]
You're right, @kalyan860.  Autocomplete doesn't even work when editing a cell anyway.

Your wish is granted.

**Comment by kalyan860** [comment]
Thank you
