### ISSUE TITLE
How to set cells as null and use f command?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#217]
Hi,
I would like to apply `f ` command to the null values of a column of this table.

But I'm not able to make it works. My cells are completely empty.
I run vd with `vd --null-value="" table.csv`.

Thank you

![image](https://user-images.githubusercontent.com/30607/49346074-63346580-f68d-11e8-8156-f0f5cb0bad78.png)

**Comment by saulpw** [comment]
Hi @aborruso, this seems like a duplicate of #213, which you filed 10 days ago.  Does it seem to work on the other dataset, but not this one?  In that case, we would need to know more about this dataset.  Can you provide a test dataset that exhibits this behavior?

**Comment by saulpw** [comment]
Ok, I think I see what is going on.  You have only the blank cells selected; you would need to select the previous values you want it to use also.  Basically the process is: select all of the rows, then unselect rows which you don't want to be filled (if any), then `f`ill.  But you're right, this is a bit counter-intuitive; I will look into changing it to use the previous non-null regardless of whether it is selected.

**Comment by aborruso** [comment]
Hi @saulpw now it works.

Sometimes I have to do something wrong, but I can not figure out what. I feel myself very stupid and disturbing.

Excuse me a lot
