### ISSUE TITLE
[graph] terminals smaller than 80x25 attempt to draw offscreen

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2171]
**Small description**
If a window is smaller than the default startup window, `canvas.py` thinks the screen is bigger than it is, and attempts to draw offscreen at first. This causes errors to show up from various calls to `scr.addstr()`:
```
scr.addstr(y, x, disp_column_fill*actualw, cattr.attr)  # clear whole area before displaying
_curses.error: addwstr() returned ERR
```

**Steps to reproduce with sample data and a .vd**
Open a terminal narrower than 80 columns or shorter than 25 columns, and plot any data set.

**Additional context**
saul.pw/VisiData v3.0dev

I'm looking into the cause and a fix.

**Comment by saulpw** [comment]
Thanks for looking into this, @midichef.  It's probably entirely cosmetic but it would be good to clean it up anyway.

**Comment by midichef** [comment]
I did a bisect, and it seems the problem started in the 4 commits after b2523752b31f9a2990d960ee64f5418661ab3a4e, and in or before e1dd8c494a6494506560163c6c409e36c7e630c4, in the reworking of the color attributes in October. I have looked at the changes a few times but surprisingly, nothing looks like a likely cause.

I'll keep investigating.

**Comment by midichef** [comment]
>surprisingly, nothing [in these commits] looks like a likely cause.

My best guess is that these commits did not cause the bug. They merely revealed it. The bug is sensitive to timing. While investigating, I accidentally made the problem disappear by adding `vd.status()` calls. My tentative working hypothesis is: the bug causes no problems if `refresh()` can be reached before `draw_all()` runs. (The particular `refresh()` call to reach may be the one at the end of `reload()`.)

I've got a patch for `Canvas` to handle the case when the terminal window is very small.
