### ISSUE TITLE
[windows] VisiData must be run using WSL

### ISSUE THREAD

**Issue by wcheek** [saulpw/visidata#2172]
**Small description**
`visidata` doesn't work. I'm running Windows 10 Pro `Version 10.0.19045 Build 19045`. I'm on a Japanese laptop, so maybe encoding is throwing things off.

**Expected result**
`visidata <file>` would open a file.

**Actual result with screenshot**
When I try to run eg `visidata faa-wildlife-strikes.csv`, it hangs for a moment and then returns me to the command prompt without displaying anything:

```cmd
D:\Projects\RiceMiller\RawData>visidata faa-wildlife-strikes.csv

D:\Projects\RiceMiller\RawData>
```

When I run `visidata -h` I get a `UnicodeDecodeError`:

```cmd
D:\Projects\RiceMiller\RawData>visidata -h
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\Scripts\visidata.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\visidata\main.py", line 395, in vd_cli
    rc = main_vd()
         ^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\visidata\main.py", line 116, in main_vd
    print(fp.read())
          ^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0x94 in position 101: illegal multibyte sequence
```

**Steps to reproduce with sample data and a .vd**
When I run 
```cmd
D:\Projects\RiceMiller\RawData>echo "abc" | visidata -f faa-wildlife-strikes.csv -N

D:\Projects\RiceMiller\RawData>
```

Nothing happens.

**Additional context**
```cmd
D:\Projects\RiceMiller\RawData>visidata --version
saul.pw/VisiData v2.11.1
```
`Python 3.12.0`

I was able to fix the `visidata -h` `UnicodeDecodeError` by explicitly specifying `encoding="utf-8"` in line 113 of `main.py`, but so far unable to figure out how to actually get files opening.

**Comment by saulpw** [comment]
Hey @wcheek, what happens if you use `vd` instead of `visidata`?  Also does it work on the `develop` branch?

**Comment by wcheek** [comment]
`vd` isn't a recognized command even though I have a `vd` file in `site-packages` in the same place that I have the `visidata.exe` file that is currently failing. I'll check the develop branch.

**Comment by wcheek** [comment]
I get a few more notifications at least but the file still doesn't open and `vd` is still not working. However, `visidata -h` works now.
```cmd
D:\Projects\RiceMiller\RawData>visidata --version
saul.pw/VisiData v3.0dev

D:\Projects\RiceMiller\RawData>visidata faa-wildlife-strikes.csv
saul.pw/VisiData v3.0dev
opening faa-wildlife-strikes.csv as csv

D:\Projects\RiceMiller\RawData>vd faa-wildlife-strikes.csv
'vd' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by saulpw** [comment]
Try running with `--debug`, does that show anything for you?

**Comment by wcheek** [comment]
@saulpw same behavior with a small stack trace?

```cmd
D:\Projects\RiceMiller\RawData>visidata --debug faa-wildlife-strikes.csv
saul.pw/VisiData v3.0dev
opening faa-wildlife-strikes.csv as csv [visidata\_open.py:137:openPath]

D:\Projects\RiceMiller\RawData>
```

In `openSource()`, `vd.openPath()` is getting called:
```python
        else:
            print("Here!")
            vs = vd.openPath(
                Path(p), filetype=filetype, create=create
            )  # convert to Path and recurse
```
`openSource()` returns `vs = "faa_wildlife-strikes"` and then the only place I see `openSource()` getting referenced is in these `BaseSheet` and `TableSheet`. Interestingly, the only one that seems to actually be present in the `visidata` module is `BaseSheet`:

![image](https://github.com/saulpw/visidata/assets/66931618/ec982611-f755-49f7-8b10-33260fdbdb82)

![image](https://github.com/saulpw/visidata/assets/66931618/f36a1e2d-6ac0-41b1-bff5-09b5a3524ea0)

**Comment by saulpw** [comment]
How did you install VisiData, @wcheek?  You said you're running on Windows, is this with WSL?

**Comment by wcheek** [comment]
I installed it using the [recommended way](https://www.visidata.org/install/): `pip3 install visidata`.

I have WSL installed, but I am running `visidata` with the Windows shell. I've tried it on both `wezterm` and `powershell` to no avail.

**Comment by saulpw** [comment]
Try installing it inside WSL and running it there.  Or, you could try installing from the unreleased develop branch.  v2.11.1 definitely works for other users under WSL.

**Comment by wcheek** [comment]
@saulpw confirmed v2.11.1 works in WSL.

No offense, but it seems like a serious problem if it's not working on Windows, even the v.3.0dev version. Let me know if you need more information from my system.

**Comment by saulpw** [comment]
None of us on the dev team use Windows, so I don't believe it's ever worked on Windows outside of WSL.  I think the correct fix here is to remove any hint from https://visidata.org/install that it might work without WSL.

If anyone is interested in getting VisiData to work on Windows apart from WSL, please get in touch!
