### ISSUE TITLE
inputMultiple() displays a malformed empty status box

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2181]
**Small description**
`search-keys` and `search-col` displays an empty box while waiting for the user to input a regex at the prompt. The box is shown where the usual status messages are shown.

**Expected result**
No box should be displayed.

**Actual result with screenshot**
![sidebar-inputMultiple](https://github.com/saulpw/visidata/assets/67946319/1b068536-bd38-4953-bfc0-640920380ded)

For comparison, here is what the normal status messages look like:
![sidebar-normal](https://github.com/saulpw/visidata/assets/67946319/de49d377-aaab-4b1b-9ac3-56906b7c53a3)

**Steps to reproduce with sample data and a .vd**
Open any sheet and hit `r` or `/`.

**Additional context**
saul.pw/VisiData v3.0dev
Python 3.10.12
Ubuntu 22.04.3

**Comment by saulpw** [comment]
Hm, these are help panels which should be installed via pip now.  Can you try uninstalling and reinstalling?
