### ISSUE TITLE
[jsonla] saving None saves a string

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2183]
**Small description**
When saving a .jsonla file, `None` is turned into `"(None)"`

**Expected result**
I expect a .jsonla file that has:
```
["column"]
[null]
```

**Actual result with screenshot**
```
["column"]
["(None)"]
```

**Steps to reproduce with sample data and a .vd**
[jsonla-nulls.json](https://github.com/saulpw/visidata/files/13735383/jsonla-nulls.json)
`vd -f json jsonla-nulls.json` then save as a .jsonla file.

**Additional context**
saul.pw/VisiData v3.0dev
Python 3.10.12

**Comment by saulpw** [comment]
Thanks @midichef, should be fixed now.
