### ISSUE TITLE
Is there any plan to support virtual text like in text editors for example neovim? 

### ISSUE THREAD

**Issue by soluty** [saulpw/visidata#2194]
I think search and move in viewport will be more quick way to move around anywhere and select a piece of area like in vim's famous plugin  easymotion do. in sheet processor this way also can work well.
when i start to search, and press a letter, if i can make some label in such contains that letter's cell, then i can press label name, and go to that cell, this maybe the quickest way to move and select, in neovim there is an awesome plugin flash.nvim can do it  in texteditor, and it use neovim's virtual text feature to make this feel very confortable. 
Now visidata's search feeling is like traditional vim, / and ? as search direction, this way can touch letter not in viewport, but in viewport, the way like easymotion or flash.nvim is better, to complete it need feature like virtual text and i found api, there is no such
api i can use. 
What about this idea do you think?

**Comment by saulpw** [comment]
It sounds like you want commands like vim's `ma` to mark a location, and then `'a` to go to that location, is that correct?

**Comment by soluty** [comment]
> It sounds like you want commands like vim's `ma` to mark a location, and then `'a` to go to that location, is that correct?

no, it is not bookmark, look at this ![imag](https://private-user-images.githubusercontent.com/292349/247490834-90af85e3-3f22-4c51-af4b-2a2488c9560b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDQ3NDEsIm5iZiI6MTcwMzc0NDQ0MSwicGF0aCI6Ii8yOTIzNDkvMjQ3NDkwODM0LTkwYWY4NWUzLTNmMjItNGM1MS1hZjRiLTJhMjQ4OGM5NTYwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwNjIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTQ0YmNjM2VlZGNiNjk1ODJmZjRjYjVlODhmOWYxMWJjMzBlN2RiYjVkZjRjYmNkNGVlNmY0OGZlMzEwNGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FE2EcyE-D-oMtLpWkmyGSA-e0rSExqJhC2kO0dHDQ9k)
and website is here https://github.com/folke/flash.nvim

when you type a single letter, it will find all viewport's cell and get matches, then put a label on it, if you type correct label , cursor move , awesome feeling in text editor and i think it can use in table data.

**Comment by saulpw** [comment]
I can't see your image, but I understand from the flash nvim plugin that it's a quick-search.  It sounds like a nice feature but also a lot of work, so we won't be doing it any time soon.  We'll keep it as a wishlist item for the future if anyone wants to try their hand at it.

Kondo'ed for now.
