### ISSUE TITLE
[input/adding aggregators] Hitting return doesn't work when adding aggregators

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2195]
**Small description**
Hitting return doesn't work when adding an aggregators.  It is not clear how to accept your final choices

**Expected result**
The Return key would causes the aggregator to be accepted.

**Actual result with screenshot**

 https://asciinema.org/a/ElDBFLlXyfgS7AoA4KCoELeul

I tried to hit return after enter a valid value like max, and VisiData did nothing

**Steps to reproduce with sample data and a .vd**

`vd sample_data/benchmark.csv`

Use `+` to add an aggregator, pick on and try to hit return to accept.  The Return is ignored.

**Additional context**
Please include the version of VisiData and Python.  Latest develop branch, and Python 3.9.2

**Comment by saulpw** [comment]
Thanks, @frosencrantz.  This was an issue with `inputPalette` when it allows multiple inputs (like add-aggregator does).  Now `Space` will add an input and `Enter` will accept all inputs.

**Comment by frosencrantz** [comment]
Thanks, @saulpw!  That works great.
