### ISSUE TITLE
Save (not save as)

### ISSUE THREAD

**Issue by multimeric** [saulpw/visidata#22]
It looks like currently the only way to save is to use `Ctrl+S`, except that this always prompts the user for a file name, and there is no way of simply saving over the current file. 

Could this feature be added? It seems fairly essential. I think that if the user provides no input in the save prompt, `vd` should override the current file. Thoughts?

**Comment by saulpw** [comment]
I agree that it would be handy; however, data safety is a big concern of mine, so I am hesitant to make it too easy to overwrite your original source data.  A good compromise might be to auto-populate the `Ctrl-S`ave with the original filename + some extension to ensure that the original data isn't overwritten accidentally.  Alternatively, @andjelx proposed a simple tab completion mechanism that could be used with file opening/saving, which would help accomplish the same effect.  Thoughts?

**Comment by hellerve** [comment]
That sounds like a healthy compromise to me. I definitely see how just overwriting is a very dangerous operation, and how I would just accidently destroy my data.

**Comment by multimeric** [comment]
I think it should pre-populate the field with the current filename (no extension), but if the user tries to save over any existing file (including the current file), the editor asks if they're sure. This is how most user-friendly editors work (e.g. `nano`)

**Comment by hellerve** [comment]
That's fine by me as well. I see how this might get annoying when doing this very often, but better safe than sorry.

**Comment by multimeric** [comment]
Ideally you'd be able to turn off the prompting so that it's less annoying
