### ISSUE TITLE
feature request:  set names of all visible columns to contents of current row

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#220]
Hi,
often I have CSV with more than one header row. I open it and viewing it for the first time I discover that I should use third row as header, but I cannot do it fast, because I have no null  unnamed visible columns and I cannot apply `g^`.

What do you think to convert this command to "set names of all visible columns to contents of selected rows (or current row)"?

Thank you

**Comment by anjakefala** [comment]
Hi @aborruso!

If you press `gz^` that will set the name of the **current** column to contents of selected rows. That does not do exactly what you want, so I  am going to provide a snippet for your .visidatarc. =)

```
def renameColNames(sheet, rows):
    for c in sheet.visibleCols:
        c.name = "_".join(c.getDisplayValue(r) for r in rows)

Sheet.addCommand('', 'rename-all-cols-selected', 'renameColNames(sheet, selectedRows or [cursorRow])')
```

You can add a keystroke to the first argument, or press `space` followed by `rename-all-cols-selected`.

Some things that came out of this:
* The native gz^ should have the longname `rename-col-selected`. This snippet would then have the longname `rename-cols-selected`.
* @saulpw should review the snippet before it goes into (if it goes into) visidata proper.

**Comment by saulpw** [comment]
That works well, @anjakefala. Let's make `z^` do as `gz^` does now, and bind this command to `gz^`. Thanks for the suggestion, @aborruso!
