### ISSUE TITLE
[interface] magnifier: multiline row at cursor only

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2205]
An idea to only show the current row as multiline, and the rest of the rows as single-line.  Not sure if the row display should be stable (such that the rows near the cursor row are obscured) or if they all should scroll.

**Comment by saulpw** [comment]
When options.disp_multiline_focus is set, only the cursor row is multiline.

**Comment by frosencrantz** [comment]
Thank you @saulpw!  This is a wonderful feature.  I tried it and like it.  I like this better than both the default for this mode, and the trick with showing the current cell in the sidebar.

**Comment by saulpw** [comment]
Thanks @frosencrantz !  We may set this to be the default for this mode at some point.

**Comment by frosencrantz** [comment]
@saulpw There might be an off-by-one error with this new feature.  When I enable this feature, VisiData no longer shows the row on the screen just above the status line. The line is left blank.  When I enable `disp_multiline_focus` that bottom line disappears. When multiline mode is enabled and the screen is too short, it might not show any data, even if there are a few lines available for row data to display.

Created https://github.com/saulpw/visidata/issues/2556

**Comment by saulpw** [comment]
I made this the default behavior, but you can still get the older behavior with `options.disp_multiline_focus=False`.
