### ISSUE TITLE
[interface] add aggregator column totals below sheet

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2209]
Add a row just above the status bar for each aggregator type on one or more columns, and display the aggregated values for those columns.

**Comment by saulpw** [comment]
something like this:

![vd-aggr-summary](https://github.com/user-attachments/assets/2ae7da12-68fd-47d7-a748-6f12177305b1)

**Comment by gennaro-tedesco** [comment]
This new aggregators view is awesome, thank you a lot for coming up with such a neat idea.

However, how can one "remove" the resulting row, at some point, to get rid of it (currently I just reload the sheet but I presume there is a more native way to do so)?

**Comment by saulpw** [comment]
Well, you could go to the Columns Sheet and remove the aggregators from all columns.   If you want a command that does this:

```
Sheet.addCommand('', 'remove-aggregators', 'Fanout(columns).aggregators = ""')
```
