### ISSUE TITLE
how to use a field with a numeric name?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#221]
Hi,
I have one field whose name is "3". Ho to create a clone of this field using `=FieldName`? If I use `=3` I have a field with `3` in all rows.

Thank you

**Comment by saulpw** [comment]
The column must have a name which is a valid Python identifier in order to be used in an expression like that.  That's a necessary part of the design.

**Comment by aborruso** [comment]
Very useful the `--force-valid-colnames` option
