### ISSUE TITLE
[docs] search-and-replace in a column

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2223]
Also, an example of my confusion between the different "channels" (docs, tuts & manpage) is actually what lead me to my [latest question](https://github.com/saulpw/visidata/discussions/2222): I looked at the ["How to" about Columns](https://www.visidata.org/docs/columns/) and was hoping to find something about search-&-replace in a column, but could find anything there, but maybe I just didn't look properly..

_Originally posted by @halloleo in https://github.com/saulpw/visidata/discussions/2221#discussioncomment-8000137_

**Comment by anjakefala** [comment]
This has been documented in the new RegexGuide: https://github.com/saulpw/visidata/pull/2552
