### ISSUE TITLE
[split] Change in behaviour in visidata 3.0

### ISSUE THREAD

**Issue by fourjay** [saulpw/visidata#2224]
regex split behavior has changed with the update to version 3
Instead of splitting columns, the behavior I expected from version 2
I instead get a new column with format:
[N] first_value ; second_value
where N is a number (appears to be field count)
and the various fields are all contained in the first (and only) field 

It's clear that something is being done, as the regex field has been replaced by a semicolon

Is this due to a change in how columns are handled in version 3 
(it seems possible that the semicolon might be a default output)

If this is more appropriately a bug, update the ticket and I'll provide more information
(FWIW, I am using pipx to install, with some additional plugins with their support libraries, and I've tested without a visidatarc)

**Comment by saulpw** [comment]
Yes, now it's a single column with a list.  Use `(` to expand the list into multiple columns like you're used to.

**Comment by saulpw** [comment]
Note also that the previous `split-col` command still exists (but is deprecated), so previous cmdlogs should still work.  Or you can unbind/rebind `:` to that previous command.  If people wind up rebinding to the older command, let us know so we can un-deprecate it.

**Comment by saulpw** [comment]
/docs/columns#split

**Comment by awwaiid** [comment]
OK -- so I was using `;` and then `(.......)` to take a date/time column and grab off the first 7 characters which happens to be the month, like `2023-12-01 21:32` → `2023-12`. This change surprised me, but now I see I can press `(` to get the first capture and then ignore/delete the cruft. Is there a better way?

**Comment by saulpw** [comment]
How about `=curcol[:7]`?

**Comment by awwaiid** [comment]
I didn't know about `curcol`, that's pretty cool! I often need to run `clean-names` but `curcol` will remove some of those use cases.

Whelp. This helps the specific use-case I was most recently using this week. Just now playing with it the only other feedback/suggestion is that if the regex capture only has one group maybe it shouldn't group the column.

**Comment by p3k** [comment]
I got surprised by this today. I suggest the [documentation](https://www.visidata.org/docs/columns/) could be updated with the information about

1. only 1 new column is created
2. the new column contains a list
3. this list can be expanded into columns using `(`

It currently states:

> `:` adds _new columns_ derived from splitting the current column at positions defined by a regex pattern

(Emphasis mine.)

**Comment by anjakefala** [comment]
Thanks @p3k! Would you be willing to open a PR updating it?

**Comment by p3k** [comment]
Willing yes, but currently not finding the time.

**Comment by krackout** [comment]
Please do not remove `split-col` if possible in future releases! It's simpler, I've rebind it to `:` as in v2.

What are the advantages of the new way to split columns?

**Comment by saulpw** [comment]
@krackout Sometimes there are an indefinite number of splits, like a space-separated list of tags, for instance.  If you want to unfurl the tags so you have one row per item-tag, you need the tags as a list in a single cell.  There's no way to combine columns after the old `split-col`, so you can't use `split-col` and would have to manually use a python expression like `=curcol.split(' ')`, or worse if you need to split on a regex instead of a string.  With the new `addcol-split`, you're only one keystroke (`(`) away from the old behavior anyway.  (And of course you can always rebind to the old behavior as you've done; the command is deprecated but we have no need or plans to ever remove deprecated commands.)

**Comment by anjakefala** [comment]
`(` has now been documented here: https://github.com/saulpw/visidata/blob/develop/visidata/guides/RegexGuide.md#examples in the new regex guide. =)
