### ISSUE TITLE
[pandas wishlist] Support multi-index

### ISSUE THREAD

**Issue by jtrakk** [saulpw/visidata#223]
Pandas has the option of [multi-indexes](https://pandas.pydata.org/pandas-docs/stable/advanced.html), which can produce tables like this:

```
first        bar                 baz                 foo                 qux          
second       one       two       one       two       one       two       one       two
A       0.895717  0.805244 -1.206412  2.565646  1.431256  1.340309 -1.170299 -0.226169
B       0.410835  0.813850  0.132003 -0.827317 -0.076467 -1.187678  1.130127 -1.436737
C      -1.413681  1.607920  1.024180  0.569605  0.875906 -2.211372  0.974466 -2.006747
```

Does/can Visidata support this kind of table?

**Comment by saulpw** [comment]
Hi @jtrakk, that's an interesting idea.  I think it can probably be done; would you be interested in implementing it?  The [VisiData pandas loader](https://github.com/saulpw/visidata/blob/stable/visidata/loaders/_pandas.py#L34) is pretty simple; as long we can get at an individual cell in your example like `df.iloc[0]['bar']['one']`, then we can change line 34 to create a `MultiIndexColumn` (which we'd have to make) for each of the permutations.

Multi-line headers would require a bit of a change to the draw() loop, but not too bad.  I could see this going into 1.6 very reasonably.

**Comment by jtrakk** [comment]
@saulpw I appreciate the invitation and I'm glad to hear it sounds feasible. As much as I would like to give it a shot, I can't dive into it right now due to commitments on other projects. Maybe one day I'll get to play around with visidata's codebase, that'd be fun :-).

**Comment by agguser** [comment]
With this, can "footer rows" (e.g. showing columns' aggregate values like avg, sum) be supported?

**Comment by saulpw** [comment]
That's a good idea, @agguser.  I'll add it when we get around to updating the draw() code.

**Comment by saulpw** [comment]
@jtrakk, we have multi-line column names now; if you wanted to submit a sample dataset and code to elicit the kind of table you show above, we could probably get this done in a very short order.

**Comment by jtrakk** [comment]
Just snipping from the pandas doc I linked above:

```python
In [11]: index = pd.MultiIndex(levels=[['bar', 'baz', 'foo', 'qux'], ['one', 'two']], 
    ...:            codes=[[0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1]], 
    ...:            names=['first', 'second'])                                                                                                                               

In [12]: df = pd.DataFrame(np.random.randn(6, 6), index=index[:6], columns=index[:6])                                                                                        

In [13]: df                                                                                                                                                                  
Out[13]: 
first              bar                 baz                 foo          
second             one       two       one       two       one       two
first second                                                            
bar   one    -1.908044 -0.464585  1.267319 -0.113221  1.359061  0.882592
      two    -0.054933  0.325378  0.124164 -1.072553 -0.834204  0.577244
baz   one     0.685178  0.825827  0.525639 -0.145356 -0.782442  0.208828
      two    -2.001790  1.070894 -1.249558 -0.205456 -1.485430 -0.459406
foo   one    -1.453257 -1.246919 -1.182969  0.237347 -0.369938  0.731892
      two     0.184026 -0.141614  1.567034  0.491889 -0.310546 -1.135242

df.to_csv(filename)
```

**Comment by anjakefala** [comment]
I am going to close this, per the Kondo policy. If anyone wants to champion this, they are more than welcome to!

**Comment by daviddwlee84** [comment]
Getting error `TypeError: Setting a MultiIndex dtype to anything other than object is not supported` while reading a multi-column dataframe from a `feather`. 
While opening with `pd.read_feather()` without any argument is fine.
(Seems not implemented)
