### ISSUE TITLE
[threads] HelpSheet thread causes an exception

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2235]
**Small description**
When I plot a png using `.` on any column and then quit with `^Q`, about 25% of the time I get an exception.

**Expected result**
I expect visidata to exit as normal.

**Actual result with screenshot**
```
Traceback (most recent call last):
File "/home/midichef/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/main.py", line 377, in vd_cli
    rc = main_vd()
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/main.py", line 337, in main_vd
    run(vd.sheets[0])
...
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/mainloop.py", line 320, in run
    vd.cancelThread(*[t for t in vd.unfinishedThreads if not t.name.startswith('save_')])
File "/home/midichef/.local/lib/python3.10/site-packages/visidata/threads.py", line 89, in cancelThread
    ctypes.pythonapi.PyThreadState_SetAsyncExc(ctypes.c_long(t.ident), ctypes.py_object(exception))
    TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Steps to reproduce with sample data and a .vd**
`vd -N ~vdsrc/sample_data/vdlogo-160x24.png`
Plot the first column with `.` then hit `^Q`.
I cannot reproduce the exception when I replay a command log `vd -p repro.vdj`, that does the equivalent sequence (open file and plot column in the replay; then I press `^Q` myself).

**Additional context**
saul.pw/VisiData v3.1dev (539935b2)
Ubuntu 22.04.3
Python 3.10.12

**Comment by midichef** [comment]
Here's what I've found so far.

The exception occurs because `t.ident` is `None`. I believe this means [the thread has not been started](https://docs.python.org/3/library/threading.html?highlight=ident#threading.Thread.ident).

The thread here `t` is `sort()` for a `Helpsheet`.

Bisect shows the exception first appears in fde05882e205a902b5890212389571b47c61aae4, where `CommandHelpGetter(type(sheet))` is called:
https://github.com/saulpw/visidata/blob/fde05882e205a902b5890212389571b47c61aae4/visidata/sidebar.py#L17
It creates a `HelpSheet`:
https://github.com/saulpw/visidata/blob/fde05882e205a902b5890212389571b47c61aae4/visidata/guide.py#L118
And `sort()` is called from the HelpSheet's `afterLoad`:  
https://github.com/saulpw/visidata/blob/fde05882e205a902b5890212389571b47c61aae4/visidata/sheets.py#L290


My first thought was that it may be related to recent changes to how threads work in `threads.py` in the last few months. But I don't think they are related. I tested older versions of `threads.py` while keeping the rest of the code at the breaking commit (fde05882e205a902b5890212389571b47c61aae4). Reverting `threads.py` to the last stable change in March 2023 (1c1a11e20fef30406a9bdc546f2f85ec79130aa2) still had the problem of the occasional exception on quitting, as did more recent commits affecting `threads.py` from October and November 2023. So it's not caused by those recent changes.

Commenting out `self.helpsheet.ensureLoaded()` does seem to prevent the exception:
https://github.com/saulpw/visidata/blob/fde05882e205a902b5890212389571b47c61aae4/visidata/guide.py#L119

**Comment by saulpw** [comment]
It could also be that the thread finishes after it's put into the list of threads to cancel.  But if it's not running we can't cancel it anyway.  So we can just check for this to avoid the exception.

BTW, do you have a reason to use `Ctrl+Q` instead of `gq`?  I think the only difference is that it avoids the quitguard, do you want that behavior, or do you prefer the keybinding, or?

**Comment by midichef** [comment]
I use it to skip the quitguard. But also the key combination is easier for me to press.

Also, I override the `Q` binding of `quit-sheet-free`, and bind it instead to a custom quit function that avoids the quitguard for the current sheet.
