### ISSUE TITLE
key column wider than screen makes other columns un-viewable

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2236]
**Small description**
When a key column has more characters than the screen can contain, it takes up the whole screen and becomes the only column I can see when I scroll.

**Actual result with screenshot**
If I `scroll-right` to the other columns, the color state of the key column shows me the cursor has moved, but I can't see the new column that holds the cursor. I can perform operations in the other column like `edit-cell`, but I have to do it without visible feedback.

**Steps to reproduce with sample data and a .vd**
[wide.txt](https://github.com/saulpw/visidata/files/13848896/wide.txt)
`vd -N wide.txt` and make the first column a key column.

**Additional context**
saul.pw/VisiData v3.1/dev and v2.11.1

**Comment by saulpw** [comment]
It's a wart for sure and if we can think of a way to fix it without 20 hacky lines of code (I tried this evening to no avail) then I'm happy to take a look.
