### ISSUE TITLE
[memory/cpu]. VisiData ends up using lots of CPU and memory in idle state

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2243]
**Small description**
VisiData ends up using lots of CPU and memory in idle state

**Expected result**
Idle time is not too busy

**Actual result with screenshot**

https://asciinema.org/a/HDtlFjQTpi5lIigMPdGgw2kXP

Not really sure how to show it.  On the threads page, I notice it keeps doing reloads.  Also the old threads do not seem to be collected.

**Steps to reproduce with sample data and a .vd**

`vd sample_data/benchmark.csv`

**Additional context**
Please include the version of VisiData and Python. Python 3.9.2. Latest develop branch

**Comment by frosencrantz** [comment]
This is a recent issue.  I've been having issues with VisiData using up lots of memory when it sits idle.

**Comment by saulpw** [comment]
@frosencrantz I don't see this on my machine.  Can you try with `vd -N` and see if the issue persists?

**Comment by frosencrantz** [comment]
Thanks, @sualpw.  The issue appears to be on my side.  Do you have any suggestions for how to find what is causing these additional reloads?

**Comment by saulpw** [comment]
Try `vd --config /dev/null` to figure out if it's in your visidatarc (otherwise it would have to be a plugin).  If it is in your visidatarc, try bisecting it by commenting out half of it to see which half is causing the problem, and repeat.  Use `'''` at the start and end of a block, since they can be on their own line and easily moved around (assuming you don't use `'''` in your visidatarc already).

**Comment by frosencrantz** [comment]
Can I use the threads sheet and profiling to identify what is causing all the threads?  I am not sure how to check what is starting the thread, that seems like it would be useful.  The thread names are reload, but it is not clear to me why it needs to do a reload after the data has loaded, and I have let it sit and do nothing.

**Comment by saulpw** [comment]
I can't think of a way off the top of my head.  Did you find out if the problem is due to your visidatarc though?
