### ISSUE TITLE
[question] cmdlog tests save .rst file as tsv

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2249]
**Small description**
When running `dev/tests.sh`, `save-benchmarks.rst` is saved in tsv format instead of .rst format. How do I configure the tests to save the file in rst format, which I think is reStructuredText?

**Expected result**
I expect to save as rst [like the cmdlog tests currently do, on line 4675](https://github.com/saulpw/visidata/actions/runs/7470935255/job/20330395664?pr=2244)
```
saving 1 sheets to tests/golden/save-benchmarks.rst as rst
```

**Actual result with screenshot**
```
saving 1 sheets to tests/golden/save-benchmarks.rst as tsv
```

What do I need to do to get a .rst file to save as rst? Did I perhaps fail to install some libraries? I did not yet install the custom `pyxlsb` and `savReaderWriter` libraries listed in `requirements.txt`.

I'm running Python 3.10.12, Ubuntu 22.04.3, Visidata v3.1dev

**Comment by midichef** [comment]
Got it, the solution was to install the `tabulate` library to save as rst, then the `wcwidth` library to get `save-benchmarks.rst` to have the correct layout with its Unicode text:

`pip install tabulate wcwidth`

**Comment by anjakefala** [comment]
I'll add them to the extras!
