### ISSUE TITLE
Have "b to toggle sidebar" show user's shortcut

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2250]
I changed my shortcut for `sidebar-toggle` to `Ctrl-B`, but I still get the text "b to toggle sidebar". I would prefer to see "^b to toggle sidebar".

Python 3.10.6, visidata==3.0.1

**Comment by anjakefala** [comment]
![Screenshot from 2024-01-14 15-20-23](https://github.com/saulpw/visidata/assets/7489659/63701323-30a0-4c44-804b-facf69bee05e)
![Screenshot from 2024-01-14 15-21-13](https://github.com/saulpw/visidata/assets/7489659/b5fc4f31-fdb0-44c9-b5bb-fda6b976abb2)


@saulpw With the attempted usage of `CommandHelpGetter`. How does it feel?

**Comment by anjakefala** [comment]
I could specifically change it to grab the `sidebar-toggle` keystroke, instead of using this macro. If we want to get rid of the ``.

**Comment by saulpw** [comment]
Can we get rid of the `` and still use the CommandHelpGetter?  I like the idea.

**Comment by anjakefala** [comment]
![Screenshot from 2024-01-14 15-31-59](https://github.com/saulpw/visidata/assets/7489659/34cbde2b-4958-4caf-b5b4-f132baca3785)
It then looks like this

**Comment by anjakefala** [comment]
Thanks @cool-RR! This will be in v3.0.2.
