### ISSUE TITLE
After replaying a script file, the timer is still present on screen

### ISSUE THREAD

**Issue by tdussa** [saulpw/visidata#2251]
**Small description**

When replaying a `.vd` file with the `-i -b -p` parameters, a timer is shown that displays the elapsed time.  This timer keeps popping up in the top-left corner even after the replay has finished.

**Expected result**

The timer should not reappear after a replay is finished.

**Actual result with screenshot**

![2024-01-13T17:38:52-Screenshot](https://github.com/saulpw/visidata/assets/6197517/60781a55-0f9c-4752-94cb-469b98e24457)

**Steps to reproduce with sample data and a .vd**

Run the replay from the zip file attached to this ticket with this command:
```
vd -i -b -p test.vd
```
The commandlog is attached.

**Additional context**

VisiData 3.0.1, Python 3.11.6

 * Test files: [test.zip](https://github.com/saulpw/visidata/files/13928838/test.zip)
 * Log file: [test.log](https://github.com/saulpw/visidata/files/13928842/test.log)

**Comment by saulpw** [comment]
Thanks, @tdussa!  Should be fixed in 3.0.2.

**Comment by tdussa** [comment]
FWIW, I've manually applied the patch in your commit to 3.0.1, and that does solve the issue, indeed.  However, now I don't get any progress display during replays whatsoever.  I suppose that was not intended either?

**Comment by anjakefala** [comment]
> FWIW, I've manually applied the patch in your commit to 3.0.1, and that does solve the issue, indeed. However, now I don't get any progress display during replays whatsoever. I suppose that was not intended either?

The progress display should only appear for very long-running commands. The command in your example probably should not have shown a progress counter at all. I'm going to attempt to follow-up on this.

**Comment by anjakefala** [comment]
Thanks so much @tdussa! Both things should be fixed now.

**Comment by tdussa** [comment]
I can confirm this works as expected for me now. Thanks a lot! :)

**Comment by anjakefala** [comment]
It will be in 3.0.2! We shipped that to PyPI tonight. Homebrew + Debian will be updated soon.
