### ISSUE TITLE
[] a custom command `diff from previous column`

### ISSUE THREAD

**Issue by maxim-uvarov** [saulpw/visidata#2260]
In Discord I've asked some time ago about the function to calculate differences from previous column. 
Saul kindly suggested a variant:
```
class DiffPreviousColumn(Column):
    def calcValue(self, row):
        prevval = self.prevCol.getTypedValue(row)
        curval = c.getTypedValue(row)
        return (curval-prevval)/prevval

@Sheet.api
def diff_cols(sheet):
    for c in vd.numericCols(sheet.visibleCols):
        newcol = DiffPreviousColumn(c.name + 'diff', type=float, sourceCol=c)
        sheet.addColumn(newcol, index=sheet.columns.index(c))
        c.hide()

Sheet.addCommand('', 'diff-cols', 'diff_cols()')
```

I tried it, but it didn't work. I have been trying to understand how to fix it, but so far, I have had no luck. 

I tried to change:
```
        return (curval-prevval)/prevval
```

with 
```
        return 1
```

but even then I had errors in calculated columns:

<img width="561" alt="image" src="https://github.com/saulpw/visidata/assets/4896754/fafed7fe-bc62-45db-8d52-311a09ede812">

Can anyone help me make it work, please?
Here is an example file to experiment with (you'll need to pivot this):

[example_melted.csv](https://github.com/saulpw/visidata/files/13976476/example_melted.csv)

I have recorded a 1-minute screencast demonstrating the desired result:
https://www.youtube.com/watch?v=9DmVd3htE1A

**Comment by saulpw** [comment]
What is the error in one of the cells?  You can see it with `z Ctrl+E`.

**Comment by maxim-uvarov** [comment]
```
Traceback (most recent call last):
File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/wrappers.py", line 105, in wrapply
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/column.py", line 340, in getValue
return self.calcValue(row)
^^^^^^^^^^^^^^^^^^^
File "/Users/user/.visidatarc", line 27, in calcValue
prevval = self.prevCol.getTypedValue(row)
^^^^^^^^^^^^
AttributeError: 'DiffPreviousColumn' object has no attribute 'prevCol'
```

**Comment by saulpw** [comment]
Change `prevCol` to `sourceCol` (or vice versa).

**Comment by maxim-uvarov** [comment]
I changed the code and now I got this error:

```
Traceback (most recent call last):
File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/wrappers.py", line 105, in wrapply
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/Users/user/miniconda3/lib/python3.11/site-packages/visidata/column.py", line 340, in getValue
return self.calcValue(row)
^^^^^^^^^^^^^^^^^^^
File "/Users/user/.visidatarc", line 28, in calcValue
curval = c.getTypedValue(row)
^
NameError: name 'c' is not defined
```

my current code is:

```
class DiffPreviousColumn(Column):
    def calcValue(self, row):
        prevval = self.sourceCol.getTypedValue(row)
        curval = c.getTypedValue(row)
        #return (curval-prevval)/prevval
        return 1

@Sheet.api
def diff_cols(sheet):
    for c in vd.numericCols(sheet.visibleCols):
        newcol = DiffPreviousColumn(c.name + 'diff', type=float, sourceCol=c)
        sheet.addColumn(newcol, index=sheet.columns.index(c))
        c.hide()

Sheet.addCommand('', 'diff-cols', 'diff_cols()')
```

**Comment by saulpw** [comment]
Change `c` to `self`.

I just kind of tossed this code off, I thought maybe you knew how to code in Python a bit and could fix the issues and get it working for yourself.  Adding this feature properly will probably require more polish (including documentation and a test) once it's working, and it's not a priority on our roadmap.

Kondo'ed for now.
