### ISSUE TITLE
website has dead links for man pages/quick docs

### ISSUE THREAD

**Issue by clach04** [saulpw/visidata#2261]
**Small description**

https://www.visidata.org/docs/ and https://www.visidata.org/ both link to https://www.visidata.org/docs/man/ which has an Oops! (404?) page.

**Expected result**

See quick ref guide (2.0?)

**Actual result with screenshot**

> Oops!
> Oops!
> Sorry, we can't find that page!
> 
> Take me back to the homepage

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**

NA

First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.

NA

**Comment by anjakefala** [comment]
Thanks! Both links are now fixed.
