### ISSUE TITLE
visidata silently fails under Windows with Python 3.12 (3.11 fine)

### ISSUE THREAD

**Issue by clach04** [saulpw/visidata#2267]
**Small description**

visidata fails to load/display files without error

**Expected result**

visidata to load correctly (or report an error)

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**

Either `pip install visidata` or from source code

1. follow https://github.com/saulpw/visidata/blob/6a1f17c961d3a4cc32b198b018169198f7e4e4c3/README.md?plain=1#L30
        `pip3 install git+https://github.com/saulpw/visidata.git@develop`
2. run `visidata`

Will see version information, but process exits without UI showing.

I tried different tags with no success. Works fine with Python 

Calling with a parameter, appears to load as there is a message to that effect but no UI loads up.

First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.

any 3.0.x and 3.1

Python 3.12

    
    (py312visidata_pip) C:\tmp>visidata
    saul.pw/VisiData v3.0.2
    
    (py312visidata_pip) C:\tmp>python
    Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32

EDIT See https://github.com/saulpw/visidata/issues/2119#issuecomment-2244526323 - suspected PDCurses bug (note link related to keyboard, unclear if this specific issue).

**Comment by clach04** [comment]
(py3venv) C:\code\py\visidata>visidata --debug
    saul.pw/VisiData v3.0.2

Debug flag has no impact on reporting more details

**Comment by clach04** [comment]
Appears to die inside:

https://github.com/saulpw/visidata/blob/6a1f17c961d3a4cc32b198b018169198f7e4e4c3/visidata/main.py#L341

**Comment by tahir-hassan** [comment]
@clach04 I tried using Visidata on normal Python on Windows and it loads files fine, but there were two issues: 1. the mouse didn't work (I couldn't click on a cell), and 2. pressing double quote (") didn't produce a character.  I ended up installing Visidata via MSYS2, as it works within there.  

Here is the issue: [Double Quotation Character not working on Windows](https://github.com/saulpw/visidata/issues/2479)

**Comment by daviewales** [comment]
I expect that Visidata needs to update the `windows-curses` dependency to [2.3.3](https://github.com/zephyrproject-rtos/windows-curses/releases/tag/v2.3.3), for which the release notes state:

> Fixed setupterm issue causing Python process to exit silently on Python 3.12. For more details, refer to the GitHub issue https://github.com/zephyrproject-rtos/windows-curses/issues/50.

However, I can see that Visidata has intentionally held an older version of `windows-curses` to avoid this bug:
https://github.com/zephyrproject-rtos/windows-curses/issues/41

So, to make it work on Python 3.12, we lose the ability to detect some keypresses!

**Comment by midichef** [comment]
@daviewales Updating `windows-curses` to 2.3.3 does not fix the missing keypress problem. The discussion of the `windows-curses` bugs has been scattered in several threads, so I keep [my recent notes on windows-curses findings in a comment](https://github.com/saulpw/visidata/issues/2119#issuecomment-2244526323), and link to it from threads like this one.

In the past week, `windows-curses` has traced the problem to specific commits in `PDCurses`, which they make use of. So I'd expect a fix in their next release, once they decide what version of `PDCurses` they want to use.

**Comment by anjakefala** [comment]
This will be fixed in the next release of VisiData!

Until then, you can `pip3 install git+https://github.com:saulpw/visidata.git` or `pip3 install windows-curses>=2.4`.
