### ISSUE TITLE
Is it possible to rename fields in bulk via join?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#227]
Hi,
I have a CSV file in which I need to rename in bulk a lot of columns, using a schema I have in an another CSV. This last CSV has this schema:

```
name,newname
field1,lorem
field2,ipsum
...,...
```

If I open columns sheet of my input CSV, I could do a JOIN between this and schema CSV file, using name as join field, and than in the source name field use `g=` and insert `newname`, but I have this error.

![image](https://user-images.githubusercontent.com/30607/49873989-898c9a80-fe1d-11e8-99f6-f0e76108fe04.png)

Is there a way to rename in bulk using data of a joined table?

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, this is what the `extend` join type is for, to keep the semantics of the the first sheet (make sure the columns sheet is first) when joining.  Try that and see if it solves your problem.

**Comment by aborruso** [comment]
You are a genius, I'm trying 💯

**Comment by aborruso** [comment]
GREAT, it works
