### ISSUE TITLE
visidata.desktop doesn't pass validation

### ISSUE THREAD

**Issue by QuLogic** [saulpw/visidata#2276]
**Small description**
On Fedora, packages that include a `.desktop` file [must pass validation](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_desktop_files). Presumably something similar is required for Debian.

This validation can be run with the following command (from the `desktop-file-utils` package in Debian/Fedora):
```
desktop-file-validate path/to/visidata.desktop
```

**Expected result**
Validation passes.

**Actual result with screenshot**
```
.../visidata.desktop: error: value "bash -i -c 'vd %f'" for key "Exec" in group "Desktop Entry" contains a reserved character ''' outside of a quote
.../visidata.desktop: error: value "bash -i -c 'vd %f'" for key "Exec" in group "Desktop Entry" contains a reserved character ''' outside of a quote
.../visidata.desktop: warning: value "Application;" for key "Categories" in group "Desktop Entry" contains a deprecated value "Application"
.../visidata.desktop: hint: value "Application;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
```

**Additional context**
VisiData 3.0.2

**Comment by anjakefala** [comment]
Ah @QuLogic =/ I had no idea. It worked fine for me on Debian. I'll give this a try.

**Comment by anjakefala** [comment]
Thanks @QuLogic! =)
