### ISSUE TITLE
Avoid Status Spam/Visual Noise

### ISSUE THREAD

**Issue by gordo-veda** [saulpw/visidata#2283]
Regardless of how anyone may feel about the subjectivity of this "feature", previously, setting an empty motd URL kept this sort of status spam from appearing during startup. However, at some point after updating to a newer version of visidata, this status message is now very pronounced and distracting, and disabling the MOTD doesn't disable the status display either. 

This, coupled with the default help status overlay (which also was not a default behavior previously), leads to a very distracting user experience. Thankfully, it's possible to disable the help overlay at least with config overrides, but there doesn't seem to be a way to disable the default status upon startup.

I suggest removing this line, or add a "quiet" option to skip this status display:
https://github.com/saulpw/visidata/blob/develop/visidata/main.py#L180

<img width="1040" alt="Screenshot 2024-01-31 at 14 43 52" src="https://github.com/saulpw/visidata/assets/108159757/a9379613-5b2f-4998-b869-49e93e9d118c">

I would like for visidata to "stay out of my way" as it did in previous versions.

**Comment by anjakefala** [comment]
I'm curious - have you ever supported the project? Through code, written contributions, bug reporting, or financially?

**Comment by gordo-veda** [comment]
Nope, I'm just a user, and haven't had a need that isn't already met by this tool.

That being said, I also don't think one must support a project in any way at all to be allowed to make suggestions, either.

I have encouraged others to use this tool, and that should be enough.

**Comment by gordo-veda** [comment]
Here, have a bug report: https://github.com/saulpw/visidata/issues/2284

**Comment by saulpw** [comment]
Hi @gordo-veda, the point was not to create a make-work issue as some kind of token gesture of support.  Within the context of our conversation today, it could be seen as petulant or, given the inherent asymmetry in open-source software development, possibly even malignant.  I would appreciate it if you took extra care to abide by our [Code of Conduct](https://github.com/saulpw/visidata/blob/develop/CODE_OF_CONDUCT.md) when interacting with us in the future.

Your annoyance has been noted, and we will try to address it as part of #2202.
