### ISSUE TITLE
Feature request: add option for select behavior

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#229]
Hi,
in most of the software I use if I run a selection (visual or programmatically), by default this selection replace the previous one.

Sometime I make errors using vd, because I think that it's a new selection and not an addition (the default in vd).

It would be great to have an option (or a key combination) for `.visidatarc` - something like `options.select_behavior` - to set the way you want use selection command, distinguishing in "new" and "add".

Thank you

**Comment by anjakefala** [comment]
Feature was added in commit https://github.com/saulpw/visidata/commit/c345b127d5f748f8483f05420ff1c84dd2778d29. =)

To use, set `options.bulk_select_clear=True` in your `.visidatarc` or pass `--bulk-select-clear` through the commandline. =)

**Comment by aborruso** [comment]
Wow, thank you
