### ISSUE TITLE
[question] What is the recommended way to change `options.regex_skip`?

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#2305]
`options.regex_skip` has a custom value for certain sheets:

```
visidata/loaders/csv.py:CsvSheet.options.regex_skip = '^#.*'
visidata/loaders/json.py:JsonSheet.options.regex_skip = r'^(//|#).*'
visidata/loaders/jsonla.py:JsonlArraySheet.options.regex_skip = r'^(//|#).*'
visidata/loaders/tsv.py:TsvSheet.options.regex_skip = '^#.*'
```

For those sheet types, how would I change the value of `options.regex_skip` without delving into the code?

**Comment by saulpw** [comment]
In visidatarc, this seems to work fine:

    JsonLinesSheet.options.regex_skip = ''

You can replace it with a different regex, or an empty regex disables skipping.
