### ISSUE TITLE
Allow disabling of colorizers on xlsx files.

### ISSUE THREAD

**Issue by krackout** [saulpw/visidata#2317]
It seems that colour support for xlsx files was added with this:
https://github.com/saulpw/visidata/issues/1718

I recently updated from Visidata 2.11 to 3.0.2. I prefer to not have text and fill colours on xlsx files (as in v2.11), yet I cannot disable colorizers.
I've tried  starting `visidata --xlsx-meta-columns=False` parametre, but unfortunately colours are still on. Also tried to switch theme to asciimono, yet xlsx files still load with colours.

If `xlsx-meta-columns=False` is supposed to disable colours on xlsx, I'm filling a bug report. Else sorry for misunderstanding and please guide me to the proper way of disabling them.

**Comment by frosencrantz** [comment]
This would be useful, too.  I like having the colors, however, there are spreadsheets where the color choice is not useful, and can make seeing the values in VisiData more difficult.

**Comment by anjakefala** [comment]
Ah no, `xlsx-meta-columns` is for whether to include columns that contain meta information about an xlsx file. It's `False` by default! I'm going to convert this into a feature request.

**Comment by anjakefala** [comment]
Hi @krackout! I added a `--xlsx-color-cells` option that you can set to False. It's currently available on the `develop` branch. You can `pip3 install git+https://github.com/saulpw/visidata` or wait for the next release, which is coming soon. =)
