### ISSUE TITLE
I wrote an r package for visidata, rvisidata

### ISSUE THREAD

**Issue by paulklemm** [saulpw/visidata#232]
I just want to notify you that I developed a tiny `R` package which can be used to open any `R` data frame in `visidata.` The repo can be found here: [https://github.com/paulklemm/rvisidata](https://github.com/paulklemm/rvisidata). It works really simple and is not really performant by writing the data frame to a temporary file and then opening it with `visidata.` But it works.

Maybe it is useful for other people that use `R`.

**Comment by saulpw** [comment]
That's awesome, @paulklemm, thanks for sharing!  I'm sure it will be useful to some other R users as well.  Would you like us to put a link to it on the website?

**Comment by paulklemm** [comment]
Glad you like it!

>  Would you like us to put a link to it on the website?

That would be great 🎉

**Comment by paulklemm** [comment]
By the way, I'm sure there is a more elegant and efficient way of connecting `Visidata` with `R` through the [reticulate](https://github.com/rstudio/reticulate) package, but I honestly lack the Python skills for that (for now).

I think this implementation will do for now.

**Comment by anjakefala** [comment]
This is so exciting! =)

I will leave the issue open until it has been added to the website. ^^

**Comment by anjakefala** [comment]
I have documented it here: https://github.com/saulpw/visidata/commit/0e251670e7fc519d9b216992eb6265c3eaefc01d

Please review. =) @paulklemm

**Comment by paulklemm** [comment]
Looks good, thanks a lot

**Comment by anjakefala** [comment]
Awesome.

Thank YOU. =)
