### ISSUE TITLE
`open-cell` (`zo`) should open the correct filetype in cell

### ISSUE THREAD

**Issue by dufferzafar** [saulpw/visidata#2327]
If I've opened the current sheet as a `jsonl` but the cell that I'm on has a CSV url?

Currently I get:

```
opening http://url/to/file.csv as jsonl
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Where it tries to open a CSV file as JSONL for some reason.

_Originally posted by @dufferzafar in https://github.com/saulpw/visidata/issues/1514#issuecomment-1938786979_

**Comment by dufferzafar** [comment]
Reproduce it like so:


```
cat > /tmp/t.json
[
    {
        "type": "csv",
        "url": "https://raw.githubusercontent.com/duckdb/duckdb/main/data/csv/aws_locations.csv"
    },
    {
        "type": "json",
        "url": "https://raw.githubusercontent.com/duckdb/duckdb/main/data/json/issue.json"
    },
    {
        "type": "jsonl",
        "url": "https://raw.githubusercontent.com/duckdb/duckdb/main/data/json/duplicate_key.ndjson"
    }
]
```

```
vd /tmp/t.json
# try to use zo on cells, and it works correctly!
```

```
vd -f json /tmp/t.jsonn
# try to use zo on cells, and it will consider everything to be json
```

cc: @anjakefala

**Comment by dufferzafar** [comment]
I just figured out that this only happens if you open the file with a specific format `-f json`, so I've removed it from my current scripts and things work for me.

**Comment by saulpw** [comment]
Glad you were able to find a workaround, @dufferzafar!  You might also try `-n -f json <foo.json>` to apply the option only to the given path, and not globally.

**Comment by justin2004** [comment]
what would be a good way to open the file in the cell but as type `f`? this is in case the file doesn't have an extension. 

the only way i've come up with is to use [my repl](https://github.com/saulpw/visidata/discussions/2290) and eval:
say if you have an email file
```
vd.push(vd.open_eml(Path(vd.sheet.cursorDisplay)))
```
i guess i could turn that into a command but i need to pass in the filetype e.g. "eml" "xlsx" etc.

**Comment by anjakefala** [comment]
@justin2004 If this is still a question you have, could you open a new issue? I'm closing this issue because the original question was addressed!
