### ISSUE TITLE
v3.0.2: Installed via pipx, app returns `segmentation fault` when attempting to open file

### ISSUE THREAD

**Issue by jheasly** [saulpw/visidata#2330]
**Small description**  

This is a one-off problem, but I'm looking for thoughts/ideas on how to debug rather than a fix (and am posting an issue per @saulpw's suggestion).  

When I install `VisiData` via `brew` or via `pipenv` in a pipenv-created virtual environment it runs fine, but when I install via `pipx` the resulting install throws a seg fault when I try to open a file:

```zsh
$ zsh segmentation fault  vd file_name.db
                                         %
```

 ... and the shell goes bonkers. Keystrokes randomly fire when I try to use the arrow keys or touchpad. I lose all control of the session and I have to do a Hard Reset just to be able to quit the Terminal window. Anyone seen anything similar/thoughts on how to debug?

**Expected result**

File opens in VisiData.

**Actual result with screenshot**

Segmentation fault.  

As you can see in the .gif, I attempt to open an SQLite file and I can't even get the cursor to select the `segmentation fault` message. And then touching keyboard keys causes the stream of strange characters.

![Feb-22-2024 15-48-51](https://github.com/saulpw/visidata/assets/96007/4b80ff88-6751-4898-9e9b-bc102886759d)

**Steps to reproduce with sample data and a .vd**

After the seg fault there is no control of the session, which prevents generating a .vd file.

**Additional context/my Python setup**

OS X 13.6.4 (Ventura)  
zsh 5.9 (x86_64-apple-darwin22.0)  
pyenv 2.3.35  
Python 3.12.1  
pipenv 2023.12.1  
pipx 1.4.3  

Per [this blog post](https://chrisamico.com/blog/2023-01-14/python-setup/), I use `brew` to install `pyenv`, then switch to a current `Python`, then `pip install pipx`, then `pipx install pipenv` and `pipx install visidata` (which leads to the seg fault).

FWIW, `pipx install vd` works flawlessly on another Intel Mac with the Python set up as above but running the following versions:

OS X 12.7.3 (Monterey)  
zsh 5.8.1 (x86_64-apple-darwin21.0)  
pyenv 2.3.31  
Python 3.12.0  
pipenv 2023.10.3  
pipx 1.2.0  
so, as I said, it's a very one-off seeming issue.

**Comment by saulpw** [comment]
First of all, does this happen with any data source, or just sqlite files?   And does it happen instantly, or after a moment or two?  (Do you see anything in the terminal before segfault?)

Also, I think the "terminal going haywire" might be it getting stuck in an incorrect state.  If you type 'reset' and press Enter, does that fix the broken terminal?  If so, that is due to the segfault from within a TUI, and not relevant to the segfault itself.

**Comment by jheasly** [comment]
I tried an SQLite and .csv files and both instantly caused seg faults.

Ah! Yes, `reset` fixes the Terminal/TUI.

**Comment by jheasly** [comment]
**Update:** When installed via plain old `pip`, `VisiData` behaves the same, i.e., immediately returns `segmentation fault` when attempting to open a file.

**Comment by jheasly** [comment]
Got it to work by uninstalling the pipx-installed-with-Python-3.12.1 `VisiData`, uninstalling `pipx`, rolling the global Python back to 3.10.10 (admittedly selected at random) via `pyenv`. Then installing `pipx` with Python 3.10.10 `pip`, then installed `VisiData` with the pipx-with-Python-3.10.10 and **It Just Works**. No segfaults. Yay! I ended up with the same version of `pipx` (1.4.3), so there may be something up with Python 3.12.1 and `VisiData`? 🤷‍♂️ Will have to switch it back and see if the segfaults return ...
