### ISSUE TITLE
Sidebar blinking

### ISSUE THREAD

**Issue by NickOveracker** [saulpw/visidata#2334]
**Small description**
The top few bullet-points in the Directory Sheet sidebar blink each time the selected cell changes.

**Expected result**
No blinking.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
[YouTube demo](https://youtu.be/6uhwxKFcoyo)

**Steps to reproduce with sample data and a .vd**
Open a directory in vd and navigate the directory sheet.

No commands other than the automatically-invoked "open-file".

**Additional context**
VisiData v3.0.2
Python 3.8.0
Ubuntu 18.04.6 LTS (64-bit)

Memory: 125.4GiB
Processor: Intel Core i9-7920X CPU @ 2.90GHz x 24
Graphics: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2

**Comment by midichef** [comment]
Thanks for including video, as it was very helpful in diagnosing the problem. The likely cause of this bug is discussed in https://github.com/saulpw/visidata/pull/2352. I expect it will be fixed by https://github.com/saulpw/visidata/pull/2352/commits/4ed4fb1bb454dc63ff953ed624ddaf6d74fcb083.
