### ISSUE TITLE
[loader] Support for BoltDB

### ISSUE THREAD

**Issue by ThaDaVos** [saulpw/visidata#2339]
We love to build loaders with people that are familiar with the format and how it is used.  Knowing about quirks and variations and usage-in-the-wild is very hepful.

To that end, a new loader can be created quite quickly with the following:

There is a existing terminal viewer: https://github.com/hasit/bolter

**Comment by saulpw** [comment]
Your app is written in Go, whereas VisiData is written in Python.  This unfortunately does not help us implement a loader for VisiData.
