### ISSUE TITLE
A small edit in man, for  zc and  zr 

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#234]
Hi,
in the reference we have "zc and  zr number    move to column/row number".

I would change it in "zc and  zr number    move to column/row number (the number starts from 0)".

Thank you

**Comment by saulpw** [comment]
Hmmm..it is 0-based now, but would it be more intuitive if it were 1-based?  (we should probably call it out explicitly either way).

**Comment by aborruso** [comment]
> Hmmm..it is 0-based now, but would it be more intuitive if it were 1-based? (we should probably call it out explicitly either way).

VisiData in some way is a spreadsheet and the spreadsheet apps is 1-based. For this reason I'm always wrong  with `zr` :) 

But 0 or 1 is in some way is the the same, but I would add a note in the doc.

Thank you

**Comment by saulpw** [comment]
If we want to move to 1-based rows/columns in the future, we should also make statusLine (shown with `Ctrl+G`) and row/col numbers in the cmdlog be the same.  There may be other instances that are needed to make it consistent too.
