### ISSUE TITLE
A small announcment: a VisiData introductory guide in Italian

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#235]
Hi @saulpw and @anjakefala I have written the first release of a **VisiData introductory guide in Italian** :)

I discovered this instrument and I loved it: I think it's important to make it known in my country (and everywhere).

I have put it in a github repo and [this](https://github.com/ondata/guidaVisiData/blob/master/README.md) is the first release of the text.

Tomorrow I will announce it in a Medium blog post. I think I can activate good "word of mouth" in italian open data community (VisiData could be a good tool for open data tasks).

The text of my guide is very inspired by the great work of @jsvine.

I would like to be able to do better and more, but I hope it can still be useful.

Please do not anticipate it. Tomorrow I will announce it on twitter (and I will write also a note here).

Best regards

**Comment by aborruso** [comment]
This is the right URL of the guide https://github.com/ondata/guidaVisiData/blob/master/testo/README.md

**Comment by jsvine** [comment]
Neat! And thank you for the very kind words!

**Comment by saulpw** [comment]
This is awesome, @aborruso!  Thank you so much for using your enthusiasm to spread the word about VisiData.  I think your tutorial turned out really well, too (from what I can read in google translate).

**Comment by saulpw** [comment]
@aborruso, I read through the translated guide, and I thought of a couple of (very minor) points:

- under Pivot Table, maybe it would be good to note that all aggregators on the pivoted column will be created too.
- under Python modules, maybe note that setting the type with `@` and then `=data_immatricolazione.month` would work as well?  So people don't think they have to strftime for such a common task :)

Also we recorded another video last weekend, using your recent issue #227 for inspiration. I hope you don't mind if I mention your name again :)

Happy new year!

**Comment by aborruso** [comment]
Hi Saul,

On Sat, 29 Dec 2018 at 09:06, Saul Pwanson <notifications@github.com> wrote:

>  I read through the translated
> guide, and I thought of a couple of (very minor) points:
>
>    - under Pivot Table, maybe it would be good to note that all
>    aggregators on the pivoted column will be created too.
>

I had no idea, I'm sorry. How to show them?

>    - under Python modules, maybe note that setting the type with @ and
>    then =data_immatricolazione.month would work as well? So people don't
>    think they have to strftime for such a common task :)

It is already written in the text: "NOTA BENE: le funzioni del modulo
datetime sono disponibili in modo nativo per le colonne già impostate (come
tipo) a data. Quanto scritto sopra vale soprattutto come guida al come
precaricare e utilizzare un modulo Python in VisiData."

That in english is something like "NOTE: the functions of the datetime
module are available natively for the columns already set (as type) to
date. What is written above is primarily a guide to how to preload and use
a Python module in VisiData."

>> Also we recorded another video last weekend, using your recent issue #227
> <https://github.com/saulpw/visidata/issues/227> for inspiration. I hope
> you don't mind if I mention your name again :)

I'm very proud to be mentioned. Where can I find this new video?


> Happy new year!
>
Thank you very much, best wishes to you too

**Comment by saulpw** [comment]
Oh, I missed that NOTE.  And the video is not yet out, probably in another week or two.

As for the Pivot aggregators, I don't know how to show them.  I just thought mentioning them was a good idea so people knew (I guess you didn't even know!).

**Comment by aborruso** [comment]
> As for the Pivot aggregators, I don't know how to show them. I just thought mentioning them was a good idea so people knew (I guess you didn't even know!).

I did not understand you, I'm sorry.

I know that I can add, but I understood that they were somehow calculated by default.

Instead you are telling me to point out that it is possible to add them. Now Do I understand you?

**Comment by saulpw** [comment]
Yes, exactly!  I believe you mention it with the Frequency Table, and it works similarly with Pivot, so it seems like maybe a good idea to mention.

**Comment by aborruso** [comment]
On Sat, 29 Dec 2018 at 19:16, Saul Pwanson <notifications@github.com> wrote:

> Yes, exactly! I believe you mention it with the Frequency Table, and it
> works similarly with Pivot, so it seems like maybe a good idea to mention.
>

I'll do it

-- 
___________________

Andrea Borruso
website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by aborruso** [comment]
> Yes, exactly! I believe you mention it with the Frequency Table, and it works similarly with Pivot, so it seems like maybe a good idea to mention.

@saulpw I have added an example with avg aggregator

![image](https://user-images.githubusercontent.com/30607/50542421-08732880-0bbd-11e9-8261-f2726b987378.png)

**Comment by aborruso** [comment]
I have published also a Medium blog post https://medium.com/tantotanto/visidata-il-coltellino-svizzero-per-i-dati-che-probabilmente-non-conosci-2209ffd4fa39

**Comment by anjakefala** [comment]
This is wonderful! ^^ Happiest of New Years. 😊
