### ISSUE TITLE
Add Command Line information to Options Sheet: "cli", "cli_optname", "type"

### ISSUE THREAD

**Issue by Zeethulhu** [saulpw/visidata#2353]
It would be nice to see which options can be set via the command line when looking at the available options in the OptionsSheet.

This has the benefits of;

* Quickly identify the options that can be set at the command line
* Convenient export of CLI options (for documentation?)

If I'm exploring some of the capabilities of visidata and its options. I can filter some of its extra functionality using the module column, and then can see which of its options can be set via the command line.

This reduces having to read the available list from `vd --help` or https://www.visidata.org/man/

As a prototype I've taken some of the code from `visidata/man/parse_options.py` and applied it to `visidata/optionssheet.py`

![image](https://github.com/saulpw/visidata/assets/16505748/d0bd146c-f0e8-4c2a-8969-886839343469)

![image](https://github.com/saulpw/visidata/assets/16505748/b517701a-5d75-401e-b6d6-906321a1a5e2)

```python

@VisiData.api
class OptionsSheet(Sheet):
    _rowtype = Option  # rowdef: Option
    rowtype = 'options'
    precious = False
    columns = (
        Column('option', getter=lambda col,row: row.name),
        Column('module', getter=lambda col,row: row.module, max_help=1),
        Column('value',
            getter=lambda col,row: col.sheet.diffOption(row.name),
            setter=lambda col,row,val: vd.options.set(row.name, val, col.sheet.source)
            ),
        Column('cli', width=0, getter=lambda col, row: col.sheet.isOptionCli(row)[0]),          # ℹ️  New column
        Column('cli_optname', width=0, getter=lambda col, row: col.sheet.isOptionCli(row)[1]),  # ℹ️  New column
        Column('type', width=0, getter=lambda col,row: type(row.value).__name__),               # ℹ️  New column
        Column('default', getter=lambda col,row: vd.options.getdefault(row.name)),
        Column('description', width=40, getter=lambda col,row: vd.options._get(row.name, 'default').helpstr),
        AttrColumn('replayable', max_help=1),
    )
    colorizers = [
        CellColorizer(3, None, lambda s,c,r,v: v.value if r and c in s.columns[2:4] and r.name.startswith('color_') else None),
    ]
    nKeys = 2

    @property
    def guide(self):
        if self.source == 'global':
            r = '# Global Options\nThis is a list of global option settings.'
        else:
            r = '# Sheet Options\nThis is a list of option settings specifically for the current sheet.'

        r += f'\n\n- `e` to edit/toggle the current option value'
        r += '\n- `d` to restore option to builtin default'
        return r

    def isOptionCli(self, row):  # ℹ️  New method
        """
        Returns a tuple containing True/False if the options can be set via the CLI interface and the CLI parameter name.
        """

        if row.name[:5] in ['color', 'disp_']:
            return (False, "")
        else:
            cli_name = f"--{row.name.replace('_', '-')}"
            return (True, cli_name)

    def diffOption(self, optname):
        return vd.options.getonly(optname, self.source, '')

    def editOption(self, row):
        currentValue = vd.options.getobj(row.name, self.source)
        vd.addUndo(vd.options.set, row.name, currentValue, self.source)
        if isinstance(row.value, bool):
            vd.options.set(row.name, not currentValue, self.source)
        else:
            helpstr = f'# options.{self.cursorRow.name}'
            opt = vd.options._get(self.cursorRow.name, 'default')
            if opt.helpstr:
                x = getattr(vd, 'help_'+opt.helpstr, opt.helpstr or '')
                helpstr += (x or '').strip()
            if opt.extrahelp:
                helpstr += '\n'+opt.extrahelp.strip()
            valcolidx = self.visibleCols.index(self.column(self.valueColName))
            v = self.editCell(valcolidx, value=currentValue, help=helpstr)
            vd.options.set(row.name, v, self.source)

    @property
    def valueColName(self):
        return 'global_value' if self.source == 'global' else 'sheet_value'

    def beforeLoad(self):
        super().beforeLoad()
        self.columns[2].name = self.valueColName

    def iterload(self):
        for k in vd.options.keys():
            # v = vd.options._get(k)  # ℹ️  Original line.
            v = vd.options._opts._get(k)  # ℹ️  Modified. Adapted from `parse_options.py` unsure if necessary 🤔
#            if vd.options.disp_help > v.max_help:
#                continue
            if v.sheettype in [None, BaseSheet]:
                yield v
            elif self.source != 'global' and v.sheettype in self.source.superclasses():
                yield v

    def newRow(self):
        vd.fail('adding rows to the options sheet is not supported.')

```

**Comment by saulpw** [comment]
They should all be able to be set via the CLI.  The disp/color options aren't shown in `--help` because there are so many of them and they're cosmetic, so they're almost always set in visidatarc.  But you can set them via the CLI as well.

**Comment by Zeethulhu** [comment]
Thanks. I learned something about Visidata I didn't know before.

The problem I was trying to solve (as trivial as it is) was to be able to quickly output the options that are listed in `--help` to the command line in a way they could be parsed easily into something like `fzf` tool to explore and quickly select options from the command line.

The current `--help` output is difficult to do so because of the line wrapping in the description.

I managed something with some convoluted regular expressions. 

![image](https://github.com/saulpw/visidata/assets/16505748/ae04eb17-6339-4986-9b23-9fc77f39817c)

However it would be a lot easier if I could get a tabular format, instead of resorting to regex.

So, I dived into how the help text and the `man` file is generated, saw it was coming from the Options sheet but there currently wasn't a way to show which ones were available as command line options (and now I know they are **all** available at CLI)

**Comment by saulpw** [comment]
> I managed something with some convoluted regular expressions.

Why not just save the relevant columns from the options sheet as a .tsv?

**Comment by Zeethulhu** [comment]
> > I managed something with some convoluted regular expressions.
> 
> Why not just save the relevant columns from the options sheet as a .tsv?

A very good and practical point, and I think I will do that.

It occurs to me that I was laser focused on trying to get the information from commands alone.

And I realise now that even if the Options sheet did have the information I wanted, I dont think there is a way to export it out of visidata without a replay/playback file.

Unless there is something like; `vd +:global_options:: -b -o visidata_options.tsv`

**Comment by saulpw** [comment]
`vd -P options-global -b -o visidata_options.tsv`

where `-P` is alias for `--preplay`
