### ISSUE TITLE
Allow specifying on CLI the number of lines to load from a file

### ISSUE THREAD

**Issue by jwnacnud** [saulpw/visidata#2356]
If I have a large file, certainly I can just HEAD it to get the lines I want. I'd love to run the following:

vd -n100000 filename.csv

and have visidata simply open the first 100,000 records of the file. I know I can ctrl-c to stop along the way on a large file but that's not consistently stopping in the same place.  I also know that I can head the file, if the file supports that, which parquet doesn't.

Am I just dreaming?

- [X] what should the helpstring say
    This value indicates how many records will be loaded from the input file (default, all of them)
- [X] where should this command go in the menu system
    ON INPUT, not in the menu system.

**Comment by saulpw** [comment]
Hi @jwnacnud, I added a `--max-rows` option that works on most source sheets.  The `-n` CLI flag is already an alias for `--nonglobal`, so there's no short option alias for now.  If you can think of a reasonable one (that isn't already used), please suggest it.
