### ISSUE TITLE
Aggregator with `+` not appearing in frequency table _unless_ selected after typing it out

### ISSUE THREAD

**Issue by gennaro-tedesco** [saulpw/visidata#2359]
**Small description**
When choosing an aggregator via `+`, such aggregator is not added to the frequency table if selected via `<Tab>` scrolling _unless_ it is first selected by typing it out.

**Expected result**
The aggregator is added to frequency tables even if selected via `<Tab>` scrolling.

**Actual result with screenshot**
See recording below. Explanation: consider the below file as `test.csv`
```
class,number
A,1
A,5
B,4
B,3
```
and let us assume we want to sum the values of the column `number` grouped by `class`. In the first attempt below I open the aggregator menu via `+` and "scroll down" until I select the relevant function (in this case `sum`): moving to the key column I then access via `shift+F` the frequency table only to find that the aggregator is not there.

Subsequently instead of scrolling down to the relevant aggregator I type it out manually, say `s-u-m` and _then_ select it: all works as intended in this case and as you can see the aggregator appears in the frequency table as needed.

https://github.com/saulpw/visidata/assets/15387611/b78ddfcf-a5ed-4eee-aaa0-3b74d412206b

**Additional context**
```
python3 -V
Python 3.12.2

vd -v
saul.pw/VisiData v3.0
```
on a 
```
OS         macOS 12.7.4 Monterey
```

P. S. It seems as if scrolling does not really "select" anything, the selection only happens if the menu element is typed out.

Anyway, as always, thank you for the excellent work you people are putting in `visidata`: these little problems are nothing compared to how much work we are getting done using your software.

**Comment by midichef** [comment]
Thanks for the detailed report, the screen recording was very helpful in reproducing this. I can reproduce this behavior on visidata v3.0, but not the latest version, which is v3.0.2. Can you try out v3.0.2 and see if this problem still occurs?

**Comment by gennaro-tedesco** [comment]
> Can you try out v3.0.2 and see if this problem still occurs?

I confirm that it works fine on `v3.0.2` - I will update (sorry, I should have done it already, generally I wait for releases in minor versions first).
