### ISSUE TITLE
Possible to specify non-standard .visidatarc/.visidata file location?

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#236]
It might be neat/useful to be able to specify, via a`vd` command-line flag, the location of the preferred `.visidatarc` file. Based on this code search, I don't see a way to do it, but it's possible I'm overlooking something obvious: https://github.com/saulpw/visidata/search?utf8=%E2%9C%93&q=loadConfigFile&type= 

The same idea, I suppose, for plugins — i.e., if you want to use a custom directory instead of `~/.visidata`.

My specific use-case: I'd like to customize my personal VisiData experience via  `~/.visidatarc` and `~/.visidata`, while also being able to use "vanilla" VisiData for https://jsvine.github.io/intro-to-visidata/

Thanks, as always, for continuing to improve this already-fantastic piece of software!

**Comment by jsvine** [comment]
Ah, it looks like specifying the plugins dir *is* possible, via `--visidata-dir`: https://github.com/saulpw/visidata/blob/80f186a37eb09fb6a07f036da2c0e6302b368aed/bin/vd#L49

So maybe the corresponding command-line option for specifying an alternate `.visidatarc` could be `--visidatarc` or maybe `--visidatarc-path`?

**Comment by saulpw** [comment]
Yes, good idea!  I like `--visidatarc` (it was my first thought too), but maybe `--config` would be more command-line-like?

**Comment by jsvine** [comment]
Awesome, and thanks!
