### ISSUE TITLE
[dev] AttributeError: 'ExprColumn' object has no attribute 'column_letter'  when creating new column from Python expression

### ISSUE THREAD

**Issue by gt00x** [saulpw/visidata#2363]
openSUSE Leap 42.3
saul.pw/VisiData v3.0.2

**Small description**
When creating a new column from a python expression (=) in a Excel xlsx file in vd 3.0.2, I get the error "AttributeError: 'ExprColumn' object has no attribute 'column_letter'". When converting/saving the file as .tsv, then the "=" command silently fails (the created column is empty).

When running the same command on another (older) installation it works fine:  
VisiData v2.10.2
Python 3.6.12.
openpyxl in .local/lib/python3.6/site-packages (2.6.4)
et-xmlfile in .local/lib/python3.6/site-packages (from openpyxl) (1.1.0)
jdcal in .local/lib/python3.6/site-packages (from openpyxl) (1.4.1)

**Expected result**
The column is created from the python command
e.g. = datetime.datetime.strptime(time-column,'%y.%j.%H.%M.%S.%f')

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
Traceback (most recent call last):
 File "my-progs/miniconda3/lib/python3.9/site-packages/visidata/sheets.py", line 216, in _colorize                ║
 r = colorizer.func(self, col, row, value)                                                                                             ║
 File "my-progs/miniconda3/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 45, in <lambda>            ║
 CellColorizer(5, None, lambda s,c,r,v: c and r and s.colorize_xlsx_cell(c,r))                                                         ║
 File "my-progs/miniconda3/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 206, in colorize_xlsx_cell ║
 fg = getattrdeep(row, col.column_letter+'.font.color', None)                                                                          ║
 AttributeError: 'ExprColumn' object has no attribute 'column_letter'

**Steps to reproduce with sample data and a .vd**
First try reproducing without any user configuration by using the flag `-N`.

open the attached xlsx or tsv file and try to e.g. convert the date in the Date column:
= datetime.datetime.strptime(Date,'%y.%j.%H.%M.%S.%f')

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.
!$ python3 -VV
Python 3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0]
!$ pip3 install openpyxl --upgrade
openpyxl in ./my-progs/miniconda3/lib/python3.9/site-packages (3.1.2)
et-xmlfile in ./my-progs/miniconda3/lib/python3.9/site-packages (from openpyxl) (1.1.0)

[test1.xlsx](https://github.com/saulpw/visidata/files/14758637/test1.xlsx)
[test1_Sheet1.vdj.txt](https://github.com/saulpw/visidata/files/14758647/test1_Sheet1.vdj.txt)
[test1_Sheet1.tsv.txt](https://github.com/saulpw/visidata/files/14758678/test1_Sheet1.tsv.txt)

**Comment by midichef** [comment]
Thanks for the detailed version information. This bug has been fixed on the develop branch (https://github.com/saulpw/visidata/pull/2299). Can you try the fix out (https://github.com/saulpw/visidata/commit/5e611e39cbb6a35c25bd34c323956f9a7bd44c30) and confirm that it fixes the issue for you?

**Comment by gt00x** [comment]
Thank you for the quick response. 
I installed the dev branch with 
` pip3 install --upgrade git+https://github.com/saulpw/visidata.git@develop`
and did a quick test:
- the error no longer appears
- but : the resulting column is created empty. (see screenshot)

![image](https://github.com/saulpw/visidata/assets/26870648/4346fcdf-f501-4b78-87ff-6861f82aead4)

**Comment by midichef** [comment]
The `!` symbols indicate that there were errors when calculating the new cells. To see the errors, navigate to one of the cells and run `error-cell` in it (either by hitting `Space` and typing `error-cell` in the command prompt, or by the shortcut `z` `Ctrl+E`). It will open a new sheet with a traceback for the error in that cell.

The error is probably due to the `datetime` module not being imported. That would be fixed by adding the line `import datetime` to `.visidatarc` in your home directory.

**Comment by gt00x** [comment]
Thanks for the detailed steps to check ... and fix it. It is working now. The "error-cell" command is quite handy to know :-). (I was not aware this is necessary. In my old 2.10 installation, I don't have a .visidatarc and still it is working. )
Thanks again for the quick help.
