### ISSUE TITLE
Cannot open xpt files with the latest xport dependency version

### ISSUE THREAD

**Issue by v** [saulpw/visidata#2364]
**Small description**

visidata needs a specific version of the `xport` package to open XPT files, but this isn't specified in the requirements anywhere

**Expected result**

Should open xpt files.

**Actual result with screenshot**

![image](https://github.com/saulpw/visidata/assets/627846/6e46e790-273f-475d-8f66-6831a892384e)

```
Traceback (most recent call last):
File "/Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages/visidata/threads.py", line 220, in _toplevelTryFunc
t.status = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages/visidata/sheets.py", line 260, in reload
self.loader()
File "/Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages/visidata/sheets.py", line 285, in loader
for r in self.iterload():
File "/Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages/visidata/loaders/sas.py", line 25, in iterload
for i, var in enumerate(self.rdr._variables):
^^^^^^^^^^^^^^^^^^^
File "/Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages/xport/__init__.py", line 849, in __getattr__
return getattr(self.dataset, name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages/pandas/core/generic.py", line 5487, in __getattr__
return object.__getattribute__(self, name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Member' object has no attribute '_variables'
```

My locally installed versions of visidata and xport are as follows:

```
$ pip show xport
Name: xport
Version: 3.6.1
Summary: SAS XPORT file reader
Home-page: https://github.com/selik/xport
Author: Michael Selik
Author-email: michael.selik@gmail.com
License: MIT
Location: /Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages
Requires: click, pandas, pyyaml
Required-by: 
```

```
$ pip show visidata
Name: visidata
Version: 3.0.2
Summary: terminal interface for exploring and arranging tabular data
Home-page: https://visidata.org
Author: Saul Pwanson
Author-email: visidata@saul.pw
License: GPLv3
Location: /Users/vaibhav/.pyenv/versions/3.11.5/envs/onc/lib/python3.11/site-packages
Requires: importlib-metadata, python-dateutil
Required-by: 
```

**Steps to reproduce with sample data and a .vd**

1. Download this xpt file:

https://github.com/prasertcbs/basic-dataset/blob/8c80eb454b2defd3db217d8f95883eb6a1e3f263/brakes.xpt

2. Open it using visidata, and notice that you get the exception above.

```
AttributeError: 'Member' object has no attribute '_variables'
```

3. If I `pip install 'xport<3'`, visidata opens the file just fine.

**Additional context**
Please include the version of VisiData and Python.

Visidata version included above.

Python version:

```
$ python --version
Python 3.11.5
```

**Comment by midichef** [comment]
Thanks for pointing this out, @v.

It appears that visidata relies on behavior from xport v2, and [xport v3 has changed how to read files](https://github.com/selik/xport/blob/master/CHANGELOG.rst):
```
v3.0.0, 2020-04-20
Revise API to the load/dump pattern. Enable specifying dataset name, variable names, labels, and formats.
```

Perhaps visidata should switch to using [xport v3's load() for reading files](https://github.com/selik/xport?tab=readme-ov-file#reading-xpt).

As a side note, while investigating the xport v2 format, I noticed the .xpt loader has a bug. It will cause inability to edit cells, and possibly odd behavior when selecting rows. I've proposed a fix here: https://github.com/saulpw/visidata/pull/2365
If you run into such problems, you may want to apply that fix. If not, an alternate workaround would be to save .xpt files right after opening them, in some other format (like .tsv or .json). Then reopen the new .tsv file in visidata.

**Comment by midichef** [comment]
I've drafted a fix to update visidata's use of xport from xport v2 to v3.6.1. I'm unfamiliar with SAS and Pandas, so I cannot test it thoroughly. But it does seem to give the same results as Visidata v3.0 for this 2-column test file of numbers: https://github.com/prasertcbs/basic-dataset/blob/8c80eb454b2defd3db217d8f95883eb6a1e3f263/brakes.xpt.

I'll leave the draft here as a starting point for anyone who wants to work with it in the future: https://github.com/saulpw/visidata/commit/793ec73af678e72d3e2dce77ccc916aede41b9c4

**Comment by saulpw** [comment]
I took @midichef's draft and integrated it into the .xpt loader.  Let us know if there are any issues with it.

**Comment by anjakefala** [comment]
Hi folks!

For reasons I don't understand, this latest change breaks on the Python 3.12 build: https://github.com/saulpw/visidata/pull/2516

I tried reproducing locally, and wasn't able to. Exact same python, xport, and pandas version would lead to a passing test for me. 

For now, i turned off `load-xpt` for the Python 3.12 CI. If anyone wants to take a crack at understanding this, they are welcome to! Then we can turn it back on. =)
