### ISSUE TITLE
AttributeError: `AttrColumn` object has no attribute `column_letter`

### ISSUE THREAD

**Issue by RoryWatts** [saulpw/visidata#2367]
**Small description**
In v3.0.2 When opening some .xslx worksheets, I get multiple `AttributeErrors` (4884x in the attached workbook on worksheet `cr2` for example)
[COPD Projection Results Spectrum Avenir CR Null CR1 CR3.xlsx](https://github.com/saulpw/visidata/files/14813931/COPD.Projection.Results.Spectrum.Avenir.CR.Null.CR1.CR3.xlsx)
Each time I perform a command (e.g. move to the next row or column), these errors are logged again, causing massive slowdown.

**Expected result**
Wouldn't expect massive slowdown because of continuous logging of errors.

**Actual result with screenshot**
![Here's the error](https://github.com/saulpw/visidata/assets/24748959/1f80422d-f548-4c76-9da3-43e338f0ea94)

Here's the stack trace
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
![image](https://github.com/saulpw/visidata/assets/24748959/34020d52-d997-4d33-bb99-0daca3403193)

**Steps to reproduce with sample data and a .vd**
I recently installed visidata with `pip install --upgrade visidata` which upgraded it from v.2.11 to v.3.0.2

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.
[replay.vdj.md](https://github.com/saulpw/visidata/files/14813943/replay.vdj.md)
(NOTE - I changed the file extension so I could attach it here)

**Additional context**
Please include the version of VisiData and Python.
Visidata v3.0.2
Python v.3.10.12

**Comment by anjakefala** [comment]
Hello!

This was fixed in the develop branch, and will be part of the next release. =)

Please see here for details: https://github.com/saulpw/visidata/issues/2363
