### ISSUE TITLE
The expression used for custom columns using `=` is evaluated repeatedly

### ISSUE THREAD

**Issue by mplattner** [saulpw/visidata#2371]
**Small description**
I experienced that when a custom column is added using `=`, the expression is evaluated/executed many times (20+ times for the initial view). Simple visidata actions such as using the arrow keys each add 10-20 executions of the function, even for my sheet with only two rows.

Example:
```
# .visidatarc
def myfunc():
    myfunc.counter += 1 # static variable to demonstrate the issue
    return myfunc.counter

# initialize to 0
myfunc.counter = 0
```

Then open a file (e.g., CSV) using visidata, press `=` and use `myfunc()` as the expression.

**Expected result**
```
│ myfunc ║
│ 1     #║
│ 2     #║
```

**Actual result with screenshot**
```
│ myfunc ║
│ 23    #║
│ 24    #║
```

**Steps to reproduce with sample data and a .vd**
```
# test.csv
ips
1.1.1.1
8.8.8.8
```
```
#!vd -p
{"sheet": "global", "col": null, "row": "disp_date_fmt", "longname": "set-option", "input": "%Y-%m-%d %H:%M", "keystrokes": "", "comment": null}
{"sheet": "global", "row": "clean_names", "longname": "set-option", "input": "True", "keystrokes": ""}
{"longname": "open-file", "input": "test.csv", "keystrokes": "o"}
{"sheet": "test", "col": "ips", "row": "", "longname": "addcol-expr", "input": "myfunc()", "keystrokes": "=", "comment": "create new column from Python expression, with column names as variables"}
```

**Additional context**
VisiData 3.0.2
Python 3.10.7
Fun fact: I learned that my actual function is executed many times as I ran in a rate limit of an API that the function is using. 😊 I have fixed it for now by using `@cache` from the `functools` module.

**Credits**
I found visidata a couple of days ago and I'm very amazed - it's an incredibly helpful and fun-to-use tool! It's funny, but I keep finding myself opening random (large) CSV files I have on my computer to check what I can extract to learn visidata better. Many, many thanks and congrats to this amazing work! 👏

**Comment by saulpw** [comment]
This is, for better or worse, by design.  If the column is cached (`cache=True`) then it will only run it once per row, unless `z'` is used to reset the cache.  This is probably functionally equivalent to using `@cache` yourself, except you can't reset it.

**Comment by mplattner** [comment]
Ok, thanks. I assumed that it might be by design and/or hard to fix/change. I haven't known about the [cache feature](https://jsvine.github.io/intro-to-visidata/intermediate/large-files/#caching-dynamic-columns) of columns. Sounds good, but I think it might be better to use `@cache` for functions that reach out to a REST-API, as already the initial column creation after submitting `=` seems to evaluate the expression many more times than the number of rows. Feel free to close this issue.
