### ISSUE TITLE
Can't disable mouse

### ISSUE THREAD

**Issue by dsoprea** [saulpw/visidata#2379]
**Small description**

Mouse-disable commands do nothing. In-session disable states invalid command. I'm running in a headless environment over SSH. Since I don't have access to a system clipboard, I need to be able to select values.

**Expected result**

I should be free to select terminal text with my mouse.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

Not disabled. Not including a screenshot in order to avoid confusing the issue.

**Steps to reproduce with sample data and a .vd**
First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

Tried adding to ~/.visidatarc:
```
options.mouse_interval = 0 # disables the mouse-click                           
options.scroll_incr = 0    # disables the scroll wheel 
```

Tried disabling directly:
```
[SPACE] mouse-disable
```

Shows:
```
[...]| no binding for mouse-disable
```

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

Not necessary given that specific commands just aren't doing anything with no prior history.

**Additional context**
Please include the version of VisiData and Python.
VisiData: 1.5.2-1
Python: 3.8.10

VisiData was installed via Apt on Ubuntu 20.04.1 .

The bodge for my particular issue (needing to copy values out the remote terminal) is just to enter command mode, which makes everything in the terminal selectable.

**Comment by anjakefala** [comment]
Hi @dsoprea!

That's actually quite an old version of VisiData. We are now in v3.0+. Some of the things you see documented might not behave as expected.

Having said that, `mouse-disable` was actually not working on `develop`, and I went ahead and fixed that. You can install from the develop branch with `pip3 install git+https://github.com/saulpw/visidata`

There's nothing we can give you to put in your `visidatarc` to disable your mouse. But either `Shift+Mouseclick` or `Option+Mouseclick` should allow you to select text.

**Comment by dsoprea** [comment]
You're right. Updating to latest fixed things. Thank you for the hotkey. That works great. However, the configuration previously give did, in fact, disable the mouse (the cursor is now an I-beam by default in my remote terminal).

Thank you.
