### ISSUE TITLE
Is this the way to unmelt a table?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#238]
Hi,
I have this table that I want to unmelt.

```
id,Variable,Value
1,size,55
1,material,wood
2,size,100
2,material,iron
2,shape,round
```

I'm able to do it in this way:

- set id as key field;
- ad max aggregator to Value;
- select Variable field and click Shift+W.

Is it the right way to do unmelt?

Thank you

**Comment by anjakefala** [comment]
Yup! This is correct. =) We should add this to the docs.

**Comment by aborruso** [comment]
I have written a very small tutorial in English

“Creating non-numeric pivot tables with VisiData (recipe three)” https://link.medium.com/B9Wxt0xq3S

**Comment by anjakefala** [comment]
@aborruso This was fun! ^^ Thank you. I love seeing comparisons of workflows side-by-side. =D
