### ISSUE TITLE
[Windows] Error: use_default_colors() returned ERR

### ISSUE THREAD

**Issue by otonoton** [saulpw/visidata#2383]
Trying to start visidata immediately exits with `Error: use_default_colors() returned ERR`.

VisiData version 2.8
python version 3.11.8

Platform: Windows (mingw64) using default mintty terminal

**Comment by anjakefala** [comment]
Hi @otonoton!

There are a lot of threads of folks navigating using VisiData on Windows. I believe this is the one relevant to you: https://github.com/saulpw/visidata/issues/2172. (using VisiData on Windows requires WSL.)

Can you go through the other Windows threads, and see if the conversations help resolve your challenges?

**Comment by acxz** [comment]
The solution for me was to simply replace this line in `visidata/color.py` with `pass`: https://github.com/saulpw/visidata/blob/77a43da60b70bd14ad40412882b00b54cad806e8/visidata/color.py#L89

i.e.

```
def setup(self):
    pass
```
