### ISSUE TITLE
g* / setValuesFromRegex bug

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#239]
It appears there's a bug with `g*` in v1.5.1. Executing that command produces this error: `UnboundLocalError: local variable 'col' referenced before assignment`.

The code at issue appears to be `setValuesFromRegex(...)` in `regex.py`: https://github.com/saulpw/visidata/blob/80f186a37eb09fb6a07f036da2c0e6302b368aed/visidata/regex.py#L52-L57

The bug appears to have been introduced in this commit: https://github.com/saulpw/visidata/commit/653f330327d92d746d1bf76ea65d46e4852a3e20

Minimal test: 

- `echo "a,b,c" | vd -f csv --header 0`
- On load: <kbd>g*</kbd>
- At prompt: `a/z` + <kbd>Enter</kbd>

**Comment by anjakefala** [comment]
(I have missed your beautiful bug reports. 😇 )

Nice catch! We are going to bundle this up for 1.5.2.

**Comment by anjakefala** [comment]
Okay! The fix is currently on stable. If you would like to pull it in, you can run `pip3 install git+https://github.com/saulpw/visidata.git` as per usual. =D

Thanks for the really thorough bug report. ^^

**Comment by jsvine** [comment]
Thanks!
