### ISSUE TITLE
Can't open any file

### ISSUE THREAD

**Issue by jbayardo** [saulpw/visidata#2403]
**Small description**

Installed visidata (3.0.2) via 3 different methods: pipx install, conda install and pip install. Also tried visidata dev as of right now (a48c4ee)

I have a small file, test.csv with the following content:

![image](https://github.com/saulpw/visidata/assets/1063569/d5c99c64-d67c-4305-8c71-fff539ae4bb8)

**Expected result**

When I run visidata.exe test.csv, I'd expect to see the visidata UI.

**Actual result with screenshot**

I see:

$  visidata.exe .\test.csv
saul.pw/VisiData v3.0.2
opening .\test.csv as csv

And it just exits. There is no UI involvement at all. This happens reliably regardless of installation method for v3.0.2 and dev. The same thing happens with --debug and --nothing

![image](https://github.com/saulpw/visidata/assets/1063569/7eeba12f-821c-409f-8b06-692b27a41700)

I haven't found any way to obtain tracing information about what's going on, but would be happy to run with any necessary options to test.

**Steps to reproduce with sample data and a .vd**

1. Install
2. Try to open any file

**Additional context**

Reproduces on 3.0.2 and dev, using pipx, conda forge or pip install against python 3.12.2. May also happen with other versions, but I'm unsure.

I'm using Windows Terminal with Powershell, but it also happens using cmd (i.e., I don't think PowerShell has anything to do with it).

**Comment by anjakefala** [comment]
Hi @jbayardo!

There are a lot of threads of folks navigating using VisiData on Windows. I believe this is the one relevant to you: https://github.com/saulpw/visidata/issues/2172. (using VisiData on Windows requires WSL.)

Can you go through the other Windows threads, and see if the conversations help resolve your challenges?

**Comment by jbayardo** [comment]
@anjakefala it looks like this is the problem: https://github.com/zephyrproject-rtos/windows-curses/issues/52

This worked for me:

```
conda create -n vd python=3.11
conda activate vd
pipx install visidata
```

It might save you some github issue management time if this were added to the official install instructions.
