### ISSUE TITLE
Scientific notation shown for column with large number even when type is string

### ISSUE THREAD

**Issue by jay-babu** [saulpw/visidata#2404]
**Small description**

![image](https://github.com/saulpw/visidata/assets/36803168/dabb21a9-4d98-42d4-b845-1eaaf10468b5)

**Expected result**

Seeing the original string that is in the csv

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.

**Comment by jay-babu** [comment]
[MarketData_may_v4_fix_v2.csv](https://github.com/saulpw/visidata/files/15287370/MarketData_may_v4_fix_v2.csv)

**Comment by saulpw** [comment]
I mean that is the string that is in the .csv file, what else would you expect?  VisiData does no automatic typing or conversion.
