### ISSUE TITLE
TypeError: '<' not supported between instances of 'CsvSheet' and 'CsvSheet'

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#241]
I encounter the error in the title of this issue when trying to sort by the `origin_sheet` column of the result of an append-join. 

It's easy enough to get around by <kbd>=</kbd> + `origin_sheet.name` + <kbd>Enter</kbd>, and then sorting on that new column ... but it also seems like it could be handled natively by giving `CsvSheet` the relevant comparison methods. What do you think?

Minimal example / command log: [csvsheet-example.zip](https://github.com/saulpw/visidata/files/2722757/csvsheet-example.zip)

**Comment by saulpw** [comment]
I decided to make BaseSheet sortable by name, and then by id(sheet) (an arbitrary tiebreaker for same-named sheets).  Nice find, @jsvine, thanks for the bug report.

**Comment by jsvine** [comment]
Thanks! That fix sounds/looks good.
