### ISSUE TITLE
[BUG] Opening in interactive shell using `xdg-open` yields `unexpected EOF`

### ISSUE THREAD

**Issue by LnLcFlx** [saulpw/visidata#2413]
**Small description**
`xdg-open file.csv` inside an interactive bash shell gives
```
%f': unexpected EOF while looking for matching `''
```
and exit code 1.

**Expected result**
Using `xdg-open` outside a terminal (e.g. a script) it successfully opens a new terminal and visidata inside of it.

**Steps to reproduce**
1. set `visidata.desktop` as default app for some mimetype e.g. `text/csv` (e.g. in `~/.config/mimeapps.list`)
2. `xdg-open file.csv`

**Additional context**
- Linux 6.9.2-arch1-1
- Python 3.12.3
- Kitty 0.35.0

This is probably due to some string escape problem in the line
```desktop
Exec=bash -i -c 'vd %f'
```
in `visidata.desktop`

**Comment by midichef** [comment]
Can you see if it works if you change that line in `visidata.desktop` to:
`Exec=vd %F`

That's two changes: get rid of bash, and then make `%f` uppercase. `%F` is a list of files, according to [documentation](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html). I would expect it is more versatile than the lowercase `%f` that only handles one file.

I'd test it myself, but I can't figure out how to get my system to use `visidata.desktop`. I've run into a bit too much trouble trying to get `xdg-mime default` to work.

**Comment by LnLcFlx** [comment]
Can confirm this work (just having `Exec=vd %F`).

**Comment by midichef** [comment]
Thank you, I will submit the change.

**Comment by midichef** [comment]
@anjakefala 
I just looked into the history of the .desktop file, that the current configuration worked for you in #1738. Can you check whether the simpler version works for you:  `Exec=vd %F`? I based it on [vim's .desktop file](https://github.com/vim/vim/blob/f51ff96532ab8f97f779b44d17dccdda9d8ce566/runtime/vim.desktop#L112).

In particular, does it work for filenames that have spaces in the middle, and for opening multiple files at the same time?

**Comment by anjakefala** [comment]
This is available on `develop`, and will be in the next VisiData release!
