### ISSUE TITLE
[question] Cannot select rows from CSV file where column value has leading whitespace

### ISSUE THREAD

**Issue by efung** [saulpw/visidata#2414]
(I'm using VisiData 3.0.2 installed via pip3 with Python 3.11.9)

Given the following CSV file:

```
Name,Colour
Joe, Green
Jill,Red
Marta,Yellow
Chun, Grey
Ahmad,White
Bo,Maroon 
Steph,Mauve 
Erik,Silver
```

Note that all rows where the colour value beings with a `G` contain a **leading space**, while those where the colour value begins with `M` contain a **trailing space**

In VisiData, I can successfully select rows where there is a trailing space like this:

```
c Colour
| [ ]+$
```

Both the Maroon and Mauve rows get selected.

However, if I try to select rows where there is a leading space:

```
c Colour
l ^[ ]+
```

No rows get selected.

Why is this not possible? I'm guessing there is some stripping of whitespace going on? Is there a way to disable this?  

I later discovered `options.csv_skipinitialspace` but even if I set that to `False` in my `~/.visidatarc`, it seems to have no effect.

**Comment by saulpw** [comment]
Yes, this is due to the csv format allowing spaces between fields; if you really want them preserved, they need to be quoted.

`options.csv_skipinitialspace = False` works for me with the develop branch, are you sure it's not working for you?

**Comment by efung** [comment]
Ah, I see.

Tried again with the sample CSV I posted above, and it's working as expected.  

When I reported it not working with `options.csv_skipinitialspace = False` before, it's possible I was reading a version of a CSV file in which the column already had those leading spaces removed (which is what I was trying to do with VisiData in the first place 😀)
