### ISSUE TITLE
[addcol-shell]. Quoted special shell characters are not properly quoted.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2415]
**Small description**
The `addcol-shell` command uses shlex.split to break up the user provided shell command, but uses  ' '.join to rebuild the command.  When there are quoted values, they are not properly put back together.

**Expected result**

Quoted values are properly quoted when sent to the shell.

**Actual result with screenshot**

Going straight to Python. Code: https://github.com/saulpw/visidata/blob/develop/visidata/shell.py#L76-L82

If the code used shlex.join() it would properly quote the string `"what | not-a-command"`, but with `' '.join()` it does not properly quote the pipe character with unexpected results.

```
python3
>>> import shlex
>>> shlex.join(shlex.split('echo "what | not-a-command"'))
"echo 'what | not-a-command'"
>>> ' '.join(shlex.split('echo "what | not-a-command"'))
'echo what | not-a-command'
```
The shlex.join() makes sure to re-quote the string, but not string join.

**Steps to reproduce**

Use the `z;` command.  Then type in a command line like `echo "| Ceci n'est pas une pipe"`

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?
**yes**

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?
**yes**

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)? Linux

- Which version of Python? 3.12

The issue can be fixed by using https://docs.python.org/3/library/shlex.html#shlex.join in the code like here:  https://github.com/saulpw/visidata/blob/develop/visidata/shell.py#L76-L82

This was added in 3.8.  What versions of Python does VisiData support?

**Comment by anjakefala** [comment]
Hi @frosencrantz!

Thanks for researching this thoroughly. It was what I needed to finally officially drop support for 3.7.

**Comment by frosencrantz** [comment]
Thank you @anjakefala!  The fix handles the case I originally hit. 

Dropping 3.7 support makes sense. According to https://devguide.python.org/versions/, Python 3.7 has end-of-life status, there will not even  be security fixes.   I did not know that when I posted this bug.  Glad I could help.
