### ISSUE TITLE
How to get started with writing a Guide

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2423]
I'd like to begin the SortGuide.md; I'm on macOS 14.5 23F79 arm64 and am generally using `3.12.2 (set by /Users/reagle/.pyenv/version)`.

```
cd ~/bin/
git clone https://github.com/saulpw/visidata.git
cd visidata
❯ ls guides
ColumnsGuide.md  SortGuide.md
❯ ls visidata/guides
DirSheet.md	JsonSheet.md	MenuGuide.md	   SortGuide.md
ErrorsSheet.md	MacrosSheet.md	SelectionGuide.md  XsvGuide.md
```

1. Why is there `guides` in `visidata` and `visidata/visidata/`?
2. I added `SortGuide.md` to both, but when I run `~/bin/visidata/bin/vd` "Sorting" is not an option.

**Comment by anjakefala** [comment]
Hi @reagle! I'm so excited that you want to contribute a guide! =)

1. `guides` in the root level should be removed. I'll go ahead and do that. That was a place where we were storing some WIP drafts. `visidata:visidata/guides` is the correct place!

2. And that's so weird that you're not seeing it in `visidata --guides`! I did this from within the visidata repo: `touch visidata/guides/SortGuide.md`, and it showed up highlighted in `visidata --guides`. Could you get me a gif recording of what you're seeing? I can even hop on discord for debugging.

**Comment by anjakefala** [comment]
We've moved the debugging part of this conversation to discord
