### ISSUE TITLE
rendering goes wrong (control chars are shown)

### ISSUE THREAD

**Issue by lodagro** [saulpw/visidata#2426]
**Small description**

**Data to reproduce**

 https://jsvine.github.io/intro-to-visidata/_downloads/a61d9b28e9a942e1254bffeb8289a447/faa-wildlife-strikes.csv

**Steps to reproduce**

```vd faa-wildlife-strikes.csv```
Create frequency table

**Expected result**

![image](https://github.com/saulpw/visidata/assets/1094464/88a4dda5-748a-4476-9b86-e633132f9677)

vd version 2.11.1

**Actual result with screenshot**

vd version 3.0.2

![image](https://github.com/saulpw/visidata/assets/1094464/f49e3ca9-d8f4-45c9-af88-c23d89c7e4c4)

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?

yes

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?

latest release: yes
saul.pw/VisiData v3.1dev: yes

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?

Linux

- Which version of Python?

3.10.0

- Which terminal are you using (for display and input issues)?

gnome-terminal and xterm

**Comment by midichef** [comment]
Thanks for giving detailed configurations descriptions.

Can you describe your Linux system more specifically? Which distribution (Ubuntu, or Debian, or Fedora, etc) and specific version (for example, my Ubuntu version is 22.04.4)? `cat /etc/os-release` may help with this, specifically the `VERSION=` line.

Also, what is your terminal version:  `gnome terminal --version`

And can you give more details on your terminal settings? What is the output of these commands (the last 2 may not exist on your system):
`echo $TERM`
`echo $LANG`
`tset -q`
`locale`

**Comment by lodagro** [comment]
```
❯ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
```
❯ gnome-terminal --version
# GNOME Terminal 3.28.2 using VTE 0.52.4 +GNUTLS
```

```
❯ echo $TERM
screen-256color
```

```
❯ echo $LANG
en_US.UTF-8
```

```
❯ tset -q
screen-256color
```

```
❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by midichef** [comment]
I have not yet been able to get access to a CentOS system where I can reproduce this behavior.

Your TERM variable suggests to me that you are set up to use tmux or screen. Perhaps the behavior is related to this.

Can you try two things and report back? What happens if you open xterm and then in the shell there, run `export TERM=xterm-256color` and then run `vd` there? And what happens if  you run gnome-terminal, and in that window, `export TERM=gnome-256color`, and then run `vd` there?

**Comment by lodagro** [comment]
tmux is what i use. 

Below is the result of the two experiments (using saul.pw/VisiData v3.0.2).

### xterm

export TERM=xterm-256color

![image](https://github.com/user-attachments/assets/28307247-94e4-4bfe-bf79-90a58e85c2af)

### gnome-terminal

export TERM=gnome-256color

![image](https://github.com/user-attachments/assets/5cc4241c-5864-43f2-abc0-fb2c196c37ee)

**Comment by lodagro** [comment]
After upgrading tmux to version 3.4, rendering is ok with visidata 3.0.2.
The older tmux version i was using was version 3.1b.

**Comment by saulpw** [comment]
So weird.  Glad you got it working though, @lodagro!
