### ISSUE TITLE
Problem with deb version

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#243]
Hi,
I have installed it with 

```
wget https://github.com/saulpw/deb-vd/raw/master/pool/main/v/visidata/visidata_1.5.2-1_all.deb
sudo dpkg -i visidata_1.5.2-1_all.deb
```

When I use it I have

```
Traceback (most recent call last):
  File "/usr/bin/vd", line 152, in <module>
    main()
  File "/usr/bin/vd", line 52, in main
    vdtui.loadConfigFile('~/.visidatarc', globals())
AttributeError: module 'visidata' has no attribute 'loadConfigFile'
```

**Comment by aborruso** [comment]
I have no problem with visidata_1.5-1_all.deb

**Comment by anjakefala** [comment]
Conversation has been moved to here: https://github.com/saulpw/deb-vd/pull/1

**Comment by anjakefala** [comment]
My current prediction is that this issue is not reflecting a problem with the debian package. I will leave this open until aborruso's problem has been fixed.

**Comment by aborruso** [comment]
It's not a debian package problem. Thanks to @anjakefala, the problem has been solved https://github.com/saulpw/deb-vd/pull/1
