### ISSUE TITLE
Odd memory sheet binding

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2431]
When I try to see the memory sheet I get: 'no command for "alt+shift+m".' When I look at the command help, I see an odd binding: `Alt+Shift+Shift+M`. 

```
sheet	module	longname	keystrokes	description
TableSheet	memory	open-memos	Alt+Shift+Shift+M	open the Memory Sheet
```
Editing the `keystrokes` cell to "Alt+Shift+M" is unable to change it. This config setting has no effect:

```
TableSheet.unbindkey('Alt+Shift+Shift+M')
TableSheet.bindkey('Alt+Shift+M', 'open-memos')
```

**Comment by saulpw** [comment]
This is fixed on the develop branch.  We should do a pass on some other issues (including the sidebar usability) and release a 3.1 soon.
