### ISSUE TITLE
visidata thinks ODS spreadsheets have 16K columns, 1M rows, uses all my memory and crashes

### ISSUE THREAD

**Issue by dandrake** [saulpw/visidata#2440]
Whenever I try to load an OpenOffice / LibreOffice spreadsheet (an ods file), visidata thinks every sheet has 16384 columns, 1 million (okay, 2^20) rows, and it crashes when it runs out of memory.

This is on Ubuntu 24.04.

I can save the same spreadsheet in Excel format and visidata works fine. It seems that something is wrong with the ODS converter.

**Comment by saulpw** [comment]
Hi @dandrake, what version of VisiData are you using?  It works for me in the develop branch.  Can you download our ODS sample data and see if it works for you? https://github.com/saulpw/visidata/raw/develop/sample_data/benchmark.ods

**Comment by dandrake** [comment]
I did some more testing, and I don't think this is a visidata bug. Here's the background for anyone else encountering this:

I think this comes from Google Sheets. When you download those, you get wonky spreadsheets; I'm not sure if it's just ODS format, or any format.

But, if I take one of those spreadsheets, I can do one of the following to get a new spreadsheet that works as expected:

First, convert to Excel with something like `libreoffice --headless --convert-to xlsx input.ods`. That gives a spreadsheet that visidata thinks has a million rows in some sheets, but it loads and works fine. 

Second:

* open the existing, downloaded spreadsheet. In another window, create a new blank spreadsheet.
* For each sheet, copy just the cells with data. Don't use ctrl-A to select all; that will grab the 16K columns and 1M rows. 
* But, I think even *that* may not be enough! I did those steps *again* to yet a 3rd spreadsheet, and that, somehow, finally, avoided whatever wonkiness was infecting the original spreadsheet.

**Comment by saulpw** [comment]
Thanks for the update, @dandrake.  Can you attach a small .ods file that exhibits the behavior you're seeing?  Maybe there's a way to improve VisiData even if the file itself is wonky.

**Comment by dandrake** [comment]
Even better: see <https://docs.google.com/spreadsheets/d/1fvI6ZnACxbT35AdF49EH6Fw7d4QaS1qthpe9SixXwA4/edit?usp=sharing>

STeps to reproduce:

1. Download that as ODS.
2. Open with visidata. That actually worked -- 1 million rows, 1K columns -- but it needed a LOT of memory. (My computer has 32GB; usage topped out at over 15GB starting from about 6.5.)
3. Open the spreadsheet with LibreOffice. I have the usual version shipping with Ubuntu 24.04, which seems to be 24.2.4.
4. Ctrl-A to select all cells. Change the font to Liberation Sans.
5. Save.
6. Now open again -- visidata now thinks there are 16K columns. Memory usage climbed past 18GB and I wasn't brave enough to keep going, as previously my computer froze up when it ran out of memory (Linux's OOM killer wasn't quite smart enough?).

I'm also attaching the exact ODS file from step 6.
[Untitled spreadsheet.ods](https://github.com/user-attachments/files/16133141/Untitled.spreadsheet.ods)

Another way to reproduce: just save as Excel, open in LibreOffice, and save as ODS. The resulting spreadsheet ([visidata and XLSX export.ods](https://github.com/user-attachments/files/16133180/visidata.and.XLSX.export.ods)) has the same behavior.

Everything I've downloaded from Google Sheets does this.

**Comment by saulpw** [comment]
This is due to Google Sheets padding the sheet with repeated empty cells and rows (with e.g. attribute `number-rows-repeated: 1048570`).  Pandas handily strips empty cells/rows at the end: https://github.com/pandas-dev/pandas/blob/d96646219618e007f64ee49e0a6e20f4aea761b5/pandas/io/excel/_odfreader.py#L137

And now we'll do the same.

**Comment by anjakefala** [comment]
Hi @dandrake!

Saul pushed the fix he had proposed. I tested it, and it resolves the problem.

Please update your version of VisiData to develop with `pip3 install git+https://github.com/saulpw/visidata.git`. This will be shipped in the next release.
