### ISSUE TITLE
Trying to open quick reference (`gCtrl-h`) throws `NameError: name 'TextSheet' is not defined`

### ISSUE THREAD

**Issue by dkasak** [saulpw/visidata#2441]
**Small description**

Trying to open the quick reference (`gCtrl-h`) throws the `NameError: name 'TextSheet' is not defined` error.

**Data to reproduce**

N/A

**Steps to reproduce**

Open visidata and press `g`, followed by `Ctrl-h`.

**Expected result**

Quick reference opens.

**Actual result with screenshot**

```
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/visidata/basesheet.py", line 211, in execCommand
escaped = super().execCommand2(cmd, vdglobals=vdglobals)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/visidata/extensible.py", line 79, in wrappedfunc
r = oldfunc(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/visidata/basesheet.py", line 76, in execCommand2
exec(code, vdglobals, LazyChainMap(vd, self))
File "sysopen-help", line 1, in <module>
'VisiData: a curses interface for exploring and arranging tabular data'
^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/visidata/help.py", line 163, in openManPage
vd.push(TextSheet('man_vd', source=module_path/'man/vd.txt'))
^^^^^^^^^
NameError: name 'TextSheet' is not defined. Did you mean: 'MetaSheet'?
```

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?

Yes

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?

With the latest release. Develop branch untested.

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?

Linux

- Which version of Python?

CPython 3.12.4

- Which terminal are you using (for display and input issues)?

kitty

**Comment by saulpw** [comment]
It works on develop for me.  We'll have another release soon.
