### ISSUE TITLE
[loader] for linters:  pylint, ruff, and more

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2444]
People using linters would find Visidata very useful. Linter output is often long, with a lot of tabulated results that users would like to filter on. A perfect use for visidata!

So for future reference, here is a list of some Python linters that have JSON output:
```
pylint --output-format=json
pylint --output-format=json2
ruff check --output-format json
ruff check --output-format json-lines
```

If anyone knows of popular linters for other languages than Python, please reply so we can make a list. Especially if the linters already have output in formats that are easy to handle, like JSON or JSONL.

**Comment by reagle** [comment]
Neat idea! `pyright --outputjson` .

**Comment by anjakefala** [comment]
This is a really good suggestion, but we don't see this being on our Roadmap in the near future. I'm going to Kondo this issue for now, but I added a `loader` label so we can find it later when we have more capacity to add loaders.
