### ISSUE TITLE
[website] wikipedia example - wrong table

### ISSUE THREAD

**Issue by piec** [saulpw/visidata#2446]
Hi,

Thanks for visidata, which is amazing.

On the main page https://www.visidata.org/ the wikipedia table should be `table_2` (not `table_1`). I suppose the wikipedia layout has been updated.

Cheers,
Pierre

**Comment by saulpw** [comment]
Thanks @piec!  Should be fixed now.

**Comment by piec** [comment]
cool :)

Related question: is this table a good example because I can't get visidata to sort the population column as a number. I assume it's due to the thousands separator being a `,`?

**Comment by saulpw** [comment]
Use `$` to type it as a dirty float first.

**Comment by piec** [comment]
yay!
