### ISSUE TITLE
Error when editing inside nested object sheet

### ISSUE THREAD

**Issue by egwynn** [saulpw/visidata#245]
When I open a `JSON` file and use `Enter` to dive into a leaf node, `vd` shows me an error if I try to edit it.

### VisiData Version

```.sh
$ vd --version
saul.pw/VisiData v1.3.1
```

**NOTE**: I also reproduced this with `v1.5.2`

### Example JSON file

```.sh
$ jq < demo.json
```

```.json
[
  {
    "A1": {
      "x": "baz"
    },
    "A2": {
      "x": "bap"
    }
  }
]
```

### Command Log

```.sh
$ cat cmdlog-1.vd
sheet   col     row     longname        input   keystrokes      comment
                        open-file       demo.json       o
demo            0       dive-row                ^J
demo[0]                 dive-row                ^J
```

**NOTE**: The exact key sequence (not entirely captured in the above command log) is:

<kbd>Enter</kbd>, <kbd>Enter</kbd>, <kbd>e</kbd>, <kbd>1</kbd>, <kbd>Enter</kbd>

### Error message:

```
TypeError: 'str' object does not support item assignment
```

**Comment by saulpw** [comment]
Thanks for the report, @egwynn!  It's fixed in develop and will be in the next release.
