### ISSUE TITLE
Guides: do guides support markdown tables? If so, which?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2456]
The following markdown is not rendered in the guide, does it support markdown tables?

```markdown

| Command |   Type   |
|---------|----------|
| `~`     | string   |
| `#`     | int      |
| `%`     | float    |
| `$`     | currency |
| `@`     | date     |
| `z#`    | vlen     |
| `z~`    | anytype  |

```

**Comment by saulpw** [comment]
No; we use simple lists instead.  And there's a helpful macro to turn a longname into a standard form with the keystroke and helpmsg, which is what we should use in this case I think.

**Comment by reagle** [comment]
Thanks, I've realized the markdown is very limited -- not even nested bullets -- but that's probably fine for the task.

**Comment by reagle** [comment]
What about openable URLs? For example, in the `TypesSheet.md` I submitted it could be useful to continue on to <https://www.visidata.org/docs/columns/> for more information.

**Comment by anjakefala** [comment]
Here's an example of openable URLs =) 

> See [:onclick https://docs.python.org/3/library/codecs.html#standard-encodings]https://docs.python.org/3/library/codecs.html#standard-encodings[/]

**Comment by reagle** [comment]
Thank you, I see that's in the [Guide Style Guide](https://www.visidata.org/docs/api/style). I added the following, but am not seeing a result:

> *Note*: `float` uses the decimal separator; `currency` removes non-numeric characters and parses as float; `date` parses dates into ISO8601 format; `len` formats the cell value to the length of the content. See 
[:onclick https://www.visidata.org/docs/columns/]Columns[/].

"Columns" is not differentiated, and when I click on it with mouse I get a warning.

<img width="377" alt="SCR-20240719-hqnj" src="https://github.com/user-attachments/assets/d208bbc6-bed3-4a33-b485-e98698c0535a">
<img width="373" alt="SCR-20240719-hqld" src="https://github.com/user-attachments/assets/7a2938ea-c0d2-41f0-9739-95105fc95f11">

**Comment by anjakefala** [comment]
Could you open a new bug report?
