### ISSUE TITLE
csv rows with a leading `#`

### ISSUE THREAD

**Issue by justin2004** [saulpw/visidata#2458]
when i open this csv file with several other csv aware tools i can see the 2nd row

```
% cat some.csv 
name,height
fred,44
#bob,66
```

however when i open it with vd i don't see the 2nd row:
```
% vd -o- some.csv | cat
name    height
fred    44
```

but if i comment [this line](https://github.com/saulpw/visidata/blob/develop/visidata/loaders/csv.py#L82) out

then it works as expected:

```
% vd -o- some.csv | cat
name    height
fred    44
#bob    66
```

should vd have this as a default when other csv aware tools don't?

**Comment by saulpw** [comment]
Thanks for reminding me of this.  It's used for json/jsonl, and was extended to csv/tsv, which has proven to be a mistake.  @jsvine noticed this also.  It should be fixed on develop now and will be in the next release.
