### ISSUE TITLE
[Loader] .xlsb support

### ISSUE THREAD

**Issue by woutervdijke** [saulpw/visidata#246]
A xlsb loader would be nice, and probably not that difficult using the [pyxlsb package](https://github.com/wwwiiilll/pyxlsb).

**Comment by saulpw** [comment]
Hi @woutervdijke, thanks for the suggestion.  I've never seen this format before, could you attach an example .xlsb to this issue?

**Comment by woutervdijke** [comment]
Sorry, I'm only seeing your reply now @saulpw. I can't attach the file but [I downloaded it from here](https://www.rvo.nl/sites/default/files/2019/01/Voorlopige_labels_okt2018.zip) as a zip file.

Fwiw I was able to convert it to a csv file using the following code:
```
import csv
from pyxlsb import open_workbook

with open_workbook('/input.xlsb') as wb:
    for name in wb.sheets:
        with wb.get_sheet(name) as sheet, open(name + '.csv', 'w') as f:
            writer = csv.writer(f)
            for row in sheet.rows():
                writer.writerow([c.v for c in row])
```

**Comment by saulpw** [comment]
Thanks @woutervdijke, that was very helpful.  I forked pyxlsb and added an asynchronous .xlsb loader, which is now in develop and will be in the next big release.  Let me know how it works for you!
