### ISSUE TITLE
Guides: URL not working

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2466]
I am working on `TypesSheet.md` with the following content:

```
# Types

Columns usually begin as untyped (`anytype`), but can be set.

- {help.commands.type-any}
- {help.commands.type-currency}
- {help.commands.type-date}
- {help.commands.type-float}
- {help.commands.type-int}
- {help.commands.type-len}
- {help.commands.type-string}

*Note*: `float` uses the decimal separator; `currency` removes non-numeric characters and parses as float; `date` parses dates into ISO8601 format; `len` formats the cell value to the length of the content. See 
[:onclick https://www.visidata.org/docs/columns/]Columns[/].
```

I am not seeing a result: "Columns" is not differentiated, and when I click on it with mouse I get a warning. See [#2456](https://github.com/saulpw/visidata/issues/2456#issuecomment-2239001172) for screenshots.

======

saul.pw/VisiData v3.1dev on macOS 14.5 23F79 arm64

**Comment by saulpw** [comment]
Thanks for reporting this, @reagle.  It should be fixed now.
