### ISSUE TITLE
Add command palette

### ISSUE THREAD

**Issue by paulklemm** [saulpw/visidata#247]
Often I find myself browsing the (great) `visidata` documentation for the shortcut of the command I want to use because I forgot it again.

One thing that would really help is a command palette like in Sublime Text or Visual Studio Code. One shortcut brings up a search box where one can query basically all commands available in the current context. Showing the keyboard shortcut next to the command also helps a lot memorizing them again.

Here is an example from VSCode:

![image](https://user-images.githubusercontent.com/2169489/52074578-7c249e80-258a-11e9-8a5b-92fb3762e1b1.png)

**Comment by saulpw** [comment]
This is a good idea, @paulklemm.  Do you know about `z Ctrl+H`, which takes you to a sheet of all commands available on the current sheet?  And `g/` which you can use to search that sheet.  It's not quite the same workflow, but I'm wondering how close that gets you to what you want.  What if we improve that workflow (suppose `g Space` to do something similar without going to a separate sheet), and maybe add a 'keywords' column to commands.tsv so that common synonyms can be given without cluttering the helpstring.

**Comment by paulklemm** [comment]
Thanks, the `z Ctrl+H` together with `g/` already is super useful, I wasn't aware of that. Still having something without going to a separate sheet would be nice I think.

**Comment by jtrakk** [comment]
I like how emacs-helm does this by splitting into two panes, where the bottom pane shows the command palette. For visidata, showing the `z Ctrl+H` table in the bottom half of the screen would work nicely, I think. Typing into the palette does a live fuzzy-filter over the options.

![image](https://user-images.githubusercontent.com/43392409/58979229-661a2b00-8782-11e9-9987-ec235f551988.png)

**Comment by saulpw** [comment]
Added `help-search` command that opens a commands sheet filtered by the input regex.  Unbound by default, you could try binding it to `KEY_BACKSPACE` if that works on your system, or `^@` (Ctrl+Space).

I agree, split-pane is the way to do this.  It's already on the roadmap, so I'm closing this issue, though we may not get to it until 2.1.

**Comment by reagle** [comment]
I'm new to visidata and this is the first thing I wanted. I can't find it, and disagree with the suggestion that a static help filter/search is equivalent to the dynamic fuzzy match of a genuine command palette.

**Comment by reagle** [comment]
I’m wondering if this might be in 3.0? Should I create a new issue if this one won’t be reopened?

**Comment by saulpw** [comment]
Good timing, @reagle.  I was just thinking about what should be in 3.0, and command palette is very near the top of the list.  If you're interested in talking through the design, it would be much appreciated; come over to visidata.org/chat if you want to do it sync.

**Comment by reagle** [comment]
Yes! You mean here, vidchat, email? (My timing is because I hadn't used visidata in a few months, forgot all the commands, and soon got frustrated.)

**Comment by saulpw** [comment]
I would prefer a more synchronous chat medium, so come to visidata.org/chat (redirect to a Discord server) and we can either text chat there, or set up a vidchat.  Let's make this experience better for the next time you come back to VisiData after a few months of not using it :)

**Comment by reagle** [comment]
Just sent you an email to schedule something. 😄

**Comment by reagle** [comment]
I, coincidentally, just came across this Textual library: https://github.com/darrenburns/textual-autocomplete

I know you don’t want dependencies, but it might provide some ideas.

**Comment by pacien** [comment]
My two cents: I'd absolutely love this. "CTRL-K" jump and command palettes are
getting more and more common in many programs. It's very handy when thinking
of the name of an action or a word that might match in its description, and to
be reminded of existing keyboard shortcuts at the same time.

For more UI inspiration, here's how the command palette looks like in the Howl
editor:
![howl-tab-31-howl-opensource](https://github.com/saulpw/visidata/assets/1449319/689d8cf4-781c-448d-a927-44721a590041)

**Comment by saulpw** [comment]
@zormit Want to pair on this sometime soon?

**Comment by reagle** [comment]
BTW: I know Textual isn’t right for this project for a number of reasons, but their new command palette might be a useful demo. https://textual.textualize.io/blog/2023/09/15/textual-0370-adds-a-command-palette/

**Comment by anjakefala** [comment]
@zormit @saulpw I would love to join the pairing if schedules work out!

**Comment by zormit** [comment]
@saulpw @anjakefala yes! I'm currently on my way to Strangeloop and then flying back to Germany. So from Tuesday on we can try to find some time.

**Comment by saulpw** [comment]
We've got a command palette now, on `Space`, thanks to @zormit!  Try it out and let us know what you think.
