### ISSUE TITLE
[question] Guides: How much to include?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2472]
Given the changes in the PR related to #2471, I'm wondering how extensive the guides should be?

For example, #2466 arose from my intention to include a URL to other documentation, but perhaps those docs will be obviated as the the [blog post](https://www.visidata.org/blog/2024/help-with-docs/) says:

> Through this consolidation, we will create a single place inside the main repo where the documentation needs to be updated.

Yet, it also says:

> Basically, write a short overview (a couple of sentences, and then figure out which commands and options should be referenced, and how they should be organized. A little goes a long way!

Also, it [appears there is an ability](https://www.visidata.org/docs/api/style) to navigate to other guides and options? (I don't yet understand that without an example in the existing guides.) So perhaps that's an argument for everything, ultimately, within the guides?

(BTW: That's not to say that the URL/onclick issue is unimportant, that could still be useful for a link to a more complete, offsite, resources, such as regex guide.)

**Comment by saulpw** [comment]
My feeling is that the Guides should be complete but not exhaustive.  Maybe we should call them "summary content".  Taken together they should mention maybe 90% of the commands and options, leaving out only the ones which are esoteric or optimized for single specific use-cases.  We want people to feel confident that they can learn all about VisiData from the Guides, without being overwhelmed by the sheer amount of content.

I see the Guides as a second entry point, to be used right after a hand-holding tutorial like jsvine's [Intro to VisiData](https://jsvine.github.io/intro-to-visidata/).  (Ideally it would be referenced in the tutorial as the next place to learn more).  Anyone who just needs a little pointer in the right direction can use the Guides, and then they can either experiment or venture online for additional content, whether videos or forums or long-winded blog posts.

Does that help clarify?
