### ISSUE TITLE
pipx install seems to not install markdown filetype

### ISSUE THREAD

**Issue by fourjay** [saulpw/visidata#2474]
visidata installed with pipx seems to not import/export markdown tables

Install visidata with pipx
read a markdown formatted table with ``visidata -f md``
Visidata opens the file as text, and gives the warning ``unknown "md" filetype``

**Expected result**
input file is read as a table in markdown format

**Actual result with screenshot**
data is read as a text file

[If there is an error message, please include the full stack trace shown with `Ctrl+E`.]
No output

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?
usint ``-N``does not change

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?

This does seem to have surfaced on a newer version (I'd have to poke around installing older versions to pinpoint, and will do so if needed).
I do remember it working a year or so ago.

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?
Linux

I'm wondering if a markdown library is not in the list of required libraries (and used to be).
If so, it would make sense to me that a pipx install would fail.
I am using pipx --inject to install some optional filetype readers

- Which version of Python?
3.11.3

- Which terminal are you using (for display and input issues)?
kitty

**Comment by saulpw** [comment]
Hi @fourjay, there isn't a markdown table loader (see https://visidata.org/format for the full list).  Saving should work but you'll have to install the `tabulate` library manually.

**Comment by frosencrantz** [comment]
Hi @fourjay 

Reading markdown tables has been a past feature request:  https://github.com/saulpw/visidata/issues/1758

As mentioned there, it is possible to use pandoc to filter different types of markup tables to a format that can be *read* by Visidata. 

It is then sort of possible to round-trip (read and then update) with manual edits.  Basically you save the modified table in the format you want, and then manually replacing the table in the original md file.  You can easily lose special formatting with this type of "editing".

As Saul says in that feature request:

> We're always open to PRs for new loaders.
