### ISSUE TITLE
[save] nulls derived from other columns save as "str(None)" "float(None)" etc

### ISSUE THREAD

**Issue by midichef** [saulpw/visidata#2476]
**Small description**
There is a problem saving nulls in the formats `txt`, `csv`, and `tsv`.
When a column is derived from another column via `=`, the new cells that are `None` save as strings like `"(None)"`, `"str(None)"`, `"float(None)"`, etc. The `str`/`float` string before the parentheses comes from the type of the original column at the time of saving.

**Steps to reproduce**
To get `"(None)"`:
`echo '{"col": null}' |vd -f jsonl` then `=` `col` `Ctrl+S` `out.txt`
To get `"float(None)"`:
`echo '{"col": null}' |vd -f jsonl` then `%` `=` `col` `Ctrl+S` `out.txt`  

**Expected result**
```
% cat out.txt
col	col
	
```

**Actual result with screenshot**
```
% cat out.txt
col	col
	float(None)
```
**Configuration**
v3.1dev

**Additional context**
The creation of the `float(None` string is in `iterdispvals()`, where the `ExprColumn` calls the first column's `formatValue()` method:
https://github.com/saulpw/visidata/blob/8f823f5a3d922756e49ed47086419ab366e8fbc4/visidata/save.py#L29
The issue reminds me of https://github.com/saulpw/visidata/issues/2183 for json files. Perhaps the solution will be similar.

**Comment by saulpw** [comment]
Thanks for the report, @midichef!  The solution did indeed involve TypedWrapper.  It's tested for csv, and should work for the other text formats as well.
