### ISSUE TITLE
Double Quotation Character not working on Windows

### ISSUE THREAD

**Issue by tahir-hassan** [saulpw/visidata#2479]
Before I start, I just want to say that I am very impressed with your work.

## Description of issue

On Windows, pressing double quotation key doesn't work.  This is when I use it on the native Windows Python platform.

### How to reproduce 

I am following the tutorial (I am on the bit [Understanding Rows](https://jsvine.github.io/intro-to-visidata/basics/understanding-rows/)) and when it asked me to type in `OPERATOR == "BUSINESS"` I realized that the double quote character did not work.

### How I am installing Visidata 

I am installing Visidata using the following steps:

* Install Python using Scoop using `scoop install main/python`
* Install Visidata using `pip3 install visidata`

### What went wrong

It should write a double quotation character, however nothing happens (no double quotation character is inserted).

### Additional context

| Software | Version |
|---|---|
| Operating System | Windows 10 Enterprise |
| Python | 3.12.2 |
| Terminal | Wezterm, Windows Terminal |

# This works, however...

Pressing double quote key works if I install Visidata using MSYS2's Python. 

## Steps to reproduce working Visidata 

* Install MSYS2 using Scoop using `scoop install main/msys2`.
* Within MSYS2/Mingw64...
    * install Python using pacman using `pacman -S python`
    * install Pip using pacman using `pacman -S python-pip`
    * Create a new venv for Visidata: `cd ~; mkdir visidata; python -m venv ~/visidata`
    * Install Visidata in the above venv: `~/visidata/bin/pip install visidata`
    * Use `~/visidata/bin/visidata` to open files.

I am using `Wezterm` in both instances (raw Python and MSYS2's Python).

# Conclusion

I have also found that the mouse works in MSYS2's Visidata but not the other one.  I think perhaps the documentation should just mention that it is a bad idea to install Visidata in the normal Python and just use MSYS2's Python instead.

**Comment by anjakefala** [comment]
Thanks for all your thorough investigation @tahir-hassan!

> I have also found that the mouse works in MSYS2's Visidata but not the other one. I think perhaps the documentation should just mention that it is a bad idea to install Visidata in the normal Python and just use MSYS2's Python instead.

We have this line in the docs: https://www.visidata.org/install/#windows

> Use Windows Subsystem for Linux (WSL).

I can definitely add a mention of MSYS2's Python, since you tested it.
