### ISSUE TITLE
[pandas develop] add-row error in pandas.DataFrame

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#248]
```
h1,h2
a,10
b,11
```
```python
import pandas as pd
pd.read_csv('the.csv').to_parquet('the.parquet')
```
`vd -f pandas the.parquet`

Pressing `a` to add a new row raises `TypeError: insert() missing 1 required positional argument: 'value'`

**Comment by saulpw** [comment]
Thanks for the report, @apnewberry.  It appears that several commands will have to be rewritten to work specifically with the pandas.DataFrame.  I have a tentative short-term fix for `add-row`, but [there are several different ways to do it](https://stackoverflow.com/questions/24284342/insert-a-row-to-pandas-dataframe) and I'm not sure which one is the best way for VisiData.  Maybe you know how to use DataFrames better than I do?

**Comment by ghost** [comment]
I think pandas doesn't really like to insert rows in arbitrary position, but perhaps 

```python
pd.concat([df.iloc[:location], pd.DataFrame([{'h1': -99, 'h2': -98}]), df.iloc[location:]]).reset_index(drop=True) 
```
or the `.append()` solution of https://stackoverflow.com/a/24284515/3346095

**Comment by anjakefala** [comment]
@ajkerrigan has fixed this! =D
