### ISSUE TITLE
About config display option and regex filters

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#2481]
Hi,
in my config file I have

```
options.disp_float_fmt = '{:,.02f}'
options.disp_int_fmt = '{:,}'
```

And when I open this jsonl input

```
{"name": "andy","value":10245888888}
{"name": "saul","value":10245}
```

I have 

![image](https://github.com/user-attachments/assets/99c3b52e-b8c1-4efb-b796-f8f19f6bbd55)

If I run a regex filter to find all rows in value that contain `8888` I have no result.
To have some result I need to apply a right regular expression for what I see, and not for the value contained in the cells.
I must use `8,888`.

Regex searches operate based on how the cell contents are displayed rather than on the actual values contained within the cells. 
I had never noticed this, and I discovered it because I was going crazy trying to figure out why the regex was not working.
Is this the intended behavior? I'm sure it is.

I believe it would be more useful, and more consistent with user expectations, if regex searches operated by default on the cell values, regardless of how they are displayed.
Couldn't this thing become a boolean configuration parameter? And leave it up to the user if he or she wants regexes to apply to what he/she sees and not to cell values. 

And wouldn't it be a good idea to emphasize the actual behavior in the documentation? "Dear user, please note, regex filters are applied to the value as it is formatted."

Best regards,

Andrea

**Comment by saulpw** [comment]
Hi @aborruso, thanks for the feedback.  I'm sorry that's frustrating, and yes, it is intentional; it's this [`col.getDisplayValue(row)`](https://github.com/saulpw/visidata/blob/378a45904133297a0ec75dbd874644b55b2b5de9/visidata/features/regex.py#L24).  I don't think we should change it (though I'm open to it if other people chime in with the same preference), and an option seems unnecessary since you can get there with one command (`~`) , but I agree that we can put something in the documentation.  Where in the documentation were you looking that you would have seen it yourself?

**Comment by aborruso** [comment]
> it is intentional; it's this [`col.getDisplayValue(row)`](https://github.com/saulpw/visidata/blob/378a45904133297a0ec75dbd874644b55b2b5de9/visidata/features/regex.py#L24)

Okay, you're the boss :)

For me, though, it is the first software where searching via regex does not impact the raw data, but the display configuration.
And that confused me. But I'm the only one, so it's okay.

Thank you

**Comment by saulpw** [comment]
@aborruso I'm sure you're not the only one.  I'd like to put something in our documentation as you suggested in the first place. I just don't know where to put it so that someone like you would be able to find it.  Can you help me out?  Where were you looking while you were frustrated with this?

**Comment by aborruso** [comment]
@saulpw I didn't close the issue without thinking about it, but I thought about it for a while and gave up.

The vd documentation is this one: https://www.visidata.org/man/

The way it is constructed, it is difficult to put a note like this. The note would be this: 

**Note:** Regex searches are performed on how values are displayed, not the actual data values. For example, if the value `8000` is displayed as `8,000`, you must search using `8,000` in your regex, not `8000`.

Or simply: Regex searches are performed on how values are displayed, not the actual data values.

But where to put it? Some ideas:

- at the bottom of that page. But no one would see it. 
- as a footnote, with footnote links, every time a regex search is cited on the page. That seems too invasive to me 
- at the top of the page under "Quick Reference Guide." To me perhaps this seems like the most sensible solution, the way documentation is today 

What do you think, thank you very much

**Comment by saulpw** [comment]
Hm, interesting, I guess we don't have a page on visidata.org about regex.  Maybe we should make one.  Is /man the main way you look for information, or did you type "regex" in the search bar on the website?

What if we included this information in the regex help sidebar in VisiData itself?  Do you ever look at that or do you have sidebars turned off too? :)

**Comment by aborruso** [comment]
I would do all this:

- a page on visidata.org about regex
- put this information in the regex help sidebar 
- find a way to put a small note on https://www.visidata.org/man/ page, because in my opinion it is the most referenced place when you have lost hope of finding a solution.
