### ISSUE TITLE
[] Feature request: Horizontal guide lines in plots

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2482]
It would be cool if I could add horizontal guide to plot. I mean that I could give specific Y values where a line would be drawn from the left edge of the screen to the right edge. Whereever there are datapoints, the line won't be drawn. 

Here's a grab-bag of horizontal line characters at various heights:

```
━─═﹉﹊﹋﹌﹍﹎﹏―—–‐⁃_‗⎯⎼⎽⏤▁▔⚊一
```

We could use the different heights to make the lines more accurately-placed.

**Comment by midichef** [comment]
I've got this mostly implemented. I'm using these characters `▁━▔`, since I don't know of any other Unicode characters for horizontal lines that have vertical levels that I can rely on.

How do you want to specify the y values? From the command line, in .visidatarc, or interactively within visidata?

**Comment by cool-RR** [comment]
Awesome, thank you! I was thinking there'd be an attribute like `graph_sheet.y_guide_lines = [0, 0.5, 1]` and then commands to add or remove numbers to that list. Then I could also write a script in `.visidatarc` that automatically adds guide lines by just adding to that list.

**Comment by midichef** [comment]
Okay I've got it implemented, @cool-RR. Let me know what you think of #2489.

While working on this feature, I fixed some bugs in how points line up with labels. They became very obvious in graphs with lines drawn on them. So you will also want to deploy the fixes in https://github.com/saulpw/visidata/pull/2487.

**Comment by cool-RR** [comment]
Awesome, thank you! What would be the way for me to test this feature, given that it depends on two commits in separate branches?

**Comment by midichef** [comment]
Try this, for `pip`:
```
cd /tmp
git clone -v -v https://github.com/midichef/visidata/ visidata.midichef
cd visidata.midichef
git cherry-pick origin/graph_plot_points origin/graph_line
pip install file://`pwd`
## to reinstall the main branch afterward
# pip uninstall visidata; pip install git+https://github.com/saulpw/visidata
```
If it worked, you'll be able run `vd`, then press `Space` and run `add-line-y`, `remove-line-y`, `clear-lines-y` interactively. I'm not yet sure how to preset line values in `.visidatarc`.

**Comment by cool-RR** [comment]
Thank you, I'll do that soon. Note that you used the term "line" which might be a little generic and overloaded. I asked Claude and ChatGPT what you might call a line like that which doesn't represent real data, and they suggested "baseline", "reference line", "threshold line", "benchmark line", "target line" and "cutoff line". I like the first two suggestions best. Also if this is accepted there's also a good chance that the same feature for the X axis would be desired.

I'll test in the next few days and let you know.

**Comment by midichef** [comment]
Thanks for suggesting alternatives! I agree "line" is too generic, and I like "reference ilne". Maybe change `add-line-*` to `add-refline-*`?

Vertical lines on the X axis are already supported, the `*-y` commands have counterparts in `add-line-x`, `remove-line-x`, and `clear-lines-x`.

**Comment by midichef** [comment]
The `develop` branch has merged the patch fixing alignment between points and labels. So I've deleted the branch I used for that pull request.

Now the commands to try the graph reference-line feature are:
```
cd /tmp
git clone https://github.com/midichef/visidata/ visidata.midichef
cd visidata.midichef
git cherry-pick origin/graph_line
pip install file://`pwd`
## to reinstall the main branch afterward
# pip uninstall visidata; pip install git+https://github.com/saulpw/visidata
```

**Comment by cool-RR** [comment]
I tried it now and it looks good. 

When I first did a line it looked great:

![screenshot_TURING_2024-08-08_095800](https://github.com/user-attachments/assets/de99b36e-b842-42a9-942b-25c350b1cd83)

This is just the right thickness and color I imagined. I see it uses the character `▔`

However, after I pressed `x` and changed `xmin xmax`, the line became thicker and possibly have a different color:

![screenshot_TURING_2024-08-08_095744](https://github.com/user-attachments/assets/bbec3df0-80bc-4274-aa39-4c4c2b5c7774)

This uses the character `━`. I don't like how it looks.

I tried `clear-lines-y` and it worked.

I tried `add-line-x` and got this: 

![screenshot_TURING_2024-08-08_095952](https://github.com/user-attachments/assets/58a43923-c5ec-4de4-93a3-25d9d774a3dc)

Like the previous example, the line is too bold.

Otherwise the feature is great.

**Comment by midichef** [comment]
@cool-RR 
The newest commit on https://github.com/saulpw/visidata/pull/2489 changes the line characters based on your feedback. The y-line characters are now `▔──▁`. Unfortunately I can't find a mid-cell horizontal character in Unicode that is guaranteed to be the same width as the ones at the top/bottom. I've chosen to exclude characters that have tiny visual spaces between characters, like dashes in many fonts: "---". I only looked at characters that leave no visual blank spots between repeated characters, as in your sample images.

Let me know what you think.
