### ISSUE TITLE
Menu rendering glitches on macOS

### ISSUE THREAD

**Issue by dserodio** [saulpw/visidata#2486]
**Small description**

There are some weird rendering glitches on macOS, with some characters left over when navigating the menu (2nd screenshot). Also, it looks like the windows' top and bottom borders are not properly drawing either (1st screenshot).

**Data to reproduce**

I used the [faa-wildlife-strikes.csv](https://jsvine.github.io/intro-to-visidata/_downloads/a61d9b28e9a942e1254bffeb8289a447/faa-wildlife-strikes.csv) file from [An Introduction to VisiData tutorial](https://jsvine.github.io/intro-to-visidata/basics/opening-files/) 

**Steps to reproduce**

1. Open VisiData with `vd faa-wildlife-strikes.csv`
2. Control+H (menu borders are not shown correctly)
3. Hit Right Arrow a few times (some characters left over from previous menus)

**Expected result**

Menus should redraw properly

**Actual result with screenshot**
![SCR-20240805-nuem](https://github.com/user-attachments/assets/bca46b8c-7ad3-4553-b807-73569cd18b04)

![SCR-20240805-nqql](https://github.com/user-attachments/assets/1a0e0034-e9dc-4366-9633-673e18a5c9c2)

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)? **Yes**

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)? **Yes**

**Additional context**

- VisiData v3.0.2
- macOS 14.5
- Python 3.12.4
- Installed with HomeBrew (I also uninstalled and installed with `pipx`, same results)
- Terminal.app (it also happens with iTerm2)

**Comment by reagle** [comment]
Hi @dserodio, I'm not a dev, but I am a fellow Mac user. For what it's worth, I was [not able to replicate](https://asciinema.org/a/gfPI3YMrgtwEWeQDrGVJc1Rd8). (Sorry for the initial pause in the recording, I was reading your sequence so as to replicate). My default vd is in pyenv, but I also installed the homebrew version.

- VisiData v3.0.2
- macOS 14.5 23F79 arm64
- /Users/reagle/.pyenv/shims/python3 (3.12.2)
- /opt/homebrew/Caskroom/iterm2/3.5.4

I wonder what the difference might be?

**Comment by dserodio** [comment]
Hi @reagle, thank you for your help. At first I thought the issue might be cause because I use iTerm 3.5.4beta2 and powerlevel10k which is a very advanced prompt, but I can reproduce it with Terminal.app and plain Bash prompt.

What font are you using? Can you please send me some environment variables used to set up the terminal?

```
$ env | grep TERM
TERM_PROGRAM_VERSION=453
TERM_SESSION_ID=B30482BE-7EFB-4A1F-B2F3-AF8317A12568
TERMINFO=/Users/daniel.serodio/.terminfo
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal

$ locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by reagle** [comment]
Coincidentally, I'm using powerlevel10k as well.

```zsh
❯ env | grep TERM
...
LC_TERMINAL_VERSION=3.5.4
ITERM_PROFILE=Default
TERM_FEATURES=T3LrMSc7UUw9Ts3BFGsSyHNoSxF
TERM_PROGRAM_VERSION=3.5.4
TERM_PROGRAM=iTerm.app
LC_TERMINAL=iTerm2
COLORTERM=truecolor
TERM=xterm-256color
TERMINFO_DIRS=/Applications/iTerm.app/Contents/Resources/terminfo:/usr/share/terminfo
❯ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by dserodio** [comment]
Thanks! Comparing your env. vars with mine, I thought `TERMINFO` might be the culprit. I removed my `~/.terminfo` file and the glitches are now gone. 🙌🏼
