### ISSUE TITLE
External custom loaders

### ISSUE THREAD

**Issue by azjps** [saulpw/visidata#249]
Hi, is it possible to use a [loader](http://visidata.org/docs/loaders/) which is defined externally, to load a custom/proprietary data format? It'd be sufficient for example to read an import path like `my_foo_library.open_{foo}` from a command-line argument or environment variable.

**Comment by saulpw** [comment]
Hi @azjps, yes it certainly is!  You would follow the recipe at [visidata.org/docs/loaders](http://visidata.org/docs/loaders/), putting the code into `~/.visidata/vdfoo.py`, and then in your `.visidatarc` file you would put `from vdfoo import open_foo`.  Then you can open `.foo` files just like anything.  Let me know if you have any issues getting this to work for your format.

**Comment by azjps** [comment]
Thanks for the fast response, I confirmed that this works :) Is it possible to customize the location of this file? It would be nice I could distribute this to other users without them having to make similar changes to their `~/.visidata` and `~/.visidatarc`.

**Comment by saulpw** [comment]
Unfortunately, that's not possible at present.  Are you thinking you would drop the vdfoo.py file into a folder and then visidata would autoload it on startup?  What if that folder were something like  `~/.visidata/autoload`?

**Comment by azjps** [comment]
For a bit more context, we have a virtualenv which is shared by many users. The most ideal situation would be if its possible to install "extensions" directly to the virtualenv. For an example of an analogous situation: `jupyter labextension install` will install apps by default into `{sys.prefix}/share/jupyter/lab`. That way all users using this virtualenv would all be able to use this custom loader without having to do anything in addition, it "just works".

However I understand if that is a bit complicated to implement, so I was thinking another option would be to allow an environment variable, command-line option, or similar to specify a shared directory, which would be used in the same way as `~/.visidata`.

I suppose I could also wrap visidata in a shell script which automatically creates and manages `~/.visidata`.

**Comment by saulpw** [comment]
Interesting, thanks for sharing your use case.  There is an option `visidata_dir` which can only be set from the command-line (`--visidata-dir`) that sets the dir to use instead of `~/.visidata`.  In conjunction with `--config` which sets the `.visidatarc` file to use, it seems like you could make a small wrapper around `vd` which does what you want.  The only downside is that it would not allow individual users to customize their own `.visidatarc` or have their own `.visidata` folder for plugins.

**Comment by azjps** [comment]
Yes, that would be perfect. On v1.5.2 though I don't seem to see a `--config` option:
```bash
$ vd -v
saul.pw/VisiData v1.5.2
$ vd my_data.foo --config ~/.visidatarc
vd: error: unrecognized arguments: --config ~/.visidatarc
```

**Comment by saulpw** [comment]
Ah, sorry, that is in `develop`, not released yet.  Will be in the next version.
