### ISSUE TITLE
Add friendly view of PyTables structured HDF5 files

### ISSUE THREAD

**Issue by jeffmelville** [saulpw/visidata#2492]
pandas uses PyTables for HDF5 outputs.  This creates a lot of extra structure (which I don't totally understand) that makes it hard to view idomatically in visidata.

"Unpacking" the PyTables schema would make this tool incredibly useful for peeking at HDF5 files created by pandas.

**Comment by saulpw** [comment]
Hi @jeffmelville, thanks for the request.  I'm not very familiar with PyTables or what it would mean to unpack its schema.  Can you provide a bit more context?  An example .hdf5 with some description of specifically what you'd like to see would be very helpful.

Kondo'ed for now.
