### ISSUE TITLE
How would you unhide a single column in visidata? 

### ISSUE THREAD

**Issue by ivan-gerov** [saulpw/visidata#2497]
How would you unhide a single column in visidata? My workflow sometimes involves looking at the columns in a file (Shift-C mode), find a column using regex, select all other columns and hide them. After looking at the data of that column, I might think that I need to unhide one of the columns that I just hid. Unfortunately, there doesn't seem to be an option to unhide only a single column in the Shift - C mode. There doesn't seem to be a way to unhide even selected columns. I tried using `gv` but that just unhid all columns in the current view, which are not the columns of the file (that are currently arranged in rows (Shift-C mode).

How might one go about doing what I want above? Is it that I am misunderstanding the way of use and there is a better way of doing this?

**Comment by anjakefala** [comment]
In `Shift+C`, edit the value in the `width` column to be more than 0. =)

**Comment by saulpw** [comment]
Also, on develop, the hidden columns are still "visible" to the right, and can be unhidden by moving to the hidden column and pressing `_`.
