### ISSUE TITLE
Show key columns on ColumnSheet

### ISSUE THREAD

**Issue by vbrown608** [saulpw/visidata#25]
If a user makes a column into a key column and then goes to the ColumnSheet, there should be an indicator on that sheet that shows which columns are key columns.

Key columns are colorized on the main sheet. One approach could be to colorize the rows that represent key columns on the ColumnSheet.

It is not currently possible to colorize rows, so this issue depends on #24.

**Comment by saulpw** [comment]
Fixed as of 9147e2cd6c84184a819a13a66bd3437f548a9b1a
