### ISSUE TITLE
Include memory sheet variables in autocomplete?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2509]
With #2431  issue resolved (in dev at least) I'm using memory sheet more and would like to be able to have its values available in autocomplete (e.g., with `=` command). I do think it makes sense to limit autocomplete to the current sheet, but perhaps an exception could be made for the memory sheet? Or, perhaps there could be a prefix or shortcut when editing an expression to reference the memory sheet namespace and help with autocomplete?

**Comment by saulpw** [comment]
VisiData has a concept of "contexts" which are available to `eval()` expressions.  I added these contexts to the list of autocomplete keys.

There are also a lot of keys in "globals" which are available, though most of them are useless in an eval'ed expr.  (Try Tab to autocomplete with no identifier started.)  We should clean those up at some point.
