### ISSUE TITLE
Viewing PDFs: External package "pdfminer.high_level" not installed; run: pip install pdfminer.six

### ISSUE THREAD

**Issue by CharlesARoy** [saulpw/visidata#2510]
Hello,

I'm trying to view PDFs with Visidata but I keep getting the following error when I try to open files:
```
External package "pdfminer.high_level" not installed; run: pip install pdfminer.six
```

I have Visidata installed with brew so I ran the following command to install pdfminer.six in the visidata environment as @anjakefala explained in #2508.
```
pip3 install --target /opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/ pdfminer.six
```

When that didn't work, I ran the following commands for good measure, none of which have helped:
```
pip3 install --target /opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/ pdfminer
pip install --target /opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/ pdfminer.six
pip install pdfminer.six
pip install pdfminer
```

According to [this page](https://stackoverflow.com/questions/64948893/pdfminer-high-level-not-showing-up), to fix the pdfminer.high_level issue, you need to install pdfminer.six and import pdfminer.high_level after you import pdfminer. Not sure if that applies here.

Any input is appreciated!

**Comment by saulpw** [comment]
@CharlesARoy Based on what you said from that page, try adding this to your visidatarc:

```
import pdfminer
import pdfminer.high_level
```

**Comment by CharlesARoy** [comment]
Wow, thanks for the quick response!

Ok, adding that to my .visidatarc file resulted in the following error:
`ModuleNotFoundError: No module named 'pdfminer.high_level'`

**Comment by CharlesARoy** [comment]
These are the files listed in `/opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/pdfminer`. Does that error mean that a file named high_level.py is missing?

![image](https://github.com/user-attachments/assets/cf546c54-3361-47e8-b29f-5eda9f1fb863)

**Comment by saulpw** [comment]
It seems like this may be the wrong version of pdfminer then.  You may have to do some Python spelunking on this one.

**Comment by anjakefala** [comment]
Closed as inactive! If you still need help debugging this, please write a comment or open a new issue.
