### ISSUE TITLE
Deprecation and vulnerability in upstream library (olm)

### ISSUE THREAD

**Issue by dbaynard** [saulpw/visidata#2515]
This should be resolved with [Core requirement libolm is officially deprecated in favor of vodozemac · Issue #518 · matrix-nio/matrix-nio](https://github.com/matrix-nio/matrix-nio/issues/518) but meanwhile it may be worth making the (zulip) dependency optional, in some way? I was able to run visidata without the zulip dependency.

Context: Olm has been deprecated [Security Issues in Matrix’s Olm Library - Dhole Moments](https://soatok.blog/2024/08/14/security-issues-in-matrixs-olm-library/#user-recommendations).

**Comment by saulpw** [comment]
Hi @dbaynard, thanks for drawing our attention to this.  The zulip dependency is already optional (as are all dependencies for VisiData), and only used if the Zulip loader is invoked.  Unless there's an actual security issue, I think it's fine as it is.

**Comment by dbaynard** [comment]
Ah it's my distribution that requires it; I'll raise an issue there. Thanks for addressing this.
