### ISSUE TITLE
Mailbox support not working?

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2521]
**Small description**

I can't read Thunderbird mbox or maildir in visidata (latest dev).

**Detailed description**

The python library seems to be working:

```
❯ ipy
Python 3.12.5 (main, Aug 16 2024, 15:20:20) [Clang 14.0.3 (clang-1403.0.22.14.1)]
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mailbox

In [2]: mbox = mailbox.mbox('/Users/reagle/data/tbird-reagle/Mail/Local/A-Bulk')

In [3]: print([message['subject'] for message in list(mbox)[:3]])
['Congratulations to promoted 24-25 faculty', '=?utf-8?Q?Teaching=20Statements=2C=20AI=20Assignment=20Design=2C=20and=20More=21?=', '[Wiki Education] Join us tomorrow for Instructor Office Hours!']

...

In [2]: maildir = mailbox.Maildir('/Users/reagle/data/tbird-reagle/Mail/Local-maildir/A-Bulk')

In [3]: print([message['subject'] for message in list(maildir)[:3]])
['=?utf-8?Q?Students=20prepare=20for=20satellite=20launch?=', 'Sad news about ...', 'Security alert for joseph.reagle@gmail.com']
```

Yet visidata is not reading them using mailbox.

```
❯ pipx inject visidata mailbox
⣟ installing mailbox  injected package mailbox into venv visidata
done! ✨ 🌟 ✨
❯ vd -f mailbox Local-maildir/A-Bulk
saul.pw/VisiData v3.1dev
Support VisiData: https://github.com/sponsors/saulpw
guessed "dir" filetype based on contents
❯ vd -f mailbox Local/A-Bulk
saul.pw/VisiData v3.1dev
Support VisiData: https://github.com/sponsors/saulpw
unknown "mailbox" filetype
opening Local/A-Bulk as txt
```

**Comment by midichef** [comment]
It looks like the filetype visidata is looking for is officially `mbox`, not `mailbox`, though visidata's [Supported Formats table](https://www.visidata.org/docs/formats/) currently says "mailbox". So for now the command should be `vd -f mbox`.

It'll be a simple fix to make `-f mailbox` work too.

**Comment by reagle** [comment]
Thanks for this!

I've used vd to read mbox in the past, but yesterday I was using vd to look at Thunderbirdr mbox and maildir --- as I transition from the former to the latter. In the past, I didn't even have to give a format, but that wasn't working so I consulted the "Supported Formats" table and used `mailbox`, so #2522 will help there.

However, I just tried `-mbox` with maildir (since deleted mailbox) and I get:

```
❯ vd -f mbox ~/data/tbird-reagle/Mail/Local-maildir/A-Bulk
saul.pw/VisiData v3.1dev
Support VisiData: https://github.com/sponsors/saulpw
opening /Users/reagle/data/tbird-reagle/Mail/Local-maildir/A-Bulk as mbox
```
but with vd the status says:

```
opening /Users/reagle/data/tbird-reagle/Mail/Local-maildir/A-Bulk/cur as mbox IsADirectoryError: [Errno 21] Is a directory: ' /Users/reagle/data/tbird-reagle/Mail/Local-maildir/A-Bulk/cur'
```

I've read that Thunderbird maildir's aren't to standard, but if the mailbox library can read them, I'm not sure why vd can't...?

**Comment by midichef** [comment]
Try `vd -f maildir` for that. Does it work?

For mailbox, there are four undocumented filetypes:  `maildir`, `mmdf`, `babyl`, and `mh`.

Here's how I found them. If any function in a loader starts with `open_`, you can use `-f` with whatever follows `open_`. And `loaders/mailbox.py` has an `open_maildir()` function:
https://github.com/saulpw/visidata/blob/b0092d5dfb475dbb6d1d55fa842d9ba61e834bbe/visidata/loaders/mailbox.py#L10

We should document these somewhere. But the column in `docs/formats.md` does not quite have room to fit `maildir,mmdf,babyl,mh` next to `mailbox`.

**Comment by reagle** [comment]
Yes, `-f maildir` worked! 

New rows could easily be added to `docs/formats.md`, especially if `-f mailbox` isn't supposed to detect the variants automatically. (Is this a docs issues or a code issue?)

My other favorite tool, pandoc, also supports many input and output formats. When I get in a pickle there, I can use `--list-input-formats` and `--list-output-formats`. If the intention is to move more of the vd info into the code, and generate docs from that, perhaps that would be an option?

**Comment by anjakefala** [comment]
That's a cute suggestion! Would you please open an issue so we can consider it?

**Comment by reagle** [comment]
Can we still get an update to the HTML formats table?
