### ISSUE TITLE
Precision adjustments on date columns

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2523]
I'm new to the `alt`,`-`/`+` command for the precision of shown/formatted data.
Unfortunately, when I derive a column from `created_utc`, which is a string of epoch seconds, `+/-` does weird things...

1. `=date(created_utc)` seems to work but `alt+-` turns it back into seconds with ".00" precision. I can't find much documentation on this built-in `date` function, is there a list of them?
2. If I use `=dt.datetime.fromtimestamp(float(created_utc))` the type for the new column is blank in the column sheet. If I `alt+-` I get "TypeError: float() argument must be a string or a real number, not 'datetime.datetime'". If I convert it to date type within vd via `@` I get  a column of ".1f"s. (It does work if immediately upon creation I remember to set the new column type to `@`.)

https://asciinema.org/a/xoUKGRryAEotb1BeoklpR6gBM

```csv
created_utc,title
1295471619,[SSPSF] says thanks!
1295471580,Introducing: Bad Influence Puppy
1295470777,[TLTNP] couldn't care less
1295470700,[AGOC] red light district
1295469892,[PPP] Relax!
1295469265,hypochondriac hello kitty cupcake
1295468961,[HHKC] saw a movie
1295468543,There's one in every town.
1295468031,[IT] hate it when i do this
1295467821,[DHPF] just got his report card
1295467664,[UAA] whatcha doin' there?
1295465577,[TLTNP] says fuck it
1295465440,unsolicited advice algae
1295465204,analysis at a glance omnipresent cloud
1295460404,Procreation has its benefits
1295453664,[HHKC] pins and needles
1295452894,[TLTNP] is bored
1295452829,shameless self promotion stick figure
1295452795,i guess i'm shameless self promotion stick figure
1295452615,oh wait... you're here already...
1295445352,[KHPDG] watch it buddy!
1295445158,kidding herself pole dancer giraffe
1295438674,[HHKC] should quit smoking
1295438031,hypochondriac hello kitty cupcake
1295415002,bruised thumb... credit to thehalfwit for the pic
1295414667,barely legible blimp
1295413341,peer pressure pachyderm
1295411794,shady drug dealer red panda
1295410970,[TLTNP] is hungry
```

**Comment by saulpw** [comment]
Yes, the column type has to be set for this to work properly; if it's unset, it sets it to float because it's trying to be helpful and doesn't know any better.  We could warn or fail in that case instead, however; maybe that's more useful?

I'm not seeing the other error you mentioned.

**Comment by reagle** [comment]
@saulpw, thanks for the response! I think both of these stem from me not understanding what is happening with types. 

BTW: Is there documentation of natively available commands such as `date`?

1. After creating the `=date(created_utc)` from an anytype, and then going back and setting `created_utc` to integer, I see '@' in the cells of the new column, but not the column header. I assumed I could then use precision commands, but this reveals I don't understand how the type guessing/inference happens. Are types in the cell values only guesses, and not amendable to precision commands? Instead of setting (fake) cell types, why not set the column type?

2. Here is a command log that prompts the issue. Again, I'm going down a weird path because I didn't set the column type correctly but getting a `2f` in the end is odd.

```
#!vd -p
{"sheet": "global", "col": null, "row": "disp_date_fmt", "longname": "set-option", "input": "%Y-%m-%d %H:%M:%S", "keystrokes": "", "comment": null}
{"longname": "open-file", "input": "test.csv", "keystrokes": "o"}
{"sheet": "test", "col": "created_utc", "row": "", "longname": "addcol-expr", "input": "dt.datetime.fromtimestamp(float(created_utc))", "keystrokes": "=", "comment": "create new column from Python expression, with column names as variables"}
{"sheet": "test", "col": "dt.datetime.fromtimestamp(float(created_utc))", "row": "", "longname": "setcol-precision-less", "input": "", "keystrokes": "Alt+-", "comment": "show less precision in current column"}
{"sheet": "test", "col": "dt.datetime.fromtimestamp(float(created_utc))", "row": "", "longname": "type-date", "input": "", "keystrokes": "@", "comment": "set type of current column to date"}
```

**Comment by saulpw** [comment]
1. The cell types aren't guessed, they are the actual types of the underlying object.   (The default "anytype" is a simple pass-through identity function.)  The precision commands look at the column type to determine the format string to apply.
2. Since anytype columns don't use a format string, I decided to make it fail instead, so that the issue is at least clear.

**Comment by reagle** [comment]
Confirmed that I get an exception now, though the error is "ValueError: year 1295471619 is out of range."  Is that the problem or that it is a anytype and needs to be an integer or float?
