### ISSUE TITLE
[guides] Unable to view guides

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2538]
**Small description**

Unable to view guides

**Data to reproduce**
None.
**Steps to reproduce**
Run the `open-guide-index` command.  Hit Enter to dive into a guide.  No rows/guides are highlighted white.

**Expected result**

Be able to view the new guides.

**Actual result with screenshot**

 https://asciinema.org/a/knK5PY7vq5rs6Sgp4QRhjMrbU

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?
- develop

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)? Linux

- Which version of Python? python 3.12 and others.

Does it need to download the guides?

@anjakefala, I mentioned this  in  https://github.com/saulpw/visidata/commit/63984ddba4db1ac628752e6318cb4a859e54739b

**Comment by thejud** [comment]
FWIW, I see this issue when I install locally via:

`pip install .`

but not when I do the develop mode install:

`pip install -e .`

**Comment by frosencrantz** [comment]
Yes that may be the problem.  I use `pip install .` to install an independent installation.  There may be a bug in the installation process.

**Comment by anjakefala** [comment]
> Yes that may be the problem. I use pip install . to install an independent installation. There may be a bug in the installation process.

I'll investigate! Good clue.

**Comment by anjakefala** [comment]
Hey @frosencrantz Can you try out my latest commit, and see if it fixes the problem? Things work for me, but it's tricky to tell with my environment.

**Comment by frosencrantz** [comment]
@anjakefala that did not work.  :(

**Comment by anjakefala** [comment]
@frosencrantz Could you try again?

**Comment by reagle** [comment]
I suspect this is unrelated, but I've never been able to have guides survive an update using pip (or pipx). 

```zsh
git -C ~/bin/src/visidata pull
pip install --upgrade ~/bin/src/visidata
```

I have to `pip uninstall visidata` first, then install `pip install -e ~/bin/src/visidata`

**Comment by frosencrantz** [comment]
That did not work.   I tried using a new installation to see if that would work and it did not help.

**Comment by anjakefala** [comment]
I finally have a reproduction folks. I'm not sure why this is happening, but I'm on it!

**Comment by anjakefala** [comment]
Okay, we have the bug! This fixed things for me. The package_data was incorrectly configured.

```
commit 545886ada7252f8fa2feae2fb8366ead273bfcbd (HEAD -> develop, origin/develop)
Author: anjakefala <anja.kefala@gmail.com>
Date:   Tue Oct 8 21:42:00 2024 -0700

    [guides-] fix package data installation directory for guides

diff --git a/setup.py b/setup.py
index 564c6a3c..5e5ad1f8 100755
--- a/setup.py
+++ b/setup.py
@@ -77,7 +77,7 @@ setup(
     package_data={
         "visidata.man": ["vd.1", "vd.txt"],
         "visidata.ddw": ["input.ddw", "regex.ddw"],
-        "visidata.guides": ["visidata/guides/*.md"],
+        "visidata": ["guides/*.md"],
         "visidata.tests": ["sample.tsv", "benchmark.csv"],
         "visidata.desktop": ["visidata.desktop"],
         "visidata.experimenta.noahs_tapestry": [
anja@kefala:git/visidata ‹develop*›$ 
```

Can you confirm @frosencrantz?

**Comment by frosencrantz** [comment]
Fixed. Thanks, @anjakefala!
