### ISSUE TITLE
[roadmap] "snap" Linux installer

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#254]
Hi,
today I have discovered [Snaps](https://snapcraft.io/) "a single secure package and auto-update system for Ubuntu, Debian, Arch, Centos, Amazon Linux".

What benefits do snaps bring to Python apps?

- Snaps are easy to discover and install. Millions of users can browse and install snaps graphically in the Snap Store or from the command-line.
- Snaps install and run the same across Linux. They bundle the exact version of Python required and all of your app’s dependencies, be they Python modules or system libraries.
- Snaps automatically update to the latest version. Four times a day, users’ systems will check for new versions and upgrade in the background.
- Upgrades are not disruptive. Because upgrades are not in-place, users can keep your app open as it’s upgraded in the background.
- Upgrades are safe. If your app fails to upgrade, users automatically roll back to the previous revision.

This is the help for Python https://docs.snapcraft.io/python-apps/6741

I think that I'm not able to create it, but it could be a great way to spread the use of Visidata.

Best regards

**Comment by anjakefala** [comment]
Thanks for the suggestion! 😊 

I will take a look sometime soon and review pros and cons of maintaining a VisiData snap.

In the meanwhile, if there are existing folks who would love a VisiData snap, please let me know in this issue!

**Comment by Peppolhound** [comment]
I would be interested into as well!

**Comment by saulpw** [comment]
This is on the roadmap, so I'm going to close this issue and link to it from there.  Thanks for the suggestion!
