### ISSUE TITLE
`TypeError: list object not callable` for quantile aggregators

### ISSUE THREAD

**Issue by gennaro-tedesco** [saulpw/visidata#2541]
**Small description**

Percentile aggregators except with `TypeError: list object not callable`

**Data to reproduce**

Let us consider the following csv file `example.csv`
```
counts
1
2
3
4
5
```

**Steps to reproduce**

https://github.com/user-attachments/assets/2723ac8d-9b38-491f-8618-5b1a1943d629

**Expected result**

Numerical percentiles should be shown

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?

Yes

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?

I could not check

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?

MacOs

- Which version of Python?

Python 3.12.6 (but also any other 3+ version)

I presume I must be doing something wrong myself since the median (50% percentile) works well and I have not found any other issue on the matter (this should be a pretty common functionality hence I expect most people to use it) except [this one](https://github.com/saulpw/visidata/issues/1312) (which is a little different though).

**Comment by saulpw** [comment]
I'm sorry, @gennaro-tedesco, I can't view the video anymore.   Could you include a .vdj or .vdx file?  It seems to work fine for me.

Edit: Please press Ctrl+V to see the version of VisiData and report it here.  I think this might be fixed already in the current version.

**Comment by gennaro-tedesco** [comment]
The version I am using is 3.0.2 installed via brew on MacOs.

The video essentially shows that I first convert the column to integers (pressing `#`) and then operate with `z+` to output the quantiles. All other numerical aggregators work as expected.

I have reproduced the issue also considering a file with 1 row and 1 value only and it still occurs on quantiles (that is why I suspect it's in the underlying function code perhaps).

**Comment by saulpw** [comment]
Thanks, @gennaro-tedesco.  This is fixed in the develop branch already.  We'll be releasing 3.1 soon.

**Comment by gennaro-tedesco** [comment]
Awesome, thank you for looking into it, looking forward to the 3.1!
