### ISSUE TITLE
[vds] save error values as null

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2542]
I've created a `=date(epoch_seconds)` column and if there are null cells in `epoch_seconds` the derived values are errors rather than null.

Because of the cell errors, I cannot save the sheet as vds: "Exception: invalid type for date TypedWrapper".

Even if I freeze the derived column, I still cannot edit the cells with errors and try to set them to 0 or None: `gz=None` fails "TypeError: 'int' object is not iterable"

**Comment by saulpw** [comment]
`gz=` is a bit non-standard, it takes an iterator or list and assigns successive values to selected cells.  Using `g=None` on a frozen column should work.

You should definitely be able to save .vds with errors, though.  In derived columns they shouldn't even be used when you load the sheet.

**Comment by reagle** [comment]
Here's a recording of a toy example.

https://asciinema.org/a/S8ATYuaYn97q8WePGfkLVwx6J

1. I load in a jsonl file with null values.
2. I create a new column `date(curcol)` and set the column type to date, resulting in error cell values corresponding to the null values (it'd be nice if they could be null as well).
3. I save it as a vds, exit, and open the vds and my `date(curcol)` column is full of error cells.
4. I exit, re-open jsonl file to try to set the derived error cells to `None`, which fails because that's an invalid date type.

**Comment by saulpw** [comment]
Okay, this should fix the main issue.  You'll still have to freeze a column to set things to null if you want (and remember `gzd` is basically the same as `g=None`).

**Comment by reagle** [comment]
Thank you Saul. FYI: After creating the new column, I can save but upon opening that vds file _all_ cells in the new column have become `!`. The attached shows the derived column (and frozen column with `!` set to null) upon reopening.

<img width="524" alt="SCR-20241004-hxcb" src="https://github.com/user-attachments/assets/cdc5b0ce-4d76-4454-9567-ebc9454fdbea">
