### ISSUE TITLE
Inform user sidebar is toggled with `Ctrl+G` somewhere in UI

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#2546]

**Comment by saulpw** [comment]
On the bottom right of the statusline, a little `[1]` shows how many help sheets are available to cycle through; is that what you mean?

**Comment by anjakefala** [comment]
@saulpw Oh no!

What I mean is, there is currently no way for a user to know that `Ctrl+G` is the keystroke that opens up the sidebar help sheets. Especially a beginner user. We don't have it documented in the manpage (yet), and it's nowhere in the UI. It feels as important as `Alt+H for menu`.

**Comment by anjakefala** [comment]
Thank you! This looks great.
