### ISSUE TITLE
[python] New Python version 3.13 released

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2550]
New Python version 3.13 released.  And 3.8 will be EOL soon.

See https://devguide.python.org/versions/

With an upcoming VisiData release, it might be useful to run tests on the new release.

**Comment by anjakefala** [comment]
Hey @frosencrantz!

I opened: https://github.com/saulpw/visidata/pull/2555 We're currently blocked on merging until `pyarrow` publishes a 3.13 wheel. I tested locally, and everything else seems to run fine! =)

Thank you for bringing this to my attention before we shipped. ^^
