### ISSUE TITLE
Add color to current cursor cell for easier tracking

### ISSUE THREAD

**Issue by reagle** [saulpw/visidata#2553]
I added the following as soon as it was helpfully suggested to me. I recently had cause to use visidata without my .visidatarc and was surprised the the current cell is still hard to track. Suggestion: add better row, column, and cell highlighting out of the box.

```
# Xterm Color Numbers https://www.ditig.com/256-colors-cheat-sheet
TableSheet.colorizers += [
    CellColorizer(
        3,
        "bold 226 on 143",
        lambda s, c, r, v: c is s.cursorCol and r is s.cursorRow,
    )
]
```

**Comment by saulpw** [comment]
We have `options.color_current_cell` (in v3.0 even) which is currently unset by default.  So your .visidatarc can be reduced to `options.color_current_cell = "bold 226 on 143"`.  Are you also suggesting this particular color should be set in the default theme?

**Comment by reagle** [comment]
Thanks, didn't know about that option! And, yes, I think it would help people to have the current cell be more visible.
