### ISSUE TITLE
[3.1]  Several bugs in Multline and one in input 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2556]
**Small description**
There are currently three bugs I know about:
- Typing Ctrl-V in input mode will cause a stack trace, and exit input mode.
- Multiline issues:
   - enabling the `disp_multiline_focus` option  causes VisiData not to use the line just above the status line.
   - the `disp_rowbot_sep` is not being used/shown when in multiline mode.  (Need to set a unique value, and then use multiline mode.

I do not have time to write these up more, but I they should be easy to reproduce.  If you need more information let me know.

**Comment by saulpw** [comment]
Thanks for noting these, @frosencrantz.  They should be fixed now.

**Comment by frosencrantz** [comment]
Thank you, @saulpw!  Those all work now.  Also, happy to see that `disp_multiline_focus` is now default as true. 👍
