### ISSUE TITLE
[xlsx] Not able to read data from file that is not local and no errors are reported

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2557]
**Small description**
Not able to read xlsx file from a location that is not a direct filename.  No web or zip file contents are read.

**Data to reproduce**
Example:
```
vd  https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1179998/LSBS_Year_8__2022__Businesses_with_no_employees_Data.xlsx
```
**Steps to reproduce**

See example data.  Trying to load from URL returns no data, and does not report an error.

**Configuration**
VisiData 3.1dev latest develop. Python 3.12.6

**Additional context**

It looks like https://xlrd.readthedocs.io/en/latest/api.html#xlrd.open_workbook accepts a file_content arg, which might make it possible to pass in data loaded from zip or web.

This might be an issue with other filetypes, too.  Also, this might have been broken for some time.

https://github.com/saulpw/visidata/blob/90f7eeefe48c93f030fa1af7b6cfbbaf90f53653/visidata/loaders/xlsx.py#L37

**Comment by saulpw** [comment]
It's a nice feature when it's convenient, but I don't think it's worth it to handle remote files in all cases.   Some formats need a random-access file on disk, like sqlite for example.  I agree there should be an error message instead of a silent failure.

**Comment by frosencrantz** [comment]
Thank you, @saulpw. 

I would have liked VisiData to be able to handle zip or url data, but having an error message is preferable to no error.  The guide for zip files does tell the user to use `x` to extract the file, and then hit ENTER.  I did not realize this was required.  I do find I am learning from the guides.  😃
