### ISSUE TITLE
Man page options are mislabeled

### ISSUE THREAD

**Issue by greenskeleton** [saulpw/visidata#256]
https://github.com/saulpw/visidata/blob/32771e0cea6c24fc7902683d14558391395c591f/visidata/man/vd.1#L745-L748

http://visidata.org/man/

I noticed the options  `--tsv-safe-newline` and `--tsv-safe-tab` appear to have the descriptions reversed.

**Comment by anjakefala** [comment]
Nice catch, @greenskeleton! Thanks for pointing this out.

I just pushed a fix. It will show up in /man the next time we re-deploy the website and in visidata's man page on our next release.

***
_Some background on the fix_

Our [builder](https://github.com/saulpw/visidata/blob/develop/dev/mkman.sh#L20) constructs the cli options in our man page by [parsing](https://github.com/saulpw/visidata/blob/develop/visidata/man/parse_options.py#L53) our `options()` and their docstrings. Option descriptions in our man page are modified by editing the option's docstring in the code. =)
