### ISSUE TITLE
Update to 3.1: circular import error

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#2562]
**Small description**

I have installed it both via pip and pipx, and I have "ImportError: cannot import name 'GuideSheet' from partially initialized module 'visidata'" error

**Steps to reproduce**

I have installed vd in two ways:

- pip3 install visidata
- pipx install visidata

Then I run `vd` and I have

```
Traceback (most recent call last):
  File "/home/aborruso/.local/bin/vd", line 3, in <module>
    import visidata.main
  File "/home/aborruso/.local/pipx/venvs/visidata/lib/python3.11/site-packages/visidata/__init__.py", line 157, in <module>
    importFeatures()
  File "/home/aborruso/.local/pipx/venvs/visidata/lib/python3.11/site-packages/visidata/__init__.py", line 139, in importFeatures
    vd.importSubmodules('visidata.features')
  File "/home/aborruso/.local/pipx/venvs/visidata/lib/python3.11/site-packages/visidata/settings.py", line 508, in importSubmodules
    vd.importModule(pkgname + '.' + module.name)
  File "/home/aborruso/.local/pipx/venvs/visidata/lib/python3.11/site-packages/visidata/settings.py", line 491, in importModule
    r = importlib.import_module(pkgname)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborruso/.local/pipx/venvs/visidata/lib/python3.11/site-packages/visidata/features/errors_guide.py", line 1, in <module>
    from visidata import GuideSheet, vd
ImportError: cannot import name 'GuideSheet' from partially initialized module 'visidata' (most likely due to a circular import) (/home/aborruso/.local/pipx/venvs/visidata/lib/python3.11/site-packages/visidata/__init__.py)
```

**Expected result**

**Actual result with screenshot**

[If there is an error message, please include the full stack trace shown with `Ctrl+E`.]

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)?

Yes

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)?

yes

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?

Debian 12

- Which version of Python?

Python 3.11.2

**Comment by RyannDaGreat** [comment]
Same here!

**Comment by midichef** [comment]
@anjakefala @saulpw 
I'm not familiar with how the packaging process works. But it looks like the some files made it into the pip release that were deleted by past commits of visidata? I see `features/errors_guide.py`, which is causing this startup error. But also: `guides/SortGuide.md`, `loaders/api_bitio.py`, `stored_prop.py`.

The commits that removed these files are:
`features/errors_guide.py` - b8a8b5b1c8f84d01a86473d09583d9dcf1a2fa04
`guides/SortGuide.md` - none, I can't find any commit that created it or removed it.
`loaders/api_bitio.py` - 8ec40607651204610aea01940accaa1490ea1b55
`stored_prop.py` - 7ef08d93dfb76aeb1da4d9ecd072e6296c14ba3d

**Comment by anjakefala** [comment]
Wild! Thanks for letting us know folks. I'll try to understand what is happening and get it fixed ASAP.

**Comment by fleimgruber** [comment]
I can confirm that installation from git at e.g. https://github.com/saulpw/visidata/commit/8a4179422d45702b34baa0cb05f681e74e00daa5 (v3.1 bump) does not show this error.

**Comment by anjakefala** [comment]
Hey folks, sorry about this. There was something wrong with my local environment. There was a `build/lib` directory with old files that setup.py was pulling files from for some reason. I added a step to remove that directory in the future and pushed a v3.1.1 that should be working.

I'm sorry for the confusion. Please upgrade to v3.1.1. Could someone confirm everything's fine for them with v3.1.1?

**Comment by midichef** [comment]
I can confirm v3.1.1 starts up fine.

**Comment by anjakefala** [comment]
Thanks @midichef! Thanks for letting us know everyone. We hope you enjoy the new release. =)

**Comment by aborruso** [comment]
> . I added a step to remove that directory in the future and pushed a v3.1.1 that should be working.

How to install it?

**Comment by aborruso** [comment]
@anjakefala the 3.1.1 is the develop version?

```
pip3 install git+https://github.com/saulpw/visidata.git@develop
```

Thank you

**Comment by midichef** [comment]
@aborruso
v3.1.1 should be installable as a normal pip package. You don't need the develop branch, just `pip install --upgrade visidata`

And yes, thanks for the quick fix @anjakefala!

**Comment by aborruso** [comment]
> v3.1.1 should be installable as a normal pip package. You don't need the develop branch, just `pip install --upgrade visidata`

I didn't see it in the [releases](https://github.com/saulpw/visidata/releases) and didn't think it could be installed with pip. 

Thank you very much @midichef and @anjakefala

**Comment by aborruso** [comment]
> I didn't see it in the [releases](https://github.com/saulpw/visidata/releases) and didn't think it could be installed with pip.

It's in the tags https://github.com/saulpw/visidata/tags
