### ISSUE TITLE
Feature request: Option to customize refline color

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2566]

**Comment by midichef** [comment]
Thanks for catching this, I had a typo in the name of the refline color option.

For now, if you are using v3.1.1 and don't want to run the develop branch, you can still set the color with:
`options.color_refline = 'green'`

But in future releases, the name that is used will be `color_graph_refline`:
`options.color_graph_refline = 'green'`

**Comment by cool-RR** [comment]
Great, thank you. 

In case it's helpful for anyone, here's my color setup for reflines:

```
options.disp_graph_reflines_y_charset = '─' * 4
options.disp_graph_reflines_x_charset = '│' * 4
options.color_graph_refline = '238 blue'
options._set('color_refline', options.color_graph_refline, 'global', module='unknown')
```

I have it use only one character for each because the different widths of the different characters seem confusing to me.

Here's the beautiful result:

![image](https://github.com/user-attachments/assets/33ef2e1e-4c61-4164-8cde-c10791a9be44)

**Comment by anjakefala** [comment]
@cool-RR I just merged https://github.com/saulpw/visidata/pull/2569 ! Could you install from `develop` and let me know if that meets your needs?

This will be part of our next patch release.

**Comment by cool-RR** [comment]
Confirmed works, thank you.
