### ISSUE TITLE
[question] how to disable guides/tips panel

### ISSUE THREAD

**Issue by kguidonimartins** [saulpw/visidata#2567]
Hello everyone, thank you very much for this tool!

Today I updated the visidata and saw the new implementation of the guides/tips panel. So useful, but is there a way to disable it? The guides show up on every new file I open.

TIA

**Comment by saulpw** [comment]
You can use `Ctrl+G` to cycle through panels to "off", or use `b` to toggle them on/off.  Both should persist for the session.

If you want them off at the start, you can set `options.disp_sidebar = False`.  If you want both sidebar and the chooser menu (the fancy interface stuff that can obscure the interface) permanently off, set `options.disp_expert = 5`.

**Comment by kguidonimartins** [comment]
Great!

**Comment by kguidonimartins** [comment]
Sorry for returning to this question, but the banner still on after read the file, despite my configs:

```python
options.disp_sidebar = False
options.disp_expert = 5
options.disp_menu = False
options.default_width = 500
options.default_height = 10
options.disp_lstatus_max = "500"
options.disp_status_fmt = " {sheet.name} | "
options.color_key_col = "cyan reverse"
options.color_default = "black"
```

Below is the banner which still appearing in the right bottom of the screen:

<img width="790" alt="image" src="https://github.com/user-attachments/assets/d64c8c00-69d8-457a-8fa1-3720d243adb4">

Is there a way to disable that too?

TIA

**Comment by saulpw** [comment]
The status messages in the sidebar can't be disabled.  But if you press any key (including e.g. `Ctrl+L` to refresh the screen), the sidebar status messages will disappear.

**Comment by kguidonimartins** [comment]
ah, ok. no problem! thanks again!
