### ISSUE TITLE
sort command does not work in PandasSheet

### ISSUE THREAD

**Issue by migueldvb** [saulpw/visidata#257]
Sorting rows with the keys `[ ` and `]` do not work in PandasSheet. The error message is:

` AttributeError: 'DataFrame' object has no attribute 'sort'`

**Comment by anjakefala** [comment]
Hi @migueldvb !

Thanks for the issue. I have reproduced it locally, and you are right it currently does not work. 

One thing I noticed is that the error stacktrace is dependent on which version of pandas is installed. Can you please confirm with me which version of pandas and visidata you are using? 

Also, can you also provide me with a sample code snippet over how you would perform the sort using pandas?

**Comment by migueldvb** [comment]
I have pandas 0.24.1 and visidata 1.5.2. This is the code I have used to sort on a single column: 
```
df.sort_values(by='col1')
```
and sort descending:
```
df.sort_values(by='col1', ascending=False)
```

**Comment by anjakefala** [comment]
Hi @migueldvb =)

I have pushed a preliminary implementation for sorting using the pandas loader: https://github.com/saulpw/visidata/commit/1c3d1c9df4563e0648352677e83353c9083ae733.

Please give it a go by installing from the `develop` branch, and let me know what you think!

This will shipped with the next release.

**Comment by migueldvb** [comment]
Thank you! This is working perfectly.
