### ISSUE TITLE
Space as leader/prefix key?

### ISSUE THREAD

**Issue by slinkeepie** [saulpw/visidata#2574]
Hey, eager to know if I can somehow set Space as the leader/prefix key? I use space in vim and it's great, couldn't figure out how to get it working here though (almost seems that the command search is an irremovable built-in, as I couldn't unbind Space/' ' ...).

Hopefully there's something I'm just not doing right?

David

**Comment by saulpw** [comment]
You can add your own prefixes like `vd.allPrefixes += ['Space']`, and then use them in your own command bindings.  Space should be unbindable the same as any keystroke, but you may have to unbind it on sheet it's bound on (BaseSheet). If that doesn't work then it's a bug.

**Comment by midichef** [comment]
I tested using `Space` as a command prefix, it works in visidata v3.1.1.

Here are examples of how to do it. Your custom commands would go in your `.visidatarc`:
```
# set the prefix
vd.unbindkey('Space')
vd.allPrefixes += ['Space']
vd.bindkey('1', 'exec-longname')  # you'll probably want an alternate key to run exec-longname

## example bindings
# two examples of how to bind keystroke to a new command
Sheet.addCommand('Space s', 'select-rows-10', 'select(rows[:10])', 'select the first 10 rows')
# replay=False to match the definition of go-down
Sheet.addCommand('Space j', 'go-down-10',     'cursorDown(10)',    'go down ten', replay=False)

# example of how to bind keystroke to a command that already exists
BaseSheet.bindkey('Space z', 'go-up')
```

**Comment by slinkeepie** [comment]
Thank you so much @midichef and @saulpw , I got it working with the above code but had to upgrade to that version (I was on 3.0.1 or something). Also the 'Space X' notation probably would have eluded me for a while either way as it seems quite idiomatic, so you've no doubt saved me lots of time!

I'm still a bit confused as to the scope differences of attaching (un)bindkey commands to BaseSheet/(Table)Sheet/vd, but I'll just stick with what works without (I did look up references but I sometimes get confused by multiple paths to the same solution until I make clear logical links).

p.s. I really appreciate the highlighted column and hidden column updates in 3.1.1 !

**Comment by midichef** [comment]
fyi, the `' '` space character in `'Space a'` is just a visual convenience. Binding to `'Space a'` is actually the same as binding to `'Spacea'`, because the space character is stripped from the keystroke given to `addCommand`/`bindkey`.

In fact my own first try at this binding was to bind to `' a'`, which did not work at all, because it was equivalent to `'a'`.

**Comment by ajkerrigan** [comment]
> fyi, the `' '` space character in `'Space a'` is just a visual convenience. Binding to `'Space a'` is actually the same as binding to `'Spacea'`, because the space character is stripped from the keystroke given to `addCommand`/`bindkey`.

> In fact my own first try at this binding was to bind to `' a'`, which did not work at all, because it was equivalent to `'a'`.

This was news to me, thanks! At some point I had to change key bindings in my visidatarc from e.g. `' j'` to `'Spacej'` and since then I've always read it as "space edge". Now I can add a visual convenience space and not mentally trip over those shortcuts 😅
