### ISSUE TITLE
[hide-uniform-cols] Couple issues.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#2577]
In https://github.com/saulpw/visidata/pull/2453 @midichef added `hide-uniform-cols`.  Thank you!  I have started using it.  I have a couple suggestions:

1. The `hide-uniform-cols` does not properly handle where the current column is after this command is done.  The code calls column.hide(), which does not change the index of the current column.  So if a column left of the current column is hidden it should move the cursor left by one. If the current column is hidden it should also move the cursor one column left, if possible.

https://github.com/saulpw/visidata/blob/3e10140963a62a5f78fc6b60ebd2ac9264ef2772/visidata/column.py#L289 

2. It would be useful if the command reported (vd.status())when it hides a column the name of the column and its value.  So you know what was hidden.

**Comment by midichef** [comment]
Thanks @frosencrantz for catching this. I can confirm that the lack of moving the cursor in `hide-uniform-cols` can cause problems like `IndexError`, when the number of columns hidden on the left is more than the remaining columns on the right.

I've got a patch to move the cursor, I'll discuss some implementation details in the PR.

**Comment by frosencrantz** [comment]
Thank you, @midichef! That was fast. I'll wait for the final commit.

**Comment by frosencrantz** [comment]
Thank you, @midichef!  This fix has made it to develop branch.  It works great.

**Comment by frosencrantz** [comment]
I find I use this command frequently. Thank you, again.

**Comment by saulpw** [comment]
@frosencrantz have you bound this command to a shortcut?

**Comment by frosencrantz** [comment]
@saulpw I have not, but it would be useful given how frequently I use it.  Maybe `g-` would be a good fit.  It fits with the scheme of `g` is wider version of the base command, and the base `-` hides the current column.

This keystroke is only used by `ColumnsSheet`, to `hide-selected`.  I do not expect to use `hide-uniform-cols` on the `ColumnsSheet`.
