### ISSUE TITLE
cannot open stdin when it is a tty

### ISSUE THREAD

**Issue by tkossak** [saulpw/visidata#2583]
**Small description**
can't replay vdj file when data comes from stdin

**Data to reproduce**
create file `test.csv` with content:
```csv
id,Name
1,Ziutek
2,Barbara
3,Hermenegilda
```

create test vdj file (`test.vdj`) - it was generated by visidata with `Ctrl+d`:
```
#!vd -p
{"sheet": "-", "col": null, "row": "csv_doublequote", "longname": "set-option", "input": "False", "keystrokes": "", "comment": null, "replayable": null}
{"sheet": "-", "row": "csv_skipinitialspace", "longname": "set-option", "input": "False", "keystrokes": ""}
{"longname": "open-file", "input": "-", "keystrokes": "o", "replayable": true}
{"sheet": "-", "col": "id", "row": "", "longname": "hide-col", "input": "", "keystrokes": "-", "comment": "hide the current column", "replayable": true}
```

**Steps to reproduce**
Run: `cat test.csv | vd -p test.vdj` and observe the error  `cannot open stdin when it is a tty`. The csv file is not shown, only test.vdj content.

**Expected result**
csv file, without first column (should be hidden by test.vdj file)

**Actual result with screenshot**
![image](https://github.com/user-attachments/assets/3ea2c298-5d94-41e9-9e28-7585077c728e)

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)? Yes.

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)? I have latest release: `saul.pw/VisiData v3.1.1`

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)?
Linux Manjaro

- Which version of Python? 3.11.9

- Which terminal are you using (for display and input issues)? Konsole

**Comment by midichef** [comment]
Thanks for the report. This will be fixed soon. Until then, as discussed in https://github.com/saulpw/visidata/issues/2582#issuecomment-2430093541 you can for now try commenting out the line that has `open-file` and `"-"`:
```
{"longname": "open-file", "input": "-", "keystrokes": "o", "replayable": true}
```

**Comment by Kossak-esky** [comment]
If it's of any use, I just installed vd from develop branch (3.2dev) and it gives me the same error.
Commenting out the line with "open-file" causes error `no sheet named -`

**Comment by tkossak** [comment]
If it's of any use, I just installed vd from develop branch (3.2dev) and it gives me the same error.
Commenting out the line with "open-file" causes error `no sheet named -`

**Comment by midichef** [comment]
Thanks @tkossak. I've just submitted a draft fix. For now, you can try it out temporarily by running `pip install git+https://github.com/midichef/visidata.git@stdin_pipe_tty`. It will install my fork of visidata with a 1-line fix for this bug.

That branch will work till I delete it, which will happen a bit after visidata incorporates a final fix for this issue.

**Comment by tkossak** [comment]
Works perfectly, thank you very much for your work on this awesome tool!

**Comment by anjakefala** [comment]
Gonna leave this open until it's merged. =) But I'm grateful for your testing!
