### ISSUE TITLE
automatic data updates

### ISSUE THREAD

**Issue by migueldvb** [saulpw/visidata#259]
I wonder if it is possible to get automatic updates of a `visidata` sheet based on the data provided in a web API. For example using the `gevent` library that  provides data in the queue to be processed by visidata. Are there any similar examples in the documentation?

**Comment by saulpw** [comment]
Hi @migueldvb, that's an interesting idea.  We could easily set it up to append additional rows, or execute individual commands (like from a .vd commandlog).  What's your particular use case?

**Comment by migueldvb** [comment]
I was thinking to update the numbers in the data sheet automatically without having to press some key combination. Currently the data is organized in a pandas dataframe with a preliminary manipulation from the queried API. The dataframe is updated approximately every minute, and then the changed values in the rows would be updated.

**Comment by saulpw** [comment]
Can you connect directly to the pandas DataFrame with VisiData?  It should be updated automatically already if so.  You can add another column to do the API query, and then set a timer that clears the caches every minute or so.  Does that make sense?

**Comment by migueldvb** [comment]
Thanks for the indications. I'm not sure how to connect VisiData with the dataframe, currently I'm launching vdtui using this code but it doesn't work for automatic updates.
```
 vd.run(vd.PandasSheet('pandas', source=df))
```

**Comment by saulpw** [comment]
Where does the dataframe (df) come from?  How does it get loaded in the first place?

**Comment by migueldvb** [comment]
The dataframe consists of integers and float numbers where the script updates some of the elements periodically inside a while loop.  I did not manage to have the visidata sheet update automatically the changed elements in the dataframe.

```
import pandas as pd
import visidata as vd
from random import randint
import time

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)

vd.run(vd.PandasSheet('pandas', source=df))

while True:
    df.loc[0, "col1"] = randint(0, 9)
    time.sleep(5)
```

**Comment by saulpw** [comment]
ah, I see, that's because vd.run() doesn't return until you quit out of VisiData. Try putting the code you want to run in parallel into an `@asyncthread` function that you call before run():

```
@vd.asyncthread
def changedata(df):
    while True:
        df.loc[0, "col1"] = randint(0, 9)
        time.sleep(.1)

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)

changedata(df)

vd.run(vd.PandasSheet('pandas', source=df))
```

**Comment by migueldvb** [comment]
Awesome! Thank you for the code example.
