### ISSUE TITLE
VisiData showing `{sheet.selectedStatus}` in right corner

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2599]
![image](https://github.com/user-attachments/assets/447404b4-16eb-44cf-85d7-dd14aad5ba45)

Sometimes VisiData shows `{sheet.selectedStatus}` in the bottom right corner. This happens even without `.visidatarc`. I got it to happen when I drew a plot, though it might have been happening in non-plot sheets too.

**Configuration**

- Does this issue reproduce without any plugins or configuration (using the `-N` CLI flag)? **Yes**

- Does this issue reproduce with either the [latest release](https://www.visidata.org/releases/), or with the [develop branch](https://www.visidata.org/install/#update-visidata-from-an-existing-installation)? **Both latest release and develop branch**

**Additional context**

- What platform and version are you using (Linux, MacOS, Windows)? **WSL Ubuntu on Windows, though I think it happens in normal Ubuntu too.**

- Which version of Python? **3.10.12**

- Which terminal are you using (for display and input issues)? **Windows Terminal, zsh.**

**Comment by midichef** [comment]
Thanks for catching this.
