### ISSUE TITLE
external importlib_metadata should not be required

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2612]
On a fresh checkout of 3.2dev, I get an error, missing `importlib_metadata`.  This external library should not be required on non-EOL Python versions: https://stackoverflow.com/questions/73165636/no-module-named-importlib-metadata

Replacing the `_` with `.` fixes the issue locally.

**Comment by anjakefala** [comment]
This was with Python 3.12

> Replacing the _ with . fixes the issue locally.

Replacing `importlib_metadata` with `importlib.metadata` in the code?

**Comment by anjakefala** [comment]
Okay, after some investigation, we basically don't need `importlib_metadata` anymore. We support Python 3.8+, and Python 3.8 has `importlib.metadata`. I'll make the change.
