### ISSUE TITLE
enable config of status messages on startup

### ISSUE THREAD

**Issue by zachvalenta** [saulpw/visidata#2621]
Turning off the status messages in the sidebar is [not currently possible via config](https://github.com/saulpw/visidata/issues/2567).

This ticket is me asking to make it configurable.

I find the quotes (`"And how else can it be?"`, `"Does YOUR watch tell you what year it is?"`) distracting. I also sense that it diminishes trust in visidata from non-developers. If I'm showing something to mgmt - already wedded to Excel and probably wondering why I'm using a TUI - gnostic quotes popping up on startup hurts my cause.

I really like visidata, hope this isn't coming off as froward.

**Comment by saulpw** [comment]
The quotes can be disabled by setting `options.motd_url=''`.

As for other status messages, it's important that they are visible somehow.  They used to be shown on the bottom "status bar" but that is now quite crowded, and there are sometimes more status messages than can fit on a single line anyway.  It's not a good idea to be able to turn them off entirely.

**Comment by zachvalenta** [comment]
> The quotes can be disabled by setting `options.motd_url=''`.

Great!

> As for other status messages, it's important that they are visible somehow. They used to be shown on the bottom "status bar" but that is now quite crowded, and there are sometimes more status messages than can fit on a single line anyway. It's not a good idea to be able to turn them off entirely.

Totally agree. Find them a very useful sanity check + they look snazzy.
