### ISSUE TITLE
Allow octants in plots

### ISSUE THREAD

**Issue by cool-RR** [saulpw/visidata#2626]
I was very excited to hear about the new [octants](https://github.com/microsoft/cascadia-code/issues/711) in Unicode, and I tried to replace the braille characters used in VisiData with these new characters.

I tried this in my `.visidatarc`:

```
options.disp_canvas_charset = '⠀𜴀𜴉𜴊𜴍𜴁𜴂𜴋𜴌𜴎𜴏𜴃𜴄𜴆𜴇𜴐𜴑𜴔𜴕𜴅𜴈𜴒𜴓𜴖𜴗𜴘𜴙𜴜𜴝𜴧𜴨𜴫𜴬𜴚𜴛𜴞𜴟𜴩𜴪𜴭𜴮𜴠𜴣𜴤𜴯𜴰𜴳𜴴𜴡𜴢𜴥𜴦𜴱𜴲𜴵𜴶𜴹𜴺𜵅𜵈𜴷𜴸𜴻𜴼𜵆𜵇𜵉𜵊𜴽𜴾𜵁𜵂𜵋𜵌𜵎𜵏𜴿𜵀𜵃𜵄𜵍𜵐𜵑𜵒𜵕𜵖𜵡𜵢𜵥𜵦𜵓𜵔𜵗𜵘𜵣𜵤𜵧𜵨𜵙𜵚𜵝𜵞𜵩𜵪𜵭𜵮𜵛𜵜𜵟𜵠𜵫𜵬𜵯𜵰𜵱𜵴𜵵𜶀𜶁𜶄𜶅𜵲𜵳𜵶𜵷𜶂𜶃𜶆𜶇𜵸𜵹𜵼𜵽𜶈𜶉𜶌𜶍𜵺𜵻𜵾𜵿𜶊𜶋𜶎𜶏𜶐𜶓𜶜𜶝𜶠𜶡𜶑𜶒𜶔𜶕𜶞𜶟𜶢𜶣𜶖𜶗𜶙𜶚𜶤𜶥𜶨𜶩𜶘𜶛𜶦𜶧𜶪𜶫𜶬𜶯𜶰𜶻𜶼𜶿𜷀𜶭𜶮𜶱𜶲𜶽𜶾𜷁𜷂𜶳𜶴𜶷𜶸𜷃𜷄𜷇𜷈𜶵𜶶𜶹𜶺𜷅𜷆𜷉𜷊𜷋𜷌𜷏𜷐𜷛𜷞𜷍𜷎𜷑𜷒𜷜𜷝𜷟𜷠𜷓𜷔𜷗𜷘𜷡𜷢𜷤𜷕𜷖𜷙𜷚𜷣𜷥'
```

This probably doesn't look right in your browser, but it looks right in my IDE and terminal:

![image](https://github.com/user-attachments/assets/a327a282-68e8-4ea9-9e75-e56f6758d400)

By the way, I had to work for an hour and a half to order these octants in the same order as braille characters.

Unfortunately, VisiData does not play ball:

![image](https://github.com/user-attachments/assets/f0c4afb3-047b-4d68-b969-ac61596443ac)

This is on the `develop` branch.

As you can see, the lines have holes in them which is where VisiData is trying to put the octant characters, but they come out blank.

**Comment by cool-RR** [comment]
I'm unsure whether this is a feature request or maybe I just need to adjust some encoding somewhere in the stack.

**Comment by midichef** [comment]
I can't check what's going on here as my system doesn't have these fonts.

But there's at least one problem: the octant `disp_canvas_charset` string here has only 230 characters. It'll need to have 256 of them like the current implementation:
https://github.com/saulpw/visidata/blob/ff489d3717a817a0a04a9cc0b48d5c19ea5e540c/visidata/canvas.py#L13

It would be good to have some Python code to generate the octant charset string programatically. That would make it easier to inspect the logic and the correctness.

**Comment by cool-RR** [comment]
> I can't check what's going on here as my system doesn't have these fonts.

You can download it here: https://github.com/microsoft/cascadia-code/releases

> 
> But there's at least one problem: the octant `disp_canvas_charset` string here has only 230 characters. It'll need to have 256 of them like the current implementation:
> 
> https://github.com/saulpw/visidata/blob/ff489d3717a817a0a04a9cc0b48d5c19ea5e540c/visidata/canvas.py#L13
> 
> It would be good to have some Python code to generate the octant charset string programatically. That would make it easier to inspect the logic and the correctness.

Right. But before solving this problem, we should figure out why VisiData doesn't show any octants at all.

**Comment by cool-RR** [comment]
To confirm it's not the number of characters that's the problem, I tried this: 

```python
options.disp_canvas_charset = '𜶫' * 256
assert len(options.disp_canvas_charset) == 256
```

Still I got the same blank results as in the original message on this issue.

**Comment by midichef** [comment]
Thanks. I was able to install the `Cascadia Mono` fonts on Ubuntu. I can see the octant characters in my terminal and in Python, for example, by running `python -c "print(''.join(chr(0x1cd00+i) for i in range(230)))"`.

I can reproduce the issue you are describing in Visidata: for octant characters on screen, blank spaces are drawn. Not just for octants plotted via `disp_canvas_charset`, but in writing text to the screen via `curses` calls. For example, `vd.status('a' + '\U0001cd00' + 'a')` draws `a a`. But on stdout, when the status call is run from `.visidatarc`, it shows up correctly in the terminal: `a𜴀a`.

My versions:
Ubuntu 24.04
Python 3.12.3 (where `unicodedata.unidata_version` is 15.1.0)
gnome-terminal

Ubuntu 22.04
Python 3.10.12 (where `unicodedata.unidata_version` is 13.0.0)
gnome-terminal

**Comment by midichef** [comment]
The issue seems to be within `curses`, not visidata. The octant character doesn't show up when curses draws it, using this test script:

```
#!/usr/bin/python
import curses

octants = ''.join(chr(0x1cd00+i) for i in range(230))
bracketed = '[' + octants + ']'
def main(stdscr):
    stdscr.addstr(f'octants drawn in curses: {bracketed}')
    stdscr.refresh()
    stdscr.getch()

try:
    curses.wrapper(main)
except KeyboardInterrupt:
    pass
print(f'octants printed to stdout: {bracketed}')
```

**Comment by cool-RR** [comment]
Thank you. Opened https://github.com/python/cpython/issues/127795

**Comment by midichef** [comment]
My current best guess for what is happening here:  the new characters are so new that `ncurses` cannot know how to draw them. When `ncurses` sees an "unassigned codepoint", [it draws a blank space for it (at least, it did in 2016)](https://lists.gnu.org/archive/html/bug-ncurses/2016-01/msg00006.html).

The octant characters are part of Unicode 16.0, which was released a few months ago. My guess is `ncurses` will draw these characters when the OS gets some kind of update to its character database. (If you want to investigate further, the technical term "locale" may be useful.) That update is likely the responsibility of the OS distro. I don't think it's something `ncurses` has any responsibility for.

Unicode releases happen each year in September, and Ubuntu support follows 3-6 months later. So I'd expect an Ubuntu update to fix this problem in the next few months.

For Windows, I'm not sure what to expect.

**Comment by frosencrantz** [comment]
It looks like this  bug progress was here, and should be fixed.

- Curses: [https://lists.gnu.org/archive/html/bug-ncurses/2024-12/msg00008.html](https://lists.gnu.org/archive/html/bug-ncurses/2024-12/msg00008.html) says glibc doesn’t support Unicode 16.0  (2024 Dec)  
- Glibc supports it now in 2.41 (2025 Jan) [https://lists.gnu.org/archive/html/info-gnu/2025-01/msg00014.html](https://lists.gnu.org/archive/html/info-gnu/2025-01/msg00014.html) 


@cool-RR or @midichef  did you ever get it to work for you?  I tried it recently on a terminal that supports the characters, but it didn't appear to work.

**Comment by midichef** [comment]
Yes, I tested just now in Ubuntu 25.04, which has glibc 2.41. Octants work [inside curses in a Python test script](https://github.com/saulpw/visidata/issues/2626#issuecomment-2530149005), and inside visidata plots when I used @cool-RR's custom `disp_canvas_charset`.

However that charset mapping for the first 230 characters does not look correct. It doesn't match the patterns of braille on my system (on Ubuntu 25.04/gnome-terminal). What remains now is to sort out the proper ordering of the assignment of octant characters. Perhaps consult an LLM, then have a different LLM look for flaws?

**Comment by cool-RR** [comment]
I tried this on two of my Linux systems and it didn't work. If I'll have to compile curses or something I'll pass and just wait for it to become more easily available.

**Comment by PhMajerus** [comment]
Just in case you're still looking for the braille to octants mapping...
Octants do not cover the whole 256 possible patterns because some already existed as part of half-blocks and quadrants, so the full list has to stretch across several Unicode blocks.
Here is the full mapping in JSON:
```
["\u2800\u2801\u2808\u2809\u2802\u2803\u280a\u280b\u2810\u2811\u2818\u2819\u2812\u2813\u281a\u281b\u2804\u2805\u280c\u280d\u2806\u2807\u280e\u280f\u2814\u2815\u281c\u281d\u2816\u2817\u281e\u281f\u2820\u2821\u2828\u2829\u2822\u2823\u282a\u282b\u2830\u2831\u2838\u2839\u2832\u2833\u283a\u283b\u2824\u2825\u282c\u282d\u2826\u2827\u282e\u282f\u2834\u2835\u283c\u283d\u2836\u2837\u283e\u283f\u2840\u2841\u2848\u2849\u2842\u2843\u284a\u284b\u2850\u2851\u2858\u2859\u2852\u2853\u285a\u285b\u2844\u2845\u284c\u284d\u2846\u2847\u284e\u284f\u2854\u2855\u285c\u285d\u2856\u2857\u285e\u285f\u2860\u2861\u2868\u2869\u2862\u2863\u286a\u286b\u2870\u2871\u2878\u2879\u2872\u2873\u287a\u287b\u2864\u2865\u286c\u286d\u2866\u2867\u286e\u286f\u2874\u2875\u287c\u287d\u2876\u2877\u287e\u287f\u2880\u2881\u2888\u2889\u2882\u2883\u288a\u288b\u2890\u2891\u2898\u2899\u2892\u2893\u289a\u289b\u2884\u2885\u288c\u288d\u2886\u2887\u288e\u288f\u2894\u2895\u289c\u289d\u2896\u2897\u289e\u289f\u28a0\u28a1\u28a8\u28a9\u28a2\u28a3\u28aa\u28ab\u28b0\u28b1\u28b8\u28b9\u28b2\u28b3\u28ba\u28bb\u28a4\u28a5\u28ac\u28ad\u28a6\u28a7\u28ae\u28af\u28b4\u28b5\u28bc\u28bd\u28b6\u28b7\u28be\u28bf\u28c0\u28c1\u28c8\u28c9\u28c2\u28c3\u28ca\u28cb\u28d0\u28d1\u28d8\u28d9\u28d2\u28d3\u28da\u28db\u28c4\u28c5\u28cc\u28cd\u28c6\u28c7\u28ce\u28cf\u28d4\u28d5\u28dc\u28dd\u28d6\u28d7\u28de\u28df\u28e0\u28e1\u28e8\u28e9\u28e2\u28e3\u28ea\u28eb\u28f0\u28f1\u28f8\u28f9\u28f2\u28f3\u28fa\u28fb\u28e4\u28e5\u28ec\u28ed\u28e6\u28e7\u28ee\u28ef\u28f4\u28f5\u28fc\u28fd\u28f6\u28f7\u28fe\u28ff","\u00a0\ud833\udea8\ud833\udeab\ud83e\udf82\ud833\udd00\u2598\ud833\udd01\ud833\udd02\ud833\udd03\ud833\udd04\u259d\ud833\udd05\ud833\udd06\ud833\udd07\ud833\udd08\u2580\ud833\udd09\ud833\udd0a\ud833\udd0b\ud833\udd0c\ud83e\udfe6\ud833\udd0d\ud833\udd0e\ud833\udd0f\ud833\udd10\ud833\udd11\ud833\udd12\ud833\udd13\ud833\udd14\ud833\udd15\ud833\udd16\ud833\udd17\ud833\udd18\ud833\udd19\ud833\udd1a\ud833\udd1b\ud833\udd1c\ud833\udd1d\ud833\udd1e\ud833\udd1f\ud83e\udfe7\ud833\udd20\ud833\udd21\ud833\udd22\ud833\udd23\ud833\udd24\ud833\udd25\ud833\udd26\ud833\udd27\ud833\udd28\ud833\udd29\ud833\udd2a\ud833\udd2b\ud833\udd2c\ud833\udd2d\ud833\udd2e\ud833\udd2f\ud833\udd30\ud833\udd31\ud833\udd32\ud833\udd33\ud833\udd34\ud833\udd35\ud83e\udf85\ud833\udea3\ud833\udd36\ud833\udd37\ud833\udd38\ud833\udd39\ud833\udd3a\ud833\udd3b\ud833\udd3c\ud833\udd3d\ud833\udd3e\ud833\udd3f\ud833\udd40\ud833\udd41\ud833\udd42\ud833\udd43\ud833\udd44\u2596\ud833\udd45\ud833\udd46\ud833\udd47\ud833\udd48\u258c\ud833\udd49\ud833\udd4a\ud833\udd4b\ud833\udd4c\u259e\ud833\udd4d\ud833\udd4e\ud833\udd4f\ud833\udd50\u259b\ud833\udd51\ud833\udd52\ud833\udd53\ud833\udd54\ud833\udd55\ud833\udd56\ud833\udd57\ud833\udd58\ud833\udd59\ud833\udd5a\ud833\udd5b\ud833\udd5c\ud833\udd5d\ud833\udd5e\ud833\udd5f\ud833\udd60\ud833\udd61\ud833\udd62\ud833\udd63\ud833\udd64\ud833\udd65\ud833\udd66\ud833\udd67\ud833\udd68\ud833\udd69\ud833\udd6a\ud833\udd6b\ud833\udd6c\ud833\udd6d\ud833\udd6e\ud833\udd6f\ud833\udd70\ud833\udea0\ud833\udd71\ud833\udd72\ud833\udd73\ud833\udd74\ud833\udd75\ud833\udd76\ud833\udd77\ud833\udd78\ud833\udd79\ud833\udd7a\ud833\udd7b\ud833\udd7c\ud833\udd7d\ud833\udd7e\ud833\udd7f\ud833\udd80\ud833\udd81\ud833\udd82\ud833\udd83\ud833\udd84\ud833\udd85\ud833\udd86\ud833\udd87\ud833\udd88\ud833\udd89\ud833\udd8a\ud833\udd8b\ud833\udd8c\ud833\udd8d\ud833\udd8e\ud833\udd8f\u2597\ud833\udd90\ud833\udd91\ud833\udd92\ud833\udd93\u259a\ud833\udd94\ud833\udd95\ud833\udd96\ud833\udd97\u2590\ud833\udd98\ud833\udd99\ud833\udd9a\ud833\udd9b\u259c\ud833\udd9c\ud833\udd9d\ud833\udd9e\ud833\udd9f\ud833\udda0\ud833\udda1\ud833\udda2\ud833\udda3\ud833\udda4\ud833\udda5\ud833\udda6\ud833\udda7\ud833\udda8\ud833\udda9\ud833\uddaa\ud833\uddab\u2582\ud833\uddac\ud833\uddad\ud833\uddae\ud833\uddaf\ud833\uddb0\ud833\uddb1\ud833\uddb2\ud833\uddb3\ud833\uddb4\ud833\uddb5\ud833\uddb6\ud833\uddb7\ud833\uddb8\ud833\uddb9\ud833\uddba\ud833\uddbb\ud833\uddbc\ud833\uddbd\ud833\uddbe\ud833\uddbf\ud833\uddc0\ud833\uddc1\ud833\uddc2\ud833\uddc3\ud833\uddc4\ud833\uddc5\ud833\uddc6\ud833\uddc7\ud833\uddc8\ud833\uddc9\ud833\uddca\ud833\uddcb\ud833\uddcc\ud833\uddcd\ud833\uddce\ud833\uddcf\ud833\uddd0\ud833\uddd1\ud833\uddd2\ud833\uddd3\ud833\uddd4\ud833\uddd5\ud833\uddd6\ud833\uddd7\ud833\uddd8\ud833\uddd9\ud833\uddda\u2584\ud833\udddb\ud833\udddc\ud833\udddd\ud833\uddde\u2599\ud833\udddf\ud833\udde0\ud833\udde1\ud833\udde2\u259f\ud833\udde3\u2586\ud833\udde4\ud833\udde5\u2588"]
```
This is an array with the full list of Braille followed by the full list of octants (and previously existing borrowed patterns) in the same order. So you can use it to build a corresponding map or a conversion function:

<img width="932" height="124" alt="Image" src="https://github.com/user-attachments/assets/a08869ff-2c83-4b7d-9391-df64448cd727" />

**Comment by midichef** [comment]
Oh, that's great work, thank you for putting that together!

**Comment by midichef** [comment]
(EDITED 2026-02-05 to note that this code was wrong)
Okay for future reference, here's the options setting to use octants instead of Braille:
```
options.disp_canvas_charset = ' \U0001cea8\U0001cd00▘\U0001cd09\U0001cd0a\U0001fbe6\U0001cd0d\U0001ceab🮂\U0001cd01\U0001cd02\U0001cd0b\U0001cd0c\U0001cd0e\U0001cd0f\U0001cd03\U0001cd04\U0001cd06\U0001cd07\U0001cd10\U0001cd11\U0001cd14\U0001cd15▝\U0001cd05\U0001cd08▀\U0001cd12\U0001cd13\U0001cd16\U0001cd17\U0001cd18\U0001cd19\U0001cd1c\U0001cd1d\U0001cd27\U0001cd28\U0001cd2b\U0001cd2c\U0001cd1a\U0001cd1b\U0001cd1e\U0001cd1f\U0001cd29\U0001cd2a\U0001cd2d\U0001cd2e\U0001fbe7\U0001cd20\U0001cd23\U0001cd24\U0001cd2f\U0001cd30\U0001cd33\U0001cd34\U0001cd21\U0001cd22\U0001cd25\U0001cd26\U0001cd31\U0001cd32\U0001cd35🮅\U0001cea3\U0001cd36\U0001cd39\U0001cd3a▖\U0001cd45\U0001cd48▌\U0001cd37\U0001cd38\U0001cd3b\U0001cd3c\U0001cd46\U0001cd47\U0001cd49\U0001cd4a\U0001cd3d\U0001cd3e\U0001cd41\U0001cd42\U0001cd4b\U0001cd4c\U0001cd4e\U0001cd4f\U0001cd3f\U0001cd40\U0001cd43\U0001cd44▞\U0001cd4d\U0001cd50▛\U0001cd51\U0001cd52\U0001cd55\U0001cd56\U0001cd61\U0001cd62\U0001cd65\U0001cd66\U0001cd53\U0001cd54\U0001cd57\U0001cd58\U0001cd63\U0001cd64\U0001cd67\U0001cd68\U0001cd59\U0001cd5a\U0001cd5d\U0001cd5e\U0001cd69\U0001cd6a\U0001cd6d\U0001cd6e\U0001cd5b\U0001cd5c\U0001cd5f\U0001cd60\U0001cd6b\U0001cd6c\U0001cd6f\U0001cd70\U0001cea0\U0001cd71\U0001cd74\U0001cd75\U0001cd80\U0001cd81\U0001cd84\U0001cd85\U0001cd72\U0001cd73\U0001cd76\U0001cd77\U0001cd82\U0001cd83\U0001cd86\U0001cd87\U0001cd78\U0001cd79\U0001cd7c\U0001cd7d\U0001cd88\U0001cd89\U0001cd8c\U0001cd8d\U0001cd7a\U0001cd7b\U0001cd7e\U0001cd7f\U0001cd8a\U0001cd8b\U0001cd8e\U0001cd8f▗\U0001cd90\U0001cd93▚\U0001cd9c\U0001cd9d\U0001cda0\U0001cda1\U0001cd91\U0001cd92\U0001cd94\U0001cd95\U0001cd9e\U0001cd9f\U0001cda2\U0001cda3\U0001cd96\U0001cd97\U0001cd99\U0001cd9a\U0001cda4\U0001cda5\U0001cda8\U0001cda9▐\U0001cd98\U0001cd9b▜\U0001cda6\U0001cda7\U0001cdaa\U0001cdab▂\U0001cdac\U0001cdaf\U0001cdb0\U0001cdbb\U0001cdbc\U0001cdbf\U0001cdc0\U0001cdad\U0001cdae\U0001cdb1\U0001cdb2\U0001cdbd\U0001cdbe\U0001cdc1\U0001cdc2\U0001cdb3\U0001cdb4\U0001cdb7\U0001cdb8\U0001cdc3\U0001cdc4\U0001cdc7\U0001cdc8\U0001cdb5\U0001cdb6\U0001cdb9\U0001cdba\U0001cdc5\U0001cdc6\U0001cdc9\U0001cdca\U0001cdcb\U0001cdcc\U0001cdcf\U0001cdd0▄\U0001cddb\U0001cdde▙\U0001cdcd\U0001cdce\U0001cdd1\U0001cdd2\U0001cddc\U0001cddd\U0001cddf\U0001cde0\U0001cdd3\U0001cdd4\U0001cdd7\U0001cdd8\U0001cde1\U0001cde2▆\U0001cde4\U0001cdd5\U0001cdd6\U0001cdd9\U0001cdda▟\U0001cde3\U0001cde5█'
```

It took me a bit to guess the format of the octants mapping since it's a string of length 494 instead of 256, turns out it is slightly malformed(?) UTF-16. So the code to generate the braille to octants mapping was:
```
## 2026-02-05 EDITED to remove incorrect code
```

**Comment by PhMajerus** [comment]
> It took me a bit to guess the format of the octants mapping since it's a string of length 494 instead of 256, turns out it is slightly malformed(?) UTF-16.

You're mixing Unicode code points and UTF-16 code units. Not all Unicode characters can be encoded using a single UTF-16 code unit, and the Symbols for Legacy Computing Supplement block is in a block that requires surrogates pairs when encoded in UTF-16.

In UTF-16, characters above `U+FFFF` require two code units, called a surrogate pair, to be encoded. That's how UTF-16 extended UCS-2 to support `U+10000` and above. So while the Octants string is indeed 494 UTF-16 code units, it is 256 Unicode code points as expected.
This is similar to how they would have different lengths (code unit counts) in UTF-8, 768 for Braille and 1004 for Octants respectively.
JSON uses UTF-16 because of its JavaScript origins, so the strings are built using UTF-16 surrogates. It should be parsed by a JSON decoder and then converted to the format used by your programming environment in a data type that supports Unicode properly to process them as 'characters'. Just remember that many languages provide a `length` function that returns the number of code units in the UTF encoding they're using, not the number of code points.

**Comment by PhMajerus** [comment]
Here are the two character sets as Python literals (escaped to avoid any encoding mismatch):
```
braille = "\u2800\u2801\u2808\u2809\u2802\u2803\u280A\u280B\u2810\u2811\u2818\u2819\u2812\u2813\u281A\u281B\u2804\u2805\u280C\u280D\u2806\u2807\u280E\u280F\u2814\u2815\u281C\u281D\u2816\u2817\u281E\u281F\u2820\u2821\u2828\u2829\u2822\u2823\u282A\u282B\u2830\u2831\u2838\u2839\u2832\u2833\u283A\u283B\u2824\u2825\u282C\u282D\u2826\u2827\u282E\u282F\u2834\u2835\u283C\u283D\u2836\u2837\u283E\u283F\u2840\u2841\u2848\u2849\u2842\u2843\u284A\u284B\u2850\u2851\u2858\u2859\u2852\u2853\u285A\u285B\u2844\u2845\u284C\u284D\u2846\u2847\u284E\u284F\u2854\u2855\u285C\u285D\u2856\u2857\u285E\u285F\u2860\u2861\u2868\u2869\u2862\u2863\u286A\u286B\u2870\u2871\u2878\u2879\u2872\u2873\u287A\u287B\u2864\u2865\u286C\u286D\u2866\u2867\u286E\u286F\u2874\u2875\u287C\u287D\u2876\u2877\u287E\u287F\u2880\u2881\u2888\u2889\u2882\u2883\u288A\u288B\u2890\u2891\u2898\u2899\u2892\u2893\u289A\u289B\u2884\u2885\u288C\u288D\u2886\u2887\u288E\u288F\u2894\u2895\u289C\u289D\u2896\u2897\u289E\u289F\u28A0\u28A1\u28A8\u28A9\u28A2\u28A3\u28AA\u28AB\u28B0\u28B1\u28B8\u28B9\u28B2\u28B3\u28BA\u28BB\u28A4\u28A5\u28AC\u28AD\u28A6\u28A7\u28AE\u28AF\u28B4\u28B5\u28BC\u28BD\u28B6\u28B7\u28BE\u28BF\u28C0\u28C1\u28C8\u28C9\u28C2\u28C3\u28CA\u28CB\u28D0\u28D1\u28D8\u28D9\u28D2\u28D3\u28DA\u28DB\u28C4\u28C5\u28CC\u28CD\u28C6\u28C7\u28CE\u28CF\u28D4\u28D5\u28DC\u28DD\u28D6\u28D7\u28DE\u28DF\u28E0\u28E1\u28E8\u28E9\u28E2\u28E3\u28EA\u28EB\u28F0\u28F1\u28F8\u28F9\u28F2\u28F3\u28FA\u28FB\u28E4\u28E5\u28EC\u28ED\u28E6\u28E7\u28EE\u28EF\u28F4\u28F5\u28FC\u28FD\u28F6\u28F7\u28FE\u28FF"
octants = "\xA0\U0001CEA8\U0001CEAB\U0001FB82\U0001CD00\u2598\U0001CD01\U0001CD02\U0001CD03\U0001CD04\u259D\U0001CD05\U0001CD06\U0001CD07\U0001CD08\u2580\U0001CD09\U0001CD0A\U0001CD0B\U0001CD0C\U0001FBE6\U0001CD0D\U0001CD0E\U0001CD0F\U0001CD10\U0001CD11\U0001CD12\U0001CD13\U0001CD14\U0001CD15\U0001CD16\U0001CD17\U0001CD18\U0001CD19\U0001CD1A\U0001CD1B\U0001CD1C\U0001CD1D\U0001CD1E\U0001CD1F\U0001FBE7\U0001CD20\U0001CD21\U0001CD22\U0001CD23\U0001CD24\U0001CD25\U0001CD26\U0001CD27\U0001CD28\U0001CD29\U0001CD2A\U0001CD2B\U0001CD2C\U0001CD2D\U0001CD2E\U0001CD2F\U0001CD30\U0001CD31\U0001CD32\U0001CD33\U0001CD34\U0001CD35\U0001FB85\U0001CEA3\U0001CD36\U0001CD37\U0001CD38\U0001CD39\U0001CD3A\U0001CD3B\U0001CD3C\U0001CD3D\U0001CD3E\U0001CD3F\U0001CD40\U0001CD41\U0001CD42\U0001CD43\U0001CD44\u2596\U0001CD45\U0001CD46\U0001CD47\U0001CD48\u258C\U0001CD49\U0001CD4A\U0001CD4B\U0001CD4C\u259E\U0001CD4D\U0001CD4E\U0001CD4F\U0001CD50\u259B\U0001CD51\U0001CD52\U0001CD53\U0001CD54\U0001CD55\U0001CD56\U0001CD57\U0001CD58\U0001CD59\U0001CD5A\U0001CD5B\U0001CD5C\U0001CD5D\U0001CD5E\U0001CD5F\U0001CD60\U0001CD61\U0001CD62\U0001CD63\U0001CD64\U0001CD65\U0001CD66\U0001CD67\U0001CD68\U0001CD69\U0001CD6A\U0001CD6B\U0001CD6C\U0001CD6D\U0001CD6E\U0001CD6F\U0001CD70\U0001CEA0\U0001CD71\U0001CD72\U0001CD73\U0001CD74\U0001CD75\U0001CD76\U0001CD77\U0001CD78\U0001CD79\U0001CD7A\U0001CD7B\U0001CD7C\U0001CD7D\U0001CD7E\U0001CD7F\U0001CD80\U0001CD81\U0001CD82\U0001CD83\U0001CD84\U0001CD85\U0001CD86\U0001CD87\U0001CD88\U0001CD89\U0001CD8A\U0001CD8B\U0001CD8C\U0001CD8D\U0001CD8E\U0001CD8F\u2597\U0001CD90\U0001CD91\U0001CD92\U0001CD93\u259A\U0001CD94\U0001CD95\U0001CD96\U0001CD97\u2590\U0001CD98\U0001CD99\U0001CD9A\U0001CD9B\u259C\U0001CD9C\U0001CD9D\U0001CD9E\U0001CD9F\U0001CDA0\U0001CDA1\U0001CDA2\U0001CDA3\U0001CDA4\U0001CDA5\U0001CDA6\U0001CDA7\U0001CDA8\U0001CDA9\U0001CDAA\U0001CDAB\u2582\U0001CDAC\U0001CDAD\U0001CDAE\U0001CDAF\U0001CDB0\U0001CDB1\U0001CDB2\U0001CDB3\U0001CDB4\U0001CDB5\U0001CDB6\U0001CDB7\U0001CDB8\U0001CDB9\U0001CDBA\U0001CDBB\U0001CDBC\U0001CDBD\U0001CDBE\U0001CDBF\U0001CDC0\U0001CDC1\U0001CDC2\U0001CDC3\U0001CDC4\U0001CDC5\U0001CDC6\U0001CDC7\U0001CDC8\U0001CDC9\U0001CDCA\U0001CDCB\U0001CDCC\U0001CDCD\U0001CDCE\U0001CDCF\U0001CDD0\U0001CDD1\U0001CDD2\U0001CDD3\U0001CDD4\U0001CDD5\U0001CDD6\U0001CDD7\U0001CDD8\U0001CDD9\U0001CDDA\u2584\U0001CDDB\U0001CDDC\U0001CDDD\U0001CDDE\u2599\U0001CDDF\U0001CDE0\U0001CDE1\U0001CDE2\u259F\U0001CDE3\u2586\U0001CDE4\U0001CDE5\u2588"
```

**Comment by midichef** [comment]
Ah thank you. I understand now. Your code snippet was JSON, and not, of course, malformed. Your explanation was extremely clear and helpful. I have done some extra reading on Unicode to remedy my ignorance. And edited my comment to mark it as wrong.

Using your helpful mapping between octants and braille, the following code will generate a string of octants ordered for use in Visidata as `disp_canvas_charset`:
```
b2o = dict(zip(braille, octants, strict=True))
disp_canvas_octants = ''.join([ b2o[chr(0x2800+i)] for i in range(256) ])
print(repr(disp_canvas_octants))
```

Giving the final result:
```
disp_canvas_charset_octants = '\xa0\U0001cea8\U0001cd00▘\U0001cd09\U0001cd0a\U0001fbe6\U0001cd0d\U0001ceab🮂\U0001cd01\U0001cd02\U0001cd0b\U0001cd0c\U0001cd0e\U0001cd0f\U0001cd03\U0001cd04\U0001cd06\U0001cd07\U0001cd10\U0001cd11\U0001cd14\U0001cd15▝\U0001cd05\U0001cd08▀\U0001cd12\U0001cd13\U0001cd16\U0001cd17\U0001cd18\U0001cd19\U0001cd1c\U0001cd1d\U0001cd27\U0001cd28\U0001cd2b\U0001cd2c\U0001cd1a\U0001cd1b\U0001cd1e\U0001cd1f\U0001cd29\U0001cd2a\U0001cd2d\U0001cd2e\U0001fbe7\U0001cd20\U0001cd23\U0001cd24\U0001cd2f\U0001cd30\U0001cd33\U0001cd34\U0001cd21\U0001cd22\U0001cd25\U0001cd26\U0001cd31\U0001cd32\U0001cd35🮅\U0001cea3\U0001cd36\U0001cd39\U0001cd3a▖\U0001cd45\U0001cd48▌\U0001cd37\U0001cd38\U0001cd3b\U0001cd3c\U0001cd46\U0001cd47\U0001cd49\U0001cd4a\U0001cd3d\U0001cd3e\U0001cd41\U0001cd42\U0001cd4b\U0001cd4c\U0001cd4e\U0001cd4f\U0001cd3f\U0001cd40\U0001cd43\U0001cd44▞\U0001cd4d\U0001cd50▛\U0001cd51\U0001cd52\U0001cd55\U0001cd56\U0001cd61\U0001cd62\U0001cd65\U0001cd66\U0001cd53\U0001cd54\U0001cd57\U0001cd58\U0001cd63\U0001cd64\U0001cd67\U0001cd68\U0001cd59\U0001cd5a\U0001cd5d\U0001cd5e\U0001cd69\U0001cd6a\U0001cd6d\U0001cd6e\U0001cd5b\U0001cd5c\U0001cd5f\U0001cd60\U0001cd6b\U0001cd6c\U0001cd6f\U0001cd70\U0001cea0\U0001cd71\U0001cd74\U0001cd75\U0001cd80\U0001cd81\U0001cd84\U0001cd85\U0001cd72\U0001cd73\U0001cd76\U0001cd77\U0001cd82\U0001cd83\U0001cd86\U0001cd87\U0001cd78\U0001cd79\U0001cd7c\U0001cd7d\U0001cd88\U0001cd89\U0001cd8c\U0001cd8d\U0001cd7a\U0001cd7b\U0001cd7e\U0001cd7f\U0001cd8a\U0001cd8b\U0001cd8e\U0001cd8f▗\U0001cd90\U0001cd93▚\U0001cd9c\U0001cd9d\U0001cda0\U0001cda1\U0001cd91\U0001cd92\U0001cd94\U0001cd95\U0001cd9e\U0001cd9f\U0001cda2\U0001cda3\U0001cd96\U0001cd97\U0001cd99\U0001cd9a\U0001cda4\U0001cda5\U0001cda8\U0001cda9▐\U0001cd98\U0001cd9b▜\U0001cda6\U0001cda7\U0001cdaa\U0001cdab▂\U0001cdac\U0001cdaf\U0001cdb0\U0001cdbb\U0001cdbc\U0001cdbf\U0001cdc0\U0001cdad\U0001cdae\U0001cdb1\U0001cdb2\U0001cdbd\U0001cdbe\U0001cdc1\U0001cdc2\U0001cdb3\U0001cdb4\U0001cdb7\U0001cdb8\U0001cdc3\U0001cdc4\U0001cdc7\U0001cdc8\U0001cdb5\U0001cdb6\U0001cdb9\U0001cdba\U0001cdc5\U0001cdc6\U0001cdc9\U0001cdca\U0001cdcb\U0001cdcc\U0001cdcf\U0001cdd0▄\U0001cddb\U0001cdde▙\U0001cdcd\U0001cdce\U0001cdd1\U0001cdd2\U0001cddc\U0001cddd\U0001cddf\U0001cde0\U0001cdd3\U0001cdd4\U0001cdd7\U0001cdd8\U0001cde1\U0001cde2▆\U0001cde4\U0001cdd5\U0001cdd6\U0001cdd9\U0001cdda▟\U0001cde3\U0001cde5█'
```
