### ISSUE TITLE
An aggregator which gathers values into a list

### ISSUE THREAD

**Issue by chocolateboy** [saulpw/visidata#263]
Any interest in adding an aggregator which gathers items into a (Python) list? I often need to group by a key column and gather values in another column into a list, which is then exported as a JSON array e.g. for something like an [episode guide](https://www.youtube.com/watch?v=0iJ9F4uTkz8), I might want to group by writer and gather together their episodes into an array of titles.

I've added an aggregator for this to my `~/.visidatarc`, which works well, but it seems like such an obvious/common usage that I'm wondering why it's not built in.

The implementation is trivial:

```python
def collect(values):
    """aggregator which gathers values in a column into a list"""
    return list(values)

aggregator('collect', collect)
```

The only downside I can think of is that the list of aggregators is already rather long.

**Comment by saulpw** [comment]
That's a great suggestion, @chocolateboy.  It did not occur to me that someone would want to do this (I don't work with nested JSON very often), but now that I see it, it does seem obvious.  We could go even one step further with `aggregator('list', list)` which is an almost comical oversight.

Also, you're right, the list of aggregators is already long (14 with this new one).  I had been wondering what to do about them, and I think they are a good candidate for a popup subsheet chooser (which would also include a docstring column).
