### ISSUE TITLE
[question] Replaying command log file is significantly slower in release 3.1.1 compared to 2.11

### ISSUE THREAD

**Issue by DmitryAndreyeff** [saulpw/visidata#2634]
Replaying command log file is significantly slower in release 3.1.1 compared to 2.11.

Based on [this](https://github.com/saulpw/visidata/discussions/2628#discussioncomment-11489070) discussion, attaching [files.zip](https://github.com/user-attachments/files/18126892/files.zip) to reproduce the issue.

env details:
Mac OS Sonoma 14.6
Python 3.12.7
Visidata 3.1.1

Please advise.

**Comment by midichef** [comment]
Okay, I can reproduce some slowness, it takes about 1.6 seconds longer on v3.1.1 vs 2.11.1.

How fast is it when you add `-b -i` to your replay command:  `vd -b -i -p sheets.vdj`. For me that restores the quick playback that I see in v2.11.1. Does it restore the previous quickness for you?

**Comment by DmitryAndreyeff** [comment]
Hi @midichef , indeed, these flags make the playback in v3 as fast as it was in v2. Thank you very much!

**Comment by midichef** [comment]
Okay, then I know what caused the change. We should be able to figure out a fix for the slowness, so you won't need to do `-b -i` in the future. (And `-b -i` has some definite drawbacks, like not being able to see data on-screen during loading, which could be a long time for a slow sheet.)

**Comment by DmitryAndreyeff** [comment]
@midichef , actually `-b` flag breaks completely the ability to edit cells.

**Comment by midichef** [comment]
Thanks @DmitryAndreyeff for reporting that. I have created an issue #2639 for that problem.

For now, I would recommend applying the fix in #2635, which is this commit: 87c99f215182930e12814b96f5ac35dfa2db078a. It will let you avoid using `-b -i`. It will allow `edit-cell` to work as usual. It will remove some of the visible delay in your replays, though not all of it.
