### ISSUE TITLE
Crash when replaying a command log that contains brace-enclosed RegEx quantifiers

### ISSUE THREAD

**Issue by jspatz** [saulpw/visidata#271]
When playing back a command log that includes RegEx quantifiers in braces (e.g. using [0-9]{5} to match sequence of exactly five digits) -- or in fact includes numeric digits inside of curly braces for any reason at all -- VisiData will crash.  It looks like the Python string format function that substitutes variables with the values assigned on the command line is throwing an exception whenever it encounter numbers in braces.

An effective workaround is to replace brace-enclosed quantifiers with alphabetic variable names in the command log, then assign the full quantifier expression (including the braces) to that variable on the command line.

**Comment by saulpw** [comment]
Thanks for the report, @jspatz.  You are totally right that this is an issue.  The fix that I made was to only format the string *if* extra args (like filenames) or kwargs (like `key=value`) are given on the command line.  If not, then the cmdlog is passed through unformatted.  This has the small disadvantage that replaying a "template" .vd without any args will fail in a less obvious way; I might recommend that these are named `.tvd` or something to indicate that they need parameters.  But this won't affect you, and the above fix should make your life easier.  This will be in 1.6.
