### ISSUE TITLE
harmonic and geometric means in describe sheet

### ISSUE THREAD

**Issue by unhammer** [saulpw/visidata#273]
The [geometric mean](https://en.wikipedia.org/wiki/Geometric_mean) is nice for [comparing values from different ranges](https://www.cse.unsw.edu.au/~cs9242/15/papers/Fleming_Wallace_86.pdf) and the [harmonic mean](https://en.wikipedia.org/wiki/Harmonic_mean) for comparing ratios. It'd be nice if they showed up in the `shift-i`  describe sheet :-)

**Comment by unhammer** [comment]
(Or is there a way to customize the describe sheet?)

**Comment by saulpw** [comment]
Thanks for the request, @unhammer.  I'm wondering if maybe we should automatically add all aggregators to the describe sheet, and then you could add those aggregators yourself in your `.visidatarc` (and we may add them to core VisiData once we have a better way to organize the increasingly long list of aggregators).  My only concern is that this would make the Describe sheet messier by default, and so I'm not sure how best to organize it.  Do you have any ideas?

And of course, everything is customizable, if you're willing to dive into the code :)

**Comment by unhammer** [comment]
Hm, I don't think I'm experienced enough with visidata to think of what the best organisation would be, but auto-adding aggregators to describe sheet does sound like an ok solution.

**Comment by saulpw** [comment]
With the above commit, add this to your .visidatarc for e.g. an harmonic mean to be added automatically to the describe sheet:
    
            from statistics import harmonic_mean
            options.describe_aggrs += ' harmonic_mean'  # note the leading space

**Comment by danielfleischer** [comment]
For completeness, the code needed is this:

```python
from statistics import geometric_mean
vd.aggregator("gmean", geometric_mean, type=float)
options.describe_aggrs += " gmean"
```
