### ISSUE TITLE
How to save column expressions (à la Excel, etc.)?

### ISSUE THREAD

**Issue by rnkn** [saulpw/visidata#276]
VisiData is a truly amazing piece of software. Much appreciation for creating it.

I'm wondering if it's possible to use VisiData in a similar way to Excel or other spreadsheeting programs that have dynamic column values calculated with formulas?

I guess in VisiData these would be Python expressions but is it possible to save these to the (tsv|csv) file somehow? Or save in another file and reference them?

I'm really just trying to replace Excel with a CLI program 😁

**Comment by saulpw** [comment]
Hi @rnkn, thanks for the suggestion!  This is not currently possible, but I've been thinking about extending the tsv loader such that column names that start with `=` become expression columns.  You'd have to manually put the `=` into the name before saving the first time, though they'd roundtrip after that.  In this scheme, both the expression and all computed values would be saved into the .tsv, but the computed values would be ignored on subsequent loads.

Of course, with VisiData in general, you can't have cell-based formulas; they all have to be by column.  So it couldn't be a general Excel-replacement, but assuming you can work within this constraint, we should be able to get something that works for this use case.  Excel is an awesome program but being able to work within the terminal is :heart:

**Comment by rnkn** [comment]
Omg @saulpw your website design is amazing...

I like your `=` idea. I was also thinking maybe expressions could be saved in a separate sheet file in the same directory, like `.visidata-expr.tsv` or something, and accessed similarly to the columns sheet. It's a more complicated approach but might be nicer for long expressions. Also maybe expressions from this external file could be referenced in multiple columns/sheets. Just spit-balling...

**Comment by saulpw** [comment]
I started implementing the tsv loader idea I mentioned last night, and realized that in addition to expressions you probably also will want column types, and column names that aren't just the formula, and probably other things as well.

So I was thinking, are you aware that VisiData can save off its cmdlogs and you can replay them?  This might be a reasonable solution for what you want.  You can make a .vd script (go to the cmdlog with `Shift+D` and then `Ctrl+S` to save it as a .vd file) and then replay with `vd -p foo.vd`.  It will open the files and replay all the actions to get you back to whatever useful starting point.  That way you can get it setup just how you like it, with no additional complexities in the data files.  And if you want to apply it across different sheets, you can even parameterize the .vd script from the command line.

Let me know if you think this might work for you, or if you need any help getting it working.  It's a pretty cool feature and we should have better documentation for it.

**Comment by anjakefala** [comment]
A link to our documentation, with a demo of save/replay, is here =) http://visidata.org/docs/save-restore/

I definitely need to add information on parametrisation to it.

**Comment by rnkn** [comment]
This is awesome. Thanks for the heads up, I'll dive into this soon!

**Comment by saulpw** [comment]
Closing for now, as replay should be a sufficient and also a more flexible mechanism.
