### ISSUE TITLE
Links in HTML tables

### ISSUE THREAD

**Issue by am-zed** [saulpw/visidata#278]
Link names in HTML tables are not always useful and a way to toggle between hrefs and names would be handy.

Example: 
Links to "hosts" files from this github page are the info that makes sense instead of "link" and "raw" names:
$ vd -f html https://github.com/StevenBlack/hosts

Sample table; "Home page", "Raw hosts" and "Issues" are not useful here unless links themselves can be viewed:

|Host file source | Description | Home page | Raw hosts | Update frequency | License | Issues|
|---|---|---|---|---|---|---|
|Steven Black's ad-…| Additional sketch …| link | raw | occasionally | MIT | issues|
|Malware Domain List| Malware Domain Lis…| link | raw | weekly | 'can be used for f…| issues|
|add.Dead | Dead sites based o…| link | raw | occasionally | GPLv3+ | issues|
|add.Spam | Spam sites based o…| link | raw | occasionally | GPLv3+ | issues|
...

**Comment by saulpw** [comment]
Thanks for the suggestion, @am-zed!  This is in develop branch now, slated to be released in v2.-1.  If you have a chance to try it out, let me know how it works for you.
