### ISSUE TITLE
Plot timestamp with time as x, and float as y

### ISSUE THREAD

**Issue by Znarkus** [saulpw/visidata#281]
Is there any way to make the plot graph show timestamp with time? Not only date
Looking at the readme, I can only see the command line argument `disp_date_fmt`. But there might be a way in the UI?

<img width="1657" alt="Screenshot 2019-05-09 at 11 27 15" src="https://user-images.githubusercontent.com/168042/57444633-dea7cd80-7250-11e9-92d7-1f4b41181e81.png">
<img width="1657" alt="Screenshot 2019-05-09 at 11 27 18" src="https://user-images.githubusercontent.com/168042/57444634-df406400-7250-11e9-9e6e-d9fabaa76cf9.png">

**Comment by saulpw** [comment]
Hi @Znarkus, you can set the `disp_date_fmt` option from t he `O`ptions sheet within VisiData, which will set it globally, or in the Sheet-specific options sheet (with `zO`).  Alternatively, you can set the format for a single date column from the `C`olumns sheet; edit the `fmtstr` column to the strftime format string you'd like displayed.  That should change the display format on the sheet itself in that column and then also reflect that format to the graph axis.

Let me know if you have any issues getting this to work.

**Comment by Znarkus** [comment]
Thank you!
