### ISSUE TITLE
Select starting table in postgres from command-line

### ISSUE THREAD

**Issue by bknowles** [saulpw/visidata#282]
Related to #214 , I'd like to be able to specify a starting table when opening a particular postgres database.  The database I'm trying to work with has dozens of tables, some of which have millions of rows.  So, it takes so long to list all the tables and how many rows are in each table that the database query times out and I can't ever select the particular table that I want to open inside of the database.

Note that Postico doesn't have any problems with opening the database and getting a list of tables, but at the top level it doesn't really need to know about how many rows are in each table.  So, I know I can get a list of tables quickly, and that would at least let me specify in advance from the command line which particular table I want to open with visidata.

Please let me know if you want to see any examples of the kind of thing I'm looking for.

**Comment by saulpw** [comment]
Thanks for the bug report, @bknowles. I thought `COUNT(*)` would be a fast operation, and it's weird that the queries are taking so long.  Would you be able to check out the source code, and comment out the nrows column?  https://github.com/saulpw/visidata/blob/stable/visidata/loaders/postgres.py#L73
We still want to provide a generic way to open straight to a particular sheet, but that might be a short-term workaround.  Let me know if it works, and we might provide an option to disable it.

**Comment by bknowles** [comment]
@saulpw -- I did a git clone on the repo at https://github.com/saulpw/visidata.git, made your suggested one line change, and then did a "pip3 install ." in the visidata directory.

I can confirm that by omitting the count operation, we can load the list of tables almost instantaneously, and then I can select the table in question and pull up the contents.

So, this seems like a good solution to me!

**Comment by bknowles** [comment]
Note that, in our case, this database has 41 tables, and several of those tables have several million rows.  So, doing a count of the number of rows in each table will take quite a while.  And doing all those count operations in parallel in multiple asynchronous threads will probably make that something close to 41 times worse.

Fortunately, this is just a read replica server and no one else is using it right now.

**Comment by saulpw** [comment]
Thanks for running that experiment, @bknowles, and glad it will work for you.  Though, a database really should not require a linear scan to count the number of rows in a table.  I'm wondering if it doesn't have more to do with the number of concurrent threads as you suggest, maybe some kind of locking contention.  If you are able, it would be great to try the same test but with 41 tables that each have only a few hundred rows.  If that is slow, we can throttle the number of concurrent threads vd can have (probably a good idea anyway).  But if it turns out that the number of rows really does impact `COUNT(*)`, we should look into that, because someone must be doing something wrong.

**Comment by bknowles** [comment]
Let me see if I can find a lower lifecycle database that has roughly the same number of tables, but with much less data.

**Comment by aistellar** [comment]
> Thanks for running that experiment, @bknowles, and glad it will work for you. Though, a database really should not require a linear scan to count the number of rows in a table. I'm wondering if it doesn't have more to do with the number of concurrent threads as you suggest, maybe some kind of locking contention. If you are able, it would be great to try the same test but with 41 tables that each have only a few hundred rows. If that is slow, we can throttle the number of concurrent threads vd can have (probably a good idea anyway). But if it turns out that the number of rows really does impact `COUNT(*)`, we should look into that, because someone must be doing something wrong.

Slow COUNT(*) is a fundamental limitation of transactional databases. MySQL with InnoDB storage engine also suffers from the same issue.
https://wiki.postgresql.org/wiki/Count_estimate
https://wiki.postgresql.org/wiki/Why_PostgreSQL_Instead_of_MySQL:_Comparing_Reliability_and_Speed_in_2007#Counting_rows_in_a_table

So the current visidata postgres data source design is just not usable for any sufficiently large database.

I think a probably more productive integration of visidata and postgresql is to use visidata as a psql pager (See https://github.com/okbob/pspg).
