### ISSUE TITLE
feature request: add global Enter to Frequency Table sheet

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#285]
Hi,
I use a lot Frequency Table, it's one of the great ideas of Visidata.

When I open it, very often I use enter to open sheet of source rows that are grouped in current cell. It would be fantastic to have `g+Enter` to open sheet of source rows that are grouped in selected cells.

Thank you

**Comment by anjakefala** [comment]
Thanks for the feature requests as always @aborruso 😊 

https://github.com/saulpw/visidata/commit/2c5719254927e546a822dbc879da42bca8388f35

We agree, that would be wonderful! And, we have that implemented already in `develop` =D

**Comment by aborruso** [comment]
as always you are great!

**Comment by anjakefala** [comment]
I love that we came up with the same command structure and functionality. 🙃 😊
