### ISSUE TITLE
how to set the characters for key columns separator and null value?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#289]
Hi,
I'm using Visidata inside Windows WSL.

The characters for key columns separator and for null value are not recognized.

How to set them?

Thank you

![image](https://user-images.githubusercontent.com/30607/58703181-1ca79580-83a8-11e9-80dd-fade54c828d7.png)

**Comment by anjakefala** [comment]
`disp_note_none` for the None cells and `disp_keycol_sep` for the key column separator. You can set them through the `OptionsSheet` (reload with `^R`) or through your `.visidatarc`. =)

**Comment by aborruso** [comment]
@anjakefala I have asked here because these not work.

It' a problem of Windows WSL default font. The solution is:

- Right click on the title bar
- Select Properties
- Go to the tab Font
- Select "Dejavu Sans Mono" in the Font section
- Click the OK
