### ISSUE TITLE
What's the display options colors specification?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#290]
Hi,
probably it's a stupid question, but I need to ask it.

When I read `color_selected_row  215 yellow`, what's this color specification? What is the color list (as a string) I can choose? What does the numeric code represent?

Thank you

**Comment by anjakefala** [comment]
Hi @aborruso! Not a stupid question at all.

`curses` comes with a [color palette](https://stackoverflow.com/questions/18551558/how-to-use-terminal-color-palette-with-curses). =) Each color should have a label and a number. There are also other sorts of formatting options like `reverse` and `bold`. For example, the current cursor row is `reverse`d. The current column is bolded.

If you press `Space`, followed by the longname `colors` that will take you to the ColorsSheet. You will see a number along with the associated color. Try playing with the `color_selected_row` parameter by swapping it with another number or color label. (Note that the RGB columns currently do not work in my terminal.)

In terms of what `215 yellow` means, I believe `215` is the preferred color for selected rows and the second color (yellow) is the fallback in case the first color is not available in the terminal.

**Comment by aborruso** [comment]
@anjakefala as usual thank you very much.

I think you should insert some note about it, in the documentation

**Comment by anjakefala** [comment]
Totally! We have dreams to. 👼 

![Screen Shot 2019-05-31 at 11 17 21 AM](https://user-images.githubusercontent.com/7489659/58715826-b0239b00-8395-11e9-951b-db205258763e.png)

Our documentation should be getting a revamp over the summer. We will have an updated ToC and procedure, so others can also add stuff to it.

**Comment by aborruso** [comment]
Ok, I will be there :)
