### ISSUE TITLE
feature request: enable spatialite in VisiData

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#291]
Hi,
[spatialite](https://www.gaia-gis.it/fossil/libspatialite/index) is IMHO one of the greatest geospatial open source project:  is an open source library intended to extend the SQLite core to support fully fledged Spatial SQL capabilities.
In a spatialite db, you have a special kind of field, in which you collect geometries (in example the coordinates of the hotels of your city)

To enable it in a python console these are the steps:

```python
import sqlite3
connection = sqlite3.connect('db_test.sqlite')
connection.enable_load_extension(True)
connection.load_extension('/usr/local/lib/mod_spatialite.so')
```

It would be great to have a parameter as `--spatialite="yes"` that enables it when I run `vd --spatialite="yes" db.sqlite'`. Probably this is simple.

But I have no idea on how to enable visidata to apply a geospatial spatialite function as `ST_Area()` to a record.

I'm writing this request almost like a dream, and to understand if it is madness or if it is feasible

**Comment by pigreco** [comment]
Wow, it would be nice to be able to use spatialite in visidate.

I imagine I can write St_Area () or St_length ()

Thanks for all!!!

**Comment by saulpw** [comment]
This is a great idea for a plugin.  I'm going to close this and add it to the roadmap in the plugins section.  Thanks for the suggestion!
