### ISSUE TITLE
[develop-branch] help-commands is showing null keystrokes

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#292]
The z^H command (help-commands) is broken in the develop branch it reports that bindkeys is not defined.
And the it show null for the keystrokes for all rows.

**Comment by anjakefala** [comment]
Hi @frosencrantz!

Thanks for reporting. 💯  It ended up being a missing import. I just pushed a fix https://github.com/saulpw/visidata/commit/0c9724532fb157f40c98ecfb1d4aba20d8c5f136

Something we should add to our issue documentation.... `Ctrl-E` (`error-recent`) shows the complete traceback for the most recent global exception. `zCtrl-E` (`error-cell`) shows the complete traceback for an error contained in the current cell. These would be helpful to share when documenting bugs like these. =) And may also be helpful to you in your personal debugging journeys.

**Comment by frosencrantz** [comment]
I didn't know that is what the error-* commands do, will use those.  Will you also add tests to automatically catch issues with the help-commands command?  Thanks for fixing it quickly.
