### ISSUE TITLE
[wishlist] Command cluster help

### ISSUE THREAD

**Issue by jtrakk** [saulpw/visidata#293]
Some commands go together in a logical group. I'd like to be able to pull up a visual help showing the bindings for those commands. It provides an easy way to use the commands that go together, while *teaching* me new commands I didn't know about, *and* what their bindings are.

For example, in Magit, I get help by pressing `?`, and it pulls up the Magit help menu at the bottom

![image](https://user-images.githubusercontent.com/43392409/58979932-091f7480-8784-11e9-8958-4ac617734618.png)

And to see the commit-related commands, I press `c` (indicated by the `c commit` in the first column).

That turns the bottom pane into the commit menu.

![image](https://user-images.githubusercontent.com/43392409/58980028-497ef280-8784-11e9-807d-205f691d59f0.png)

In Visidata, there are tons of commands I don't know, and I don't always look in the man page to find out what commands are available (or what their bindings are). I'd love to see menus for select, filter, pivot, and others.

**Comment by saulpw** [comment]
Thanks for the suggestion, @jtrakk, it's a really good idea.  I'm thinking we could use the upcoming split-window functionality and open a context-dependent commands sheet (like you can already get with `z Ctrl+H`) which includes the keybinding and a description for each command.  It would then go straight into insta-searching (see #286) the longname and the description columns (the longnames hopefully already organize the commands somewhat).  Up and Down would move the cursor between commands, and Enter would execute the command at the cursor.

What do you think, would that work?

**Comment by jtrakk** [comment]
The functionality you describe would definitely be helpful. But I don't think it gets at the command-group idea though. I'm thinking a sheet like 


|group|key|description|
| --- | --- | --- |
|filter|f|Filter the data on this sheet|
|pivot|p|Reshape the data on this sheet|
|meta|m|Visidata options|
|quit|q|Exit this menu|

Pressing `f` would switch to a table of all the filtering commands


|function|key|description|
| --- | --- | --- |
|delete-row|d|Delete the current row|
|delete-rows-like-this|D|Delete all rows matching this cell|
|filter-by-regex|r|Filter all rows by regex (interactive)|
|quit|q|Exit this menu|

Pressing `p` would show something helpful about the various ways to pivot the current sheet.

This help sheet would be in the bottom half of a split screen, with the main data sheet in the upper half.

**Comment by saulpw** [comment]
That does sound like it would be useful for newcomers, @jtrakk.  With the features mentioned above, and maybe a little extra sauce, we could provide a framework to make this pretty easy to create.  You seem to have a particular vision, would you be willing to figure out what groups make sense and how they should be laid out?  I've been using VisiData for too long and I can't seem to make features for newbies anymore :)

**Comment by jtrakk** [comment]
Happy to put some thought into it. Magit relies on the idea that different keys are available in each sub menu, and the help-popup changes to show the relevant keys. But visidata doesn't have different contexts - all the keys are always available in a flat "namespace". So two options:  

- the top-level menu provides a new set of bindings for selecting a themed group of commands, and then selecting that group would pull up the menu of keybindings that visidata already has. This is nice because it teaches me the normal visidata bindings while I'm using it.
- the top-level menu provides a new set of bindings for selecting a themed group of commands (same as above) but the Pivoting submenu provides a whole bunch more pivot-related options than are normally available, and with possibly different bindings. This is nice because it provides more pivoting functionality options and with more convenient bindings for the specialized task.

**Comment by geekscrapy** [comment]
An FYI, lnav does a good job of this as well: https://github.com/tstack/lnav

Can maybe take examples from there

**Comment by anjakefala** [comment]
This is not going to be done for 2.0, so wishlist'd for exploration later!

**Comment by geekscrapy** [comment]
This kind of simple popup would be a good start? https://github.com/prompt-toolkit/python-prompt-toolkit/raw/master/docs/images/ptpython.png

From: https://github.com/prompt-toolkit/python-prompt-toolkit

(UPDATE) - Think I read the post wrong :) but I do think this kind of popup may help in the intermediate term when entering a long command.

**Comment by geekscrapy** [comment]
> The functionality you describe would definitely be helpful. But I don't think it gets at the command-group idea though. I'm thinking a sheet like
> 
> group	key	description
> filter	f	Filter the data on this sheet
> pivot	p	Reshape the data on this sheet
> meta	m	Visidata options
> quit	q	Exit this menu
> Pressing `f` would switch to a table of all the filtering commands
> 
> function	key	description
> delete-row	d	Delete the current row
> delete-rows-like-this	D	Delete all rows matching this cell
> filter-by-regex	r	Filter all rows by regex (interactive)
> quit	q	Exit this menu
> Pressing `p` would show something helpful about the various ways to pivot the current sheet.
> 
> This help sheet would be in the bottom half of a split screen, with the main data sheet in the upper half.

This idea may also replace the ^H help page to a certain extent, and a byproduct of this would be that it would be dynamic/encompass additional plugin commands!
