### ISSUE TITLE
How to load .sqlite3 extension

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#295]
Hi,
I have read that in the next really great release will possible to load .sqlite3 extension.

How to do it??

I would like to try to load spatialite one (see #291).

Thank you

**Comment by saulpw** [comment]
You should be able to use `-f sqlite` in 1.5.2.  Does that work for you?

Also do you use IRC, @aborruso?  Some of us hang out on freenode:#visidata if you would like to join.

**Comment by aborruso** [comment]
@saulpw only to add a note after today chat.

Probably the best approach would be to have a special kind of sql column (your idea). These columns could be created using or updating a SQL query and not a python expression.

I'm adding a correlated thing, because I do not know if it has inside some idea useful for this goal: it's partially OT, it's a Jupyter kernel for PostgreSQL than enable you to SQL query inside a notebook cell.
In background there is sqlalchemy.

Thank you

**Comment by anjakefala** [comment]
Hi @aborruso! 

Did you find that your question was answered? Would you like to rename this issue or shall we close it?

**Comment by aborruso** [comment]
I'm closing, because I had read [here](https://github.com/saulpw/visidata/blob/f6b9032784ab8268de236a8a9668937c931d57b8/CHANGELOG.md) "add support for .sqlite3 extension", but I had misunderstood: I thought it was possible to load sqlite extensions https://www.sqlite.org/loadext.html

Thank you
