### ISSUE TITLE
An hello world example for "gz="

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#296]
Hi,
I know that `gz=` sets the value according to a Python iterator, it " sets current column for selected rows to the items in result of Python sequence expr".

I know that probably it's a stupid request, but I would like to have an example in the "'How to' recipes", with the use of `gz=`.

Because I suspect it can be very useful, but I didn't understand at all what it is for :)

Thank you

**Comment by saulpw** [comment]
I usually just do `gz=range(100000)` to number rows, to be honest.  But it would also be useful for example if you had a common list of something you wanted to fill rows with.  Like you could also put this in your `.visidatarc`:

```ordinals = '''primo secondo terzo quarto quinto sesto settimo ottavo nono decimo undicesimo dodicesimo tredicesimo quattordicesimo quindicesimo sedicesimo diciassettesimo diciottesimo diciannovesimo ventesimo ventunesimo ventiduesimo ventitreesimo ventiquattresimo venticinquesimo ventiseiesimo ventisettesimo ventottesimo ventinovesimo trentesimo'''.split()```

and then do `gz=ordinals` to fill in the selected rows.

**Comment by aborruso** [comment]
Thank you
