### ISSUE TITLE
Float conversion should ignore leading or trailing currency indicators

### ISSUE THREAD

**Issue by vbrown608** [saulpw/visidata#30]
For example, if a cell contains a dollar sign, it should be stripped and conversion to float should succeed.

**Comment by saulpw** [comment]
Add a currency type, and change '$' to currency.  Maybe use ~ for string, and ditch autodetect.

**Comment by saulpw** [comment]
Fixed with 12a6b0e28cacad5e776af474344e36dbda9dcee2.  This allows currency columns to be used in math operations.  Currency columns are printed with commas, although commas are not accepted input.  The currency indicator is dropped from the display.
