### ISSUE TITLE
How to go to next difference with --diff?

### ISSUE THREAD

**Issue by unhammer** [saulpw/visidata#303]
If I do `vd --diff foo.csv bar.csv`, how do I navigate to the next difference? I tried searching f1 for `diff` but nothing useful showed up.

```
$ vd --version
saul.pw/VisiData v1.5.2

```

**Comment by saulpw** [comment]
Hi @unhammer, unfortunately there's no easy way to do that.  The diff functionality is actually just a quick hack, a colorizer off the given base sheet (see [diff.py](https://github.com/saulpw/visidata/blob/stable/visidata/diff.py)).  I could see `vdiff` being a really great plugin, but it would have to be architected differently.  I'd be happy to explore what that might look like, if you (or anyone) is interested in driving the development.

**Comment by anjakefala** [comment]
This issue has been moved to the [maybe someday roadmap](https://github.com/saulpw/visidata/blob/develop/dev/ROADMAP-someday.md). If somebody wants to pick up the design for this functionality, reopen the issue and leave a message!

**Comment by unhammer** [comment]
In case it's useful to anyone, I have a little [wrapper](https://gist.github.com/unhammer/9497641f44634ae96c6509a2cfaae574) that first runs `diff -u`, to make it easier to get right at the differences.
