### ISSUE TITLE
[plugin request] shift selected rows to the left/right

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#306]
Sometimes data are not uniform, or sometimes I need to join two similar but not-quite-the-same tsv files (e.g. older and newer, or pre- and post-enriched version), where one of them has an extra column,or a column less. On top of that, I need to sort this new file to see and compare the two similar lines easily. 
What I would like to be able to do is select a few rows, go to a specific column, and shift the contents e.g. on the right of that column, one column to the left. That would allow me to align these rows with the rest of the dataset. 
Could something like this be implemented easily? 

illustration attached
![Screenshot from 2019-06-26 11-02-07](https://user-images.githubusercontent.com/1530259/60166784-15867280-9802-11e9-91ba-9f07f0619b92.png)

**Comment by saulpw** [comment]
Hi @sfranky, this one is tricky.  We could probably make a hacky plugin to do something like this, but in your specific case I wonder if you could load the tsv files separately and join using the `append` jointype, which matches columns by column name instead of position.  Would that do the trick, do you think?

**Comment by sfranky** [comment]
thanks for the reply!
the case i uploaded is mostly covered by the workaround you proposed, so
thanks for that..! however, sometimes i have bad csv files where this
problem exists within the same csv, so it would be ideal to be able to do
that. But I guess it's something very few people need, so don't worry about
it. i'm already gaining TONS of time by using visidata!!
