### ISSUE TITLE
Feature request: change the "text" type keyboard shortcut

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#310]
I think that all this kind of shortcut must be quick and ready for everyone.
The `~` is in the american layout, but in a lot of layouts you do not have it. It is uncomfortable to use `ALT+126`.

What about to change it simply in <kbd>t</kbd>

**Comment by saulpw** [comment]
`t` is used for "toggle selection", so not that one, but we could easily add another keybinding for layouts without `~`.  What is your keyboard layout?  (Could you take a picture?)  It seems like many layouts have `é` in the upper row, so you could add this to your .visidatarc:

`Sheet.bindkey('é', 'type-string')`

**Comment by aborruso** [comment]
You are right, I'm stupid: "t" is for toggle.

I have a [Italian layout](https://commons.wikimedia.org/wiki/File:Italian_Keyboard_layout.svg)
