### ISSUE TITLE
Problems loading plugins

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#311]
In the develop branch, I'm getting a stack trace from .visdatarc:
File “visidata/settings.py", line 246, in loadConfigFile
     exec(code, _globals or globals())
File "home/.visidatarc", line 2, in <module>
     import plugins.livesearch                                                                                                        
 ModuleNotFoundError: No module named 'plugins' 

I haven't tried to debug it.

**Comment by saulpw** [comment]
Ah, yes, you need to make a `home/.visidata/plugins/` directory and put `livesearch.py` into that.  Alternatively if you put it directly into `home/.visidata/`, you would use `import livesearch`.

**Comment by frosencrantz** [comment]
The plugin is in $HOME/.visidata/ and was loading without issue. It  looks like it broke after recent changes to settings.py.

**Comment by saulpw** [comment]
Should be fixed now, thanks for the report.
