### ISSUE TITLE
Provide a way to limit the maximum number of columns created by the fixed format

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#313]
The fixed input format does a good at job at splitting lines into columns.   Sometimes it overfits the data, and the last true column is split into multiple columns.   Many text tables generated for the terminal place irregular-length, space-filled data in the last column on the right (e.g commands or help text).  If there is a long line with spaces or a couple of long lines that happen to have spaces that coincidentally align, fixed format will generate extra unwanted columns.

Two workarounds are joining the columns from the columns table, or using the flag to limit the number of rows that fixed uses.   The --fixed-rows flag doesn't help with these ragged values.

**Comment by saulpw** [comment]
Hi @frosencrantz, thanks for filing this issue.  I think we maybe should add a loader option, `fixed_maxcols`, which allows you to specify the max number of columns manually.  Alternatively we could make it so that the number of column names in the header defines the max number of columns, but of course that wouldn't help if there are no headers.  Would `fixed_maxcols` be sufficient?  It's easy enough to add.

**Comment by frosencrantz** [comment]
Thank you. I haven't tried it, yet, but that sounds like it should fix the issue.

**Comment by frosencrantz** [comment]
HI @saulpw it looks liked fixed format is broken now. 

1.  If --fixed-maxcols is not passed no table is generated.  The screen is blank.
2. If maxcols is too low, the values at the end of the line are not combined into the last column but are truncated. In that case I would expect the values at the end to be part of the last column,

I can reproduce with the sample data
bin/vd -f fixed sample_data/countries

I'm using the head version of the develop branch.

**Comment by anjakefala** [comment]
I can see what is wrong in each case. I just pushed a temporary fix for case `1` https://github.com/saulpw/visidata/commit/bf205fc5a4f829f203e1e7236b0537320850d7e1. Now if --fixed-maxcols is not passed the entire table is generated as before.

I will re-open the issue for the second request. I consider it an extension of the feature request.

**Comment by anjakefala** [comment]
@saulpw pushed a fix for both. See ^.

**Comment by frosencrantz** [comment]
There is an issue with the values being truncated when the first row is shorter than the maximum cols.  If the first row has the maximum number of columns then it seems to work.

For the shrt files below the longs rows are truncated.  Even look at the case when --fixed-maxcols is 5, the 5th column is empty, which is broken.

Here is the example:
```shell
# Log first row, with increasing value for fixed-maxcols:
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=1 --header 0 -o long1.csv -
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=2 --header 0 -o long2.csv -
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=3 --header 0 -o long3.csv -
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=4 --header 0 -o long4.csv -
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=5 --header 0 -o long5.csv -
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=6 --header 0 -o long6.csv -
$ (echo a b c d e f ; echo 1 2 3 ) | bin/vd  -b -f fixed --fixed-maxcols=7 --header 0 -o long7.csv -

# short first row with increasing value for fixedmaxcols:
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=1 --header 0 -o shrt1.csv -
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=2 --header 0 -o shrt2.csv -
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=3 --header 0 -o shrt3.csv -
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=4 --header 0 -o shrt4.csv -
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=5 --header 0 -o shrt5.csv -
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=6 --header 0 -o shrt6.csv -
$ (echo a b c ; echo 1 2 3 4 5 6 ) | bin/vd  -b -f fixed --fixed-maxcols=7 --header 0 -o shrt7.csv -

$ grep "" *
long1.csv:a b c d e f
long1.csv:1 2 3
long2.csv:a,b c d e f
long2.csv:1,2 3
long3.csv:a,b,c d e f
long3.csv:1,2,3
long4.csv:a,b,c,d e f
long4.csv:1,2,3,
long5.csv:a,b,c,d,e f
long5.csv:1,2,3,,
long6.csv:a,b,c,d,e,f
long6.csv:1,2,3,,,
long7.csv:a,b,c,d,e,f
long7.csv:1,2,3,,,
shrt1.csv:a b c
shrt1.csv:1 2 3
shrt2.csv:a,b c
shrt2.csv:1,2 3
shrt3.csv:a,b,c
shrt3.csv:1,2,3
shrt4.csv:a,b,c,
shrt4.csv:1,2,3,
shrt5.csv:a,b,c,,
shrt5.csv:1,2,3,4,
shrt6.csv:a,b,c,,,
shrt6.csv:1,2,3,4,5,
shrt7.csv:a,b,c,,,
shrt7.csv:1,2,3,4,5,6
```

**Comment by frosencrantz** [comment]
I tried the latest version, for my simple test case it worked great.  Thank you, @saulpw and @anjakefala !
