### ISSUE TITLE
[docs] note that activated caps lock modifies shortcuts

### ISSUE THREAD

**Issue by pigreco** [saulpw/visidata#314]
`shift+c` = Columns Sheet
`shift+C` = column name regex

that is, if caps lock is activated, type <kbd>C</kbd> and not <kbd>Shift+c</kbd>

**Comment by anjakefala** [comment]
Hi @pigreco!

Thanks for commenting in our corner of the Internet. =) I am not sure if you are requesting an action to take place, and would like some clarification.

Is the issue that you are pointing out that the docs usually refer to commands as `Shift+C`? We have historically done that for clarity and aesthetics. I.e. `C` can possibly be ambiguous in places like the manpage, and we wanted the aesthetics of `Shift+C`olumns sheet. I *think* most users grokk it and I am hesitant to modify that.

Or is the issue that you think we should mention in the documentation that activated caps lock modifies shortcuts?

**Comment by pigreco** [comment]
>Or is the issue that you think we should mention in the documentation that activated caps lock modifies shortcuts?

Exact,
it would be a good idea to write it in the documentation.

Thanks for the great job

**Comment by anjakefala** [comment]
Hi @pigreco! I added a note to the manpage reference documentation that the commands are case-sensitive. ^^
