### ISSUE TITLE
Consider adding sum to the Describe Sheet

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#315]
The Describe Sheet `Shift+I` is a useful tool for getting an idea of what sort of data I'm dealing with in a sheet. But I find that when I load a sheet, there's almost always at least one column I want to sum. Usually I'll do this by selecting the column and then `z+sum`. I wish this was included on the describe sheet by default so that I could see all of the basic statistics I usually care about in one place.

Is there a reason sum isn't included?

**Comment by saulpw** [comment]
It's a good idea to include `sum`, @pigmonkey.  There are some details that make `sum` more difficult than the other aggregators, and the Describe Sheet is almost bursting at the seams anyway (we need a better way to support the current plethora of aggregators), but it's reasonable to include `sum` there for now.
