### ISSUE TITLE
unselect-rows on frequency table doesn't update source rows

### ISSUE THREAD

**Issue by cwarden** [saulpw/visidata#318]
Selecting rows in a frequency tables selects the corresponding rows in the source table, and `unselect-row` unselects the corresponding rows in the source table, but `unselect-rows` does not unselect the corresponding rows in the source table.

**Comment by saulpw** [comment]
Thanks for the report, @cwarden.  This was a good find, and caused me to tweak the selection API a bit to distinguish between `unselect(selectedRows)` and `clearSelected()`.
