### ISSUE TITLE
Canvas graph labels are truncated

### ISSUE THREAD

**Issue by nicwaller** [saulpw/visidata#319]
In canvas view, graph labels appear truncated if longer than 11 characters and this makes it challenging to visualize data with long key names.

### Expected Result
Graph labels should be rendered as wide as necessary to fit the entire text of the label. Or alternately, they should inherit the width of the column as it appears in table view.

### Actual Result
Graph labels are always truncated after 11 characters.

<img width="183" alt="Screen Shot 2019-07-23 at 08 50 32" src="https://user-images.githubusercontent.com/2850248/61726722-f73f6400-ad26-11e9-9f0a-cb1f479cb4f2.png">

### Steps to reproduce
```shell
echo -e "Key,Value\nAverylongname,0\nAmuchlongername,1" > sampledata.csv
```

```visidata command script
sheet	col	row	longname	input	keystrokes	comment
			open-file	sampledata.csv	o
sampledata	Key		key-col		!
sampledata	Value		type-int		#
sampledata	Value		plot-column		.
```

### Additional Details
`saul.pw/VisiData v1.5.2`

**Comment by saulpw** [comment]
Thanks for the excellent bug report, @nicwaller. Inheriting the column width was a good idea, and I tried to do it, but it's too complicated to find when drawing the legend.  So instead it now just fits the longest label.
