### ISSUE TITLE
Request for human-friendly .visidatarc template

### ISSUE THREAD

**Issue by mightymiff** [saulpw/visidata#322]
Great tool, loving it.

Might I suggest fleshing out an example of the .visidatarc file and placing it in a more accessible location in the documentation?  The current configuration error message does not help debug faulty syntax, and that syntax is--as far as I can tell--not readily accessible.

I'm pasting my current configuration (which took more than an hour of guess and check just to get working) below as an example:

```
options.clipboard_copy_cmd   = 'xclip -selection primary'
options.min_memory_mb        =  100
options.cmdlog_histfile      = '~/.visidata/history/%Y%m.vd'
options.disp_note_none       =  '⌀'                  #visible contents of a cell whose value is Nonedisp_truncator      …                      # indicator that the contents are only partially visible
options.disp_oddspace        =  '·'                  # displayable character for odd whitespace
options.disp_unprintable     =  '.'                  # substitute character for unprintables
options.disp_column_sep      =  '|'                  # separator between columns
options.disp_keycol_sep      =  '‖'                  # separator between key columns and rest of columns
options.disp_status_fmt      =  '{sheet.name}|'      # status line prefix
options.disp_lstatus_max     =  '0'                  # maximum length of left status line
options.disp_status_sep      =  '|'                  # separator between statuses
options.disp_edit_fill       =  '_'                  # edit field fill character
options.disp_more_left       =  '<'                  # header note indicating more columns to the left
options.disp_more_right      =  '>'                  # header note indicating more columns to the right
options.disp_error_val       =  '!'                  # displayed contents for computation exception
options.disp_ambig_width     =  '1'                  # width to use for unicode chars marked ambiguous
options.color_default        =  '60 mediumpurple4'   # the default color
options.color_default_hdr    =  '24 deepskyblue4 bold underline'     # color of the column headers
options.color_current_row    =  '64 chartreuse4'     # color of the cursor row
options.color_current_col    =  'red reverse'        # color of the cursor column
options.color_current_hdr    =  'red bold reverse underline'         # color of the header for the cursor column
options.color_column_sep     =  '130 darkorange3'    # color of column separators
options.color_key_col        =  'blue'               # color of key columns
options.color_hidden_col     =  '8'                  # color of hidden columns on metasheets
options.color_selected_row   =  '215 yellow'         # color of selected rows
options.color_keystrokes     =  'white'              # color of input keystrokes on status line
options.color_status         =  '145 grey69 bold'    # status line color
options.color_error          =  'red'                # error message color
options.color_warning        =  'yellow'             # warning message color
options.color_edit_cell      =  'normal'             # cell color to use when editing cell
options.disp_pending         =  '{PENDING}'          # string to display in pending cells
options.color_note_pending   =  'bold magenta'       # color of note in pending cells
options.color_note_type      =  '226 yellow'         # cell note for numeric types in anytype columns
options.disp_date_fmt        =  '%Y-%m-%d'           # default fmtstr to strftime for date values
options.color_change_pending =  'reverse yellow'     # color for file attributes pending modification
options.color_delete_pending =  'red'                # color for files pending delete
options.disp_histogram       =  '*'                  # histogram element character
options.disp_histolen        =  '50'                 # width of histogram column
options.color_working        =  'green'              # color of system running smoothly
options.disp_replay_play     =  '▶'                  # status indicator for active replay
options.disp_replay_pause    =  '‖'                  # status indicator for paused replay
options.color_status_replay  =  'green'              # color of replay status indicator
options.disp_pixel_random    =  'False'              # randomly choose attr from set of pixels instead of most common
options.color_graph_hidden   =  '238 blue'           # color of legend for hidden attribute
options.color_graph_selected =  'bold'               # color of selected graph points
options.color_graph_axis     =  'bold'               # color for graph axis labels
options.color_diff           =  'red'                # color of values different from --diff source
options.color_diff_add       =  'yellow'             # color of rows/columns added to --diff source   # displayable character for odd whitespace

globalCommand('gm', 'mm, _ = curses.mousemask(-1); status("mouse "+("ON" if mm else "OFF"))', 'enable mouse events')
globalCommand('zm', 'mm, _ = curses.mousemask(0); status("mouse "+("ON" if mm else "OFF"))', 'disable mouse events')
```

**Comment by anjakefala** [comment]
Hi @mightymiff! 

It brought me joy to see your .visidatarc. I love seeing alternative VisiData themes ^^ 

You are right that the documentation on it can be a lot clearer. I added a tag to add this and added it to my queue.

Alternatively, if you would like to take charge, contribute aspects of your sample, and write a small guide, I would be more than happy to show you where to place it.

**Comment by frosencrantz** [comment]
Yes, that looks very nice, @mightymiff!

@saulpw  or @anjakefala: 
Seeing it in that tabular format makes me wonder why doesn't visidata have a way to load options and/or key bindings via a data file (e.g csv or tsv file).  You could do themes that way.

**Comment by mightymiff** [comment]
Thanks @frosencrantz.  For the basic options, the current code input method is mostly fine by me (once I managed to figure it out), and maybe even for the average user so long as there is a template they can copy/paste and then tweak.  I'm actually pretty ecstatic it is so easy to specify all those colors so easily, because it is a lot more interesting for me than looking at an unhighlighted file and opens up all kinds of fun possibilties for tagging fields of interest that had never really occurred to me before.

Then again, the global method declaration is not so pretty, though I just started using VisiData this week, so I don't much have a need for them yet.  If there are loads more complicated configurations like that, however, you might be right about the convenience of a plain text input format.  

Thanks also to @anjakefala and your kind attentiveness.  As for making a contribution to the project in the form of documentation, I am neck deep in thesis research at the moment, so sadly don't have too many spare moments, though you are of course free to use anything I post in this space for what limited use or value it may be to the project.

I messed around with the configuration file accessible from within the program for a bit, but didn't really grok it very well/couldn't get it to work in the amount of time I was willing to spend to understand how it worked.

**Comment by saulpw** [comment]
Cool, glad you're enjoying the theme options, @mightymiff.  It's a small thing, but I wanted to point one thing out about the colors (we'll definitely be documenting this more thoroughly in the Book of VisiData):

```options.color_default        =  '60 mediumpurple4'   # the default color```

I think you're using `mediumpurple4` here as a readable tag for the color, which is a neat idea and I think we should adopt it.  But strictly speaking, what VisiData does to compute colors, is try to parse each part as a [color (red green yellow blue magenta cyan white, or a number if 256 colors available)](https://github.com/saulpw/visidata/blob/develop/visidata/color.py#L72) or [attribute (normal blink bold dim reverse standout underline)](https://github.com/saulpw/visidata/blob/develop/visidata/color.py#L76). A 256-color palette is not guaranteed, however, and in that case a color like `60` would not exist. In the default colors, the second term is a basic color, to be used as a fallback. But if the `60` is found, then it's used preferentially.  (Attributes however are always applied).

So in your case, I would probably use `mediumpurple4 60 magenta`, so if for some reason your curses setup knows about `mediumpurple4`, it can go ahead and use that, otherwise fall back to `60` in the 256-color palette, and in 16-color mode, use plain old `magenta` as a crude approximation of your design intent.

**Comment by mightymiff** [comment]
Haha, thanks for explaining @saulpw .  Your assumption is correct, and while it did occur to me sometime yesterday that that likely wasn't really how it worked, as it didn't seem to break anything, I stopped worrying about it, :).  In any case, I am glad to actually know how colors are parsed and to be able to configure my options correctly.

**Comment by saulpw** [comment]
This little Python script will generate a sample .visidatarc with all the defaults:

```
from visidata import options

for optname, val in sorted(options().items()):
    val = repr(val)
    helpstr = options._get(optname, 'global').helpstr
    print(f'options.{optname:25s} = {val:10s}  # {helpstr}')
```

**Comment by 9mm** [comment]
I know this is old but.. what is the command in visidatarc to default all columns to max width? like `g_` does?

**Comment by saulpw** [comment]
From [issue #1681](https://github.com/saulpw/visidata/issues/1681#issuecomment-1783689728):

```
@Sheet.after
def afterLoad(sheet):
    vd.queueCommand('resize-cols-max', sheet=sheet)
```

This is a common enough request that we'll probably turn it into an option at some point.  But the above code is what to put into visidatarc now to get VisiData to do anything you want after a sheet has loaded (in this case, running the `resize-cols-max` command).

**Comment by 9mm** [comment]
thanks!
