### ISSUE TITLE
Global tsv options and settings affect HelpSheet loading

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#323]
Seeing traceback from help.  I see it only when using the --delimiter flag. 

```
==> cell_err.txt <==
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/visidata/wrappers.py", line 95, in wrapply
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/visidata/column.py", line 168, in getValue
    return self.calcValue(row)
  File "/usr/lib/python3.6/site-packages/visidata/column.py", line 136, in calcValue
    return (self.getter)(self, row)
  File "/usr/lib/python3.6/site-packages/visidata/metasheets.py", line 83, in <lambda>
    Column('description', getter=lambda col,row: col.sheet.cmddict[(row.sheet, row.longname)].helpstr),
KeyError: ('Sheet', 'show-cursor')

==> last_err.txt <==
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/visidata/utils.py", line 76, in __getattr__
    return self[self._fields.index(k)]
ValueError: 'sheet' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/visidata/threads.py", line 191, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/visidata/metasheets.py", line 101, in reload
    self.cmddict[(cmdrow.sheet, cmdrow.longname)] = cmdrow
  File "/usr/lib/python3.6/site-packages/visidata/utils.py", line 78, in __getattr__
    raise AttributeError
AttributeError
```

Not seeing the traceback when run these ways:
```
bin/vd --csv-delimiter ,  long7.csv
bin/vd -f csv --csv-delimiter ,  long7.csv
bin/vd  -f tsv   long7.csv
```

Consistently getting the error this when running help (z^H) when run like this:
```
bin/vd -f tsv --delimiter ,  long7.csv
```

**Comment by saulpw** [comment]
Thanks for the bug report, @frosencrantz, that's a good one.  Should be fixed now.

**Comment by anjakefala** [comment]
Since this was such a good bug, I wanted to document what was happening.

VisiData tracks its built-in commands through a [commands.tsv](https://github.com/saulpw/visidata/blob/develop/visidata/commands.tsv) that gets packaged with it.

This commands.tsv is where the HelpSheet pulls the description for each command from. =) When you set the `--delimiter` option for tsvs, that was also being applied when commands.tsv was being loaded. Since it was a regular tsv, it was being loaded with the incorrect delimiter, and the `HelpSheet` was unable to parse out the description. 

The fix involved overriding the `delimiter` flag on the `HelpSheet` class such that it always opened commands.tsv with a `\t` delimiter.

**Comment by frosencrantz** [comment]
@saulpw Thank you for fixing the issue.  
@anjakefala thanks for the explanation, that helps.  The symptoms seemed unusual.

**Comment by frosencrantz** [comment]
There is also an issues with the --header flag.  If you use 0 or  2+.  For example,
```
vd -f fixed --header 0 -
```

If you need the stack trace, let me know.

If you have the flags on the command line, and then load additional files once visidata is running, will the delimiter, header, and other flags also apply?

**Comment by saulpw** [comment]
Yeah, I guess all of the tsv options are susceptible to this.  Thanks for reporting.

And yes, the command-line options affect future loads, unless overridden further on the options sheet.

**Comment by anjakefala** [comment]
We started work on implementing a system TsvSheet in this commit: https://github.com/saulpw/visidata/commit/7c5febb4068852e81c6a13991af9a878f0d33de4. 

I will add header.

**Comment by anjakefala** [comment]
Added the remaining ones above!

Please re-open the issue if you find any remaining options that should be set.

**Comment by frosencrantz** [comment]
Will do.  I mentioned on another issue help was recently broken, but appears to be working again.
