### ISSUE TITLE
tab completion of columns in python expression input

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#33]

**Comment by saulpw** [comment]
Tried implementing this today.  It can pretty easily be made to work to tab-complete the first (i.e. only) column name, but tab-completion would have to be reworked substantially to be token/parsing aware.  Punting to 2.0.

**Comment by cwbooth5** [comment]
Could you show me the spot in the code where I can capture and act on the tab key as input for this? I have an idea for this. I know how to access the column names but wasn't quite sure where to make the case for tabs as input in just this expression. Then I need to understand what prints words in the 'expr=' line so I can add these names in. I was thinking of starting it after just '=' for now.

Also, what's your go-to trick for inserting a breakpoint that actually redraws the screen nicely after each  pdb command?

**Comment by saulpw** [comment]
Hey @moronbros, thanks for giving this a try! [vdtui.py:2183](https://github.com/saulpw/visidata/blob/stable/visidata/vdtui.py#L2183) is where the completer func is called ultimately in the builtin line editor.  [vdtui.py:280](https://github.com/saulpw/visidata/blob/stable/visidata/vdtui.py#L280) is where the input() function is called to provide the new expr.  If you create a completerfunc(value, idx) and then pass it as the `completer` kwarg to that call to `input()`, that should do the trick.

As for breakpoint/redrawing, I have never actually used pdb with VisiData.  `^L` will redraw the screen, but I guess that doesn't help you if you're single-stepping.

**Comment by saulpw** [comment]
Thanks for kicking this into gear, @moronbros!  You are to credit/blame for having tab completion (of both filenames and Python expressions) in the upcoming v0.99 release.
