### ISSUE TITLE
Feature request: Add help table with --help output

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#330]
Requesting  a way to browse --help output as a Visidata table.  Either have a command that shows the help in a table like 'z^H' does for keys, or a way to have --help output in a table format that Visidata can read.

**Comment by saulpw** [comment]
Hi @frosencrantz.  The --help output is composed automatically from the internally declared options, which is also available on the Options Sheet via `Shift+O`.  Do you want something other than that?

**Comment by frosencrantz** [comment]
The Options Sheet includes values that are not possible to set from the command line, and the mapping to flag names (short&long) are not show in the Options Sheet.  

It does look like the options parsing library used allows a formatter to supplied to generate the output.  Not sure if that would allow for generating a csv version.

**Comment by saulpw** [comment]
See [this short Python script](https://github.com/saulpw/visidata/issues/322#issuecomment-554248742) to enumerate all options and their defaults and helpstrs.

**Comment by frosencrantz** [comment]
@saulpw Thanks this is useful, it took me while to understand that command line flags and options are the same.

One additional thing that would help me is if there was some context as to where each option is coming from.  For example tsv and csv each have their own delimiter options.  It would be useful to know where an option was defined.  Not sure how easy is to show that additional bit of information from that script.

**Comment by saulpw** [comment]
The location of the option definition isn't stored internally.  I use `git grep 'option(' | grep optname` when I want to see where an option is defined.  (`theme(` for `disp_' and `color_` options, but I think `theme()` will be deprecated for 2.0 anyway).

For loader-specific options we've tried to standardize on `ext_opt_name` where `ext` is the filetype, with `delimiter` and `row_delimiter` just being special and having an implicit `tsv_`.
