### ISSUE TITLE
[loader] Support for S3 paths

### ISSUE THREAD

**Issue by ajkerrigan** [saulpw/visidata#333]
Hi there, I've been using visidata for local files recently and loving it! Would you be open to having an S3 loader so objects could be opened using S3 paths directly?

I've done some local fiddling inspired by the http loader, and taking an optional extra dependency on [s3fs](https://github.com/dask/s3fs/). If this seems like something you'd actually want in the product I'd like to talk it through, get some feedback and try to help make it happen.

Thanks for a great tool!

**Comment by saulpw** [comment]
Hey @ajkerrigan-mdsol, an s3 transport/loader would be pretty great.  I would use it myself.  Have you been working with 1.5.2 or the develop branch?  You should be able to package it as a plugin, and we can add it to the plugins sheet that will be in 2.x.

**Comment by ajkerrigan** [comment]
Hey @saulpw, thanks for the reply! I was working off 1.5.2 (by accident really, I was just poking around before opening an issue and got carried away). Getting a plugin together sounds like the right call and I see some good examples there, thanks for the nudge :).

**Comment by saulpw** [comment]
For sure!  I'd love to help any way I can. We're on Freenode #visidata if you do the IRC thing, or you can email me at `vd@saul.pw` if you want to chat a different way.

**Comment by ajkerrigan** [comment]
Great! I've got a minimally viable plugin started at https://github.com/ajkerrigan/visidata-plugins, trying to follow cues from https://github.com/jsvine/visidata-plugins and deviate from the core VisiData bits as little as possible. I'll catch up with you through freenode/mail to chat :).

**Comment by saulpw** [comment]
This is great, @ajkerrigan!  We'll add it to our plugins.tsv whenever it's ready for wider distribution.
