### ISSUE TITLE
[develop] Joining columns in the ColumnSheet causes an exception

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#336]
**Joining columns in ColumnSheet cases traceback**

**Expected result**

Columns would be joined

**Actual result with screenshot**
Exception in cells of new column:
```
Traceback (most recent call last): 
   File "/usr/lib/python3.6/site-packages/visidata/wrappers.py", line 95, in wrapply 
     return func(*args, **kwargs) 
   File "/usr/lib/python3.6/site-packages/visidata/column.py", line 168, in getValue 
     return self.calcValue(row) 
   File "/usr/lib/python3.6/site-packages/visidata/metasheets.py", line 36, in calcValue 
     return srcCol.getDisplayValue(srcCol.sheet.cursorRow) 
 AttributeError: 'NoneType' object has no attribute 'cursorRow'                    
```
**Steps to reproduce with sample data and a .vd**
Select multiple rows in a ColumnSheet, and hit the '&' key

**Additional context**
develop branch

**Comment by anjakefala** [comment]
~~~
sheet   col     row     longname        input   keystrokes      comment
                        open-file       sample_data/sample.tsv  o
sample                  columns-sheet           C
sample_columns          キRep   select-row              s
sample_columns          キItem  select-row              s
sample_columns          キRep   join-cols               &
~~~

**Comment by anjakefala** [comment]
[sample_columns.vd](https://github.com/saulpw/visidata/files/3518665/sample_columns.txt)

**Comment by anjakefala** [comment]
Thanks for the bug report. =)

**Comment by saulpw** [comment]
should be fixed now.

Note that the default `&` keybinding may be removed, since we've assigned it otherwise to `join-sheets-top2` on all sheets, and it seems important to be consistent.  So you may have to Space + `join-cols` in the future.
