### ISSUE TITLE
VisiData v2.-1dev - Range binning for numeric columns: how to use it?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#337]
Hi,
I have added `options.numeric_binning = "True"` to my config file.

Then I have opened a csv file, set a the field type to floating for a field and then I launched `SHIFT + i` to open frequency table.

But I do not understand where I should see the binning output?

Thank you

![image](https://user-images.githubusercontent.com/30607/63427412-5c18d780-c415-11e9-9f06-94c4beeedecd.png)

**Comment by anjakefala** [comment]
Hi @aborruso =)

You are right about setting `options.numeric_binning="True"` in your `~/.visidatarc`. 

Then set a column to any of the numeric types (int, float, currency, or date) and then press `shift+F` or `shift+W` on that column. Numeric binning is supported for frequency tables or pivot. :blush:

**Comment by anjakefala** [comment]
This has more info on frequency tables: https://jsvine.github.io/intro-to-visidata/basics/summarizing-data/

**Comment by aborruso** [comment]
Hi @anjakefala 

> You are right about setting `options.numeric_binning="True"` in your `~/.visidatarc`.
> 
> Then set a column to any of the numeric types (int, float, currency, or date) and then press `shift+F` or `shift+W` on that column. Numeric binning is supported for frequency tables or pivot. 😊

I know all above, but probably I was drunked _)

I do not why I have used `shift + i` and not `shift + f`.

As usual, thank you

**Comment by anjakefala** [comment]
```
I know all above, but probably I was drunked _)
```

lolol xD

I knee-jerk over-write in issues. 

Enjoy!
