### ISSUE TITLE
[develop] Alt+<s> doesn't do anything

### ISSUE THREAD

**Issue by Mikee-3000** [saulpw/visidata#338]
**Small description**
Opened 2 CSVs and tried to switch between them using Alt+

**Expected result**
Alt+1 should change to sheet 1, Alt+2 to sheet 2

**Actual result with screenshot**
Nothing happened. Stack trace is empty ("no error") 
![vd](https://user-images.githubusercontent.com/13318998/63546039-b488cb80-c520-11e9-8c08-1e750fddb38c.gif)

**Steps to reproduce with sample data and a .vd**
Open 2 sheets, try to switch between them with Alt+
Command log:
```
sheet	col	row	longname	input	keystrokes	comment
			open-file	sh1.csv	o	
			open-file	sh2.csv	o	
sh2			sheets-stack		S	
sheets		quit-sheet		q	
```

**Additional context**
Version 2.-1dev on PopOS 19.04 and Manjaro

**Comment by saulpw** [comment]
Try `Esc 1`.  What terminal and/or window manager are you using?  If you look at the lower right, `Alt+1` isn't showing up at all, so the Alt sequence is being intercepted before it gets to the terminal.

**Comment by Mikee-3000** [comment]
You're right - this is Tilix, I didn't know that Alt+num changes open sessions. Alt+num works in Terminator, and Esc+num works in Tilix. Case closed, I hope I didn't waste too much of your time.

**Comment by saulpw** [comment]
Not at all!  It reminds us that we have to document the Alt/Esc thing more thoroughly, since Alt isn't passed through to every terminal.  Keep em coming :)
