### ISSUE TITLE
[develop] undo - redo doesn't go back to the same state

### ISSUE THREAD

**Issue by Mikee-3000** [saulpw/visidata#339]
**Small description**
Opened a sheet, added a row, edited the cell [1:2]. 2 times Shift+U undid both steps. Consequent Shift+r added the row back, but the edited cell was now [2:2]

**Expected result**
The edited cell was meant to be [1:2]

**Actual result with screenshot**
![vd_redo](https://user-images.githubusercontent.com/13318998/63547924-19debb80-c525-11e9-837d-a59f700ccb7e.gif)

**Steps to reproduce with sample data and a .vd**
Open a simple sheet with a row and 3 cells. Add arow. Enter a number into the first cell of the second row. Press Shift+U twice to undo all edits. Press Shift+R twice for redo.

```
sheet	col	row	longname	input	keystrokes	comment
			open-file	sh1.csv	o	
sh1		0	add-row		a	
sh1	2	1	edit-cell	2	e	
```

**Additional context**
VD: 2.-1dev, OS: Linux

**Comment by saulpw** [comment]
Thanks for this report, @Mikee-3000.  Undo/redo needs a bit of work clearly :)

**Comment by saulpw** [comment]
Nice find!  It turned out only to happen with an action on the first row.  Should be fixed now.
