### ISSUE TITLE
Include jsvine's vdtabulate in the plugins list.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#341]
Looks like vdtabulate is missing:
    https://github.com/jsvine/visidata-plugins/blob/master/plugins/vdtabulate.py

**Comment by anjakefala** [comment]
Thanks for bringing this to my attention!

I added it. If you find another that is missing, you are welcome to add it to plugins/plugins.tsv, and make a PR. =)

**Comment by frosencrantz** [comment]
Yes, that would have been better.  When I started writing the issue, I thought I was looking at a repo of aborruso's plugins, and would need to request permission.  Then realized that these were jsvine's plugins.
