### ISSUE TITLE
Add support for displaying cursor row/column numbers at bottom right?

### ISSUE THREAD

**Issue by khughitt** [saulpw/visidata#343]
**Small description**

Would it be possible to add an option to toggle the current row/column number (according to the position of the cursor/cell in focus) at the bottom right of the screen?

It would be useful to provide some context with respect to where in the document you currently are.

Something as simple as the "<row>:<col>" section in vim would do the trick. One could imagine getting a bit fancier and modifying the color or brightness of each number based on the relative position with a sheet.

Another possible extension would be to provide an option to also include the relative position of each as a percentage of the total # rows / # columns.

**Expected result**

- key could be bound to toggle row/column visibility
- visidata could be configured to show the row/column numbers by default.

**Comment by saulpw** [comment]
Do you know about `Ctrl+G`, which shows the current row and col position?  The formatting could be improved but I think it gets you the information you want.

If you want to have it always onscreen, you can add it to the left status (the right status isn't as configurable yet) with a small bit of code in your .visidatarc:

```options.disp_status_fmt = '({sheet.cursorRowIndex},{sheet.cursorColIndex}) ' + options.disp_status_fmt```

You can of course format it however you want, or replace it entirely.

If you want it to be percentages, you could provide some simpler helper properties also, and then use those:

```
@Sheet.property
def cursorRowPct(sheet):
    return sheet.cursorRowIndex*100//sheet.nRows if sheet.nRows else 0

@Sheet.property
def cursorColPct(sheet):
    return sheet.cursorVisibleColIndex*100//sheet.nVisibleCols if sheet.nVisibleCols else 0

options.disp_status_fmt = '({sheet.cursorRowPct}%,{sheet.cursorColPct}%) ' + options.disp_status_fmt
```

You can also add a command to toggle it:

```
Sheet.addCommand('b', 'toggle-sheetpos', 'toggleStatus()')

def toggleStatus():
    global oldfmt
    if 'cursorRow' not in options.disp_status_fmt:
        oldfmt = options.disp_status_fmt
        options.disp_status_fmt = '({sheet.cursorRowIndex},{sheet.cursorColIndex}) ' + options.disp_status_fmt
    else:
        options.disp_status_fmt = oldfmt
```

It should be easier to 'unset' an option; we'll look at that for the 2.0 API, along with possibly making the right status more configurable.

**Comment by khughitt** [comment]
I was not aware of that! I did try searching the docs, but didn't come across that command.

Thanks for sharing that, and for the configuration suggestions! Those are all quite useful.

**Comment by saulpw** [comment]
Now there is an `options.disp_rstatus_fmt` that you can configure similarly for the right-side status bar.
