### ISSUE TITLE
TSV file with column name "length" causes TypeError

### ISSUE THREAD

**Issue by suhrig** [saulpw/visidata#344]
**Small description**
Files in TSV format containing a column named `length` cannot be loaded.

**Expected result**
See content of TSV file.

**Actual result with screenshot**
An empty file is shown. In the footer line it says:
```
TypeError: 'property' object is not callable
```

**Steps to reproduce with sample data and a .vd**
Create a file named `test.tsv` with this content:
```
length
1
```
Then, try to open it:
```
vd test.tsv
```

**Additional context**
version 1.5.2

**Comment by saulpw** [comment]
Hi @suhrig, thanks for the bug report.  This is a really good one, and I'm surprised we hadn't found it before! I'll look into it sometime soon, and hopefully get it fixed for the next 2.x release candidate.
