### ISSUE TITLE
Add support for styling columns based on type?

### ISSUE THREAD

**Issue by khughitt** [saulpw/visidata#348]
**Small description**

It would be great to be able to specify type-specific styles (color, and perhaps bold/italics/oblique) to be applied to columns, based on the column type.

- For numeric values, different colors/styles could be used for negative/zero/positive values.
- For categorical columns, a color palette (or gradient to be used to generate such a palette) could be used.
- Another possibility would be to assign color gradients to numeric columns.

This would be useful to allow one to quickly understand the contents of various columns, and to get a sense for the distribution of values in each column.

Going one step further, one could even imagine applying the same colorschemes used for values in a color to plots generated from those columns.

**Comment by saulpw** [comment]
You should be able to do most of these with colorizers:
```
theme('color_negative', 'red', 'color of negative numbers')
Sheet.colorizers += [ColumnColorizer(2, 'color_negative', lambda s,c,r,v: c and v is not None and isinstance(v.value, (int,float)) and int(v.value) < 0)]
```

Edit: fixed colorizer.

**Comment by khughitt** [comment]
Very cool! I will give this a shot as well and let you know if I have any insights as to where it's broken.
