### ISSUE TITLE
Link to screenshots broken in documentation

### ISSUE THREAD

**Issue by KPLauritzen** [saulpw/visidata#35]
On https://visidata.readthedocs.io/en/stable/screen-layout/

There are 2 links to https://visidata.readthedocs.io/en/stable/visidata-interface.png, which I guess should be located at visidata/docs/visidata-interface.png in the github repo.

**Comment by saulpw** [comment]
Fixed now (link also moved to http://visidata.readthedocs.io/en/stable/dev-cursors.html)
