### ISSUE TITLE
Failure reading stdin (piping to vd)

### ISSUE THREAD

**Issue by ajkerrigan** [saulpw/visidata#354]
**Small description**
In `v2.-1` I was able to pipe command output to `vd` and get a sheet. With the current develop branch (37acde0bb9a0b758d664341c835b4a13de0a2a08), I get no data.

**Expected result**
Piping something like a directory list to VisiData, I expect to see a sheet with the data:

```ls -l | vd -f fixed```

**Actual result with screenshot**
I get no error, but vd stops after showing:

```- does not exist, creating new sheet```

**Steps to reproduce with sample data and a .vd**
This small test script should exit with 0 if things are working, and 1 otherwise. Using it with `git bisect` suggests the issue traces back to 4f7f82cf4f1d4d278c51a9bfc00ad3514b69b8ef:

```bash
#!/bin/bash
VALUE=$(echo "hi" | ./bin/vd -bo -)
[[ "$VALUE" == "hi" ]] && exit 0
exit 1
```

**Comment by saulpw** [comment]
A model bug report, @ajkerrigan!  concise and informative, which made it easy to fix.  Should be fixed in 2.-2.
