### ISSUE TITLE
Feature request: add field type column to Describe Sheet

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#356]
Hi,
it vould be great to have column type field (text, integer) in Describe Sheet sheet.

![image](https://user-images.githubusercontent.com/30607/64763206-d84b9a00-d53f-11e9-8d05-9ba79c8e5ce9.png)

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, thanks for the suggestion.

If all you want is a 'type' column in a running session, you can copy and paste it from the ColumnsSheet's columns sheet onto the describe sheet.  Note how the rowtype in the lower right for both sheets is `columns`.  So, from the DescribeSheet, press Shift+C twice, then go to the `type` row, `y`ank it to the clipboard, `q`uit back to ColumnsSheet, and then `p`aste it there.  Then `q`uit back to the DescribeSheet and you should now have a type column on it.

If you want to do this by default, you can add this to your .visidatarc:

```DescribeSheet.columns[2:2] = [ColumnEnum('type', globals(), default=anytype)]```

I feel like the DescribeSheet is pretty crowded already, though.  What is it you really want to do?  To change them in bulk, there are already the e.g. `g#` commands to set the type of the selected columns.  Is there something else you'd like to do?

**Comment by aborruso** [comment]
> I feel like the DescribeSheet is pretty crowded already, though. What is it you really want to do?

@saulpw thank you very much. I love the describe sheet and I think that to complete the description it would be very useful to have also field type.

As you have in [xsv stats](https://github.com/BurntSushi/xsv/).


```
+-----------------------+---------+-----------+---------------------------------+--------------------------------------+------------+------------+------------+-------------------+----------+------+-------------+
| field                 | type    | sum       | min                             | max                                  | min_length | max_length | mean       | stddev            | median   | mode | cardinality |
+-----------------------+---------+-----------+---------------------------------+--------------------------------------+------------+------------+------------+-------------------+----------+------+-------------+
| id                    | Integer | 192754407 | 37715788                        | 39887089                             | 8          | 8          | 38550881.4 | 836432.5764532606 | 38188171 | N/A  | 5           |
| tipo_veicolo          | Unicode | -         | A                               | A                                    | 1          | 1          | -          | -                 | -        | A    | 1           |
| destinazione          | Unicode | -         | AUTOCARRO PER TRASPORTO DI COSE | AUTOVETTURA PER TRASPORTO DI PERSONE | 0          | 36         | -          | -                 | -        | N/A  | 3           |
| sesso                 | Unicode | -         | F                               | M                                    | 1          | 1          | -          | -                 | -        | M    | 2           |
| marca                 | Unicode | -         | AUDI                            | MAN                                  | 0          | 16         | -          | -                 | -        | N/A  | 5           |
| cilindrata            | Float   | 26847     | 1108                            | 13798                                | 0          | 8          | 6711.75    | 5356.208284551675 | 5970.5   | N/A  | 5           |
| kw                    | Integer | 637       | 40                              | 235                                  | 2          | 3          | 127.4      | 74.20673823851847 | 105      | N/A  | 5           |
| data_immatricolazione | Unicode | -         | 1977-01-01 00:00:00             | 2015-07-20 00:00:00                  | 19         | 19         | -          | -                 | -        | N/A  | 5           |
+-----------------------+---------+-----------+---------------------------------+--------------------------------------+------------+------------+------------+-------------------+----------+------+-------------+
```

**Comment by saulpw** [comment]
I've added this as a hidden column by default.  Press `gv` to show all hidden columns, and et voila!  Thanks for the suggestion.
