### ISSUE TITLE
cannot import name 'asyncsingle' error

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#357]
Hi,
using saul.pw/VisiData v1.5.2, installed via pip (`python3 -m pip install --user visidata`), I have at start this error:

```
ImportError: cannot import name 'asyncsingle' from 'visidata' (/home/aborruso/.1oca1/lib/python3.7/site-packages/visidata/_init_.py)
```

How to solve it?

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, `asyncsingle` was added after 1.5.2.  I'm guessing you have either some code in your visidatarc that's trying to import it, or a plugin for a newer version?

**Comment by aborruso** [comment]
@saulpw I have commented `import plugins.livesearch` and it works.

Thank you
