### ISSUE TITLE
[feature request] Enable plugins to add to vdobj

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#359]
vdobj is a core module in VisiData. Currently, it is initialised [before plugins and visidatarc are loaded](https://github.com/saulpw/visidata/blob/develop/visidata/__init__.py#L119). This means that there is no way for plugins to expand vdobj.

This should be adjusted.

**Comment by saulpw** [comment]
`VisiData.init()` is not useful and will be deprecated; use `@VisiData.lazy_property` to create the value as needed (and it will be cached thereafter).
