### ISSUE TITLE
Discussion: should undo apply to row selection commands?

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#362]
The general rule, is that a command is undoable if the data would be changed when saved to a new output.  So changing the width of a column can't be undone, because it is purely cosmetic and does not affect saving (except markdown format, but it should not change the data at all).  But setting the width to zero is undoable, because it hides the column and therefore removes it from the list of columns to be saved at all.

This criteria has a bit of nuance, as illustrated above, but I think overall is a pretty good distinction.  However, I'm torn as to whether undo should apply to selection commands.  On the one hand, it might be nice sometimes to accumulate a collection of selected rows, and if a bulk regex select goes wrong, getting back to the previous collection is only a `Shift+U` away.  This was even one of the first suggested use cases for undo in #141. But it violates the general rule above, and I'm worried it might be confusing if the rule isn't hard and fast.  Also, I don't know of any other tools that would have undo apply to their concept of selections.

Does anyone have opinions one way or another?

**Comment by paulklemm** [comment]
Hey Saul, excited for Visidata 2.0🎉

I would expect the undo feature to apply on selections. I constantly screw up selections and a quick way to undo this would be to just `Shift+U`. I agree, it gets a bit inconsistent, but I don't think it's that big of a problem.
