### ISSUE TITLE
SQLite handler fails with 'sqlite3.OperationalError' on selecting tables with keyword names

### ISSUE THREAD

**Issue by shym** [saulpw/visidata#369]
**Small description**
Using VisiData v1.5.2, I cannot visualise the content of a table named “table” or “select” (or, I imagine, other SQL keywords) in a SQLite database.
I wonder whether that could be a duplicate of #119 but I understood that issue as fixed quite some time ago, and the fix doesn’t seem to relate to this issue.

**Actual result with screenshot**

```
 Traceback (most recent call last):                                                           ‖
   File "/usr/lib/python3/dist-packages/visidata/vdtui.py", line 1115, in exec_command        ‖
     exec(cmd.execstr, vdglobals, LazyMap(self))                                              ‖
   File "<string>", line 1, in <module>                                                       ‖
   File "/usr/lib/python3/dist-packages/visidata/vdtui.py", line 961, in push                 ‖
     vs.reload()                                                                              ‖
   File "/usr/lib/python3/dist-packages/visidata/loaders/sqlite.py", line 24, in reload       ‖
     self.columns = self.getColumns(tblname)                                                  ‖
   File "/usr/lib/python3/dist-packages/visidata/loaders/sqlite.py", line 33, in getColumns   ‖
     for i, r in enumerate(self.conn.execute('PRAGMA TABLE_INFO(%s)' % tableName)):           ‖
 sqlite3.OperationalError: near "select": syntax error                                        ‖
```

Without surprise, in an interactive SQLite session I get:

```
sqlite> PRAGMA TABLE_INFO(table);
Error: near "table": syntax error
sqlite> PRAGMA TABLE_INFO("table");
[correct output]
```

**Steps to reproduce**

```sh
$ sqlite3 bug.db 'create table "table" ("col" text)'
$ vd bug.db
```
and select the table.

**Additional context**
VisiData v1.5.2, debian package 1.5.2-1

**Comment by saulpw** [comment]
Thanks for the quality bug report, @shym! Fixed in develop, will be in 2.0.

**Comment by shym** [comment]
Kudos, that was fast!
Looking at 1b27bb4a8a67328e5b2c7dd794cf4d9fa9754338, I’m wondering what would happen with a table name containing a `"` (which is admittedly looking for trouble but is accepted by sqlite when escaped as `""`).

**Comment by saulpw** [comment]
Hi @shym, that would certainly break it!  In general though I try not to fix speculative edge cases proactively; there are a near infinite number of possible issues and it's generally not worth the risk and complication for an issue that doesn't affect anyone.  That said, if you or anyone else wanted to create a sqlite db that exhibited this issue, and submit a PR that fixed it, we'd be happy to merge it in.
