### ISSUE TITLE
Handle over-large input files gracefully

### ISSUE THREAD

**Issue by DataBranner** [saulpw/visidata#37]
Attempting to open the NYC Open Data 311 dump (9.5Gb) this morning left my computer hanging after 34 minutes (13555788 records, or 88%, loaded).

It would be a good idea for the application to monitor changes in loading speed and warn User when there is likely to be trouble. 

I suggest User then be offered the option to abort cleanly, recording the details in the configuration file. It may be useful to know in future what size files are too large to be loaded, something the application could then look up in the config file and give User earlier warning of.

Handing over-large files the way database programs do, with fast data structures that maximize efficient disk-lookups, would be nice but I think perhaps overkill for this application at this time.

**Comment by saulpw** [comment]
This would be really great, and I'd love to solve this at the root, by e.g. constructing an on-disk index of the file offsets for each line and accessing the file through mmap().  @vbrown608 and I tried to implement this a few weeks ago, but it turns out to require substantially more work than originally estimated.  I've put it on the roadmap for something closer to a version 2.0.

**Comment by saulpw** [comment]
v0.96 added the option `min_memory_mb`, which if free memory falls below, will abort all async actions.  Defaults to 0 (disabled); 100 may be a reasonable value.  Add `options.min_memory_mb = 100` to `.visidatarc` to prevent running out-of-memory.

**Comment by CMCDragonkai** [comment]
Will there still be plans to add in lazy loading of large files? What about streaming similar to less?

**Comment by saulpw** [comment]
Yes, I'm planning for lazy loading in 1.2 or 1.3.  Streaming input already works; try doing e.g. `find / | vd` and it will launch immediately and add to the end as new results are found.  I've also made some loaders that never complete (like chat clients).  Streaming output (for instance as a filter pipe lline) does not work.

**Comment by CMCDragonkai** [comment]
If you're loading new pages, will old pages (that are not being viewed) be deallocated?

**Comment by saulpw** [comment]
Not automatically; sheets are 'pushed' onto the sheets list, and they stay until dropped.  `q` drops the current sheet, or you can go to the SheetsSheet and `d`elete a sheet from there.  Then the Python garbage collector deallocates at its discretion.
