### ISSUE TITLE
vd is a great tool - but can I somehow preset the screen height?

### ISSUE THREAD

**Issue by halloleo** [saulpw/visidata#372]
**Description**

I am paying around with visidata - and love it already. :-)

However I have *sometimes* trouble that it allocates more lines than aviable in my terminal emulater - whith the result that the top- line scrolls out of view.

Is there a way to specify via CLI options the number of lines `vd` should occupy?

**Comment by saulpw** [comment]
Hi @halloleo, glad you're enjoying it!  There's no way to do this from the CLI, but you could add this to your `.visidatarc`:

```
@VisiData.property
def windowHeight(vd):
    return 11

@BaseSheet.property
def windowHeight(sheet):
    return 11
```

and then it would only use 11 lines.  Not the easiest to update but if your windows are usually a particular height, maybe it will work for you.

**Comment by saulpw** [comment]
Now you can set `LINES` and/or `COLUMNS` envvars to manually indicate the number of lines/columns to use.  Does not seem to work well if set greater than the actual number of lines/columns.  But should work in your case, @halloleo.

**Comment by halloleo** [comment]
I tested it against the stable branch and it works! :-) Thanks a lot, @saulpw!

Only problem using env vars with standard names is that some terminal programs reset them on window resize, effectively overriding my choice. A variable VD_LINES would avoid this.

BTW, I tried the approach with the `.visidatarc` file, but then I get the message 

    AttributeError: type object 'VisiData' has no attribute 'property'
