### ISSUE TITLE
Expansions to PluginsSheet

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#373]
Requested by @saulpw

- [x] add a pydeps column, which is a space-delineated list of pypi dependencies, with pip3 friendly text (e.g. `requests==2.3.0 lxml`)
- [X] add a hash column, and add hash verification with downloads before loading them
- [X] add a vdplugindeps column, space-delineated list of plugin dependency urls

**Comment by saulpw** [comment]
`vdplugindeps` is present but not used currently.  closing this issue.
