### ISSUE TITLE
Progress with no length

### ISSUE THREAD

**Issue by layertwo** [saulpw/visidata#375]
Re: IRC discussion

There are cases where (particularly in vsplunk) where a progress percentage can't be known as data is streamed in without a total count.

This request is for a spinning progress indicator instead of the current percentage.

**Comment by saulpw** [comment]
With the latest commit to develop, if `progressTotal` is 0 then it doesn't display `0%` (though it will still show `processing...`).  If you want to use your own gerund in place of `processing`, you can use something like `Progress(gerund='fetching', total=0)` as a context manager.
