### ISSUE TITLE
Cells with embedded newlines display well but export badly

### ISSUE THREAD

**Issue by Mesibov** [saulpw/visidata#376]
VisiData v1.5.2

If a CSV is exported from a spreadsheet which contains newlines within cells, the CSV has broken records, with each of the lines from the "newline-embedded" cells starting a new CSV line. If this CSV is imported into VisiData, VisiData displays the broken lines as single lines - great!!

However, after saving the CSV from VisiData as a TSV, the new TSV does not save the displayed table with broken lines fixed, but has the same structure as the CSV, with the full number of broken lines.

I suggest this is a bug because "save" ("^s") is really just "convert", not "save as displayed".

I attach a small .txt which should be renamed .csv before opening in VisiData. One record (begins with "22177") has 2 cells containing embedded newlines.

[first10.txt](https://github.com/saulpw/visidata/files/3747286/first10.txt)

**Comment by anjakefala** [comment]
Hi @Mesibov!

Thanks for writing up an issue about this and ++ for providing sample data.

I can provide some context for what is happening. It was deliberately decided that embedded newlines hold meaning. In fact, in the newest version of VisiData (not yet released), users can press `v` to display those cells as multiple rows. I agree that that can result in broken files when saved like that, especially for tsvs.

We do have a `safety_first` option (https://github.com/saulpw/visidata/blob/stable/visidata/loaders/csv.py#L10) that cleans up csvs in exchange for a performance cost. For now, it erases Null characters. I can see adding "removing embedded newlines" to that and perhaps other csv cleaners.

@saulpw is afk for the next week or so, and ultimately he has the final design call. When he next comes online we can see how he thinks we should respond to this case. =)

**Comment by Mesibov** [comment]
@anjakefala Many thanks for thinking about cleaning up embedded newlines, it would be a great help. Another great help to us data workers would be for governments around the world to pass laws forbidding the use of CSVs (https://www.datafix.com.au/BASHing/2018-07-18.html).

**Comment by anjakefala** [comment]
> Another great help to us data workers would be for governments around the world to pass laws forbidding the use of CSVs (https://www.datafix.com.au/BASHing/2018-07-18.html).

:rofl:

**Comment by saulpw** [comment]
@anjakefala is exactly right.  With `safety_first`, the csv loader removes NUL characters, and the tsv saver translates newlines to `options.tsv_safe_newline`.  We should make them both act the same way (probably a union of both behaviors).  Thanks for pointing this out, @Mesibov!

**Comment by saulpw** [comment]
Savers should work consistently now, and `options.safety_first` will convert newlines and tabs to `options.tsv_safe_newline` and `options.tsv_safe_tab`, respectively.  @Mesibov, let us know if you have any more issues with saving edge cases like this.
