### ISSUE TITLE
vim editing a cell adds a trailing space, leaves the cell open upon saving

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#378]
I'm using 2.-1, but i think i remember the same behaviour in master visidata.

I press e to edit the cell, then ctrl-o to go into vim, edit the text, then save with :wq, and i get the cell still open (so i need to close), and there's also a whitespace character appended at the end.
Is there some way to configure that, if it's intended behaviour?
Thanks!

(edit: when you have to do a million of them, speed matters!!)

**Comment by saulpw** [comment]
I believe what you want is actually a vim option, `set noeol`: https://stackoverflow.com/questions/1050640/vim-disable-automatic-newline-at-end-of-file#16114535

Though interestingly, we should be already trimming that newline in `launchExternalEditorPath`.  So maybe there are multiple newlines in your case?

Also, for speed, you might want to try this, to avoid having to press `e` and `Enter`:

```
Sheet.addCommand('^O', 'sysedit-cell', 'cursorCol.setValues([cursorRow], launchExternalEditor(cursorValue))')
```

**Comment by sfranky** [comment]
Thanks for the provided command, that's perfect !!!

As for the newline, the `set noeol` doesn't seem to have an effect (although i see [noeol] in vim).
After exiting vim and getting back to the open-for-editing cell (btw is there also a way to turn that behaviour off, so that exiting vim gets back to a *closed* cell?), the dot is still there. 

I don't see multiple newlines, if i just save out of vim, and let the cell keep its newline and then save the tsv and open it in vim, i only see one newline.

**Comment by saulpw** [comment]
If you start from an open-for-editing cell, you should return to the same, in my design opinion.  There's also an issue with the implementation since input is modal (same issue why it's harder to Tab to the next cell from within input mode, and re-enter/stay in input modef).  The above command does what you want though anyway, right? 

Also you can change the above command to this:

```
Sheet.addCommand('^O', 'sysedit-cell', 'cursorCol.setValues([cursorRow], launchExternalEditor(cursorValue).rstrip("\n"))')
```

and that will strip all newlines off the end for you.

**Comment by sfranky** [comment]
yes, that makes sense you're absolutely right.
The first command does open directly, which is a great upgrade, but the second command doesn't anymore, I get this:
```
Traceback (most recent call last):
  File "/home/sfranky/.local/lib/python3.7/site-packages/visidata/basesheet.py", line 112, in exec_command
    code = compile(cmd.execstr, cmd.longname, 'exec')
  File "sysedit-cell", line 1
    cursorCol.setValues([cursorRow], launchExternalEditor(cursorValue).rstrip("
                                                                              ^
SyntaxError: EOL while scanning string literal
```
and also, if i instead go with e, ^o, like in the past, the `\n` is still there.

**Comment by saulpw** [comment]
Add an extra `\`.  (I didn't test this before sending it).

And yeah, this only changes the `Ctrl+O` from the sheet itself, not the one from within the line editor.

**Comment by sfranky** [comment]
It's perfect thanks very much !! (btw i hadn't noticed that after vim the command also exited out of the edit cell, THAT'S what you meant!!)
