### ISSUE TITLE
TypeError: 'classmethod' object is not callable

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#379]
My .visidatarc is fairly empty. Basically, it just imports the three plugins vddedupe, rownum, vdnormcol (which work last time i checked), and datetime.

If i add this line:
bindkey('0', 'go-leftmost')
I get this error (and of course the binding doesn't work):

```
Traceback (most recent call last):
  File "/home/sfranky/.local/lib/python3.7/site-packages/visidata/settings.py", line 257, in loadConfigFile
    exec(code, _globals or globals())
  File "/home/sfranky/.visidatarc", line 19, in <module>
    bindkey('0', 'go-leftmost')
TypeError: 'classmethod' object is not callable

```

I'm using version 2.-1.
Thanks!

**Comment by saulpw** [comment]
Hm, good catch, @sfranky!  There is a separate `bindkey` for classes and globally.  We'll fix the global one (which is broken), but in most cases you actually want to use the class-specific one:

`BaseSheet.bindkey('0', 'go-leftmost')`

because this would not be a useful binding without a sheet.

**Comment by sfranky** [comment]
excellent!! i thought i was going to get away also without using one :)
this is great !!
