### ISSUE TITLE
Link to keybinding descriptions from `vd -h`

### ISSUE THREAD

**Issue by pjvandehaar** [saulpw/visidata#38]
Could `vd -h` show the link <https://visidata.readthedocs.io/en/stable/user-guide/>?  After `pip3 install visidata` there's not a clear way to figure out keybindings except coming to the github page.

**Comment by saulpw** [comment]
When `vd` starts up, it shows both saul.pw/VisiData (which should go to a landing page where documentation is easily found), and "F1 or z? opens help" on the status line.  These could be added to `vd -h` also.  I'll merge the PR if one is submitted.

**Comment by pjvandehaar** [comment]
Huh, I don't know how I missed those, thanks.
