### ISSUE TITLE
[defermods] edits to derived sheet do not transfer to the source sheet without a commit

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#383]
If on a simple tsv file I select two rows, open a subsheet with " (double-quote), proceed to change the value of one of the cells (the cell gets coloured yellow), and then switch back to the main tsv file with ctrl-6, the value is not transferred there. However, if I save the subsheet with a random name and *then* go back to the main tsv, the change is now visible. 
[edit: tried it with a simple numerical 4x4 tsv file]

**Comment by anjakefala** [comment]
This bug has not been fixed, but I am not sure if there is going to be future development on trackmods. (It is a tricky plugin.)

Closing for now.
