### ISSUE TITLE
xlsx plugin produces bad column in [develop]

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#385]
**Small description**
When loading any xlsx file, the first column is comprised of  `[<number>]`s everywhere. In [v2.-1], the output is normal. 

**Additional context**
develop branch

**Comment by anjakefala** [comment]
Hey @sfranky! I was not able to reproduce this with the [sample xlsx](https://github.com/saulpw/visidata/blob/stable/sample_data/sample-sales-reps.xlsx). Can you give this data a try, and post a screenshot if you see the bug?

**Comment by anjakefala** [comment]
If you do not see the bug there, is it possible to point me to some sample data where you do? =)

**Comment by sfranky** [comment]
I see the same problem in the sample you sent. I tried disabling my ~/.visidatarc file, still the same!

![xlsx_column_bug](https://user-images.githubusercontent.com/1530259/68416601-127a9600-0195-11ea-8694-f036c6e8ce1b.png)

**Comment by anjakefala** [comment]
Excellent! What is your most recent commit?

**Comment by sfranky** [comment]
67c3f925

**Comment by anjakefala** [comment]
Please update to https://github.com/saulpw/visidata/commit/e1d62971a02d5fb53e78761e3ead573f9c4ffd0e. :blush:

**Comment by anjakefala** [comment]
There was a bug that was introduced with a partial upgrade of the xlsx loader to a new loader framework (I am working on the documentation for it atm). It got fixed in later commits.

**Comment by sfranky** [comment]
worked like a charm !! thanks !!
