### ISSUE TITLE
CSV file is sometimes truncated randomly when saved

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#388]
**Small description**
I have a CSV file of about 4800 rows. When I save it from vd, there's a roughly one in three chance that the file will be truncated and the last 100-2000 lines will be gone.

**Expected result**
Shouldn't lose data.

**Steps to reproduce with sample data and a .vd**
Here is a randomly generated CSV with 4866 lines: https://gist.githubusercontent.com/dbandstra/6e586c0d4fd3ccdacf85e3fd4d898a2a/raw/de8c734b15e7d2d2604586a7cbded2cec7309488/random.csv

Download it to disk, open it in `vd` and just save it again (ctrl-s, enter, y, enter). Quit. Check the file with `wc -l test.csv` to count the number of lines. Usually within 1 or 2 times doing this it's already missing lines (e.g. down to 4261 from 4866).

**Additional context**
Happens with v1.3, v1.5, and v2.-1dev, both on Ubuntu 18 and on a Mac.

**Comment by anjakefala** [comment]
VisiData definitely should *not* be doing that, and this will take utmost priority.

I have a guess for what might be happening, @dbandstra,

Something caught my eye in these instructions:
```
Download it to disk, open it in vd and just save it again (ctrl-s, enter, y, enter). Quit.
```

There is a progress indicator in the bottom right corner. If you are working with large files and you quit before they finish saving, the saved file would be truncated.

Can you please confirm for me if this is what is happening? Do you get truncated files even when the Progress indicator is confirmed to have finished?

**Comment by ghost** [comment]
I think that's what it is. I tried a bunch of times, waiting for the progress indicator, and it didn't get truncated. I never noticed the progress indicator before!

**Comment by anjakefala** [comment]
@dbandstra, awesome!  :blush: 

Thanks for posting an issue.  =)
