### ISSUE TITLE
Memory sheet

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#392]
Hi,
when I run `z+` to do a one-off calculation, I'm not able to copy (and then paste) the output.

If there is not a way to do it, what about to add the output in memory by default (a `CTRL+C`, a copy by default)?

Thank you

**Comment by anjakefala** [comment]
Hi @aborruso! 

I can tell you about some steps for copying the `z+` output.

`Ctrl+P` will take you to a **StatusSheet**. It is a history of all left statuses. You can interact with it using any of the VisiData copy commands. =)

**Comment by aborruso** [comment]
@anjakefala and what do you think to create also direct way to use it? I think it would be a useful feature

Thank you

**Comment by saulpw** [comment]
I think there should be a way to save a value on something like a 'memory' sheet, and then you can go there to `zY` (`syscopy-cell`) to the system clipboard, or give it a name so you could use it in other expressions (which would also solve #391). `show` commands would add it there by default.

I'll add this to the roadmap, as we're cleaning feature requests off the issues list.
