### ISSUE TITLE
Feature Request: Add gz^H command to get global help

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#393]
**Small description**
Add a gz^H command to provide a way to get full help of all table types.

**Expected result**
Help for all table types, sort of like loading commands.tsv.

**Additional context**
Per @saulpw  comment: https://github.com/saulpw/visidata/issues/329#issuecomment-548668046

**Comment by saulpw** [comment]
Thanks for the reminder, @frosencrantz.  I think this is a useful idea, and especially as we deprecate commands.tsv, it's good to have them in one place.

**Comment by frosencrantz** [comment]
Thank you, @saulpw . 

The name of the sheet ends up being the previous sheet plus a suffix of _commands.  Wondering if the name should be "help" or "help_all".

**Comment by saulpw** [comment]
Well it is a list of commands...what about `all_commands`?
