### ISSUE TITLE
Consider a list of community plugins

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#394]
I stumbled upon [jsvine's visidata-plugins](https://github.com/jsvine/visidata-plugins) accidentally, found them to be useful, and wondered what other useful things are out there.

It might be nice if the project had some kind of list of community plugins. This could be as simple as a list of links in the README that plugin authors could contribute to via a PR. Or, I see there is a GitHub Wiki for the project, so maybe that?

**Comment by saulpw** [comment]
We're working on this for 2.0.  There's a PluginsSheet (`open-plugins`, or from the VisiData main menu) and ability to install them from within VisiData itself.  You can see the current list of known plugins (may not be entirely complete right this second) at https://github.com/saulpw/visidata/blob/develop/plugins/plugins.tsv.

**Comment by pigmonkey** [comment]
Great!
