### ISSUE TITLE
[v1.5.2] Can't see quantiles for column

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#395]
**Small description**

I have a csv with one column of floats, and I want to see quantiles for it. I would expect from reading the [Summarizing Data](https://jsvine.github.io/intro-to-visidata/basics/summarizing-data/) documentation that pressing `%` to set the column to floats, `z+`, typing `q4`, and pressing return would do this. Aggregations like `sum` and `max` work,.

**Expected result**

I see the quantiles for the column displayed.

**Actual result with screenshot**

Error:
```
filename| AttributeError: 'list' object has no attribute 'type' | "q4"                                                                                                                   z+      2690 lines
```

Stack trace:
```
 Traceback (most recent call last):
   File "/usr/local/Cellar/visidata/1.5.2/libexec/lib/python3.7/site-packages/visidata/vdtui.py", line 1115, in exec_command
     exec(cmd.execstr, vdglobals, LazyMap(self))
   File "<string>", line 1, in <module>
 AttributeError: 'list' object has no attribute 'type'
```

**Steps to reproduce with sample data and a .vd**

Unfortunately the sheet that I was operating on is confidential, but I think it's a pretty simple thing to reproduce - I'd expect that any sheet of floats would do this, though.

**Additional context**

`vd --version` reports `saul.pw/VisiData v1.5.2`. I'm running on a Mac.

**Comment by saulpw** [comment]
Hi @WesleyAC, that's a good find, I agree that it should work as you expect.  With the above commit, hopefully it does.

If we decide to release a v1.5.3, this is a good candidate for back-porting.
