### ISSUE TITLE
[wishlist] Automatically alter date and time display formats based on found values

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#397]
Sometimes I have a sheet with a column that contains date values like `2019-11-14`. In this case, marking the column as a date with `@` does exactly what I want.

Sometimes I have a sheet with a column that contains date time values like `2019-11-14 13:27`. In that case, marking the column as a date with `@` hides the time, which can cause the data to be misconstrued. In these cases, I can change the date format with `disp_date_fmt = '%Y-%m-%d %H:%M'` to get what I want. But remembering to do this, and then doing it manually, is kind of annoying.

I would like visidata to attempt to detect if the column contains hours, minutes, or seconds, and alter the display format appropriately when I specify the column type with `@`. Actually, it should also look for year, month, and day values (right now if a column contains only times like `01:51`, and the default date display format is used, all cells will display as the current date, which can be confusing).

I would expect the resulting display format to be based on the most granular value found. For example, a CSV like this:

```
foo,bar
1,2019-11-14 13:15
2,2019-11-14
```

Would display like this after `bar` is marked as a date:

```
foo  | bar
1    | 2019-11-14 13:15
2    | 2019-11-14 00:00
```

A CSV like this:

```
foo,bar
1,13:15
2,01:00
```

Would display like this:

```
foo  | bar
1    | 13:15
2    | 00:00
```

In that example, I would expect the underlying Python datetime object to still use the current date -- I just don't want to see the date when it didn't exist in the original source, as it could cause me to misinterpret the data.

(I'm using visidata 1.5.2, so apologies in advance if this has already been addressed in the 2.x preview.)

**Comment by saulpw** [comment]
Hi @pigmonkey, this is a good idea and I can see how it would be very useful.  Thanks for suggesting it.

The problem of parsing an unknown date format is challenging, and thankfully the
[python-dateutil](https://dateutil.readthedocs.io/en/stable/) library does an excellent job of parsing dates/times in nearly any format. For the feature you requested, I think the simplest way would be to assemble the strftime-like format string that could reproduce the original string from dateutil's internals.

But I took a look and did not see an easy way to do it.  If we had something working that did this (in just basic Python), we could get the feature as requested into VisiData right quick.  Or if you wanted to cheat and only support ISO format, we could probably pull together a small plugin that you could use.

Until then, this feature request is Marie Kondo'ed (closed without prejudice).

**Comment by pigmonkey** [comment]
I think we can reduce the complexity of the issue if we consider it a problem of looking at the parsed datetimes, rather than the original string.

For example, if after I hit `@` the strings are parsed and the resulting datetime objects are stored in a list `column_datetimes`, this would solve the bulk of the problem:

```
# Default to YYYY-MM-DD.
disp_date_fmt = '%Y-%m-%d'
# Check if any datetime has a nonzero hour, minute or second.
has_hourminute = any(x for x in column_datetimes if x.hour > 0 or x.minute > 0)
has_second = any(x for x in column_datetimes if x.second > 0)
# If any datetime has a time with a nonzero hour, minute or second, add full time to the display.
if has_hourminute or has_second:
    disp_date_fmt += ' %H:%M:%S'
# If any datetime has a nonzero hour or minute, but no seconds, and an abbreviated time to the display.
elif has_hourminute and not has_second:
    disp_date_fmt += ' %H:%M'
```

This would result in the behaviour I want, except for the case of the original data being time only with no dates. For that we could check of every entry in `column_datetimes` has the same date value and, if so, set `disp_date_ftm = '%H:%M'`. But that would result in hiding the date even if the original strings in the sheets did have dates (for instance, if the sheet was a list of log entries from a single calendar day), which may cause more confusion than it is worth. This part of the problem probably does involve analyzing the original strings. I'm fine with ignoring it and just doing something like the above to automatically add hours, minutes and seconds to the date when appropriate.

**Comment by corneliusroemer** [comment]
I would like to +1 this feature request.

Right now the date datatype is useless when you need to see time.

Could one maybe add a datetime display type for date columns?

**Comment by saulpw** [comment]
@corneliusroemer See above about setting the `fmtstr` for date columns to show the time.  You can create a command to do this in your visidatarc, like this `type-datetime`:

    Sheet.addCommand('', 'type-datetime', 'cursorCol.type=date; cursorCol.fmtstr="%Y-%m-%d %H:%M:%S"', 'set type of current column to datetime')
