### ISSUE TITLE
[develop] If any of a Sheet's colorizers raises an exception at any point, the sheet does not get drawn

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#399]
In this example:
https://github.com/saulpw/visidata/issues/348#issuecomment-528722373

```
ColumnColorizer(2, 'color_negative', lambda s,c,r,v: c and isNumeric(c.type) and v < 0)
```

Occassionally, cell values (`v`) are `None`. In that case, `v < 0` raises an Exception. If this happens, the entire sheet does not get drawn.

@saulpw and I agreed that this is not ideal, and should be characterised as a bug. This needs to be fixed without breaking our ability to debug, and we need to retain some notification when something is wrong. Correct behaviour needs design.

**Comment by saulpw** [comment]
with the standard `for/try:/.../except Exception as e: vd.exception(e)` idiom.
