### ISSUE TITLE
Add support for databases such a MySQL, PostgreSQL, SQLite via Blaze

### ISSUE THREAD

**Issue by scls19fr** [saulpw/visidata#4]
Hello,

you might add support for databases such a MySQL, PostgreSQL, SQLite via [Blaze](https://blaze.readthedocs.io/).

https://blaze.readthedocs.io/en/latest/uri.html

Kind regards

**Comment by saulpw** [comment]
Great suggestion!  I didn't know about Blaze until today.  I'm going to try to get that working in the next few days.

**Comment by scls19fr** [comment]
As suggested in https://github.com/firecat53/tabview/pull/116 code from  https://github.com/wavexx/gtabview could be reused

**Comment by scls19fr** [comment]
especially files `dataio.py` and `models.py`
Idea was to share this code accross both `tabview` (so curse interface) and `gtabview` (Qt interface)

**Comment by saulpw** [comment]
After much consideration, I think Blaze is much too large a dependency for this purpose.  VisiData can currently connect to a sqlite database via the standard library module, and other SQL databases have small Python connectors that can be used similarly.

**Comment by s-celles** [comment]
@wavexx may correct me if I'm wrong, but I think he uses Blaze as an **optional** dependency in gtabview

**Comment by saulpw** [comment]
@scls19fr  It would be fantastic if you created a loader for Blaze!  There are already custom loaders like the [sqlite loader](https://github.com/saulpw/visidata/blob/stable/visidata/loaders/sqlite.py) and the [postgres loader](https://github.com/saulpw/visidata/blob/stable/visidata/loaders/postgres.py), and that's the direction I would go to add support for MySQL and MariaDB, but Blaze is fine too if you can get it to work.  You really just have to collect the rows and define the columns, and VisiData will take care of the rest.  I would be happy to help you get this working if you are interested!
