### ISSUE TITLE
Saving CSV data is broken: all values replaced with visidata.column.Column

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#401]
**Small description**
Saving CSV data is broken: all values replaced with visidata.column.Column

**Expected result**
Read and then write a csv file, expect the contents to be the same.

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
No exception.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.
vd foo.csv
then ^S to save the contents, overwrite the original file.  Data has been destroyed.

**Additional context**
Please include the version of VisiData.
latest from develop branch

Apologies, this is an incomplete report.  If there is not enough to reproduce the bug, I'll provide additional details.

**Comment by anjakefala** [comment]
Nice catch @frosencrantz! This should be fixed on the develop branch now. The issue had to do with itervalues being a misnomer. It returned an OrderedDict which then had to be additionally iterated on.

**Comment by frosencrantz** [comment]
Thanks @anjakefala!    Glad I was able to help.
