### ISSUE TITLE
[wishlist canvas] specify graph axis range

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#403]
I have a CSV file that looks like this:

```
id,percent
1,33.4
2,28.9
3,26.1
4,32.3
5,35.1
6,20.2
```

In visidata I mark the first column as an integer with `#` and a key column with `!`. The second column I mark as a float with `%`. I want to get a feel for how these percent values vary, which I think is a good use of visidata's graphing functionality. However, when I graph the data as is with `.` the result is not immediately useful. The Y values in my data are all quite similar, so visidata gives me a Y axis of 20.20 - 35.10, which results in what looks like just a random splattering of points.

These values are percents, so I think of them on a scale of 0 to 100. I can add two fake rows to my data to force visidata to display it on a scale that is more intuitive to me:

```
id,percent
1,33.4
2,28.9
3,26.1,
4,32.3
5,35.1
6,20.2
7,0
8,100
```

The resulting graph makes it much easier for me to understand the data and how the values in the second column are changing -- except I have two fake data points.

I think it would be neat if, when viewing a graph, I could tell visidata what range I wanted to see for either axis. Something like a `options.y_axis = (0,100)`.

Supporting this for both axis would also allow the user to zoom in on a particular area by telling visidata to shrink the X and Y axis to some smaller values. Maybe my X and Y axis are both 1-100, but I think I see something interesting happening with a bunch of high values in the beginning. I could do something like `options.x_axis = (0,10)` and `options.y_axis = (73, 92)` to zoom in on that area.

I've played around with changing the zoom level by moving around the cursor and using `-` and `+` but it feels a little clunky to me. In cases like this where I know the axis values I'm interested in, I would prefer [the ESPER Machine approach](https://www.youtube.com/watch?v=QkcU0gwZUdg&feature=youtu.be&t=45) of just telling visidata what I want.

**Comment by saulpw** [comment]
Thanks for this feature request, @pigmonkey. It should have been really simple but I couldn't get it working straightaway :)  I'll give it another stab in the coming weeks and post my notes here if that doesn't do the trick.

**Comment by saulpw** [comment]
Hi @pigmonkey, this took me a lot longer than I thought it would.  But with the above commits (on develop, will be in next 2.0 pre-release), you can now use `x` and `y` commands on GraphSheet to set the min/max of that axis (separated by a space).  Like in your example, `y0 100`.  Hopefully this does what you need, let me know if it works for you!

**Comment by pigmonkey** [comment]
I just tried this on 2.-4 and it works great.
