### ISSUE TITLE
[wishlist] "merge" jointype

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#405]
I'd like to propose an additional kind of merge:
one where same-named columns get overwritten. The use case for this is e.g. updating a bigger backlog of entries with a new/updated tsv file that should take precedence over the previous values. The new row should not completely overwrite the previous row, i.e. if a cell in the new tsv is empty, it should be "transparent", leaving the old value intact. Ideally this would be selectable, though.

Included are four files, 
* one "db" file with the initial values, 
* one "new" file with the incoming/updated values, 
* two result files,
one with an extra column (as the incoming file has an extra column) and one without the extra column. The opposite could also be a choice (that the db file has extra columns)

[merge_example.zip](https://github.com/saulpw/visidata/files/3876864/merge_example.zip)

![merge_example](https://user-images.githubusercontent.com/1530259/69379501-e2f97c80-0cb0-11ea-9a80-48f5f4e62a8b.png)

**Comment by saulpw** [comment]
Kondo'ed for now, will probably happen at some point.
