### ISSUE TITLE
Support for Alt/Meta keybindings

### ISSUE THREAD

**Issue by vapniks** [saulpw/visidata#407]
I would like to be able to use emacs keybindings that are hardcoded into my brain, rather than try to memorize a whole new set of keybindings.
This include several Meta/Alt keybindings such as "M-<" & "M->" (go-top & go-bottom),
but currently visidata doesn't appear to support the Alt or ESC keys.
Note: I'm using visidata v1.5.2 through tmux on zshell.

**Comment by vapniks** [comment]
OK, so I just noticed that Alt keybindings are enabled in v2.0

**Comment by saulpw** [comment]
@vapniks Yes, although it may become optional in 2.0.  The current (prefix) implementation feels a bit screwy I think.

In 1.5.2 you should be able to put this in your .visidatarc:

```
VisiData.allPrefixes = ['g', 'z', '^[']
```

and then add keybindings as desired (with e.g. `^[<`).

**Comment by vapniks** [comment]
How do I alter keybindings in v2.-1dev?
If I use the following in my ~/.visidatarc file:

```
VisiData.allPrefixes = ['g', 'z', '^[']
bindkey('^[<','go-top')
```
I get the following error at the bottom of the visidata window in bright yellow:
```
TypeError: 'classmethod' object is not callable
```
and the new keybinding is not registered.
Same thing if I omit the `allPrefixes` command.

**Comment by saulpw** [comment]
Use `BaseSheet.bindkey`.

**Comment by vapniks** [comment]
Thankyou. 
For the benefit of others: it seems that the allPrefixes command is not necessary, since I guess those prefixes are already defined in  v2.-1dev
