### ISSUE TITLE
Default to sorting by value for numeric histograms

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#408]
I think it'd be useful for numeric histograms to be sorted by value by default, instead of by count (specifically for floats, but I think this would be useful for other numeric values as well.

It's not very useful to see an unordered list of ~100 floating point numbers - I can't visually parse it, since I need to read each number to know what it is.

I don't know exactly what typical usecases are here (maybe it would make sense to have a threshold where when there are more than N buckets, it sorts by value? Although I'm inclined to think that that's a bit too magical)

Happy to send a PR if it's something that'd be merged :)

**Additional context**

VisiData 1.5.2 on Mac

**Comment by saulpw** [comment]
I agree! This now happens naturally with the numeric binning code in 2.x, which adds the ranged bins in order and then only sorts the result if it wasn't binned numerically.
