### ISSUE TITLE
histogram_bins option is disabled

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#409]
**Small description**

I'd like to be able to set the number of bins for my histograms. It looks like the way to do this is with the `histogram_bins` option, but that's [commented out](https://github.com/saulpw/visidata/blob/stable/visidata/freqtbl.py#L11), so I don't see it in my options table. Is there a way to set this option, or another supported way to set the number of bins for a histogram?

**Expected result**

When I press `Shift-O`, one of the columns is `histogram_bins`.

**Actual result**

`histogram_bins` is not among the options.

**Additional context**
VisiData 1.5.2 on Mac

**Comment by anjakefala** [comment]
Hi @WesleyAC!

Frequency binning of numeric columns is not available in v1.5.2. That feature got postponed to v2.0.

It is under a feature flag on the `develop` branch, where you are welcome to check it out. (Though, we do not guarantee the reliability of the `develop` branch. =) And the documentation is not ready for it, yet. ) That feature still has a planned review and doc update to undergo.
