### ISSUE TITLE
Consider VD add-on for use as email client

### ISSUE THREAD

**Issue by DataBranner** [saulpw/visidata#41]
Thinking aloud here. For interacting with the Maildir and mbox, VD would seem ideal. But I think it will take a lot of work to handle connecting to commercial mail servers and the range of authentication tools that are in use. 

Neither Alpine nor Mutt, the two main applications in use nowadays for CLI-based email, are up to snuff. Using Alpine to access the Gmail IMAP servers requires one to downgrade one's permissions to "less-secure app", and encryption requires clunky third-party tools like Topal, plus patches to the Alpine code. Mutt doesn't seem to be able to handle multiple INBOXes on multiple servers, and configuration is daunting.

**Comment by saulpw** [comment]
This is an interesting use case.  VisiData is explicitly made extensible for this kind of purpose.  I don't think this should be part of the VisiData core platform or the `vd` application, but I'd be really interested to see how this could work.
