### ISSUE TITLE
[develop] VisiData 2.0 fails to install via pip on MacOS Mojave

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#411]
**Small description**

When I execute `pip3 install git+git://github.com/saulpw/visidata@v2.-1`, as directed by http://visidata.org/v2.x/, I get the following error:

```
Collecting git+git://github.com/saulpw/visidata@v2.-1
  Cloning git://github.com/saulpw/visidata (to revision v2.-1) to /private/var/folders/mn/q2sl9dvn2qd0cq_kkrb_442c0000gp/T/pip-req-build-5pdvj2gk
  Running command git clone -q git://github.com/saulpw/visidata /private/var/folders/mn/q2sl9dvn2qd0cq_kkrb_442c0000gp/T/pip-req-build-5pdvj2gk
  Running command git checkout -b v2.-1 --track origin/v2.-1
  Switched to a new branch 'v2.-1'
  Branch v2.-1 set up to track remote branch v2.-1 from origin.
  Running command git submodule update --init --recursive -q
  error: invalid key (newline): submodule.pyxlsb
  deps/pyxlsb.url
  error: invalid key (newline): submodule.pyxlsb
  deps/pyxlsb.url
  No url found for submodule path 'deps/pyxlsb' in .gitmodules
ERROR: Command "git submodule update --init --recursive -q" failed with error code 1 in /private/var/folders/mn/q2sl9dvn2qd0cq_kkrb_442c0000gp/T/pip-req-build-5pdvj2gk
```

**Additional context**

MacOS version: 10.14.6 (18G103)
pip version: `pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

**Comment by WesleyAC** [comment]
According to [this SO post](https://stackoverflow.com/questions/13606951/git-submodule-update-gives-error-invalid-key-newline), it seems likely that this is because pyxlsb is defined twice in gitmodules: https://github.com/saulpw/visidata/blob/v2.-1/.gitmodules#L4-L9.

**Comment by anjakefala** [comment]
I am glad you followed up because on initial try, I was not able to reproduce the issue!

My `pip` is `9.0.1`, and I suspect that is why I never bumped into this.

When I next devote time to VisiData, I will look into seeing if I can reproduce this with an upgraded `pip` and fix the `.gitmodules` regardless (I agree that is wrong).

**Comment by WesleyAC** [comment]
It's also definitely possible that it's a git version thing. I'm running a pretty heavily patched version of git, but it's based on `2.4.11` - possibly that's relevant.

**Comment by anjakefala** [comment]
I was still not able to reproduce. D=

Can you please check if `pip3 install git+git://github.com/saulpw/visidata@v2.-2 ` works for you? I made the SO suggested fix. I will continue looking into this.

**Comment by WesleyAC** [comment]
`pip3 install git+git://github.com/saulpw/visidata@v2.-2` works for me 🎉

**Comment by anjakefala** [comment]
Awesome! The notes for that branch will be up later this week. =)
