### ISSUE TITLE
visidata v2.-1dev (but not v1.5.2) flickers when run through emacs term-mode 

### ISSUE THREAD

**Issue by vapniks** [saulpw/visidata#412]
visidata v1.5.2 works fine in emacs term-mode which is great because it means I don't have to leave my python/R coding editor to peruse the data.

However, when I run visidata v2.-1dev through emacs (x11) term-mode the top line is not displayed, and when I press a key the screen flickers slightly as it shifts the text down a line to display the top line (thereby hiding the bottom line), and then back up again to display the bottom line. If I then press f11 to make my emacs window full screen all lines are displayed and the flickering stops, however if I try starting term-mode in full screen mode _before_ starting visidata I get the one line missing & flickering problem again.

**Comment by anjakefala** [comment]
Hi @vapniks!

Thanks for letting us know about this.

Are you comfortable with `git bisect`? If you are, could you please run `git bisect` between the `v1.5.2` tag and the `v2.-1` branch to let me know which was the first commit where the flickering started? 

I would like to narrow in on the change which introduced this issue. This will help speed-up fixing it. =)

**Comment by sfranky** [comment]
btw same flickering occurs in WSL windows 10, but I think that has been an issue for far longer..

**Comment by vapniks** [comment]
I am on the case (for emacs)..

**Comment by sfranky** [comment]
for me, first bad commit is 
ef0fee2095be09282fb761826fa8375c68936156

**Comment by vapniks** [comment]
The commit which causes the jittering and one-line missing problem is 06d608f002643bd1b3de3fb62d314ea9488ca86e
but I've also noticed some flickering on the bottom status line. Will try to track that down..

**Comment by vapniks** [comment]
The commit which causes the bottom status line to flicker is ef0fee2095be09282fb761826fa8375c68936156

**Comment by anjakefala** [comment]
Thanks @vapniks and @sfranky! :tada:

**Comment by saulpw** [comment]
Thank you both!  This is very helpful.  I think I understand what's going on in both cases, though I don't know why I added the scr.refresh() in ef0fee2, so removing it might leave artifacts on the screen in some situations.  We can try it though and see if we ever notice :)

As for 06d608f...I'd better dollars to donuts that the unicode character (`〉`) being full-width is the culprit.  VisiData should take character width into account when determining how to truncate strings, and I'm guessing that on any other line it wouldn't have an effect, but the last line of terminals is often touchy, and so I wouldn't be surprised if it causes the line to wrap and thus scroll before it redraws it properly.  In this case, an easy fix for you is to set `options.disp_status_fmt = '{sheet.num}> {sheet.name}| '` (for example--or remove the sheet.num portion entirely).  Probably we should do that for maximum compatibility anyway.

**Comment by vapniks** [comment]
Yes, that fixes the jittering problem, but now I get `AttributeError: 'CsvSheet' object has no attribute 'num'` in yellow along the bottom.

**Comment by anjakefala** [comment]
@vapniks :tada: at it working. Can you please try `options.disp_status_fmt = '{sheet.shortcut}> {sheet.name}| '`. Basically, `sheet.shortcut` instead of `sheet.num`?

**Comment by vapniks** [comment]
Yes, that works, thanks! (still have the status line flicker though).

**Comment by saulpw** [comment]
I removed the `scr.refresh()` that apparently causes the status line flicker, and that leaves artifacts on the screen inside tmate (which happens in 1.5.2).  If anyone finds a solution to the tmate artifacts issue that doesn't cause status-line flicker, I'd love to get it fixed, but for now, a bit of flicker is better than the artifacts.

**Comment by EduardoVernier** [comment]
I still have a flicker on my emacs terminal at the frequency sheet because of the `♯` character in the count column. I was able to resolve it by adding this to my .visidatarc

```
from visidata import vd, vlen
vd.getType(vlen).icon = 'L'   # choose any single-char symbol your font supports
```

Hope this helps someone in the future! Visidata is great!
