### ISSUE TITLE
z^S only saves column, not key column + column

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#415]
z^S only saves the current column, instead of saving also the key column, as stated in the manual.

**Additional context**
Latest dev commit
No .visidatarc, no plugins loaded

**Comment by saulpw** [comment]
Thanks @sfranky.  I added an unbound command `save-col-keys` that does this now.  We need to update the docs to reflect the expected behavior of `save-col` and the new command.

Also if anyone can think of a better name for either or both of these commands, I would love to hear them.
