### ISSUE TITLE
Undo results of new custom command

### ISSUE THREAD

**Issue by vapniks** [saulpw/visidata#417]
I've added to following code to my config file:
```
Sheet.addCommand('','trim-col-whitespace','cursorCol.setValuesFromExpr(selectedRows or rows, cursorCol.name + ".strip()")')
```
It creates a new command (with no keybinding) which trims whitespace from all cells in the current column. However, after applying the command I am unable to undo it.
I've tried searching the code for the `undo-last` command, but even though this is listed in the help sheet, when I grep through the code I can't find it.
Please help.

**Comment by saulpw** [comment]
What version are you using, and what version are you grepping through?  This seems to me like it should be undo-able in the current develop branch.

**Comment by vapniks** [comment]
I'm using v2.-1dev, and grepping through v1.6-dev... Doh!!! (slaps head)
I forgot that I'd downloaded both versions, and was looking at the wrong one!

**Comment by vapniks** [comment]
In any case, how would I get undo working with my custom command?

**Comment by saulpw** [comment]
Try upgrading to v2.-2 and it should just work.

**Comment by vapniks** [comment]
Hmm.. did that, but when I run the `trim-col-whitespace` command above I get:
```
SyntaxError: invalid syntax
```
It works if I run this code at the python CLI:
```
>>> import visidata as vd
>>> data = vd.openSource('faa-wildlife-strikes.csv')
>>> data.reload()
>>> data.cursorValue
'BUSINESS  '
>>> data.cursorCol.setValuesFromExpr(data.selectedRows or data.rows, data.cursorCol.name + ".strip()")
>>> data.cursorValue
'BUSINESS'
```

**Comment by anjakefala** [comment]
@vapniks, I cannot reproduce the `SyntaxError`. Can you reproduce the error, and then please press `Ctrl+E` then `Ctrl+Q`, and paste the stacktrace?

**Comment by vapniks** [comment]
Ah.. just figured out what the problem was. I used a different source when I tried it with ```vd``` directly. I was replaying a .vd file in which the original source was a URL, and the column I was trying to trim didn't have a name.
However, after setting the column name to "Country" and trying again I get:
```
Country column cannot be changed
```
If I then try saving the sheet, I get:
```
IndexError: list index out of range
```
however the sheet appears to have been saved.
If I try ```trim-col-whitespace``` again I get the same message as before, but if restart vd with the saved sheet I am able to run ```trim-col-whitespace``` without errors.

It would be nice to be able to use my command on data sourced from URL's, since then I could merge wikipedia tables in a single session (and share the resulting .vd file with others) without having to save the sheets to files first.

**Comment by saulpw** [comment]
You can get around this with `g'` to freeze the values in the sheet.  The proper alternative is to replace the current column with a derived column that does the .split() (e.g. use `=` instead of `g=`').  The only reason to make it like `g=` as you have it, is if you want the results propagated back to the source sheet from a derived sheet.  But as you're seeing, the source column is not actually editable anyway.
