### ISSUE TITLE
How to unbind a keybinding

### ISSUE THREAD

**Issue by vapniks** [saulpw/visidata#420]
In my config file I have:
```
BaseSheet.bindkey('^_','undo-last')
```
and when I start visidata v2.-2 I get this message in bright yellow at the bottom of the screen:
```
^_ was already bound to toggle-profile | g^S was already bound to save-all
```
There is no mention of the ```g^S``` binding in my config, but it is set in the ```defermods``` plugin which I have installed. When I press ```^_``` it calls ```undo-last``` which is what I wanted, but if I could unbind the default binding before creating the new one in my config file it would prevent the yellow message and free some screen space for any more important messages. 
More generally I can envisage situations where others may want to disable some keybindings entirely.
How can this be done?

**Comment by saulpw** [comment]
Use `BaseSheet.unbindkey('^_')`.  Unfortunately for now you have to know which Sheet type the key was already bound on.

**Comment by anjakefala** [comment]
@saulpw, where do you unbind if the original was a `globalCommand` (which is the case for `g^S`)?

**Comment by saulpw** [comment]
global `unbindkey` should work in that case for now.  Ultimately global commands will either be on BaseSheet, or on VisiData itself.

**Comment by sfranky** [comment]
all this time i saw something similar on the status row and i thought it was some kind of super inner joke i will never get!!!

**Comment by anjakefala** [comment]
I mean... the inner joke is

![image](https://user-images.githubusercontent.com/7489659/70943039-c24cea00-2004-11ea-8169-ebdeed98b797.png)

**Comment by sfranky** [comment]
i see Ted Danson, I upvote

**Comment by anjakefala** [comment]
```quote
There is no mention of the g^S binding in my config, but it is set in the defermods plugin which I have installed. 
```

This has been updated in the most recent version of the defermods plugin! I am going to close this issue since the question has been answered. =)
