### ISSUE TITLE
Navigating to the nth column

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#421]
I have a script which loads a sheet and extracts the 26th column. The script is not working as expected with some sheets. I loaded one of those sheets with visidata so that I can manually inspect it.

Is there a way to tell visidata to navigate to the 26th column? I don't know what the header of that column is, so I can't do a regex search. I was hoping to do something vim-like, such as `26l` to move to the right 26 times.

**Comment by anjakefala** [comment]
Hi @pigmonkey!

VisiData does not have relative-numbering column navigation (illustrated in your `26l` example), but there is a way to navigate to the 26th column.

`c` navigates to the column by name regex.
`zc` navigates by column number (where the columns are numbered via 0-indexed).'

Hope that helps. =)

**Comment by pigmonkey** [comment]
I see `zc` in the man page now. Thanks. That does what I need.

**Comment by anjakefala** [comment]
@pigmonkey I should add a how-to for that. Thanks for asking usability questions, it will help me for when I make time to mature those!
