### ISSUE TITLE
[vddedupe] not working

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#423]
**Small description**
plugin vddedupe's dedupe-rows command not working  (no sheet change upon execution), with vanilla visidatarc.

example file dloaded from docs (https://jsvine.github.io/intro-to-visidata/advanced/extending-visidata/) not working , although select-duplicate-ows working normally.
Running on last develop commit.

**Comment by anjakefala** [comment]
Hi @sfranky! Can you please move this issue to the plugin repo, and mark that changes are required for the plugin once VisiData 2.x is shipping?

We are cleaning up our issues, and this is not really actionable from the VisiData repo's end.
