### ISSUE TITLE
--config command line option does not appear to work

### ISSUE THREAD

**Issue by osunderdog** [saulpw/visidata#427]
**Small description**
vd --config {filename} does not execute python code in {filename}.
 
**Expected result**
From the help documentation `vd --config {filename}` should exec {filename} on startup.  

**Actual result with screenshot**
The only way I can get a config file to execute is if the config file is saved at `$HOME/.visidatarc`.

**Steps to reproduce with sample data and a .vd**
Create config file /tmp/visidata-config.py:
```
raise NotImplementedError()
```
run the command:
`./bin/vd --config /tmp/visidata-config.py`
press `ctrl-e`
observe no exception. (expected NotImplementedError)

Link /tmp/visidata-config.py to $HOME/.visidatarc and run vd and observe that the exception is hit.
```
ln -s /tmp/visidata-config.py $HOME/.visidatarc
./bin/vd
```
press `ctrl-e`
observe expected exception

**Additional context**
branch v2.-2 (202d235a)

**Notes**
What I want to be able to do is to have multiple different config files containing different functions that are useful in the context.  I though using the --config would do this, but it does not appear to be implemented at the moment.  If I get time I'll try and do a PR for this.

**Comment by saulpw** [comment]
Thanks for the bug report, @osunderdog.  Your expectations were correct, this was a good bug.  The commit above should both fix it and explain it.
