### ISSUE TITLE
[jsonl] load and save round-trip (minimal diff)

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#429]
When a user does `vd -b file.jsonl -o file.jsonl`, the output file should be identical to the input file.

**Comment by saulpw** [comment]
This is pretty important, but I'm not quite sure how to do it!  If anyone wants to make an attempt, the code should all be in visidata/loaders/json.py.

**Comment by anjakefala** [comment]
Accomplished a minimal diff!
