### ISSUE TITLE
[howto] hide invariant columns

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#431]
This is a request to the visidata community.  I would like a plugin that hides invariant columns.

I look at data with many columns.  Sometimes the columns have only a single value. Sometimes this happens after drilling down into the data.

It would be useful if these invariant columns could be hidden with a single command. Now, I just visit the frequency table to see if what values are in a column, and manually hide columns.

A secondary feature, would be to create a second table that has a copy of each of the invariant columns but with a single row.  This second table should be the alternate table so, that Ctrl-^ would make it possible to quickly view.

**Comment by anjakefala** [comment]
@frosencrantz, can you define for me "invariant columns" in this context?

**Comment by frosencrantz** [comment]
In this context  an "invariant column" is a column that has same value in all rows.  There needs to be more than one row.

**Comment by saulpw** [comment]
To hide columns which have the same value in all rows, open the Describe Sheet (`Shift+I`), select columns using `z|` where `distinct <= 1`, and then hide them with `g-`.

**Comment by frosencrantz** [comment]
Thanks, @saulpw!  That works.
Is there a way to make that into a single shortcut?
