### ISSUE TITLE
[colorizer]  Adding a colorizer applies to all sheets not just the sheet the colorizer was added to.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#433]
**Small description**
From https://github.com/saulpw/visidata/issues/430#issuecomment-570672955
@saulpw says:
sheet.addColorizer seems like it should only add the colorizer to the current sheet, I agree. This is probably just a bug, though it may prove difficult to fix in the short term. We'll look into this, esp as we finalize the API for 2.0.

**Expected result**
Apply only to the sheet that sheet sheet.addColorizer was called on.  Though I could see how it would be useful either way to make a global or local colorizer.

**Comment by saulpw** [comment]
Fixed now.

**Comment by saulpw** [comment]
Fixed now so that `sheet.addColorizer` only applies to `sheet`.  To apply to an entire class of sheets, use e.g.:

```
TsvSheet.colorizers += [
    CellColorizer(0, 'reverse', lambda s,c,r,dw: dw == 3)
]
```

The `dw == 3` works now too.

**Comment by frosencrantz** [comment]
Thanks, @saulpw. I like that it can be done either way now.
