### ISSUE TITLE
[wishlist] delete an added colorizer

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#434]
**Small description** 
This might just be a question, rather than a bug.

It is not clear what the correct way to remove a colorizer that was added via sheet.addColorizer()
If I add one via a command mapping it would be useful to be able to remove it with a command.

**Comment by saulpw** [comment]
Added `sheet.removeColorizer` for 2.0.  Now you can do e.g.:

```
@Sheet.command('1', 'equal-3', 'reverse cells == 3')
def equal3(sheet):
    c = CellColorizer(0, 'reverse', lambda s,c,r,v: v == 3)
    sheet.addColorizer(c)
    vd.addUndo(sheet.removeColorizer, c)
```

which makes an undo-able command to add a colorizer which applies `reverse` to all cells equal to 3.

**Comment by frosencrantz** [comment]
I haven't tried it, yet.

It occurs to me is that the only name for a colorizer is a reference to it.  That works with the undo example.  It's not clear how I would remove it as a user after doing other operations without a name. Oh... maybe a table of the installed colorizers. 

I like the example you gave, I hadn't noticed the decorator format before. 

Thanks, @saulpw!
