### ISSUE TITLE
[wishlist] Add ability to set both foreground and background colors independently 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#435]
**Small description**
sheet.addColorizer() only allow you to see the fg or bg color (via the reverse attribute).  But there is no way to independently set both.   It would be nice to have control of both these independently.

It looks like part of the issue is that the curses color_pairs are all created at start up, and there are no free spots.  Perhaps these can be changed later.

I know this is unlikely to be added any time soon, but this would be nice to have.

**Comment by frosencrantz** [comment]
This is wicked cool.  Thank you, @saulpw !

I saw the change at the beginning of the week, and haven't had a chance to try it out.

**Comment by geekscrapy** [comment]
This is great!! 👍
