### ISSUE TITLE
[feature-request] Add way to compare rows to visidata

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#442]
Add a way to compare a bunch of rows easily. Here, if a column have the same value for all rows in a sheet, they should be hidden.

**Comment by anjakefala** [comment]
Hi @nabeel-ms!
I cannot find an issue where @saulpw talks about it (:disappointed:), so this is based on my understanding of the roadmap. 

```
Add a way to compare a bunch of rows easily.
```
My gut instinct is that what you are asking for is a way to specify "rows" as an entity in formulas and perform operations on them. Being able to easily write formulas that compare rows to each other within the VisiData interface is out of scope for 2.0. Folks have been building plugins for the specific row inter-row comparisons that they have been looking for. Building a plugin that contains a command that hides a column if all of its contents are the same is do-able.
However, 
```
Here, if a column have the same value for all rows in a sheet, they should be hidden.
```
if the "they" in this case are "rows should be hidden", there are a few different ways to do this.
@jsvine's dedupe plugin: https://github.com/jsvine/visidata-plugins/blob/master/plugins/vddedupe.py comes with commands that remove duplicated rows.

If you go to a row, and press `,` on a cell, it will select all rows that have the same value in that column. You can then press `gd` to delete those rows. If you want the column to be hidden, you can look at the status to see how many rows were selected, and visually compare that to the number of rows. If they are the same, you can then hide the column with `-` (and then unselect all of your selected rows with `gu`).

You can perform Python expressions when selecting with `z|`. So you can `z|` *Items > 3*, to select all rows with contents in *Items* that are larger than 3. Likewise, you can do `z|` *Items == 3*. `z=` works similarly, but with creating expression columns. These are all comparing all-rows to a certain constant value, not comparing rows to each other.

**Comment by frosencrantz** [comment]
I'm not sure I understand the request.  But part of what you are requesting sounds like my recent plugin request: https://github.com/saulpw/visidata/issues/431 to hide columns that only have a single value.  

Your request sounds like a special case, where it would only hide columns if they have a single value in the selected rows (vs all rows).

**Comment by ghost** [comment]
@frosencrantz  Thanks. That fits my requirements perfectly.
