### ISSUE TITLE
[wishlist] fixed format - column definitions?

### ISSUE THREAD

**Issue by tkossak** [saulpw/visidata#443]
Is it possible to define exact column positions/lengths for fixed format? I have a fixed file and it is impossible for visidata to properly recognize where column begins and where it ends without proper defintion.
It would be good if we were able to pass columns definition to visidata eg:

column 1 - from char 0 to 5
column 2 - from char 6 to 10
column 3 - from char 25 to 30
etc...

**Comment by saulpw** [comment]
Hi @tkossak, you can get column on a fixed sheet from position `i` to `j` with `FixedWidthColumn(name, i, j)`, which you could make into a little command to add the right columns for your filetype (this can probably go straight into your .visidatarc):

```
betterCols = [
         FixedWidthColumn('col1', 0, 5),
         FixedWidthColumn('col2', 6, 10),
         FixedWidthColumn('col3', 25, 30),
]

Sheet.addCommand('', 'addcols-myfiletype', 'for c in betterCols: sheet.addColumn(c)')
```

or if you wanted something more generic, you could do something like this:

```
option('fixed_cols', '', 'fixed width columns')

@FixedWidthColumnsSheet.api
def addFixedCols(sheet, coldesc):
    'coldesc like "0-5 6-10 24-30"'
    for n, desc in enumerate(coldesc.split(" ")):
        i, j = desc.split("-")
        sheet.addColumn(FixedWidthColumn(f'col{n}', int(i), int(j)))

FixedWidthColumnsSheet.addCommand('', 'addcols-fixed', 'addFixedCols(options.fixed_cols or input("columns (0-4 5-7 ..): "))')
```

`vd -f fixed --fixed-cols="0-5 6-10 24-30"` and then exec `addcols-fixed` and et voila, Robert's your uncle.

**Comment by tkossak** [comment]
I tried second solution (more generic option) and in visidata v1.5.2 I get:
```
Traceback (most recent call last):
  File "/home/kossak/.local/pipx/.cache/23c5a5ea4e2bdc0/lib/python3.6/site-packages/visidata/vdtui.py", line 2861, in loadConfigFile
    exec(code, _globals or globals())
  File "/home/kossak/.visidatarc", line 3, in <module>
    @FixedWidthColumnsSheet.api
AttributeError: type object 'FixedWidthColumnsSheet' has no attribute 'api'
```

So I tried latest 2.0 version (`vd -f fixed --fixed-cols="0-2 3-5 6-8" test.txt`) (this is the file: [test.txt](https://github.com/saulpw/visidata/files/4070939/test.txt)) and got this in status bar:

`1〉--fixed-cols=0-2_3-5_6-8| --fixed-cols=0-2 3-5 6-8 does not exist, creating new sheet | saul.pw/VisiData v2.-2.1 | opening test.txt as fixed`

**Comment by saulpw** [comment]
Ah, the core problem here is that plugin options don't get added to the cmdline parser--we need to parse the cmdline args to find any '-c <config>' to specify alternate .visidatarc, which then import plugins.  So it should work if you specify it in your .visidatarc:

        options.fixed_cols="0-2 3-5 6-8"

I added a re-parsing step for cli args so that plugins can have their options on the cli options.  Long-term solution would be to write our own slick options parser.

**Comment by saulpw** [comment]
I believe this should work as expected now.  Let me know if this does not work for you, @tkossak.

**Comment by tkossak** [comment]
Yes it works after I installed https://github.com/saulpw/visidata/commit/3bcee8b4bc8095a7d61f760ff4996b2239a5690f version.

Ideally it should work without people modifying their `.visidatarc` and running `addcols-fixed` manually after starting `vd` (CLI option should be enough). But nonetheless it works so thank you very much.
