### ISSUE TITLE
Display columns are duplicated when loading JSON with a single object

### ISSUE THREAD

**Issue by ajkerrigan** [saulpw/visidata#444]
**Small description**

If I open a JSON file which contains a single JSON object rather than an array of objects, its columns are duplicated in the VisiData window. Sample contents (`singleitem.json`):

```json
{
  "key1": "val1",
  "key2": "val2"
}
```

**Expected result**

Opening a JSON file with a single object should appear the same as opening a JSON file containing an _array_ containing only that object.

In VisiData 1.5.2, this works as expected:

```
 key1   | key2   ‖
 val1   | val2   ‖
```

**Actual result with screenshot**

In VisiData 2.-3dev:

```
 key1   ╵ key2   ╵ key1   ╵ key2   ║
 val1   ╵ val2   ╵ val1   ╵ val2   ║
```

**Steps to reproduce with sample data and a .vd**

```
echo '{
  "key1": "val1",
  "key2": "val2"
}' > singleitem.json

vd singleitem.json
```

**Additional context**

Version: VisiData 2.-3dev, most recently 0164c10.

Note that this issue appears to be only a _display/UI_ quirk. Saving the file does _not_ cause duplicated columns in the output.

**Comment by ajkerrigan** [comment]
For the record, this feels like a pretty low priority issue and I'm happy to take a peek at it myself. Just wanted to get it documented before I forgot!

**Comment by saulpw** [comment]
Nice find, @ajkerrigan, and thanks for fixing it!
