### ISSUE TITLE
Consider filesystem support for add-ons

### ISSUE THREAD

**Issue by DataBranner** [saulpw/visidata#45]
For treatment in the documentation, what sort of README and subdirectory support would be reasonable for add-on modules? 

It's convenient having them all together in `addons/`, but for those that require special instructions (for instance, what if key-commands overlap with those of other add-ons?) or look-up files, what would the best way be to structure things? I can imagine each module, with appurtenances, in its own subdirectory, and I can also imagine something like

```
screen-reader.py
screen-reader.md
screen-reader-support/
```

Any thoughts.

**Comment by saulpw** [comment]
No addons have this issue at present, so it's best to postpone this decision until there is a concrete use case to design around. Probably large add-ons or add-ons with profound conflicts should be in their own separate repositories anyway, and then their maintainers can decide the best way to structure them for their own needs.
