### ISSUE TITLE
[wishlist] Add ability to set the default alignment of values and scroll the values within a column. 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#455]
If the values of a column are too wide for the width of the column there is no way to scroll the value within the column.

Some values are wide, but only seeing one (or both) edge(s) of the value is enough, but it is not possible to tell visidata the values in a column should be left, right, or center aligned.  If the width of the column becomes too narrow for the column, the alignment would control what part of the value is elided.

For some values it would be useful to have absolute control over what part of the value you see.  For example using the sparkline plugin, it would be useful to be able to scroll the column/graph to the part of the range of interest.

For cool points, allow the horizontal scrolling of a column to be connected to the horizontal scrolling of the sheet.  So if you made a sparkline column a key column, and the made the column width smaller than the width of the sparkline graphs. then as you scroll the non-key columns left or right the values in the column would also scroll in a matching way.

So three requests:
  * add ability to scroll the values of a column
  * add the ability to specify the alignment of a column & the ability to control the what part of a wide value is shown in a narrower column. 
  *😎 add way a to synchronize intra-columnn scrolling with sheet scrolling.

**Comment by saulpw** [comment]
Yeah this would be really cool!  I can't think of an interface for it though.  How would it work?

**Comment by frosencrantz** [comment]
I think for regular alignment it would need to be another metadata field about columns, there are already  properties like type and width.  For values wider than the column, we would also need an offset to where to start showing the value.   The default for wide values would be such that center alignment would elide the center of the value, so you could see as much as you can of the left and right sides.   Left or right alignment would clip the side that make sense, like is already done.

As for the extra cool points for automatic alignment..  My first thoughts are...
When I use sparklines, the input columns are left in the same order as when they are used to generate the graphs in the column.  Maybe have an additional alignment type called synchronized.  To use it, you need to first make the sparkline column a key column.  Then go to the leftmost column of the data columns used for the sparklines, and run a command that marks this as  the left-hand side.  

Then the leftmost column's location relative to the left edge is used to scroll the the sparkline column.  If the leftmost column is the first column off the left side, then the sparkline would have it's leftmost value scrolled off the left side.  Keep the leftmost data column's location relative to the left edge synchronized with where the leftmost mark is relative to the left side of the sparkline column.

**Comment by saulpw** [comment]
This made it into 2.0 on the zh/zj/zk/zl bindings.
