### ISSUE TITLE
[tsv] Problem reading file that contains a CRLF within a quoted cell

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#459]
**Small description**

When I read [this](https://github.com/saulpw/visidata/files/4159251/input.zip) TSV file, that has inside cells some CRLF, visidata does not map correctly cells.

**Expected result**

Using LibreOffice I have no problem

![image](https://user-images.githubusercontent.com/30607/73838760-b9161780-4814-11ea-8685-8af81387df74.png)

**Actual result with screenshot**

Using VisiData v1.5.2 I have this

![image](https://user-images.githubusercontent.com/30607/73838833-e1057b00-4814-11ea-9d67-e2478acb71a6.png)

That TSV does not seem to me wrong, because the CRLFs are inside double quotes.

**Comment by anjakefala** [comment]
Thank you so much for the detailed bug report @aborruso!

From a glance, the tsv loader code does not seem to support a quotechar.

The csv loader does!

A current workaround, until we have an opportunity to give this issue more attention, is to load these files with the csv loader, and specify a tab delimiter. You can do that:

```
vd input.tsv -f csv --csv-delimiter=$'\t'
```

**Comment by sfranky** [comment]
I didn't know about the dollar sign @anjakefala, I always typed ctrl-v<tab> to put a literal tab !! nice !!

**Comment by aborruso** [comment]
hi @anjakefala `$'\t'` is the ANSI C way to write the tab char?

**Comment by anjakefala** [comment]
:joy: 

Saul taught me this! It blew my mind, too. I asked him how to pass a tab just before commenting on this issue.

From what I understand, the `$` tells the shell to interpret `\` escapes. Instead of literally taking the `"\"`  as string, it interpets the `\t` as a backslash'd entity.

**Comment by saulpw** [comment]
This is the correct solution, as quoted newlines aren't allowed in 'true' tsv files.
