### ISSUE TITLE
[wishlist] long to wide command (a sort of specialized pivot)

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#461]
Hi,
if I need to transform long to wide [this TSV](https://gist.github.com/aborruso/bd1017a9cb9d765932b0bbb59617c069), starting from the columns "key" and "value",  the steps are these:

- set all the fields as key (excluding "key" and "value" fields);
- add max aggregator to "value" field ;
- select "key" field and click Shift+W.

![long2wide](https://user-images.githubusercontent.com/30607/73948445-4a5eba00-48f9-11ea-85a4-e70d69c7d42a.gif)

"long to wide" (and vice versa)) is a classic transformation, and it would be great to have a more direct way to do it, using different procedure and a new shortcut: in example to start from setting as key fields the "key" and "value" fields and then select the "key" field and use a dedicated shortcut to apply "long to wide" transformation (and not to start to set as key fields all the other fields).

Thank you

**Comment by jsvine** [comment]
Interesting! I was just thinking the same, while working through a "long" dataset. I'd defer to @saulpw and @anjakefala, but it seems to me that a tricky part might be how to handle non-unique indexes/keycol-sets. For instance:

```
name    key      value
------  -------  -------
fido    species  dog
fido    weight   100
bobbie  species  cat
bobbie  weight   20
```

... should transform to:

```
name    species      weight
------  ---------  --------
fido    dog             100
bobbie  cat              20
```

But what should trying to do the same with this table, which has two `species` keys for `fido`?:

```
name    key      value
------  -------  -------
fido    species  dog
fido    species  cat
bobbie  species  cat
bobbie  weight   20
```

Some possibilities:

- The command could first search all the way through all the keys to detect duplicate keys, and then throw an error if it found one... and then build the wide table. Downside: For large tables, it'd feel like there was a lag before the wide table began to render.

- The command could start building the wide table, and then abort if it encountered duplicate keys. Downside: You might waste time rendering large tables that cannot be used.

- The command could create numbered columns for each duplicate key it encounters. E.g., `species`, `species_2`, et cetera. Downside: A bit messy. 

- The command could simply ignore duplicate keys. Downside: Unexpected.

Thoughts?

**Comment by aborruso** [comment]
Hi @jsvine,
I think that it's especially up to the user to check for duplicates key value, for the same item (here it's "fido", and "name" is the one and only key field), before thinking to run long to wide transformation.

A check could be to add in background count as aggregator for the value field: if in the output there is some cell with value >1, then there is some duplicates key coupled with key fields value, then there is a problem and vd could write "hey user, check your data".
In my example TSV something like the image below.

![image](https://user-images.githubusercontent.com/30607/73970713-e4385e00-491d-11ea-938c-ed96988d73c8.png)

**Comment by paulklemm** [comment]
Maybe it's a good idea to learn from the behavior of `tidyr` in these special cases:

https://tidyr.tidyverse.org/reference/pivot_longer.html
https://tidyr.tidyverse.org/reference/pivot_wider.html

**Comment by anjakefala** [comment]
Hi! Unfortunately, it seems like we do not have the bandwidth to fulfill this request for v2.0, so I am going to wishlist this for now. Anyone is welcome to add a PR for this feature!

**Comment by srearl** [comment]
second this request @aborruso , and thanks for posting the super helpful example of how to accomplish this with the existing tool suite!
