### ISSUE TITLE
[wishlist] Create new column from row index

### ISSUE THREAD

**Issue by paulklemm** [saulpw/visidata#463]
How can I add a new column involving the current row index?

For example from

| Brands |
| - |
| Mazda |
| Mercedes |
| BMW |

to

| Brands | ID |
| - | - |
| Mazda | 1 |
| Mercedes | 2 |
| BMW | 3 |

This is probably already trivial. Maybe we can add an example here: https://jsvine.github.io/intro-to-visidata/intermediate/creating-new-columns/

**Comment by aborruso** [comment]
Hi @paulklemm you could do in this way https://github.com/saulpw/visidata/issues/215#issuecomment-443544587

**Comment by sfranky** [comment]
@paulklemm if you're willing to switch to the develop branch, there's a plugin that does that, rownum.
If you install the plugin, then all you have to do is [space]addcol-rownum[enter]

**Comment by anjakefala** [comment]
Thanks so much @aborruso and @sfranky for thoroughly answering the question. <3 :blush:

**Comment by anjakefala** [comment]
And yes, @paulklemm, it would definitely be good to document this. I will add it to our docs at least. This is intro to visidata's repo: https://github.com/jsvine/intro-to-visidata
