### ISSUE TITLE
[wishlist] Ability to load from a the contents of a cell.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#465]
A cell can have contents that could be interpreted as a data file.  Add the ability to load the contents of a cell as a particular type, which could be different from the type of the data file it is part of.

For example, there are json files called har files that web browsers can create.  These json files can have strings that have the contents of a independent file.  It is possible to save the contents of the cell to a file, and then load that file.  It would be useful if that could be done directly (cell to newly loaded sheet).

**Comment by saulpw** [comment]
Interesting idea!  Maybe `z ENTER` or `zo` would be a reasonable keybinding for such a command.  I guess you'd have to input the filetype it would open as.  Should be reasonably straightforward to cobble something together using visidata.Path and openSource; left as an exercise for the reader (who should post their solution(s) here).

**Comment by frosencrantz** [comment]
Thanks, @saulpw ! That was very helpful.  It looks like there is already a good example in the code  for loading data from a string:

https://github.com/saulpw/visidata/blob/dd93954a4baeefefeb5fec49c0ae5fa8acab13bb/visidata/main.py#L26-L29

log can be replaced with cursorValue
the type can be replaced with input("type", value="json")
The name could be: name + "_cell"
