### ISSUE TITLE
[user pref] if columns are too narrow and `g_` is annoying, increase options.default_width

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#466]
There was a request on twitter for rough edges:

When loading data, visidata uses set columns sizes.  I look at data that could easily fit within the width of the screen, but is has values wider than the default columns. So the data hides in narrow columns, cowering on the left side of the screen. Easy for me to fix with a 'g_'. 

Still feels like a rough edge.

**Comment by saulpw** [comment]
In the context of discovered column widths, `options.default_width` serves as a maximum.  It's set to 20 by default but I chose this arbitrarily; you can set it higher if you want.  There needs to be a maximum to avoid pathological layouts.
