### ISSUE TITLE
[rough edges] Unhiding a column takes a lot more keystrokes than hiding

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#467]
Hiding a column is easy is and fast:
- Navigate to column
- Type "-"

Unhiding a column takes a lot more work:
 - A couple special cases are nice and easy:
    - There is 'gv' to unhide all hidden columns
    - There is undo, if you just hid the column.
 - But the general uses a lot of keystrokes:
   - Type 'C', go to column sheet.
   - Navigate to the width column, navigate to column of interest
   - 'e' to edit the cell
   - clear the '0'
   - type in the new width, hit enter
   - return to the original sheet. 

Maybe if there was an unhide-col command that could take a column name, maybe with column name completion, and listing the names of columns that are currently hidden. Sort of like the add aggregate-col command does.

**Comment by saulpw** [comment]
This is definitely a command you could make yourself, @frosencrantz.  I'd love to see the result when you get it working!  And probably others would too.

**Comment by frosencrantz** [comment]
@saulpw this issue was in response to your tweet: https://twitter.com/saulfp/status/1222033912597073920

It has been on my list, and I will get to it at some point. It seemed to be what you were requesting.

**Comment by frosencrantz** [comment]
I do not know how to get a list of the hidden column names. It would useful to know that.

**Comment by anjakefala** [comment]
I think you might need to make a new property that tracks that? https://github.com/saulpw/visidata/blob/develop/visidata/layout.py#L27

**Comment by saulpw** [comment]
@frosencrantz `[c.name for c in sheet.columns if c.hidden]`

**Comment by frosencrantz** [comment]
Thanks @saulpw!

That could be combined with chooseMany() like is done for aggregators:
   https://github.com/saulpw/visidata/blob/a65b464118fbcb66e46e89da22a81b8e48c61b2d/visidata/aggregators.py#L145-L147

Untested:
```
Sheet.addCommand('+', 'column-unhide', 'for c in chooseMany([c.name for c in sheet.columns if c.hidden]): c.hidden = False')
```

Not sure how to unhide a column.  Either that or set a base width.  `c.width = 10`

**Comment by ZachGawlik** [comment]
I stumbled onto this issue from my own searching for a way to easily unhide selected columns in the columns sheet. I've worked out the following to build an inverse of `g-` in the columns sheet:

```py
# I've added the below to my .visidatarc file
ColumnsSheet.unbindkey('g+')
ColumnsSheet.addCommand('g+', 'unhide-selected', 'onlySelectedRows.hide(False)', 'unhide selected source columns')
```

I'm pretty delighted by how easy it was for me to figure this out by grepping within this repo. Grepping for `hide-selected` took me to

https://github.com/saulpw/visidata/blob/f40ba4cb7c59f526bda9ea5e438f11c9eced21c9/visidata/metasheets.py#L140

which then led me to grep more generally for `hide`. I saw a hit in the columns file, which shows me it could take a `False` argument to unhide:

https://github.com/saulpw/visidata/blob/f40ba4cb7c59f526bda9ea5e438f11c9eced21c9/visidata/column.py#L287-L291
