### ISSUE TITLE
[wishlist] Keep history files for the various kinds of prompts

### ISSUE THREAD

**Issue by tsibley** [saulpw/visidata#468]
VisiData does a great job of preserving history for various kinds of readline-based prompts it issues, like the ones for Python expressions or regex searches. The histories only last the lifetime of the vd process, however, and it'd be nice if they were more permanently written to history files, the way shell history generally works.

**Comment by saulpw** [comment]
This is a good idea!  I'd love to have this be an option, though I'm not sure it should be enabled by default.  We could even use the information already being captured with `options.cmdlog_histfile`, though then it wouldn't be according to history "type" (unless we did something else to annotate the histfile).

**Comment by saulpw** [comment]
Kondo'ed

**Comment by saulpw** [comment]
Reusing `options.cmdlog_histfile` was too thorny.  So I added `options.input_history` (default `''` meaning disabled)  which is a basename in `visidata_dir` to which `.jsonl` is appended and the inputs persisted, by type (with a catchall for untyped inputs).  This sheet can be opened with the `open-inputs` command (and edited/saved if desired).

There is no catchall, so any `input()` that wants a history needs to specify a specific *type* of history.  We should do an audit at some point of all prompts and statuses, but in the meantime please let us know here which commands need history and which type.

Thanks go to @ajkerrigan for keeping this pinned open and to @anjakefala for helping pull it together.
