### ISSUE TITLE
[wishlist] .ods loader (LibreOffice/OpenOffice spreadsheet)

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#473]
ODS it's one of the "classic" table format.

It could be enabled using [pyexcel](https://github.com/pyexcel/pyexcel) and pyexcel-ods.

I'm not able to implement it as extension, but I'm writing here because I think it would be great to have it in vd.

Thank you

**Comment by saulpw** [comment]
Yes, this would be nice.

**Comment by frosencrantz** [comment]
@saulpw  or @anjakefala  do you keep a list of approved/closed issues?  In case there are volunteers who are looking to help contribute code?  There are many closed issues due to different reasons.  In this case, you are saying good idea, but you won't implement it.  Or maybe an issue tag?

@aborruso hope you are doing well.

**Comment by aborruso** [comment]
@frosencrantz thank you very much. I'm fine!

How are you?

It's a good idea to create a list for "how to help" section

**Comment by anjakefala** [comment]
@aborruso, I am really glad that you are okay. :purple_heart: I hope everyone here has their needs taken care of

We have this list on the develop page: https://github.com/saulpw/visidata/tree/develop#help-and-support. I do not actually remember what happened to that maybe someday list. I think what likely happened is that we got such an overwhelming influx of feature requests at some point that we stopped maintaining it. 

~~If someone were to go through the issues, and leave a comment "this is an issue for which you said you were open to a PR", I can add a help wanted tag to those,~~ and add a link to a filter for all issues (closed+opened) with a ~~help wanted~~ tag. Combing through all those issues myself, right now, just fills me with dread. I have not gone outside in a week.

**Edit**: See comment below, please don't leave comments!

**Comment by anjakefala** [comment]
I just remembered that is what the `[wishlist]` tag is for. I will add a link to a filter for the `[wishlist]` tag.

**Comment by anjakefala** [comment]
Done: https://github.com/saulpw/visidata/commit/ae0f2aaa0bb97ad738d1239498e78e5fe632f41d

Sorry everyone for the spam. =( I am a bit frazzled this morning.

**Comment by ghost** [comment]
Note: As of pandas 0.25, the `pandas.read_excel` function will [automatically read ODF/ODS files](https://pandas.pydata.org/docs/user_guide/io.html#opendocument-spreadsheets).

Unfortunately, this won't immediately work with the existing [visidata pandas loader](https://www.visidata.org/docs/loading/), as visidata will try to call `pandas.read_ods`, when it instead needs to call `pandas.read_excel`.

Also of note, pandas uses `odfpy` to read ODF/ODS files, so this may be a good option to investigate if we want native ODF support in visidata.
