### ISSUE TITLE
[date] error with "date" column type and python expressions

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#474]
Pressing `@` will set the column type "date". However, this doesn't seem to play well with using `=` to operate on that column. I expect that, if I have two date columns, `foo` and `bar`, and I press `=` and type `foo > bar`, i will get output showing if the date in column foo is further towards the future relative to the date in column `bar` (specifically, what I'd expect is for `foo` and `bar` to be Python `datetime` objects, which have comparison operations defined). Instead, I get a red `!` symbol in the constructed column (presumably indicating an error - I do not see an error message).

I'm aware that time as a concept is quite a large can of worms, but it seems reasonable for the date type to be cast into a python `datetime` in derived columns.

**Comment by anjakefala** [comment]
![Screenshot from 2020-02-21 09-36-26](https://user-images.githubusercontent.com/7489659/75057363-b0b51200-548d-11ea-9c63-06a9005987a8.png)

I agree it is reasonable! We actually already support it, so I am really curious about your error.

Can you please walk me through the steps you took in more detail or upload a gif?

To obtain the contents of an error in a cell, you press `z Ctrl+E` on the cell. Please share the resulting stacktrace with me!

**Comment by anjakefala** [comment]
(More information about your environment would also be nice.) :angel:

**Comment by WesleyAC** [comment]
Ah, indeed. Looks like I mistyped one of my column names, sorry for the noise :(

It'd be useful if the tip about `z Ctrl+e` was displayed somewhere upon error - I think I was expecting a note about what the error was in the statusbar (I've definitely seen that before, presumably for other categories of errors) - displaying either the error or instructions to see the stack trace (or both) in the statusbar would be really useful. Should I file another issue for that?

**Comment by saulpw** [comment]
Whether and where to offer hints about how to diagnose errors is a larger topic and is not a directly actionable issue.  After the API settles and we release 2.0, we'll probably turn some of our attention to better usability for newcomers.  For now though this powerful secret magic will just have to be passed by word-of-mouth :)
