### ISSUE TITLE
[key columns] If a key column is wider than the screen no other columns can be seen

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#475]
**Small description**
If a key column is wider than the screen no other columns can be seen or scrolled on the the screen.
It is non-obvious what is wrong.

**Expected result**
See some part of non-key columns.

**Actual result with screenshot**
Sorry no screen shot.   But you would see that all you can see is the wide key column, but you can move the cursor to other non-key columns, but you can't see the cursor or the non-key column

**Steps to reproduce with sample data and a .vd**

Several ways to get there:

* Use a command `g_` or `_` when you have a key column that is wider than the screen.
* The key column is already  wide, but then you shrink the width of the screen, smaller than the width of the key column.

**Additional context**

This might be working as expected, just don't do that.  However, it happened to me a couple times, when I had a wide key column, and the screen became narrow. it seems like the key columns shouldn't be able fill the width of the screen (unless there are only key columns).  So the key columns should leave a little space for non-key columns.  Configurable by the user.

**Version**
Using head of develop.

**Comment by saulpw** [comment]
In bug reports, please include the exact version you're using.

**Comment by saulpw** [comment]
This would be a lot of code for an edge case that has a reasonable workaround already (use `z-` or `z_` on the keycol to make it small enough).
