### ISSUE TITLE
[wishlist] Build automated column renaming into visidata

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#476]
There is already a useful plugin already by @jsvine:
    https://github.com/jsvine/visidata-plugins/blob/master/plugins/vdnormcol.py

It renames columns in way that makes them valid python identifiers.  

It has some limitations:

  *  empty column names are left empty
  * it doesn't check column names for conflicts with globals (https://github.com/jsvine/visidata-plugins/issues/5)

It is possible to correct this with a plugin, and Jeremy's plugin is a great starting place.

There are many Visidata command that allow you to refer to columns by name.  To be able to use this, it would be useful if Visidata itself had some basic ability to fix column names so they all can be used from Python expressions. Or make it easier to implement something like Jeremy has done.  It seems like people might have different preference for how to name columns, (for example, maybe just letters like a spreadsheet.)

Not sure what easier would look like.  It seems like the main things would be a renaming pattern, ways to handle conflicts with names, and conflicts with globals.

**Comment by anjakefala** [comment]
```
Or make it easier to implement something like Jeremy has done.
```

Could you please elaborate on this point? What are the difficulties you face in adapting a plugin like jsvine's to handle global namespace conflicts and unnamed columns?

**Comment by frosencrantz** [comment]
Yes, my last paragraph was to sort of ask what do I really mean.  I'm not sure what "easier" would be.
This may be too ambiguous.

I guess the main steps involved with making good names are:
  1) Determine if you want to even change a name (e.g. vdnormcol doesn't change empty strings.)
  2) scrub names of unwanted characters.  (spaces,dashes to underscores, upper case to lower)
  3) change names if there are names with conflicts with other columns, globals.

If the code had hooks for each of these three operations, I guess that would make it easier.
    1) boolean functions name_should_be_fixed
    2) function that changes names.
    3) function give me an alternate name for name since there is a conflict


Some schemes I can think of are:
   Just use spreadsheet column naming.  The names would just be a-z, a[a-z], b[a-z], etc.  You would want to do that for every column.  You would need to skip names like 'in' or 'or'.
   Use the vdnormcol, but also include empty col names.

**Comment by frosencrantz** [comment]
Also, making it easier is for extra credit.

I think having a basic renamer than can change every column into a usable name from a python expression without conflicts with other columns or globals is the basic functionality.

I felt any solution would be subjective, and so it seemed like allowing users to customize would also be important. Though any such customization would be extra credit.

**Comment by saulpw** [comment]
I don't see anything directly actionable here, so closing for now.  Put together a workable solution in plugin form and we can consider whether it belongs in stock VisiData.
