### ISSUE TITLE
[wishlist] `ls` format:  Multiple columns of columns.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#477]
When you run the `ls` command, if the names are narrow enough, you get rows and columns of the file names.   It would be useful to be able to have a similar mode in Visidata.

Maybe this could be done via repeated columns.  So if the columns are narrow enough, instead of scrolling off the bottom, display the next rows to the right.  Repeat as much as there is space to the right.  

To make the data more narrow, just have multi-column mode for the key columns.
To me this would be a way to navigate long data.  Once you find the rows of interest you would get out of this directory mode, and could see the data in it's wider format.

**Comment by saulpw** [comment]
This is antithetical to the design of VisiData.

**Comment by frosencrantz** [comment]
Hi @saulpw, would you be willing to explain more about why?

I am very surprised by this answer. VisiData is able to handle graphs in the terminal and hierarchical data.  It seemed like it could work with thin/long tables/data by wrapping them vertically.  But I don't know VisiData as well as you.  This was an earnest suggestion.

**Comment by saulpw** [comment]
I'm not sure I can really explain it.  Rows are objects, columns are functions.  Changing that element of the design is like changing Euclid's 5th postulate in planar geometry.  Consider that you'd have to think through nearly every interaction in this mode and ask "how would this have to work differently to be compatible?"  Like pick any command.  What would `d` (delete-row) do, for example?  or `=` (addcol-expr)?  It's just a non-starter at a core level.

**Comment by frosencrantz** [comment]
@saulpw  you are suggesting a very deep solution.  It might be possible to do something superficial and useful.

If you have a long, thin column, would it be difficult to wrap it on the screen but in other respects treat it as that long column.

So if we only had a 3line by 10column screen and a long 9 row column with name N:

```
N
A
B
C
D
E
F
G
H
I
```

Could it be presented on screen like so (not sure if the column titles would be on the second and third part of the wrapped column.

```
N N N
A D G
B E H
C F I
```

Even if navigation and other commands still treated it as that long column, for example:
  * Down from C would get you to D.
  * You can't go left or right from E

This is really just intended to be a view of the wider part of the table.  Like the Frequency sheet is a subset of the source sheet.

In this example the delete-row would still work as if we were in the long table, just you can see more of the table
