### ISSUE TITLE
[sqlite cosmetic] Sqlite index sheet polish items

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#479]
**Small description**
Two small polish items on the sqlite index sheet:
  * sqlite items name "sheets" →"tables"
  * initial row&col columns counts are incorrect for unloaded tables
      * For unloaded tables it has row counts of 0, and column counts 1.
      * vd doesn't make it clear that it hasn't loaded the tables, it just has names.

**Expected result**
*  items should be named "tables"
* col&row counts should be `?` / `unloaded` or should be correct.
    * It might be possible to actually get column counts about tables.
    * Row counts could be found with 'select *'.

**Actual result with screenshot**
Sorry no screenshot.  If the results are not easy to see let me know.

**Steps to reproduce with sample data and a .vd**
Open a sqlite database with vd.

**Additional context**
Please include the version of VisiData: latest develop version

**Comment by saulpw** [comment]
Yes, I agree, `tables` is a more precise term. `sheets` is pretty embedded in the docs though and it will be a lot of work to look at every usage and determine whether it means `table` (with columns) or `sheet` (either table or canvas).  Are you willing to do any of this work?

As for your second item, you could try a CellColorizer and see how it feels: `lambda s,c,r,v: s.rows is UNLOADED`

**Comment by saulpw** [comment]
I would love it if you submitted a PR for either or both of these.  In particular the first item is trivial: just add `rowtype = 'tables'` to SqliteIndexSheet.

**Comment by frosencrantz** [comment]
Thanks @saulpw .  The first item might be a one line change. Sorry no code at this point.

I can give you words...

**Comment by saulpw** [comment]
Yes, it's a one-line change.  Most of the effort involved is going through the process.  Anyone is welcome to contribute to make the software better as they see it, but as a volunteer open-source project we aren't excited about make-work tasks created by people who want awesome free software but aren't willing to do any of the work.
