### ISSUE TITLE
[wishlist] HTTP API pagination loader

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#480]
I'd love to know if this was possible and maybe have a crack myself but I'm unsure if it is.

I have a graphql API which supplies tabular data that I would like to analyse. The data should be streamed as it could be updated in the database, and could be from 1, to millions of rows. The API has pagination and an offset value.

Question is, could I build a loader which would be able to load data from this API, and be able to do all the things like navigation, searching, summarisation etc. without having to download the whole table and load it in as a CSV (or another format). Essentially only retrieving what it needed to show the user what is in their view, stream the data.

I'd also need to be able to modify some of the rows and push that to the API. Like tagging and commenting, but that'd be secondary to actually being able to load the data of course!

Also, do you use a terminal GUI library like (prompt-toolkit) or is it all from scratch?!

TIA!

**Comment by saulpw** [comment]
Hi @geekscrapy!  Yes this should be doable, and probably pretty easily.  If you have some standalone Python code that can generate the "rows" of data, then it is straightforward to make a loader to get it into VisiData and work with it how you like.  I might also like to use an HTTP API loader for some things myself.  Come by the #visidata channel on freenode, or we can try to have the discussion here if you have specific questions and/or some code to review.

**Comment by anjakefala** [comment]
> Also, do you use a terminal GUI library (like prompt-toolkit) or is it all from scratch?!

VisiData makes use of the [curses module](https://docs.python.org/3/howto/curses.html), which is part of the standard library. =) The only dependency for core VisiData is [dateutil](https://pypi.org/project/python-dateutil/) for the `date` type. @saulpw wrote the terminal interface.

**Comment by saulpw** [comment]
Closed without prejudice.
