### ISSUE TITLE
[wishlist] xdg support

### ISSUE THREAD

**Issue by teto** [saulpw/visidata#487]
hi,

I've just discovered visidata and this might very well become one of my favorite programs as I develop/look into data files quite a bit.

I see a v2 is coming so I believe it would a good time to support the XDG spec, wouldnt it ? I see it was removed some time ago`remove .visidatarc support in PWD or XDG; only $HOME/.visidatarc supported now`

**Comment by anjakefala** [comment]
The issue that references the conversation where it was originally removed: https://github.com/saulpw/visidata/issues/93

**Comment by anjakefala** [comment]
> I've just discovered visidata and this might very well become one of my favorite programs as I develop/look into data files quite a bit.

:blush: :blush: :blush:

**Comment by saulpw** [comment]
Hi @teto, thanks for the note!  

I agree in principle with XDG and de-cluttering dotfiles, but XDG proved to be more complicated than I was willing to implement (and I don't want to take on a dependency for it).  `$HOME/.visidatarc` seems to work reasonably well for most people, and XDG people can make a symlink which should suffice.  (That's what I do with [my dotfiles](https://github.com/saulpw/dotfiles).)

**Comment by ptman** [comment]
Would it be possible to set an env var for file locations? Also ~/.visidata/cache would be nice to send to ~/.cache/visidata

**Comment by saulpw** [comment]
Hi @ptman, as of VisiData 2.0, you can use the environment variables `$VD_CONFIG` and `$VD_DIR` to override the default locations of `options.config` and `options.visidata_dir` respectively.

The problem with using a `.cache` directory is that it won't be available on all systems (e.g. Windows).  On Linux and OS/X, you can create a symlink if you want:

    mkdir ~/.cache/visidata
    rm -rf ~/.visidata/cache
    ln -s ~/.cache/visidata ~/.visidata/cache

**Comment by ptman** [comment]
Ah, I didn't find those documented. A symlink does not solve my issue with ~/.visidata, which is that I want to get rid of dotfiles. But there are other reasons to support XDG basedir spec ( https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ). By having all cache files in a single ~/.cache you only have one thing to exclude from backups. And config files should probably be per user, while cache files should be per machine if the user login and home directory is shared on several machines in a larger computing environment (school, enterprise, lab, ...)

There are probably several python libraries for handling the, but unfortunately not in the stdlib like in go https://pypi.org/project/xdg/ ( https://pkg.go.dev/os#UserCacheDir )

**Comment by teto** [comment]
xdg config is nice since you don't have to tweak on a per application basis (e.g., VD_CONFIG), it clutters the environment too.

**Comment by saulpw** [comment]
Yeah, it's too bad it's so complicated!  If you (or anyone) are motivated to add XDG support without adding a (non-stdlib) dependency, please submit a PR.

**Comment by jck** [comment]
@saulpw would you be ok with with a PR which vendors in https://github.com/ActiveState/appdirs/blob/master/appdirs.py

**Comment by saulpw** [comment]
@jck Yes, that would be fine, and much appreciated.
