### ISSUE TITLE
[wishlist] Correlation matrix

### ISSUE THREAD

**Issue by meddulla** [saulpw/visidata#488]
This is an absolutely awesome tool. Thank you for developing it. 

A good addition to the summarizing data section would be a correlation matrix between (numeric) columns.

This would allow for a quick check of columns to exclude for example.

**Comment by saulpw** [comment]
Hi @meddulla, thanks for the suggestion!  I agree, that would be a nice feature, and would be reasonably easy to do for someone who knows how to generate a correlation matrix.  If you or anyone is interested in putting together some Python code for this, we could turn it into a plugin in short order.

Closing for now as per wishlist policy.
