### ISSUE TITLE
[wishlist] Add support to visidata for powerline

### ISSUE THREAD

**Issue by PaulHiemstra** [saulpw/visidata#490]
I really like working with [powerline](https://github.com/b-ryan/powerline-shell), which greatly improves the visual style of the bash shell. In addition, there are plugins for vim and tmux which look really great. 

I would like to see support for powerline in visidata.

**Comment by saulpw** [comment]
Hi @PaulHiemstra, this is a really cool idea!  It could pretty easily be a plugin for VisiData as well.  We'd love to check it out when you've put something together, and we can add it to the list of plugins for 2.0 when it's ready.

Closing for now as per our wishlist policy.
