### ISSUE TITLE
[bug:v2.-4dev] First row+col of table switches with second row if double clicked

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#492]
With version v2.-4dev, if the top row or first column (I believe of any sheet) is double clicked with a mouse, it switches with the second row. Unsure if this is intentional, but doesn't happen in earlier versions.

This bug was tested, and existed with, DirSheet, TsvSheet and FreqTable using OSX and iTerm3

**Comment by anjakefala** [comment]
Mouse click-and-drag was added since v1.5.2!

So that is why it does not show up in previous versions. I am not sure if this specific way it expresses is a bug.

**Comment by geekscrapy** [comment]
Unsure if you were asking me to test, but I did, and I'm definitely not click dragging, just double clicking 😁

**Comment by saulpw** [comment]
Nice catch, @geekscrapy.  Should be fixed now.
