### ISSUE TITLE
[wishlist pcap] add SLL support

### ISSUE THREAD

**Issue by teto** [saulpw/visidata#494]
**Small description**
 I am not able to load packets from this pcap in visidata 2.-3 
https://github.com/teto/mptcpanalyzer/blob/master/examples/client_2_filtered.pcapng
(because of a missing ethernet layer ?)
as discussed on irc CC @layertwo 

`--debug` shows errors about the inability to download files such from wireshark.org. The output is garbled (very annoying, can I redirect to a file ? like `vd 2>log.txt`).

**Additional context**
v2.-3

**Comment by anjakefala** [comment]
Those files have now been re-added, and their new urls updated on the `develop` branch. Can you update your local version of `vd`, and let us know if you are still having issues?

**Comment by teto** [comment]
so I now see the vd interface with `dpkt.dpkt.NeedData` (e.g., no packet is loaded).

**Comment by layertwo** [comment]
The issue stems from a different type of packet structure in the pcap. We expect to have an actual Ethernet layer in the capture, but the with the sample capture @teto provided it has a pseudo-Ethernet layer known as SLL (or reported as Linux cooked capture). See more here: https://wiki.wireshark.org/SLL

The good news is that dpkt has an SLL option, so there's a little bit of work needed to implement that into the default pcap_reader.

**Comment by saulpw** [comment]
Submit a PR and we'll review it!  Kondo'ing for now.
