### ISSUE TITLE
Editing savename results in incorrect input.

### ISSUE THREAD

**Issue by c-bun** [saulpw/visidata#5]
When saving a file, using the 'delete' key to edit the save name results in '.' being inserted into the line of text.

**Comment by saulpw** [comment]
The '.' is actually a displayable substitute for an unprintable (control) character.  On the Linux and OS/X configurations that I'm using the delete key works as desired.

Please answer the following questions to help fix the bug:

1. What platform and terminal are you using vd on?

2. What does the status line display when you press the 'delete' key in the main mode?  (If nothing, what action does it appear to take?)

**Comment by c-bun** [comment]
Thanks for the quick reply! It could definitely be an issue on my end. 

I'm running OSX 10.11.6
Pushing the 'delete' key in the main mode displays ``no command for key "^?" (127)``.

**Comment by saulpw** [comment]
It probably has something to do with your TERM variable.  I would have thought that curses.KEY_DC would be 127 but apparently not.  So I'll set 127 to be like Backspace and then we don't need a configuration option (yet).  Look for it in the next release in a few days.  Thanks for the report!
