### ISSUE TITLE
Allow field-editing with user's own editor

### ISSUE THREAD

**Issue by DataBranner** [saulpw/visidata#50]
When a cell contains a substantial amount of text, most users will probably prefer to use their own editor, as set for the system or in VD options. I think it's reasonable for that to be the normal behavior whenever the size of the text is greater than the visible width of the cell. 

Some users may prefer never to load their editor, and others may prefer to use their own editor all the time, even for tiny strings. Still others may want to use their own editor whenever the size of the text is something other than what I've described.

I suggest using a single command to begin editing a cell, and having a cut-off string-length set in options — between editing VD's built-in tools and editing with one's own editor. I think this single command would more naturally be `ENTER` than `e`, but perhaps they should co-exist, since `ge` is not really replaceable by `g-ENTER`. `^` for editing column-headers is a different use case and would remain as is.

**Comment by saulpw** [comment]
Good idea, there might be some users who would get some benefit from this.  The edit capability of VisiData is not its primary use though, and I can foresee some issues with interactions between vd and the editor (how can an edit be canceled?), so this is low priority for me right now.  Submit a PR if you get it working and we'll try to get it integrated.

**Comment by saulpw** [comment]
editText supports `Ctrl+O` to launch the editor in $EDITOR.

**Comment by m-gris** [comment]
Super late comment... But who knows, might still be helpful / relevant:
`Ctrl-Z` might not be the best choice since it typically is used to suspend jobs.

**Comment by saulpw** [comment]
That's a good point, @m-gris, and we did wind up changing that (thanks to urging by @ingydotnet).  Now it's Ctrl+O (and I've updated the comment to reflect that).

**Comment by m-gris** [comment]
@saulpw : Great ! 🙏 😄
