### ISSUE TITLE
VisiData ignores final character of stdin if no newline

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#502]
**Small description**

```sh
echo -n "abc" | vd -f txt
```

**Expected result**
```
 text ║
 abc  ║
```
**Actual result with screenshot**

```
 text ║
 ab   ║
```

<img width="58" alt="Screen Shot 2020-04-09 at 11 53 55 AM" src="https://user-images.githubusercontent.com/534702/78914736-d8b9fe00-7a58-11ea-881f-ef18b962cee6.png">

If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
See above.

**Additional context**

- VisiData version: v2.-4dev (though also true of v1.5.2)
- Shell: bash
- Platform: MacOS

Thanks in advance!

**Comment by saulpw** [comment]
Thanks for the bug report, @jsvine!  Should be fixed now.

**Comment by jsvine** [comment]
Awesome, thanks!
