### ISSUE TITLE
[xml loader] Exception thrown for path column

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#504]
**Small description**
When reading XML files the path column has an exception.

**Expected result**
The path value for that xml element.

I don't always read xml data, but when I do I see that this column has an error.
Also, it looks like there are no xml tests for the xml loader to catch an error like this.

**Actual result with screenshot**
Sorry no screenshot.  But if there was you would see the path column has '!' marks on the right side of every cell in that column. 

```
visidata/loaders/xml.py", line 25, in <lambda>
     Column('path', width=0, getter=lambda c,r: c.sheet.source.getpath(r)),                               
 AttributeError: 'NoneType' object has no attribute 'source'                           
```
**Steps to reproduce with sample data and a .vd**

Read an xml file, then use 'gv' command show all the hidden columns.  All cells in the path column will have an exception as shown above.

**Additional context**
Please include the version of VisiData.
Latest develop branch version

**Comment by saulpw** [comment]
Thanks @frosencrantz, that was a good repro.  There were bound to be other problems with that code too.  Should be fixed now.
