### ISSUE TITLE
[wishlist html] Provide way to access non-table elements

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#505]
When loading XML or HTML files the modules used to load the data have a native format.  Within Visidata it is not possible to get to the native data structure of the data for HTML or XML files.

For HTML files you can only see the tables.  If you wanted  to pull out data from a list or some other HTML structure you can't do it with Visidata.  For HTML it might be useful to also expose the whole HTML document as a Visidata sheet.

With XML, most of the data is provided to a sheet.  But it would be useful to be able to use the lxml library to  extract a tag or attribute if Visidata doesn't provide the data in a useful format.

**Comment by saulpw** [comment]
I agree, @frosencrantz, it'd be great if the XML and HTML loaders had this functionality (and a lot more!).  We'll add it to the wishlist.
