### ISSUE TITLE
[v2.-4dev/3702790/unexpected] Columns move left when a key column is clicked

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#508]
Scenario: You have more columns than the screen is able to show, and at least one key column

Expected: Move to the far right column (g->) and then click on a key column with the mouse. Columns should stay in place (visually), only with the key column now selected.

Actual: Move to the far right column (g->) and then click on a key column with the mouse. The columns visually jump back to the first column.

This is not a massive issue, but one which is unexpected - I wanted to have the far right columns in view, but select a keycol so I could yank its cell (zY) value. I often tend to not make a note of the actual row I'm selecting and just go to select the column, however when the columns jump back I loose my reference of the cell I actually want to yank the data for. This means I am forced to use the keyboard instead of the mouse.

**Comment by saulpw** [comment]
Fixed.
