### ISSUE TITLE
[cell display] A column with a width of 1, with data of a single character always displays ellipsis 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#512]
**Small description**
Set the width of a column to 1.  If the data in the column is only 1 character wide, I see only an ellipsis.

**Expected result**
See the single character data vaue.

**Actual result with screenshot**
Sorry no screenshot.  If this is not reproducible let me know.

**Steps to reproduce with sample data and a .vd**
Create a new table (A) with 1 column
Change the column width to 1
Add a row (a)
Edit the cell, insert a single character, like 'a'.

You only see the truncation character (ellipsis) in the cell., not the single character value.

**Additional context**
Using latest version from develop branch.

**Comment by saulpw** [comment]
Do you have an actual use case for this, @frosencrantz ?  IIRC it was a mild pain to get a minimum column width of 2 working, and I decided not to spend the effort on 1 because it would be too much work for zero reward.  I've never had a need for it myself.

**Comment by frosencrantz** [comment]
I do. I have data with many rows and columns.  The columns are ordered in a sequence, and the value of each column has been boiled down to a single character.   Example of single character data would be T/F for True/False, or *nix file permissions rwx.   Other examples might be a Mindsweeper board or a crossword puzzle with just the letters.

I also would like to be able to remove the column separators so that I can get even more columns on the screen, but that felt more like a feature request.  Needing 2 screen columns and a third one for the separator makes the display of this data a lot wider than it needs to be.

It boils down to wanting to be able to squeeze more data into the space of my terminal.

It is possible to combine the columns into a single wide column, which makes the data as compact as I'm looking to get.  I tried that, but lost the ability to color individual cells, and to provide wider data in the column like for the header.

**Comment by saulpw** [comment]
Ah, I see.  You can remove the column separators by setting `options.disp_col_sep=''`.  I've used that myself in vdgalcon to get an exact column width of 2, which I agree, is useful.

If you want columns of width 1 to display the first character instead of ellipsis, you can [subscribe to my Patreon](https://patreon.com/saulpw) and I'll make it happen.

**Comment by frosencrantz** [comment]
Thanks for the tip about empty `options.disp_col_sep`.  That works and helps.

I would like to help increase the number of sponsors.  I'm looking forward to you hitting your goal of 100 sponsors.  Right now I can't contribute as a sponsor, I'll wait until a real sponsor does become interested in this feature.

**Comment by frosencrantz** [comment]
There is exuberant joy in Whoville!  Thanks @saulpw!
