### ISSUE TITLE
[build] Package into VisiData a set up of unit tests + basic functionality tests

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#516]
We want a set of tests to help catch packaging errors. These are part of the requirements for packaging authorities like Debian, GNU Guix, and Homebrew.

Basics:
* Test that `Ctrl+H` works
* package in the unit tests
* benchmark.csv + some test .vd to make sure it loads and maybe saves

**Comment by ryanprior** [comment]
If you can ping me when this lands I'd appreciate it!

**Comment by anjakefala** [comment]
Hi @ryanprior! I packaged a basic set of unit tests into VisiData.

Tests are run by executing `pytest visidata/tests/` wherever the VisiData root
directory is installed. Sadly, `setup.py` has deprecated `setup.py tests`.

This will be part of VisiData 2.0.

I hope that helps!
