### ISSUE TITLE
vd 2.develop: impossible to open html sub-sheet

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#521]
Hi,
if I run

```
curl -L "https://en.wikipedia.org/wiki/Olympic_medal" | vd -f html +:table_2:1:1
```

vd does not open `table_2`. What's wrong in my command?

Thank you

**Comment by anjakefala** [comment]
It was a bug! >___>

Very nice catch! Should be fixed on develop.

**Comment by saulpw** [comment]
Also, @aborruso, note that `vd https://en.wikipedia.org/wiki/Olympic_medal` will also work (don't need curl or even `-f html`).

**Comment by aborruso** [comment]
@anjakefala @saulpw it works great.

Thank you very much

**Comment by aborruso** [comment]
Hi,
I have no problem to open the sheet "results" of the attached html file, running `vd input8.html` and then selecting it and clicking return

![image](https://user-images.githubusercontent.com/30607/82782687-34034c80-9e5d-11ea-9309-52f64959b345.png)

But if I run `vd +:results:: input8.html` I have the below error. I'm using the latest develop version.

Thank you

```
Traceback (most recent call last):
  File "/home/aborruso/.local/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/home/aborruso/.local/lib/python3.7/site-packages/visidata/main.py", line 213, in vd_cli
    rc = main_vd()
  File "/home/aborruso/.local/lib/python3.7/site-packages/visidata/main.py", line 152, in main_vd
    vs = vd.getSheet(startsheets[0]) or sources[-1]
  File "/home/aborruso/.local/lib/python3.7/site-packages/visidata/basesheet.py", line 216, in getSheet
    sheetidx = int(sheetname)
ValueError: invalid literal for int() with base 10: ''
```


[input8.zip](https://github.com/saulpw/visidata/files/4675415/input8.zip)

**Comment by anjakefala** [comment]
Hi @aborruso! Thanks for the bug report, and thanks for the sample data. Sorry it took so long to fix. My change had a small regression. It should work now.

**Comment by aborruso** [comment]
@anjakefala thank you very much
