### ISSUE TITLE
[wishlist] have vd foo.zip -f fixed apply to the inner files

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#523]
:grinning:

**Comment by geekscrapy** [comment]
Are you able to change the format once the format is already loaded? I use the zip loader a lot but I don't always know what file type in it until I open it. Could be a log file, could be a binary file, it would be nice to be able to change the loader for the particular sheet! I guess that would solve this issue too?

**Comment by tsibley** [comment]
@geekscrapy To set `-f` once you're in a VisiData session, you can open the options sheet with <kbd>Shift</kbd>+<kbd>O</kbd>, find the `filetype` option row, and edit the value (e.g. to `fixed`).

**Comment by anjakefala** [comment]
This is now on develop!
