### ISSUE TITLE
[develop] postgres: cannot open rows on this sheet

### ISSUE THREAD

**Issue by dufferzafar** [saulpw/visidata#525]
**Small description**
Can't view postgres tables properly. When pressing enter on a row, error message `cannot open rows on this sheet` shows up.

**Expected result**
Deep dive into a row.

**Actual result with screenshot**
![image](https://user-images.githubusercontent.com/1449512/80194750-77895180-8638-11ea-8c00-fb47f535b9f4.png)

**Additional context**
`saul.pw/VisiData v2.-3`

**Comment by saulpw** [comment]
Hi @dufferzafar, those are the actual rows in your `ticket_items` table.  How would you want them to be "opened"?  This acts just like any other data source (csv, json, etc); source rows in general can't be dived into.

**Comment by dufferzafar** [comment]
For one, I'd like to be able to view the data in the `action_data` column. Which shows `[1]` 

I thought diving into that row would show me that data.

**Comment by saulpw** [comment]
At the moment there is no standard meaning of 'dive' for source rows.  Things you might want to try are `Ctrl+Y`, which opens the row as a Python object,  or `z Ctrl+Y`, which opens the cell as a Python object, or `(`, which expands the column if it contains a list or a dict.
