### ISSUE TITLE
Is it possible to disable tables rows and columns counting?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#526]
Hi,
I'm testing the very [useful plugin](https://github.com/aswan89/visidata_plugin_genericSQL) of @aswan89, using an Oracle database.

In this db there are some very big tables, and vd cannot complete reading the list of tables inside it, because it must read the number of rows and columns of each table. It probably could do it, but it seems like it takes too long. It would be enough for me to have the tables list.

It would be very great, to have the option not to do this count, and to have only the list. Is there this option?

I'm making here this question, because it seems to me a generic vd question.

Thank you

![image](https://user-images.githubusercontent.com/30607/80260426-2e60ee00-8688-11ea-8bd5-59cefc6be042.png)

**Comment by aswan89** [comment]
@aborruso you should probably open this within my plugin repo since this functionality is contained entirely within the plugin, not visidata itself.

**Comment by aborruso** [comment]
ok, thank you @aswan89

**Comment by frosencrantz** [comment]
The builtin sqlite loader by default  doesn't give row and column counts.  The issue I have is that for tables that haven't been opened, it reports tables have row counts of 0, and column counts 1. I found this misleading.  https://github.com/saulpw/visidata/issues/479  

@aswan89 if you do change the behavior of your plugin, it might be good to make it clearer that the tables haven't yet been loaded.

This is explained in for csv files:
  https://www.visidata.org/blog/2020/unloaded/

**Comment by anjakefala** [comment]
> The builtin sqlite loader by default doesn't give row and column counts. 

*for unloaded sheets.

Decision was made for the sake of performance. This is consistent behaviour for all of the loaders.
https://www.visidata.org/blog/2020/unloaded/

> @aswan89 if you do change the behavior of your plugin, it might be good to make it clearer that the tables haven't yet been loaded.

Can you please move this part of the conversation to @aswan89's plugin repo, as requested. Thanks @aswan89 for helping us out with that!
