### ISSUE TITLE
[develop bug] Undo has trouble when multiple sheets have the same name

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#527]
**Small description**

On `v2.-4dev`, VisiData gets confused when an undo references a non-unique sheet name.

**Expected result**

Undo should work as expected.

**Actual result with screenshot**

A screenshot here doesn't quite demonstrate the issue; see reproduction below.

**Steps to reproduce with sample data and a .vd**

Data: [test-100-nums.csv.zip](https://github.com/saulpw/visidata/files/4532248/test-100-nums.csv.zip) [unzip before proceeding]

Cmd log:  [test-100-nums-random-then-undo.vd.zip](https://github.com/saulpw/visidata/files/4532249/test-100-nums-random-then-undo.vd.zip) — but you'll have to press `U` to run the final step (it seems not to have been logged)

In this example, I select a random subset of rows, and then try to undo that ... but VisiData seems to get confused by the duplicate sheet names, because nothing is undone and instead I get an error in the status line:

> 2› test-100-nums| more than one sheet named "test-100-nums" | random-rows undone

... and the random-rows appears *not* to have been undone.

One solution *could* be just to make sure that `random-rows` (and all other commands) creates a unique sheet name. But I'm not sure that fully solves the issue, because what if someone, on their own, decides to name two sheets the same thing?

So, another possible solution would be to have some deeper mechanism that prevents duplicate sheet names, globally.

A third option (the one Google Sheets, for instance, seems to have taken) is to assign every sheet a unique ID separate from its display name, and to use that for all internal operations. That seems like the most robust solution ... but also possibly like a huge hassle to make work in VisiData?

**Additional context**
`v2.-4dev`, revision `96e5ab66` (Sunday, April 19)

**Comment by saulpw** [comment]
Sorry for taking awhile on this one, it slipped through the cracks.  Thanks for reporting it!
