### ISSUE TITLE
[wishlist] Allow undo-ing a reload?

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#528]
Command log and data: [undo-reload-log-and-data.zip](https://github.com/saulpw/visidata/files/4532253/undo-reload-log-and-data.zip) 

(Note: To fully reproduce, you'll have to press `U` to run the final step, which  seems not to have been logged.)

In the command log above, I load a minimal CSV, `addcol-expr ="a"`, press reload, and then try to undo. My expectation had been that the reload would have been undone, returning me to the pre-reload state ... but instead the statusline tells me that addcol-expr is "undone":

> 1› test-100-nums| addcol-expr undone

... which is unexpected, since that column does not exist on the (not-undone) reloaded sheet.

Ideally (for me), VisiData would simply be able to undo a reload. That said, I realize there may be other constraints / architectural priorities. So, as a backup, perhaps VisiData could just tell me that "reload commands cannot be undone"? That still leaves the question of how to handle undoing/redoing actions that came before the reload, though...

**Comment by frosencrantz** [comment]
If possible, it would be useful if reload could be undone.  I really like this idea.
Losing changes due to reload is a pain. I've also reported it: https://github.com/saulpw/visidata/issues/438
I feel a warning prompt would be helpful if undo is not implemented.

**Comment by anjakefala** [comment]
Hi!

I agree that undo-ing a reload would be convenient. I am going to give a quick overview of why this has not been implemented yet.

Undo works by keeping track of the previous state. Here is an example of one of the undo functions:

```
 def addUndoSetValues(vd, cols, rows):                                                                                                                                                   
     oldvals = [(c, r, c.getValue(r)) for c,r in itertools.product(cols, vd.Progress(rows, gerund='doing'))]                                                                             
     def _undo():                                                                                                                                                                        
         for c, r, v in oldvals:                                                                                                                                                         
             c.setValue(r, v)                                                                                                                                                            
     vd.addUndo(_undo) 
```

Reload is not a modification. It is not comparing the current rows to source, and making updates where it sees differences. It empties the existing rows and columns, and re-creates the sheet from source. 

What this means is to create an undo function for reload, you would need to save the entire state of the sheet pre-reload. This can easily become a memory issue with large sheets, especially if the user reloads frequently in a session. 

We do not foresee users reloading a whole ton, so I think there is a chance that this will end up getting implemented. It is convenient, and folks want it. =)

**Comment by jsvine** [comment]
Thanks for explaining, @anjakefala! Would a reasonable compromise be to prompt users on reload to ask whether to save the previous sheet in the undo-history? I feel like this might solve two things at once:

- The issue at hand
- Allowing people to cancel an unintentional reload (which in the past I have sometimes done when instead trying to run `random-rows` ... though it looks like that particular command has been demapped from the keyboard shortcuts in 2x)

**Comment by anjakefala** [comment]
This is on `develop` now! =)
