### ISSUE TITLE
Plain JSON lists cannot be loaded

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#529]
**Small description**

VisiData seems unable to load/render JSON files that are "plain" lists, such as:

```json
[
    "tt0177489",
    "tt0098168",
    "tt0233146",
    "tt0100816",
    "tt0122427"
]

```

**Expected result**

VisiData should be able to handle any valid JSON file.

**Actual result with screenshot**

See below.

**Steps to reproduce with sample data and a .vd**

[test.json.zip](https://github.com/saulpw/visidata/files/4532256/test.json.zip)

```sh
vd test.json
```

When I try running this, the right-statusline correctly tells me that there are 5 rows, but the core view is entirely blank. The main statusline says this:

> 1› test| [19x] AttributeError: 'NoneType' object has no attribute 'keycol'

The traceback for which is:

```sh
Traceback (most recent call last):
  File "[...]/src/visidata/visidata/basesheet.py", line 183, in checkCursorNoExceptions
    return self.checkCursor()
  File "[...]/src/visidata/visidata/sheets.py", line 508, in checkCursor
    if self.cursorCol.keycol:
AttributeError: 'NoneType' object has no attribute 'keycol'
```

The issue seems to be that VisiData is expecting the list items to be dicts, when instead they are just strings. Running vd test-2.json (see below; identical to test.json except that it wraps those strings in a simple dict) does work just fine.

[test-2.json.zip](https://github.com/saulpw/visidata/files/4532258/test-2.json.zip)

**Additional context**

`v2.-4dev`, revision `96e5ab66` (Sunday, April 19)

**Comment by ajkerrigan** [comment]
Let me take a look at this one - I just ran into the same error in a few cases where I'm piping JSON output to VisiData. Saving the same JSON and opening it as a file worked with no trouble. Could be related.

**Comment by anjakefala** [comment]
![image](https://user-images.githubusercontent.com/7489659/80781878-de22d980-8b28-11ea-8b06-7cf1b39098fc.png)
                             :1st_place_medal:

**Comment by ajkerrigan** [comment]
Hey @jsvine I think with #541 landed this should be kicked, but let me know if you notice any fishiness :)

**Comment by jsvine** [comment]
A big thanks!
