### ISSUE TITLE
[wishlist] When fetching data from URL, have format default to file extension

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#531]
Currently, when VisiData fetches data from a URL, it defaults to using the HTTP response's mimetype to determine the the file format and loader. 

One problem with this is that users rarely know what the mimetype of an HTTP response will be. They do know, however, what the file extension is! So it seems preferable, at least in my opinion, to use the file extension — if present and if matching a known loader — as the primary format clue, rather than mimetype. 

For instance, I think users would reasonably expect that this command:

```sh
vd https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
```

Would load the file as a CSV, rather than as `text`. Currently, instead a user would have to run:

```sh
vd https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv -f csv
```

What do you think?

**Comment by saulpw** [comment]
This is probably the right move.  If anyone wants to make it happen, we'll take a PR, but I probably won't put time into it myself before 2.0.

**Comment by anjakefala** [comment]
@jsvine Thanks Jeremy!! :tada:
