### ISSUE TITLE
[poll] Should `O` go to the global options and `zO` to the local options?

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#532]
I find myself more wanting to set options __globally__ more often than than locally. 

For instance, with the numeric binning options in `v2.x`. At first, I was setting those options via `O` on my base sheet, and the creating a frequency sheet ... only to be perplexed why there were no numeric bins! Ultimately, I realized that the binning is a property of the frequency sheet, not the base sheet, and that options set via local options are not inherited by derived sheets. A few possible solutions:

- Have derived sheets inherit their base sheet's options. But maybe that'd cause unexpected/undesirable side effects?

- Make `O` point to the global options sheet and `zO` point to the local/sheet-specific options shset, since I think people expect "options" in a program to apply broadly.

- Stay the course, not changing the options commands.

**Comment by anjakefala** [comment]
I would *also* like to expand this issue to encompass `D` and `gD`.

**Comment by anjakefala** [comment]
Thank you for starting this discussion @jsvine!

Here is the tension behind why this decision was made.

|Command | z-Prefix| Standard | g-Prefix|
|---------------| ------------- | ---------|------------|
| Shift+S  | N/A  | Sheet Stack | All sheets |
| Shift+C  | N/A  | Current sheet | All sheets |
| Shift+D  | Current sheet only | Current sheet + recursive | All sheets |
| Shift+O | N/A | Current sheet | All sheets |
| Shift+I | N/A | Current sheet | All sheets |

This table was why `cmdlog-all` got moved to `gD` and `options-global` got moved to `gO`.

Personally, I most frequently want `cmdlog-all` and `options-global`. If we do change both or either of them, we are going to have to settle for the mild inconsistency demonstrated by this chart. We may decide that that is worth it.

**Comment by jsvine** [comment]
Thanks, @anjakefala! A few questions and thoughts: 

- It seems the third and fifth rows of the table above both say "Shift+D". Is one supposed to be something different?

- As much as I see the beauty in a logically-consistent design, it seems like there might always be a bit of discrepancy. For instance: `Shift+S` arguably *does* apply to all sheets. It doesn't apply to deleted sheets ... but `g-Shift+C` does not apply to deleted sheets, either, does it?

- Personally, I'm fine with the `g-` and `z-` prefixes having *relative* meaning, rather than absolute meaning, with non-prefixed keystrokes being the "most common" (if there's ever such a way to adjudicate that) version of the command. That said, I defer to the maintainers 👍

**Comment by anjakefala** [comment]
> It seems the third and fifth rows of the table above both say "Shift+D". Is one supposed to be something different?

Hehehe. One was supposed to be for the **DescribeSheet**.

**Comment by saulpw** [comment]
[This is why we should try to use longnames when discussing commands :)]

I'm fine with either, and I've gone back and forth, most recently to `O`/`gO` back in November 2019 because it seemed like it was more consistent and easier to explain.  But if we're considering newbs at all, then `Shift+O` is a much easier first entry-point than `g Shift+O` anyway--and let's give them the chainsaw before we let them know about the scalpel.

How about a poll?  Vote up if you want the title proposal to be in 2.0, down if you want it to stay like it is.

**Comment by anjakefala** [comment]
> [This is why we should try to use longnames when discussing commands :)]

:")

**Comment by saulpw** [comment]
Also, going back go `zO`/`O` leaves `gO` open for another command, maybe `open-visidatarc`?

**Comment by geekscrapy** [comment]
In my head g=global (as it's probably designed!), z is cell related. So therefore zO would make me think I'm changing options to the cell, which doesn't make sense. "G"lobal "O"ptions sounds and does what I would expect as it is now. Just my two cents! 👍

**Comment by jsvine** [comment]
Hmmm, there _is_ something nice about that, @geekscrapy. Maybe it's just a matter of me drilling into my own head that `options == gO`, `options == gO`, `options == gO`. I guess it's just one of those rare instances when the `g`-prefixed version of a command is the more common use-case than the solo command.

**Comment by saulpw** [comment]
Ok, the poll didn't get much traction, but @jsvine, I think you're right anyway.  The `g` and `z` prefixes are more "relative" mnemonics, and the most common version of a command should be the unprefixed version.  We'll make the change and get it into the next pre-release version.

**Comment by anjakefala** [comment]
How do we feel about this when it comes to the cmdlog commands?

**Comment by saulpw** [comment]
@anjakefala Let's not conflate the two. If there's a concrete proposal for cmdlog bindings let's open up a new issue for discussion. (Unless you think that the cmdlog commands are reason enough to veto the options proposal, in which case, try and convince me!)

**Comment by anjakefala** [comment]
> Unless you think that the cmdlog commands are reason enough to veto the options proposal, in which case, try and convince me!

@saulpw Nope! :)

**Comment by anjakefala** [comment]
Change is now in develop!
