### ISSUE TITLE
[wishlist] Highlight search result match

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#534]
Wondering thoughts on if it was possible to highlight the matched value(string) when '/' or the like is used. This would really assist when looking at 

Is there the ability in the API to highlight/format certain characters?

**Comment by anjakefala** [comment]
Hi @geekscrapy!

Thanks for making a feature request. :blush: 

I agree that this would be a cute idea. I am going to Kondo it for now, since we are trying to focus on getting 2.0 out, and kondo-ing wishlists that do not make it on the roadmap. @saulpw might revert this decision. 

The api right now supports colouring cells, rows, and columns! Not individual characters within a cell.

**Comment by frosencrantz** [comment]
Even without the individual character highlighting, it seems like highlighting matching cells would be useful.  @geekscrapy,  if you do create a plugin for colorizers, this seems like a useful addition.

Using the colorizers it would be possible to change the color of matching cells:
https://github.com/saulpw/visidata-book/blob/master/colorizers.md

You would need to get the value of the last search pattern.

It might be possible to update the coloring as you are typing.  The livesearch plugin might provide help for how to do that:
https://github.com/saulpw/visidata/blob/develop/plugins/livesearch.py

**Comment by anjakefala** [comment]
Thanks for linking relevant documentation @frosencrantz!

**Comment by geekscrapy** [comment]
Thanks for the tips, I'll look into it. This said though my main motivation behind this was due to having a very long values in a cell, so coloring the whole cell wouldn't be too helpful (for me) 😁. Also character coloring isn't actually available right now

**Comment by frosencrantz** [comment]
Yes, I've felt the ability to color parts of a cell would be helpful.  In addition to search terms, it would be useful to be able to build color bar graphs under the words, so you could combine the frequency values right into a column.  The htop program has color bar graphs showing memory and swap usage combined with the values.
