### ISSUE TITLE
[wishlist] ';' to utilise named capturing groups

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#535]
it would be very useful to be able to use named capturing groups to automatically name columns based on the capture group name. This would significantly decrease the time to rename all the columns when a lot of regex groups are captured.

Another very useful aspect is this: I am building up a library of regex matches for different log formats. when I open one of these log files currently I have to run the match command and then rename multiple columns manually.

I think that completely user driven, deterministic (although I appreciate they are deterministic now!) columns names would be a great addition for ';'

**Comment by anjakefala** [comment]
Hi @geekscrapy! Thanks for making a feature request.

SInce we are really trying to get 2.0 out, our current procedure is to kondo wishlist items that are not on the 2.0 roadmap. @saulpw may revert this decision, but I am going to close for now.

If you could please add an example (i.e. these are the columns, this was my capture-group regex, these should be the resulting column names), that will help me when I pick this up in the future.

It is cool to see people using `;`. :blush:

**Comment by geekscrapy** [comment]
Np about closing the issue, just wanted it to be logged!

Use cases for this would be to auto parse logs (which could be an awesome plugin that's floating around in my head) to vd rows.

A simple example would be this:
`127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326`

The regex for this with named groups would be:
`(?P<src_ip>.*?)\s(?P<ident>.*?)\s(?P<user>.*?)\s\[(?P<finish_processing>.*?)\]\s"(?P<req_method>\w+)\s(?P<req_uri>.*?)\s(?P<req_protocol>.*)"\s(?P<resp_status>\d+)\s(?P<resp_bsize>\d+)`

In a small py programe:

```
>>> import re
>>> log = '127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326'
>>> p = re.compile(r'(?P<src_ip>.*?)\s(?P<ident>.*?)\s(?P<user>.*?)\s\[(?P<finish_processing>.*?)\]\s"(?P<req_method>\w+)\s(?P<req_uri>.*?)\s(?P<req_protocol>.*)"\s(?P<resp_status>\d+)\s(?P<resp_bsize>\d+)')
>>> p.search(log).groupdict()
{'src_ip': '127.0.0.1', 'ident': '-', 'user': 'frank', 'finish_processing': '10/Oct/2000:13:55:36 -0700', 'req_method': 'GET', 'req_uri': '/apache_pb.gif', 'req_protocol': 'HTTP/1.0', 'resp_status': '200', 'resp_bsize': '2326'}
```

My intention would be that the dict keys would be the new column names.

Another example (taken from: [elasticsearch](https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs))
`97.116.185.190 - - [17/May/2015:11:05:29 +0000] "GET /style2.css HTTP/1.1" 200 4877 "http://www.semicomplete.com/articles/dynamic-dns-with-dhcp/" "Mozilla/5.0 (Windows NT 5.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"`
Regex:
`(?P<src_ip>.*?)\s(?P<ident>.*?)\s(?P<user>.*?)\s\[(?P<finish_processing>.*?)\]\s"(?P<req_method>\w+)\s(?P<req_uri>.*?)\s(?P<req_protocol>.*)"\s(?P<resp_status>\d+)\s(?P<resp_bsize>\d+)\s"(?P<referrer>.*?)"\s"(?P<useragent>.*?)"`

py:
```
>>> log = '97.116.185.190 - - [17/May/2015:11:05:29 +0000] "GET /style2.css HTTP/1.1" 200 4877 "http://www.semicomplete.com/articles/dynamic-dns-with-dhcp/" "Mozilla/5.0 (Windows NT 5.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"'
>>> p = re.compile(r'(?P<src_ip>.*?)\s(?P<ident>.*?)\s(?P<user>.*?)\s\[(?P<finish_processing>.*?)\]\s"(?P<req_method>\w+)\s(?P<req_uri>.*?)\s(?P<req_protocol>.*)"\s(?P<resp_status>\d+)\s(?P<resp_bsize>\d+)\s"(?P<referrer>.*?)"\s"(?P<useragent>.*?)"')
>>> p.search(log).groupdict()
{'src_ip': '97.116.185.190', 'ident': '-', 'user': '-', 'finish_processing': '17/May/2015:11:05:29 +0000', 'req_method': 'GET', 'req_uri': '/style2.css', 'req_protocol': 'HTTP/1.1', 'resp_status': '200', 'resp_bsize': '4877', 'referrer': 'http://www.semicomplete.com/articles/dynamic-dns-with-dhcp/', 'useragent': 'Mozilla/5.0 (Windows NT 5.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36'}
```

If you are familiar with elasticsearch and logstash there are lots of examples of regex examples here:
[Common log formats/example logs](https://github.com/elastic/examples/tree/master/Common%20Data%20Formats)
[Common log format regex patterns used in logstash](https://github.com/logstash-plugins/logstash-patterns-core/tree/master/patterns)

**Comment by geekscrapy** [comment]
Had a look at this as it was bugging me, so came up with this if anyone else needs it!

License: It work(ed|s) for me :) But happy to edit if anyone has improvements for it!

https://github.com/geekscrapy/visidata_plugins/blob/master/capture_named_col.py

This now allows me to load any text file with vd using:
`vd https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs`

And extract already renamed new columns with:
`capture-named-col`
Then input:
`^(?P<src_ip>.*?) (?P<remote_log_name>.*) (?P<userid>.*) \[(?P<req_date>.*?)\] \"(?P<http_method>.*?) (?P<uri>.*?) (?P<http_ver>.*?)\" (?P<resp_code>.*?) (?P<bytes_returned>.*?) \"(?P<referer>.*?)\" \"(?P<user_agent>.*?)\"`

So from this:
![image](https://user-images.githubusercontent.com/11225502/90524771-84015f00-e17f-11ea-8479-741654b310cc.png)
To this, in a couple of seconds (knowing the regex of course):
![image](https://user-images.githubusercontent.com/11225502/90524834-9a0f1f80-e17f-11ea-9921-7b16bbc16cf6.png)
