### ISSUE TITLE
[wishlist] Sheet protection?

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#538]
The undo/redo features in 2.x have created a new VisiData use-case for me: data entry! In the course of using 2.x more for that sort of thing, I've come to desire a particular feature: sheet protection. 

I.e., I'd like to be able to mark a sheet as "protected," in which case I would not be able to `q`/quit it without confirming (much like I can't save it without confirming).

If this doesn't fit into the roadmap, however, I'd be open to creating a plugin that achieves this effect.

Thanks regardless!

**Comment by saulpw** [comment]
Design idea: a command `guard-sheet` that sets `options.quitguard=True` on the sheet.

Then we make it confirm whenever a sheet is quit() which has quitguard set, even if the program itself isn't exiting.  Ideally we this could be all quitguard behavior (since the global option will make it set on all sheets), but I think that's annoying in most cases and so when set globally quitguard should behave as now, and only confirm when quitting the last sheet.

**Comment by geekscrapy** [comment]
@jsvine When I've accidentally quit a sheet in the past I've just give to gS (sheets graveyard) and reopened it. This, joined with the confirm quit option has saved me in the past (for data entry too!)
Maybe, to also add, a read-only option for the sheet might be good? Just a variance on this

**Comment by jsvine** [comment]
@saulpw That would work for me, thanks!

@geekscrapy Ah, yes, the global quit-guard used in tandem with the sheets graveyard would do the trick. (Thanks!) But maybe the sheet-specific quit-guard would still be a useful improvement, especially for newer users unfamiliar with the graveyard?

And re. the read-only option: Would that prevent in-memory changes, or just saving changes to file? And if the latter, what's the use-case that makes that preferable to the current save-confirmation flow? (Not a rhetorical question, genuinely curious.)

**Comment by geekscrapy** [comment]
read-only: I was meaning to prevent in memory changes 🤗 so prevent 'e' edit cell, add col, add row, new col via expression '=', etc. anything that modifies the source data basically

**Comment by saulpw** [comment]
@jsvine There is now an unbound `guard-sheet` command you can play with.  Let me know how it works for you.

**Comment by jsvine** [comment]
Awesome, and thank you! Just gave it a test-spin, and works as expected.
