### ISSUE TITLE
[wishlist] focus sheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#544]
This sheet is a meta sheet which has some associated conditions related to row contents. If a condition is met the row is included and shown in the sheet.

For example rules could be defined by a python lambda such as:

`lambda columns, row: c["randomcol"].getDisplayValue(r) == 'test'`

Therefore, if "test" is displayed in a Column named "randomcol", the row will appear in the Filter sheet.

Preferably this would auto refresh and not require a reload, and all columns for that row would be present like if appending sheets.

This idea was brewed from : #540

**Comment by geekscrapy** [comment]
This would auto populate on vd load while sheets are loading. So if a large file is loading, the focus sheet will gradually populate with matching rows

**Comment by anjakefala** [comment]
This is a pretty fun idea! 

Closed for now as per wishlist policy. :)
