### ISSUE TITLE
[v2.-4dev] -f filetype is ignored if a directory is given (always opens DirSheet)

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#546]
If I want to create a new "file" type / loader which consumes a directory argument but it always opens a `DirSheet`. I have created a loader which consumes a directory and will create sheets based on the files in that directory. However, if I do this on the command line `vd -f xloader /path/to/dir` it loads a DirSheet. I expect this is given, but it restricts creating new loaders which use directories as their source.

I would always expect `-f` to override the guessed format, and use the associated loader?

**Comment by anjakefala** [comment]
Hm. This may be a little tricky considering the nature of folders compared to files. 

I will take a look at this when I re-integrate `vls`.

**Comment by saulpw** [comment]
Let me know if this fixes it for you, @geekscrapy!  Thanks for reporting.
