### ISSUE TITLE
[wishlist loader] HexSheet for unknown/binary files

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#548]
I may have a crack myself, as I come across this a bit, but it'd be great to have a hex viewer (maybe editor?!) as the default sheet instead of a TextSheet (or maybe if the source doesn't decode successfully as text). Or alternatively, the user would have the option to reopen the file in a different sheet at runtime (can't remember if this is possible)

**Comment by saulpw** [comment]
A HexSheet is a super cool idea, @geekscrapy!  I'd love to have this myself sometimes.  Ping me on #visidata and I can help with the design and whatnot.
