### ISSUE TITLE
[wishlist] concatenate columns, value separator option

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#550]
In VisiData it's possible to concatenate columns, using `&` in Columns Sheet.

The results values will be [separated by space](https://github.com/saulpw/visidata/commit/44dc5ce51ca1a91ae2f7f5fc98c822bcc00f8ee2#diff-1f5a50f1a6c5a6bb7b3ae35017e52b63R165). Then if your source columns contain already some space, it's impossible to have idea of the source distinction.

My request is to add a "value separator" option.

Thank you

**Comment by pigreco** [comment]
Just in these days I am using `&` to concatenate columns, it would be really useful to be able to choose a separator other than space

**Comment by saulpw** [comment]
This is no problem to implement.  There are still a few design points to consider though:

1) What should the option be called?

2) Should this option (or a different option) be used for joining sheet names also?  Both for JoinSheets and for diving into subsheets.

These may be different cases but I don't like having 3 or more different options.  By default, column names and joined sheet names are combined with `+`, while other instances of combined sheet names are combined with `_`, and sometimes `.` is used instead.  It would be nice to have these used and specified consistently.

**Comment by aborruso** [comment]
As usual you are very kind.

Thank you very much

**Comment by pigreco** [comment]
wow, thank you very much!

**Comment by aborruso** [comment]
@saulpw I have set `value_joiner="|"` in `.visidatarc` file, but when I do columns join I have always the standard value_joiner value, a white space. 

If I set it via options sheet, it works.

I'm using saul.pw/VisiData v2.-4dev

**Comment by anjakefala** [comment]
Did you do `options.value_joiner="|"` @aborruso?

**Comment by aborruso** [comment]
> Did you do `options.value_joiner="|"` @aborruso?

No, I'm stupid I wrote only `value_joiner="|"`

Thank you @anjakefala, it works
