### ISSUE TITLE
[develop] gO does not open the .visidatarc file

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#553]
**Small description**

In vd [it's possible](https://github.com/saulpw/visidata/releases/tag/v1.5.1) to open `.visidatarc` file via `gO`. If I use it in `saul.pw/VisiData v2.-4dev` I have "no command for gO".

**Expected result**

To open the `.visidatarc` file 

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/30607/81541100-e671e480-9372-11ea-84e9-ef188c47d021.png)

**Steps to reproduce with sample data and a .vd**

Open a file and run `gO`

**Comment by anjakefala** [comment]
Nice catch @aborruso! =) @saulpw has fixed this on the latest `develop`.

**Comment by aborruso** [comment]
Thank you very much @saulpw and @anjakefala
