### ISSUE TITLE
[bug] load_pyobj() missing 1 required positional argument: 'obj" `

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#557]
**Small description**
Getting stack trace with latest version from develop branch:
```
Traceback (most recent call last):
File "/usr/lib/visidata/basesheet.py", line 126, in execCommand
   exec(code, vdglobals, LazyChainMap(vd, self))
File "dive-row", line 1, in <module>
  import math
File "/usr/lib/visidata/sheets.py", line 241, in openRow
  return vd.load_pyobj(tuple(c.getTypedValue(row) for c in self.visibleCols)) TypeError: load_pyobj() missing 1 required positional argument: 'obj"
```
**Expected result**
No trace.

*Steps to reproduce with sample data and a .vd**
Attempt to dive-row into a row of csv data.

**Additional context**
Latest version of Visidata b9ff312

**Comment by anjakefala** [comment]
Definitely a bug. Thanks. =)

Should be fixed on `develop` now.

**Comment by frosencrantz** [comment]
Seeing a related stack trace when diving into a json file row.

```
File "/usr/lib/visidata/basesheet.py", line 126, in execCommand
   exec(code, vdglobals, Lazy ChainMap (vd, self))
File "dive-row", line 1, in <module>
   import math
File "/usr/ib/visidata/pyobj.py", line 10, in openRow
  return load_pyobj("%s[%s]" % (name, rowIndex), row)
NameError: name 'name' is not defined

```

**Comment by anjakefala** [comment]
Why don't you open a small PR where you add these in?

**Comment by anjakefala** [comment]
Nvm =)

**Comment by frosencrantz** [comment]
Thanks for the fixes for the last couple bug of reports! 

Sorry not to be more helpful on the fixing side of things.  I don't know the code well enough.  I try to help by providing timely bug reports, and checking that things are working afterwards.  Hopefully you consider that helpful.

I looked at your first fix on this issue and didn't understand, and asked a question.  Thanks for the feedback.  I was surprised by your answer!  :)

Thanks Anja, you're great!
