### ISSUE TITLE
[wishlist] center scrolling

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#561]
I work with datasets that are usually ordered by date and the importance of that data is influenced by other rows surrounding it. For example, http log data, do you see a login followed by a /admin/ request?

Currently, when paging through the data I have to use zz to align the current row to the middle so I can see rows surrounding it (which are as important as the row itself). This also occurs with search commands which could highlight any row in the screen.

Is there a way to keep the current row in the middle?

For example, if row 0 was selected, the cursor would be at the top of the page. The user then moves the cursor down until they hit the (screen) middle row. At this point, the cursor no longer visually moves as the rows surrounding (visually) move instead. The opposite then happens when you come to the bottom. Rows (visually) move until the middle row of the last full page, then the selected row moves down until it hits the last row, which is always at the bottom of the screen.

This would act more like gui scrolling behaviour, and would also prevent 99% empty rows being shown when you reach the bottom row.

Related to #559

**Comment by frosencrantz** [comment]
Saul's response in #559 contains a good part of what you would need to change.  Up&down bindings that change both sheet.topRowIndex and sheet.cursorRowIndex  until you are half a screen from the top or bottom of the file.  And nScreenRows would tell you the row count of the screen.

**Comment by geekscrapy** [comment]
is topRowIndex the row that is at the top of the screen?
I'll look at creating a plugin for this, I always find its good to have an alternative way to scroll through data

**Comment by geekscrapy** [comment]
I came up with the following in the end. Not sure if overriding the commands was the best way to go, but it works for now and I couldn't see a quick and easy way to do it!
https://github.com/geekscrapy/visidata_plugins/blob/master/scroll_fix.py

If you want to include this in the plugin repo and it needs any changes, just let me know. Otherwise, I'll just keep it in my personal repo that I'm building up slowly!

**Comment by frosencrantz** [comment]
There is an unbindkey method that could be used to change the key, so you can use different long commands for the commands:
  *  https://github.com/saulpw/visidata/blob/develop/visidata/settings.py#L253

It seems like these commands might be generally useful.

**Comment by geekscrapy** [comment]
You wouldn't have any examples on how to use it would you...? 🙂

**Comment by frosencrantz** [comment]
Here's an example: https://github.com/saulpw/visidata/issues/420
