### ISSUE TITLE
defermods plugin SHA256 does not match

### ISSUE THREAD

**Issue by jtf621** [saulpw/visidata#564]
When I try to activate the defermods plugin I get the error message `defermods plugin SHA256 does not match!` 

Screenshot:
![image](https://user-images.githubusercontent.com/2312781/82470941-ff297b00-9a93-11ea-9aaf-b8c4baa3205f.png)

`vd --version` output:  saul.pw/VisiData v2.-3 version

I checked out the develop branch and the same error occurs.

I am really looking forward to the ability to edit sqlite files with visidata.

**Comment by anjakefala** [comment]
@jtf621 I need to clean up those shas. For now, I have excellent news. =) I integrated defermods into VisiData, so you should be able to edit sqlite on `develop`.

Type `z Ctrl+S` to commit your changes to the source sqlite file. Let me know how it works out for you!

**Comment by jtf621** [comment]
@anjakefala Thanks for the quick response.  Using the `develop` branch, I can get visidata to save a sqlite file, but editing simple files leads to a bunch of different issues.  Is there a part of the docs or code I can look at to better understand what is possible and that I am using vd correctly for editing sqlite files?  If I still have issues should I open a new issue?

Thank you for visidata, it is a wonderful tool that I reach for often.

**Comment by anjakefala** [comment]
@jtf621 Ah sorry, this is a very new feature, and there are no docs at the moment. 

You can take a look at this commit https://github.com/saulpw/visidata/commit/4b5c4401df510c1d3414dfc555edb40dadecf0cd along with the `putChanges()` method in `visidata/loaders/sqlite.py`. We should support adding a row, deleting a row, and editing a cell in pre-existing tables.

You are very welcome to open issues, if you understand that we may close them! Creating a full sqlite editor is a lot of work that we would be happy to do given support, but we do not really have support for it at this moment.
