### ISSUE TITLE
[loader] text loader to support utf8 decoding

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#565]
Is there scope/need for adding an option to toggle between text decoding? It'd be great if it did it automatically, but I think the user should be told that it's happening

**Comment by saulpw** [comment]
You can set the `encoding` option to change the decoding method.  By default it is utf-8 and that should be used for any loader that supports variable encodings.

**Comment by anjakefala** [comment]
@saulpw @geekscrapy Can this issue be closed? It seems like Saul answered the question.

**Comment by geekscrapy** [comment]
I'll test it this week and comment/close

**Comment by anjakefala** [comment]
Closing because the feature already exists. =) Please re-open if you would like to continue the conversation.
