### ISSUE TITLE
[2.4-dev] no user feedback or async for search-col, searchr-cols, search-expr etc.

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#567]
I've noticed, there is no user feedback given in the form of % searched for either forwards or backwards regex searches. These two also freeze the user interface when used on large files

I have noticed, they also don't react to ^C (cancel / bail out)

Longnames of the commands I believe are affected:

- search-col
- search-cols
- search-expr
- searchr-col
- searchr-cols
- searchr-expr

**Comment by saulpw** [comment]
Fixed in 7dbfb148fda8df299dc769730b5c6aaf819b600b.

**Comment by geekscrapy** [comment]
Yes!
Does search-expr use this method as well?!
