### ISSUE TITLE
disp_float_fmt option error (for thousands separator)

### ISSUE THREAD

**Issue by dimonf** [saulpw/visidata#575]
**Small description**

custom format (thousands comma) is not applied:
`cat .visidatarc
 options.disp_float_fmt='%,.02f'`

I added comma into format spec. Instead of new format apply, a question mark appended to the value which is still in default format (%.02f)

**Expected result**
comma-separated presentation for float type: 15,220.22

**Actual result with screenshot**
15220.22?

**Additional context**
Version: v2.-3

**Comment by saulpw** [comment]
Hi @dimonf, thanks for bringing this to my attention, as this has needed to be fixed for awhile now.  It's now in develop, but you'll have to use either `%.02f` (these are now automatically grouped) or `{:,.02f}` (which is a python format string); the one you suggested will give an error regardless.
