### ISSUE TITLE
Add some notes about CSV cleaning by default when vd save a file?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#580]
Hi,
if you have this input csv file

```
fieldA ,fieldB
"0",1
```

and you open and save it using vd (without do anything more) you have in ouput a different file

```
fieldA,fieldB
0,1
```

```diff
@@ -1,2 +1,2 @@
-fieldA ,fieldB
-"0",1
+fieldA,fieldB
+0,1
```

It's good, because it's a cleaner file, but probably it should be better to add some notes in the documentation about vd implicit transforming, and about the rules of this transforming.

**Comment by geekscrapy** [comment]
Worth adding here that the same may happen to xls/x (https://github.com/saulpw/visidata/pull/574#issuecomment-635752076) if there is to be a globally (rather than loader specific) documented section regarding changes that are made to the output

**Comment by anjakefala** [comment]
I am working on a blog post that touched on this, actually!

The basic theme is "for most loaders VisiData saves the display value".

**Comment by anjakefala** [comment]
I added a minor note here while I continue to work on those docs!

https://github.com/saulpw/visidata/blob/develop/docs/columns.md#how-to-format-columns

**Comment by aborruso** [comment]
thank you @anjakefala
