### ISSUE TITLE
[wishlist] pasting data into input(): should not react to newlines

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#585]
I've come against this a few times now where I've accidentally pasted multi line data into the regex search input. This does two things:
1. When a new line character is pasted, it takes this as and enter which competes the command
2. If there are any characters after the new line these are entered as key commands which could potentially mess up the table

Recreate:
Open a sheet
Copy some text to search for. This will include a new line character
Use / to open the input prompt
Paste the text

I often do this when I copy data from a cell using using zY (the cell data maybe partially hidden). This cell value may contain a new line character that I'm unaware of and upon pasting into the input field searches for everything up to the new line, but then entered a bunch of unintended key combinations which are from the following line.

**Comment by saulpw** [comment]
Ah yeah, so basically you would want the input buffer to be cleared on exit from `input()`.  This would still only get the first line, but at least it wouldn't screw things up afterwards.

Alternatively we could make something like a multiline input mode that requires Ctrl+Enter or something to accept the input.  But this would be more complicated and should actually display multiple lines for editing, which inputline doesn't do.

**Comment by geekscrapy** [comment]
Yea, the first option would be best. I'm not totally convinced myself that multi line input is necessary, _maybe_ convert special characters to their regex counterpart? So if I pasted something with a newline it'd actually paste it as \n?
That might be a good way to go

**Comment by anjakefala** [comment]
The proposed simple fix should be on `develop` now! Thanks for drawing our attention to this @geekscrapy.

Upon, ENTER, VisiData will clear the input buffer.
