### ISSUE TITLE
[question] z^S does not save key columns

### ISSUE THREAD

**Issue by tmward** [saulpw/visidata#597]
Hello and thank you for the great piece of software. I ran into an issue with the `z^S` command to save both key columns and current column.

The man page for vd states:
`z^S filename     save key columns and current column only to filename in format determined by extension (default .tsv)`

This functionality (saving key columns *and* current column) is also supported in CHANGELOG.md on line 181:
`- `z^S` to save selected rows of current column only (along with key columns)`

If you assign a few columns in a sheet to be key columns with `!` though and then do `z^S`, it will only save the data in the *current* column, not both the key columns and current column. I've been able to reproduce this across a few csv/tsv files.

Looking through the repository, `visidata/commands.tsv` on line 170 conflicts with the manual page:
`Sheet	save-col	z	^S	z^S	n	n	n	y		sheet-save-column	save current column to filename in format determined by extension`

The "save only cursor column" approach is supported by what the code actually does (if I found the right bit that is) in line 99 of `visidata/data.py`:
`Sheet.addCommand('z^S', 'save-col', 'vs = copy(sheet); vs.columns = [cursorCol]; vs.rows = selectedRows or rows; saveSheets(inputFilename("save to: ", value=getDefaultSaveName(vs)), vs, confirm_overwrite=options.confirm_overwrite)')`

I guess it depends on what functionality you actually want to target (I personally like saving key columns and current column since I just wanted to select a few columns and save that as a new csv). To make that happen, I think it would involve changing the above line in `visidata/data.py` to:
`Sheet.addCommand('z^S', 'save-col', 'vs = copy(sheet); vs.columns = keyCols + [cursorCol]; vs.rows = selectedRows or rows; saveSheets(inputFilename("save to: ", value=getDefaultSaveName(vs)), vs, confirm_overwrite=options.confirm_overwrite)')`

where the `vs.columns` is now `keyCols + [cursorCol]` instead of just `[cursorCol]`.

**Comment by anjakefala** [comment]
@tmward, which version of VisiData are you using?

**Comment by tmward** [comment]
> @tmward, which version of VisiData are you using?

Sorry I left that out:
visidata-1.5.2 on Void Linux, python 3.8.3

**Comment by tmward** [comment]
Also, I noticed a little bug in my solution. If the cursor is currently on a column that is already a keycol it would duplicate the column at the end. To solve that, only want the cursorCol added to the end if it is not already in the keyCols. You can do this with the following that I tested and worked in visidata 1.5.2 for `visidata/data.py`:
`Sheet.addCommand('z^S', 'save-col', 'vs = copy(sheet); vs.columns = (keyCols + [cursorCol], keyCols)[cursorCol in keyCols]; vs.rows = selectedRows or rows; saveSheets(inputFilename("save to: ", value=getDefaultSaveName(vs)), vs, confirm_overwrite=options.confirm_overwrite)')`

-thomas

**Comment by anjakefala** [comment]
Hi @tmward!

Thanks for leaving such a detailed report.

To start off, I am sorry, that is a bug in v1.5.2. It was fixed on the `develop` branch. Unfortunately, we unbound `z Ctrl+S` from `save-col`, but you will be able to rebind it so you should choose. =) We will have a guide available on how to do that hopefully, soon.

`commands.tsv` is deprecated, and is no longer kept up to date!

I am glad that you got it working in your local version! :blush: Maybe I can make a FAQ to add your fix to.
