### ISSUE TITLE
No ~/.visidatarc in 2.-3?

### ISSUE THREAD

**Issue by Mesibov** [saulpw/visidata#603]
Installed 2.-3, works fine. No ~/.visidatarc installed or created on use, so I can do global option changes (like reversing default color) on sheets, but the changes don't persist.

**Comment by anjakefala** [comment]
Hi @Mesibov! 

The ~/.visidatarc is never automatically created. You manually create one in your home directory and add the options within there. =)

**Comment by Mesibov** [comment]
Thanks @anjakefala!  It wasn't clear to me in the docs that ~/.visidatarc is user-created. Mine now has

options.color_default = "reverse"

To see why, compare the 2 attached screenshots. To my eyes, the selected rows stand out better with reversed color:

![default](https://user-images.githubusercontent.com/16182234/85189742-da276280-b2f4-11ea-9346-be56b416dec9.png)
![reversed](https://user-images.githubusercontent.com/16182234/85189743-dc89bc80-b2f4-11ea-9b51-3c62863d24a8.png)

**Comment by anjakefala** [comment]
Very cool theme! =) Thanks for sharing.

**Comment by frosencrantz** [comment]
Hi @Mesibov ,

Contributions are welcome.  I don't think Saul will change the defaults for this.  You are welcome to create visidata_plugins repository with any code you create, and @saulpw and @anjakefala  can include it in the plugin directory if you want.

Also, if you are looking at customizing your environment Saul provided a small Python script here to create a ~/.visidatarc file that contains all the options with their defaults.  It is a great place to start from.
https://github.com/saulpw/visidata/issues/322#issuecomment-554248742

Also, I enjoy your blog, https://www.datafix.com.au/BASHing/,  I would like to hear more about how you use Visidata.
It seems like a great fit for the types of data work you do.
