### ISSUE TITLE
[wishlist] optimize melt operation on large files

### ISSUE THREAD

**Issue by Mesibov** [saulpw/visidata#605]
Running VisiData 2.-3 on a machine with i5-4590T Quad Core CPU at ca 800 MHz, 8GB RAM with ca 2 GB in swap (MX-19 Linux).
I shuffled a ca 6.5M-record TSV with 23 text fields and used "head" to generate files with 1K - 5M rows. I then timed a melt on each file with a seconds timer, with these results:
1K rows: 0 sec
2K: 0
5K: 0
10K: 0
20K: 1
50K: 3
100K: 5
200K: 10
500K: 24
1M: 47
2M: froze at 67% melted
5M: froze at 3% melted

**Comment by Mesibov** [comment]
Please note that within the accuracy of my seconds timer, time-to-complete is linear with record number up to 1M records.

**Comment by saulpw** [comment]
Hi @Mesibov,

While these large melts are working, is VisiData responsive?  That is, do you see a percentage indicated in the lower right, and can you move the cursor (and especially stop the huge merge from continuing further with `Ctrl+C`), even if it lags up to a second or so?

This sounds like it could be a performance issue, but as long as it remains responsive, I think we'll make it a wishlist item to optimize the Melt Sheet.

For the larger datasets that freeze outright, I'm guessing your computer exceeds RAM and starts thrashing into swap. You can try setting `options.min_memory_mb` to something like `100`.  If this is set, VisiData uses the `free` command to check memory usage and will abort threads if it drops below the given threshold.  You still won't be able to load all the data, but at least it won't freeze and you can use the data it has loaded.

Also, if you didn't know, you can press `Ctrl+T` to go to the Threads Sheet, which will show you threads that ran for more than a blip and how long they took, so you don't have to use a stopwatch.

**Comment by Mesibov** [comment]
Hi @saulpw.

While non-freezing melts are happening the percentage figure increases steadily at lower right until the melt is finished. With the freezing melts the percentage figure stalls, the cursor isn't responsive and Ctrl+C doesn't work. All I can do is close the terminal.

Setting options.min_memory_mb = 100 in ~/.visidatarc had no effect just now on the 5M-record melt - it still stopped at 3% and the shell became unresponsive.

Didn't know about the Threads Sheet, many thanks. You can edit the 5 seconds for 100K records to 5.13!

**Comment by Mesibov** [comment]
Same result after opening 5M sheet and loading all records, then editing min_memory_mb in the Options sheet, then trying a melt.

**Comment by saulpw** [comment]
> Setting options.min_memory_mb = 100 in ~/.visidatarc had no effect just now on the 5M-record melt - it still stopped at 3% and the shell became unresponsive.

Did it then show the amount of memory remaining in the right status bar?  Before it froze, what was the number?

**Comment by Mesibov** [comment]
Lower right corner on freeze:
![Screenshot](https://user-images.githubusercontent.com/16182234/85252404-01ba2e80-b49f-11ea-8737-6406b303ab18.png)

**Comment by saulpw** [comment]
Then `min_memory_mb` isn't working for you.  What system are you using, and is `free` installed?

**Comment by Mesibov** [comment]
MX 19 Linux, which is lightly built on top of Debian 10, which naturally includes free.

**Comment by Mesibov** [comment]
@saulpw Could there be a parsing problem with free in VisiData code? /proc/meminfo is where free gets its numbers from before doing some arithmetic.

**Comment by saulpw** [comment]
Do you see a warning in `Ctrl+P` after you've started the melt with `min_memory_mb`?  Also try with `--debug`.

**Comment by Mesibov** [comment]
> Do you see a warning in `Ctrl+P` after you've started the melt with `min_memory_mb`? Also try with `--debug`.

The only new msg with Ctrl+p after setting min_memory_mb to 100 and starting the melt is "100".
Running with --debug, I can load the 5M-record file but can't start a melt with Shift+m; the shell freezes. And I can't access the session log, which disappears when I close the terminal to get out of the freeze.
