### ISSUE TITLE
[question] no command for "z|"

### ISSUE THREAD

**Issue by jimbeauh** [saulpw/visidata#607]
I am going through the tutorial and when I got to the section on Python expressions I find that none of the "z" commands work.  Any idea how to troubleshoot this?

**Comment by anjakefala** [comment]
Hi @jimbeauh 
Can you please let me know what version of VisiData you are using, and describe what happens when you type `z|`?

When you tap the spacebar, do you get a `command name: ` prompt at the bottom? Can you type `select-expr` into it, and press Enter? What happens then.

**Comment by jimbeauh** [comment]
version 1.0

When I have csv file loaded, if I type z|, I see no command for "z|".

If I tap the spacebar I see no command for " ".

**Comment by anjakefala** [comment]
Hi @jimbeauh, that is a very old version of VisiData that is no longer maintained. =) I do not believe any of the z-prefix commands existed at that point.

Could you please update to 1.5.2? https://www.visidata.org/install/
