### ISSUE TITLE
[wishlist] VisiData installer for Windows

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#609]
https://github.com/python/cpython/tree/master/Tools/msi

This link provides a 'how-to' for making a python installer. We should try using it, and this issue will act as a reminder.

If it does not end up working, this issue will get closed.

**Comment by anjakefala** [comment]
https://pythondev.readthedocs.io/windows.html

**Comment by anjakefala** [comment]
https://visualstudio.microsoft.com/dev-essentials/

**Comment by saulpw** [comment]
From https://stackoverflow.com/questions/10535088/creating-a-windows-installer-for-python-a-set-of-dependencies:

> I suggest to use the packaging tool that I also use to build the Python releases, which is in Tools/msi/msi.py. Unpack the additional dependencies on top of the Python source (or an installation), then adjust msi.py to pick up all additional files that you want to package. You should adjust display strings to indicate that this is really a separate Python distribution.

**Comment by anjakefala** [comment]
# Notes
* Install a clean version of Python
* We think we need to copy the source code into our site-packages
* The msi builder lists additional required dependencies (e.g. WiX)
* We may need VisualStudio

**Comment by anjakefala** [comment]
https://cyrille.rossant.net/create-a-standalone-windows-installer-for-your-python-application/

**Comment by charlie17** [comment]
Any movement on this for v2? Was hoping...

**Comment by saulpw** [comment]
Hey @charlie17, we have some ideas about how to build this, but it would be a fair amount of work any which way (and more for me, since I'm not a natural Windows developer).  What platforms do you use VisiData on currently, and how do you install it now?  Is there a benefit to you for a Windows installer besides convenience?

**Comment by charlie17** [comment]
I have actually never used it, for this reason. You have generated a bit of buzz around the product, and it looks awesome - I've seen the videos, read some of the docs etc - but I'm a Windows guy for better or worse. I saw reference to WSL etc but that's just too much friction. Very keen to use it - I believe this fills a real market niche - but need Windows, and have to believe there are many out there in the same boat. Thanks for considering

**Comment by saulpw** [comment]
Kondo'd for now.
