### ISSUE TITLE
Problems installing visidata 

### ISSUE THREAD

**Issue by gusennan** [saulpw/visidata#61]
I ran into two issues when following the install instructions for visidata:

1) The requirements.txt is not where the readme says it will be
2) Running `vd` after install throws an ImportError "No module named 'visidata.addons".

I've attached my install and run logs.  The run logs show the full stack trace for the import error.

[install.txt](https://github.com/saulpw/visidata/files/1102131/install.txt)
[run.txt](https://github.com/saulpw/visidata/files/1102132/run.txt)

**Comment by saulpw** [comment]
Thanks for reporting these issues @gusennan.
