### ISSUE TITLE
[vgit develop] not able to install it

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#610]
Hi,
I do not if this is the right place to open an vgit issue.

If I run

```
python3 -m pip install --upgrade --user git+git://github.com/saulpw/visidata/vgit@develop
```

I have 

```
  Running command git clone -q git://github.com/saulpw/visidata/vgit /tmp/pip-req-build-xhtfp_vr
  fatal: remote error:
    saulpw/visidata/vgit is not a valid repository name
    Email support@github.com for help
ERROR: Command errored out with exit status 128: git clone -q git://github.com/saulpw/visidata/vgit /tmp/pip-req-build-xhtfp_vr Check the logs for full command output.
```

How to install it?

Thank you

**Comment by saulpw** [comment]
To be honest, @aborruso, I haven't paid much attention to vgit in awhile.  Probably best to stick with the (very alpha!) version released to pip.  And even then probably read-only.  I hope to get back to it someday, it's pretty slick for what it can do.
