### ISSUE TITLE
[wishlist] Do not expand strings when expanding lists

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#619]
**Small description**
String cell is expanded if in a column with lists. Expand fails with different types in a column.
**Expected result**
The string is not expanded.
There are stack traces if the column contains different types, some of which are nested.

**Actual result with screenshot**

b[0] | b[1] | b[2]
-----+------+------
a    | b    |
a    | b    |    c
   
**Steps to reproduce with sample data and a .vd**

(echo '{"b": ["a", "b"]}' ; echo '{"b": "abc"}')| vd -f json
Expand the b column  with '('

**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by ajkerrigan** [comment]
Hmm, with #611 in place we scan a configurable number of rows to identify addable columns. We _could_ abort the expand if that scan turns up more than 1 unique type (excluding nulls). What do you think @saulpw / @anjakefala ?

**Comment by saulpw** [comment]
VisiData doesn't pretend to work perfectly with heterogenous columns; it would make it more complicated and slower.  I'm inclined to leave it as-is, or provide some kind of "listify if not already list" transform. How do you get something like this in real data, @frosencrantz ?

**Comment by frosencrantz** [comment]
Often I transpose json/yaml data, so it is very easy to have a column of heterogeneous cells.  It is possible to expand before transpose, but this gets you a different result. Also, it is possible to hide heterogeneous rows after transpose, but again a different result.

Also, see my soon to be Kondo'd FR: https://github.com/saulpw/visidata/issues/623 for expanded rows...

**Comment by saulpw** [comment]
Okay, I see.  We can leave this as a wishlist item but I'm not sure of the right way to implement it.  Kondo'd for now.
