### ISSUE TITLE
 [plugin loader question] How to register a file type without vd.filetype()?

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#620]
**Small description**
Plugin loader stops working, once the vd.filetype() call was removed. Converting to open_TYPE() function.

**Expected result**
Loader continues to work.

**Actual result with screenshot**
Reports as status: unknown "TYPE" filetype
def open_type(p):
   return MyTypeSheet(p.name, source=p)
It appears the open_* function is not in the global namespace.

**Steps to reproduce with sample data and a .vd**
need type loader as part of~/.visidata/pluins/loader_type.py
$ vd foo.type

**Additional context**
Please include the version of VisiData. Latest version of develop

**Comment by saulpw** [comment]
Hi @frosencrantz, functions can be exposed globally in a couple of ways:

1. by adding `addGlobals(globals())` at the end of the plugin .py file. This will add all functions and variables in the file, so they can be used by command execstr's, and open_ and save_ functions will be exposed as well.

2. adding `__all__=['open_foo', ..]` at the top of the plugin .py file, with the list of functions and variables you want exposed explicitly.  Then the plugin needs to be imported as `from plugins.foo import *`; this import statement should add them to the global namespace too.

Let me know if these work or not.  Which loader is causing problems for you?

**Comment by frosencrantz** [comment]
I added a `addGlobals({'open_type': open_type})`.  That didn't require changes to my .visidatarc file.

That appears to work.  Thanks, @saulpw!

It might be helpful to document that for plugin loaders.  I would expect other plugin loaders are seeing the same issue.

I have a simple loader for some data I have.

**Comment by anjakefala** [comment]
Yeah, I agree, that should definitely be part of the updated loader documentation when that gets shipped.
