### ISSUE TITLE
[wishlist] Add '^O' binding for TextSheet to open sheet in editor

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#622]
Add to TextSheet a '^O' binding , which allows you open the contents of the text sheet in an editor.

If you are in DirSheet you can hit '^O' on a row/file and open it in the editor.  If you just dive-row on a file it opens it in the TextSheet.  From TextSheet you can't open the contents in your editor.

**Comment by saulpw** [comment]
Lots of questions here, @frosencrantz.  Is this for viewing only or editing too? If editing, do you want to edit the source directly or get a copy of the current set of lines?  After editing, should the changes be pulled back into VisiData if they're saved?  What's your use case?

**Comment by frosencrantz** [comment]
Thank you @saulpw, that's great!

Sorry to be too slow to respond, and you might not care anymore, but to answer your question:
I've started using Visidata as directory explorer.  I use it with different types of directories (data, documentation, source code, etc) and sometimes it is useful to take a peek at the file in Visidata, and if I need to do more than just view I can drop into Vim. I might make edits in Vim, but after I'm done editing, I'm likely to just go back to the DirSheet.
