### ISSUE TITLE
[wishlist] bool symbol included in pysheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#627]
Unlike the `duration`, `seen_bytes`, `total_bytes`, `missing_bytes` and `overflow_bytes`, the fields `local_orig` and `is_orig` don't have the bool symbol to show they are a `bool` column (they are a `bool` column in the parent sheet)

![image](https://user-images.githubusercontent.com/11225502/86936949-b61aac80-c14f-11ea-8bed-0d9637f10d2a.png)

It would be great if the `bool` symbol could be included here!

**Comment by anjakefala** [comment]
There is no officially supported `bool` type as of 2.0, so there is no `bool` symbol to indicate that. =)

What do you think a good bool symbol would be?

**Comment by geekscrapy** [comment]
To be honest, I thought the `?` shown in my bool columns _was_ the icon! 🙃 
In terms of icon, I think `?` works!

**Comment by anjakefala** [comment]
@geekscrapy Oh, that means unknown type. :joy:

**Comment by geekscrapy** [comment]
In that case then....! The `✓` symbol might be good! (but I still secretary like `?` 😝)

I thought `!` covered unknown/error scenarios, or is that just for use in the cell? Might be good for continuity to use the same symbol in the column header?
