### ISSUE TITLE
Trouble opening files (via command-line only) with spaces in the filename

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#628]
**Small description**

On my computer (Mac OS) the edge version of VisiData (5b057274, but also previous `develop` versions) seems to bug out when I point `vd` (on the command line) at a file whose name contains a space character. It seems to think I am pointing it to two (or more, depending on the number of spaces) files, typically neither of which exist.

Opening the same filename via `o` works fine, however.

**Expected result**

`vd` should be able to open files with spaces in their names :)

**Actual result with screenshot**

See below.

**Steps to reproduce with sample data and a .vd**

```sh
echo "z" > "My Test.csv"
vd "My Test.csv"
```

Result: `My does not exist, creating new sheet | Test.csv does not exist, creating new sheet`.

<img width="635" alt="Screen Shot 2020-07-10 at 10 09 17 AM" src="https://user-images.githubusercontent.com/534702/87163506-79f16400-c295-11ea-865d-82d85fd9b871.png">

**Additional context**

Mac OS, VisiData 5b057274

**Comment by anjakefala** [comment]
@jsvine Oh dear, I cannot reproduce on Linux...

![Peek 2020-07-10 21-17](https://user-images.githubusercontent.com/7489659/87216265-efd7e880-c2f2-11ea-8a44-ecb7a09789e1.gif)

**Comment by anjakefala** [comment]
I also tried with the specific example you gave, and was unable to reproduce this. I wonder if this is a terminal or shell issue... Does it work with 1.5.2 with the same terminal?

**Comment by geekscrapy** [comment]
I'm on Mac and I've not come across this issue... What terminal are you using and what shell? (I use gnu bash and iTerm)

**Comment by jsvine** [comment]
Doh! Was totally my own fault, in how I wired up Bash to use the `develop` branch. 🤦 for not having double-checked that first. Thank you for the sanity checks 🙏 , and apologies for the distraction!
