### ISSUE TITLE
[transpose] Transpose stack traces when there is an int value in key column

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#631]
**Small description**
Transpose stack traces with an int value in key column

**Expected result**
Transpose doesn't stack trace. Value is converted to string for new column name.

**Actual result with screenshot**
```
Traceback (most recent call last):
  File "/usr/env/lib/python3.8/site-packages/visidata/threads.py", line 207, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/env/lib/python3.8/site-packages/visidata/transpose.py", line 18, in reload
    self.addColumn(Column('_'.join(self.source.rowkey(row)),
TypeError: sequence item 0: expected str instance, int found
```
**Steps to reproduce with sample data and a .vd**
```
cat <<EOF >reproduce.vd
sheet	col	row	longname	input	keystrokes	comment
			open-file	-	o	
-	a		key-col		!	toggle current column as a key column
-			transpose		T	open new sheet with rows and columns transposed
EOF
echo '{"a":1}' | vd -f json -p reproduce.vd
```

**Additional context**
Please include the version of VisiData. Latest version of develop

This is not that important to me.  I hit it, so reporting it.

**Comment by anjakefala** [comment]
Should be fixed!

Thanks @frosencrantz, for the report. =)
