### ISSUE TITLE
Alt key being reassigned on exit. [mlterm]

### ISSUE THREAD

**Issue by peterjschroeder** [saulpw/visidata#638]
**Small description**
When exiting visidata in mlterm, the ALT key is being reassigned in the terminal for all other apps until closing the terminal.

**Expected result**
For it to not do that.

**Actual result with screenshot**
showkey shows this for "Alt+2" before i start visidata.

^[2      27 0033 0x1b
         50 0062 0x32

After exiting, showkey shows this for "Alt+2"

²       194 0302 0xc2
        178 0262 0xb2

**Steps to reproduce with sample data and a .vd**
Open terminal, open sheet with visidata, exit visidata.

**Additional context**
VisiData v1.5.2

**Comment by saulpw** [comment]
Hi @peterjschroeder, what OS and terminal program are you using?

**Comment by peterjschroeder** [comment]
Hello saul,
Sorry about that, that definitely should of been included.

Linux (Debian Sid)
MLTerm

**Comment by saulpw** [comment]
I run Linux also, and within an mlterm instance, when I press Alt+2, I get `²`, both before and after running vd.  It seems unlikely that it would be the exact distro or window manager.  Maybe it's the shell (I use zsh with oh-my-zsh)?

I don't think anyone's experienced this before, and I'm not sure if I can figure it out remotely.  Do you have any ideas what part of your configuration might be causing this?  If you want to come by freenode #visidata we can try talking it through, and if anyone else has this issue, please post a comment describing your setup and any clues you might have.

**Comment by peterjschroeder** [comment]
It was a TERM issue, saul helped me out. Thank you.

**Comment by saulpw** [comment]
@peterjschroeder was setting `TERM=xterm-256color` in zshrc, but MLterm needed `TERM=mlterm-256color`.  In general if you are having weird problems with your terminal, it probably has something to do with `$TERM`.

**Comment by peterjschroeder** [comment]
This has snuck back up. TERM is still set as mlterm-256color.

**Comment by peterjschroeder** [comment]
For whatever reason, if launched through tmux, this does not occur.

**Comment by peterjschroeder** [comment]
Here is what I believe is triggering this, I could be wrong tho.

I am thinking python curses messes with the keybindings and than restores it on exit to what is defined in the terminals terminfo.
I am also thinking that mlterm overrides the terminfo on startup. So when python curses restores it, it doesn't restore mlterm's overrides.
The newest mlterm terminfo from ncurses-term is broken without these overrides. Replacing it from an earlier version (6.1+20181013-2+deb10u2) makes the bug non-existent.
