### ISSUE TITLE
[dirsheet] open-row uses original filename after editing

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#645]
**Small description**
Changing the ext column on a dirsheet doesn't change the type of file being loaded

**Expected result**
Change the value of the ext column, then opening the file should use the value from ext rather than the file.

**Actual result with screenshot**
See result here:  https://asciinema.org/a/ztn4jYNBDJ9VSPTNCumxm1ES1

**Steps to reproduce with sample data and a .vd**
See

**Additional context**
Please include the version of VisiData. Latest version of develop.

**Comment by saulpw** [comment]
This is an interesting idea, @frosencrantz, I can see why you'd expect that to work.  The ext column isn't actually the filetype, though, just the extension of the filename.  If you used `z Ctrl+S` to write the changed extension, then it should work (you might a reload but I think it reloads automatically).

The core issue is that the Path objects used on a DirSheet refer to the actual underlying file, and the changes you've made before saving are 'deferred'; they are shown on-screen and used when the value of the cell itself is needed, but the Path object is unchanged.  This is pretty foundational to VisiData so this probably won't get fixed.

**Comment by frosencrantz** [comment]
Thanks @saulpw for the response.

It would be useful if changing the ext field would allow me to tell Visidata the filetype of a file.  There are a few filetypes that use json  as the base but have their own file extension, and it would be helpful to open them from a DirSheet.  So this would be a useful feature.

The code looks like it tries to:

https://github.com/saulpw/visidata/blob/develop/visidata/shell.py#L213

But as you point out the deferred changes are not  changing the Path object being used here as a row.

I'll mention that changing the ext column and committing the sheet doesn't change the extension. 
Based on your response that might be considered a bug.
  -  https://asciinema.org/a/GFaqV26E22Rcx9IctSwrR42Dy

For my use, I don't really want to tell Visidata to rename the file that can be done with the filename column.

**Comment by saulpw** [comment]
These are good points, @frosencrantz.  After you point out the code in shell.py, I think you're right, it should use the deferred value from the `ext` column, instead of the `ext` attribute on the row object.  And I agree, it would be better suited as a filetype column rather than a modifiable piece of the Path itself.

I tried to make a small fix, but pulling on the thread has got me to rethinking a design decision at the core of VisiData.  We can change it all in one go, and make it much more elegant and powerful.  It will have to wait until after 2.0 though :)

**Comment by frosencrantz** [comment]
That works just like I thought.  Thanks @saulpw that's great!  Glad it helped illuminate other issues.
