### ISSUE TITLE
[wishlist] Number rows starting at 1

### ISSUE THREAD

**Issue by chocolateboy** [saulpw/visidata#647]
VisiData has gone from [not having a convenient way](https://github.com/saulpw/visidata/issues/215) to number rows to having two different ways to do it:

- using <kbd>i</kbd> (iota) and family
- the [rownum plugin](https://github.com/saulpw/visidata/blob/19dcd50da53361527c2272636e0de0eea8c306fe/plugins/rownum.py)*

\* side note: is the plugin still needed now that support for this is built in?

These both work well :tada:, but the 0-based index makes it inconvenient to do basic things like find an item's rank or quickly count the number of items in a category. An extra calculation has to be done in each case to translate the 0-based index into the 1-based rank favored by [Excel](https://exceljet.net/formula/increment-a-calculation-with-row-or-column), [Postgres](https://www.postgresql.org/docs/10/functions-window.html)/[SQLite](https://www.sqlite.org/windowfunctions.html#built_in_window_functions) etc.

1-based numbering could be supported by adding a parameter to the existing commands, or adding new commands, but I'd be happy if it was just a config option, e.g. `options.iota_base` (default: 0), though I think the default [should be 1](https://ux.stackexchange.com/a/84298).

**Comment by saulpw** [comment]
Thanks for the suggestion, @chocolateboy, I think you're right.  The default is now 1 and there's an option `incr_base` as well.  `rownum` is still needed though as there's no convenient way to lookup a row by a column value..yet.
