### ISSUE TITLE
[2.4][aggregator] Cannot create custom aggregator in .rc

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#651]
**Small description**
I'm trying to create a custom aggregator as a plugin (standard deviation, 1/2/3)

**Expected result**
Ability to use my custom aggregator in vd

**Actual result with screenshot**
My aggregator does not show up in the available options when using `+`

**Steps to reproduce with sample data and a .vd**
Use the following lines in .visidatarc
```
from visidata import *
aggregator('stdev', sum)
```

**Comment by saulpw** [comment]
Thanks @geekscrapy, good catch.  This should be fixed with the above commit.  Don't forget the helpstr (and that 'sum' is not actually the `stdev` :)

BTW, you shouldn't need `from visidata import *` in your .visidatarc.

**Comment by geekscrapy** [comment]
Thanks!

That was a crude test to say "should this work?". I have a stdev agg that works, but it's not pretty (made it pretty soon after finding vd...!), it works though!
