### ISSUE TITLE
[wishlist] additional unfurl commands for subsets of rows

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#652]
I'm a happy user of the new unfurl command, but it would still be useful to limit unfurls.

I mentioned it here: https://github.com/saulpw/visidata/issues/623#issuecomment-660717042

It seems to have gotten lost or didn't seem useful to others.  I'm going to promote it here as a full FR.
You are welcome to Kondo it. 

There were two things that would help me for my data.

For the data I want to unfurl, the column contains lists of dicts, but
when there is only one dict there is no list, so the cell has just the dict.

Other data I've used is JSON data that has a mix of types in a column (lists, dicts, strings, etc).

So it would be useful if unfurl could be limited:

  - to only selected rows. unselected rows would be treated like a number is treated now.
  - add a way to limit unfurl to a specific type such as only lists or only dicts.

AJ fixed the issue with strings in https://github.com/saulpw/visidata/pull/639

It seems like it be helpful it there was unfurl commands for:

   unfurl-col-lists
   unfurl-col-dicts
   unfurl-col-selected

The last one would be sufficient to cover the other two.  The current command could be restricted to the current selection and default to all if there is no selection.

**Comment by saulpw** [comment]
Thanks for re-raising the issue, @frosencrantz, it did get lost in that last issue (this seems to happen once an issue is closed, further comments don't issue notifications).

`gzM` to apply to selected rows could work, even though it's technically a smaller subset.

These should all be pretty straightforward to implement.  I don't have a need for them myself though, so Kondo'ed for now.
