### ISSUE TITLE
[preplay] The preplay flag is looking for the wrong command (no binding for command)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#658]
**Small description**
vd -P command-name  doesn't work

**Expected result**
The -P flag runs the command listed.

**Actual result with screenshot**
https://asciinema.org/a/exF54SsNFfmfxZFE4AmEQBviB
Dashes are replaced with underscores.

**Steps to reproduce with sample data and a .vd**

```
vd -P=help-commands-all
```
**Additional context**
Please include the version of VisiData. latest from develop

**Comment by anjakefala** [comment]
Thanks!

Fixed in 31a0283b8ef95d4

**Comment by frosencrantz** [comment]
Thanks, @anjakefala. Sorry about the false report.  I thought I was running the latest version.
