### ISSUE TITLE
[expr] Add a shortcut name for the current column in expressions.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#659]
Add a simple way to reference the current column in expressions, such as for the addcol-expr  or  addcol-sh commands. Now you need to type out the full column name, it would be useful if you could also use a shortcut alias like  _ or $_  .

**Comment by saulpw** [comment]
How about a way to extend the input mechanism, so that you could set e.g. Ctrl+X or Alt+X to insert cursorCol.name at the cursor?

**Comment by geekscrapy** [comment]
Neat idea @saulpw 

I think it'd be good to keep it copy/pasteable as I (and I expect others do) have a lib of useful expressions for my line of work

**Comment by frosencrantz** [comment]
It does solve the issue I reported, but I am also interested in the issue of when the column name is not a usable Python identifier, like after expanding a column the names look like 'a.b'.  This can be handled by renaming the column or using Jeremy's vdnormcol plugin, but it adds a step after new columns are created by expand or addcol-*. 

But if adding a variable doesn't seem right, having a keyboard shortcut would be useful.  It would also be helpful if that keyboard shortcut could be customized.

**Comment by saulpw** [comment]
Attributes on the column itself are now part of the expression context, and column objects will automatically be applied to the row.  So if you add this to your .visidatarc:

```
Sheet.addCommand('=', 'addcol-expr', 'addColumnAtCursor(ExprColumn(inputExpr("new column expr="), curcol=cursorCol))', 'create new column from Python expression, with column names as variables')
```

You can then use `curcol` in an expression to mean "the value of this row in the column that the cursor was on when the expression column was added".

Note that e3a6d5d includes the above addcol-expr change, so for the moment you can use `curcol` without adding the addcol-expr to your .visidatarc, but it's not documented as I don't like the name, and so it will likely change or be removed before the next release.

Let me know if this proves useful, and particularly if you (or anyone) finds other uses for this that I didn't mention.

**Comment by frosencrantz** [comment]
@saulpw   Thank you very much for adding this!  I do find this useful. Great for column names not usable in a Python expression.  Also, I found it makes it easy to reuse the same simple expression on multiple columns.


I'm fine with `curcol`, that is consistent with the name used in the macros.  But if you are still looking to rename this, I be happy with a shorter name like underscore '_'.  ... _Alas, poor Perl!  I knew him, Horatio..._

**Comment by geekscrapy** [comment]
@saulpw I just tried this feature today and think there maybe an issue.

If you use the same expression but on multiple columns it only uses the original column as `curcol`

If I have two columns I want to apply the expr `curcol.casefold()` to. I navigate to the first and apply that expr with `=` (this works as expected, creating a column which looks lowercase), but then I move to another column and apply the same expr, it creates a new column but it is identical to the other newly created column. This makes me think that `curcol` isn't being updated somewhere.

**Comment by anjakefala** [comment]
Great find @geekscrapy! This should now be fixed.

I also added documentation, and a test. =)

**Comment by frosencrantz** [comment]
Great find @geekscrapy!  Thanks for quick response @anjakefala!

I hadn't tested using `curcol` on multiple columns but it occurred to me while replying that it should work.  Also it seems like it will work well with macros (I haven't tested it, yet).  

I really like this pronoun for column name vs. proper name. It adds some additional power. Wondering if there are other places where pronouns would be useful.
