### ISSUE TITLE
[visibility]: Make visibility more configurable

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#660]
When toggling visibility with the 'v' key, the height of the column has a fixed default of 10 lines.
From the Columns sheet it is possible to change this this value, but the height column is hidden by default.

Request:
  1. Add an option to allow users to override the default visibilty height.
  1. Don't hide the height column in the Columns table.

**Comment by saulpw** [comment]
I agree with you on these points, @frosencrantz.  Where in the column order do you think the height column should go?  Right after width?

**Comment by frosencrantz** [comment]
Yes, that is a good location.  That is where it currently is and that has been good for me.   Thank you @saulpw!
