### ISSUE TITLE
How to programmatically set value for current cell(within Python code)?

### ISSUE THREAD

**Issue by ZelenyeShtany** [saulpw/visidata#665]
Please help me, guys
I want to write my own command(via command() ) where I set a specific value for a cell under cursor. How do I do this?

**Comment by saulpw** [comment]
Hi @ZelenyeShtany, you want `cursorCol.setValue(cursorRow, value)`.  Hope this helps!

**Comment by anjakefala** [comment]
A reference: https://github.com/saulpw/visidata/blob/develop/visidata/sheets.py#L1009

=)

**Comment by ZelenyeShtany** [comment]
Thank you guys very much!
