### ISSUE TITLE
Error trying to connect to MariaDB

### ISSUE THREAD

**Issue by mappum** [saulpw/visidata#671]
**Small description**
I'm trying to use visidata with my MariaDB but it errors on connect.

**Expected result**
It should open visidata with the DB data.

**Actual result with screenshot**
![](https://i.imgur.com/Sp5xWbS.png)

**Steps to reproduce with sample data and a .vd**
See above.

**Additional context**
Visidata version: `saul.pw/VisiData v1.5.2` (installed via `pip3`)
MariaDB version: `mariadb  Ver 15.1 Distrib 10.5.4-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

I followed the instructions and installed `mysqlclient` through `pip3`.

Looking forward to playing with visidata!

**Comment by anjakefala** [comment]
Welcome @mappum!

mysql is still on the cutting edge of VisiData, for the upcoming 2.0 release, on the develop branch. If you wanna play with that branch, you install it with these instructions: https://www.visidata.org/install/#git

=)
