### ISSUE TITLE
Standard "--version" option removed in version 2?

### ISSUE THREAD

**Issue by mlawren** [saulpw/visidata#674]
**Small description**

The "--version" option is fairly standard for command-line tools, is present in the stable version of Visidata (1.5.2?), but is not present or functioning properly in version 2.-4.

**Expected result**

    $ vd --version
    saul.pw/VisiData v2.-4

**Actual result with screenshot**

Running "vd --version" has the same behaviour as if "--version" was not used at all. I.e. "DirSheet for the current directory...."

**Comment by saulpw** [comment]
Thanks for pointing this out, @mlawren.  We updated the CLI arg-parser recently and this one just slipped through the cracks (`--help` right below it is specified correctly).  Should be fixed now!
