### ISSUE TITLE
Incorrect date conversions

### ISSUE THREAD

**Issue by suntzuisafterU** [saulpw/visidata#677]
First I would like to say thank you so much for this software, it has revolutionized the way I work.

**Small description**
When converting dates of the form dd-mm-yyyy with the `@` command, conversion is incorrect.
For example 08-02-2020 becomes 2020-08-02 which is mixing up the day and month; 
while            16-02-2020 becomes 2020-02-16 which is correct;

These values are all in the same column, as such should be converted with a homogeneous date format.

**Expected result**

**Steps to reproduce with sample data and a .vd**
csv:
```
date
08-02-2020
16-02-2020
```

.vd:
```
sheet   col     row     longname        input   keystrokes      comment
                        open-file       vd_issue_sample.csv     o
vd_issue_sample date            type-date               @
```

**Additional context**
Visidata v1.5.2
Ubuntu 20 installation.

**Comment by saulpw** [comment]
Hi @suntzuisafterU, thanks for the report.  This is tricky, because we use the python-dateutil library for date parsing (one of our few core dependencies), and while it's a great library, it doesn't expose its internals.  So, we can't use it to detect the date format across many values and then e.g. use the mode of those formats to parse all of the values.

One idea that comes to mind, is to make a parameterizable custom date type which inherits from our date class, but takes a strftime-style format string as a parameter, and uses that to parse exclusively.  For instance, you would add something like this in your .visidatarc:

```
Sheet.addCommand('z@', 'type-customdate', 'cursorCol.type=customdate(input("date format: "))')
```

Then you would use `z@` with `%d-%m-%Y` to parse your date column.  What do you think about this method?

**Comment by suntzuisafterU** [comment]
Hi @saulpw,

The suggested method will work to solve my current issue. I'm more concerned with possible errors in the future though. For example the reason I found this error was that a related column was monotonic. In my opinion it would be best to throw an error if appropriate, however after looking at the source for this package and dateutil I agree that this is tricky.

Is it possible to attach a date format to a column when it is first converted to the specified type?

**Comment by geekscrapy** [comment]
I'd agree this is probably going to be overlooked by casual users (and myself) and might lead to some miscalculations. Fortunately, I've not come across it as I always work with a set date format that cannot be interpreted wrongly.

I thought this was a great point so posted it on the dateutil lib issue list, see what comes of it!

**Comment by geekscrapy** [comment]
I think the method you suggested @saulpw would be a great stopgap to force the correct format!

**Comment by saulpw** [comment]
> Is it possible to attach a date format to a column when it is first converted to the specified type?

@suntzuisafterU we could consider this if dateutil provided the date format it used to parse :)  Otherwise I'm not sure how to make this happen easily.

**Comment by suntzuisafterU** [comment]
Sounds good. I will use the method you described for now.

**Comment by saulpw** [comment]
Well it won't quite work without `customdate` which hasn't been written yet :)

**Comment by saulpw** [comment]
The dateutil parser provides `dayfirst` and `yearfirst` kwargs.  We can add options `date_dayfirst` and `date_yearfirst` to be passed through to the parser to get you what you want.  Still not automatic but at least makes it possible.  (and I'm guessing most of your dates are formatted in the same way, so you can set it in your .visidatarc as your personal default).

**Comment by suntzuisafterU** [comment]
My understanding of the `dayfirst` and `yearfirst` kwargs was that they only apply to `yy-mm-dd` and `dd-mm-yy` formats, not `yyyy` formats.

From the doc string: https://github.com/dateutil/dateutil/blob/master/dateutil/parser/_parser.py#L247
```
 :param dayfirst:
        Whether to interpret the first value in an ambiguous 3-integer date
        (e.g. 01/05/09) as the day (``True``) or month (``False``). If
        ``yearfirst`` is set to ``True``, this distinguishes between YDM
        and YMD. Default is ``False``.
```

Maybe this helps:
>Caution
>
>This does not support parsing arbitrary ISO 8601 strings - it is only intended as the inverse operation of datetime.isoformat(). A more full-featured ISO 8601 parser, dateutil.parser.isoparse is available in the third-party package dateutil. 

`dateutil.parser.isoparse` takes a format string, and could be used to implement `customdate`.
https://github.com/dateutil/dateutil/blob/master/dateutil/parser/isoparser.py#L60

Here is another possible alternative: https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime
>
>classmethod datetime.strptime(date_string, format)
>
>    Return a datetime corresponding to date_string, parsed according to format.


Returning to the original issue, the parsing of a string formatted `"%d-%m-%Y"` should be straight forward, and I am not sure why the datetime library would prefer `"%m-%d-%Y"`.  I tried parsing with `maya` and it does the same thing.  Tried `arrow` and it will not parse the string period.  

This would suggest that parsing strings where the year is not the first item is error prone.
I still have not seen any function to return the valid format strings associated with an input string.

**Comment by saulpw** [comment]
Okay @suntzuisafterU, try out the new `z@` and see if it fixes your issue.

**Comment by suntzuisafterU** [comment]
Works as advertised.  Thanks!

**Comment by aborruso** [comment]
> Okay @suntzuisafterU, try out the new `z@` and see if it fixes your issue.

This is great!! What about to add it as default command?

**Comment by saulpw** [comment]
Hi @aborruso, `z@` (`type-customdate`) is in VisiData already.

**Comment by aborruso** [comment]
Thank you @saulpw !

I have to buy another brand of coffee, the one I use is not very effective 🙃

**Comment by aborruso** [comment]
> Hi @aborruso, `z@` (`type-customdate`) is in VisiData already.

It's not in https://www.visidata.org/docs/v2.4/man/

Do I try to make a PR to add it?

**Comment by aborruso** [comment]
@saulpw after setting a custom date format, I have this error if I save as `vds`

![image](https://user-images.githubusercontent.com/30607/118446035-74ec1500-b6ef-11eb-803d-98fb637b602b.png)

My input

```
FID,nomeTesto,versionID,datasetIni,datasetFin
0,Piemonte,01,06/11/2020,20/11/2020
1,Valle d'Aosta,01,06/11/2020,20/11/2020
2,Lombardia,01,06/11/2020,20/11/2020
3,Calabria,01,06/11/2020,20/11/2020
```

My log

```
sheet	col	row	longname	input	keystrokes	comment
global		null_value	set-option			
			open-file	tmp.csv	o	
tmp	datasetIni	0	release-mouse		BUTTON1_RELEASED	slide current row/column to mouse cursor release position
tmp	datasetIni		type-customdate	%d/%m/%Y	z@	set type of current column to custom date format
tmp	datasetFin		type-customdate	%d/%m/%Y	z@	set type of current column to custom date format
```

My empty vds output

```
#{"name": "tmp"}
#{"name": "FID", "width": 5, "height": 1, "expr": 0, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "Column"}
#{"name": "nomeTesto", "width": 15, "height": 1, "expr": 1, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "Column"}
#{"name": "versionID", "width": 11, "height": 1, "expr": 2, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "", "col": "Column"}
#{"name": "datasetIni", "width": 12, "height": 1, "expr": 3, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "customdate(%d/%m/%Y)", "col": "Column"}
#{"name": "datasetFin", "width": 12, "height": 1, "expr": 4, "keycol": 0, "fmtstr": "", "voffset": 0, "hoffset": 0, "aggstr": "", "type": "customdate(%d/%m/%Y)", "col": "Column"}
```
