### ISSUE TITLE
no such executable `vd` appears after `pip3 install visidata`

### ISSUE THREAD

**Issue by daveloyall** [saulpw/visidata#68]
I'm using Debian sid.  I did approximately the following:

    $ apt-get install python3-pip
    ...success...
    $ pip3 install visidata
    ...some error about bdist_wheel...
    $ pip3 install wheel
    ...success...
    $ pip3 install visidata
    ...success...
    $ vd ~/data/my.csv
    bash: vd: command not found
    $ find ~/.pip ~/local/lib/python3.5 -iname vd
    ...not found...
    $ find ~/.pip ~/local/lib/python3.5 -iname visidata
    /home/hobbes/.local/lib/python3.5/site-packages/visidata
    ...(that's a directory)...

How should I be invoking `visidata`?  Thank you in advance...  Sorry I don't know how `pip` works!

**Comment by saulpw** [comment]
Hm, that should work...have you tried doing a `rehash`?  (Perhaps your shell has cached an invalid path for vd somehow?)  I will try to repro this myself with a Debian AWS instance.

**Comment by daveloyall** [comment]
$ rehash
    bash: rehash: command not found

**Comment by daveloyall** [comment]
It's unclear to me how `pip` expects to know what is in my `$PATH`.

Meanwhile, I didn't find any file named `vd` under the directories that `pip3` wrote to.  Unless it wrote to some directory not checked in the `find` commands in my multi-line paste above.

**Comment by saulpw** [comment]
I'm sorry, I don't know.  It's unfortunately outside the scope of my knowledge, and it works from a brand new instance for me.  Please do update this issue if you figure it out.

**Comment by daveloyall** [comment]
The vd binary was placed in `~/.local/bin`.  Thanks to `#python` on Freenode for that information!
