### ISSUE TITLE
Error when loading .xlsx sheets with empty column names for non-empty columns

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#680]
**Small description**

Currently on the `develop` branch (9f5411d), `.xlsx` sheets with empty/`None` column names for non-empty columns do not load properly.

As a demonstration, see these these two files: 

- [example-good.xlsx](https://github.com/saulpw/visidata/files/5178199/example-good.xlsx)
- [example-bad.xlsx](https://github.com/saulpw/visidata/files/5178198/example-bad.xlsx)

The `good` version loads as expected. In Excel/LibreOffice, it has a single sheet, which looks like this:

```
City      State
--------  ----------
New York  New York
Seattle   Washington
```

In Excel/LibreOffice, the `bad` version is identical, except that the second column has no name:

```
City      
--------  ----------
New York  New York
Seattle   Washington
```

**Expected result**

I would expect that the `bad` version would load fine in VisiData, as it has in previous versions.

**Actual result with screenshot**

Instead, the result of loading the file is this:

```
 sheet  ║ nRows#| nCols#║
 Sheet1 ║     0 |     1 ║
```

... accompanied by this error:

```
Traceback (most recent call last):
  File "[...]/visidata/threads.py", line 207, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "[...]/visidata/sheets.py", line 878, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "[...]/visidata/sheets.py", line 845, in setCols
    self.addColumn(ColumnItem(''.join(colnamelines), i))
TypeError: sequence item 0: expected str instance, NoneType found
```

Via git-bisect, this bug appears to have been introduced in https://github.com/saulpw/visidata/commit/bbbdd42dabd663691a720218d57e9887d0a5ef63; the `bad` example loads as expected until this commit. That seems to make sense, given the traceback, but I don't think I know the motivation of the commit (or the surrounding architecture) well enough to suggest a fix.

**Steps to reproduce with sample data and a .vd**

No command log necessary, I don't think. Just `vd example-bad.xlsx` should reproduce the issue.

**Additional context**

VisiData version v2.-5dev, 9f5411d

**Comment by anjakefala** [comment]
Hi @jsvine! 

Thanks for the bug report. =)

It seems that pyxlsx returns `None` for blank column names, and in Python lists that contain a `None` cannot be joined. I added a line of code to handle that.

This should now be fixed on `develop`.

**Comment by jsvine** [comment]
Thanks, Anja! Can confirm that the fix is working for me.
