### ISSUE TITLE
[paste column] Better feedback from setcol-clipboard

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#681]
I didn't read the documentation and Visidata didn't offer helpful hints.

I tried to copy the contents of one column from one table to another, and it didn't work.
I thought I had a bug, but it was PEBCAK. I missed that setcol-clipboard requires a selection to paste into.
I tried pasting without a selection, since that is my mental model of how paste works.

Visidata could have been more helpful here.  Visidata happily let me paste without any rows selected.

So this is my feature request.

   1. Allow pasting from the current cell down the column, add empty rows, if there are not enough rows. No selection required

If you think the current behavior is correct, Visidata could have been more helpful.

  1. If the selection doesn't match the size of the column clipboard, report the size difference via status, and
  give helpful statuses for these different cases:
     1. No selection: setcol-clipoard requires a selection
     2. Selection is smaller than the clipboard: not all values will be pasted.
     3. Selection is larger than the clipboard: values will be pasted more than once.

Right now it only reports if a value was pasted, for each value pasted.  It doesn't give much help other than that.
Showing attempts to paste with those three cases now:
https://asciinema.org/a/nI1LrotEsBNZ2ZlzIe5KmPbGa

**Comment by saulpw** [comment]
I agree that it should fail if no rows selected; this is now implemented in 7e5c69ef796175f59fb6bf3bd66ae16b936914a2.

A warning in the other cases may be useful and probably setcol-clipboard execstr should be pulled out into a proper function and check for all the cases.  Kondo'ed for now.
