### ISSUE TITLE
[regex] Add smartcase for regex selection

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#682]
Vim has a useful feature called [smartcase].  When doing regex searches it does a case-insenstive search if the pattern contains only lower case letters, while it does a case-sensitive search if the pattern contains upper case letters.

That would be nice for the commands that do regex selection.

[smartcase]: http://vimdoc.sourceforge.net/htmldoc/options.html#'smartcase'

**Comment by saulpw** [comment]
This seems pretty reasonable.  If we do this we should try to factor out regex expr matching so that it's done across the board.

Kondo'ed per wishlist policy. (A Workflow Optimist subscriber on Patreon can keep it open and in our awareness.)
