### ISSUE TITLE
[watch]: Add a way to automatically reload a data source based on time or other event.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#683]
The Unix `watch` command periodically runs the same command so you can see the results over time.
It would be useful if Visidata could automatically reload the same data source after a specified time.

It would also be useful if Visidata could run a command as a data source.  Currently it can only open files or URLs.

**Comment by geekscrapy** [comment]
I'd love this also - maybe a watcher thread that does the check and issues a reload if required?

**Comment by saulpw** [comment]
This is a good idea, @frosencrantz.  The original prototype of VisiData (called "tpmenu") had this feature, to reload the page every N seconds.  It also had something like `addcol-derivative` which created a column with a derivative of the current numeric column (so you could calculate rate from totals, for instance).  It was really useful for monitoring network statistics.

Kondo'ed per wishlist policy. (A Workflow Optimist subscriber on Patreon can keep it open and in our awareness.)

**Comment by frosencrantz** [comment]
I like the idea of the addcol-derivative.  I think that would be great.  The other thing that might be useful is a way to auto join on each reload, so that multiple input sources can be combined.

I do remember you saying something about the tpmenu in one of your interviews, though not by name.

Thanks, @saulpw.  I will wait until I can officially support the wishlist or a real sponsor does.

**Comment by dufferzafar** [comment]
@saulpw Was this ever picked up again? What's the current state of "reloading the data source" in visidata?

My usecase is to "watch" a CSV file that gets updated on the server ever 5-10 seconds. So by running something like `vd http://urlto.csv/` I can keep visidata open and it refreshes the data every 10 seconds.

How hard would it be to implement this as a separate sheet `AutoRefreshCsvSheet()` ? 

Having custom columns working with a reloading sheet would be good to have as well.

**Comment by saulpw** [comment]
Try this in your .visidatarc:

```
BaseSheet.addCommand('', 'watch-sheet', 'sheet.reload_every(int(input("reload interval (sec): ", value=1)))')

@BaseSheet.api
@asyncthread
def reload_every(sheet, seconds):
    import time
    while True:
        sheet.reload()
        time.sleep(seconds)
```

I also added this to vdplus.

**Comment by frosencrantz** [comment]
Thanks, @saulpw!  Very happy to see this new feature.
