### ISSUE TITLE
Question: Filter columns

### ISSUE THREAD

**Issue by mapa17** [saulpw/visidata#684]
Hello visidata community,
I believe this to be a quite frequent use case, but I somehow don't manage to be able to solve it myself.

**How can I filter columns by column name?**

I know, that I can remove columns with - (set their width to zero), but is there an easy way to somehow select columns in column sheet and than only show those in the source sheet.

thx!

**Comment by aborruso** [comment]
You could open columns sheet using `shift + c` and then use regex on fields column

**Comment by saulpw** [comment]
Hi @mapa17 ... yes, as @aborruso suggests, go to the Columns Sheet, use Regex to select the columns you want to hide, and then use `g-` to hide them.  (or `ge` to set the widths to 0, etc)
