### ISSUE TITLE
[DirSheet sort] Sorting the directory column of a DirSheet causes a stack trace.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#691]
**Small description**
Using the '[' or ']' on the directory column in a DirSheet causes a stack trace.

**Expected result**
Column sorted by directory name.

**Actual result with screenshot**
https://asciinema.org/a/FJrrGuR3HWWBRbp57OFFxpdKK

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/visidata/sort.py", line 58, in sort
    self.rows.sort(key=sortkey)
  File "/usr/lib/python3.8/site-packages/visidata/sort.py", line 38, in __lt__
    return other.obj < self.obj
TypeError: '<' not supported between instances of 'str' and 'Path'
```

**Steps to reproduce with sample data and a .vd**
`vd -r .`
tap '[' or ']' in the directory column

**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by anjakefala** [comment]
Thanks for the bug report @frosencrantz! =) This should be fixed on develop now.

**Comment by frosencrantz** [comment]
Thanks again, @anjakefala !

I'm not seeing as many bugs, which is a good thing if 2.0 is coming out soon.
