### ISSUE TITLE
[hierarchy col] Add a way to show a hierarchy column.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#692]
There are different data sources, where the data is in a parent-child relationship, and it would be useful if we could visually see that in VisiData.

Some examples:
  - Sheets in the SheetsSheet many tables have a source that is another sheet.
     - when I have similar named files, and try to perform similar operations on them so I can compare I've found the SheetsSheet can be hard to read to figure out where each sheet came from.
  - Directory listings.  Files are children of directories.
  - Structured data sources(xml, html, json, yaml) there are parent/child nodes.
  - ps command output, processes have a parent process.

I would like if there was a way to sort a column so that child and parents are in order so you can add a visual column that show the parent/child hierarchy.  There are examples of this in Unix terminal programs, like ps can show a tree, the tree command.

**Comment by geekscrapy** [comment]
This is something I've thought about as I have the need to show process listings (which are from XML). I was thinking it might be best as a graph-like sheet instead of a tabular format

**Comment by saulpw** [comment]
This is a good idea, @frosencrantz.  I've wanted this sometimes myself.  Not quite sure exactly how to do it, but it doesn't seem impossible.

Kondo'ed per wishlist policy.  (A Workflow Optimist subscriber on Patreon can keep it open and in our awareness.)

**Comment by frosencrantz** [comment]
Hi @saulpw 

I'm still not a sponsor, and can not promise to at this point.  

I do hope you can get a few more sponsors!  It looks like you've added Github sponsorship, too.  So is Patreon the preferred sponsorship? It would be good to say if you have a preference.

**Comment by saulpw** [comment]
I understand, not everyone can offer financial support.  I just wanted to provide people an incentive to keep their favorite issue on our radar.  I'm still figuring out how things work best.  It's all a big experiment :)

**Comment by dufferzafar** [comment]
@saulpw Have you thought about this recently? I would be up for implementing such a parent / child data viewer. For eg json etc.

**Comment by saulpw** [comment]
Hi @dufferzafar !  I'm getting back into VisiData after a few months of working on [Hanukkah of Data](https://hanukkah.bluebird.sh).  If you're still interested in this, I would love to talk with you about it.  Come chat with us on Discord at [visidata.org/chat](https://visidata.org/chat), or otherwise get in touch.  Looking forward to possibly working with you on this.
