### ISSUE TITLE
[type support] Better support for Python sets.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#693]
Feature request for better support for sets.

 - Currently diving into a Python set() only creates an empty table.
- Trying to expand a column of sets does nothing.
- Unfurling a set does work.  

It is possible to get a Python set() via the aggregate distinct or via Python expressions.
Sets are useful way to model columns that contain tags.

My request is that when expanding a column of sets, VisiData would expand each
value found in the sets as a separate a column.  In the newly created columns,
the values in the cells would either be the value or a True, when that value is
in the set being expanded.

There are workarounds, it is possible to convert the values of a set into the
keys of a dict() and then expanding this converted column of dicts.

**Comment by saulpw** [comment]
Makes sense, we could maybe use `(##)` as the display.  We'll keep it in mind.

Kondo'ed per wishlist policy. (A Workflow Optimist subscriber on Patreon can keep it open and in our awareness.)

**Comment by frosencrantz** [comment]
Yes, that would work.  Thanks @saulpw!
