### ISSUE TITLE
vd to explore a folder: set a default sorting option via display option

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#699]
Hi,
when I  use vd 2 to explore a folder, the records are sorted by modtime desc.

My propose is to add a display option to set a default starting sorting option: directory, filename, abspath, ext, size, modtime, owner, group, mode or filetype.

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, thanks for the suggestion.  What would you set this option to yourself?  And would you set it globally in your visidatarc, or on the CLI for a specific use?

**Comment by aborruso** [comment]
@saulpw  when I explore my PC content using folders, I have my default ordering that usually is by name (first folders and then files).
I have this default setting, that sometime I change.

It's in some way a background behavior, I have it without asking it every time I open a folder.

I would like to have it in the same way also for vd, then using visidatarc and not the CLI

**Comment by saulpw** [comment]
With the recent change in `develop` branch, this will work now (in your `.visidatarc`):

```
def open_dir(p):
    vs = DirSheet(p.name, source=p)
    vs.orderBy(None, vs.column('filename'))
    return vs
```

**Comment by frosencrantz** [comment]
@saulpw   this was a nice response.  I like the current default, but this
provides a mechanism for those that don't.

I wonder if it would be more consistent with Visidata[1] to allow for this
to be a global option so it could also be passed on the command line and via
.visidatarc.

This would allow the user to change depending on their need.  I generally
prefer sorting by modified, but there are times filename sorting would be better.


[1] Python has Pythonic, but what do we have for VisiData?
