### ISSUE TITLE
When there is a lot of content in a cell, I want to view it, how can I view it all?

### ISSUE THREAD

**Issue by joytianya** [saulpw/visidata#701]
When there is a lot of content in a cell, I want to view it, how can I view it all?、
Can you open the details with a simple enter or a simple combination

**Comment by ajkerrigan** [comment]
Hiya @joytianya - there are a couple ways to open the details of a big cell. One of these may cover what you're looking for:

- Use `z`+`ENTER` to open the cell in a new dedicated sheet
- Use `e` to begin editing the cell in-line, then `^O` while editing to open your default external editor ($EDITOR)

Sometimes I also like to quickly open a cell in my default system pager (`less` by default). In case that sounds like a useful option for you, I wrote a small plugin [here](https://github.com/ajkerrigan/visidata-plugins#vpager-open-long-cell-values-in-the-system-pager) to set that up and bind it to `z`+`^O`.

**Comment by anjakefala** [comment]
Does anyone (@ajkerrigan included!) have any other ideas for viewing the full content of a cell? =) I can think of 2-3 other methods. 

Thanks for asking @joytianya! This is a great question, and we are going to compile the answers into a FAQ.

**Comment by ajkerrigan** [comment]
> Does anyone (@ajkerrigan included!) have any other ideas for viewing the full content of a cell? =) I can think of 2-3 other methods.

Ha, don't make us beg! I can't think of any other ones offhand, I'm curious about your 2-3 though :). (I'm assuming things like horizontal scrolling or using `v` to turn on wrapping don't count for this question, though they're still helpful in some cases.)

**Comment by anjakefala** [comment]
You got one! Multi-row definitely counts. =)

**Comment by geekscrapy** [comment]
`zY`, *opens sublime*, ctrl+v 😅

**Comment by frosencrantz** [comment]
`view-cell` ?   similar to `open-cell` which is `z` + `Enter` 

I guess you could also split the cell value.   But I doubt this one is on the list... 

I'd like to know, too.  :)

**Comment by anjakefala** [comment]
The final one is changing the width of the column with `_` or through the Columns sheet =)

**Comment by saulpw** [comment]
There's also `zh` `zj` `zk` `zl` now in 2.0, to change the offset with a column's cells, so you can "scroll" through contents, if the first cell width/height is not differentiating enough.
