### ISSUE TITLE
[community question] Where does your data go after Visidata?

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#703]
I wonder how do people use Visidata in their workflows?

For me, I mostly use it to find insights about my data.  I might use that insight to take some immediate action, or I might use it as background understanding.  Sometimes I export a table (via [vdtabluate](http://github.com/jsvine/visidata-plugins#vdtabulatepy)) and share it with others.

Where does your data go after Visidata?
  - Are you using Visidata to clean, convert or reshape the data?
  - Is the data going into Excel, notebooks, R, etc?
  - Are you sharing the data with others? How?

**Comment by saulpw** [comment]
This is a great question, @frosencrantz!  Just yesterday I found myself using `gs` `gzY` (`select-visible` then `syscopy-cells`) to copy a column of values to my system clipboard, which I then pasted into vim.

I also wonder if most people know about `Ctrl+Q` when combined with stdout redirect (which makes vd into a kind of interactive selector in the middle of a pipeline).  I hope other people will chime in with their 'data destinations'!

**Comment by ajkerrigan** [comment]
Sweet question :). (Also appreciate the mention of [vdtabulate](https://github.com/jsvine/visidata-plugins#vdtabulatepy), I've scrolled right past that and never used it before!)

>     * Are you using Visidata to clean, convert or reshape the data?
Sometimes. I've used VisiData with [vfake](https://github.com/saulpw/visidata/blob/develop/plugins/vfake.py) to get scrubbed data from private sources. It's nice to have a safe, quick way to interactively sample and scrub data. Really handy for creating test data from real API responses, or providing documentation with reproduction steps for software issues.
> 
>     * Is the data going into Excel, notebooks, R, etc?
For my own use, probably not. For sharing with other folks, yes.
> 
>     * Are you sharing the data with others? How?
Excel, Google Docs, Jira comments/attachments, S3...

I'm not sure if screensharing counts for this question. I've occasionally used VisiData to help with brainstorming or troubleshooting calls though.

**Comment by anjakefala** [comment]
Hi @frosencrantz!

To keep our issue counts manageable, I am going to close this issue, and direct folks to write aboutt where their data goes afterwards in #595. =)

Thanks for creating this lil space. :purple_heart:

**Comment by frosencrantz** [comment]
It was very nice to see this pinned for a while.   I do think this is a different question #595 

It is was great to hear from Saul and AJ.  I would have liked to hear from other regular contributors such as yourself. I was hoping it would generate more interest.
