### ISSUE TITLE
regex/capture split for rows

### ISSUE THREAD

**Issue by lxcode** [saulpw/visidata#705]
It would be super handy to be able to specify a capture pattern for duplicating rows. For example, if you had a text field that had multiple URLs, e-mails hashtags, etc, you could specify a capture pattern, make one row for each capture as well as a new column for the capture results, and then you can do a frequency analysis to find the most common ones in the dataset.

So for example:

`"A tweet with #BTS #visidata #cutlery"`

split with (\B#\w\w+) capture

```
"A tweet with #BTS #visidata #cutlery"     "#BTS"
"A tweet with #BTS #visidata #cutlery"     "#visidata"
"A tweet with #BTS #visidata #cutlery"     "#cutlery"
```

Would this be a possible enhancement? Or is there functionality to do this somewhere that I'm missing?

**Comment by ajkerrigan** [comment]
Hmm that's an interesting idea. I thought perhaps that `capture-col` (`;`) would cover that, but I tried a couple different variations and it didn't work the way I was expecting.

I'm sure other folks will jump in with some solutions, but I can offer a workaround in the meantime at least. Assuming you were starting with a sheet like this:

```
 text                                 ║
 A tweet with #BTS #visidata #cutlery ║
```

You could use `=` to create a new column using the Python expression `re.findall(r'#\w+', text)`:

```
 text                                 | re.findall(r'#\w+', text) ║
 A tweet with #BTS #visidata #cutlery | [3]                       ║
```

That new columnn would be a list of all matching hashtags. Then you can use the recently added `unfurl-col` to split that list out into rows:

```
 text                                 | re.findall(r'#\w+', text)_key | re.findall(r'#\w+', text)_value ║
 A tweet with #BTS #visidata #cutlery | 0                            #| #BTS                            ║
 A tweet with #BTS #visidata #cutlery | 1                            #| #visidata                       ║
 A tweet with #BTS #visidata #cutlery | 2                            #| #cutlery                        ║
```

If there's not a better native option available, it might be worth packaging this up for easier general reuse. Neat idea in any case!

**Comment by saulpw** [comment]
Hi @lxcode, this is an interesting request.  We could make a `capture-col-all` (bound to `g;`) that uses `re.findall()` instead of `re.search()`, which would create a column with a list of matches that you could then expand or unfurl as @ajkerrigan suggests.

**Comment by lxcode** [comment]
g; sounds pretty flexible and unintrusive to me. For the moment I just declared a few regex functions in my .visidatarc using @ajkerrigan's approach. Thanks!

**Comment by saulpw** [comment]
Kondo'ing for now.
