### ISSUE TITLE
Incorrect command in man page for View traceback for most recent error(s)

### ISSUE THREAD

**Issue by aac** [saulpw/visidata#707]
In the man page:

> ^E  g^E         view traceback for most recent error(s)

But the actual commands seem to be ^e and g^e.

**Comment by anjakefala** [comment]
Hi @aac!

Yeah...That was intentional. We prefer the aesthetic of `Ctrl+E` and `^E` over `Ctrl+e` and `^e`. This applies to all of the Ctrl commands. 

We are going to leave a note in the documentation mentioning that, because yes, that can definitely be confusing.

**Comment by aac** [comment]
Ahh, got it. Fair enough. Feel free to close?
