### ISSUE TITLE
[v2.-5dev] add-row in ThreadsSheet causes uncaught exception

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#713]
As per the title 😀

I accidentally hit `a` and found this...

**Comment by saulpw** [comment]
Nice find, @geekscrapy.  I haven't seen one of those in awhile!  Should be fixed now.

**Comment by geekscrapy** [comment]
Out of interest is there a command that would remove a command for a sheet? Additionally is there a way to enumerate all commands for a sheet class?

**Comment by saulpw** [comment]
You can view all commands for all sheets with `gz Ctrl+H`, and there is a column for the class.  It might be fun to add a `d`elete command which removes the command from within VisiData.  But I assume you mean removing a command from a plugin or .visidatarc?  If so, 'unbind' is probably what you're looking for.  The command will still be there, but unbound.
