### ISSUE TITLE
Guess column names based on file name

### ISSUE THREAD

**Issue by skeept** [saulpw/visidata#715]
I have some files which are essentially csv files without headers. They usually end with .dat. I have an alias to be able to open these directly:

```
alias vc=vd --filetype csv --header 0
```

This works well but then obviously I don't get column names.
But given that I know the column name based on the name of the file I am using the following hack:

```
Sheet.addCommand("gw", "set-col-names", 'guessColNames(source, visibleCols)')

cc = None
def guessColNames(source, cols_input):
    source = os.path.basename(str(source))
    cols = []
    if source == "file_1.dat":
        cols = "col1 cc2 cc3".split()
    elif source == "file_2.dat":
        cols = "co1 sr grn fetch".split()

    global cc
    cc = cols
    return cols

def d():
    return cc
```

So what I do is first use `gw` then use `C` to open columns-sheet and once there `gz=d()` to actually set the columns name.

My question is if there is a less hacky way to do this, essentially do all this work just with one command.

Another related question is if it is possible to skip the alias and have some logic in the configuration file that if the file name matches a given file name assume what I am using right now for the alias.

Thank you.

**Comment by saulpw** [comment]
Hi @skeept, this is an interesting question.  How about:

    vd.likelyColNames = {
       'file_1': "col1 cc2 cc3",
       'file_2': "co1 sr grn fetch",
    }

    Sheet.addCommand("gw", "set-col-names", 'for col, name in zip(visibleCols, likelyColNames(source.name).split()): col.name = name')

(untested, but hopefully works without too much difficulty)

**Comment by skeept** [comment]
Thank you @saulpw.

What I was missing was that I could use the `.name` to set the column name. With that I could solve the problem.
Here is what I ended up for reference in case it may help other users:

```python

Sheet.addCommand("gw", "set-col-names", 'guessColNames(source, visibleCols)')

def guessColNames(source, cols_input):
    file_name = os.path.basename(source.resolve())
    names = []
    if file_name == "file_1.dat":
        cols = "col1 cc2  . cc3".split()
    elif file_name == "file_2.dat":
        cols = ".co1 sr grn fetch".split()


    for col, name, idx in zip(cols_input, itertools.chain(names, itertools.repeat(".")), itertools.count(0)):
      col.name = name if name != "." else f"c{idx}"
```

The last part is just a trick to have some columns that I ignore show up with a c and a number, for example `c2` in the case of file_1.dat above.
