### ISSUE TITLE
It is unclear how to quit for new users without consulting docs

### ISSUE THREAD

**Issue by theosanderson** [saulpw/visidata#716]
I just Installed VD and got stuck in it, unable to quit, because I didn't know the shortcut, not unlike [this](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/). I expect I'm not alone. (Yes, I should have RTM).

Suggestion: You could add `(press q to quit)` to the `no active threads on this sheet` that users typically get on instinctively pressing `ctrl-C`.

Just a thought.

**Comment by theosanderson** [comment]
I guess this actually applies to most command-line tools so I've reconsidered

**Comment by saulpw** [comment]
Thanks for the suggestion, @theosanderson.   I tried to make quitting be as easy and intuitive as possible, and the first section of every tutorial, manpage, etc includes "how to get out of trouble", with `q` and `Ctrl+Q` at the top of the list.  When we audit all the messages in VisiData, we'll definitely consider adding something to `Ctrl+C` to help the process along.
