### ISSUE TITLE
[guidance] Guidance on default keystrokes for plugin commands

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#719]
Would it be useful to provide some guidance on the default keystrokes that plugins should use?

There is a plugin I'm using which does an  that overrides a default keystroke for a builtin command I use.
I can remap the commands from my .visidatarc file, so this doesn't stop me, but does add inconvenience when installing the new plugin.
Also, I'm not sure what happens if there is a longname conflict.

Vim has a concept of the Leader key prefix, which provides a namespace for plugin keystrokes.

It would be wonderful if we see more plugins in the future.  Wondering if this needs a solution.

**Comment by anjakefala** [comment]
Thanks for bringing this up! This is a reasonable concern.

We do provide a Leader key prefix (`Alt`, documented [here](https://www.visidata.org/docs/develop/api/commands.html#keybindings)), and we do try to review for things like "longname conflicts" and potential keystroke conflicts when we are curating the plugins. 

Leaving this open in case @saulpw has more that he wants to add. =)

**Comment by saulpw** [comment]
Yes, as @anjakefala mentions, `Alt` is our user-defined keystroke space.  Maybe we should enforce it for plugins, unless they are extending an existing command.

@frosencrantz, you can add your own leader key to `vd.allPrefixes` as documented on that same page, and then use it for your own command bindings.  Does that page answer most of your questions?
