### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by tkossak** [saulpw/visidata#72]
When i start vd with `vd file.csv` or just `vd` all I see is black screen and nothing happens (can't write anything, `ctrl+c`, `ctrl+z`, `ctrl+/` don't work either). Any ideas what could be wrong? I intalled it via `pip install visidata`.

visidata 0.91
Python 3.6.1
Linux Mint

**Comment by saulpw** [comment]
Could be a colors issue.  Check your TERM setting.  Btw Ctrl-q should quit even in such dire circumstances.

**Comment by tkossak** [comment]
I just tried it on my other computer with latest Linux Manjaro and i have the same problem. Here i use:
xfce4-terminal 0.8.5.1
`$TERM=screen-256color` (inside tmux)
`$TERM=xterm-256color` (also tried without tmux)
Python 3.6.1
visidata 0.91

`ctrl+q` doesn't quit the black screen either.
I also renamed my `.bashrc` and started new bash shell - effect is the same (black screen after running vd).
I also tried changing `$TERM` to `xterm` but to no avail.
I use anaconda version of Python3 if it makes any difference? `'3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]'`

**Comment by saulpw** [comment]
The lack of ctrl+q likely means that curses isn't working at all.  It might be that anaconda Python3 doesn't come with curses.  Please update this issue if you get it working.

**Comment by tkossak** [comment]
@saulpw i have curses installed:

```
» python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> curses.version
b'2.2'
>>> import visidata
>>> visidata.__version__
'saul.pw/VisiData v0.91'
>>> 
```

Anything else i might be lacking?
