### ISSUE TITLE
`random-rows` command no longer available

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#720]
**Small description**

Longname command `random-rows` appears no longer to be available.

My guess is that this is because https://github.com/saulpw/visidata/blob/develop/visidata/max.py is not imported into the global namespace.

**Expected result**

Users should be able to run `random-rows` command.

**Actual result with screenshot**

After raising the longname command prompt with `Space`, and then entering `random-rows`, the statusbar says the following:

`1› | no binding for random-rows | "random-rows"`

**Steps to reproduce with sample data and a .vd**

See above.

**Additional context**

VisiData 2.-5dev, commit 0b206baa3aa8e0366b339bf7ae97f04b0d6db5bc

Setup: MacOS, iTerm2, `tmux`, `bash`

**Comment by saulpw** [comment]
Thanks for reporting, @jsvine.  Just slipped through the cracks  Should be back in now.

**Comment by jsvine** [comment]
Super, thanks!
