### ISSUE TITLE
[savers] Tabulate savers all save same format

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#723]
**Small description**
Tabulate savers all save same format

**Expected result**
Savers save in named format

**Actual result with screenshot**
**Steps to reproduce with sample data and a .vd**

```
vd sample_data/benchmark.csv
^S benchmark.plain
```
Save a file with the new tabulate formats.  benchmark.csv  to benchmark.plain
The format is not plain.

It looks like the bug is here: https://github.com/saulpw/visidata/blob/d67612c935bab59faea6e130af5d4d029e3c7c23/visidata/loaders/texttables.py#L15  because of https://bugs.python.org/issue13652

**Additional context**
Please include the version of VisiData. 2.0.1

While not the best place to say this: Congratulations on 2.0!!! Very excited to see the new version.

**Comment by saulpw** [comment]
Thanks for finding and filing the bug, @frosencrantz!  I knew there were going to be some right out of the gate.
