### ISSUE TITLE
No module named 'curses'

### ISSUE THREAD

**Issue by yonist** [saulpw/visidata#725]
After installing on EC2 instance  with AWS Linux 2 and python 3.6 (using `pip install visidata --user`) I get the following error :

Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/vd", line 3, in <module>
    import visidata.main
  File "/home/ec2-user/.local/lib/python3.6/site-packages/visidata/__init__.py", line 31, in <module>
    from .vdobj import *
  File "/home/ec2-user/.local/lib/python3.6/site-packages/visidata/vdobj.py", line 3, in <module>
    import curses
ModuleNotFoundError: No module named 'curses'

**Comment by anjakefala** [comment]
Hi @yonist!

This happens when the necessary developer package of `ncurses` is not available on an OS while Python is being built. Python requires those header files in order to build the curses module. 

If you google the message, lots of different people offer various suggestions for fixing it. =) Good luck!

**Comment by startakovsky** [comment]
Why wouldn't this dependency automatically install  or there be something in the Installation docs about this? Running Mac OS 11.2 with pyenv managing my environments. Thanks.

**Comment by saulpw** [comment]
curses is part of the standard library, so it's either there or not depending on how the Python package itself was configured.  It does seem strange that a MacOS version of Python would be using a Python without curses though.  If you find any more clues or figure out a solution, please post back here!  I'm very curious what the ultimate issue is.

**Comment by jabellcu** [comment]
This fixed it for me on windows: `python -m pip install windows-curses`
