### ISSUE TITLE
[loaders xlsx] Provide hidden and active sheet indicators when opening spreadsheet

### ISSUE THREAD

**Issue by kbd** [saulpw/visidata#726]
When I open a spreadsheet in LibreOffice (or Excel...), it opens to the last-active sheet. VisiData first provides me a choice of a number of sheets, some of which are hidden in the Excel file, without indication of which is the active sheet. So if I get a spreadsheet given to me and want to explore it in VisiData, I can't tell which sheet the sender was intending me to look at without first opening it in a GUI spreadsheet program.

Suggestion: in addition to the `sheet`, `nRows#`, and `nCols#` columns in the sheet selection, show a "hidden" true/false column and mark the active sheet somehow (egs. with a leading asterisk like git, highlighting in a different color, a true/false column).

**Comment by saulpw** [comment]
Hi @kbd, thanks for the suggestion.  You can add this to your .visidatarc:

    XlsxIndexSheet.columns += [Column('active', getter=lambda col,row: row.source is col.sheet.workbook.active)]

It's a good idea and I've added it to xlsx loader to be included in the next release.

I can't see how to know if a column is hidden or not from the [openpyxl library](https://openpyxl.readthedocs.io/en/stable/api/openpyxl.worksheet.worksheet.html?highlight=hidden) that's used for .xlsx files.  If we can figure out how to get the information from the library then adding it to VisiData is trivial.

**Comment by kbd** [comment]
> If we can figure out how...

Looks like it's:

```python
from openpyxl import load_workbook
wb = load_workbook('file.xlsx')
for name, sheet in zip(wb.sheetnames, wb.worksheets):
    print(name, sheet.sheet_state)
```

(I couldn't immediately find if a worksheet knows its own name, hence the `zip`)

So, looks like `workbook.worksheets[i].sheet_state` is either "hidden" or "visible". Could show that column directly? Currently trying to figure out how to traverse to there in that getter function in your example (which works btw, ty!) so I can add the column to my sheet list.

**Comment by kbd** [comment]
There we go:

```python
[Column('state', getter=lambda col,row: row.source.sheet_state)]
```

**Comment by saulpw** [comment]
Nicely done!
