### ISSUE TITLE
Collecting use cases from the community

### ISSUE THREAD

**Issue by amotl** [saulpw/visidata#730]
Hi again,

it would be cool to start a collection of things how VisiData is used by others beyond what is currently on [1] and [2]. @IanCal added an example on [3] the other day. Enjoy!

Cheers,
Andreas.

[1] https://www.visidata.org/blog/2020/ten/
[2] https://www.visidata.org/docs/
[3] https://news.ycombinator.com/item?id=24774947

---

> Here's a quick example from today of why I find it such a general purpose tool.
> 
> Pipe in some fixed-width formatted data
> 
>     kubectl get pods | vd -f fixed -
> 
> Gives me a searchable, usable output. Press right to highlight the status column, shift-f and I get a count (+histogram) of the statuses. Three have failed. Hit enter on that row and I can see specifically which ones have failed. This takes a few seconds (I just tried and did it under 5 from running the above command).
> 
> If I knew I wanted the failed ones I could have grepped or similar but I can then order by most restarts, etc.
> 
> This is a tiny part of the functionality but it's an example of "there's some tabular-ish data but what's there?". Load X, histogram, filter, sort is probably 90% of my use-cases. 
> 
> -- https://news.ycombinator.com/item?id=24776820

**Comment by anjakefala** [comment]
This is really lovely @amotl! Thank you for sharing. =) Would you mind reposting this in https://github.com/saulpw/visidata/issues/595?

This was one of the aims of that issue. We want to keep our number of open issues to a single page, so I am going to close this one, and encourage people to share their stories in https://github.com/saulpw/visidata/issues/595. 

:purple_heart: :bee:

**Comment by amotl** [comment]
> Would you mind reposting this in #595?

Can do, thanks for the advice. Maybe @IanCal wants to do that on his own behalf? Actually, I've hijacked his contribution from HN ;].

**Comment by amotl** [comment]
Hi again. I've added this at https://github.com/saulpw/visidata/issues/595#issuecomment-710065136. Thanks!
