### ISSUE TITLE
Using select-equal-cell to select dates

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#734]
When using `select-equal-cell` I have noticed that it only selects if the underlying cell value is equal. An example of this is with a date column.

*Scenario*
I have a column of dates with a resolution to a second, but that column has a `disp_date_fmt` of `%Y-%m-%d` (does not show the full resolution). I want to select all similar rows with the same date so I use `select-equal-cell`.

*Expecting*
All rows **showing** the same value (display value) as the current cell to be selected. Irrelevant of the underlying cell value.

*Actual*
`select-equal-cell` only selects rows which have the exact matching underlying cell value, and for these particular dates, these are resolutions to the second. This means that only cells that have the exact same second are selected.

I expect this to be the same for more than date column types, but I've not found it yet.

**Comment by ajkerrigan** [comment]
That's interesting, I haven't run into it before but I also would have assumed it would select based on the display value rather than the underlying true value.

Is there a place for both behaviors? Like maybe `z,` selects based on the underlying value because then things are `z`actly equal? 😁

**Comment by geekscrapy** [comment]
@ajkerrigan At first, I think I'd agree, but then that would rely on me remembering what the actual underlying value is, and I can't think of an example when this wouldn't be the case. You? I mean, it's pretty much only a binding away (unless there is a significant code change to select the display value).

Thinking about it, this is likely working as designed. The getValue functions are quite slow (as commented in the codebase, not my opinion!) and so this may add a ton of execution time if each cells disp value needs to be obtained. But that's just me thinking out aloud!

**Comment by ajkerrigan** [comment]
Hmm @geekscrapy, thinking through it a bit more I'm realizing I have my date display format always include hours and minutes. And the only times I've _selected_ based on date, I've extracted the components I cared about into a dedicated column for that purpose. I guess that means practically I don't have a horse in this race concerning the behavior of `select-equal`. I'll be over here talking at myself, hehe 😊

**Comment by saulpw** [comment]
The current behavior is useful for e.g. distinguishing a literal `None` from an empty string or an error, but I can also see how selecting based on the displayed value is more expected and intuitive.  I like @ajkerrigan's idea of `z,` (currently unbound) meaning `select-exact-cell`, and it's super easy to implement, so let's just go with it.
