### ISSUE TITLE
[loader] Add a toml loader

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#735]
See this page: https://pypi.org/project/toml/

It answers both of these questions:

1) A small sample representative dataset in that format.

2) A basic Python script which queries and dumps the data (possibly using an external package).

I've started to see files in the format.  It would be nice to be able to use VisiData to read these files.

**Comment by saulpw** [comment]
Noted and Kondo'ed.

**Comment by frosencrantz** [comment]
Awesome!  Thank you, @ajkerrigan !

I saw that you had added the new loader to your plugins, and was going to update this issue.  Looks like you beat me to it, which is great!

I can't say I've seen a very large toml file yet.  But I love the fact that Visidata can now handle this format, its usage is increasing.

**Comment by ajkerrigan** [comment]
Yeah, I haven't had very large files either. But for reviewing Python packaging stuff I was already using VisiData to peek inside Python wheels (yay `vd.open_whl = vd.open_zip`). But for browsing `pyproject.toml` (and more importantly `poetry.lock`) files, VisiData support for TOML was a nice win. It seems a weird fit for big data files for sure, but a tabular view over a config file is just more useful (and dare I say sexier?) sometimes.
