### ISSUE TITLE
[github metadata] Update metadata.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#737]
After you have time to catch your breath.  It might be worthwhile to clean up some of the GitHub project metadata.

Some of the items that can help attract more interest would be:
   - Adding topics
   - Adding a Social Media Image
   - Update the README to a link to the Twitter account.
   - Adding community items like a "code of conduct" and a PR template.

**Comment by saulpw** [comment]
These are good reminders.  What topics would you suggest, @frosencrantz?  And where does the social media image show up; could we just use the logo?

**Comment by frosencrantz** [comment]
I think the logo would be fine, or a some sort of screenshot. For the social media image, the places I've seen it show up on:
   * Twitter
   * Within GitHub such as topics or explore:
       * https://github.com/topics/spreadsheet


Topics I might use:
   * https://github.com/topics/spreadsheet
   * https://github.com/topics/tui
   * https://github.com/topics/csv
   * https://github.com/topics/tsv
   * https://github.com/topics/json
   * https://github.com/topics/pandas
   * https://github.com/topics/eda
Perhaps look at topics used by related projects like:
   * https://github.com/johnkerl/miller 
   * https://github.com/OpenRefine/OpenRefine

**Comment by anjakefala** [comment]
Ideas for social media image

![vdlogo](https://user-images.githubusercontent.com/7489659/98071767-4f658100-1e19-11eb-9e4f-e31f1569f2c7.png)
![vd-rtd](https://user-images.githubusercontent.com/7489659/98071783-57bdbc00-1e19-11eb-9b70-3a418a2cb429.png)
![freq-screenshot](https://user-images.githubusercontent.com/7489659/98071795-5e4c3380-1e19-11eb-86f4-fff6709810e5.png)
![basic-screenshot](https://user-images.githubusercontent.com/7489659/98071810-660bd800-1e19-11eb-8fd9-de41ecad5be4.png)

**Comment by saulpw** [comment]
Thanks for reminding me about that second image, @anjakefala .  I redid it and made it to Github's specifications, and now it's uploaded.

**Comment by frosencrantz** [comment]
Awesome progress!
