### ISSUE TITLE
[2.0] Congratulations on 2.0!  🎉

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#738]
Just wanted to say thank you so much @saulpw and @anjakefala  for getting 2.0 out!

Also, a couple other big accomplishments this week:
   - Breaking 3000 GitHub stars (and also 3100)
      - https://asciinema.org/a/366119
   - Making GitHub top 25 Python trending repositories for the day.
   - Getting more Patreon supporters  (now ~~26~~ 28)
   - Hacker News article about the 2.0 release
       - https://news.ycombinator.com/item?id=24774947
   - A new contributor
   - A new tutorial on the S3 plugin.  (Thanks @ajkerrigan )

So happy to see all this great work be recognized by more people.

**Comment by ajkerrigan** [comment]
@frosencrantz nice touch plotting stars over time 😀

**Comment by saulpw** [comment]
Thanks so much, @frosencrantz!  That's a really cute demo and graph of our star count.  And I didn't know we got in the Github top 25 trending!  That's amazing.  Thanks for cataloguing our progress.

**Comment by frosencrantz** [comment]
I noticed VisiData in the trending repositories for Python the day before I posted.  It might have been there several days.  I'm not sure if there is way to look back at past days.

I've noticed a few more sponsors so updated the original comment, and noticed there are a couple more YouTube videos using VisiData from a couple different creators.

Thanks again for all the great work!
