### ISSUE TITLE
Enter key results in ^M on windows

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#741]
**Small description**
Pressing enter results in ^M in terminal and message "no command for ^M".  
**Expected result**
Pressing enter should execute the command, submit filter, etc.
**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.
open command prompt, type visidata
**Additional context**
Please include the version of VisiData.
windows 10
tried multiple command terminal options (including legacy)
also tried phython3.7

python 3.9

pip3 list
Package         Version
--------------- -------
pip             20.2.3
python-dateutil 2.8.1
setuptools      49.2.1
six             1.15.0
visidata        2.0.1
windows-curses  2.2.0a1

**Comment by saulpw** [comment]
Thanks for the bug report, @bob-u.  5ee1640 should fix this issue; we'll include it with the next release, or you can try it out yourself on the `develop` branch.

**Comment by bob-u** [comment]
Thanks!  Enter is working now on Windows.
