### ISSUE TITLE
[UI] Add menus for command discovery

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#742]
VisiData is fantastic.

I just think it would be more accessible if you added menus to get at categorized operations.
Also, typing ? should show some help rather than backwards regex search.  I know you have a command that shows all key mappings in a sheet view but think of a new user just trying to find help initially.

Here is a writeup on how to create menus with the panel curses extension:
https://stackoverflow.com/questions/14200721/how-to-create-a-menu-and-submenus-in-python-curses

**Comment by saulpw** [comment]
Hi @rswgnu, thanks for the suggestions.  I agree that VisiData could use some menus to aid in command discovery, and now that 2.0 has shipped I'm gearing up to explore some ideas I have for a menu system.

As for `?`, it might not be the best binding overall, but it goes along with the vi commands `/` and `n` and `N`.  VisiData help is on `Ctrl+H`, which launches the manpage, searchable with those same `/` and `?` bindings within `man` itself.  I think this makes for a more consistent and seamless experience, even if it is a bit more difficult for some people the very first time they use it.  We call it out at the beginning of the manpage and docs and tutorials and in a startup status message so hopefully that helps people too.

Kondo'd for now.

**Comment by rswgnu** [comment]
Thanks for the detailed response.  I'll look forward to your menu ideas.

On the help key, C-h is fine and the man page reasonable.  Maybe there is a need for a quick help as well with a very short summary of most commonly used keys for selection, sorting, filtering and summarizing.
