### ISSUE TITLE
[Windows v2.0] Enter does not work when trying to submit regex under windows.

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#744]
**Small description**
when entering regex pressing enter does nothing.  This is probably related to ^M bug from yesterday.
**Expected result**
I expect that enter will execute the regex filter
**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
open a file, go to column, press "|", type regex filter, press Enter key.
There are probably other keys not working, I just have not used Linux version to know what to expect.  For example, ctrl+h does not bring up help which I believe it is supposed to.
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData.
Same as here: https://github.com/saulpw/visidata/issues/741

**Comment by saulpw** [comment]
Thanks for the bug report, @bob-u.  This should be fixed in develop now, and will be included in the next release.

**Comment by bob-u** [comment]
It works now.  Thank you!
