### ISSUE TITLE
[Windows] Issue with viewing HelpSheet (manpage) on Windows

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#745]
Small description
pressing ctrl-h does not work 
after exiting the program (gq), I see in the terminal:
[Errno 2] No such file or directory: '/dev/tty'
'man' is not recognized as an internal or external command,
operable program or batch file.
'man' is not recognized as an internal or external command,
operable program or batch file.
'man' is not recognized as an internal or external command,
operable program or batch file.
'man' is not recognized as an internal or external command,
operable program or batch file.

'man' is probably invoked every time ctrl+h is pressed.

Expected result
I expect that enter will execute the regex filter
help page should open
Actual result with screenshot
If you get an unexpected error, please include the full stack trace that you get with Ctrl-E.

Steps to reproduce with sample data and a .vd
press crtl+h

Please attach the commandlog (saved with Ctrl-D) to show the steps that led to the issue.
See here for more details.

Additional context
Please include the version of VisiData.
Same as here: #741

**Comment by anjakefala** [comment]
Hi!

`Ctrl+H` makes assumptions about the operating system having a method to view manpages, which Windows does not have. So this is an expected limitation with using VisiData on Windows. We upload the manpage online for those cases: https://www.visidata.org/docs/v2.0/man/.

One thing we possibly could do (@saulpw?), is catch this case, and output to status directing users to the website.

**Comment by bob-u** [comment]
Thanks, that's what I thought.  As a new user I would be happy to be presented with a page showing all of the possible or common key combinations, like top does when you press h.

**Comment by anjakefala** [comment]
You can use `z Ctrl+H` to get a sheet of those. =)

**Comment by bob-u** [comment]
Excellent.  Once the regex search is working I will be able to search though the quite extensive list.  Have you considered allowing typing words (like those describing the key combinations) to make it easier for those with bad memory?

Btw, are the yellow squares a bug or a feature?

![visidata_squares](https://user-images.githubusercontent.com/61708771/96949656-67064680-14b6-11eb-9c34-f36ca222490e.PNG)

**Comment by saulpw** [comment]
The yellow boxes are actually `∅` (null set) symbols, that your terminal font doesn't support.  They mean the underlying value is None (as opposed to an empty string).

**Comment by saulpw** [comment]
Also, I'm not sure what you mean by "typing words (like those describing the key combinations)".  You can use Spacebar to execute a longname, like "open-sheets", if you can't remember that `Shift+S` is the binding for that command.

**Comment by bob-u** [comment]
Ok, thanks, I will stop making suggestions and RTFM.

Regarding the yellow symbols, now I understand - the key combination is not set.  In the manual it says:

"you make your own command in your ~/.visidatarc, you can make that and bind it yourself" - where would that be under Windows?

**Comment by anjakefala** [comment]
@bob-u, you might also appreciate [this cheat sheet](https://jsvine.github.io/visidata-cheat-sheet/en/). =)

`~` should be your home directory.

**Comment by bob-u** [comment]
Thanks.  I created .visidatarc and it is indeed being read.  To test it I added following text:

bindkey('^[p','open-source')

but visidata starts with reload aborted.

**Comment by anjakefala** [comment]
@bob-u That is an occassional bug with the vdmenu, which is what opens if you launch `vd` with no input. =) It is a bug that does not impact anything for the user, beyond the confusing message.

**Comment by bob-u** [comment]
I think it might be something else because ALT+p is not defined as it should.  I since revised the command to what I think is proper syntax now:
BaseSheet.bindkey(ALT+'p', 'mouse-disable')

I still get 'reload aborted' and ALT_p is unassigned.

**Comment by saulpw** [comment]
What do you see in the lower right status when you press `Alt+P` ?

**Comment by bob-u** [comment]
"no command for Alt_P"

![altp](https://user-images.githubusercontent.com/61708771/96955399-793ab180-14c3-11eb-97fe-be0c758483d3.PNG)

![visidarc_contents](https://user-images.githubusercontent.com/61708771/96955415-8192ec80-14c3-11eb-998d-07ddf1533084.PNG)

**Comment by saulpw** [comment]
Awesome, and thank you for the screenshot, that was very helpful. You should use `'ALT_P'` (notice the quotes) instead of `ALT+'p'`.  We'll update the docs and include a note for Windows users, if we can't just autodetect Windows curses and change the ALT variable ourselves.

**Comment by anjakefala** [comment]
@bob-u, we added a fallback `vd.txt` that will get pushed if `man` is not available on an Operating System. =) It will be part of the next release, but you are welcome to install it off the `develop` branch.

You can continue adding Windows stuff to this issue (or another one), I am just gonna close this because the core task is done. We have a checklist item for performing the Windows autodetection.

**Comment by bob-u** [comment]
Sure, thanks.

Speaking of vd.  Then I type vd I get 
'vd' is not recognized as an internal or external command,
operable program or batch file.

typing visidata starts the application.  Happens the same on two different Windows machines.  What should I check to make vd work?

**Comment by anjakefala** [comment]
@bob-u Could you open a fresh issue for that one? That is also a Windows quirk. I would need to investigate what is happening. I think you might need to manually change your `PATH`, it seems like your default `Path` might not cover where Python installed the bin.
