### ISSUE TITLE
[v2.0] there should not be duplicate autocomplete suggestions (of column names)

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#747]
**Small description**
If you have multiple columns of the same name, the input autocomplete feature lists both the names and therefore requires multiple [tab]s to go to the next entry.

**Expected result**
As you cannot distinguish between columns by name, I believe there should only be one entry in the autocomplete suggestions

**Actual result**
You have to tab multiple times to skip duplicate column names

vd 2.0.1

I'm logging this here, and will take a look myself as I've started looking at the Completer feature recently. I hope it maybe a case of just using `set()` instead of a list. But if anyone knows otherwise let me know!

**Comment by anjakefala** [comment]
Thanks @geekscrapy!

Duplicate column names should now not be suggested for `addcol-expr`. 

The nature of this fix might be changed to something better by us later. This variant ensures the tabbing order maintains the existing alphabetic order. `set()`s in Python are not ordered.

**Comment by anjakefala** [comment]
(Time: 2 hours)
