### ISSUE TITLE
[Python expressions] Add magic to Python expressions

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#750]
Add the features of https://github.com/hauntsaninja/pyp to the commands that accept Python expressions.

It would be helpful if we could use all of the Python supplied modules without having to add lines to our .visidatarc

Some of the useful features:
   - auto import
   - some modules like math don't need to be qualified
   - before and after processing
   - looping variables
   - debugging for the magic in case it does unexpected things

**Comment by saulpw** [comment]
Interesting idea, @frosencrantz, I've never used the pyp library before.  We can look into it at some point and see how it fits in.

Kondo'd for now.

**Comment by frosencrantz** [comment]
I've only used pyp a little.  To me the most useful feature would be making it easier to access python modules with little effort as a user.

**Comment by geekscrapy** [comment]
Just noting that pyforest looks to do the same thing so maybe another option:
https://pypi.org/project/pyforest/
