### ISSUE TITLE
[scroll cell]  zh/zl Left hand side of a cell with content hidden doesn't show ellipsis

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#751]
When using scrolling the values of cells in a column it would be useful if there was a visual indicator if some of the data on the left hand side is hidden because of scrolling.

Visidata already does a great job at this on the right-hand side, it would be nice if it could also do this on the left-hand side.

**Comment by saulpw** [comment]
Okay, this is done.  I'm not sure I entirely like it (it's always the same down the entire column), and maybe more could be done to indicate whether it's a positive or negative (right-justified from the end) offset.  But it is useful to not get caught by accident with a weird offset.

**Comment by frosencrantz** [comment]
This seems to work fine.  Thanks, @saulpw!
