### ISSUE TITLE
[usability addcol-sh] When using the addcol-sh command without any parameters

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#752]
I was using vd as a directory viewer, and used `addcol-sh` and gave input 'grep foo'  to grep files.  The cursor was on the filename column, but I didn't add the $filename so VisiData ran multiple grep commands that all were waiting for input.

This was user error, but VisiData could have helped here:

   1 If the input to addcol-sh does not contain a column name, it could ask if that is intended.
   2 Close STDIN for any commands run.

**Comment by saulpw** [comment]
Good points, @frosencrantz.  While testing I could see how annoying the hanging processes are, so passing an empty is super important.  I added a warning; I'm not sure if it's the right thing, but it doesn't feel like asking for confirmation or failing outright is right either.  Let's see how this feels; other people can weigh in here also if they come across this.
