### ISSUE TITLE
[json loader] Json indent doesn't handle integers 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#753]
**Small description**
Using an integer for the json_indent option/flag uses the number input as the character used for indenting rather than the number of spaces.

**Expected result**
Using an indent of the given length.

**Actual result with screenshot**
See below.

**Steps to reproduce with sample data and a .vd**

According to https://docs.python.org/3/library/json.html:

   * If indent is a non-negative integer or string, then JSON array elements and object members will be pretty-printed with that indent level. An indent level of 0, negative, or "" will only insert newlines. None (the default) selects the most compact representation. Using a positive integer indent indents that many spaces per level. If indent is a string (such as "\t"), that string is used to indent each level.

   * Changed in version 3.2: Allow strings for indent in addition to integers.

Run the command twice once with double spaces as indent, and a second time with an indent of "2".  Would expect these to have the same output.

```
$ cat json-indent.sh
  jo a=$(jo b=c d=e) f=g | vd -g  -f json -b -o out.json --json_indent "  "  - ; cat out.json
  jo a=$(jo b=c d=e) f=g | vd -g  -f json -b -o out.json --json_indent 2  - ; cat out.json
$ bash -x json-indent.sh
+ vd -g -f json -b -o out.json --json_indent '  ' -
++ jo b=c d=e
+ jo 'a={"b":"c","d":"e"}' f=g
opening - as json
saving 1 sheets to out.json as json
+ cat out.json
[
  {
    "a": {
      "b": "c",
      "d": "e"
    },
    "f": "g"
  }
]+ vd -g -f json -b -o out.json --json_indent 2 -
++ jo b=c d=e
+ jo 'a={"b":"c","d":"e"}' f=g
opening - as json
saving 1 sheets to out.json as json
+ cat out.json
[
2{
22"a": {
222"b": "c",
222"d": "e"
22},
22"f": "g"
2}
]
```

**Additional context**
Latest version of visidata from develop

**Comment by saulpw** [comment]
This should be fixed now.

**Comment by frosencrantz** [comment]
I've used this several times now.  Works great!  Thanks!
