### ISSUE TITLE
[2.0.1] RecursionException on expr columns

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#756]
_This issue was taken from the vd "irc" chat_

**Small description**
Columns show expr output based on their order.

Replication: Open any sheet that has more than 1 column (I've tried a CSV sheet). Make sure you have the first column selected, now create a new column with the expression the name of any of the other columns with an index > `selectedColumn`. So if I have a sheet of 3 columns, `A`, `B`, `C`, I have A selected, and create a `ColumnExpr` (using `=`) and set the `expr` to `C` (literally). This will create a new column called `C`, but it's value will be a `RecursiveException`. To get around this slide the new column to be after the source column (in this case `C`, the new column should now evaluate and show the correct value. Alternatively, you can rename the new column to something other than `C`, e.g. `C2`.

I presume that it's to do with the order at which the expr looks at the columns. Instead of throwing a `RecursionException` would it be feasible to skip the col which would cause the Recursion and only throw it when all the cols have been tried?

By the looks of it, this issue occurred in pre vd 2.0.1, but due to `ColumnExpr` no longer caching, the behavior now appears inconsistent.

**Expected result**
The new column `C` to take the value of the source column `C` exactly - wherever it is in the sheet column list.
I believe that one should be able to name, and move columns freely without modifying the shown value.

**Comment by saulpw** [comment]
Thanks for reporting, @geekscrapy!  Imlemented as you suggested, by merely skipping the same column.  Now it's requires a bit more complicated of a setup to raise a RecursionException :)
