### ISSUE TITLE
[2.0.1] ColumnExpr expr to return the row object instead of requiring row.row

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#757]
_sparked from vd "irc" chat - I was logging it here for myself (so I can remember the fix!) and to track when it gets fixed_

**Small description**
When attempting to access the row object it is currently required to access it with `row.row`. @saulpw came up with the following small fix (that I've been using for a while and seems fine).

`visidata/sheets.py:137, change to "return self.row"`

**Expected result**
To be able to access the original row object by just using `row.foo()` in `expr="row.foo()"`

**Comment by saulpw** [comment]
Should be committed already in 3dabc0a9c00a812952e925c4cbebb6eb7d5e1525.

**Comment by geekscrapy** [comment]
Nice! I didn't notice that as I'm trying to stick to stable now for my main dev, but I'll keep in mind to check next time 👍
