### ISSUE TITLE
[Windows] vd bin is not executable on windows installation

### ISSUE THREAD

**Issue by bob-u** [saulpw/visidata#760]
**Small description**
typing vd from command prompt results in:
'vd' is not recognized as an internal or external command,
operable program or batch file.

typing visidata starts the application
**Expected result**
I think vd should start visidata
**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData.
I installed visidata with pip3 on windows 10.
vd and visidata are in the same folder so it's not a path issue.
As per the screenshot - vd is not an application

![vd_location](https://user-images.githubusercontent.com/61708771/97587111-65b2ad80-19d1-11eb-9a5d-49b2e0011bab.PNG)

**Comment by anjakefala** [comment]
Hi @bob-u! 

Is that `AppData/Local/Programs/Python/Python39/Scripts` part of your Windows system `Path`? This is unfortunately not something the VisiData installation can configure automatically for you. You would have to adjust that manually.

**Comment by bob-u** [comment]
My path variable includes below, so it does not seem to be the isse.
`C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python39\;`

Screenshot shows that vd is not executable or file associated with any application.  Maybe I'm looking at a wrong file?

vd  is a text file which contains:

```
#!c:\users\rybarmic\appdata\local\programs\python\python39\python.exe

import visidata.main

if __name__ == '__main__':
    visidata.main.vd_cli()
```

**Comment by anjakefala** [comment]
Oh sorry! Early morning, and I read through your issue quickly.

This is probably the problem:

```
       entry_points={'console_scripts': [
           'visidata=visidata.main:vd_cli'
         ],
       },
```

I am not sure if we can fix this on our end, or if it will be a quirk of Windows. We use Python's entry point system, so that people can type both `visidata` and `vd`, where `vd` is the script and an entry point for `visidata`.

I will look into it! Does typing `visidata` work? If it works, you can create an alias `visidata` -> `vd` as a temporary workaround. =)

**Comment by saulpw** [comment]
The `visidata` command uses the more portable entry point system, which has been the easiest way to get a Python program installed on Windows.  But the entry point system adds a quite a bit of startup time, so on Linux and Macos which don't require it, we have a `vd` script which launches very quickly.  So if you want to use `vd` on Windows, you should create an alias for now.

**Comment by bilderbuchi** [comment]
I am on Windows 10, and just installed visidata 2.1 from conda-forge. Curiously, neither the `vd` nor `visidata` commands work correctly in my powershell - the related scripts are _opened_ in a text editor, not _executed_. Your setup.py entrypoints definition looks alright to me, and I have been successfully using that in other projects on Windows, as well. 
What I noticed is that for some reason, the `vd` and `visidata` tools are not generated as a .py file + a shim .exe, as many other scripts, but are just "Files":
![image](https://user-images.githubusercontent.com/327442/102885145-3198bd80-4453-11eb-9340-a541bffb515a.png)

**Comment by saulpw** [comment]
@bilderbuchi Let's make a separate issue instead of appending to this one.  Though this would seem to be an issue with conda-forge more than our Windows setup.  Not sure what we can do about it, or even how to test--none of us use it on Windows.  If you have any ideas on what's going wrong or how to fix it, please put them in the new issue.

**Comment by bilderbuchi** [comment]
Sure: https://github.com/conda-forge/visidata-feedstock/issues/15
