### ISSUE TITLE
`zh` and `zl` use the cursor column's official width, not the column's visible width

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#762]
**Small description**

This issue pertains to this bit of code:

https://github.com/saulpw/visidata/blob/e0b105238f08decd3817b888e82710f531b94fcd/visidata/movement.py#L163-L164

The logic says this: Internally scroll a column's contents right/left by `cursorCol.width - 2`. This works as expected in most situations *except* when you're working with a column whose "true" width is greater than can be visibly displayed (e.g., a 200-char wide column on a 100-char wide screen). In those cases, this code makes the cell scroll more than I think most users would expect.

**Expected result**

I would expect that `zh`/`zl` would base their scroll-distance on the column's *visible width* rather than the column's official width.

**VisiData version**

`2.0.1`

**Additional context**

I *think* this can be solved with a combination of `Sheet._visibleColLayout` and the column index, but I'm not familiar enough with that attribute to say for sure.

**Comment by saulpw** [comment]
Should be fixed now!  Thanks for reporting, @jsvine.

**Comment by jsvine** [comment]
Super, and thanks!
