### ISSUE TITLE
[json] improve performance of loader

### ISSUE THREAD

**Issue by lxcode** [saulpw/visidata#765]
Not really a bug, not really a feature request per se: 

In looking into the JSON loader to see if I could tweak performance at all, I found that the biggest performance gain is disabling the object_pairs_hook, which doesn't seem to cause any difference in functionality for me (and shouldn't be necessary post-python 3.7 AFAICT). For a 200k line Twitter JSONL file, my non-rigorous benchmarks for the reload thread on a pretty beefy iMac Pro were:

Current JSON loader: 52 seconds
Current loader sans object_pairs_hook: 34 seconds
Using orjson: 28 seconds

Is it possible that a) the object_pairs_hook could be removed or that b) orjson could be used instead? It helps a lot when your JSON entries get into the 6 figures.

**Comment by saulpw** [comment]
Hi @lxcode, thanks for the suggestion and for doing the performance analysis on this.  I'm open to removing object_pairs_hook, though we would want to bump the minimum required version of Python for VisiData to 3.7.

**Comment by saulpw** [comment]
Okay, the offending code has been removed.  Enjoy the 50% speedup :) 

Also, we're not going to bump the minimum version of Python for VisiData, as this is a minor degradation of a single saver, and ~10% of users still use Python 3.6.
