### ISSUE TITLE
[dev2.+] long sheet names obstruct ^g output

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#766]
**Small description**
In particular, when joining lots of sheets, the concat sheet name is a join of all the source sheets' names. This is fine, however when you open a joined sheet that has many files and press something like `^g` to see some sheet stats, it does not appear.

**Expected result**
The output from `^g` to appear like normal.

**Potential idea**
Truncate the _visibility_ of long sheets? Maybe something like: `verylongsheetn...ylongsheetname` - removing the center portion until it fits within `x%` of the screen width?

**Comment by saulpw** [comment]
Hi @geekscrapy, you can set `options.disp_lstatus_max` to a reasonable maximum status length, and it will be "middle truncated" as you want.

Also, if you can't see the status messages, you can use `Ctrl+P` to view the history of status messages.  (More keystrokes, I know, but it works in a pinch.)

**Comment by geekscrapy** [comment]
@saulpw thanks, didn't know about that option!
