### ISSUE TITLE
Add `keycol` column in columns-sheet

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#768]
I'd love to be able to see (and manipulate) which columns are keycols from within the columns-sheet. Couldn't currently find an obvious way to do this, feel free to correct me 😀
TIA!

**Comment by saulpw** [comment]
Add a `keycol` attr column.  `col.keycol` is an integer: 1 for the 1st key column, 2 for the 2nd, etc.  0 for not a keycol. We could add this as a another hidden column.

**Comment by geekscrapy** [comment]
Thanks @saulpw , I was originally trying `row.keycol` as an `ColumnExpr`....

I just tried this as a new ColumnAttr ("`addColumnAtCursor(ColumnAttr(input("attr: ", type="attr-col"), width=10))`") and when I modified the value of this column it was always set as a `str` not an `int` breaking the original sheet...

In terms of having it as another column, would it not be best as a shown column? It's one of the main attributes of a column,

**Comment by saulpw** [comment]
You almost have it with your code, just pass `type=int` to the column and then it will set as int.

We can argue over whether or not it's shown by default.  Maybe all columns sheet columns should be.

**Comment by saulpw** [comment]
Added as a hidden column; will be in the next release.
