### ISSUE TITLE
Simplest sequence of keys to show the sum of the current column

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#771]
This seems so basic yet it remains unclear after reading a bunch of documentation.  Sum is used so frequently I think it should be available separate from the aggregate-col command.

So I select a column, use # to make it an int, press + to aggregate, select sum with 's' and then hit RETURN and nothing happens.  I didn't select a key column but even if I do that, I can't just get a display of the sum of the column.

**Comment by saulpw** [comment]
`+` adds an aggregator for later grouping.  Try using `z+` which shows the result of the aggregator on the status line immediately.

**Comment by rswgnu** [comment]
The problem was that in the aggregation popup, I would use 's' to select the 'sum' operation that I wanted and then would hit return but because I was now on the next line, vd would ignore my selection and use that line, showing me 'distinct' number of values.

Seems to be consistent in UI, if you don't use 's' or 't' to select an aggregation operation, then default to the one on the current line but if you do select one or more, use those.

**Comment by rswgnu** [comment]
Or how about numbering the aggregator operations and then letting someone just press '+' and '<number>' to apply a  single operator to the selected column.  Make the more elaborate key-based aggregation be the longer key sequence, not the simpler one.

And how do you aggregate from just the selected rows on the current column rather than the whole column from the sheet?

**Comment by anjakefala** [comment]
> And how do you aggregate from just the selected rows on the current column rather than the whole column from the sheet?

`z+` will aggregate for selected rows, falling back to all rows when none are selected. =)

**Comment by rswgnu** [comment]
Thank you.

This affirms my earlier recommendation that the aggregators applied should
act the same way and reflect any selection made when the aggregation
operation is run.

**Comment by anjakefala** [comment]
Hi @rswgnu!

1.

> The problem was that in the aggregation popup, I would use 's' to select the 'sum' operation that I wanted and then would hit return but because I was now on the next line, vd would ignore my selection and use that line, showing me 'distinct' number of values.

In the prototype it behaved this way, but this bit long-time users of VisiData.

One user identified why:
> The only funky bit to me is how the fancy chooser doesn't behave quite like other sheets when it comes to multiple selection. E.g., selecting two rows, navigating down to a third, and then pressing enter ... puts the selected rows in the input. On other sheets, it's the row on which you hit Enter that gets acted upon, right?

We want to maintain consistent behaviour as much as possible, so I think this is the best approach. 

If you like, you can customize your version of VisiData:

```
 ChoiceSheet.addCommand(ENTER, 'choose-rows', 'makeChoice(selectedRows or [cursorRow])') 
```

2.

> This affirms my earlier recommendation that the aggregators applied should
act the same way and reflect any selection made when the aggregation
operation is run.

If you want the classic column aggregator (`+`) to be applied only to a subset of selectedRows: after adding an aggregator with `+`, and selecting your rows of interest, you can use `"` to create a new sheet which only contains the selected rows . The aggregator gets carried over to that new filtered sheet. When you perform any of the grouping commands (Frequency Table, Pivot) on the filtered sheet, the respective aggregated column will also appear. 

I think that answers the questions in this thread! I am going to close it. =)

**Comment by rswgnu** [comment]
> Hi @rswgnu!
> 
> 
> > The problem was that in the aggregation popup, I would use 's' to select the 'sum' operation that I wanted and then would hit return but because I was now on the next line, vd would ignore my selection and use that line, showing me 'distinct' number of values.
> 
> In the prototype it behaved this way, but this bit long-time users of VisiData.
> 
> One user identified why:
> 
> > The only funky bit to me is how the fancy chooser doesn't behave quite like other sheets when it comes to multiple selection. E.g., selecting two rows, navigating down to a third, and then pressing enter ... puts the selected rows in the input. On other sheets, it's the row on which you hit Enter that gets acted upon, right?
> 
> We want to maintain consistent behaviour as much as possible, so I think this is the best approach.

The only reason I selected an operation was because after using '+' and pressing return on 'sum' nothing happened.  When does the sum get computed and where is it displayed when I use an aggregator this way?  Why do I have to use 'z+' to get the more immediate action that most people would expect?  I just want to press you guys to think a bit more about new users and how to make certain things more approachable and to see where things are not clear.

> 
> If you like, you can customize your version of VisiData:
> 
> ```
>  ChoiceSheet.addCommand(ENTER, 'choose-rows', 'makeChoice(selectedRows or [cursorRow])') 
> ```

Great, I will try that.

> 
> 
> > This affirms my earlier recommendation that the aggregators applied should
> > act the same way and reflect any selection made when the aggregation
> > operation is run.
> 
> If you want the classic column aggregator (`+`) to be applied only to a subset of selectedRows: after adding an aggregator with `+`, and selecting your rows of interest, you can use `"` to create a new sheet which only contains the selected rows . The aggregator gets carried over to that new filtered sheet. When you perform any of the grouping commands (Frequency Table, Pivot) on the filtered sheet, the respective aggregated column will also appear.

This is nice too.  Thanks for the pointers.  I'm starting to get the zen of visidata the more I experiment.

> 
> I think that answers the questions in this thread! I am going to close it. =)
