### ISSUE TITLE
Issues in v2.-4

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#775]
I just install v2.-4 and am testing it out a bit.  Here are issues so far:

1. It doesn't read my ~/.visidatarc file.  The stable version read this fine.

2. When using z^H, many of the newer key bindings listed there do not work, e.g. jumping to sheets with ALT -<digit> or ESC-<digit>.

3. Splitting into 2 windows works fine.  However, I think you should change the close window commands.  Rather than just closing the bottom window, you should have 'close-active-window' and 'close-other-window'  command since you typically want to close a window relative to the data you are displaying, not one in a fixed position. 

This is on MacOS Mojave 10.14.6.

**Comment by saulpw** [comment]
Hi @rswgnu, v2.-4 is an older pre-release which is out-of-date now that we've released v2.0.  Please use v2.0.1 (stable) and refile if these issues still exist there.

**Comment by rswgnu** [comment]
So is the develop branch the latest unreleased branch for testing new features before release?

**Comment by saulpw** [comment]
> So is the develop branch the latest unreleased branch for testing new features before release?

Yes.
