### ISSUE TITLE
[help] Add extended cheatsheet

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#776]
I have taken the existing cheetsheet for VisiData, edited, reorganized, extended and changed it into text format.  See it here:

https://github.com/rswgnu/rsw-visidata

I think it is much more approachable and useful for new and existing users than what is on ^H right now (the man page).  Please consider integrating it into VisiData whether on ^H or elsewhere for easy access, maybe with a few tweaks you feel are important.  One area that is not covered right now is visualization beyond frequency tables.

--

If you are a subscriber at the 'Workflow Optimist' level on [Patreon](https://www.patreon.com/saulpw/), you can designate this feature as one you would like to remain open, by adding an "[optimist]" tag in the summary line.

**Comment by saulpw** [comment]
Thanks for putting this together, @rswgnu.  We're considering where we might want to include this.

**Comment by saulpw** [comment]
We decided to include a menu system which I think will work better than an internal cheat sheet.
