### ISSUE TITLE
[config] `vd --config=''` does not ignore visidatarc

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#777]
Sometimes for testing you want to ignore your personal init file.  I don't see how to do that from the man page.  Any suggestions?

**Comment by saulpw** [comment]
Hi @rswgnu, try `vd --config='nofile'` (or some other non-existent filename).  `vd --config=''` *should* work to disable the config but apparently does not currently, and we'll fix that.

**Comment by anjakefala** [comment]
> vd --config='' should work to disable the config but apparently does not currently, and we'll fix that.

Fixed on develop! Will be part of the next release.
