### ISSUE TITLE
[macros] add ability to inject keystrokes

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#779]
Often I might want to string together a series of key presses and bind that to a key (a keyboard macro) without having to figure out the command names and make a function out of them to bind.

Add a syntax that allows the bindkey command to take a second argument of not just long command names but of a sequence of keys as well (where the keys are given exactly as in the first argument of a key binding but strung together in a string.

Say the syntax for a key string was that it began with 'keys:', so:
(bindkey '^A', 'keys:sss"IALT-1')
pressing Control-A would executed the sequence of keys: s s s " I ALT-1.

**Comment by saulpw** [comment]
This one seems tricky to implement for a couple of reasons, and I think it could be better accomplished by injecting the keystrokes from the terminal directly, rather than from within VisiData.  If someone can put together an elegant PR I'm not opposed to it though.

Kondo'ed for now.

**Comment by anjakefala** [comment]
Maybe you could explore this feature? https://github.com/saulpw/visidata/issues/755

And see if it helps you get partway to what you desire!

**Comment by rswgnu** [comment]
I will have to try the dev branch to check this out.  Thanks.
