### ISSUE TITLE
"TypeError: 'generator' object is not subscriptable" when loading Excel sheet

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#78]
## Setup

- Python 3.6.0
- `xlrd==1.0.0`
- `visidata==0.91`
- [this test Excel file](https://github.com/saulpw/visidata/files/1136950/test.xlsx)

## Problem

When I try to open `Sheet1` of the test file, I get the following error:

```
test~Sheet1| TypeError: 'generator' object is not subscriptable | TypeError: 'generator' object is not subscriptable | TypeError: 'generator' object is not subscriptable
```

Opens fine if I use Python 2.7

**Comment by saulpw** [comment]
Fixed in develop with 205872352cbfb6ff6ff4ab0dfc156946105c3983.  Will merge into stable tonight or tomorrow.

**Comment by jsvine** [comment]
Super, and thanks!

**Comment by saulpw** [comment]
Fixed in stable and pypi.
