### ISSUE TITLE
[commands] Numeric prefix of repeat count for commands

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#781]
You likely know about Emacs prefix arguments which allow you to send numeric, typically repeat count, arguments to interactive commands, such as: {ESC 20 C-f} which would move forward 20 characters.

In my own HyControl window manager program (part of the GNU Hyperbole Emacs package), I have extended this concept and allowed you to just press the numeric keys to build up a value or . to clear any prefix value (without the need for the ESC prefix).  I would suggest something similar for VisiData and then allow many commands to take numeric arguments which they would use in the most intuitive way, e.g. select next or prior X rows, multiple the selected cells in a column by a value, jump to sheet X, etc.  Maybe the {.} key binding in VisiData could be changed to accomodate this behavior.

Many people have found this a powerful concept that aids interactive productity and also is quite useful when replaying commands or a series of key sequences.

**Comment by saulpw** [comment]
Thanks for the suggestion, @rswgnu.  vi has this kind of functionality too.  It would be useful but I expect it would also be quite a bit of work to get right.

Kondo'ed for now.
