### ISSUE TITLE
 [Dirsheet Frozen Col] Empty frozen column in duplicated DirSheet

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#786]
**Small description**
Frozen columns in a duplicated DirSheet are empty.

**Expected result**
Frozen columns keep their values.

**Actual result with screenshot**
https://asciinema.org/a/bRYBx9fw7Q5FXP52COQ1Wuqpb

**Steps to reproduce with sample data and a .vd**
Open a dirsheet, freeze the column, and duplicate the sheet.

```
sheet	col	row	longname	input	keystrokes	comment
			open-file	.	o	
	filename		freeze-col		'	add a frozen copy of current column with all cells evaluated
		キ.,.emptyfrozencol-in-dup-dirsheet.md.swp	select-row		s	select current row
			dup-selected		"	open duplicate sheet with only selected rows
```

**Additional context**
Please include the version of VisiData.  Using latest develop version.

**Comment by saulpw** [comment]
This is any sheet with deferred modifications.  Note that the frozen column is highlighted as "modified" even though it is not related to the actual source data.  Making a frozen column not deferred will fix this issue.

**Comment by anjakefala** [comment]
Thanks @frosencrantz! =) This should now be fixed on `develop`.

**Comment by frosencrantz** [comment]
Works great!
