### ISSUE TITLE
[macros] Recording a macros fails

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#787]
**Small description**
Recording a macro fails.

**Expected result**
Macro is saved.

**Actual result with screenshot**
https://asciinema.org/a/7T0YgyrSQFhHyWfdok17oi6Qj

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 136, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "macro-record", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/visidata/macros.py", line 52, in startMacro
    vd.cmdlog.saveMacro(vd.macroMode.rows, ks)
  File "/usr/lib/python3.9/site-packages/visidata/macros.py", line 37, in saveMacro
    append_tsv_row(vd.macrosheet, (ks, macropath))
  File "/usr/lib/python3.9/site-packages/visidata/loaders/tsv.py", line 81, in append_tsv_row
    if not vs.source.exists():
AttributeError: 'NoneType' object has no attribute 'exists'
```

**Steps to reproduce with sample data and a .vd**
Record a macro, provide a filename when asked, and vd throws an exception.

**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by anjakefala** [comment]
This should now be fixed on `develop`!

**Comment by frosencrantz** [comment]
Hi @anjakefala! I was trying to confirm the fix.  But I'm not sure how to run a macro.  It looks like the macro name becomes the name of a new command, but when I try to run it, I get a KeyError: ' '  It is getting late, I don't have time now to look further.  Will have to take a look when I have time.

**Comment by frosencrantz** [comment]
Hi @anjakefala I think I understand my issue.  

When it is time to save the macro, I wasn't giving a keystroke, but giving it longer name, `delete-ten-rows` rather than `zx`.  If I then try to do a long-command: `delete-ten-rows`, I get the KeyError.

https://asciinema.org/a/mUuTYelsvQ6gduB4qMKQpaWmM

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 136, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "cmdlog", line 1, in <module>
KeyError: ' '
```

**Comment by anjakefala** [comment]
@saulpw, should we allow longnames, as well as keystrokes? Hmmmmm.

**Comment by saulpw** [comment]
Yes, allowing longnames is a good idea.  I think it should work already, though, so this may be just a small bug (hopefully it doesn't unravel into something bigger).

**Comment by anjakefala** [comment]
This should now work on develop, @frosencrantz!

**Comment by frosencrantz** [comment]
Awesome! I tried it out, and it works nicely.  Thanks @anjakefala and @saulpw !
