### ISSUE TITLE
Debian Package update for 2.0.1

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#788]
I'm not familiar with how to update a Debian repository.  A friend told me that she wanted to use an official package, but she only sees the 1.5.2 version here: https://tracker.debian.org/pkg/visidata

Is there something more that needs to happen to let Debian know there is an update?  What are the next steps?

**Comment by anjakefala** [comment]
It is a really time-consuming process to update a package in Debian (I think it usually takes me 2 weeks, with not working on anything else for VisiData), and because I am not a Certified Debian Contributor, I need to work with somebody who is in order to move VisiData through the process (which means that we are taking 2 weeks of their time reviewing my work). So we only want to do the update when we are deeply sure about what we are uploading. It is not straightforward to send forward a patch.

This is why we also host our own deban repository, which your friend is more than welcome to use =) 

I keep that one up-to-date: https://github.com/saulpw/deb-vd

**Comment by frosencrantz** [comment]
It sounds unpleasant.  Is it something you want to continue to own? 

Many other open source packages I use seem to have maintainers that own multiple packages.  I’m not familiar with the process, but I wonder if you would be open to have someone else do it.  Maybe one of those maintainers would be willing to also own VisiData’s Debian packaging.  Especially given how wonderful VisiData is.

My friend needs an official Debian repository.

Earlier you mentioned something about the 2.1 release.  When do you think that would be available?  Seems like it could be soon.   Are you still considering releasing it via an official Debian repository after the 2.1 release?

@anjakefala Thank you very much for your past efforts on this.  It does make a difference.

**Comment by anjakefala** [comment]
> Is it something you want to continue to own?

This is a reasonable thing to suggest! I am at the moment attached to being the owner for Debian. This might change in the future. 

When Debian files a bug for VisiData, it is currently my responsibility to fix and deploy it through their pipeline. So, I want to be careful with what we submit. It is potentially a negative experience, and a waste of a lot of people's time, if we rush something through that we are not confident in.

> My friend needs an official Debian repository.

I will send out a release announcement when it is shipped. =)

> Are you still considering releasing it via an official Debian repository after the 2.1 release?

Not sure when it will be updated; if it will be for the 2.1 release. The 2.1 release is going to be soon. The Debian package will be updated when we are confident in the stability of 2.x VisiData, and that there are no major bugs.

**Comment by frosencrantz** [comment]
That sounds like a good plan.  Hopefully we can get a stable release with 2.1.  

Again thank you for your efforts for doing these releases.  I do hope someday there is someone in the community who 
would be willing to take over the duty of the Debian releases.

**Comment by anjakefala** [comment]
@frosencrantz VisiData v2.2 has been uploaded to Debian testing! It will show up in one of the next Debian releases. =)
