### ISSUE TITLE
[column type] Column type that references a path (file or URL)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#789]
Add a new type that allows a column's value to be considered a path (file or URL).  Keyboard commands
would need to be changed to open the path:
   - In your favorite editor
   - as a new data sheet
   - import the data into a new column, with the cells containing the data read from the path.

**Comment by anjakefala** [comment]
Fun fact, I made a **Sheet** type for a txt file of paths!

https://github.com/saulpw/visidata/blob/stable/visidata/shell.py#L192

**Comment by saulpw** [comment]
Interesting idea, I'm not sure if a column type is the best way to go about this.  I have some local custom commands to open URLs in cells that could maybe be expanded someday.

Kondo'ed for now.

**Comment by frosencrantz** [comment]
Many times I have data that point at URLs or local files.  And it would be useful to open these as easily as I do in the file sheet.  I think your local custom commands would be useful.

@anjakefala, thanks for that fun fact.   I really want you to know I've been a happy user of the **fdir** file type for a while now.  Thanks for adding that!
   
```
find .  -my-find-query | vd -f fdir
locate '*.csv' '*.json  | vd -f dir
```

**Comment by dufferzafar** [comment]
I have a CSV file that looks like this:

```
 url                                            | date     | venue            | region | product ║
 http://secmaster/20201223.CHINA_EQUITY.csv     | 20201223 | CHINA_EQUITY     | asia   | equity  ║ 
 http://secmaster/20201223.CHINA_EQUITY.old.csv | 20201223 | CHINA_EQUITY.old | asia   | equity  ║
 http://secmaster/20201223.HK.csv               | 20201223 | HK               | asia   | equity  ║ 
 http://secmaster/20201223.HK.old.csv           | 20201223 | HK.old           | asia   | equity  ║
 http://secmaster/20201223.JP.csv               | 20201223 | JP               | asia   | equity  ║
 ```
 
 I would want that when I press `enter` on a row, that particular CSV should then be loaded from the URL column.
 
 @saulpw Is there any way to achieve this?

**Comment by saulpw** [comment]
@dufferzafar  Add this to your .visidatarc, and then use `z Enter` to open the cell as a new sheet.  (This is untested but is straightforward and should work.)

```
TableSheet.addCommand('z'+ENTER, 'open-cell', 'vd.push(openSource(cursorDisplay))', 'open filename or url in current cell')
```

You can bind this to `Enter` by itself or another keystroke, but you have to be on the column itself for it to work.
