### ISSUE TITLE
[hooks] Add hooks that allow users to customize behavior when events happen

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#790]
Provide a way to add user hooks that allow users to customize VisiData behavior when well defined events happen.

For example, it would be useful if there was a hook when a file finished loading, so users can customize a table automatically.
Or a hook for when adding a new column or row.  Or per command hooks. Or when opening a file.

Other tools have hooks, such as Emacs, Vim, and Tmux.

One thing I would like to accomplish is automatically set column types from CSV files.
Similar usage in https://github.com/saulpw/visidata/issues/715

For opening files, it would be useful if there was a mechanism via hooks to take a user supplied logical filename and convert that to an actual filename or URL.  For example when adding base Github or Wikipedia URLs and convert them to a canonical version of the URL that Visidata can read.

I think hooks provide another way that plugins could provide more customization.

**Comment by saulpw** [comment]
This feature request is too large and generic, and focuses on the implementation mechanism rather than a specific end goal.  You've mentioned some examples, but there are too many to address individually and nothing concrete enough to satisfy.
