### ISSUE TITLE
[wishlist] Give keystrokes in a string on cmdline to batch filter data

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#792]
I would love to be able to quickly use VisiData in batch mode or a pipeline to filter data in one of two ways via a cmdline option:

1. Select rows where a string or regex matches anywhere within a row (g|)
2. Select rows where a string or regex matches only the column specified by name or position number (|).

This would be very powerful and useful, allowing people to make cmd aliases that easily dynamically filtered data to just what they wanted for display or further use.   I imagine there would be a --macro option with the macro specified inline.

This would be my number one request right now.

**Comment by saulpw** [comment]
This is already possible in 2.0.  Pipe or redirect vd stdout (or pass `-o filename`) and use `Ctrl+Q` to exit.  The top sheet will be saved to stdout or the given filename.  (`Ctrl+Q` is required because `gq` is a clean exit which pops all sheets).

**Comment by rswgnu** [comment]
Do you mean just use echo and pipe stdin to vd to give it the keystrokes desired?  Would prefer a vd command-line option since echo might not be available within every shell.

-- Bob

**Comment by saulpw** [comment]
Sorry, I misunderstood what you were asking for.  The stdout redirect and `Ctrl+Q` are for using vd as an interactive filter as part of a pipeline.  Data can be piped into stdin but keystrokes can't.

For the actual request, to be able to pass in commands, can you make a .vd or .vdj file with the commands, and use `vd -b -p`?  You can make it a template with `{input}` (in the input column) and then pass `input=searchterm` and it will be substituted in.

**Comment by rswgnu** [comment]
I will try that.  Are there any similar examples to reference?

**Comment by saulpw** [comment]
1. Open representative data in vd.
2. Execute the command(s) you want.
3. Press `g Shift+D` to see the cmdlog with all commands executed.
4. Delete the `open-file` row with `d`.
5. Clear the specific sheet names in the rest of the commands with `gs` and then `gzd` in the `sheet` column.
6. Use `e` to edit the `input` field(s) to `{input}` (use a unique identifier for each distinct input).
7. Save with `Ctrl+S` to `foo.vd`.
8. Replay with `vd -p foo.vd newdata.csv input=searchterm`.

This should work, but won't currently due to issue #572.  There's probably a workaround (like using `1` for the sheet, instead of blanking it, but then that leaves the replay script on top of the stack which is annoying), but I'm hoping to fix this for 2.1.

**Comment by rswgnu** [comment]
All of below works if I add the -b option except that the final sheet is
not output (as you predicted).  Is there any command that will just dump
the final sheet to stdout?  Given that this works if you don't replay a
script and just pipe the output to cat, there must be a simple way to get
the same behavior after a playback script.  -- Bob

**Comment by saulpw** [comment]
Yes, either redirect stdout, or use `-o -`.

**Comment by rswgnu** [comment]
I have redirected stdout into cat as I mentioned.  It does not output the last sheet if I play back my script, only when no playback.

-- Bob

**Comment by saulpw** [comment]
I don't know what's wrong then, because it works for me.

**Comment by rswgnu** [comment]
This is what I get with visidata 2.0.1:

vd -b -p test.vd 5.csv input='a' | cat

Who ever saw one that size?

opening 5.csv as csv

opening test.vd as vd

select rows matching regex in any visible column

"a"

search wrapped

6 matches for /a/

selected 6 rows

open duplicate sheet with only selected rows

replay complete

saving 1 sheets to - as tsv

sheet col row longname input keystrokes comment

- save finished

**Comment by rswgnu** [comment]
There are a number of issues that visidata is not handling automatically:

1. The playback file is loaded as sheet 1 and then immediately starts
playing before the data sheet is loaded.  It should always wait at least
until some minimum number of rows is loaded from the data sheet.

2. The data file should be sheet 1 since that is what most people would
expect and it will greatly simplify macros/scripting.  Make the playback
script load after initial async loading of any data sheets.

3. After my script plays, even though it shows that 6 rows were selected
from the data sheet (I believe), an unexpected header-only sheet appears
and that is what is output to stdout, rather than the rows selected.

Again, if the keystrokes could be given on the command-line instead, there
wouldn't be any confusion with the replay script being loaded as a sheet,
you wouldn't have to specify an input variable separately.

**Comment by rswgnu** [comment]
I got it working by specifying 5 as the sheet name to apply things to since
the input file is 5.csv (probably should use an alpha name).  For general
use, we need to know that the first sheets will be the data files given on
the command-line, not a playback sheet or anything else generated by
VisiData.

**Comment by rswgnu** [comment]
Now what if I wanted to match the regex only within a column name that I
specified on the command-line?  Would prefer column_name=value but could
live with: --col column_name input=value.
