### ISSUE TITLE
[question] What happened to export as an Org or Markdown table

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#793]
What happened to this feature from V1.1:

     New supported formats:

     markdown (md) is now supported for saving (but not loading, yet) to an org-mode compatible table format.

It sounds good.

**Comment by anjakefala** [comment]
Export as markdown still exists! We were corrected by another user that it was not "org mode markdown". I believe this correction happened off of GitHub.

Note, that you can also come to #visidata on freenode to ask small questions. =)
