### ISSUE TITLE
[bug] -p option should not affect numbering of data sheets loaded

### ISSUE THREAD

**Issue by rswgnu** [saulpw/visidata#795]
**Small description**

vd data.csv
   loads sheet named 'data' as sheet `#1`
vd -p test.vd data.csv
   loads test.vd as sheet `#1` - prevents referencing sheet `#1` in the playback script to refer to data file (without having to utilize the filename itself to get to the sheet)                   
   loads sheet named 'data' as sheet `#2` 
   
**Expected result**

  Data files loaded into the same ordered sheets whether -p is given or not for consistency of reference.
  Load 

**Additional context**
V2.0.1

**Comment by saulpw** [comment]
Okay, now the .vd is not pushed onto the sheet stack for replay.  This should fix the underlying issue.

**Comment by rswgnu** [comment]
Great, thanks.
