### ISSUE TITLE
Return selected rows and current row, col...

### ISSUE THREAD

**Issue by s-celles** [saulpw/visidata#799]
Hello,

I would like to use visidata as a "component" for a curses application (currently I don't know if I will use curses, pyCDK, urwid, npyscreen...) but anyway I will probably have a visidata screen to be able to show a lot of data, filter and or sort them.

For such a purpose, I need `visidata.view_pandas` to return selected rows and current row, col

This is probably a bit out of the scope of visidata (which seems to be essentially about viewing data) but interacting with them is important and returning the "context" will be great to use visidata as a component for a more complex application.

Any opinion about this?

Kind regards

**Comment by saulpw** [comment]
Hi @scls19fr, what do you mean to "return" those things?  Like, after someone presses `gq` you want to know what rows were selected in the data frame and where the cursor was?  Or, while they are interacting with the sheet, you would like to get the selected rows and cursor information externally (or from a new command in VisiData issued by the user)?

**Comment by s-celles** [comment]
After quitting I would like to know what rows where selected and where the cursor was.

**Comment by saulpw** [comment]
Something like this code should work (haven't tried it, just from memory):

```
vs = PandasSheet('sheetname', source=df)
visidata.run(vs)
rownum, colnum = vs.cursorRowIndex, vs.cursorColIndex
selected_rows = vs._selectedMask
```

You can look in the [API docs](visidata.org/docs/api) for some of this, but the [pandas loader source code](https://github.com/saulpw/visidata/blob/stable/visidata/loaders/_pandas.py) will be more useful for you, as pandas support is necessarily implemented differently (hence `_selectedMask`, which is a pandas.Series of bools).

I'd love to see what you come up with!  Please keep us posted as you develop.
