### ISSUE TITLE
view_pandas(df.transpose()) raises AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by s-celles** [saulpw/visidata#800]
Hello,

The following code:

```python
import visidata
import pandas as pd
df = pd.read_csv("https://jsvine.github.io/intro-to-visidata/_downloads/83e70cf67e909f3ac177575439e5f3c5/faa-wildlife-strikes.csv")
visidata.view_pandas(df)
df = df.transpose()
visidata.view_pandas(df)
```

raises

```
AttributeError: 'int' object has no attribute 'startswith'
```

A temporary fix is to do

```
df.columns = df.columns.map(str)
```

but using such a transposed version of data is very, very slow.

Any idea?

Kind regards

Related #129, #631 (about transpose on visidata side)

**Comment by ajkerrigan** [comment]
I'm not sure the best way to fix this properly. VisiData seems to assume that column names will be strings, so violating that assumption seems likely to cause odd errors both in the core functionality and any plugins that implicitly inherit that assumption.

Stringifying the colum names isn't an ideal fix, but it's at least more palatable than dying with an `AttributeError`.

**Comment by saulpw** [comment]
Yeah, I think this is reasonable.  The other option I can think of, is to leave the column names blank if transposing a sheet in which the first/key column is numeric.  But I think that's worse in a couple ways, so let's stick with the column-name-stringification approach.

**Comment by s-celles** [comment]
Thanks for this fix.
But watching transposed version of df is still very slow!

**Comment by saulpw** [comment]
Sorry, @scls19fr, we don't know a lot about pandas. Are you interested in trying to make it faster? If you know how to transpose quickly with pandas, it shouldn't be too difficult to make a custom transpose command for PandasSheet that uses the optimized version.  I'm sure it would make a lot of pandas users very happy!

**Comment by s-celles** [comment]
I don't think the problem is on pandas side but visidata code seems to be optimized for data with small number of columns but big number of rows.
When transposing with Pandas you can notice that it's a very quick operation but the problem seems to be when trying to display such a wide data using visidata (ie low number of rows but high number of columns)
My guess is that your are ingesting the whole data into visidata instead of just having a "view" on data (but I may be wrong as I didn't looked intensively to visidata code).
Some years ago @wavexx did a great work on https://github.com/TabViewer/gtabview to provide such a mechanism (unfortunately it wasn't merged into [tabview](https://github.com/TabViewer/tabview)

**Comment by saulpw** [comment]
Yes, you're right, VisiData ingests all the data.  It would be really awesome if VisiData had a direct view into Pandas DataFrames.  I don't know enough about Pandas to do this, but if you are a serious Pandas user, this would be a great addition!
