### ISSUE TITLE
Filtering Pandas DataFrame doesn't work in IPython

### ISSUE THREAD

**Issue by s-celles** [saulpw/visidata#801]
Hello,

I was trying to follow https://jsvine.github.io/intro-to-visidata/basics/sorting-and-filtering/#how-to-filter-rows
but in an IPython console... (not using `vd` cli)
and noticed that it doesn't work.

For example : Filtering selected rows with "

```
$ ipython
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import visidata

In [2]: import pandas as pd

In [3]: df = pd.read_csv("https://jsvine.github.io/intro-to-visidata/_downloads/83e70cf67e909f3ac177575439e5f3c5/faa-wildlife-strikes.csv")

In [4]: visidata.view_pandas(df)
```

Press 3 times on "t" key (to select first 3 rows) and " key (to filter using selected rows)

An empty sheet is shown (with only columns headers) instead of a sheet with selected rows.

Kind regards

**Comment by s-celles** [comment]
Similar issue occurs when trying to select rows from a frequency table.

```
visidata.view_pandas(df)
```

Press 3 times on left arrow to go to STATE column

Press Shift + F to open frequency table

Press down arrow to go to CA row and ENTER

An empty sheet is also shown (with only columns headers) instead of a sheet with rows whom STATE is CA.

**Comment by ajkerrigan** [comment]
Thanks for the report @scls19fr, these are good issues to track down. There is some consistent tension between pandas and VisiData, which @saulpw recaps nicely in [this blog post](https://www.visidata.org/blog/2020/row-major/). That can lead to some whack-a-mole finding and fixing operations just for pandas. I'd like to try to address that at a higher level, but that's a big lift and I don't know pandas well enough!

Based on your reports I'm guessing you know pandas better than VisiData's maintainers or I do. If you'd like to try to team up to improve the pandas loader, it could be pretty useful!
