### ISSUE TITLE
SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.

### ISSUE THREAD

**Issue by s-celles** [saulpw/visidata#802]
Hello,

This line

https://github.com/saulpw/visidata/blob/6691869060c8c3d0fcb4fb3d528f87af2dd9ad07/visidata/loaders/pandas_freqtbl.py#L108

raises

`SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.`

(I was using `visidata.view_pandas` method in an IPython console)

This kind of warning can generally be fixed using `df.loc[...]`
See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy for more informations

Steps to reproduce

```
$ ipython
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd

In [2]: import visidata

In [3]: df = pd.read_csv("https://jsvine.github.io/intro-to-visidata/_downloads/83e70cf67e909f3ac177575439e5f3c5/faa-wildlife-strikes.csv")

In [4]: visidata.view_pandas(df[["STATE"]])
```

Press Shift + F

![Capture d’écran 2020-11-21 à 22 54 27](https://user-images.githubusercontent.com/109167/99888551-081b2500-2c4e-11eb-9b80-23c0f4827a23.png)

Kind regards

**Comment by ajkerrigan** [comment]
Hi there @scls19fr - you can give the changes in #816 a shot when you get a chance, they should resolve this issue.

**Comment by s-celles** [comment]
LGTM
Thanks @ajkerrigan
