### ISSUE TITLE
visidata doesn't read Frictionless DataPackage which doesn't have a 'format' key

### ISSUE THREAD

**Issue by s-celles** [saulpw/visidata#803]
Hello,

I noticed that

```
vd -f frictionless https://raw.githubusercontent.com/datasets/country-codes/master/datapackage.json
```

works fine but

```
vd -f frictionless https://raw.githubusercontent.com/datasets/core-datasets/master/datapackage.json
```

raises `KeyError: 'format'` and shows an empty sheet (columns headers only) probably because of

https://github.com/saulpw/visidata/blob/6691869060c8c3d0fcb4fb3d528f87af2dd9ad07/visidata/loaders/frictionless.py#L11

I'm not a specialist of DataPackage and so I can't say I this key `'format'` is required or optional.

So pinging @aborruso @anjakefala @rufuspollock @pwalsh

Related issue #237

Kind regards

**Comment by saulpw** [comment]
Hi @scls19fr, thanks for filing this bug.  Does @aborruso or someone know what format should be chosen if it is not given?

**Comment by saulpw** [comment]
The spec says (from https://specs.frictionlessdata.io/data-resource/#data-location):

> a consumer of resource object MAY assume if no format or mediatype property is provided that the data is JSON and attempt to process it as such.

I've added this functionality to the frictionless loader, but it seems like the dataset itself is incorrectly specified in the datapackage.json, probably assuming that the .csv extension is sufficient.  So even with the fix this dataset won't load properly.  Please submit a PR to the dataset in its repo to add the right format to the datapackage.json.
