### ISSUE TITLE
[2.0.1] Color Progress string

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#804]
I think it'd be a neat tweak to be able to see at a glance (or even just in peripheral vision) if something is actively running.
The tweak would involve coloring the text `25% grouping` (for freq table) or `processing` (general) etc.

**Comment by saulpw** [comment]
It was `color_status`, now it's `color_working` (default green).

**Comment by geekscrapy** [comment]
Hey @saulpw , I just attempted to do a `freeze-col` and it doesn't look like `color_working` is working (🫢). I see the following (`vd --config=/dev/null`)

![image](https://user-images.githubusercontent.com/11225502/189051623-5f5d981a-e4b2-412c-8af9-46d11ed5be33.png)

**Comment by saulpw** [comment]
Thanks for the note, @geekscrapy!  Should be fixed now (again).
