### ISSUE TITLE
Mouse scroll up fails: no command for "2097152"

### ISSUE THREAD

**Issue by onlyjsmith** [saulpw/visidata#805]
Visidata is totally awesome.

**Small description**
Scroll down with mouse if fine, prints 'BUTTON4_PRESSED' in status bar. Scrolling up with mouse fails, prints 'no command for "2097152"' instead.

**Expected result**
Expect that scrolling up or down scrolls a long file. Works fine for scrolling down, but not for scrolling back up.

**Actual result with screenshot**
![Screenshot from 2020-11-23 19-49-26](https://user-images.githubusercontent.com/148280/100002539-03c54800-2dc5-11eb-9b1d-de938f987295.png)
No error.

**Steps to reproduce with sample data and a .vd**
No steps needed - just load a file (like from [here](https://www.appsloveworld.com/sample-csv-file/)) and try to scroll.

**Additional context**
saul.pw/VisiData v1.5.2

PS Sorry I originally posted this issue with no content - hopefully it's now updated!

**Comment by anjakefala** [comment]
What is your operating system, shell, and terminal @onlyjsmith?

**Comment by onlyjsmith** [comment]
Confirmed same behaviour on:
- pop_os 20.10, zsh, Tilda shell
- mx 19.3, bash, Xfce shell (in Virtualbox on top of the above)

Used this as a push to finally install v2.0.1 of Visidata on pop_os, and it's no longer an issue.

**Comment by anjakefala** [comment]
That makes sense! This was was added in `v2.0`:

```
visidata/movement.py:Sheet.bindkey('2097152', 'scroll-down')
```

I am going to close this as fixed.
