### ISSUE TITLE
Have A/B/C... refer to unnamed columns when VisiData opens .xlsx files

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#81]
When opening an xlsx file with visidata, colums are unnamed and instead contain the excel letter headers.

These default headers cannot be used as a reference for keys such as `c` or `=`.

![](https://user-images.githubusercontent.com/7489659/29503424-95157e1c-8605-11e7-9788-4f702e32fa8c.png)

```
File "visidata/vdtui.py", line 1511, in _getDisplayValue
    cellval = self.getter(row
File "visidata/addons/metasheets.py", line 75 in <lambda>
    vc.getter = lambda r,c=vc,s=sheet: LazyMapping(s, r)(c)
File "visidata/addons/metasheets.py", line56, in __call__
    return eval(col.expr, getGlobals(), self)
File "<string>", line 1, in <module>
NameError: name 'F' is not defined
```

Current workaround is to rename headers with `^`.

![](https://user-images.githubusercontent.com/7489659/29503529-5601a768-8606-11e7-99bc-a992eeff3f81.png)

**Comment by saulpw** [comment]
in v0.97
