### ISSUE TITLE
[develop] color_column_sep regression

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#814]
**Small description**
After a short convo with @spw in #visidata the color_column_sep bug was fixed (search for color_column_sep in the chat).

I appears that the issue has now resurfaced and the columns separators do not color using `color_column_sep`.

Currently, only the header row is colored correctly

![image](https://user-images.githubusercontent.com/11225502/100535400-00e9ad80-3232-11eb-917c-8ef5771983cf.png)

**Expected result**
Column separators to be able to be colored by using the options in the .rc:

```
options.color_column_sep = 'red'
vd.options.color_column_sep = 'red'
TableSheet.options.color_column_sep = 'red' 
Sheet.options.color_column_sep = 'red' 
```

**Comment by anjakefala** [comment]
Hi @geekscrapy!

I could not reproduce this with the most recent `develop` branch. Which commit are you on? Could you update and check if you are still seeing the issue?

Something that I did notice is that `<TableSheet|Sheet>.options.color_column_sep = 'red'` should be `<TableSheet|Sheet>.class_options.color_column_sep = 'red'`. `class_options` is the class property, `options` is used by instances.

**Comment by anjakefala** [comment]
We have determined that this was an environment issue!
