### ISSUE TITLE
Pandas DataFrame should be viewed simply using visidata.view(..)

### ISSUE THREAD

**Issue by s-celles** [saulpw/visidata#817]
Hello,

currenty to view a Pandas DataFrame it's necessary to do

    visidata.view_pandas(df)

Maybe it should be possible to have only one `view` entry point (ie method)

    visidata.view(df)

Depending if Pandas is installed and if `df` is really a DataFrame (or a Series) it should call internal method `visidata._view_pandas` or `visidata._view_other`

Kind regards

**Comment by saulpw** [comment]
I agree, this would be an improvement.  Submit a PR and we'll get it merged!
