### ISSUE TITLE
xlsx file loader: xml.etree.ElementTree.ParseError: not well formed

### ISSUE THREAD

**Issue by suntzuisafterU** [saulpw/visidata#819]
**Small description**
When opening an xlsx file, I get the following error:
```
xml.etree.ElemeentTree.ParseError: not well formed
```

**Expected result**
No error.

**Actual result with screenshot**
Sorry, no screen shot.  Technical difficulties.
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.
```
text                                                                                                                           
Traceback (most recent call last):                                                                                               
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/visidata/threads.py", line 215, in _toplevelTryFu   
    t.status = func(*args, **kwargs)                                                                                             
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/visidata/sheets.py", line 888, in reload  
    for r in vd.Progress(itsource, gerund='loading', total=0):                                                                   
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/visidata/threads.py", line 70, in __iter__            
    for item in self.iterable:                                                                                                   
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/visidata/loaders/xlsx.py", line 32, in iterload       
    for row in Progress(worksheet.iter_rows(), total=worksheet.max_row or 0):                                                    
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/visidata/threads.py", line 70, in __iter__            
    for item in self.iterable:                                                                                                   
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/openpyxl/worksheet/_read_only.py", line 82, in _c     
    for idx, row in parser.parse():                                                                                              
File "/usr/local/Cellar/visidata/2.0.1/libexec/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py", line 139, in pars 
    for _, element in it:                                                                                                        
File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py",     
    yield from pullparser.read_events()                                                                                          
File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py",     
    raise event                                                                                                                  
File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py",      
    self._parser.feed(data)                                                                                                     
File "<string>", line None   
                                                                                                
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 202, column 31102623
```

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

Sorry, but due to the sensitive nature of this data I can not provide a sample.
If I can determine exactly what in the data is causing this issue I will update the post, or if I can make a minimal dataset that reproduces this error.

**Additional context**
Please include the version of VisiData.

VisiData v2.0.1

Notably this file is successfully parsed by the R library readxl (and I can subsequently open the file in visidata with the rvisidata R library).
The data seems to be well formed when opened in R, this seems to be a limitation of the openpyxl library (or possibly of the xml library).

**Comment by anjakefala** [comment]
Hi @suntzuisafterU!

Is it possible to share the xlsx file that you saw this problem with? Because we cannot reproduce this with our sample xlsx file.

One thing left for me to try is to check if this is a Python 3.9 xml problem. @ajkerrigan, do you see this with a homebrew'd VisiData?

**Comment by suntzuisafterU** [comment]
Sorry, I can not share the file.
I should have tried this earlier, but attempting to open the file in excel failed.
Actually excel repaired it by removing the offending table and producing a blank file.

I think this problem is out of visidatas control.  Apparently readxl is the gold standard in repairing excel files, :).

**Comment by saulpw** [comment]
Hi @suntzuisafterU, if you can find a way to read the file using some kind of Python library, I'd be very interested.  Ideally we would submit a fix upstream to openpyxl if we figured out what was going wrong.

**Comment by niinod** [comment]
I have this same problem with some files I'm working on.

I have an archive where the content of my files is duplicated. Meaning, I have the content both in a csv file, and a xlsx file. 
And i have hundreds of these couples. 

I have made a python script that processes these files by importing the excel files in pandas and doing some stuff to them, and exporting it again. But every now and again i run in to an excel-file that gives me a similar error as OP. (The column number is very high, much higher than the actual numbers of columns in the file.)

I have found that I can open the csv-file in excel and see the data. I can import the data with read_csv. But if i process the data from the csv-file, and try to 'to_excel' it again. I get the same problem as the original excel file. 

The file cannot be opened in excel and it can't be read with read_excel.

**Comment by saulpw** [comment]
@niinod If you can share one of the broken excel-files, that would be very helpful.

**Comment by niinod** [comment]
I can't share the files, unfortunately. 

But i rebuild my script so it isolated the broken files, and then the cells that contains the text that causes problems.

There are a bunch of characters here that doesn't make any sense.

I have about 20 different cells that looks something like this: =��_����J�y���]�IK�S��?��$d�e�Yh�C�a{?Q���2Ƞ��h�C
���;7�Zi���2Y��#��ʹ[��

That data is supposed to be a text-string that should be readable to humans, so obviously something went wrong somewhere along the way before i got them.

All the cells starts with =

**Comment by saulpw** [comment]
Unfortunately we can't figure out how to work around the issue from that fragment.  We need to see the file in the surrounding context.  Maybe see if you can create a minimal example that you can share but still exhibits the same properties.

**Comment by niinod** [comment]
The xlsx, file cannot be opened in excel, and it also can not be read with .read_excel.
I can open the csv-file that is supposed to contain the same data as the excel-file. 

Those characters i posted is the data in the cell that causes the problems. If i remove it, I can "to_excel" the dataframe and i have no more problems that that file, other than that Im missing a line in one of the files. 

I have exported one of the cells to and csv-file. If you read this with read_csv, it will work. If you then to_excel it, and then read_excel it, I believe you will get the same error as OP.

[problemcell.csv](https://github.com/saulpw/visidata/files/7860687/problemcell.csv)
