### ISSUE TITLE
[2.0.1] No .json test file in sample_data dir

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#823]
**Small description**
I was trying to find a normal .json test file to include in the test for #822 but didn't find one for .json
I presume tests are currently being run against .json?

**Comment by anjakefala** [comment]
Did you want to propose one?

**Comment by saulpw** [comment]
We do have `sample_data/y77d-th95.json.gz` that we use for some tests. (Most tests are format-agnostic, but we should try to have one small data file per supported loader).  As @anjakefala mentioned, if you have any ideas for better samples, please propose them. I've actually been wanting to overhaul our `sample_data` directory for awhile now.  Maybe we should start a discussion.
