### ISSUE TITLE
[2.0.1] Saving a file from the http loader saves to url

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#824]
**Small description**
When opening a URL like `https://isc.sans.edu/api/cloudcidrs?json` and then doing `save-sheet`, the given example name for the save location is the URL itself.

**Expected result**
A useful name to be given. For this example maybe `cloudcidrs?json` as the example name?

**Comment by saulpw** [comment]
Good idea, @geekscrapy.
