### ISSUE TITLE
How to open a PDF table?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#829]
Hi,
when I try to open [this PDF ](https://github.com/saulpw/visidata/files/5652300/C_17_notizie_5196_1_file.pdf), I'm not able to open properly any table.

I'm using the latest develop version. Is it a bad PDF or am I using vd wrong?

Thank you

![vdpdf](https://user-images.githubusercontent.com/30607/101345136-e8f3d880-3886-11eb-9724-604de0632148.gif)

**Comment by aborruso** [comment]
Using `vd --pdf-tables` I have the same result

**Comment by anjakefala** [comment]
Did you install `pdfminer.six` and `tabula`?

```
pip3 install pdfminer.six tabula
```

With any new loader, you can find its requirements in the requirements.txt or on [/formats](https://visidata.org/formats). =)

**Comment by anjakefala** [comment]
I figured it out! What you are seeing are newlines. Press `v` to enter multi-line mode. To access a page, press `z Enter` while you in the contents column. `Enter` on a row should take you there by default, I will look into that!

**Comment by aborruso** [comment]
> I figured it out! What you are seeing are newlines. Press `v` to enter multi-line mode. To access a page, press `z Enter` while you in the contents column. `Enter` on a row should take you there by default, I will look into that!

Thank you, but I'm not able to use it properly. At page 2 I have this table:

![image](https://user-images.githubusercontent.com/30607/101383400-5e789c80-38b9-11eb-91c3-dbf0d7e3e84e.png)

In vd it's in this way

![image](https://user-images.githubusercontent.com/30607/101383480-7bad6b00-38b9-11eb-8c5b-9a90005fe278.png)

If I open it and click `z Enter` I have

![image](https://user-images.githubusercontent.com/30607/101383564-97b10c80-38b9-11eb-9a77-1a7fa3591f95.png)

And I have strange page numbers: it's a 12 pages pdf and in the first column I have also page 67

![image](https://user-images.githubusercontent.com/30607/101383312-4143ce00-38b9-11eb-8dcf-9e84067e0b96.png)

**Comment by aborruso** [comment]
I must correct myself, pressing `z Enter` I have.


![image](https://user-images.githubusercontent.com/30607/101384066-3e95a880-38ba-11eb-94ec-b2bd6ba1ba4c.png)

**Comment by saulpw** [comment]
Hi @aborruso, this just reflects what the pdf-tables library reports.  Not much we can do about that.  There are other PDF data extraction services but they cost money.  If anyone has a better way to do this in Python, let me know!

**Comment by ghost** [comment]
Might be worth looking at [Camelot](https://github.com/camelot-dev/camelot). It's a Python library dedicated to extracting tables from PDF files.
