### ISSUE TITLE
How to use and set http auto-paginate?

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#830]
Hi,
in the 2.1 blog post (great release, thank you to all) there is this new feature

> [http] auto-paginate by continuing with the given links.next.url from the response.

How to use it?

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, it should happen automatically for APIs that support it. Try, for example, `vd https://api.github.com/repos/django/django/pulls`.  See how it loads them in chunks of 10; that's it following the next.url links.

**Comment by jsvine** [comment]
Ah, very interesting — and clever! Two questions about this behavior:

- Is it possible to override it? (I don't see an option in the implementation logic, but perhaps I've overlooked something.) There are times when I want to examine the *exact* data returned by an HTTP GET request, sans magic.

- What do you think about adding an option for limiting the number of pages to fetch? I can imagine some API endpoints may have nearly limitless (or sufficiently large) pages — more than the user might want to load, or than the server might want to handle.

**Comment by saulpw** [comment]
It's not possible to disable or limit it currently, but I can see how that could be useful, especially in batch mode.  We could make an `options.http_max_next`, with a default of `10` or `50` or something reasonable.

In the meantime, in interactive mode, you can also wait until the first N pages pop up, and then cancel the loader manually with Ctrl+C.

**Comment by jsvine** [comment]
Thanks for the response, and sounds good!
