### ISSUE TITLE
Better support for interactive editing/inspectability/saving aggregation results

### ISSUE THREAD

**Issue by WesleyAC** [saulpw/visidata#838]
I'll start off by saying that this is a sort of nebulous and enormous feature request, so I completely understand if it just gets closed as something that's not going to happen, or if you'd like me to split this into smaller issues. I'm making it primarily to get an idea of whether the use cases described are something you're interested in supporting, and to open a discussion about whether it's possible to have the sort of interactive editing I want in visidata using existing features that I just haven't discovered yet.

I really love visidata for exploring datasets that already exist, but I find that I come to a lot of interesting results by taking a small amount of data that exists, often from multiple sources, and combining it into a larger, more complicated model. My typical tool for doing this is google sheets, but I would prefer that it be visidata, to give me easy access to things like frequency tables and aggregations that can use python. There are a few things that keep me from using visidata for this sort of work:

**Saving aggregations that output scalars is not supported**

I can run `z+` on a column to aggregate something, but I can't save the output of that anywhere, afaict. It's common in my google sheets work to have cells that contain sums or other more complex aggregations that output scalars. While this complicates the data model, and is not a clean way of doing things (since the aggregation has a spatial location in the sheet, but often isn't actually associated with the column/row it's in), it does provide an easy way to see a set of topline metrics as the data changes. I wish I could do something similar in visidata, and I also wish I could write ad-hoc custom aggregators in `z+` the way I can with `=` (perhaps this is already possible, and I just don't know the right incantation)

I don't know what the best solution to this is — adopting the excel model where aggregation results can be put in arbitrary cells seems fraught, as I've seen plenty of spreadsheet bugs that come from a aggregation accidentally being treated as value. Perhaps a solution would be to make it easy to have a sheet that consists of two columns: an aggregation and a result, such that people could put aggregations that they want to keep track of in a sheet to store them (this fits nicely with the "everything is a sheet philosophy")

**Derivative columns are not inspectable**

Once I've made a derivative column (`=`), it's unclear to me how to see the equation that was used to create the column. If I save a cmdlog, I can see it there, but I don't know of any other way to do this. I also don't know of a way to tell which columns are derivative and which ones aren't (other than trying to edit the column and seeing if there's an error).

While the name initially gives a hint, I usually want to feed derivative columns into other derivative columns, and the generated names typically can't be used in python expressions, so I end up renaming most of the derivative columns I make.

In the same vein, I don't know of any way to edit the equation behind a derivative column without just deleting it and creating another. It seems like allowing a way to edit the equation behind a derivative column would solve both the lack of visibility and the inability to edit.

A related (but less important to me) thing is that opening xlsx sheets that use any sort of excel-style aggregations is not typically very useful, since only the results of the aggregations are displayed. For instance, opening a sheet like:

| | **A** | **B** |
| --- | --- | --- |
| **1** | 42 | 123 |
| **2** | | `=A1+B1` |

is not very useful, since the equation behind `B2` is not visible, and updating the inputs does not result in recalculation of the outputs. My guess is that fixing this in a principled way would be pretty annoying, but it seems worth noting.

To me, one of the really important aspects of spreadsheets for interactive use is the observability of the equations behind the data, which is something I find visidata doesn't do very well at.

**Graphing is tricky to use/limited in functionality**

While graphing on the terminal is very cute, I find it less useful than using tools like gnuplot, since the resolution is poorer, interactive zooming is more difficult, telling where datapoints overlap is harder, and there are many fewer features (being able to do things like graph derivatives or mathematical functions, while somewhat cumbersome in gnuplot, is quite useful).

I don't have any real vision for what this would look like, but some sort of integration with gnuplot or matplotlib would be very useful.

I haven't looked at the plugin API in detail, but it seems like maybe there could be a plugin for this?

**Cmdlogs are not well documented**

While I love the idea of cmdlogs as a way of saving history, there are a couple things about the implementation that feel tricky to use. I think it would be hard to improve the actual behaviour, but the documentation could be better. Particularly:

1. The behaviour around relative file paths is a little surprising — if you open file with a relative path, and save a cmdlog, you need to be in the same cwd as you were when you opened the file in order to run the cmdlog correctly. I expected relative paths to be interpreted relative to the location of the cmdlog, although I think the current behaviour makes sense as well — mostly, I just think that this should be documented.
2. It's unclear how changes to the schema of the input files are handled. If a column is renamed or deleted on the input sheet, how is that dealt with when the cmdlog is opened is unclear. Specifically, if a column is renamed, it's unclear to me how to edit the cmdlog to deal with that, especially if the column name is one that is generic enough to appear in multiple sheets.
3. How errors are handled and surfaced is unclear. Ideally (for my usecases), if there's any error at all in replaying the cmdlog, visidata should quit with an error explaining what happened, so that I don't inadvertently edit a sheet with a cmdlog only halfway applied. It doesn't seem like this is what happens though, but I couldn't tell you exactly what the behaviour is when there are errors.

Perhaps I'm worrying too much about this, but I think that comes from the cmdlog being undocumented, as far as I can tell, so my mental model of it is just based on poking around, which hasn't given me a ton of information.

I really love visidata, and would like to use it for more things, so I'm hoping at least a few of these things could be improved :)

**Comment by saulpw** [comment]
There are some good questions here.  Some of these are bugs, some feature requests, some are usage issues, and I have specific things to say about each one, but before that, please do split this into 4+ separate issues.  Also please be more specific with your usecases.  For example you say "ad-hoc custom aggregators in z+ the way I can with =" but it would be better to provide a literal expression or use case so there's something to design against.

Also you'll have better luck getting a positive response if you frame requests positively instead of negatively, e.g. "X is not supported" comes off as a complaint, whereas "is it possible to X?" is an invitation to be creative, or "it would be great if I could X" shares some enthusiasm.
