### ISSUE TITLE
Generate Python code to reproduce workflow/context

### ISSUE THREAD

**Issue by jflam** [saulpw/visidata#840]
Was wondering if there's any prior art for using VisiData to generate Python scripts from its logs? This could be a really interesting tool for coming up with data cleaning scripts by example - kind of like the Excel macro recorder.

With the holidays coming up this I might have some time to hack on this too, but first wanted to check to see if there was any existing code that I could look at. Thx!

**Comment by saulpw** [comment]
Hi @jflam, I've had some vague ideas about this myself, and I agree it would be awesome, but nothing has been implemented yet.  If you want, come by #visidata on Freenode and let's chat about it.

**Comment by saulpw** [comment]
I think it would be great to have a .vd to .py or SQL transpiler, but this seems like a large task.  If anyone's up to trying, I'd be happy to support the effort!

Kondo'ed for now.
