### ISSUE TITLE
Did behavior of JSON column expansion change (kind of) recently?

### ISSUE THREAD

**Issue by brookskindle** [saulpw/visidata#843]
Hello! 👋 

Let me begin by saying that I love using visidata for all types of initial exploratory data work. One of my common use-cases is using it to inspect a complex JSON payload in order to understand the structure better.

I used to have a version of visidata (I don't remember which version) where as I was diving into a large, nested JSON object, all of the fields on the current level (provided the field was not, itself, an object or array) would expand into columns automatically. 

When I updated visidata to `v2.0.1`, that default behavior changed, and object fields are now unexpanded by default
![Screen Shot 2020-12-14 at 3 12 04 PM](https://user-images.githubusercontent.com/2654835/102147093-07297d80-3e1f-11eb-9c0e-30d5c6bd68c7.png)

I can still get what I need to get done by using the `gz(` expand shortcut and setting `depth=1`, but another observation is that the column names are also different. Eg: `-[]_stores.name` instead of simply `name` (or perhaps `stores.name`, it's been a while since I used the older version with this behavior).
![Screen Shot 2020-12-14 at 3 13 38 PM](https://user-images.githubusercontent.com/2654835/102147105-0bee3180-3e1f-11eb-93a2-4e973ecd8067.png)

Do you know if this was an intentional decision, or if there is a way to configure visidata to use the old behavior that auto-expanded a depth of 1 when looking at objects?

Thanks in advance, please let me know if that makes sense!

**Comment by anjakefala** [comment]
Hi @brookskindle! Thanks for dropping by. =) I liked your blogpost on your aesthetic terminal set-up.

(Caveat: @saulpw and @ajkerrigan are more likely to know the details of the json loader than I am, but I am the one who is currently available to respond to issues. =D)

There have been some changes in the json loader based on various feedback from users.

Off the top of my head:
57ca324cabe2ebce37774e6bd40bbc223ee675db
#529 

To get an idea of which one has impacted the change in behaviour for you, I need some more information on what the raw json you are looking at looks like.

e.g. Is it kinda like this?
`[{'name': blah, 'type': blah, 'address': blah}, {'name': blah2, 'type': blah3, 'address': blah4}]`

> Do you know if this was an intentional decision, or if there is a way to configure visidata to use the old behavior that auto-expanded a depth of 1 when looking at objects?

Which version of VisiData did you have previously? I don't remember a default expanded depth of 1, but I can look into this.

**Comment by brookskindle** [comment]
Thanks @anjakefala  :) I like your avatar!

A minimal JSON example would be as follows
```json
{
  "total": 1,
  "stores": [
    {
      "number": 1,
      "name": "Store 1"
    }
  ]
}
```
(which is a much simplified format of the API response you get when entering a zipcode on [this page](https://www.nordstrom.com/stores))

Trying to view the list of `stores` in that payload is where the fields of each store are being truncated to `{2}` as opposed to expanded into columns.

~~I'm not actually sure which version of VisiData I had previously, but I can install previous versions to see at what point the behavior switches.~~
* On the official pypi releases, the desired behavior is present in `1.5.2`, but gone from `2.0`.
* By the tags, it looks like this is strictly an issue with the `2.0.0` release. `v2.-4.0` displays the same behavior as `1.5.2`

**Comment by anjakefala** [comment]
>  By the tags, it looks like this is strictly an issue with the 2.0.0 release. v2.-4.0 displays the same behavior as 1.5.2

Many thanks! You saved me a `git bisect reset`. Taking a look.

**Comment by anjakefala** [comment]
I think this is a bug.

Commits that were the origin of the problem:

```
commit cc397ee4953c13ad7b6e9d0a5ac2e2c8f8d6726a (refs/bisect/skip-cc397ee4953c13ad7b6e9d0a5ac2e2c8f8d6726a)
Author: Saul Pwanson <code@saul.pw>
Date:   Sun Aug 16 19:50:39 2020 -0700

    [api] Sheet(*names) autojoins list of name parts
    
    API changes:
    - joinSheetnames deprecated
    - Sheet(*names, **kwargs): names are automatically joined by previous joinSheetnames
    - load_pyobj(name, source) -> load_pyobj(*names, **kwargs)
       - source was inspected and then provided as kwargs to the Sheet constructor
       - now source= is required in kwargs, just like all other Sheet constructors, and other kwargs are now allowed.

commit 75540b52e0471c85e723af532c81286077e70658 (refs/bisect/skip-75540b52e0471c85e723af532c81286077e70658)
Author: anjakefala <anja.kefala@gmail.com>
Date:   Wed Aug 19 22:10:12 2020 -0700

    [api] api is now Sheet(*names, **kwargs)
    
    see cc397ee495

commit a870943c97b0db4cc2072097580d8d178e6f926f (refs/bisect/bad)
Author: Saul Pwanson <code@saul.pw>
Date:   Sun Aug 23 18:21:10 2020 -0700

    [pyobj] standardize on Sheet[List/etc](*names, **kwargs)

```

**Comment by anjakefala** [comment]
`z Enter` is opening up a pyobj sheet for lists, and that is what is behaving differently (and I think in a Less Good way). I do not think this involves the json loader (`gz(` is json loader functionality, which is what is working for you).

I am still looking into it, I am not quite sure why it is not unpacking the list, like it did previously.

**Comment by anjakefala** [comment]
Most definitely a bug, @brookskindle! It should now be fixed on develop, and will be fixed in the next release. I am gonna cobble a test for it.

Thank you so much for drawing attention to it.

**Comment by brookskindle** [comment]
🙌 I checked out develop and it works perfectly, thank you so much for fixing this @anjakefala!
