### ISSUE TITLE
 [open-new/guard-sheet] Default for a new table should have a status guard

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#844]
If you create a new sheet in Visidata, it should have guarded status.  Assume that the user is trying enter their own data and would not like to lose it.

This next suggestion is more nebulous, but just further along that path of the request.  It seems like other edit operations vs reshape options should cause a sheet to automatically become guarded.

The issue I've had is when creating personal data files in vd, I've intentionally lost data and the all the effort to enter the data.

**Comment by saulpw** [comment]
Okay, we're now tracking modifications, and by default will only ask for confirmation if the sheet is modified (and "precious").  This can be disabled by setting `options.quitguard=False`, which means confirmation is never required.

- When you add, delete, or edit values, it should display `[M]` on the right status.
- If you undo all edits, the modified status should go away.
- If the modified status is displayed, it should require confirmation to either quit or reload the sheet (also `gq` of course).
- After saving the sheet in its entirety (i.e. not just a column) the modified status should disappear and the sheet should not require confirmation to quit or reload.
