### ISSUE TITLE
[expand] Expand as a table (eaat)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#845]
Along the lines of "everything is a sheet"...

Visidata is pretty good at looking at structured data (json/yaml).  There are
some useful builtins such as expand-col and unfurl-col, but when you have a
deep structure to dive into these commands have some some issues.

Unfurl can be used for one level down, and can be applied repeatedly.

For a deep structure, expand-col expands so many columns the columns can expand
out so far that the width of the screen only lets you see a small sliver.  It
is possible to limit how many levels with expand-col-depth, but that assumes
you know how deep you want to go.  Once expanded, you use the column table to
limit what columns are shown, and to clean up the added prefix(es)
(remove/rename).  But first you have to select all these new columns, and then perform your edits.

I want something similar, but optimized for this use case.

I would like to have a two step expand-col-as-sheet command.

Run the expand-col-as-sheet command on a column with lists/dicts  it pushes a new "expand" sheet on the stack
something very much like the column sheet:

   - one row for each new source column to be expanded
   - some columns for metadata about the new columns (like the column sheet)
   - instead of a single value column, have multiple value columns.  Maybe one of
     - one column per row from the source sheet
     - one column per selected row from the source sheet 

The value columns should be readonly.  They are there mostly to help you figure out which columns you want, and what their names should be.

The user is then able to use the full power of Visidata on this expand table:
   - filter/delete rows of this temporary table
   - remove/rename prefix
   - sort/reorder rows

When everything is just right (which columns to include, naming, ordering), the
user runs the "commit" command, and the rows still left in the expand table and with the adjusted naming show up in place of the original column in the source table.

**Comment by saulpw** [comment]
Interesting idea, @frosencrantz.  Probably best as a plugin for starters.

Kondo'ed for now.
