### ISSUE TITLE
[nested values] Provide more control over formatting nested values

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#846]
Visidata is great at dealing with nested values, but it would nice to have a better idea of what data is hiding in an unexpanded value without having to expand/unfurl/etc the data.

Currently we get [3] and {3} for lists and dicts.

Some thoughts:

   1. For empty lists/dicts don't display the zero [] instead of [0].  Adding the 0 can make the value bigger than the orignal.
   2. Include the length of the string version of the value.  So maybe something like [1,2,3,4] ->  [4]:9, where 4 is the count of the list and 9 is the string length of the value.
   3. List only small parts of the data, for example:
      1. The items on the ends of the list with a 100 items might be [1,2,...,99,100]
      2. For  dicts/objects list a single identifying field, such as a field called name/id/key/etc or ['name1', 'name2',...]
   4. Just display the value as a multi-line string in the cell in a choosen format:
      1. For json or yaml this is quite useful with long cells, show as the value in the base format of the file.
      2. Display the value as a selected tabulate format.

I'm sure there are many more.

It would be helpful when viewing structured data to have more control over the formatting of the values displayed.  The current default is useful, but there are times when I find I need to expand something to help me decide what data I want to look at further, and some additional hints would have helped.

As example,the most_common and least_common columns  https://sqlite-utils.readthedocs.io/en/stable/cli.html#saving-the-analyzed-table-details .  These two columns are JSON lists of lists; the outer list contains 10 lists, the inner lists are a pair of values the count and the value.  Here it would be useful to format the cells of this column in pretty way, unfurling or expanding these columns is not as useful.

**Comment by saulpw** [comment]
You can stringify a list by marking the column as a string (`~`) type.  The problem with doing this automatically is that it can take a long time to stringify large lists.  And we can't know e.g. the length of that string without doing the stringify.

**Comment by frosencrantz** [comment]
I've used&like the string type trick, which I should have mentioned.  You can also get length if you add a column. Those  do help, but it leads me to think if I could see just format that string for smaller values, or for larger values if I could just get the names of the entries.
That's how I got to this request.

When I looked at the formatting by type it seemed like the formatting was not possible to override.  I guess it would be possible to add a new type.  But any time the user expanded a column, they would need to apply the new type on new nested columns.

**Comment by saulpw** [comment]
It's true that there is no `options.disp_dict_fmt` (I don't know quite what that would look like).  But you can do:

```
@Column.api
@functools.wraps(Column.formatValue)
def formatValue(self, typedval):
    if isinstance(typedval, (list,tuple)):
          return '[%s] %s' % (len(typedval), ' '.join('%s' % v for v in typedval))
    else:
         return self.formatValue.__wrapped__(typedval)
```

There's a problem with this usage (only one wrapper will work), but for local customizations it should be fine.

I think better proactive rendering of lists/dicts are a good idea.  I like your suggestion of `[1,2,...,99,100]` for lists but it seems harder to determine or configure what to display for dicts.  I also like the idea of being able to see and maybe edit the pretty-printed output, but would put it on something like `z Ctrl+O`.  I'd be interested to see what you wind up preferring, especially if you get something working that doesn't destroy performance with large lists.

**Comment by frosencrantz** [comment]
Brilliant!

There are a couple minor changes needed to get it to work.

```
#import yaml, tabulate
import functools
from visidata import Column

@Column.api 
@functools.wraps(Column.formatValue)
def formatValue(self, typedval):
    if isinstance(typedval, (list,tuple)):
          # return tabulate.tabulate(typedval)
          return '[%s] %s' % (len(typedval), ' '.join('%s' % v for v in typedval))
    if isinstance(typedval, dict):
          return yaml.dump(typedval)
          # return tabulate.tabulate([typedval])
    else:
         return self.formatValue.__wrapped__(self, typedval)

Column.format = formatValue
```


When I got it to work, I was able to use PyYAML and Tabulate to format the values.  The results were nice, and worth looking at some more.

Different formats work better with different data, so it does need to be made more flexible, and needs some heuristics or the ability to manually change it based on the data.

I'm not fully clear on what `options.disp_dict_fmt` would look like either.  Maybe it would allow for the user to pick the formatter, and the formatters have different options.  The formatters might look like:

 - yaml
 - tabulate.github
 - tabulate.plain
 - format

Where `format` would mean use the string format we use now, but it would have `options.disp_dict_fmt_format` with default of `{{len}}`, but if you wanted to include strlen you could set it to `{{len}} {strlen}`.

But having tried it and seeing some of the shortcomings, it does seem like it might be useful to either make it smart, or to give the user more control, such as allowing it per column.  I was trying to avoid having to set it manually per column.

Your example helps me appreciate the Extensible class, and how that works within Visidata.  Making it fairly easy to create a plugin that would allow for custom formatting.  I didn't think it was that easy.

Thanks, @saulpw!
