### ISSUE TITLE
Document how disabling motd and plugin url is supposed to work

### ISSUE THREAD

**Issue by ursetto** [saulpw/visidata#850]
Back in the [1.1 days](https://github.com/saulpw/visidata/blob/stable/CHANGELOG.md#v11-2018-03-05) it was suggested to disable motd by setting `options.motd_url = None`. In fact, this has no effect in Visidata 2.1 as `None` apparently selects the option's default value. That's really what I'd expect and this behavior is fine.

The working override is `options.motd_url = ''`. In other words, an empty string, not `None`.

I'm using Visidata behind a restrictive corporate proxy/firewall which either blocks or returns 403 Forbidden on access to visidata.org.  motd errors are silently ignored, so `None` appeared to be working, when it was actually issuing a failed network request.

`options.plugins_url = None`, however, does not fail silently. On every startup, I get 403 Forbidden in the status line as it tries to source `plugins.jsonl` from visidata.org.

Setting to `options.plugins_url = ''` fixes this.

Disabling motd/plugins isn't documented to my knowledge (except obliquely in the changelog), so documenting how it works is more a feature request than a bug fix.

**Comment by saulpw** [comment]
Hi @ursetto, thanks for the comment.  I think we should make `plugins_url` fail as silently as `motd_url`; but also, I don't think vd should be loading it every startup (unless you start as just `vd` with no input).  And yes, we should add the proper way to disable the motd to the documentation somewhere.

**Comment by dsedivec** [comment]
> The working override is `options.motd_url = ''`. In other words, an empty string, not `None`.

~~Neither `None` nor `""` work for me anymore.  Running "saul.pw/VisiData v2.2.1".~~

**EDIT**: Sorry, false alarm, I was trying to make VisiData not call out to the Internet every time I ran it, and I didn't understand that I needed to set *both* `motd_url` and `plugins_url` to `""` (empty string).  That does work, VisiData no longer "phones home".

**Comment by saulpw** [comment]
VisiData should cache the results so that it only sends these requests once per day. The plugins.jsonl request was not being cached at all, however, and was being fetched every startup. This is now fixed on `develop` and will be in the next release.
