### ISSUE TITLE
[sqlite] Respect foreign key constraints when joining tables.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#855]
I tried using http://github.com/dogdsheep/github-to-sqlite (g2s) to track the health of the VisiData repo.  For https://github.com/saulpw/visidata/issues/738 I grabbed the data using curl, but this tool made it much easier.  I then used vd to explore the data, stargazers, issues, pull requests, etc.

G2s normalizes the data, and provides foreign key constraints and references, that vd could make better use of.

For example, I wanted to look at the `stars` table.  The user details including user name are in the user table indexed by the id column, while the stars table references it by the user column.  When using the default table inner join of stars and users this didn't work without having to manually update the primary keys in the vd. (I could get it to work by changing names, and changing what was a primary column the tables.)

	```
	CREATE TABLE [stars] (
	   [user] INTEGER REFERENCES [users]([id]),
	   [repo] INTEGER REFERENCES [repos]([id]),
	   [starred_at] TEXT,
	   PRIMARY KEY ([user], [repo])
	);

	CREATE TABLE [users] (
	   [login] TEXT,
	   [id] INTEGER PRIMARY KEY,
	   [node_id] TEXT,
	   [avatar_url] TEXT,
	   [gravatar_id] TEXT,
	   [html_url] TEXT,
	   [type] TEXT,
	   [site_admin] INTEGER,
	   [name] TEXT
	);
	```

This Feature Request is to have vd read these relationships and use them automatically when doing joins.  Or provide an additional join that understands and uses these relations.

It looks like Datasette does this automatically, here is the view from the sample database:
   https://github-to-sqlite.dogsheep.net/github/stars

And its configuration: https://github.com/dogsheep/github-to-sqlite/blob/main/demo-metadata.json
https://docs.datasette.io/en/latest/metadata.html?highlight=references#specifying-the-label-column-for-a-table

It seems like it would be useful if VisiData could handle this as easily.

And Happy New Year, Saul and Anja!

**Comment by SuRaMoN** [comment]
@saulpw are you interested in this? i could build a prototype if you want. i'm thinking about something like the screenshot below. When you are in a sheet and you press "&", on the right you'll see a suggestion list based on the current loader (in the case of sqlite loader, it will show the foreign keys of the current table with the destination table).

![image](https://user-images.githubusercontent.com/852196/105081297-49835180-5a92-11eb-8d03-dc1167f523c1.png)

**Comment by saulpw** [comment]
Hi @SuRaMoN, I'm definitely interested in having better joins, though I'm not sure about the interface popup shown here.  I've been thinking that maybe `&` could actually be a 'smart' join, which tries to detect which columns are related, and part of this could be based on existing foreign key defs.  If you're up for chatting about design ideas synchronously, how about popping by our IRC channel sometime?  (#visidata on freenode.net).  I'd love to talk this through in depth.

**Comment by SuRaMoN** [comment]
joined #visidata, ready when you are

**Comment by frosencrantz** [comment]
I've put some deep dive details about SQLite that might help get details about tables/columns in https://github.com/saulpw/visidata/issues/860#issuecomment-770241187

**Comment by saulpw** [comment]
Kondo'ed until sqlite deep dive.
