### ISSUE TITLE
[SqliteQuerySheet]  What is SqliteQuerySheet used for?

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#859]
How is SqliteQuerySheet used?  I don't see any references for it in the code.  It was added here:

https://github.com/saulpw/visidata/commit/30d5570bd9dba9a1fb7960be9b1ab1236d75d633

**Comment by saulpw** [comment]
I have some private plugins :)

**Comment by frosencrantz** [comment]
@saulpw hoping you are willing to share someday.  :)
