### ISSUE TITLE
[sqlite schema] Make it easy to explore Sqlite table metadata

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#860]
As mentioned in https://github.com/saulpw/visidata/issues/855 I tried using http://github.com/dogdsheep/github-to-sqlite (g2s) to track the health of the VisiData repo.  

G2s various features such as foreign keys, references, views, indexes, full-text search (fts), triggers, etc.  It would be useful if vd made it easy to explore the table metadata.  For tables it would be useful to see:
   - type (regular table, view, fts, etc)
   - indexes
   - table schema (.schema tablename)

When looking at the column sheet for give table, it would be helpful to see:

   - indexes
   - references/foreign keys
   - type

Maybe a way to see triggers.

Sqlite databases are used everywhere, and it seems like it would be useful if VisiData could make it easier to find understand the database schema.

**Comment by saulpw** [comment]
Yes, I want this too.  I'll probably do it next time I do a deep dive on sqlite.

Kondo'ed for now.

**Comment by frosencrantz** [comment]
Looking forward to it.

Since I last looked at this I found some possibly useful links.  It looks like vd currently ignores some of the data that would make this helpful.
   - https://github.com/saulpw/visidata/blob/develop/visidata/loaders/sqlite.py#L110-L116
      - here it only looks at the 2nd column (name), but it ignores the others.
      - For a description of the columns http://sqlite.org/schematab.html
   - https://github.com/saulpw/visidata/blob/develop/visidata/loaders/sqlite.py#L41-L42
      -  Here it only looks at the second column of `pragma table_info`
      - More details are here: https://www.sqlite.org/pragma.html#pragma_table_info
      - There is also a newer `pragma table_xinfo`
         - This appears to have been added later, and might not always be available.

It looks like there is a lot of deep dive details that can be found in the datasette code:
  - The details about when table_xinfo became available: [datasette/utils/__init__.py](https://github.com/simonw/datasette/blob/640ac7071b73111ba4423812cd683756e0e1936b/datasette/utils/__init__.py#L566)
  - How to figure out tables are of the different extensions.

Also, see https://til.simonwillison.net/sqlite/list-all-columns-in-a-database

**Comment by dufferzafar** [comment]
Also, visidata doesn't seem to load SQLite views

**Comment by frosencrantz** [comment]
@dufferzafar if you can include a column named rowid, Visidata will read the view.

This is tracked in: https://github.com/saulpw/visidata/issues/1111
