### ISSUE TITLE
Comma as a decimal separator

### ISSUE THREAD

**Issue by Guiriguanche** [saulpw/visidata#863]
In my locale the decimal "point" is the comma. Columns with currencies or floats are not sorted correctly nor is it possible to set the column datatype to float or currency. I tried finding an option in the local or global options sheet but was not successful.

**Column as read**
![Screenshot 2021-01-04 at 12 11 13](https://user-images.githubusercontent.com/1771029/103534186-55fa8e00-4e86-11eb-9cf9-903bebbb4cde.png)

**Column after converting to currency**
![Screenshot 2021-01-04 at 12 11 30](https://user-images.githubusercontent.com/1771029/103534313-88a48680-4e86-11eb-9609-93296a81919f.png)

**Additional context**
Visidata version v2.0.1 on MacOS Mojave (10.14.6) (tested on osx Terminal and iTerm2)
Preferred Languages (in System Preferences): English (UK)
Region: Spain
![Screenshot 2021-01-04 at 12 20 45](https://user-images.githubusercontent.com/1771029/103534721-56475900-4e87-11eb-9d33-80bace63abba.png)

```console
~ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
~ defaults read -g AppleLocale 
en_ES
```

**Comment by anjakefala** [comment]
https://github.com/saulpw/visidata/issues/861

**Comment by anjakefala** [comment]
Hi @Guiriguanche! There should now be a method implemented on the `develop` branch. It will be part of the next release.

You will need to set your shell environment variable `LC_NUMERIC` to a locale which interprets commas as decimals. Any European one should do. I tested this with `en_DK.UTF-8`.

Then, type the column with `type-floatlocale`. You can execute the longname by pressing `Space`, and then typing out `type-floatlocale`. I would bind the command to a keystroke, if you use it frequently. The documentation for that in "How to configure commands" here: https://www.visidata.org/docs/customize/

If you want to replace the currentl `type-float` with `type-floatlocale`, add to your `~/.visidatarc`:

```
unbindkey('%')
bindkey('%', 'type-floatlocale')
```

or if you never use `type-floatsi`, you can do

```
unbindkey('z%')
bindkey('z%', 'type-floatlocale')
```

that is the gist!

Thanks for making this feature request!

**Comment by floatingpurr** [comment]
Hello @anjakefala, sorry for posting here in this closed issue. I arrived here when I tried to bind a key to `type-floatlocale`.

I'm on VisiData v2.2. In my `.visidatarc` I have the following lines:

```
bindkey('%', 'type-floatlocale')
bindkey('g%', 'type-floatlocale-selected')
```

Nevertheless `%` is still mapped to the default `type-float`. Going over this issue I discovered `unbindkey()`. I tried also to put in my .visidatarc:

```
unbindkey('%')
bindkey('%', 'type-floatlocale')
```

but when I press `%` I still trigger `type-float`. Where am I wrong?

**Comment by anjakefala** [comment]
Hi @floatingpurr!

Can you try `Sheet.bindkey(...)` and `Sheet.unbindkey(...)`? Please let me know if that works for you.

**Comment by floatingpurr** [comment]
Hu @anjakefala,

   thanks it works! Is this a kind of bug? According to point 3 of [this](https://www.visidata.org/blog/2021/v2.2/) post, `bindkey('%', 'type-floatlocale')` should do the trick!

My details: Mac OS X 10.15.7 / zsh 5.7.1 / VisiData v2.2

**Comment by anjakefala** [comment]
This is not a bug! This is a mistake in my documentation. `bindkey()` by default over-rides on the **BaseSheet**, but `type-float` is bound to the **Sheet**. Since **Sheet** inherits from **BaseSheet**, commands bound to **Sheet** override **BaseSheet**. I will make time to improve the documentation when I am done some of my urgent tasks. ^^;

Thanks for asking!

**Comment by floatingpurr** [comment]
Got it! Thanx for your help!
