### ISSUE TITLE
describe_all does not have a column for sheet name

### ISSUE THREAD

**Issue by techieshark** [saulpw/visidata#864]
**Small description**

Following [this video](https://www.youtube.com/watch?v=prdyXM6-FSc), 

I'm interested in following the example to make a codebook. Unexpectedly, when I do the "describe_all" command (`gI`), I don't have the first column, showing the sheet name.

**Expected result**

See video at https://youtu.be/prdyXM6-FSc?t=198

<img width="848" alt="image" src="https://user-images.githubusercontent.com/1072292/103712412-e44d4c00-500d-11eb-9a57-ac3d4dde769e.png">

**Actual result with screenshot**

Note the lack of a Sheet column which is shown as first column in video screenshot above:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1072292/103712821-e82d9e00-500e-11eb-8f90-15a859ae48f2.png">

**Steps to reproduce with sample data and a .vd**

1. Given `attendees.csv`:

```
name,date
peter,2020-01-01
jane,2020-01-02
jill,2020-01-03
```

and `events.csv`:
```
event,location,date
dog party,New York,2020-01-05
cat party,San Fran,2020-02-10
```

2. zip them: `zip sample.zip *.csv`
3. open in VisiData: `vd sample.vd`. 

4. As shown in video, open all sheets then do global describe all. Expect to see Sheets column, but do not.

commandlog:
```
sheet	col	row	longname	input	keystrokes	comment
			open-file	sample.zip	o	
sample			select-rows		gs	select all rows
sample		0	open-row		^J	open sheet with copies of rows referenced in current row
attendees			sheets-stack		S	open Sheets Stack: join or jump between the active sheets on the current stack
sheets		キsample	open-row		^J	open sheet referenced in current row
sample		1	open-row		^J	open sheet with copies of rows referenced in current row
events			sheets-stack		S	open Sheets Stack: join or jump between the active sheets on the current stack
sheets		キsample	delete-row		d	delete (cut) current row and move it to clipboard
sheets		キattendees	open-row		^J	open sheet referenced in current row
attendees			describe-all		gI	open Describe Sheet with description statistics for all visible columns from all sheets
describe_all	mode	キname	release-mouse		BUTTON1_RELEASED	slide current row/column to mouse cursor release position

```

**Additional context**
Please include the version of VisiData: `saul.pw/VisiData v2.1`

**Comment by saulpw** [comment]
Hi @techieshark, use `gv` (unhide-cols) to show the hidden `sheet` column.

**Comment by techieshark** [comment]
Super, thanks @saulpw! I'm new to this tool and really enjoying it. ✨✨✨
