### ISSUE TITLE
[fancy_chooser] Undo and Redo should work for choices made via the fancy_chooser

### ISSUE THREAD

**Issue by anjakefala** [saulpw/visidata#866]
The fancy chooser launches as a second sheet in a second pane, and so `cmdlog_sheet` entries for initiating the choice and selecting a choice get divided between the original sheet and **choices** sheet.

Additionally, the input does not get logged as a cell value in either `cmdlog_sheet` entry.

Saul thinks the fancy_chooser should be converted into a modal, instead of being a second sheet in the other pane.

**Comment by geekscrapy** [comment]
I'd love the idea of the modal, instead of another sheet, I think it would makes things clearer that it needs input. It also might make selection a bit more flexible 👍

**Comment by anjakefala** [comment]
Related to: https://github.com/saulpw/visidata/issues/914

**Comment by saulpw** [comment]
Rolled up into #1027
