### ISSUE TITLE
cmdlog with set-option do not replay

### ISSUE THREAD

**Issue by setop** [saulpw/visidata#870]
**Small description**

using cmdlog file with `set-option` statements, replay (`vd -p`) does nothing.

**Expected result**

The cvs file is loaded in the TUI

**Actual result with screenshot**

The program immediatlly terminate with 0 as exit code

**Steps to reproduce with sample data and a .vd**

```
sheet	col	row	longname	input	keystrokes	comment
access		header	set-option	0		
access		filetype	set-option	csv		
			open-file	access.log	o	

```
It works by removing all 'set-option' rows, but the the file is not displayed properly.

**Additional context**

"saul.pw/VisiData v2.1.1"

**Comment by anjakefala** [comment]
Thanks for the bug report!

This is fixed on the develop branch. =) df3f2b0911bc02ad323feec520a2e6bd145545f0

It will be part of the next release. Feel free to use the develop branch!
