### ISSUE TITLE
Gpg key in ubuntu repos

### ISSUE THREAD

**Issue by marcobra** [saulpw/visidata#871]
**Small description**
i usually update your package without issue, In the last week, there is an error:

Error GPG: https://raw.githubusercontent.com/saulpw/deb-vd/master sid InRelease: Le seguenti firme non erano valide: EXPKEYSIG 06C997C9869C8F01 Anja Boskovic <anja.kefala@gmail.com>

for your ppa repos

deb [arch=amd64] https://raw.githubusercontent.com/saulpw/deb-vd/master sid main

it is impossible to upgrade your package  

please dress... thank you

**Comment by anjakefala** [comment]
Hi @marcobra! Thanks so much for letting me know.

I have not had a chance to look into this yet, but I will take a look sometime this week.

**Comment by anjakefala** [comment]
Hi @marcobra!

It turns out that the gpg key that I used for signing those packages has expired and been revoked. I updated the public key in the repository, and am now signing the packages with the new key. Can you try updating with the new key, and trying to download the latest package? Please update me with the outcome. =)

**Comment by marcobra** [comment]
W: Errore GPG: https://raw.githubusercontent.com/saulpw/deb-vd/master sid InRelease: ...... NO_PUBKEY 0C7B8BD548851160
E: Il repository "https://raw.githubusercontent.com/saulpw/deb-vd/master sid InRelease" is not signed.

https://wiki.debian.org/SecureApt#Settingupasecureaptrepository

HTH thank

**Comment by anjakefala** [comment]
Weird. In the meanwhile, can you grab the `.deb` from here? https://packages.debian.org/da/source/bullseye/visidata

**Comment by marcobra** [comment]
My best choice is to download the .deb file from this server list:
https://packages.debian.org/da/bullseye/all/visidata/download
and then install 

The quick way: open a terminal and copy and paste the rows below

```
cd /tmp; wget http://ftp.us.debian.org/debian/pool/main/v/visidata/visidata_2.2.1-1_all.deb;
sudo dpkg -i visidata_2.2.1-1_all.deb; sudo apt -f install
```
HTH

**Comment by anjakefala** [comment]
It seems something went wrong with my public key export...I exported it again. It should all work now! Please re-add the public key to your apt. =)
