### ISSUE TITLE
[docs] [plugins] - Plugin API docs seem to be missing

### ISSUE THREAD

**Issue by strazto** [saulpw/visidata#877]
From https://github.com/saulpw/visidata/blob/develop/docs/plugins.md

> * ...and [let us know](https://github.com/saulpw/visidata/issues/new) about yours! Advice for [making plugins](https://github.com/saulpw/visidata/blob/develop/dev/checklists/add-plugin.md).

Unfortunately, the link appears to be broken, as do most other links documenting this API.

**Comment by strazto** [comment]
~https://github.com/saulpw/visidata/blob/stable/docs/api/plugins.rst~

~It looks like this is the correct link~

https://www.visidata.org/docs/api/

**Comment by anjakefala** [comment]
Thanks! I wrote that up before the modern api page existed (it is fairly recent). I will update those links.

**Comment by anjakefala** [comment]
That will be fixed next time I update the website. =)

**Comment by strazto** [comment]
Thank you! I think I noticed this in a few places - I'm not sure if they were just .md source and the generated website, though.
