### ISSUE TITLE
[geojson] save in GeoJSON format from any sheet with lat/long columns

### ISSUE THREAD

**Issue by siriniok** [saulpw/visidata#879]
Any chance we can have a support for CSV to GeoJSON saving?

As far as I understand from the [formats](https://www.visidata.org/formats/) page, currently it's only possible to save GeoJSON from Shapefile format. Which is understandable, however it'd nice to have an ability to convert simple CSV files too.

Currently, I'm using Mapbox Studio for that, which performs it this way:

Suppose we have a CSV file with such data:
```csv
id,title,address,latitude,longitude,open_hours
1,Gapstow Bridge,"6th Avenue &, Central Park S, New York, NY 10019, United States",40.7664085,-73.9738443,10AM–6PM
2
```

Mapbox will convert it into a following GeoJSON:
```json
{
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "title": "Gapstow Bridge",
        "address": "6th Avenue &, Central Park S, New York, NY 10019, United States",
        "open_hours": "10AM–6PM"
      },
      "geometry": {
        "coordinates": [
          -73.973844,
          40.766408
        ],
        "type": "Point"
      },
      "id": "94b1a2fa93219bed314dd2ddf4504b48"
    }
  ]
}
```

As you can see, `latitude` and `longitude` are going into `geometry.coordinates` array, and every other column goes into `properties` object. I'm not sure how "id" is generated, that's probably an internal Mapbox's extension, but [GeoJSON specification](https://tools.ietf.org/html/rfc7946#section-3.2) says that

"If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number."
      
So Visidata could just use the 'id' column as a feature id.

**Comment by anjakefala** [comment]
Fun timing! @dracos just added support for this on the develop branch: https://github.com/saulpw/visidata/pull/876. 

You can pull the develop branch, and start playing with it, or wait for the next release. =) It should be out sometime this week.

**Comment by dracos** [comment]
I'm afraid my PR did not add CSV to GeoJSON support. It can only save GeoJSON or Shapefiles as GeoJSON at present, as merged. Adding a general GeoJSON export would be something further to add on top, with some way of it finding the relevant columns to use for the geometry.

**Comment by siriniok** [comment]
Yes, I had seen #876 before opening this issue, I wasn't convinced that it's gonna work for CSV to GeoJSON. Maybe I misunderstand something about the VD's architecture though.

@dracos GeoJSON specification says little on that and there are a lot of geometry types, but I'd suggest to focus on Point geometry for now, as it's the most common one and requires only a single position.

Position always has 2 or 3 elements: `longitude`, `latitude`, and `altitude` (optional).

We can use them as expected column names, and "lat", "lon", "alt" as aliases for them (they are used in the aforementioned specification for mapping 'geo' URIs).

**Comment by anjakefala** [comment]
My mistake! Re-opened this as a wishlist item.

**Comment by saulpw** [comment]
This is an interesting feature request, and I'm open to it if anyone has working code.  Kondo'd for now.
