### ISSUE TITLE
Add accepted csv dialects to manpage/docs

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#88]
From comment by @wavexx on TabViewer/tabview#152:

> You should perhaps mention what "dialect" accepts in the man page, since
> it's already so neatly documented. As python developers we might know,
> but others will definitely not.
> 
> The list of dialects is not listed nearby the "-f" flag, just a dumb
> list or a "See SUPPORTED SOURCES" at the bottom would be nice.

Adding a list of dialects supported by Python 3.4 to the SUPPORTED SOURCES section (with "see SS" by the --dialect and --filetype options, as suggested) is probably the right way to go.

**Comment by anjakefala** [comment]
Doc addition included into [VisiData v0.98.1](https://github.com/saulpw/visidata/tree/v0.98.1).

**Comment by aborruso** [comment]
Hi, where can I find the specs of excel-tab, unix, and excel dialects?

For "unix" I have found "The unix_dialect class defines the usual properties of a CSV file generated on UNIX systems, i.e. using '\n' as line terminator and quoting all fields. It is registered with the dialect name 'unix'". It's not complete, but it's something.

Thank you

**Comment by saulpw** [comment]
Hi @aborruso, it seems like you've found the right Python documentation for the dialects.  Unfortunately I don't have any better information since we're just passing that parameter along to the Python csv parser.  If you find a more thorough explanation of the dialects, please let us know and we'll include it in our docs too.
