### ISSUE TITLE
can't copy a column

### ISSUE THREAD

**Issue by teto** [saulpw/visidata#882]
**Small description**
I am trying to copy the column "datafin" from client2.txt to tokens.txt (same number of rows, tokens.txt misses some columns from client2.txt).
Rename the file to csv and set the delimiter to `|`.
[client2.txt](https://github.com/saulpw/visidata/files/5898667/client2.txt)
[tokens.txt](https://github.com/saulpw/visidata/files/5898983/tokens.txt)

I do as advised on IRC and it works for the other columns but not for columns that lack a cell in the first row (or so it seems)
"gs gzy to copy the values, the go to the other sheet, za to create a column, gs gzp to paste"

**Additional context**
I've been using a recent one e65c076c644a9577022c985dee5b447650cddd72

**Comment by anjakefala** [comment]
Waiting on further information to aid with reproduction.

**Comment by teto** [comment]
my bad, quite busy but will do it sometime this week

**Comment by anjakefala** [comment]
Closing for now, because of "unable to reproduce"! @teto. we can re-open it when you have time to help out with that. =)

**Comment by teto** [comment]
sry I couldnt follow up. Will reopen once I get back to it.
