### ISSUE TITLE
[setcol-fill] setcol-fill has unexpected behavior

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#884]
**Small description**
The setcol-fill command will sometimes fill cells that are not selected

**Expected result**
Only selected cells are filled

**Actual result with screenshot**
I only selected some rows, and added some rows. The setcol-fill updated cells in rows not selected. The behavior I see at times is not correct.  Many times when selected rows are not contiguous.

https://asciinema.org/a/iApwtvYzhzU254QgnVCJ0PHx5

**Steps to reproduce with sample data and a .vd**

```json
{"a":1,"b":[0,1],"c":null}
{"a":2,"b":[0,1,2],"c":null}
{"a":3,"b":[0,1,2,3],"c":null}
{"a":4,"b":[0,1,2,3,4],"c":null}
{"a":5,"b":[0,1,2,3,4,5],"c":null}
```

```
sheet	col	row	longname	input	keystrokes	comment
global		filetype	set-option	json		
			open-file	-	o	
-	c	0	edit-cell	x	e	edit contents of current cell
-		0	select-row		s	select current row
-		0	add-row		a	append a blank row
-		1	add-row		a	append a blank row
-		2	add-row		a	append a blank row
-		3	select-row		s	select current row
-	c		setcol-fill		f	fills null cells in selected rows of current column with contents of non-null cells up the current column
-			cmdlog-sheet		D	open current sheet's CommandLog with all other loose ends removed; includes commands from parent sheets
```

**Additional context**
Please include the version of VisiData. Latest develop version.

**Comment by anjakefala** [comment]
Thanks for such a good example! I found 2 bugs intertwined in this, both which should be fixed now.

One where it was using the row content, not row identity, to identify which rows to fill. This meant that since two blank rows are identical, if one was selected, both would be filled.

Another, where rows were being filled with the most recent preceding value, even if that value was None.

**Comment by frosencrantz** [comment]
Awesome!  Thanks @anjakefala !  Glad that was a useful example.  I hit the issue, and it took a little while to figure out how to reproduce it reliably to demonstrate.  Your explanation makes it clear why.

One odd thing about the setcol-fill column is that it doesn't apply by default to the whole column when there is no selection.

**Comment by anjakefala** [comment]
Good point @frosencrantz! `setcol-fill` now uses `someSelectedRows`. Set `options.some_selected_rows` to True, and commands with `someSelectedRows` will use all rows, if none are selected.

**Comment by frosencrantz** [comment]
TIL about the `someSelectedRows` option.  That's great. Thanks again, Anja!
