### ISSUE TITLE
Underline bottom of rows when using visibility-sheet

### ISSUE THREAD

**Issue by fffergal** [saulpw/visidata#887]
Recently I've been working with some data where it is really useful to wrap long cells so I can read them all. It works great, but separating the rows can be more difficult. How about a feature where the bottom of the row is underlined? It could be similar to the color_bottom_hdr option. Thanks for reading, I understand most featured are closed for the wishlist.

**Comment by geekscrapy** [comment]
I have had this issue before, but didn't really realise until you said! I agree, that would make a lot of sense.

**Comment by frosencrantz** [comment]
I agree this seems like it could be useful.

I will mention a workaround that I've used to make multiline rows clearer.  There are options for `disp_row_top`, `disp_row_mid`, `disp_row_bottom`, where you can use the unicode box drawing characters to make a bracket. For example:
╔
║
╚

**Comment by saulpw** [comment]
I can see how this would be useful too.  I think @frosencrantz's workaround is a pretty good one for now, though, and we have bigger issues with multi-line rows like #916.  Kondo'ed for now.
