### ISSUE TITLE
Add option to prevent recurse from traversing fs boundaries. 

### ISSUE THREAD

**Issue by roosemberth** [saulpw/visidata#888]
Hi o/

I use btrfs and [snapper] to create hourly snapshots of different parts of my filesystem. These snapshots are created as read-only btrfs subvolumes. The snapshots are themselves btrfs subvolumes stored inside btrfs subvolume (e.g. my home directory); as a consequence of my layout that means that I have multiple copies of the same files accesible from a directory (e.g. my home directory) at different points in times but only one is rw (the one one the current btrfs subvolume). 

As a user, I'd like to have an option to prevent `vd . --dir-recurse` from traversing filesystem boundaries, just like the `-mount` option of `find(1)`

```-mount Don't descend directories on other filesystems.```

In my workflow, often enough I find myself running `find . -mount | vidir` to do bulk editing on filenames and then some shell-foo to modify other actions; I would like to use visidata instead :)

Cheers!

[snapper]: http://snapper.io/

**Comment by frosencrantz** [comment]
Hi @roosemberth !

You can already use VisiData for this.  There is a file format called `fdir`, as input it takes one filename per line, just as `find` returns. 

```
find .  -my-find-query | vd -f fdir
locate '*.csv' '*.json  | vd -f fdir
```

**Comment by roosemberth** [comment]
> You can already use VisiData for this. There is a file format called fdir, as input it takes one filename per line, just as find returns.

Nice! I still think it would be a good idea to add the flag, but I can use this as a workaround, thanks!

Edit: I think this issue may be closed if the maintainers decide this to be an unnecessary feature.

**Comment by saulpw** [comment]
Hi @roosemberth, it's a good idea; we could have `dir_recurse` be either `''` (default; do not recurse) or `'local'` (stay on filesystem) or `'all'` (cross filesystems).  But os.walk() doesn't have an option to do this, so we'd probably have to do something like call out to `find -mount` anyway.  If someone finds a clean and portable way to do this in Python, we can revisit, but for now, we'll consider it resolved with the `fdir` filetype.
