### ISSUE TITLE
[chooser] add prompt string to chooseOne, chooseMany like vd.input(prompt ...

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#889]
It would be great to be able to use `choose*` with a prompt (and the other args that `input` takes), especially since `fancychooser` has been turned off by default

**Comment by geekscrapy** [comment]
Use case: I have a plugin which needs to run against a column and takes multiple inputs. without cycling through the available options there is no way for the user to tell what the options are for. with fancychooser this was hinted at with the 'desc' column. Currently I need the user to input two lots of integers, but without looking at the code they dont know what the input is for.

I appreciate I could use vd.input, and will do, if this is the working solution. It's just _extremely_ convenient to use the `choose*` funcs.

**Comment by saulpw** [comment]
Thanks for the request, @geekscrapy.  This issue has been rolled up into #1027 and we'll address it there.
