### ISSUE TITLE
[question] How to copy a cell and use it in an expression? 

### ISSUE THREAD

**Issue by pyrrhull** [saulpw/visidata#890]
Would be great if it was possible to copy/yank a value from a cell. This can be usable for calculations as it is not possible to reference a single cell's value in an expression if i am not mistaken.

**Comment by saulpw** [comment]
Use `zy` to copy from a cell to the internal clipboard, and `Ctrl+Y` at any edit prompt to paste into it.

**Comment by anjakefala** [comment]
You can! =)

`zy` copies to VisiData's clipboard, and `zY` copies to the system clipboard, using the configured method.

`z=` allows the referencing of a single cell in the current row, through its column name. One catch with it is that it will modify the current cell with the output of the expression. One current workaround is to create a blank column to do the computation in.

**Comment by pyrrhull** [comment]
You're awesome guys, that's great! I was glancing at the quickreference before, but i think it is not obvious to see that zy aims at a cell. Btw, why is ^Y mapped to paste, isn't that counterintuitive?
Anyways, thanks for the great work you are doing!

**Comment by saulpw** [comment]
What would be a better mapping for paste, do you think?

**Comment by pyrrhull** [comment]
something like ^P (or maybe ^V) for paste. I mean y is used for yank (copy) pretty much anywhere else, also in the quickreference.
