### ISSUE TITLE
[2.2] ... appears after using zh/l, even at offset 0

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#891]
**Small description**
After using `zh/l` to show additional parts of the cell, then using `zh` to get back to offset `0`, the `...` still appears to the left. If you use `gzh`, the `...` disappears.

**Expected result**
when at offset `0`, `...` disappears.

**Steps to reproduce with sample data and a .vd**
Get a cell with long lines, use `zh/l` a few times, then use `zh` to get back to offset `0`.

**Additional context**
If you use gzh, the `...` disappear

**Comment by saulpw** [comment]
I can't reproduce this, @geekscrapy.  Do you still see this with v2.3?

**Comment by geekscrapy** [comment]
Hey! Seems to have been fixed 👍  thanks!
