### ISSUE TITLE
[vds format] Add a way to apply metadata only vds file when reading a data file.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#892]
See  https://github.com/saulpw/visidata/discussions/886

I typically run the same queries, where the columns are stable, but the data (rows,cells) are different every time.
It would be useful if I could optionally specify to `vd` column metadata in a separate file rather than bundled with the data.  Currently vds files bundle both column metadata and the data.

There is a workaround.  It is possible to combine the metadata and the data before starting `vd`.  But this might require converting the data into the JSON format used for the `vds` format.  Also, for formats like SQLite, it would require performing the query outside of `vd`.

**Comment by saulpw** [comment]
Sounds like we want a way to save the column setup for a given sheet, and apply that setup to another sheet.  Being able to apply a .vds "metadata-only" file is one way we could do that. There are some design challenges here:

- is this a special save mode/filetype?
- do we apply based on column position or name?  what attributes get applied?
- can we apply one to multiple sheets?  from different sources?  by name or position or schema?

Anyway it doesn't appear like I'm going to be able to put the effort into this soon, so Kondo'd for now.
