### ISSUE TITLE
[delete] do not copy deleted values to clipboard

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#895]
**Small description**
I went to copy a value from one cell using `zy` (cell 1), move to another cell to delete it's value with `zd` (cell 2), then paste my value into a third cell with `zp` (cell 3).

**Expected result**
The value from cell 1 is pasted into cell 3

**Actual result**
The value from cell 2 is pasted into cell 3

**Comment by geekscrapy** [comment]
Hmm, I see this is probably intentional so you can go ahead and close this out if required. However, it is a little confusing

**Comment by saulpw** [comment]
You don't have to delete the value first before pasting.   The main reason the `d` set of commands copies to the clipboard, is that they're like the "cut" of cut/copy/paste.  But I agree, this is confusing, and was just thinking about changing it the other night. So unless anyone has any objections, let's remove the copy-ness for the next version.

**Comment by geekscrapy** [comment]
I appreciate that I didn't need to delete before pasting, it was just something I did on my way to the paste 😁

I just looked up cut in vi, and now I see why `d` is a cut thing 👍

**Comment by saulpw** [comment]
The `delete-*` commands now do not alter the clipboard.  The previous version of the commands have been renamed to `cut-*` and deprecated.  Bind to those `cut-` commands for the previous behavior, and comment here if you think they should be undeprecated (i.e. not removed in the future).

**Comment by anjakefala** [comment]
> comment here if you think they should be undeprecated (i.e. not removed in the future).

I think it is a cool idea to leave them as `cut-*`!

**Comment by ghost** [comment]
I like the cut commands! My vim muscle memory was happy.

**Comment by saulpw** [comment]
@davidwales does that mean that you've rebound them in your visidatarc and would prefer they weren't deprecated after all?

**Comment by ghost** [comment]
I haven't got the latest version yet, so I still have the old behaviour at the moment. I was just reading the changelog. But it would be nice to have both behaviours available. (I am aware that one of the reasons that Vim can get away with this behaviour is that it has multiple clipboards, so your current clipboard value is not lost when you delete.)

**Comment by ghost** [comment]
On further thought, would it be possible to bind the cut behaviour to `x` (`gx`, `zx`, etc) by default?

So you would have the following:

`y`: copy but don't delete
`d`: delete but don't copy
`x`: copy and delete

I've looked at the command help sheet, and it looks like `x` is currently only used in the CommandLog sheet to replay commands.

For bonus points, perhaps we could also have `X`: copy to system clipboard and delete, to mirror the behaviour of `Y`. (I don't think `X` is used at all currently.)

I have added the following to my `.visidatarc` for anyone who wants to try it out:

``` python
bindkey('zx', 'cut-cell')
bindkey('gzx', 'cut-cells')
bindkey('x', 'cut-row')
bindkey('gx', 'cut-selected')
```

**Comment by saulpw** [comment]
Binding `x` to `cut-*` by default is reasonable, @davidwales.  I think we'll keep `Shift+X` unbound for now, though, as I don't think syscopy-and-delete (syscut?) is all that useful and we'd only be doing it for symmetry. (`x` and then `p` can be used to 'move' a row; I have a hard time imagining a workflow that would use `Shift+X`.)
