### ISSUE TITLE
[sheets source col] Paths are not sortable.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#897]
**Small description**
Trying to sort the `source` column in the Sheets table reports a traceback.

**Expected result**
The rows are sorted by the `source` column.

**Actual result with screenshot**
https://asciinema.org/a/29PPqbhrQOvBzMKeKlCBTkety
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/visidata/basesheet.py", line 136, in execCommand
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "sort-desc", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/visidata/sort.py", line 28, in orderBy
    sheet.sort()
  File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 983, in sort
    self.rows[1:] = sorted(self.rows[1:], key=self.sortkey)
  File "/usr/lib/python3.9/site-packages/visidata/sort.py", line 38, in __lt__
    return other.obj < self.obj
TypeError: '<' not supported between instances of 'Path' and 'Path'
```

**Steps to reproduce with sample data and a .vd**
Open several data files go to the Sheets sheet, and try sorting by the `source` column.

**Additional context**
Please include the version of VisiData, latest develop version.

**Comment by anjakefala** [comment]
Thanks @frosencrantz!

It was a bug in visidata.Path's `__lt__`. It should now be fixed on develop.

**Comment by frosencrantz** [comment]
Thank you, Anja!  That works great!

I found later there might be an issue with non-Path sources, too.
