### ISSUE TITLE
[SuspendCurses] Suspending(ctrl-Z)/resuming(fg) while vd is in SuspendCurses has issues

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#899]
**Small description**
If vd has called SuspendCurses to start another program (such as for ^H for the man apge, or ^O for the editor) resuming causes the vd and the other program to compete for input/output.

**Expected result**
fg resumes into the program launched by vd, allowing the user to quit that program before returning to vd.

**Actual result with screenshot**
Sorry no screenshot it causes all sort of issues to record.

**Steps to reproduce with sample data and a .vd**
Launch vd hit '^H'.  While still viewing man page, hit '^Z' to suspend.  Then resume.
I've gotten different odd results, vd is then running, but the other program is too.
I think this is an issue with SuspendCurses handling signals and subprocesses.
I think this will be rewarding to fix like 
https://github.com/saulpw/visidata/issues/851

**Additional context**

Please include the version of VisiData. using latest version of develop

**Comment by saulpw** [comment]
Hi @frosencrantz, thanks for the solid repro.  [This StackOverflow question](https://stackoverflow.com/questions/31440392/curses-wrapper-messing-up-terminal-after-background-foreground-sequence) appears very similar to this issue, and indeed the SIGTSTP workaround seems to fix the issue.

**Comment by frosencrantz** [comment]
Awesome!  Thank you, Saul! I haven't tested it much, but it does appear to work.
