### ISSUE TITLE
[sqlite] remove precount of rows for faster and incremental loading

### ISSUE THREAD

**Issue by fleimgruber** [saulpw/visidata#900]
When exploring big sqlite tables (millions of rows), the performance is really bad as visidata apparently eagerly loads all rows from the table.

Is there a way to lazily limit the number of initially fetched rows (e.g. when only a look at example data is required and no calc over whole columns)?

Thinking further, the number of rows to be initially fetched in "lazy mode" would be fetched on demand if e.g. scrolling at the bottom of the initially fetched rows or after and explicit "fetch more rows" command.

WDYT?

**Comment by geekscrapy** [comment]
In terms of your first point, you can press ctrl+c to stop the loading process. If you would like more data, use ctrl+r to reload the sheet and begin loading the data again

**Comment by geekscrapy** [comment]
In regards to your second point, I have been looking at this for some data sources I have to use vd with, which include calls to APIs (but could also be regarded like loading SQL data)

**Comment by fleimgruber** [comment]
Thanks for checking back.

> In terms of your first point, you can press ctrl+c to stop the loading process. If you would like more data, use ctrl+r to reload the sheet and begin loading the data again

The loading process shows "loading..." for a few minutes, before any data is shown in the table (and after which I would do the ctrl+c), so this does not work smoothly / intended, at least for sqlite.

**Comment by fleimgruber** [comment]
> In regards to your second point, I have been looking at this for some data sources I have to use vd with, which include calls to APIs (but could also be regarded like loading SQL data)

Yes, I think this would be a general feature handy for any generator-like sources to load rows into visidata on demand.

**Comment by fleimgruber** [comment]
> The loading process shows "loading..." for a few minutes, before any data is shown in the table (and after which I would do the ctrl+c), so this does not work smoothly / intended, at least for sqlite.

Quick follow-up: If after those minutes of initial wait time (when the "xxx rows" counter starts to count up), pressing ctrl+c a few times shows only "no active threads on this sheet" in the messages line, but the process (hogging up CPU) continues. This might be related to using visidata on Windows and conda, see also: https://github.com/conda-forge/visidata-feedstock/issues/15.

**Comment by fleimgruber** [comment]
Seeing the same thing when using WSL and visidata run from a Bash inside of it.

**Comment by saulpw** [comment]
Hi @fleimgruber, the sqlite loader shouldn't take minutes of wait time initially before it starts up.  What version of VisiData are you using?

**Comment by fleimgruber** [comment]
Hi @saulpw, thanks for checking back. I am using visidata 2.2.1 from PyPI.

Also, I should be more specific: the minutes of initial wait time (bottom right corner says "loading..." during that time) are with the command `SELECT COUNT(*) FROM "sqlite_master"` shown in visidata bottom line. The sqlite file in question has 14 GB and > 6_000_000 rows.

**Comment by saulpw** [comment]
Okay, there seems to be no way to get the number of rows in a sqlite table without doing a full table scan, which is clearly not a good strategy (and the point was to provide for a progress meter anyway).  So that first query has been removed as of 159dd908113d8d16151ab943cb58f83d00d5afb8.  Now Sqlite loads should be ~2x as fast, and incremental to boot.  Use `Ctrl+C` as mentioned above if you don't want to load all the rows.

"Lazy-load" will be a much bigger effort, which will need an architecture shift for dealing with big data sources in general (including other SQL DBs).  That's more of a roadmap item than a bug or even a feature request.
