### ISSUE TITLE
show current row and column number on the status bar

### ISSUE THREAD

**Issue by haluk** [saulpw/visidata#904]
Is it possible to see the current row and column number on the status bar? I checked the video tutorials but couldn't see it in there too.

**Comment by anjakefala** [comment]
Yup! The command is `Ctrl+G`.

I encourage you to peruse through the man page for a complete command reference (`Ctrl+H`) and [this cheat sheet](https://jsvine.github.io/visidata-cheat-sheet/en/) for a smaller, curated list of commands.

**Comment by geekscrapy** [comment]
I use the following in my .rc file. I find it more convenient as it's always present (I look at it way more than I thought!).

It looks like this in the right status bar:

![image](https://user-images.githubusercontent.com/11225502/108317660-0d015d80-71d8-11eb-8a2d-ab942c2372fb.png)

R: current row / total rows [number of selected rows] C: current column index / current number of visible columns

`Sheet.class_options.disp_rstatus_fmt = ' R:{sheet.cursorRowIndex}/{sheet.nRows}[{sheet.nSelectedRows}] C:{sheet.cursorVisibleColIndex}/{sheet.nVisibleCols} {sheet.rowtype} '`

**Comment by saulpw** [comment]
I have this, as it does seem useful to know at a glance how many rows are selected:

`options.disp_rstatus_fmt = '{sheet.nRows:9d} {sheet.rowtype} {sheet.options.disp_selected_note}{sheet.nSelectedRows}'`

**Comment by haluk** [comment]
> I use the following in my .rc file. I find it more convenient as it's always present (I look at it way more than I thought!).
> 
> It looks like this in the right status bar:
> 
> ![image](https://user-images.githubusercontent.com/11225502/108317660-0d015d80-71d8-11eb-8a2d-ab942c2372fb.png)
> 
> R: current row / total rows [number of selected rows] C: current column index / current number of visible columns
> 
> `Sheet.class_options.disp_rstatus_fmt = ' R:{sheet.cursorRowIndex}/{sheet.nRows}[{sheet.nSelectedRows}] C:{sheet.cursorVisibleColIndex}/{sheet.nVisibleCols} {sheet.rowtype} '`

This is great!

**Comment by haluk** [comment]
> I use the following in my .rc file. I find it more convenient as it's always present (I look at it way more than I thought!).
> 
> It looks like this in the right status bar:
> 
> ![image](https://user-images.githubusercontent.com/11225502/108317660-0d015d80-71d8-11eb-8a2d-ab942c2372fb.png)
> 
> R: current row / total rows [number of selected rows] C: current column index / current number of visible columns
> 
> `Sheet.class_options.disp_rstatus_fmt = ' R:{sheet.cursorRowIndex}/{sheet.nRows}[{sheet.nSelectedRows}] C:{sheet.cursorVisibleColIndex}/{sheet.nVisibleCols} {sheet.rowtype} '`

I tried ' R:{sheet.cursorRowIndex+1}/{sheet.nRows}' for 1 based indexing but it didn't work. Isn't this f-string?

**Comment by saulpw** [comment]
For this, you can add a custom property:

```
@Sheet.property
def cursorRowIndex1(sheet):
    return sheet.cursorRowIndex+1
```

and then you can use `sheet.cursorRowIndex1` in your status strings.
