### ISSUE TITLE
[Chooser] Multiple ChooseX use case example

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#905]
_I appreciate that there was talk of fancy chooser becoming more of a modal (which sounds great!)._

I wanted to just describe one issue I have at the moment with FancyChooser that would hopefully be considered when looking at the new fancychooser modal.

I have a plugin that needs selectable user inputs (from a few lists). FancyChooser works well with this (although being able to provide a name for the choice sheet would be great - the option 'keys' and 'description' column aren't always that descriptive), however I have come across a GUI issue when using consecutive chooseX options.

Using the small example below, I want the user to select a few options

```
@Sheet.api
def x(s):
    vd.chooseOne([{'key':'opt1'}, {'key':'opt2'}])
    vd.chooseOne([{'key':'opt1'}, {'key':'opt2'}])
Sheet.addCommand(None, 'x', 'x()')
```

However when using FancyChooser to see these options (and more critically the descriptions, as the current `'choose any of %d options (Ctrl+X for menu)'` isn't that helpful, the following occurs:

First option popup - fine
![image](https://user-images.githubusercontent.com/11225502/108337351-78eec080-71ee-11eb-8cc4-53ffd59c1a55.png)

Second option popup - the previous fancychooser sheet has not disappeared. It goes once the user presses ^X though, but it's not always obvious that the chooser string has appeared
![image](https://user-images.githubusercontent.com/11225502/108337409-84da8280-71ee-11eb-83c1-28a5438eec73.png)

**Comment by saulpw** [comment]
Hi @geekscrapy, thanks for the request.  The modal chooser should allow for multiple consecutive choices, though be aware that only one of the choices can be saved to the cmdlog (for redo or replay).

Rolled into #1027.
