### ISSUE TITLE
Locale-aware sort for text columns

### ISSUE THREAD

**Issue by jirir** [saulpw/visidata#906]
**Sorting non English characters produces wrong result.**

For example – sorting a dataset containing Czech characters according the CHARACTER column:

|CHARACTER  |B   |
|-----------|---:|
|a          |1   |
|á          |2   |
|b          |3   |
|c          |4   |
|č          |5   |
|d          |6   |
|ď          |7   |
|e          |8   |
|é          |9   |
|ě          |10  |
|f          |11  |
|g          |12  |
|h          |13  |
|ch         |14  |
|i          |15  |
|í          |16  |

produces incorrect result:

|CHARACTER  |B   |
|-----------|---:|
|a          |1   |
|b          |3   |
|c          |4   |
|ch         |14  |
|d          |6   |
|e          |8   |
|f          |11  |
|g          |12  |
|h          |13  |
|i          |15  |
|á          |2   |
|é          |9   |
|í          |16  |
|č          |5   |
|ď          |7   |
|ě          |10  |

**Expected result**

The correct result is in the following table. Notice the extra peculiar `ch` which in the Czech alphabet is a _single_ character after the `h` character.

|CHARACTER  |B   |
|-----------|---:|
|a          |1   |
|á          |2   |
|b          |3   |
|c          |4   |
|č          |5   |
|d          |6   |
|ď          |7   |
|e          |8   |
|é          |9   |
|ě          |10  |
|f          |11  |
|g          |12  |
|h          |13  |
|ch         |14  |
|i          |15  |
|í          |16  |

**Comment by saulpw** [comment]
Hi @jirir, thanks for the report.  I did a bit of research and it looks like there are a few ways to do it in Python but none of them seem all that great.  Do you have an idea of how it can be done in Python?

**Comment by saulpw** [comment]
If anyone has working Python code for the correct way to sort text according to locale settings, please share.  Kondo'ed until then.
