### ISSUE TITLE
[Docs] Provide explicit documentation about the Python scope for expressions

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#907]
Perhaps I have missed it...
But I can't seem to find any explicit documentation of the Python scope for expressions.

I have figured out by trial and error that something like the following has been imported

    from datetime import date

However, it would be nice to have a section in the docs dedicated to Python expressions, and what modules are imported to what namespaces, etc.

It would also be nice to provide some examples for selecting by date.

e.g. given the following table you can select all the rows between November and January with the expression below (assuming you have told `visidata` that the column is a date column):

|   ID | Date       |
|------|------------|
|    1 | 2020-11-02 |
|    2 | 2020-11-13 |
|    3 | 2021-01-07 |
|    4 | 2021-02-05 |
|    5 | 2021-05-03 |

    z| date(2020, 11, 1) <= Date <= date(2021, 1, 31)

**Comment by geekscrapy** [comment]
In the past I've found a lot out by using pythons `dir()`. Use this as a columns `expr` and you should be able to figure out quite a bit

**Comment by frosencrantz** [comment]
On my wishlist: What if VisiData could provide automatic imports so you could reference any installed Python module?

https://github.com/saulpw/visidata/issues/750

**Comment by saulpw** [comment]
Hi @davidwales, there's some information in the [API docs for Commands](https://www.visidata.org/docs/api/commands.html#command-context):

> exec() looks up symbols in this order:
> -    the current sheet
> -    the vd object
> -    the visidata module (see addGlobals() and getGlobals())

We can expand on the third item in the docs, as VisiData tries to be maximally helpful in terms of what it includes in its "globals":

- anything from .visidatarc is automatically added to globals
- anything a plugin or module adds via `addGlobals()`
- anything exported from visidata internal module (either explicitly with `__all__` or implicitly)
- everything from the `builtins` and `math` Python stdlib modules

I don't think it's reasonable to call out every available symbol that's available, especially because new ones may be added at any time and I don't want to maintain the list.  @geekscrapy's idea to browse with `dir()` is a pretty good way to explore them all.

**Comment by ghost** [comment]
Thanks @saulpw, I think `getGlobals` is what I was looking for!

For quick reference, the most direct way to get the list of globals is:

    ^X
    getGlobals()

For extra credit, you can follow this up with:

    =value.__doc__

This adds a column with the docstring of the functions!!!

|key                 |value                                                  |value\.\_\_doc\_\_                                                                                                                                                                                                                                                                                                             |
|--------------------|-------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|date                |<class 'visidata\.\_types\.date'\>                     |datetime wrapper, constructed from time\_t or from str with dateutil\.parse                                                                                                                                                                                                                                                    |
|datedelta           |<class 'visidata\.\_types\.datedelta'\>                |                                                                                                                                                                                                                                                                                                                               |
|datetime            |<module 'datetime' from '/usr/lib/python3\.8/datetime\.py'\>|Fast implementation of the datetime type\.                                                                                                                                                                                                                                                                                     |
|dateutil            |<module 'dateutil' from '/usr/lib/python3/dist\-packages/dateutil/\_\_init\_\_\.py'\>|                                                                                                                                                                                                                                                                                                                               |

(`^X dir()` will also give you the list of functions, but you can't easily get the docstring.)
