### ISSUE TITLE
How to decompose a wide table into a long table

### ISSUE THREAD

**Issue by reckoner** [saulpw/visidata#910]
When doing a groupby on a single categorical variable and on a single numerical variable, the groups are presented as a diagonal matrix, which is hard to look through when the diagonal is very long, which results in a very wide matrix. Is there a way to extract the diagonal entries of the result of the groupby into a single column?

Thanks!

**Comment by saulpw** [comment]
Hi @reckoner, if I understand you correctly, try melting the resulting sheet with `Shift+M`.
