### ISSUE TITLE
[visibility-sheet] Overflow of rows when using wordwrap does not scroll

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#916]
_Firstly, I apologise for the terrible title :D_

**Small description**
When using wordwrap (`visibility-sheet`/`v`), visible rows != number of rows on the page.

If I have the ability to show 100 rows normally without wordwrap and then use `visibility-sheet` which then means only 5 of those rows are visibly shown, when I scroll to the 6th row (that is off screen) the view does not change (even if I try `zz` for example) and I can only ever see 5 rows, but I am able to actually navigate to lower rows (> 5).

Also, when you move the cursor off screen the screen flashes a number of times (I think this is linked to the number of rows shown on screen, unsure).

**Expected result**
If the screen is filled with 5 rows (due to `visibility-sheet`), when I navigate to the 6th (off screen row) this row pops to the pop of the screen visually.

**Actual result with screenshot**
Without `visibility-sheet`, row 36 selected
![image](https://user-images.githubusercontent.com/11225502/109774372-b2c1bd00-7c19-11eb-9501-8818a6c3bcb8.png)

With `visibility-sheet`, row 11 selected
![image](https://user-images.githubusercontent.com/11225502/109774410-bce3bb80-7c19-11eb-83b0-603775cf6ee8.png)

With `visibility-sheet`, row 13 selected (but not shown)
![image](https://user-images.githubusercontent.com/11225502/109774584-f4526800-7c19-11eb-8c1d-9076ea5b03ca.png)

**Steps to reproduce with sample data and a .vd**
(for ease of reproducibility, use a small window)
1. vd https://raw.githubusercontent.com/linuxacademy/content-elastic-log-samples/master/access.log
2. Apply `visibility-sheet`
3. Scroll to the lower rows

**Comment by saulpw** [comment]
Yeah, I've known about this one.  To me this is the worst bug I know about in VisiData; it almost stopped us from shipping 2.0.   I'd love to fix this but it's a hairy one.  Thanks for logging it, sorry it's there.

**Comment by geekscrapy** [comment]
I did find a slight way around this by using my scroll-fix plugin (https://github.com/geekscrapy/visidata_plugins/blob/master/scroll_fix.py)

Just lock to a row which is at least a few rows above the bottom row and you should be good. A caveat to the workaround (🤨), this only works with `go-up` and `go-down`

**Comment by saulpw** [comment]
I changed how multiline rows are implemented; now they are always the same height for all rows (the height of the tallest visible column).  This makes everything a lot simpler and removes this bug.
