### ISSUE TITLE
How to have pandas / NumPy functions available for analysis

### ISSUE THREAD

**Issue by dufferzafar** [saulpw/visidata#917]
The  `=` key allows us to add a new column based on a python expression. It is tremendously useful!

But, usually I find myself requiring pandas / numpy functions to perform some analysis.

Would it be possible to load pandas / numpy or some other library (say `datetime` for parsing dates) so that they become available in the main context.

**Comment by dufferzafar** [comment]
For eg, right now i need to do something like `new column expr=datetime.fromtimestamp(col_date)`

**Comment by saulpw** [comment]
You can put something like this in your .visidatarc:

```
from pandas import *
```

All functions defined in the .visidatarc are exposed in the expression scope.

Also, you can press `@` to `type-date` a timestamp column and it will convert to the proper date.
