### ISSUE TITLE
Clarify the difference between float and currency format types

### ISSUE THREAD

**Issue by pigmonkey** [saulpw/visidata#918]
Is there a difference in how Visidata treats values formatted as currency (by hitting `$`) vs a float (by hitting `%`)?

I frequently find myself using Visidata to load files where some of the columns contain numerical values and some extraneous characters. For example, consider the following TSV (pretend this uses tab separators instead of the spaces that make it look good on GitHub):

    item    percent    quantity    cost    weight
    foo     32%        2,320       $82.10  1 kg
    bar     81.1%      9,123,913   $0.31   2.312 kg

The `%` in the second column, the `,` in the third column, the `$` in the fourth column, and the ` kg` in the fifth column are all garbage characters that I don't care about. I want Visidata to treat the percent, quantity, weight and cost columns as floats, allowing me to sort, sum, etc. Effectively, I want Visidata to act as if the original input was this:

    item    percent    quantity    cost    weight
    foo     32         2320        82.10   1
    bar     81.1       9123913     0.31    2.312

If I use `$` to format those 4 columns as a currency, Visidata does exactly what I want. It throws away all the characters that are not a decimal or a number and treats the remainder as a float.

If I use `%` to format those columns as a float, Visidata marks each cell as having an error since they all contain extra characters like `%`, `,`, `$`, or ` kg`.

In an example like this, where I've confirmed that all the cells in a column use the same unit and I really do not care about the non-numerical characters, is there any reason not to use the currency format even on the 3 columns that do not represent dollar values? After formatting, does Visidata treat values formatted as a currency any different than floats? Or is the only different between the two that the currency format will ignore unexpected values while it is being applied?

Whatever the answer is, my feature request is to have the man page clarify the difference between these two format types!

**Comment by saulpw** [comment]
Hi @pigmonkey, great question. The `currency` type is really just a "dirty float" as you describe.  All it does is filter out the non-float chars and then parse the remainder as a float, so your use case is a good one.  In the future, the stripped chars at the beginning and/or end of the string may be preserved and used to determine the units, possibly with unit analysis or conversion, but that's all just a dream at the moment.  The only reason not to use the `currency` type is performance (it's quite a bit slower than native parsing with `float`), or if any non-float chars *should* indicate an error.

Note that there is also a `floatsi` type (`z%`) which can handle SI magnitudes (k/M/G etc).

We may overhaul the manpage at some point, and type details would be good to include for sure. I'll defer to @anjakefala if she wants to squeeze it in before then.

**Comment by pigmonkey** [comment]
Ok, thanks for confirming my suspicions. I'll carry on using the types as I have been.

I'll leave this issue open in case it is decided that this is worth clarifying in the man page. If it isn't, I'm fine with it being closed.
