### ISSUE TITLE
set all columns to numeric except first N

### ISSUE THREAD

**Issue by Beliavsky** [saulpw/visidata#920]
I have a data file that looks like

date,PX_HIGH,PX_LAST,PX_LOW,PX_OPEN
2015-01-02,20.14,17.79,17.05,17.76
2015-01-05,21.29,19.92,19.19,19.19
2015-01-06,22.9,21.12,19.52,20.33
2015-01-07,20.72,19.31,19.04,20.15

I read about how to specify the column types individually, but is there a way, ideally a command, that tells visidata that all columns are numeric except the first N? For this file N=1.

**Comment by anjakefala** [comment]
I would go into the **Columns Sheet** with `Shift+C`, scroll down to the the N+1th row, which references that respective column, and type `gzs`. This will select all rows from cursor to bottom. Then type `g%`, this will set all selected rows (referencing their source columns) to float numeric.

**Comment by saulpw** [comment]
Definitely the Columns Sheet, but probably easier than remembering `gzs` is to just use `gs` to select every column and then `u` to unselect the ones that aren't numeric (and then `g%` as mentioned).
