### ISSUE TITLE
TypeError when Excel column names are datetimes

### ISSUE THREAD

**Issue by ghost** [saulpw/visidata#921]
**Small description**
If you try to load a file where the column name is an Excel datetime, you get a `TypeError`, and the sheet won't load.

**Expected result**
The column would be coerced to a string, and the table would load.

**Actual result with screenshot**
Screenshot:
![image](https://user-images.githubusercontent.com/55477181/110422269-24ef4180-80f3-11eb-888a-4f739fa737d6.png)

Stack trace:
``` python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/visidata/sheets.py", line 921, in reload
    self.setCols(list(self.optlines(itsource, 'header')))
  File "/usr/lib/python3/dist-packages/visidata/sheets.py", line 888, in setCols
    self.addColumn(ColumnItem(''.join(colnamelines), i))
TypeError: sequence item 0: expected str instance, datetime.datetime found
```

**Steps to reproduce with sample data and a .vd**
Commandlog (added .txt extension to appease GitHub...):
[Test.vd.txt](https://github.com/saulpw/visidata/files/6106029/Test.vd.txt)

Sample file:
[Test.xlsx](https://github.com/saulpw/visidata/files/6106031/Test.xlsx)

**Additional context**
VisiData version: v2.2.1

**Comment by saulpw** [comment]
Thanks for the report, @davidwales !  Should be fixed in the next version.
