### ISSUE TITLE
[gzip] Opening a gzip file results in > 100% progress

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#925]
**Small description**
When opening a large gzip'd file the progress % is off. I presume this is due to not knowing ahead of time how large the data is that is being loaded, or maybe because the file is gunziped first, then loaded iteratively?

**Expected result**
Progress should only be between 0% and 100%

**Steps to reproduce with sample data and a .vd**
```
wget https://raw.githubusercontent.com/linuxacademy/content-elastic-log-samples/master/access.log
for _ in {1..100}; do cat access.log >> big_access.txt; done # this just makes a large text file so it's easier to see the bug. This creates a file just under 300mb
gzip big_access.txt
vd big_access.txt.gzip
# now view the progress bar in the bottom right, it will eventually exceed 100%
```

**Comment by saulpw** [comment]
Thanks for the report, @geekscrapy!  Should be fixed now and will be in the next release.
