### ISSUE TITLE
Display pictures

### ISSUE THREAD

**Issue by faaafo** [saulpw/visidata#931]
Would be cool if -given an appropriate terminal- I'd be able to see pictures

| Picture        | Comment           | 
| ------------- |:-------------:|
| ~/foo.jpg      | bar |

**Comment by saulpw** [comment]
Interesting idea, @faaafo !  I've never played with sixels but I hear they're gaining support in the major terminals.  If/when we do start to play with them, showing images would be cool indeed.

Kondo'ed for now.
