### ISSUE TITLE
WSL/Ubuntu Update

### ISSUE THREAD

**Issue by charlie17** [saulpw/visidata#932]
Lowly Windows user here. I have managed to get Ubuntu running via WSL, and Visidata installed/running. However when I launch Visidata it implores me to upgrade to 2.0. How is this done? I have run `sudo apt update` followed by `sudo apt install visidata`. Both run successfully but the message comes back `visidata is already the newest version (1.5-2.1).` I must be missing something basic.

**Comment by anjakefala** [comment]
Hi @charlie17! Thanks for asking.

VisiData 2.2.1 is on its way through the Debian pipeline, but is still in the [testing stage](https://packages.debian.org/it/source/bullseye/visidata).

You can install using [pip](https://www.visidata.org/install/#pip3) as an alternative.
