### ISSUE TITLE
v2.3 no longer uses default terminal colors correctly

### ISSUE THREAD

**Issue by lxcode** [saulpw/visidata#939]
**Small description**

The updates to color handling seem to have made background color handling inconsistent. Part of the terminal is default, part is black.

**Expected result**

The background is entirely default.

**Actual result with screenshot**
<img width="848" alt="2021-04-05_at_11 40 30" src="https://user-images.githubusercontent.com/1959603/113611991-19b10800-9604-11eb-8ba6-bc5cf07866d8.png">

**Steps to reproduce with sample data and a .vd**
Run vd, sans any configuration file, in a terminal with a non-black default color.

**Additional context**
v2.3, macOS 11.2.3, kitty and iTerm2

**Comment by saulpw** [comment]
Thanks for reporting, @lxcode. Ultimately I'd like to deprecate this option completely so I'm thinking the proper answer is to never use the default color.  If anyone has a reason why the default color is useful to them, please speak up!

As a workaround, you can set this option in your visidatarc to its previous default:

    options.use_default_colors = False

**Comment by lxcode** [comment]
I had actually been using use_default_colors = True, because I intentionally have a lower contrast background to lessen eyestrain — FFFFFF on 000000 is pretty searing for me. Most ncurses apps seem to use default out of the box, with mutt being a notable exception.

Could there perhaps at least be an option to set the global background color to default?

**Comment by saulpw** [comment]
Hm, so I guess this has to do more with the background color change, not `use_default_colors`.  I'll dig on it and see what I can come up with.  This may be worthy of a patch release.

**Comment by saulpw** [comment]
Okay, sorry about that.  It should be much better now with the above change.  I've removed the `use_default_colors` option (will give a warning on startup if set); to use the terminal default colors, set `options.color_default=""`.  With this change you can also set it to an explicit fg and bg (e.g. `"253 on 237"` for a less intense white on a lighter black) if you want it to be different from the terminal default.

If you would, please test the latest develop and make sure this works for you; if so, we'll roll it up into 2.3.1 soon.

**Comment by lxcode** [comment]
Yup, looks good. Thanks!
