### ISSUE TITLE
Cannot set key column background color

### ISSUE THREAD

**Issue by wavexx** [saulpw/visidata#94]
I'm experimenting with the terminal default colors. It seems that it's mostly ok, but some elements still use an explicit black background: one example is the current_key_col. On a terminal with a white background, the key column will always have a black background.

And also, I cannot explicitly set the background value. For example, I cannot get "white on red" or similar colors (and no, "reverse red" is not the same, since "reverse red" will use the terminal default's background).

**Comment by saulpw** [comment]
Okay, I changed the background from COLOR_BLACK (which has the same value as A_NORMAL) to -1 when use_default_colors is set.  Please check out the latest develop and see if this fixes this issue for you.
