### ISSUE TITLE
Virtual columns in sqlite files are handled incorrectly which can lead to a column mixup

### ISSUE THREAD

**Issue by dotcs** [saulpw/visidata#945]
**Small description**

[Virtual columns](https://www.sqlite.org/gencol.html) in sqlite files are handled incorrectly which can lead to a column mix-up.

Steps to reproduce:
```console
$ cat <<EOF > sample_data.csv
col1,col2
a,1
b,2
c,3
EOF

$ vd -b sample_data.csv -o sample_data.db
$ sqlite3 sample_data.db "ALTER TABLE sample_data ADD COLUMN test_col1 AS (col1 || col2 )"
$ sqlite3 sample_data.db "ALTER TABLE sample_data ADD COLUMN test_col2; UPDATE sample_data SET test_col2 = 1;"

# For reference: This is the schema of the sqlite database. Note that test_col1 is a virtual (or computed) column.
$ sqlite3 sample_data.db ".schema" 
CREATE TABLE IF NOT EXISTS "sample_data" ("col1" TEXT, "col2" TEXT, test_col1 AS (col1 || col2 ), test_col2);
```

**Expected result**

I use sqlite CLI to show the expected result.

```console
$ sqlite3 -header sample_data.db "SELECT * FROM sample_data"
col1|col2|test_col1|test_col2
a|1|a1|1
b|2|b2|1
c|3|c3|1
```

**Actual result with screenshot**

In visidata this yields to a result where `test_col1` and `test_col2` are mixed. The headline is `test_col2` whereas the data is from `test_col1`.

![screenshot_2021-04-11_13-53-29_169115873](https://user-images.githubusercontent.com/3976183/114303223-5b8ef200-9acd-11eb-83d4-6cee7ab79e2b.png)

**Steps to reproduce with sample data and a .vd**
Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**

```console
$ visidata --version
saul.pw/VisiData v2.2.1

# this also happens with 2.3
$ visidata --version                                              
saul.pw/VisiData v2.3
```

**Comment by saulpw** [comment]
Thanks for the bug report, @dotcs!  The sqlite loader was using `PRAGMA TABLE_INFO` which doesn't include hidden columns, even though `SELECT *` will return them.  The solution is to use `TABLE_XINFO` which does include them.

I also cleaned up the sqlite type parsing, so hopefully that's a bit better too.  Let me know if you come across other issues with either!
