### ISSUE TITLE
[colors] Flashing behavior from colors sheet

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#946]
**Small description**
When opening `open-colors` sheet, colors flash.

**Expected result**
Colors don't flash

**Actual result with screenshot**
https://asciinema.org/a/4iiK7uVOKcb4tlH5LyKw4rdpS

**Steps to reproduce with sample data and a .vd**
run command: open-colors

**Additional context**
Please include the version of VisiData. Latest develop version.

I'm also seeing an issue where on different runs of vd, colorizers don't appear to color cells.  The colorizers are being called, but visidata doesn't colorize any cells.  I don't have a good reproduction yet.  But as part of trying to debug, noticed this odd behavior.  Maybe if this is fixed, the other issue will disappear.

I like the new colors sheet, really like the color swatch.

**Comment by saulpw** [comment]
Hi @frosencrantz, thanks for the report.  This is an artifact of the swatch: basically curses has a limitation of 256 "color pairs" (fg/bg) at one time.  VisiData previously got around this by pre-allocating all 256 terminal colors as foreground colors and always using the same background color (and `reverse` as needed).  Now, though, VisiData allocates color pairs on-demand, which gives us the flexibility to choose fg/bg pairs.

But we still have that 256 color-pair limit, and I decided that it was better for VisiData to clear its cache of color-pairs and start over if it reached that limit (as opposed to causing an error or returning an existing incorrect color).  This works quite well, except in the case that there are actually more than 256 color-pairs on the screen at once, in which case VisiData has to allocate and reset its cache every draw cycle, which is what causes the flickering you see on the colors sheet.  It's trying to draw the existing colors in use plus all 256 colors available, which is more than 256 :)  If you page down once, the flickering should stop.

There are a couple of ways this could be fixed, but we should examine how the colors sheet is used first.  Is it to see the palette of existing colors in use, or a way to explore possible colors that could be used?  Before v2.3, it was the latter, but on a lark in 2.3 I decided to include the current color cache as well.  To be honest, I didn't think anyone but myself used the colors sheet, and I'm now using the DarkDraw colors.ddw for my own color exploration needs.

So I think options are (in order of difficulty):

1. Remove the colors sheet and suggest colors.ddw as an alternative (it's much heavier than the colors sheet though).
2. Revert the colors sheet to not include the current color cache.
3. Display less of the swatch so fewer than 256 colors are on the screen at once.

None of these are too hard, so let me know how you're using the colors sheet and that will help inform which path we should take.

**Comment by frosencrantz** [comment]
I haven't really tried colors.ddw yet.  It looks very nice (colors and organization). I'm not familiar with how to navigate ddw sheets (yet) so that is not a good choice for me currently.

It seems useful to be able to include the current color cache, so it is possible to have some visible debugging of the current color cache.

Maybe option 3 would be the best choice of those.  I do like the color swatch.

I'm fine with the color flashing, but reported it since I was concerned something else might be wrong.  It was easy to demonstrate the color flashing, so started with that. Particularly, since I am having an issue with a custom colorizer I added that only sometimes displays colors. I know it is being called via vd.status calls.  I thought this report might help resolve that issue.  I still need a good way to reproduce the issue causing me problems.


OT: Looking forward to animated help files made via ddw code...  😎

**Comment by saulpw** [comment]
I went with option 3, and only display the swatch for rows that are on the screen already.

**Comment by frosencrantz** [comment]
Thanks, @saulpw !

I did eventually figure out the issue with my custom colorizer, it was my logic error.
