### ISSUE TITLE
Suggestion: `vd --version`

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#95]
It'd be nice to be able to call `vd --version` from the command line. Much like `python --version`, it'd print "VisiData" and the local VisiData version, e.g.:

```sh
$ vd --version
VisiData 0.98.1
```

What do you think? Happy to file a PR, if you'd like.

**Comment by saulpw** [comment]
This will be in 0.99.  Thanks for the suggestion!

**Comment by jsvine** [comment]
Super, and thanks!
