### ISSUE TITLE
Possible bug related to setting replay=True options and vd.cmdlog.rows (v2.3/2.4)

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#952]
Note: I've spent about an hour looking into this, and I still haven't quite grokked it, but will try to explain as much as I understand.

**Small description**

Customizing options (but only those for which `replay=True`) in an options sheet early in a VisiData session prevents some other sheet types from opening.

Specifically:

• Load any file in VisiData
• Before you do anything else, open the global options sheet (`O`)
• In the global options sheet, edit any value for which `replay=True` — `skip` for instance, or `default_width`. (A potential clue: editing non-replay options does not seem to trigger the later error.)
• Quit the global options sheet
• Try opening the local-sheet options sheet (`zO`)

**Expected result**

I would expect the local options sheet to open as normal.

**Actual result with screenshot**

When I do that, I get `AttributeError: 'NoneType' object has no attribute 'append'` in the statusline. Trying to `^E` actually raises the same error. But if instead I first open the Sheets Sheet (after getting the first error) and then running `^E`, I get this stacktrace:

```
Traceback (most recent call last):
  File "[...]/visidata/basesheet.py", line 154, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "[...]/visidata/basesheet.py", line 66, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "options-sheet", line 1, in <module>
    import math
  File "[...]/visidata/extensible.py", line 60, in get_if_not
    setattr(self, name, func(self))
  File "[...]/visidata/metasheets.py", line 16, in optionsSheet
    return OptionsSheet(sheet.name+"_options", source=sheet)
  File "[...]/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  File "[...]/visidata/extensible.py", line 14, in newinit
    oldinit(self, *args, **kwargs)
  File "[...]/visidata/sheets.py", line 202, in __init__
    self.setKeys(self.columns[:self.nKeys])  # initial list of key columns
  File "[...]/visidata/sheets.py", line 512, in setKeys
    vd.addUndo(undoAttrFunc(cols, 'keycol'))
  File "[...]/visidata/undo.py", line 29, in addUndo
    r.undofuncs.append((undofunc, args, kwargs))
AttributeError: 'NoneType' object has no attribute 'append'
```

(Another potential clue: After opening the Sheets Sheet, the bug also seems to vanish; it then becomes possible to open `zO`.)

It does not seem to matter whether you edit first on `O` and then try opening `zO` or vice versa; both seem to lead to this error.

Browsing through the VisiData code, the problem may stem from [`r` in `addUndo` being set to `None`](https://github.com/saulpw/visidata/blob/ed0db17a290d88c12c1d61d764558778a6303107/visidata/undo.py#L19-L29) due to [`vd.cmdlog.rows` being empty in `vd.modifyCommand`](https://github.com/saulpw/visidata/blob/ed0db17a290d88c12c1d61d764558778a6303107/visidata/cmdlog.py#L426-L431). But I don't quite have enough understanding of the internals to figure out what'd cause that, or what the best fix would be.

**Steps to reproduce with sample data and a .vd**

Unfortunately, due to the nature the behavior, I think a `.vd` file won't reproduce this, but steps listed above should do so.

**Additional context**

Bug seems to occur in `v2.3` and `v2.4` but not `v2.2`.

**Comment by anjakefala** [comment]
Thanks for such a detailed bug report + repro @jsvine! It helped me grok this bug really quickly.

`set-option` gets added to cmdlog when a replayable option is applied to a sheet. We were missing the initialising of `undofuncs` in the coded that added that row to the cmdlog. This should now be fixed on `develop`!
