### ISSUE TITLE
docs/customize vdrc.py dict bug

### ISSUE THREAD

**Issue by njthomas** [saulpw/visidata#956]
**when running vdrc.py on docs/customize I get the following bug**

```
Traceback (most recent call last):
  File "./vdrc.py", line 5, in <module>
    for optname, val in sorted(options().items()):
TypeError: 'OptionsObject' object is not callable
```

**Comment by njthomas** [comment]
Adding pull request with patch that fixes this.

**Comment by njthomas** [comment]
Also see #958 for a _somewhat related_ feature request.

**Comment by njthomas** [comment]
Oh, I should have mentioned I was running **Python 3.7.10**.

**Comment by saulpw** [comment]
Now you can save the options sheet directly as `foo.visidatarc` without any additional code.  A stem like `foo` here is required or else `visidatarc` is not recognized as the save filetype; you'll have to move the file to `.visidatarc` manually if you want to use it as-is.  (This is a mild inconvenience but perhaps also a useful safety measure to avoid directly overwriting the existing config file.)  This will be in the next release (2.5).
