### ISSUE TITLE
[docs] move docs/customize vdrc.py functionality into Options Sheet 

### ISSUE THREAD

**Issue by njthomas** [saulpw/visidata#958]
On https://www.visidata.org/docs/customize/, there is a script `vdrc.py` that allows one to dump options into a sample `~./.visidatarc`. 

This functionality should probably be moved into the Options Sheet.

**Comment by saulpw** [comment]
Good idea, @njthomas.  We can convert that code to a `save_visidatarc` function so you can just `Ctrl+S` on the options sheet as always and save as 'sample.visidatarc' if not '~/.visidatarc' itself.

**Comment by saulpw** [comment]
Now you can save the options sheet directly as `foo.visidatarc` without any additional code. A stem like foo here is required or else visidatarc is not recognized as the save filetype; you'll have to move the file to .visidatarc manually if you want to use it as-is. (This is a mild inconvenience but perhaps also a useful safety measure to avoid directly overwriting the existing config file.) This will be in the next release (2.5).
