### ISSUE TITLE
Can use semicolon (;) as column seperator

### ISSUE THREAD

**Issue by BernH4** [saulpw/visidata#960]
I cant use the delimiter ; for csv files: 

I tried `vd -d ";" test.csv`
I tried it on standard csv data with ; as seperator.

Is this a bug or a stupid mistake by me?

Heres a small recording in case it isn't clear: 
https://asciinema.org/a/xDZ4Z0335qZHr3jiEAuHqTv0T

**Comment by saulpw** [comment]
Hi @BernH4, you have to use the `--csv-delimiter ";"` option for csv files.  It's a bit of a wart but not quite a bug.
