### ISSUE TITLE
zy-gzp combination does not work anymore

### ISSUE THREAD

**Issue by sfranky** [saulpw/visidata#961]
**Small description**
When copying a single cell with `zy`, I used to be able to paste on multiple selected cells with `gzp`.
This no longer applies. 

If there was no previous `gzy` content in the clipboard, this error is shown:

```
Traceback (most recent call last):
  File "/home/sfranky/visidata/visidata/basesheet.py", line 154, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/home/sfranky/visidata/visidata/basesheet.py", line 66, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "setcol-clipboard", line 1, in <module>
    import plugins.normcol
TypeError: 'NoneType' object is not iterable
```

If there *is* a `gzy` clipboard content, then this is pasted instead of the single value from `zy`.

**Additional context**
Latest develop commit

**Comment by saulpw** [comment]
Thanks for the report, @sfranky.  This is fixed in develop and will be in the next release.  `gzp` (setcol-clipboard) will paste `None` if nothing is on the clipboard (equivalent to `gzd` (delete-cells).  Please chime in if the alternate behavior (fail with warning) is preferred.

**Comment by sfranky** [comment]
this is perfect! thanks very much!!
