### ISSUE TITLE
no loader for url scheme: postgresql

### ISSUE THREAD

**Issue by zormit** [saulpw/visidata#966]
**Small description**

When attempting to start visidata with
```
vd postgresql:///localdb
```
it fails with
```
Error: no loader for url scheme: postgresql
```

**Expected result**

I would have expected it to work the same way 
```
vd postgres:///localdb
```
works, as [both URL schemes are valid](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING).

P.S.: This is somewhere in between a bug and a feature request. As it's super small and about something existing, I called it a bug. I will raise a PR to fix this shortly.

**Comment by saulpw** [comment]
Thanks for filing and for submitting the PR, @zormit !
