### ISSUE TITLE
sqlite: saving deleted cells does not work

### ISSUE THREAD

**Issue by mattenklicker** [saulpw/visidata#969]
Saving of deleted cells in sqlite columns (without NOT NULL constraint) fails because of missing column info.
I identified [`isChanged`](https://github.com/saulpw/visidata/blob/stable/visidata/modify.py#L154) as possible reason: It gets a NonType exception and returns False which causes the row not to be added in `getDeferredChanges`.

I applied this patch to fix it, but I did not check for any side effects:
```diff
--- a/visidata/modify.py	2021-05-02 16:32:10.812482635 +0200
+++ b/visidata//modify.py	2021-05-02 16:32:03.532482545 +0200
@@ -157,7 +157,7 @@
         row, rowmods = self._deferredMods[self.rowid(row)]
         newval = rowmods[col]
         curval = col.getSourceValue(row)
-        return col.type(newval) != col.type(curval)
+        return (newval is None and curval is not None) or col.type(newval) != col.type(curval)
     except KeyError:
         return False
     except Exception:
```
**Additional context**
VisiData v2.4

**Comment by saulpw** [comment]
Hi @mattenklicker, thanks for filing and digging into this issue!  I think what you suggest makes sense.  I've applied the change to the develop branch and if it doesn't break other cases, it will be in v2.5.
