### ISSUE TITLE
[windows] AttributeError: module 'signal' has no attribute 'SIGTSTP'

### ISSUE THREAD

**Issue by KaviHarjani** [saulpw/visidata#972]
Got this error while trying to start it on windows, anyone else experiencing a similar error?

![image](https://user-images.githubusercontent.com/30836518/117106382-64f23e00-ad9d-11eb-90f4-dceb84b571a3.png)

Comes right after
pip3 install visidata
visidata
![image](https://user-images.githubusercontent.com/30836518/117106457-83f0d000-ad9d-11eb-86af-f2827bdbf1a9.png)

VisiData-2.4

**Comment by saulpw** [comment]
Hi @KaviHarjani, thanks for the report.  What platform are you running on?  It should work in WSL.

**Comment by KaviHarjani** [comment]
Hey @saulpw,

works fine on WSL
The issue occurs on plain Windows 10
Checked on StackOverflow, so...
> SIGALRM is not supported on Windows. https://docs.python.org/2/library/signal.html On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. A ValueError will be raised in any other case

I'm using it on WSL currently, just highlighting the issue with Windows

**Comment by saulpw** [comment]
Ah, Windows isn't officially supported yet.  I've been working on this recently though; you can follow along in the `develop` branch, and look for it in the Microsoft Store soon!

**Comment by Kreijstal** [comment]
I think this is because windows doesnt have a sigtstp. I think this should be easy to fix howerver, check https://github.com/benbaptist/minecraft-wrapper/issues/430#issuecomment-280934514
