### ISSUE TITLE
How to parse csv data piped into VisiData

### ISSUE THREAD

**Issue by gennaro-tedesco** [saulpw/visidata#973]
**Small description**
Visidata does not recognise comma separations by piping data from previous output (`awk`, `grep`, `sed`, `cat`).

**Expected result**
As described [here](https://www.visidata.org/docs/pipes/) and [here](https://www.visidata.org/blog/2020/ten/) I would expect `vd` to format the tabular output correctly.

**Steps to reproduce with sample data and a .vd**
Consider `file.csv`
```
name,pay,hours
Beth,4,0
Dan,3.75,0
Kathy,4,10
Mark,5,20
```
and consider the example
```
awk -F ',' '$3>0' file.csv | vd -f fixed
```
this produces the results as seen below

**Actual result with screenshot**

<img width="246" alt="Screenshot 2021-05-07 at 00 50 02" src="https://user-images.githubusercontent.com/15387611/117374835-31fb9780-aece-11eb-84f6-7e337a5f52d1.png">

whilst I would expect the results to be formatted against the comma.

**Additional context**
I have checked [this](https://github.com/saulpw/visidata/issues/69) and [this](https://github.com/saulpw/visidata/issues/354), which appear to be similar, and it seems that it should just work out of the box.

**Comment by saulpw** [comment]
Hi @gennaro-tedesco.  `-f fixed` is for "fixed-width" text files, where the fields are aligned with spaces.  For this case, you should use `-f csv`, since it's a csv file.  VisiData detects filetype based on file extension, but of course there is no filename associated with stdin so it can't know.
