### ISSUE TITLE
Not able to select comparing dates

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#975]
**Small description**

Hi,
I have this input file

```
id,data
1,2020-12-05
2,2020-07-08
3,2024-12-05
```

I would like to select all rows greater than 2020-08-08, using Python expression.
I set `data` field as date field using `@`, and then `z|`.

My expression is `data > datetime.date(2020,8,8)`.

And I have 0 rows selected

![image](https://user-images.githubusercontent.com/30607/117530546-049e0f00-afde-11eb-9786-a98e5d1dd9cd.png)

**Expected result**

To select 2 rows.

**Additional context**

saul.pw/VisiData v2.5dev

**Comment by frosencrantz** [comment]
I see several issues:
1. `z|` select-expr doesn't show exceptions [code].  It just hides them.
2. If it didn't, you would see an error something like `TypeError: can't compare date to datetime.date`.  Which is confusing, but you would see that the date class is a VisiData class, that subclasses from datetime.datetime.  And Python doesn't allow that comparison.

Some possible things to change would be below. These might not be the right things to do.
1. Don't ignore exceptions from select-expr (e.g. add a vd.exceptionCaught)
2. Rename the Visidata class date to make it clearer it is basically a datetime.
3. Change the Visidata date class to also allow comparisons with datetime.date.

@aborruso,  you could just use `data > datetime.datetime(2020, 8, 8)`


[code]: https://github.com/saulpw/visidata/blob/develop/visidata/selection.py#L88

**Comment by aborruso** [comment]
> @aborruso, you could just use `data > datetime.datetime(2020, 8, 8)`

Great, it works, thank you very much!

My real goal was to select date in the future, and now I know that I can write ` data > datetime.datetime.now()`

**Comment by saulpw** [comment]
Thanks @aborruso for filing this issue, and @frosencrantz for the quick workaround.  I've added specialized comparators for this situation (honestly I don't know why Python datetime.datetime itself doesn't do this automatically).  Note that `visidata.date` is a bit of a misnomer, as @frosencrantz says; it always includes a time as well.  Ideally it would correctly compare partially-specified dates and/or times, such that e.g. `visidata.date("2016-10") == visidata.date("2016-10-29")`, but that is a feature request outside the scope of this bug.

**Comment by aborruso** [comment]
Thank you very much
