### ISSUE TITLE
Impossible to run search & replace starting from an HTML web source

### ISSUE THREAD

**Issue by aborruso** [saulpw/visidata#978]
**Small description**

Hi,
if I open this table

```
vd +:table_2:: "https://gist.githubusercontent.com/aborruso/42dfe3d1ecb6f2aabe5d43d214e41930/raw/2c23ec5c2ddbce91d2f8295d08857138636d3eec/input.html"
```

and run a global search & replace:

- click `gs`, 
- click `gz*` 
- use `a/b` expression

I have this error

![image](https://user-images.githubusercontent.com/30607/117547574-933b7c00-b030-11eb-98c8-8e8c5b0389ce.png)

Is it mandatory to freeze it? If I freeze it, I have no error.

**Additional context**

saul.pw/VisiData v2.5dev

**Comment by saulpw** [comment]
Yes, that's right, the underlying DOM elements are not writable like that, so you have to freeze the sheet (or at least the columns you want to change) first.

**Comment by aborruso** [comment]
> Yes, that's right, the underlying DOM elements are not writable like that, so you have to freeze the sheet (or at least the columns you want to change) first.

How about returning a different error message to the end user? Something like "When you open a table from a web page, it's not writable".

Thank you

**Comment by saulpw** [comment]
@aborruso and @pigreco, has this issue come up more than once for you?  I'd rather fix the single error message that already exists (which is the same for any column that isn't settable), than create a new class of error message for every different unsettable column (there are many dozens).

**Comment by aborruso** [comment]
> @aborruso and @pigreco, has this issue come up more than once for you? I'd rather fix the single error message that already exists (which is the same for any column that isn't settable), than create a new class of error message for every different unsettable column (there are many dozens).

@saulpw  I understand what you say. In the screenshot I sent here there is  `[19x] column cannot be changed | [19x] Media intensitid+Terapia Intensiva column cannot be change gz*`.

If I read this kind of message I think there is an error related to a specific column, related to the data.
I don't think there is a disabled feature.

How about a general message like this (I also talked about it with @pigreco): "These elements are not editable. To do it, create a frozen copy of them"
