### ISSUE TITLE
Feature suggestion: Copying sheets and/or rows to system clipboard

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#98]
Fairly often, I want to copy a VisiData sheet into another document (e.g., an email or a Markdown-formatted file). I could, of course, just save the sheet and then do whatever I want with the saved output. But I think it'd be neat if there were a way to copy the current sheet (or selected rows) to the system clipboard.

It'd be especially neat if the command let you choose how output format (e.g., CSV, fixed-width, Markdown table, reStructuredText, etc.).

But perhaps I'm overlooking simpler solutions?

**Comment by saulpw** [comment]
I think this might be pretty straightforward.  There is already the `gy` (yank rows) command, which copies the rows to an internal clipboard (the same one as `gd`), but it could readily save the rows to the system clipboard in the format given by e.g. `options.clipboard_savetype` (or should it use the existing `filetype`?)

Would `gd` then have to also save to the clipboard, to be consistent with how every other application's cut/copy clipboard is unified?  If so, then this would be a performance issue when just deleting large numbers of rows.

Having an option also means that it would be a lot more keystrokes (= flow disruption) for you to change the savetype, which might not be any faster than your current process.

So maybe instead we should add another command that just saves the rows on the internal clipboard to the system clipboard.  `gp`?  If you want to paste as different formats often enough, we could make `gp` automatically take an input.

Or if we decide that it's okay for "big yank" (`gy`) to defy the laws of software design, we could just make it take an input too.

Do any of these make more or less sense for you?

**Comment by saulpw** [comment]
Put the [contents of this gist](https://gist.github.com/saulpw/e44b0ec096d3110573690bdcb4ba2cd5) into your .visidatarc to get this working for any of the formats VisiData currently supports for saving, which are currently .tsv, .csv, .json, and .html tables.  Saving in other formats would be awesome too, but the savers would have to be written (about 20 lines of code each).  

This overrides the `gy` command.  Let me know how well this works for you; if it seems to make sense, it could go into v1.1.

**Comment by jsvine** [comment]
Thanks, Saul! And really neat that it's so easy to test proposed features with .visidatarc. A couple of thoughts:

- I like the "copy rows to system clipboard as filetype:" prompt, for two reasons: (a) being able to choose the filetype, and (b) getting the chance to cancel the clipboard-writing operation if I invoked it accidentally.

- I like the symmetry of the original `y`/`gy`/`d`/`gd`/`p` commands. Overriding `gy` feels a bit unexpected. Are there other keystrokes assignable to clipboard copy? Maybe `Y`/`gY` or `^Y` (though that'd mean reassigning the Python object command)?

**Comment by saulpw** [comment]
Oh, I like `Y`/`gY`, good idea.  Although, do you ever want to copy just one row like this?  (And if you did, would you want a header row?)

In this case I think we should have `zY` also (yank contents of current cell).  There is currently no `zP` (`P` is "paste before", which doesn't make sense in the single cell case, unless it meant something twisted like "prepend to current cell"); maybe `zP` could be "paste system clipboard into current cell"?

**Comment by jsvine** [comment]
> Although, do you ever want to copy just one row like this?

Rarely.

> (And if you did, would you want a header row?)

Oooh, yes. I  should have mentioned that earlier. I'd almost always want the header.

> In this case I think we should have zY also (yank contents of current cell).

Makes sense.

> maybe zP could be "paste system clipboard into current cell"?

Interesting! I don't have strong opinions about that, though it doesn't seem all that much harder to do `e` + `cmd-V`. (Or maybe there are benefits I'm overlooking?)

**Comment by saulpw** [comment]
Okay, for symmetry, we're going with `Y`/`gY`/`zY` for row/sheet/cell copy.  I agree, that we don't need a separate "paste from system clipboard" (though this does require the small bugfix in 904b6e1cf7fa1c787df15816629182e473e7ff1c to disable the mouse in the line editor, for those of us who click to paste).  This will not be in 1.0, but will be rolled into 1.1.

**Comment by jsvine** [comment]
Super, and thanks!

**Comment by winasforcepta** [comment]
Hi @saulpw , I have a problem with this feature. Currently I use Ubuntu 16.04. This feature require `pbcopy` and as far as I know, there is no pbcopy in ubuntu (I use `xclip` instead). Is there any way to hack this problem? CMIIW.

edit: I got this error message, I hope it will help you
```
FileNotFoundError: [Errno 2] No such file or directory: 'pbcopy'
```

Thanks :)

**Comment by saulpw** [comment]
@winasforcepta Put this in your `.visidatarc`:

        options.clipboard_copy_cmd = 'xclip -selection primary'

**Comment by winasforcepta** [comment]
it's work :smile: 
Thanks so much @saulpw

**Comment by manihamidi** [comment]
> @winasforcepta Put this in your `.visidatarc`:
> 
> ```
>     options.clipboard_copy_cmd = 'xclip -selection primary'
> ```

In case this helps anyone in the future, for me and my Ubuntu 20 `xclip -selection clipboard` is what worked instead (after installing xclip that is).

**Comment by Dyphen** [comment]
I was having trouble getting this to work via WSL2. What ended up working for me was setting `options.clipboard_copy_cmd = clip.exe`.
