### ISSUE TITLE
[FR] Add `--light` theme 

### ISSUE THREAD

**Issue by NightMachinery** [saulpw/visidata#986]
`visidata` is unusable with light themes:
![image](https://user-images.githubusercontent.com/36224762/118823405-35c7ea80-b8ce-11eb-867d-abbd387205f9.png)

I know the colors are customizable, but having to create custom colors for CLI tools doesn't scale well. It would be much better if there was a simple `--light` option that automatically chose suitable colors for light themes.

Another option is to use 24-bit true colors, which do not depend on the terminal's theme.

**Comment by saulpw** [comment]
Hi @NightMachinary, thanks for the request.  It's a good idea, but of course the hard part is choosing the colors.  If you or anyone else has a light theme they want to share, please do!  It wouldn't be difficult at all to add it as a plugin and/or in VisiData itself. 

Kondo'ed for now.
