### ISSUE TITLE
[v2.4] FileProgress in v2.4 breaks opening non-gzip compressed files

### ISSUE THREAD

**Issue by jspatz** [saulpw/visidata#987]
**Small description**

The new FileProgress class meant to accurately track progress for compressed files only works properly with gzipped files.  Opening bz2- or lzma- compressed files results in an error:  `AttributeError: 'FileProgress' object has no attribute 'seekable' `, and fails to open the file.

**Expected result**
Normal opening of `foo.csv.bz2` or `foo.csv.xz` in VisiData.

**Steps to reproduce with sample data and a .vd**
[fail-open-compressed.vd.gz](https://github.com/saulpw/visidata/files/6509255/fail-open-compressed.vd.gz)

**Comment by saulpw** [comment]
Thanks for the report, @jspatz!  This is fixed in develop and hopefully loading progress will be accurate now for both compressed and uncompressed file types.  Will be in 2.5.
