### ISSUE TITLE
[addcol] Ability to add column from derived table (Freq/duplicate)

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#988]
From the discussion in https://github.com/saulpw/visidata/discussions/970.

Saul said it wouldn't be too difficult to add a feature that would allow an added column to be added back to a source sheet.

The FreqTableSheet  already allows edits to existing columns to apply to the source sheet.   After adding a column to a FreqTable or a duplicated sheet (created with `"`), add a direct way to add that column back to the source sheet. Like a `addcol-to-source` command.

There is a workaround by using the join command, but it requires setting up both tables so that they can be joined as wanted.

**Comment by saulpw** [comment]
Hi @frosencrantz, thanks for the request.  Try this in your visidatarc:

```
Sheet.addCommand('', 'addcol-source', 'source.addColumn(copy(cursorCol))')
```

I'll going to put it in mine too and see if I wind up using it.  I'm curious what keybinding you end up using for it and if it works for your use case.

**Comment by geekscrapy** [comment]
I had a usecase for this today and I used the command but I got the following exception in the source sheets' cell :
`AttributeError: 'list' object has no attribute 'sourcerows'`.

My usecase was that I was looking at ssh sessions and calculating the duration of the session using the min+max aggregators in the frequency sheet. I then used `=max-min` on the freq-sheet to get the duration which I wanted to add back to the source sheet.

**Comment by frosencrantz** [comment]
@sualpw Thanks for adding this to vdplus, and sorry for not providing feedback.  Sorry I missed this.

However, this didn't quite solve the itch I had, it seems like this just copies the column, but it doesn't copy the row data, and that is the part that is also very useful to me.  If I added my own notes from the Frequency table it would be useful if those could be pushed back to the source sheet.

**Comment by saulpw** [comment]
Ah, I see.  That's not quite possible, because the "rows" your notes are associated with, are the Frequency rows, not the source rows.  Best idea for this I can think of right now, is to create your new notes column on the source sheet (before freqing), add that column as a key, and `freq-keys`.  Then your edits in that column on the Frequency sheet will be reflected back to the rows on the source sheet.
