### ISSUE TITLE
[curcol] Allow curcol alias for current col to be available in more places.

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#989]
In https://github.com/saulpw/visidata/issues/659 a wish was granted adding the `curcol` alias to addcol-expr. Thank you!

This request is:
Allow the alias to be used in any other commands that reference column names, such as all the expr commands and  `addcol-sh`.

**Comment by saulpw** [comment]
This would be a good feature.  Kondo'ed for now.

**Comment by frosencrantz** [comment]
😞 Oh no!

 saulpw@ What chance does this have getting into VisiData?

Wondering why you decided to move from open to MK’d.  Thanks for keeping it open for as long as you did. I do think this is one of those features that really should be added.  I know I would find very useful, and it would make all the expression/shell commands more consistent.

**Comment by saulpw** [comment]
@frosencrantz It was the realization that I wasn't going to be able to get around to it any time soon, and I wanted to clean up some issues (more MK's are probably coming in a couple weeks).  But interestingly I think the big reason was that it felt too big, and if I thought it was just adding it to `addcol-sh` it might be more likely to happen.  So maybe this should stay closed and #1031 could be re-opened, esp if it would be quite useful for other people too.

**Comment by frosencrantz** [comment]
Thanks for the reply, @saulpw.  Re-opening #1031 is a reasonable next step.  I believe there will be more interest over time to  implement this feature, as users are able to use curcol in more places.

**Comment by saulpw** [comment]
Thanks for your patience, @frosencrantz.  Please let us know if you find other places that could use `curcol`.
