### ISSUE TITLE
[syspaste-cells] Add binding for syspaste-cells 

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#990]
Per https://github.com/saulpw/visidata/discussions/983#discussioncomment-745812

Add binding for `z shift-P` to `syspaste-cells`

Creating a feature request for this.  If it is not useful to create these feature requests from your comments, I won't create these.

**Comment by saulpw** [comment]
Hi @frosencrantz, thank you for helping us keep track of them.  As you can see, development happens in spurts, so when things are moving slowly it's good to make sure they stay visible.  And the more support a particular feature/bug/issue gets the more likely it is to be implemented :)

**Comment by saulpw** [comment]
Okay, I've added a binding for `z Shift+P`, and a new command `gz Shift+P` to paste onto selected rows.
