### ISSUE TITLE
 [json-loader] Value always null if key name contains '.'

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#991]
**Small description**
json-loader incorrectly and silently shows value as null for object keys that contain '.' in name

**Expected result**
Value of key name would not interfere with displaying value. Json key names can contain be any valid string.

**Actual result with screenshot**
Try the reproduce steps.  The cell should have the value 1, but instead shows 'ø'

**Steps to reproduce with sample data and a .vd**
```
echo '{"a.b":1}' | vd -f json 
```
Note cell value is null, no errors.
When loading json dicts are passed wrapped with AttrDict.

**Additional context**
Using latest version of vd from develop.

**Comment by saulpw** [comment]
Thanks for the report, @frosencrantz.  I guess it makes sense but I didn't know anyone used dotted keys in json.  Fixed in develop, will be in 2.5.

**Comment by frosencrantz** [comment]
Thank you, Saul and Anja!  I was surprised by this too.  In data I found this in the keys were actually small phrases and sentences with periods included.
