### ISSUE TITLE
Update status before executing a command to show its longname

### ISSUE THREAD

**Issue by geekscrapy** [saulpw/visidata#996]
I've had a few times when working with large files that I have pressed a key combo and I vd has frozen temporarily while it does whatever I asked it to (the most recent example was to undo a row deletion). At the time I pressed U I didn't know if I had pressed it or not as the terminal had frozen, so I pressed it again. I believe these kind of scenarios could be elevated by doing the following (if they are not done already!):

1. Write the executed command in the status line _before_ running the operation
2. Make sure the command name has successfully been drawn to the screen before running the operation

This would have prevented my double undo situation as I would have noticed that the undo command had already been run

**Comment by saulpw** [comment]
I agree, I think this is a good thing to do in general, but I'm concerned about why the undo was taking so long.  Can you reproduce this?  How large was the dataset/delete?

**Comment by geekscrapy** [comment]
I think this is reproducible, but it'd take some time as the dataset was about 44m rows 😉 I'll take another look at this particular example.

I only deleted a single row from the sheet

**Comment by geekscrapy** [comment]
This was also for a .csv.gz if that makes any difference

**Comment by saulpw** [comment]
Hm, the delete does need to do a linear scan through the rows, but that should be async, and the undo following should be instantaneous.   Please do let me know if you find a repro for this.

**Comment by geekscrapy** [comment]
@saulpw I can repro this:

`base64 /dev/urandom | head -c 1000000000 > file.txt`

*NB need to use gnu base64 as others may not create multiple lines*

This creates a file with the properties:
```bash
$ wc -l file.txt
12987012 file.txt

$ ls file.txt
961M -rw-r--r-- 1 geekscrapy 954M file.txt
```

Now open with `vd file.txt` and let it fully load.

Move down a few rows and delete 2 with `d`.
Now undo with `U`. On my 2014 Mac (personal), this took ~1m-2m to undo...
On my Mac Pro 2019 it took about 40s

So it seems consistent across Mac at least...

**Comment by geekscrapy** [comment]
So I've come up against this again (the main issue) in a slightly different way.
I have a func which cannot be decorated with async+ and I do a `vd.status` to tell the user we are running a blocking call prior to running the blocking code, however I do not see the `vd.status` message.
What would be the best way to verify status has been written to screen? Would it be possible to make the status calls blocking? How much would that break? Or can I maybe compare the count of statuses before and after the call?

**Comment by saulpw** [comment]
`vd.draw()` needs to be called in order for the status to be drawn.  You can do this manually, but it is a *strong* recommendation to find a way to call the blocking function in another thread.  We had this problem with sqlite, as connections can't be shared across threads, and so the sqlite loader has to create a new connection to the database for every query.  It's important that to work around it instead of blocking the main thread; otherwise the action is not even cancelable and might become an unwanted runaway process (even worse than crashing imo).

**Comment by geekscrapy** [comment]
Ok thanks for the info. I actually have to have it in the parent thread (which is actually another curses app) and have it block as it is checking for a valid auth session. If the session is still valid, then it unblocks and vd continues, but if the auth is not valid I need to suspend vd and let the auth flow (from the parent app) run its course (with print statements and user input that uses six.input (don't ask....)).
Thinking about it, I may try and see if I can suspend vd from an async+ thread... I'm pretty sure I tried this though.

**Comment by saulpw** [comment]
This should be fixed now.  Please let me know if it is still not showing the command.
