### ISSUE TITLE
split-col fails with JSON sheets

### ISSUE THREAD

**Issue by jsvine** [saulpw/visidata#997]
**Small description**

When running `split-col` (<kbd>:</kbd>) on a JSON sheet, the command errors out, producing the traceback below:

```
Traceback (most recent call last):
  File "/visidata/lib/python3.8/site-packages/visidata/threads.py", line 215, in _toplevelTryFunc
    t.status = func(*args, **kwargs)
  File "/visidata/lib/python3.8/site-packages/visidata/regex.py", line 71, in addRegexColumns
    vs.addColumnAtCursor(*cols.values())
  File "/visidata/lib/python3.8/site-packages/visidata/sheets.py", line 504, in addColumnAtCursor
    return self.addColumn(*cols, index=index)
TypeError: addColumn() takes 2 positional arguments but 3 were given
```

**Steps to reproduce with sample data and a .vd**

Perhaps faster to reproduce by copy-paste than download-and-.vd:

```sh
echo '[ { "a": "1_2" }, { "a": "3_4" } ]' | vd -f json
```

... followed by <kbd>:</kbd>, and then <kbd>_</kbd> (or really anything) at the `split regex:` prompt.

**Additional context**

Version: v2.4

**Comment by ajkerrigan** [comment]
Hiya @jsvine - #959 should take care of this. The fix seems to be working as expected on develop, and will be included in the next release. If you find anything out of whack though, we can get it sorted out before then :).

**Comment by jsvine** [comment]
Ah, thank you for flagging that and for the fix! I'll close this issue.
